import type { VerifiedRecipe } from "./types.js";

const VERIFIED_AT = "2026-09-14";
const GITHUB_HEADERS = {
  "user-agent": "MISSING/0.2 capability-runtime",
  "x-github-api-version": "2022-11-28",
};

/**
 * Curated Capability Expansion Wave 1.
 *
 * These recipes intentionally use public, credential-free GET surfaces so they
 * remain compatible with replay verification, failover, Kappa economics, and
 * the x402 paid-resolution path. Each recipe is replayed with two distinct
 * inputs by the dedicated capability-wave1-live workflow before merge.
 */
export const WAVE1_VERIFIED_RECIPES: VerifiedRecipe[] = [
  {
    capability: "currency_exchange_rate",
    family: "finance",
    provider: "Frankfurter",
    provider_candidate_id: "wave1_frankfurter_v2_rate",
    recipe_fingerprint: "8ab9a9b72832024c75116322c454f6e021215c8b85a688c4b29158def704de7f",
    method: "GET",
    base_url: "https://api.frankfurter.dev",
    path_template: "/v2/rate/{base_currency}/{quote_currency}",
    path_bindings: {
      base_currency: "$input.base_currency",
      quote_currency: "$input.quote_currency",
    },
    query_bindings: {},
    projection: {
      base_currency: { op: "FIELD", path: "base" },
      quote_currency: { op: "FIELD", path: "quote" },
      rate: { op: "FIELD", path: "rate" },
      date: { op: "FIELD", path: "date" },
    },
    required: ["base_currency", "quote_currency", "rate", "date"],
    example_input: { base_currency: "usd", quote_currency: "eur" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { base_currency: "usd", quote_currency: "eur" },
        { base_currency: "crc", quote_currency: "usd" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://frankfurter.dev/",
    },
  },
  {
    capability: "dns_record_lookup",
    family: "network",
    provider: "Google Public DNS",
    provider_candidate_id: "wave1_google_dns_json",
    recipe_fingerprint: "fb19d3f26dcf0c1ce983316032c12308a49bafaff5d360b356d012cb9f988790",
    method: "GET",
    base_url: "https://dns.google",
    path_template: "/resolve",
    path_bindings: {},
    query_bindings: {
      name: "$input.name",
      type: "$input.type",
    },
    projection: {
      name: { op: "INPUT", name: "name" },
      type: { op: "INPUT", name: "type" },
      status: { op: "FIELD", path: "Status" },
      answers: { op: "FIELD", path: "Answer" },
    },
    required: ["name", "type", "status"],
    example_input: { name: "example.com", type: "A" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { name: "example.com", type: "A" },
        { name: "openai.com", type: "MX" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://developers.google.com/speed/public-dns/docs/doh/json",
    },
  },
  {
    capability: "domain_rdap_metadata",
    family: "network",
    provider: "RDAP.org",
    provider_candidate_id: "wave1_rdap_org_domain",
    recipe_fingerprint: "d66288be5ce1edfda6b3330ba8bd3c35863dcf54a5f10b5944f98f1857497fea",
    method: "GET",
    base_url: "https://rdap.org",
    path_template: "/domain/{domain}",
    path_bindings: { domain: "$input.domain" },
    query_bindings: {},
    static_headers: { "user-agent": "MISSING/0.2 capability-runtime" },
    projection: {
      domain: { op: "INPUT", name: "domain" },
      ldh_name: { op: "FIELD", path: "ldhName" },
      status: { op: "FIELD", path: "status" },
      entities: { op: "FIELD", path: "entities" },
    },
    required: ["domain", "ldh_name"],
    example_input: { domain: "example.com" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { domain: "example.com" },
        { domain: "openai.com" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://about.rdap.org/",
    },
  },
  {
    capability: "npm_package_metadata",
    family: "developer",
    provider: "npm Registry",
    provider_candidate_id: "wave1_npm_registry_latest",
    recipe_fingerprint: "93144dc992f49788e67eeae5aa01aea73bbaeba9e812fc7c93ace3ebed3838e5",
    method: "GET",
    base_url: "https://registry.npmjs.org",
    path_template: "/{package_name}/latest",
    path_bindings: { package_name: "$input.package_name" },
    query_bindings: {},
    projection: {
      package_name: { op: "FIELD", path: "name" },
      version: { op: "FIELD", path: "version" },
      description: { op: "FIELD", path: "description" },
      license: { op: "FIELD", path: "license" },
    },
    required: ["package_name", "version"],
    example_input: { package_name: "express" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { package_name: "express" },
        { package_name: "react" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://registry.npmjs.org/",
    },
  },
  {
    capability: "pypi_package_metadata",
    family: "developer",
    provider: "PyPI",
    provider_candidate_id: "wave1_pypi_json",
    recipe_fingerprint: "239e044e40773aed74e90698af32cf27e42a000397b4db4b2e1e3105acda88fa",
    method: "GET",
    base_url: "https://pypi.org",
    path_template: "/pypi/{package_name}/json",
    path_bindings: { package_name: "$input.package_name" },
    query_bindings: {},
    projection: {
      package_name: { op: "FIELD", path: "info.name" },
      version: { op: "FIELD", path: "info.version" },
      summary: { op: "FIELD", path: "info.summary" },
      requires_python: { op: "FIELD", path: "info.requires_python" },
    },
    required: ["package_name", "version"],
    example_input: { package_name: "requests" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { package_name: "requests" },
        { package_name: "flask" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://docs.pypi.org/api/json/",
    },
  },
  {
    capability: "nuget_package_versions",
    family: "developer",
    provider: "NuGet",
    provider_candidate_id: "wave1_nuget_flat_container",
    recipe_fingerprint: "8290a6137cf5f635d4a0595a5b834395def847b8eb89228dc202db9524ce2f8d",
    method: "GET",
    base_url: "https://api.nuget.org",
    path_template: "/v3-flatcontainer/{package_name}/index.json",
    path_bindings: { package_name: "$input.package_name" },
    query_bindings: {},
    projection: {
      package_name: { op: "INPUT", name: "package_name" },
      versions: { op: "FIELD", path: "versions" },
    },
    required: ["package_name", "versions"],
    example_input: { package_name: "newtonsoft.json" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { package_name: "newtonsoft.json" },
        { package_name: "serilog" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://learn.microsoft.com/en-us/nuget/api/package-base-address-resource",
    },
  },
  {
    capability: "github_repository_metadata",
    family: "developer",
    provider: "GitHub",
    provider_candidate_id: "wave1_github_repo",
    recipe_fingerprint: "30a5ae09e332b554564be08a8cf7cdced23a9eb8e3c37f1ee50037a4754b5c43",
    method: "GET",
    base_url: "https://api.github.com",
    path_template: "/repos/{owner}/{repo}",
    path_bindings: {
      owner: "$input.owner",
      repo: "$input.repo",
    },
    query_bindings: {},
    static_headers: GITHUB_HEADERS,
    projection: {
      full_name: { op: "FIELD", path: "full_name" },
      description: { op: "FIELD", path: "description" },
      default_branch: { op: "FIELD", path: "default_branch" },
      stargazers_count: { op: "FIELD", path: "stargazers_count" },
      forks_count: { op: "FIELD", path: "forks_count" },
    },
    required: ["full_name", "default_branch", "stargazers_count", "forks_count"],
    example_input: { owner: "openai", repo: "openai-python" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { owner: "openai", repo: "openai-python" },
        { owner: "nodejs", repo: "node" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://docs.github.com/en/rest/repos/repos#get-a-repository",
    },
  },
  {
    capability: "github_user_metadata",
    family: "developer",
    provider: "GitHub",
    provider_candidate_id: "wave1_github_user",
    recipe_fingerprint: "2f4d411a7128df568f67978c3065cc2c990106320e0b109e926bd20704b966a7",
    method: "GET",
    base_url: "https://api.github.com",
    path_template: "/users/{username}",
    path_bindings: { username: "$input.username" },
    query_bindings: {},
    static_headers: GITHUB_HEADERS,
    projection: {
      login: { op: "FIELD", path: "login" },
      name: { op: "FIELD", path: "name" },
      public_repos: { op: "FIELD", path: "public_repos" },
      followers: { op: "FIELD", path: "followers" },
    },
    required: ["login", "public_repos", "followers"],
    example_input: { username: "torvalds" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { username: "torvalds" },
        { username: "sindresorhus" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://docs.github.com/en/rest/users/users#get-a-user",
    },
  },
  {
    capability: "postal_code_location_metadata",
    family: "geography",
    provider: "Zippopotam.us",
    provider_candidate_id: "wave1_zippopotam_postal",
    recipe_fingerprint: "891f46cbd63712955eb1e3323a64855e411c680a0db772843ddd9984b00ee626",
    method: "GET",
    base_url: "https://api.zippopotam.us",
    path_template: "/{country_code}/{postal_code}",
    path_bindings: {
      country_code: "$input.country_code",
      postal_code: "$input.postal_code",
    },
    query_bindings: {},
    projection: {
      postal_code: { op: "FIELD", path: "post code" },
      country: { op: "FIELD", path: "country" },
      country_code: { op: "FIELD", path: "country abbreviation" },
      place_name: { op: "FIELD", path: "places.0.place name" },
      state: { op: "FIELD", path: "places.0.state" },
      latitude: { op: "FIELD", path: "places.0.latitude" },
      longitude: { op: "FIELD", path: "places.0.longitude" },
    },
    required: ["postal_code", "country", "country_code", "place_name"],
    example_input: { country_code: "us", postal_code: "90210" },
    verification: {
      status: "replay_verified",
      source: "product_live",
      verification_inputs: [
        { country_code: "us", postal_code: "90210" },
        { country_code: "us", postal_code: "10001" },
      ],
      verified_at: VERIFIED_AT,
      evidence_url: "https://docs.zippopotam.us/docs/v1/",
    },
  },
];
