import {describe,expect,it} from "vitest";
import {qualifyRequestHypotheses5B19,qualificationDeterminism5B19} from "../src/experiment5b19Qualification.js";

const slot=(id:string,name:string,where:"path"|"query"="path")=>({id,name,in:where,required:true,auth_like:false,literals:[]});
const hyp=(id:string,path:string,input:string,slotName:string,proof_type="5b12_documentary_request_template",where:"path"|"query"="path")=>({id,source_operation_id:`op-${id}`,origin:"https://api.example.test",full_path:path,proof_type,evidence_ids:["e1"],source_urls:["https://docs.example.test"],slots:[slot("s1",slotName,where)],input_bindings:{[input]:"s1"},literal_bindings:{},score:1,concrete_relation:false});
const ev=(text:string)=>[{evidence_id:"e1",provider_candidate_id:"p",requested_url:"https://docs.example.test",resolved_url:"https://docs.example.test",verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"text/html",body_fingerprint:"fp",text,state:"ok" as const}];
const empty=()=>new Map<string,any>();

describe("Experiment 5B19 evidence qualification",()=>{
 it("admits native machine-contract operations with lexical bindings",()=>{const h:any=hyp("h1","/country/{country_code}","country_code","country_code","4w_linked_native_openapi_operation"),native=new Map([[h.id,{source_document_evidence_id:"e1",operation_pointer:"#/paths/x/get",method:"GET",contract_url:"https://api.example.test/openapi.json"}]]),args:any={hypotheses:[h],evidence:ev("country API operation"),intent:"Get country metadata",inputNames:["country_code"],nativeProofById:native,collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:empty()},r=qualifyRequestHypotheses5B19(args);expect(r.hypotheses).toHaveLength(1);expect(r.witnesses.get(h.id)?.qualification_class).toBe("machine_contract");expect(r.witnesses.get(h.id)?.ranking_bonus).toBe(false);expect(qualificationDeterminism5B19(args).ok).toBe(true)});
 it("rejects URL-presence-only documentary requests",()=>{const h:any=hyp("h2","/words/{word}","word","word"),docs=ev('<a href="https://api.example.test/words/{word}">docs</a>'),w=new Map([[h.id,{source_evidence_id:"e1"}]]),r=qualifyRequestHypotheses5B19({hypotheses:[h],evidence:docs,intent:"Return word definition",inputNames:["word"],nativeProofById:empty(),collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:w});expect(r.hypotheses).toHaveLength(0);expect(r.metrics.rejectedNoStrongProvenance5b19).toBe(1)});
 it("admits an explicit local GET example with strong generic-query anchors",()=>{const h:any=hyp("h3","/search?q={word}","word","q","5b6_query_oriented_parameter_local","query"),docs=ev("Dictionary API reference\nGET /search?q={word}\nReturn the English word definition."),w=new Map([[h.id,{source_evidence_id:"e1"}]]),r=qualifyRequestHypotheses5B19({hypotheses:[h],evidence:docs,intent:"Return English word definition",inputNames:["word"],nativeProofById:empty(),collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:w});expect(r.hypotheses).toHaveLength(1);expect(r.witnesses.get(h.id)?.qualification_class).toBe("documented_local_http_example");expect(r.witnesses.get(h.id)?.input_bindings[0].binding_class).toBe("generic_query_local_anchors")});
 it("rejects broad identity-like parameter compatibility",()=>{const h:any=hyp("h4","/countries/v5?memberships.g7=1","country_code","memberships.g7","5b6_query_oriented_parameter_local","query"),docs=ev("Country API reference\nGET /countries/v5?memberships.g7=1\nReturn country metadata."),w=new Map([[h.id,{source_evidence_id:"e1"}]]),r=qualifyRequestHypotheses5B19({hypotheses:[h],evidence:docs,intent:"Get country metadata",inputNames:["country_code"],nativeProofById:empty(),collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:w});expect(r.hypotheses).toHaveLength(0);expect(r.metrics.rejectedWeakInputBinding5b19).toBe(1);expect(r.metrics.broadIdentityOnlyBindingAdmissions5b19).toBe(0)});
});
