import {describe,expect,it} from "vitest";
import {buildFiveB15Report} from "../src/experiment5b15Decision.js";

const integrity:any={ok:true,base_sha:"base",prereg_commit:"pre",workload_commit:"work",recipe_fingerprint_set_matches:true,changed_input_workload_matches:true,recipe_fingerprint_set_fingerprint:"recipes",changed_input_workload_fingerprint:"inputs",semantic_verifier_unchanged:true,semantic_verifier_source_fingerprint:"verifier"};
const good:any={frozen_recipe_count:7,recipe_fingerprint_set_fingerprint:"recipes",changed_input_workload_fingerprint:"inputs",attempt1_records:7,attempt1_all_recorded_before_retry:true,non_retryable_retried_violations:0,maximum_attempts_used:3,total_http_attempts:9,logical_execution_attempts:9,request_fingerprint_mismatch_violations:0,changed_input_mutation_violations:0,retry_budget_violations:0,recipe_mutation_violations:0,semantic_verifier_source_fingerprint:"verifier",final_replay_successes:7,final_replay_rate:1,documentary_recipe_count:1,documentary_recipe_final_replay_successes:1,documentary_lineage_preserved:true,replay_catalog_fetches:0,replay_reranker_calls:0,replay_documentation_fetches:0,replay_synthesis_calls:0,replay_recovery_fetches:0,recipe_generation_calls:0,auth_like_rendered_requests:0,wrong_task_probe_attempts:0,stochastic_decisions:0,holdout_accesses:0};

describe("Experiment 5B15 formal decision",()=>{
 it("requires every frozen recipe to replay successfully",()=>{const report=buildFiveB15Report({...good},integrity,[],"a","b");expect(report.decision).toBe("GO_5B15_DETERMINISTIC_REPLAY_RESILIENCE");expect(report.gates.final_replay_rate_95).toBe(true)});
 it("keeps 6 of 7 as REASSESS",()=>{const report=buildFiveB15Report({...good,final_replay_successes:6,final_replay_rate:6/7},integrity,[],"a","b");expect(report.decision).toBe("REASSESS_5B15_DETERMINISTIC_REPLAY_RESILIENCE");expect(report.gates.final_replay_rate_95).toBe(false)});
 it("rejects retrying a non-retryable failure",()=>{const report=buildFiveB15Report({...good,non_retryable_retried_violations:1},integrity,[],"a","b");expect(report.decision).toBe("REASSESS_5B15_DETERMINISTIC_REPLAY_RESILIENCE");expect(report.gates.retries_only_after_eligible_failure).toBe(false)});
 it("rejects request or changed-input mutation",()=>{const request=buildFiveB15Report({...good,request_fingerprint_mismatch_violations:1},integrity,[],"a","b");const input=buildFiveB15Report({...good,changed_input_mutation_violations:1},integrity,[],"a","b");expect(request.decision).toBe("REASSESS_5B15_DETERMINISTIC_REPLAY_RESILIENCE");expect(input.decision).toBe("REASSESS_5B15_DETERMINISTIC_REPLAY_RESILIENCE")});
});
