import {describe,expect,it} from "vitest";
import {buildDocumentaryRequestHypotheses5B12} from "../src/experiment5b12Documentary.js";
const provider:any={case_id:"x",candidate_id:"p",name:"Example",start_url:"https://docs.example.test/"};
function ev(text:string):any{return {evidence_id:"p-e01",provider_candidate_id:"p",requested_url:"https://docs.example.test/api",resolved_url:"https://docs.example.test/api",verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"text/html",body_fingerprint:"fp",text,state:"ok"}}
describe("Experiment 5B12 pre-binding documentary request extraction",()=>{
 it("preserves documented query geometry and binds only the evidenced query slot",()=>{const c:any={input_names:["show_name"],build:{show_name:"Alpha"},intent:"find television show metadata"},r=buildDocumentaryRequestHypotheses5B12([ev("Search shows using https://api.example.test/singlesearch/shows?q=:query and receive JSON show metadata")],provider,c);expect(r.hypotheses).toHaveLength(1);const h=r.hypotheses[0];expect(h.origin).toBe("https://api.example.test");expect(h.full_path).toContain("/singlesearch/shows?q=:query");expect(h.slots.find((s:any)=>s.in==="query")?.name).toBe("q");expect(Object.keys(h.input_bindings)).toEqual(["show_name"]);expect(h.full_path).not.toContain("Alpha")});
 it("rejects off-provider documentary requests",()=>{const c:any={input_names:["name"],build:{name:"Alpha"},intent:"find item"},r=buildDocumentaryRequestHypotheses5B12([ev("GET https://outside.other.test/search?q=:query")],provider,c);expect(r.hypotheses).toHaveLength(0);expect(r.metrics.documentaryTemplatesRejectedScope5b12).toBeGreaterThan(0)});
 it("keeps fixed query values while binding one variable query slot",()=>{const c:any={input_names:["title"],build:{title:"Alpha"},intent:"search title"},r=buildDocumentaryRequestHypotheses5B12([ev("Search title: https://api.example.test/search?format=json&title=:title")],provider,c);expect(r.hypotheses).toHaveLength(1);const h=r.hypotheses[0];expect(Object.keys(h.literal_bindings)).toHaveLength(1);expect(h.input_bindings.title).toBeTruthy();expect(r.witnesses.get(h.id)?.variable_slots[0].in).toBe("query")});
 it("does not turn a query example into a path mutation",()=>{const c:any={input_names:["title"],build:{title:"Alpha"},intent:"search title"},r=buildDocumentaryRequestHypotheses5B12([ev("Search title with https://api.example.test/search?title=Girls")],provider,c);expect(r.hypotheses).toHaveLength(1);const h=r.hypotheses[0];expect(h.full_path.startsWith("/search?")).toBe(true);expect(h.full_path).not.toContain("{title}");expect(h.slots.some((s:any)=>s.in==="query"&&s.name==="title")).toBe(true)});
});
