import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import {deriveDistinctiveTaskAnchors4W,distinctiveAnchorMatch4W,rankOperation4W,solveFeasibleBindings4W} from "../src/experiment4wBinding.js";
import {buildSchemaResolverPayload4W,schemaFieldCandidates4W,validateSchemaResolverOutput4W,verifySchemaRoleWitness4W} from "../src/experiment4wSchemaWitness.js";
import {responseUsable4V,semanticErrorEnvelope4V} from "../src/experiment4vResponse.js";
import {deriveExperiment4wSource} from "../src/experiment4wDerivation.js";
import {sha4u} from "../src/experiment4uOpenApi.js";
import type {P1ProbeProof,P1RequestSlot} from "../src/experiment4ap1Model.js";

const slots=(defs:any[]):P1RequestSlot[]=>defs.map((p,i)=>({id:`p${i}`,name:p.name,in:p.in||"query",required:p.in==="path"||!!p.required,auth_like:!!p.auth_like,literals:(p.literals||[]).map((value:string,j:number)=>({id:`l${i}_${j}`,value}))}));
const solve=(inputNames:string[],params:any[],intent:string,required:string[],root:any,op:any,path:string)=>solveFeasibleBindings4W({inputNames,params,slots:slots(params),intent,required,root,op,path});
function proof(fields:any[]):P1ProbeProof{return {hypothesis:{id:"h",source_operation_id:"o",origin:"https://example.invalid",full_path:"/search",proof_type:"4w_linked_native_openapi_operation",evidence_ids:["e"],source_urls:["https://example.invalid/spec"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:false},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://example.invalid/search",requested_at:"now",final_url:"https://example.invalid/search",content_type:"application/json",response_body_fingerprint:"b",schema_fingerprint:"s",observed_fields:fields,observed_path_count:fields.length,bytes:1,error:null}}}

describe("Experiment 4W feasibility-constrained binding",()=>{
 it("selects sole required generic q instead of weak optional code overlap",()=>{const ps=[{name:"q",in:"query",required:true},{name:"country",in:"query",required:false,description:"Optional country code filter"}],r=solve(["postal_code"],ps,"Find postal records",["postal_code","country_name"],{info:{title:"Postal records service"}},{summary:"Find postal records"},"/search");expect(r.bindings?.postal_code).toBe("p0");expect(r.evidence[0].binding_kind).toBe("generic_required_fallback");expect(r.metrics.optionalWeakBindingSuppressed4w).toBeGreaterThan(0);expect(r.metrics.assignmentFeasible4w).toBeGreaterThan(0)});
 it("rejects an infeasible assignment that leaves a required slot unbound",()=>{const ps=[{name:"q",in:"query",required:true},{name:"accession",in:"query",required:false}],r=solve(["accession"],ps,"protein accession lookup",["accession","protein_label"],{info:{title:"Protein records"}},{summary:"protein accession lookup"},"/lookup");expect(r.bindings).toBeNull();expect(r.metrics.assignmentInfeasibleRequiredSlots4w).toBeGreaterThan(0)});
 it("rejects generic id fallback without a distinctive task anchor in the contract",()=>{const ps=[{name:"id",in:"path",required:true}],r=solve(["accession"],ps,"protein accession metadata",["accession","protein_label"],{info:{title:"Sports statistics"}},{summary:"job status",description:"Get asynchronous job status"},"/jobs/{id}");expect(r.bindings).toBeNull();expect(r.metrics.genericFallbackAnchorRejects4w).toBeGreaterThan(0)});
 it("admits generic fallback when a distinctive task anchor is actually documented",()=>{const ps=[{name:"q",in:"query",required:true}],r=solve(["accession"],ps,"protein accession metadata",["accession","protein_label"],{info:{title:"Protein knowledge service"}},{summary:"Search protein accession records"},"/search");expect(r.bindings?.accession).toBe("p0");expect(r.distinctiveAnchors.matched).toContain("protein");expect(r.metrics.genericFallbackAnchorAccepts4w).toBeGreaterThan(0)});
 it("does not treat weak token code alone as semantic role evidence",()=>{const ps=[{name:"country",in:"query",required:false,description:"country code filter"}],r=solve(["postal_code"],ps,"lookup postal record",["postal_code"],{info:{title:"Postal records"}},{summary:"lookup"},"/lookup");expect(r.bindings).toBeNull();expect(r.metrics.weakTokenOnlyBindingsRejected4w).toBeGreaterThan(0)});
 it("accepts exact strong local role binding without generic fallback",()=>{const ps=[{name:"accession",in:"query",required:true}],r=solve(["accession"],ps,"retrieve protein record",["accession"],{info:{title:"Unrelated title"}},{summary:"record"},"/record");expect(r.bindings?.accession).toBe("p0");expect(r.evidence[0].binding_kind).toBe("exact_parameter_role")});
 it("rejects ambiguous complete assignments instead of guessing",()=>{const ps=[{name:"x",in:"query",description:"protein accession"},{name:"y",in:"query",description:"protein accession"}],r=solve(["accession"],ps,"protein accession",["label"],{info:{title:"Protein"}},{summary:"protein"},"/search");expect(r.bindings).toBeNull();expect(r.metrics.assignmentAmbiguousRejects4w).toBe(1)});
 it("derives distinctive anchors while removing structural boilerplate",()=>{const a=deriveDistinctiveTaskAnchors4W("Given a public machine-readable API operation for a protein accession identifier",["accession"],["name"]);expect(a).toContain("protein");expect(a).toContain("accession");expect(a).not.toContain("api");expect(a).not.toContain("identifier")});
 it("ranks feasible distinctive operations above generic weak ones",()=>{const strong=rankOperation4W({bindingConfidence:80,intentScore:210,responseCoverage:1,requiredParams:1,totalParams:2,genericFallbacks:1,matchedAnchors:2}),weak=rankOperation4W({bindingConfidence:80,intentScore:10,responseCoverage:0,requiredParams:1,totalParams:1,genericFallbacks:1,matchedAnchors:0});expect(strong).toBeGreaterThan(weak)});
});

describe("Experiment 4W closed-world schema resolver",()=>{
 it("builds candidates only from documented fields that were observed live",()=>{const p=proof([{id:"f",path:"0.sub",leaf:"sub",tokens:["sub"],sample_type:"string",sample_value:"Example Country",build_value_relations:[]}]),root={components:{}},op={responses:{"200":{description:"Search results",content:{"application/json":{schema:{type:"array",items:{type:"object",properties:{sub:{type:"string",description:"human-readable country label"},ghost:{type:"string",description:"not observed"}}}}}}}}},c=schemaFieldCandidates4W(root,op,p);expect(c).toHaveLength(1);expect(c[0].observed_path).toBe("0.sub");expect(JSON.stringify(c)).not.toContain("Example Country")});
 it("keeps resolver payload free of observed runtime values",()=>{const payload=buildSchemaResolverPayload4W("country metadata",["country_name"],[{candidate_id:"c1",schema_path:"sub",observed_path:"0.sub",property_name:"sub",property_title:"",property_description:"country label",documented_examples:[],enclosing_schema_name:"",response_description:"results",observed_type:"string"}]);expect(JSON.stringify(payload)).not.toContain("provider");expect(JSON.stringify(payload)).not.toContain("domain");expect(JSON.stringify(payload)).not.toContain("case_id")});
 it("rejects an invented closed-world candidate",()=>{const c=[{candidate_id:"c1",schema_path:"sub",observed_path:"0.sub",property_name:"sub"}],v=validateSchemaResolverOutput4W({mappings:[{output_role:"country_name",candidate_id:"invented",confidence:.99}]},["country_name"],c);expect(v.mappings).toHaveLength(0);expect(v.metrics.schemaRoleResolverRejectedInventedPath4w).toBe(1)});
 it("rejects any attempt by resolver to generate a literal value",()=>{const c=[{candidate_id:"c1",schema_path:"sub",observed_path:"0.sub",property_name:"sub"}],v=validateSchemaResolverOutput4W({mappings:[{output_role:"country_name",candidate_id:"c1",confidence:.99,value:"invented"}]},["country_name"],c);expect(v.mappings).toHaveLength(0);expect(v.metrics.schemaRoleResolverValueGenerationRejects4w).toBe(1)});
 it("accepts a high-confidence closed-world field selection and verifies frozen witness",()=>{const p=proof([{id:"f",path:"0.sub",leaf:"sub",tokens:["sub"],sample_type:"string",sample_value:"X",build_value_relations:[]}]),c=[{candidate_id:"c1",schema_path:"sub",observed_path:"0.sub",property_name:"sub",property_title:"",property_description:"country label",enclosing_schema_name:"",response_description:"results"}],v=validateSchemaResolverOutput4W({mappings:[{output_role:"country_name",candidate_id:"c1",confidence:.95}]},["country_name"],c);expect(v.mappings).toHaveLength(1);const w={spec_fingerprint:"s",operation_pointer:"#/paths/x/get",response_schema_fingerprint:"r",mappings:v.mappings,semantic_evidence_fingerprint:"e",resolver_output_fingerprint:sha4u(v.mappings)};expect(verifySchemaRoleWitness4W(w,p)).toBe(true);w.mappings[0].observed_path="invented";expect(verifySchemaRoleWitness4W(w,p)).toBe(false)});
 it("retains semantic error-envelope protection",()=>{expect(semanticErrorEnvelope4V({error:"invalid"},0)).toBe(true);expect(responseUsable4V({transport2xx:true,structured:true,body:{error:"invalid"},groundedRequired:0,schemaWitnessAvailable:false}).usable).toBe(false);expect(responseUsable4V({transport2xx:true,structured:true,body:{data:"ok",warning:"stale"},groundedRequired:1,schemaWitnessAvailable:false}).usable).toBe(true)});
});

describe("Experiment 4W derivation integrity",()=>{
 it("derives the complete 4W benchmark source",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4wSource(src);expect(out).toContain('experiment:"4W"');expect(out).toContain("GO_4W_FEASIBILITY_CONSTRAINED_BINDING_DISTINCTIVE_SEMANTIC_GATE");expect(out).toContain("nativeOperationUsableStructured2xx4w");expect(out).toContain("schemaRoleResolverCalls4w")});
 it("contains no benchmark-provider or answer hardcodes in 4W runtime files",async()=>{const files=["experiment4wBinding.ts","experiment4wNativeOperation.ts","experiment4wSchemaWitness.ts","experiment4wPlanner.ts","experiment4wContract.ts"],text=(await Promise.all(files.map(f=>readFile(new URL(`../src/${f}`,import.meta.url),"utf8")))).join("\n");expect(text).not.toMatch(/postalcodes|balldontlie|P69905|P68871|90210|protein_identifier_metadata|postal_code_location/i)});
 it("computes provider-blind distinctive overlap mechanically",()=>{const m=distinctiveAnchorMatch4W("chemical element symbol metadata",["symbol"],["element_label"],{info:{title:"Chemical element data"}},{summary:"lookup by symbol"},"/elements/{symbol}",[{name:"symbol",in:"path"}]);expect(m.matched).toContain("chemical");expect(m.matched).toContain("element")});
});
