import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import type {P1ProbeProof} from "../src/experiment4ap1Model.js";
import {applyResponseRoleWitness5B,buildResponseResolverPayload5B,deriveEntityCouplingWitness5B,outputCoverage5B,responseGroundedCandidates5B,validateResponseResolverOutput5B,verifyEntityCouplingReplay5B,verifyEntityCouplingWitness5B} from "../src/experiment5bResponse.js";
import {deriveExperiment5bSource} from "../src/experiment5bDerivation.js";
import {buildFiveBReport,type FiveBIntegrity} from "../src/experiment5bHarness.js";
import {FIVE_A_CASES,fiveAWorkloadFingerprint} from "../src/experiment5aCore.js";

function proof(fields:any[]):P1ProbeProof{return {hypothesis:{id:"h",source_operation_id:"o",origin:"https://example.invalid",full_path:"/resource",proof_type:"test",evidence_ids:["e"],source_urls:["https://example.invalid/spec"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:false},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://example.invalid/resource",requested_at:"now",final_url:"https://example.invalid/resource",content_type:"application/json",response_body_fingerprint:"b",schema_fingerprint:"s",observed_fields:fields.map((f,i)=>({id:`f${i}`,tokens:String(f.leaf||"").toLowerCase().split(/[_-]/),build_value_relations:[],sample_type:typeof f.sample_value,path:f.path,leaf:f.leaf,sample_value:String(f.sample_value)})),observed_path_count:fields.length,bytes:1,error:null}}}
const field=(path:string,leaf:string,sample_value:any)=>({path,leaf,sample_value});

describe("Experiment 5B output-aware operation ranking",()=>{
 it("ranks a response documenting username/title above stats-only output",()=>{const profile={responses:{"200":{description:"player profile",content:{"application/json":{schema:{type:"object",properties:{username:{type:"string"},title:{type:"string"}}}}}}}},stats={responses:{"200":{description:"player statistics",content:{"application/json":{schema:{type:"object",properties:{chess_blitz:{type:"object"},chess_rapid:{type:"object"}}}}}}}};expect(outputCoverage5B(profile,["username","title"]).score).toBeGreaterThan(outputCoverage5B(stats,["username","title"]).score)});
 it("does not let generic id/name alone create strong distinctive coverage",()=>{const c=outputCoverage5B({responses:{"200":{content:{"application/json":{schema:{properties:{id:{type:"string"},name:{type:"string"}}}}}}}},["id","name"]);expect(c.strong_matches).toBe(0);expect(c.weak_exact_matches).toBeGreaterThan(0)});
});

describe("Experiment 5B response-grounded closed world",()=>{
 it("builds candidates from observed paths without runtime sample values",()=>{const p=proof([field("data.records.0.name","name","example.com"),field("data.records.0.data","data","1.2.3.4")]),root={components:{}},op={responses:{"200":{content:{"application/json":{schema:{type:"object",properties:{data:{type:"object",properties:{records:{type:"array",items:{type:"object",properties:{name:{type:"string",description:"DNS owner name"},data:{type:"string",description:"record data"}}}}}}}}}}}}},c=responseGroundedCandidates5B(root,op,p);expect(c.map(x=>x.observed_path)).toContain("data.records.0.name");expect(JSON.stringify(c)).not.toContain("example.com");expect(JSON.stringify(c)).not.toContain("1.2.3.4")});
 it("resolver payload contains paths/schema semantics but not sample values",()=>{const payload=buildResponseResolverPayload5B("dns answer",["answer_name"],[{observed_path:"records.0.name",leaf:"name",observed_type:"string",property_name:"name",property_title:"",property_description:"owner name",enclosing_schema_name:"Record",response_description:"answers"}]);expect(JSON.stringify(payload)).toContain("records.0.name");expect(JSON.stringify(payload)).not.toContain("example.com")});
 it("rejects invented paths and generated values",()=>{const c=[{candidate_id:"c",observed_path:"rows.0.name",leaf:"name"}];const invented=validateResponseResolverOutput5B({mappings:[{output_role:"name",observed_path:"rows.1.name",confidence:.99}]},["name"],c),literal=validateResponseResolverOutput5B({mappings:[{output_role:"name",observed_path:"rows.0.name",confidence:.99,value:"invented"}]},["name"],c);expect(invented.mappings).toHaveLength(0);expect(invented.metrics.responseGroundedInventedPathRejects5b).toBe(1);expect(literal.mappings).toHaveLength(0);expect(literal.metrics.responseGroundedValueGenerationRejects5b).toBe(1)});
 it("applies only frozen closed-world mappings",()=>{expect(applyResponseRoleWitness5B({}, {mappings:[{output_role:"address",observed_path:"rows.0.data"}]})).toEqual({address:{op:"FIELD",path:"rows.0.data"}})});
});

describe("Experiment 5B entity coupling",()=>{
 it("accepts singleton entity with input echo and metadata fields",()=>{const p=proof([field("name","name","pikachu"),field("id","id",25),field("height","height",4)]),projection={name:{op:"INPUT",name:"pokemon_name"},id:{op:"FIELD",path:"id"},height:{op:"FIELD",path:"height"}},r=deriveEntityCouplingWitness5B({inputNames:["pokemon_name"],input:{pokemon_name:"pikachu"},projection,proof:p});expect(r.ok).toBe(true);expect(r.witness.input_witnesses[0].observed_path).toBe("name");expect(verifyEntityCouplingWitness5B(r.witness,{inputNames:["pokemon_name"],input:{pokemon_name:"pikachu"},projection,proof:p})).toBe(true)});
 it("accepts array entity when echo and selected output share the same row",()=>{const p=proof([field("rows.0.key","key","abc-123"),field("rows.0.label","label","Alpha")]),projection={key:{op:"INPUT",name:"resource_id"},label:{op:"FIELD",path:"rows.0.label"}},r=deriveEntityCouplingWitness5B({inputNames:["resource_id"],input:{resource_id:"abc-123"},projection,proof:p});expect(r.ok).toBe(true);expect(r.witness.entity_scope).toBe("rows.0")});
 it("rejects response-level query echo combined with unrelated first result row",()=>{const p=proof([field("query.term","term","1342"),field("items.0.title","title","Unrelated")]),projection={id:{op:"INPUT",name:"book_id"},title:{op:"FIELD",path:"items.0.title"}},r=deriveEntityCouplingWitness5B({inputNames:["book_id"],input:{book_id:1342},projection,proof:p});expect(r.ok).toBe(false);expect(r.metrics.inputDerivedOutputCouplingRejects5b).toBeGreaterThan(0)});
 it("rejects cross-row projection",()=>{const p=proof([field("rows.0.key","key","abc-123"),field("rows.1.label","label","Wrong row")]),projection={key:{op:"INPUT",name:"resource_id"},label:{op:"FIELD",path:"rows.1.label"}},r=deriveEntityCouplingWitness5B({inputNames:["resource_id"],input:{resource_id:"abc-123"},projection,proof:p});expect(r.ok).toBe(false)});
 it("accepts composite owner/repository identity in one singleton field",()=>{const p=proof([field("full_name","full_name","torvalds/linux"),field("default_branch","default_branch","master")]),projection={full_name:{op:"FIELD",path:"full_name"},default_branch:{op:"FIELD",path:"default_branch"}},r=deriveEntityCouplingWitness5B({inputNames:["owner","repository"],input:{owner:"torvalds",repository:"linux"},projection,proof:p});expect(r.ok).toBe(true);expect(r.witness.input_witnesses).toHaveLength(2)});
 it("re-verifies frozen witness against changed replay input with no LLM",()=>{const p=proof([field("name","name","first"),field("value","value","X")]),projection={name:{op:"INPUT",name:"query_name"},value:{op:"FIELD",path:"value"}},r=deriveEntityCouplingWitness5B({inputNames:["query_name"],input:{query_name:"first"},projection,proof:p});expect(r.ok).toBe(true);expect(verifyEntityCouplingReplay5B(r.witness,["query_name"],{query_name:"second"},{name:"second",value:"Y"})).toBe(true);expect(verifyEntityCouplingReplay5B(r.witness,["query_name"],{query_name:"second"},{name:"wrong",value:"Y"})).toBe(false)});
});

function integrity():FiveBIntegrity{return {ok:true,base_sha:"03d0ec9fcf50b3ba72f98b99130c301044383a56",prereg_commit:"ca88bb261c12a5ac83aac3ad83ae67cdd486cf52",head_sha:"head",base_is_ancestor:true,changed_files:[],unexpected_files:[],first_5b_commit:"ca88bb261c12a5ac83aac3ad83ae67cdd486cf52",prereg_unchanged:true,workload_fingerprint:fiveAWorkloadFingerprint(),runtime_provider_url_literals:0,errors:[]}}
function syntheticRaw(n:number){const picked:any[]=[];const fam=new Set<string>();for(const c of FIVE_A_CASES){if(picked.length>=n)break;if(!fam.has(c.family)){fam.add(c.family);picked.push(c)}}for(const c of FIVE_A_CASES){if(picked.length>=n)break;if(!picked.includes(c))picked.push(c)}const ids=new Set(picked.map(c=>c.case_id)),caseEvidence=FIVE_A_CASES.map(c=>({case_id:c.case_id,family:c.family,success:ids.has(c.case_id)?{provider:"x"}:null,elapsed_ms:1000})),recipes=picked.map((c,i)=>({case_id:c.case_id,provider_start_url:`https://provider${i}.example/docs`,request_first_5b:i<2,response_role_witness_5b:i===0?{mappings:[{output_role:"x",observed_path:"x"}],resolver_output_fingerprint:"f"}:null,entity_coupling_witness_5b:{witness_fingerprint:"e"}})),replay=picked.map(c=>({case_id:c.case_id,success:true})),rerankEvidence=FIVE_A_CASES.map(c=>({case_id:c.case_id}));return {decision:"engine",fingerprint:"engine",caseEvidence,recipes,replay,rerankEvidence,synthesisEvidence:[{requestFirstProbeCalls5b:2,requestFirstConfirmedRecipes5b:2,responseGroundedResolverCalls5b:1,responseGroundedMappingsAccepted5b:1,entityCouplingValidationSuccesses5b:n}],metrics:{total_llm_cost_usd:.1,replay_deltas:{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,schema_probe_calls:0},authLikeRenderedRequests:0,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,entityIncompatibleStructuralProbeAttempts:0,executedTraceOriginDriftRejects:0,executedTraceRequestMutationRejects:0,nonAuthRequestTextMutations:0,operationExternalRefFetches4u:0,validatorGraphMismatchRejects:0,duplicateProbeNetworkFetches:0,duplicateAcquisitionNetworkFetches:0,duplicateSpecProbeNetworkFetches:0}}}

describe("Experiment 5B decision and derivation",()=>{
 it("requires the original six-of-eighteen threshold under stricter coupling",()=>{expect(buildFiveBReport(syntheticRaw(6),integrity()).decision).toBe("GO_5B_REQUEST_FIRST_RESPONSE_GROUNDED_ENTITY_COUPLED");expect(buildFiveBReport(syntheticRaw(5),integrity()).decision).toBe("REASSESS_5B_REQUEST_FIRST_RESPONSE_GROUNDED_ENTITY_COUPLED")});
 it("derives a 5B engine that persists and replays both witnesses",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment5bSource(src);expect(out).toContain('from "./experiment5bPlanner.js"');expect(out).toContain('from "./experiment5bContract.js"');expect(out).toContain('results/experiment-5b-engine');expect(out).toContain("entity_coupling_witness_5b");expect(out).toContain("verifyEntityCouplingReplay5B")});
 it("keeps runtime implementation free of development case/provider hardcodes",async()=>{const files=["experiment5bResponse.ts","experiment5bNativeOperation.ts","experiment5bPlanner.ts","experiment5bContract.ts"],text=(await Promise.all(files.map(f=>readFile(new URL(`../src/${f}`,import.meta.url),"utf8")))).join("\n");expect(text).not.toMatch(/pokeapi|dictionaryapi|orbitalwiki|crossref|pokemon_name_metadata|dns_a_record_metadata|chess_player_metadata|public_domain_book_metadata/i)});
 it("caps request-first continuation at two operation probes",async()=>{const text=await readFile(new URL("../src/experiment5bPlanner.ts",import.meta.url),"utf8");expect(text).toContain("Math.min(2,native.hypotheses.length)");expect(text).not.toContain("Math.min(3,native.hypotheses.length)")});
});
