import {describe,expect,it} from "vitest";
import {buildFiveB19Report} from "../src/experiment5b19Decision.js";
import {loadFiveB19Workload} from "../src/experiment5b19Workload.js";

const integrity:any={ok:true,base_sha:"base",prereg_commit:"pre",workload_commit:"work",runtime_provider_url_literals:0,runtime_provider_name_hardcoding:0,runtime_case_family_hardcoding:0};
function fixture(){const w=loadFiveB19Workload(),unhealthy=w.primaries.find(x=>x.unhealthy_after_5b15)!,other=w.primaries.find(x=>x.family!==unhealthy.family)!,mk=(p:any,n:number)=>({family:p.family,case_id:p.case_id,primary_recipe_fingerprint:p.primary_recipe_fingerprint,provider_start_url:`https://alternate-${n}.example.test`,recipe_fingerprint:`recipe-${n}`,evidence_qualification_witness_5b19:{qualification_fingerprint:`q-${n}`},first_verification:{requested_at:"a"},confirmation_verification:{requested_at:"b"},changed_input_replay:{success:true}}),recipes=[mk(unhealthy,1),mk(other,2)],caseEvidence=w.primaries.map(p=>({family:p.family,case_id:p.case_id,selected:w.candidates.filter(c=>c.case_id===p.case_id).sort((a,b)=>a.selected_position-b.selected_position).map(c=>({candidate_id:c.candidate_id,selected_position:c.selected_position})),attempts:[],success:recipes.find(r=>r.case_id===p.case_id)?{recipe_fingerprint:recipes.find(r=>r.case_id===p.case_id)!.recipe_fingerprint}:null})),audits=w.candidates.map(c=>({case_id:c.case_id,provider_candidate_id:c.candidate_id,ordinary_fetches:4,reserved_recovery_fetches:4,total_acquisition_fetches:8})),qualificationAudit5b19=w.candidates.map((c,i)=>({case_id:c.case_id,provider_candidate_id:c.candidate_id,raw_request_hypotheses:i<2?2:0,admitted_request_hypotheses:i<2?1:0,rejected_request_hypotheses:i<2?1:0,rejected_no_strong_provenance:i<2?1:0,rejected_weak_input_binding:0,admitted_machine_contract:i===0?1:0,admitted_structured_collection:i===1?1:0,admitted_executed_trace:0,admitted_documented_local_http:0,url_presence_only_admissions:0,broad_identity_only_binding_admissions:0,qualification_nondeterminism_violations:0,qualification_ranking_bonus_uses:0,qualification_beam_entries:i<2?1:0,beam_entries_without_qualification_witness:0,probed_with_qualification_witness:i<2?1:0,probed_without_qualification_witness:0,qualification_fingerprint:i<2?`fp-${i}`:null})),raw:any={fingerprint:"engine",metrics:{catalogIdentityResolutionFetches5b18:1,identityResolutionFailures5b18:0,attemptOrderingViolations5b18:0,attemptedProviders5b18:21,broadRetrievalCalls5b18:0,equivalenceRerankerCalls5b18:0,secondaryProviderRerankerCalls5b18:0,newProviderSelectionCalls5b18:0,manualProviderSubstitutions5b18:0,ordinaryReserveBorrowingViolations5b18:0,totalFetchBudgetViolations5b18:0,reservedRecoveryOrderingNondeterminismViolations5b18:0,total_llm_cost_usd:.1,mean_llm_cost_per_qualifying_alternate_usd:.05,authLikeRenderedRequests5b18:0,wrongTaskProbeAttempts5b18:0,replay_deltas:{catalog_fetches:0,broad_retrieval_calls:0,equivalence_reranker_calls:0,secondary_reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0,qualification_audits:0}},caseEvidence,recipes,replay:recipes.map(r=>({case_id:r.case_id,success:true})),providerFetchAudit5b18:audits,qualificationAudit5b19};return {w,raw,unhealthy}}

describe("Experiment 5B19 formal decision",()=>{
 it("permits GO only for qualified multi-family replayable alternates including unhealthy coverage",()=>{const {w,raw}=fixture(),report=buildFiveB19Report(raw,integrity,w);expect(report.decision).toBe("GO_5B19_EVIDENCE_QUALIFIED_EXECUTABLE_REQUEST_INDUCTION");expect(Object.values(report.gates).every(Boolean)).toBe(true)});
 it("rejects any beam or probed request without a qualification witness",()=>{const {w,raw}=fixture();raw.qualificationAudit5b19[0].beam_entries_without_qualification_witness=1;raw.qualificationAudit5b19[0].probed_without_qualification_witness=1;const report=buildFiveB19Report(raw,integrity,w);expect(report.gates.every_beam_request_qualified).toBe(false);expect(report.gates.every_probed_request_qualified).toBe(false);expect(report.decision).toContain("REASSESS")});
 it("rejects URL-presence-only, broad-identity-only, or ranking-bonus admissions",()=>{const {w,raw}=fixture();raw.qualificationAudit5b19[0].url_presence_only_admissions=1;raw.qualificationAudit5b19[0].broad_identity_only_binding_admissions=1;raw.qualificationAudit5b19[0].qualification_ranking_bonus_uses=1;const report=buildFiveB19Report(raw,integrity,w);expect(report.gates.url_presence_only_admissions_zero).toBe(false);expect(report.gates.broad_identity_only_binding_admissions_zero).toBe(false);expect(report.gates.qualification_ranking_bonus_zero).toBe(false)});
 it("rejects missing unhealthy coverage and replay-time qualification work",()=>{const {w,raw,unhealthy}=fixture();raw.recipes=raw.recipes.filter((x:any)=>x.case_id!==unhealthy.case_id);raw.replay=raw.replay.filter((x:any)=>x.case_id!==unhealthy.case_id);raw.metrics.replay_deltas.qualification_audits=1;const report=buildFiveB19Report(raw,integrity,w);expect(report.gates.every_unhealthy_primary_covered).toBe(false);expect(report.gates.replay_discovery_cognitive_qualification_zero).toBe(false);expect(report.decision).toContain("REASSESS")});
});
