import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import type {DocEvidence} from "../src/experiment3wCore.js";
import type {Provider4A} from "../src/experiment4aContract.js";
import {buildGatedQueryHypotheses5B8,querySemanticGateDeterminism5B8} from "../src/experiment5b8Gate.js";

const provider:Provider4A={case_id:"npm_package_metadata",candidate_id:"synthetic_provider",name:"Synthetic API",start_url:"https://docs.example.test/api"};
function ev(id:string,text:string):DocEvidence{return {evidence_id:id,provider_candidate_id:provider.candidate_id,requested_url:`https://docs.example.test/${id}`,resolved_url:`https://docs.example.test/${id}`,verified_at:"now",status:200,content_type:"text/html",body_fingerprint:`fp_${id}`,text,state:"ok"}}

describe("Experiment 5B8 role-segmented typed query gate",()=>{
 it("accepts an entity-coupled package query with compatible parameter semantics",()=>{const text=`<h2>Package metadata</h2><p>GET https://api.example.test/package?package_name=example</p><p>package_name: npm package name to retrieve</p><pre>{"name":"example","version":"1.0.0"}</pre>`,r=buildGatedQueryHypotheses5B8([ev("e1",text)],provider);expect(r.hypotheses.length).toBeGreaterThan(0);const a=r.audits.find(x=>x.decision==="ACCEPT");expect(a).toBeTruthy();expect(a?.matched_entity_anchor_fingerprints.length).toBeGreaterThan(0);expect(a?.input_parameter_types.some(x=>x.compatibility!=="conflict"&&x.compatibility!=="ambiguous")).toBe(true)});
 it("does not let output vocabulary such as version establish entity identity",()=>{const text=`<h2>Version search</h2><p>GET https://api.example.test/search?q=example</p><p>q: version string used for search</p><pre>{"version":"1.0.0","name":"x"}</pre>`,r=buildGatedQueryHypotheses5B8([ev("e1",text)],provider);expect(r.hypotheses).toHaveLength(0);expect(r.audits.some(x=>x.decision==="REJECT")).toBe(true)});
 it("rejects an explicitly URL-typed query parameter for a package-name input",()=>{const text=`<h2>Package page inspector</h2><p>GET https://api.example.test/inspect?q=example</p><p>q: URL to inspect for a package page</p><pre>{"name":"x","version":"1"}</pre>`,r=buildGatedQueryHypotheses5B8([ev("e1",text)],provider);expect(r.hypotheses).toHaveLength(0);expect(r.audits.some(x=>x.reason==="parameter_type_conflict")).toBe(true);expect(r.metrics.queryParameterTypeConflictRejects5b8).toBeGreaterThan(0);expect(r.metrics.queryParameterTypeExampleValueUses5b8).toBe(0)});
 it("transfers specialized action semantics only from the same exact query operation",()=>{const local=`<h2>Package query</h2><p>GET https://api.example.test/card?package_name=example</p><p>package_name: package name</p><pre>{"name":"x","version":"1"}</pre>`,same=`<h2>Preview package card</h2><p>GET https://api.example.test/card?package_name=demo</p><p>package_name: package name. Preview a package card.</p>`,r=buildGatedQueryHypotheses5B8([ev("e1",local),ev("e2",same)],provider);expect(r.metrics.queryExactOperationTransfersAccepted5b8).toBeGreaterThan(0);expect(r.metrics.queryExactOperationTransferredActionAnchors5b8).toBeGreaterThan(0);expect(r.audits.some(x=>x.specialized_action_conflicts.includes("preview")&&x.decision==="REJECT")).toBe(true)});
 it("does not transfer specialized semantics from a sibling route",()=>{const local=`<h2>Package metadata</h2><p>GET https://api.example.test/package?package_name=example</p><p>package_name: package name</p><pre>{"name":"x","version":"1"}</pre>`,sibling=`<h2>Preview package</h2><p>GET https://api.example.test/preview?package_name=demo</p><p>package_name: package name. Preview card.</p>`,r=buildGatedQueryHypotheses5B8([ev("e1",local),ev("e2",sibling)],provider),a=r.audits.find(x=>x.decision==="ACCEPT");expect(a).toBeTruthy();expect(a?.specialized_action_conflicts).toEqual([])});
 it("persists complete ACCEPT and REJECT audits",()=>{const good=`<p>GET https://api.example.test/package?package_name=example</p><p>package_name: package name</p><pre>{"name":"x","version":"1"}</pre>`,bad=`<p>GET https://api.example.test/inspect?q=example</p><p>q: URL to inspect for package preview</p><pre>{"name":"x","version":"1"}</pre>`,r=buildGatedQueryHypotheses5B8([ev("e1",good),ev("e2",bad)],provider);expect(r.audits.length).toBeGreaterThan(0);expect(r.metrics.querySemanticAuditRows5b8).toBe(r.audits.length);for(const a of r.audits){expect(a.hypothesis_fingerprint).toBeTruthy();expect(a.intent_segmentation_fingerprint).toBeTruthy();expect(a.exact_operation_identity_fingerprint).toBeTruthy();expect(a.gate_fingerprint).toBeTruthy()}});
 it("is deterministic for identical task metadata and evidence",()=>{const text=`<p>GET https://api.example.test/package?package_name=example</p><p>package_name: package name</p><pre>{"name":"x","version":"1"}</pre>`;expect(querySemanticGateDeterminism5B8([ev("e1",text)],provider).ok).toBe(true)});
});

describe("Experiment 5B8 runtime neutrality",()=>{
 it("contains no development provider/case/endpoint hardcodes",async()=>{const files=["experiment5b8Gate.ts","experiment5b8PlannerDerivation.ts","experiment5b8Derivation.ts"],text=(await Promise.all(files.map(f=>readFile(new URL(`../src/${f}`,import.meta.url),"utf8")))).join("\n");expect(text).not.toMatch(/arxiv\.org|nvd\.nist|tvmaze|openlibrary|chess\.com|warnely|ipwhois|linkpreview|magnuscarlsen|cve_vulnerability_metadata|arxiv_preprint_metadata|dns_a_record_metadata|public_domain_book_metadata|gene_identifier_metadata/i)});
 it("does not inspect build, replay or expected values",async()=>{const text=await readFile(new URL("../src/experiment5b8Gate.ts",import.meta.url),"utf8");expect(text).not.toContain("c.build");expect(text).not.toContain("c.replay");expect(text).not.toContain("expected")});
});
