import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {fieldSemanticallyGrounded4S,inputSemanticallyGrounded4S,rowLabelSemanticallyGrounded4S,semanticRoleCompatible4S} from "../src/experiment4sGrounding.js";
import {extractLinkedContractCandidates4S,linkedSpecSummary4S} from "../src/experiment4sLinked.js";
import {deterministicPartialProjection4S} from "../src/experiment4sCore.js";
import {summarizeRelational4O} from "../src/experiment4oRelational.js";
import {executeProgram} from "../src/experiment3xCore.js";
import {deriveExperiment4sSource} from "../src/experiment4sDerivation.js";
function hyp(){return {id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/x/{vin}",proof_type:"4n_executed_trace_documented_role_path",evidence_ids:["e"],source_urls:["https://api.example.test/x/a"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true}}
function field(id:string,path:string,leaf:string,tokens:string[]=[]){return {id,path,leaf,tokens,sample_type:"string",sample_value:"x",build_value_relations:[]}}
function proof(fields:any[]){return {hypothesis:hyp(),record:{hypothesis_id:"h",disposition:"success",requested_url:"https://api.example.test/x/a",requested_at:new Date().toISOString(),final_url:"https://api.example.test/x/a",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:fields,observed_path_count:fields.length,bytes:100,error:null}} as any}
describe("4S linked contracts and semantic output grounding",()=>{
 it("grounds common provider-blind wrappers",()=>{expect(semanticRoleCompatible4S("category","strCategory")).toBe(true);expect(semanticRoleCompatible4S("version","latest")).toBe(true)});
 it("rejects semantically unrelated URL as category",()=>{expect(fieldSemanticallyGrounded4S("category",field("u","url","url",["url"]) as any)).toBe(false)});
 it("rejects meal input as category but preserves name identity",()=>{expect(inputSemanticallyGrounded4S("category","meal_name")).toBe(false);expect(inputSemanticallyGrounded4S("name","meal_name")).toBe(true)});
 it("rejects vin as make",()=>{expect(inputSemanticallyGrounded4S("make","vin")).toBe(false)});
 it("exact Make label is grounded and NCSA Make is not exact role",()=>{expect(rowLabelSemanticallyGrounded4S("make","Make")).toBe(true);expect(semanticRoleCompatible4S("make","NCSA Make")).toBe(true)});
 it("locks identity and grounded category field",()=>{const p=proof([field("cat","meals.0.strCategory","strCategory",["str","category"])]),d=deterministicPartialProjection4S(p,null,["meal_name"],["name","category"]);expect(d.unresolved).toEqual([]);expect(d.projection.name).toEqual({op:"INPUT",name:"meal_name"});expect(d.projection.category).toEqual({op:"FIELD",path:"meals.0.strCategory"})});
 it("does not lock ungrounded category field",()=>{const d=deterministicPartialProjection4S(proof([field("u","url","url",["url"])]),null,["meal_name"],["name","category"]);expect(d.projection.name).toEqual({op:"INPUT",name:"meal_name"});expect(d.unresolved).toEqual(["category"])});
 it("keeps exact relational Make over NCSA Make",()=>{const body={Results:[{Variable:"NCSA Make",Value:"OTHER"},{Variable:"Make",Value:"HONDA"}]},s=summarizeRelational4O(body),d=deterministicPartialProjection4S(proof([]),s,["vin"],["vin","make"]);expect(d.unresolved).toEqual([]);expect((d.projection.make as any).label_value).toBe("Make");expect(executeProgram(d.projection as any,body,{vin:"ABC"})).toEqual({vin:"ABC",make:"HONDA"})});
 it("discovers only explicitly linked same-provider contracts",()=>{const e:any=[{evidence_id:"e1",resolved_url:"https://docs.example.test/guide",content_type:"text/html",state:"ok",text:'<a href="/openapi.json">OpenAPI</a><a href="https://evil.test/swagger.json">Swagger</a>'}],x=extractLinkedContractCandidates4S(e,"https://docs.example.test");expect(x.map(v=>v.target_url)).toEqual(["https://docs.example.test/openapi.json"])});
 it("summarizes GET operations from linked OpenAPI",()=>{const s=JSON.parse(linkedSpecSummary4S({openapi:"3.0.0",servers:[{url:"https://api.example.test"}],paths:{"/products/{code}":{get:{parameters:[{name:"code",in:"path",required:true}],responses:{"200":{description:"ok"}}}}}}));expect(s.operations).toHaveLength(1);expect(s.operations[0].path).toBe("/products/{code}")});
 it("keeps 4S implementation provider blind",async()=>{const src=(await Promise.all(["experiment4sGrounding.ts","experiment4sLinked.ts","experiment4sLinkedFetch.ts","experiment4sCore.ts","experiment4sPlanner.ts","experiment4sContract.ts"].map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/nhtsa|vpic\.|openfoodfacts|themealdb|cocktaildb|metmuseum|registry\.npmjs/i)});
 it("derives exact frozen 4R base and non-vacuous 4S gates",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4sSource(src);expect(out).toContain('base_sha:"24916e2a83428588f8dea779a8e34589814619ea"');expect(out).toContain("GO_4S_LINKED_MACHINE_READABLE_CONTRACTS_SEMANTIC_OUTPUT_GROUNDING");expect(out).toContain("linked_contract_confirmed_recipe");expect(out).toContain("semantic_output_grounding_integrity");expect(out).toContain("rerankConcurrencyLimit4p=3")});
 it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4sSource(src),r=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4s.ts"});expect((r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
