import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {prepareRequestGraph4J,rebuildRequestGraph4J,pruneAuthQueryPreserving4J,isAuthName4J,codeConcatTemplates4J,targetCompatible4J} from "../src/experiment4jRequest.js";
import {deriveExperiment4jSource} from "../src/experiment4jDerivation.js";
const ev=(text:string)=>({evidence_id:"ev4j",provider_candidate_id:"synthetic",requested_url:"https://docs.example.test/reference",resolved_url:"https://docs.example.test/reference",verified_at:new Date().toISOString(),status:200,content_type:"text/html",body_fingerprint:"fp4j",text,state:"ok"} as any);
async function graph(text:string,caseId:string){return prepareRequestGraph4J([ev(text)],caseId,new RecoveryLedger())}
describe("4J role-complete structural binding",()=>{
 it("preserves and compiles npm placeholder",async()=>{const g=await graph('<h2>Package metadata</h2><code>GET https://api.example.test/{package}</code>',"npm_package_metadata");const h=g.hypotheses.find(x=>x.full_path.includes("{package}"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{package_name:"lodash"})).toContain("/lodash")});
 it("preserves and compiles Met-style object placeholder",async()=>{const g=await graph('<h2>Artwork object metadata</h2><code>GET https://api.example.test/objects/{objectID}</code>',"artwork_object_metadata");const h=g.hypotheses.find(x=>x.full_path.includes("{objectID}"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{object_id:436121})).toContain("/436121")});
 it("binds generic code only with barcode description support",async()=>{const g=await graph('<h2>Product lookup</h2><p>Path parameter <b>code</b>: the barcode of the product to fetch.</p><code>GET https://api.example.test/product/{code}</code>',"food_barcode_metadata");expect(g.metrics.roleAcceptedGenericPlaceholderByDescription).toBeGreaterThan(0);expect(g.hypotheses.some(h=>h.full_path.includes("{code}"))).toBe(true)});
 it("rejects generic code without barcode or input description support",async()=>{const g=await graph('<h2>Product lookup</h2><p>Path parameter code.</p><code>GET https://api.example.test/product/{code}</code>',"food_barcode_metadata");expect(g.metrics.roleRejectedNoDescriptionSupport).toBeGreaterThan(0);expect(g.hypotheses.length).toBe(0)});
 it("reconstructs a VIN code-concatenation request role",async()=>{const text='<h2>Vehicle VIN decode</h2><pre>tempCall &lt;- paste0(&quot;https://api.example.test/api/vehicles/DecodeVinValues/&quot;, VINin, &quot;?format=json&quot;)</pre>';expect(codeConcatTemplates4J(text,"vin")[0]?.template).toContain("{vin}");const g=await graph(text,"vin_vehicle_metadata");expect(g.metrics.roleAcceptedCodeConcat).toBeGreaterThan(0);expect(g.hypotheses.some(h=>h.full_path.includes("{vin}"))).toBe(true)});
 it("rejects repeated concrete build values as ambiguous",async()=>{const vin="1HGCM82633A004352",g=await graph(`<h2>Vehicle VIN decode</h2><code>GET https://api.example.test/vehicle/${vin}/compare/${vin}</code>`,"vin_vehicle_metadata");expect(g.metrics.roleRejectedAmbiguous).toBeGreaterThan(0);expect(g.metrics.roleAcceptedUniqueBuildValue).toBe(0)});
 it("does not bind a build value occurring only in the host",async()=>{const g=await graph('<h2>Vehicle VIN decode</h2><code>GET https://1HGCM82633A004352.example.test/vehicle/result</code>',"vin_vehicle_metadata");expect(g.metrics.roleAcceptedUniqueBuildValue).toBe(0);expect(g.hypotheses.length).toBe(0)});
 it("rejects character task against books target",async()=>{const g=await graph('<h2>Books</h2><p>Path parameter id identifies a book.</p><code>GET https://api.example.test/books/{id}</code>',"fictional_character_metadata");expect(g.metrics.structuralTargetRejected).toBeGreaterThan(0);expect(g.hypotheses.length).toBe(0);expect(targetCompatible4J("fictional_character_metadata","/books/{id}")).toBe(false)});
 it("accepts character task against characters target",async()=>{const g=await graph('<h2>Characters</h2><p>Path parameter id identifies a character.</p><code>GET https://api.example.test/characters/{id}</code>',"fictional_character_metadata");expect(g.metrics.structuralTargetAccepted).toBeGreaterThan(0);expect(g.hypotheses.length).toBeGreaterThan(0);expect(targetCompatible4J("fictional_character_metadata","/characters/{id}")).toBe(true)});
 it("surgically removes optional auth and preserves non-auth text",()=>{const before="/product/{code}?format=json&x-api-key=abc&lang=en",after=pruneAuthQueryPreserving4J(before);expect(after).toBe("/product/{code}?format=json&lang=en");expect(after).toContain("{code}")});
 it("independently rejects auth-like slot missed by old classifier",async()=>{expect(isAuthName4J("x-api-key")).toBe(true);const g=await graph('<h2>Package metadata</h2><code>GET https://api.example.test/{package}?x-api-key={package}</code>',"npm_package_metadata");expect(g.metrics.roleRejectedAuthLike+g.metrics.finalAuthCandidatesRejected).toBeGreaterThan(0);expect(g.probe_packet.length).toBe(0)});
 it("blocks required auth before rendering",async()=>{const g=await graph('<h2>Package metadata</h2><p>An API key is required for this endpoint.</p><code>GET https://api.example.test/{package}</code>',"npm_package_metadata");expect(g.metrics.requiredAuthSlotsBlocked).toBeGreaterThan(0);expect(g.probe_packet.length).toBe(0)});
 it("rebuilds the identical 4J graph and exposes only the 4J prefix",async()=>{const docs=[ev('<h2>Package metadata</h2><code>GET https://api.example.test/{package}</code>')],p=await prepareRequestGraph4J(docs,"npm_package_metadata",new RecoveryLedger()),r=rebuildRequestGraph4J(docs,"npm_package_metadata"),src=await readFile(new URL("../src/experiment4jContract.ts",import.meta.url),"utf8");expect(r.graph_fingerprint).toBe(p.graph_fingerprint);expect(src).toContain('prefix="4J_ROLE_COMPLETE_STRUCTURAL_BINDING:"');expect(src).not.toContain('prefix="4I_STRUCTURAL_IDENTIFIER_ROLE:"')});
 it("contains no provider/domain/endpoint seed literals",async()=>{const src=(await readFile(new URL("../src/experiment4jRequest.ts",import.meta.url),"utf8"))+(await readFile(new URL("../src/experiment4jPlanner.ts",import.meta.url),"utf8"));expect(src).not.toMatch(/openfoodfacts|nhtsa|vpic|metmuseum|registry\.npmjs|thecocktaildb|themealdb/i)});
 it("derives exact 4I merge base and 4J decision strings",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4jSource(src);expect(out).toContain('base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"');expect(out).toContain("GO_4J_ROLE_COMPLETE_STRUCTURAL_BINDING");expect(out).toContain("REASSESS_4J_ROLE_COMPLETE_STRUCTURAL_BINDING")});
});
