import {describe,expect,it} from "vitest";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {classifyFailure,validateIntegrationContractR} from "../src/experiment3yirCore.js";

describe("Experiment 3Y-I-R",()=>{
 it("allows provider parameter names to differ from canonical input names",()=>{const l=new RecoveryLedger(),p={case_id:"pokemon_metadata",candidate_id:"p",name:"P",start_url:"https://pokeapi.co"},docs:any[]=[{evidence_id:"e",provider_candidate_id:"p",requested_url:p.start_url,resolved_url:p.start_url,verified_at:new Date().toISOString(),status:200,content_type:"text/plain",body_fingerprint:"x",text:"GET https://pokeapi.co/api/v2/pokemon/{id_or_name}. Response fields id and name.",state:"ok"}],c={case_id:"pokemon_metadata",provider_candidate_id:"p",decision:"COMPILE",method:"GET",base_url:"https://pokeapi.co",path_template:"/api/v2/pokemon/{id_or_name}",path_bindings:{id_or_name:"$input.pokemon_name"},query_bindings:{},output_paths:{id:"id",name:"name"},evidence_ids:["e"],reason:"x"};expect(validateIntegrationContractR(c,p,docs,l).errors).toEqual([]);});
 it("still rejects unknown canonical inputs",()=>{const l=new RecoveryLedger(),p={case_id:"pokemon_metadata",candidate_id:"p",name:"P",start_url:"https://pokeapi.co"},docs:any[]=[{evidence_id:"e",provider_candidate_id:"p",requested_url:p.start_url,resolved_url:p.start_url,verified_at:new Date().toISOString(),status:200,content_type:"text/plain",body_fingerprint:"x",text:"GET https://pokeapi.co/api/v2/pokemon/{id_or_name}. Response fields id and name.",state:"ok"}],c={case_id:"pokemon_metadata",provider_candidate_id:"p",decision:"COMPILE",method:"GET",base_url:"https://pokeapi.co",path_template:"/api/v2/pokemon/{id_or_name}",path_bindings:{id_or_name:"$input.not_real"},query_bindings:{},output_paths:{id:"id",name:"name"},evidence_ids:["e"],reason:"x"};expect(validateIntegrationContractR(c,p,docs,l).errors).toContain("invalid_input_source:id_or_name");});
 it("classifies external failures explicitly",()=>{expect(classifyFailure("http_404",404)).toBe("FIXTURE_STALE");expect(classifyFailure("auth_required",401)).toBe("PROVIDER_INELIGIBLE");expect(classifyFailure("fetch failed")).toBe("LIVE_PROVIDER_FAILURE");expect(classifyFailure("bad compiler state")).toBe("SYSTEM_FAILURE");});
});
