import {describe,expect,it} from "vitest";
import {authLikeRenderedRequest5B15,classifyFiveB15Failure,FIVE_B15_MAX_ATTEMPTS,FIVE_B15_RETRY_DELAY_MS,requestFingerprint5B15,retryAllowedFiveB15} from "../src/experiment5b15Policy.js";

describe("Experiment 5B15 deterministic retry policy",()=>{
 it("retries only preregistered HTTP and generic pre-semantic failures",()=>{for(const status of [408,425,429,500,502,503,504])expect(classifyFiveB15Failure("transport",new Error(`http_${status}`)).retryable).toBe(true);for(const status of [400,401,403,404,409,422])expect(classifyFiveB15Failure("transport",new Error(`http_${status}`)).retryable).toBe(false);expect(classifyFiveB15Failure("decode",new SyntaxError("Unexpected end of JSON input")).retryable).toBe(true);expect(classifyFiveB15Failure("transport",new TypeError("fetch failed")).retryable).toBe(true)});
 it("never retries render projection semantic or safety failures",()=>{expect(classifyFiveB15Failure("render",new Error("bad render")).retryable).toBe(false);expect(classifyFiveB15Failure("projection",new Error("bad projection")).retryable).toBe(false);expect(classifyFiveB15Failure("semantic",new Error("semantic mismatch")).retryable).toBe(false);expect(classifyFiveB15Failure("transport",new Error("redirect_cross_domain")).retryable).toBe(false)});
 it("freezes retry budget and delay",()=>{expect(FIVE_B15_MAX_ATTEMPTS).toBe(3);expect(FIVE_B15_RETRY_DELAY_MS).toBe(250);const eligible={outcome_class:"transport_exception",retryable:true,http_status:null};expect(retryAllowedFiveB15(1,eligible)).toBe(true);expect(retryAllowedFiveB15(2,eligible)).toBe(true);expect(retryAllowedFiveB15(3,eligible)).toBe(false)});
 it("fingerprints exact request semantics deterministically",()=>{const a=requestFingerprint5B15("https://example.test/x?q=1"),b=requestFingerprint5B15("https://example.test/x?q=1"),c=requestFingerprint5B15("https://example.test/x?q=2");expect(a).toBe(b);expect(a).not.toBe(c)});
 it("detects auth-like request material generically",()=>{expect(authLikeRenderedRequest5B15("https://example.test/x?api_key=secret")).toBe(true);expect(authLikeRenderedRequest5B15("https://example.test/x?q=world")).toBe(false)});
});
