import {beforeEach,describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import type {P1ProbeProof,P1RequestHypothesis} from "../src/experiment4ap1Model.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {buildAcquisitionTraceHypotheses4M,rebuildRequestGraph4M} from "../src/experiment4mRequest.js";
import {acquisitionCacheMetrics4M,fetchDocTextSafe4M,fetchSpecTextSafe4M,resetAcquisitionCache4M} from "../src/experiment4mFetch.js";
import {validate4m} from "../src/experiment4mContract.js";
import {deriveExperiment4mSource} from "../src/experiment4mDerivation.js";

let seq=0;
function ev(url:string,text:string,provider="p1",state:"ok"|"error"="ok"){const n=++seq;return {evidence_id:`e${n}`,provider_candidate_id:provider,requested_url:url,resolved_url:url,verified_at:new Date().toISOString(),status:state==="ok"?200:0,content_type:"application/json",body_fingerprint:`fp${n}`,text,state} as any}
function trace(texts:any[],caseId:string){return buildAcquisitionTraceHypotheses4M(texts,caseId)}
function hyps(r:any){return r.hypotheses as P1RequestHypothesis[]}
beforeEach(()=>resetAcquisitionCache4M());

describe("4M executed acquisition trace operation proof",()=>{
  it("induces barcode only from an actually executed whole path value",()=>{const e=ev("https://api.example.test/api/v2/product/3017620422003",JSON.stringify({code:"3017620422003",product_name:"Nutella",product:"food"})),r=trace([e],"food_barcode_metadata"),h=hyps(r).find(x=>x.proof_type==="4m_executed_trace_exact_path");expect(h).toBeTruthy();expect(h!.origin).toBe("https://api.example.test");expect(h!.full_path).toBe("/api/v2/product/{barcode}");expect(compileRequestHypothesisP1(h!,{barcode:"737628064502"})).toBe("https://api.example.test/api/v2/product/737628064502");expect(r.metrics.acquisitionTraceExactBuildValueSlots).toBe(1);expect(r.metrics.acquisitionTraceEchoSupportedSlots).toBeGreaterThan(0)});
  it("induces VIN while preserving the executed API origin",()=>{const e=ev("https://data.example.test/api/vehicles/decodevin/1HGCM82633A004352?format=json",JSON.stringify({VIN:"1HGCM82633A004352",Make:"HONDA",vehicle:"decoded"})),r=trace([e],"vin_vehicle_metadata"),h=hyps(r).find(x=>x.proof_type==="4m_executed_trace_exact_path");expect(h).toBeTruthy();expect(h!.origin).toBe("https://data.example.test");expect(compileRequestHypothesisP1(h!,{vin:"1M8GDM9AXKP042788"})).toContain("data.example.test/api/vehicles/decodevin/1M8GDM9AXKP042788")});
  it("rejects substring-only build occurrence",()=>{const e=ev("https://api.example.test/product/x3017620422003x",JSON.stringify({code:"3017620422003",name:"food product"})),r=trace([e],"food_barcode_metadata");expect(hyps(r).filter(h=>h.proof_type.startsWith("4m_executed_trace_exact_")).length).toBe(0)});
  it("rejects ambiguous repeated build occurrences",()=>{const e=ev("https://api.example.test/3017620422003/product/3017620422003",JSON.stringify({code:"3017620422003",name:"food product"})),r=trace([e],"food_barcode_metadata");expect(hyps(r).filter(h=>h.proof_type.startsWith("4m_executed_trace_exact_")).length).toBe(0)});
  it("induces a trace-family slot only from same-origin whole values",()=>{const a=ev("https://api.example.test/api/product/111111",JSON.stringify({code:"111111",name:"food product one"})),b=ev("https://api.example.test/api/product/222222",JSON.stringify({code:"222222",name:"food product two"})),r=trace([a,b],"food_barcode_metadata"),h=hyps(r).find(x=>x.proof_type==="4m_executed_trace_family_path");expect(h).toBeTruthy();expect(h!.origin).toBe("https://api.example.test");expect(h!.full_path).toBe("/api/product/{barcode}");expect(r.metrics.acquisitionTraceFamilySlots).toBeGreaterThan(0)});
  it("never joins executed traces across origins",()=>{const a=ev("https://one.example.test/api/product/111111",JSON.stringify({code:"111111",name:"food product"})),b=ev("https://two.example.test/api/product/222222",JSON.stringify({code:"222222",name:"food product"})),r=trace([a,b],"food_barcode_metadata");expect(hyps(r).filter(h=>h.proof_type.startsWith("4m_executed_trace_family_")).length).toBe(0)});
  it("rejects asset and navigation traces before hypotheses",()=>{const a=ev("https://api.example.test/static/images/3017620422003.png",JSON.stringify({code:"3017620422003",name:"food product"})),b=ev("https://api.example.test/docs/3017620422003",JSON.stringify({code:"3017620422003",name:"food product"})),r=trace([a,b],"food_barcode_metadata");expect(hyps(r)).toHaveLength(0);expect(Number(r.metrics.acquisitionTraceRejectedAsset)).toBeGreaterThan(0);expect(Number(r.metrics.acquisitionTraceRejectedNavigation)).toBeGreaterThan(0)});
  it("rejects auth-like executed trace query",()=>{const e=ev("https://api.example.test/api/product/3017620422003?key=secret",JSON.stringify({code:"3017620422003",name:"food product"})),r=trace([e],"food_barcode_metadata");expect(hyps(r)).toHaveLength(0);expect(r.metrics.acquisitionTraceRejectedAuthLike).toBe(1)});
  it("rejects trace evidence from another provider lineage",()=>{const a=ev("https://api.example.test/api/product/111111",JSON.stringify({code:"111111",name:"food product"}),"p1"),b=ev("https://api.example.test/api/product/222222",JSON.stringify({code:"222222",name:"food product"}),"p2"),r=trace([a,b],"food_barcode_metadata");expect(r.metrics.acquisitionTraceRejectedLineage).toBe(1);expect(hyps(r).filter(h=>h.proof_type.startsWith("4m_executed_trace_family_")).length).toBe(0)});
  it("validator rejects origin drift and non-slot path mutation",()=>{const evidence=[ev("https://api.example.test/api/v2/product/3017620422003",JSON.stringify({code:"3017620422003",name:"food product"}))],g=rebuildRequestGraph4M(evidence,"food_barcode_metadata"),h=(g.hypotheses as P1RequestHypothesis[]).find(x=>x.proof_type==="4m_executed_trace_exact_path")!;expect(h).toBeTruthy();const proof:P1ProbeProof={hypothesis:h,record:{hypothesis_id:h.id,disposition:"success",requested_url:"https://api.example.test/api/v2/product/3017620422003",requested_at:new Date().toISOString(),final_url:"https://api.example.test/api/v2/product/3017620422003",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:[{id:"codef",path:"code",leaf:"code",tokens:["code"],sample_type:"string",sample_value:"3017620422003",build_value_relations:["TASK_INPUT:barcode:normalized_equal"]},{id:"namef",path:"name",leaf:"name",tokens:["name"],sample_type:"string",sample_value:"food product",build_value_relations:[]}],observed_path_count:2,bytes:10,error:null}};const raw:any={case_id:"food_barcode_metadata",provider_candidate_id:"p1",decision:"COMPILE",method:"GET",base_url:h.origin,path_template:h.full_path,path_bindings:{barcode:"$input.barcode"},query_bindings:{},evidence_ids:h.evidence_ids,reason:`4M_EXECUTED_ACQUISITION_TRACE:${h.id}`,projection:{code:{op:"FIELD",path:"code"},name:{op:"FIELD",path:"name"}},probe_schema_fingerprint:"sf",probe_body_fingerprint:"bf"},provider:any={case_id:"food_barcode_metadata",candidate_id:"p1",name:"synthetic",start_url:"https://api.example.test/docs"};expect(validate4m(raw,provider,evidence,new RecoveryLedger(),proof).errors).toEqual([]);expect(validate4m({...raw,base_url:"https://www.example.test"},provider,evidence,new RecoveryLedger(),proof).errors).toContain("4m_trace_origin_drift");expect(validate4m({...raw,path_template:"/api/v2/product/{barcode}/extra"},provider,evidence,new RecoveryLedger(),proof).errors).toContain("4m_trace_request_mutation")});
  it("rebuilds the identical trace graph",()=>{const evidence=[ev("https://api.example.test/api/product/3017620422003",JSON.stringify({code:"3017620422003",name:"food product"}))],a=rebuildRequestGraph4M(evidence,"food_barcode_metadata"),b=rebuildRequestGraph4M(evidence,"food_barcode_metadata");expect(a.graph_fingerprint).toBe(b.graph_fingerprint);expect((a.hypotheses as P1RequestHypothesis[]).map(h=>h.id)).toEqual((b.hypotheses as P1RequestHypothesis[]).map(h=>h.id))});
  it("caches identical acquisition URL once within a run",async()=>{let calls=0;const fake=async(_s:string,u:string)=>{calls++;return {text:"hello",content_type:"text/plain",final_url:u}};const ledger=new RecoveryLedger();await fetchDocTextSafe4M("https://example.test","https://example.test/a",1000,ledger,fake as any);await fetchDocTextSafe4M("https://example.test","https://example.test/a",1000,ledger,fake as any);expect(calls).toBe(1);expect(acquisitionCacheMetrics4M()).toMatchObject({acquisitionCacheHits:1,acquisitionNetworkFetches:1,duplicateAcquisitionNetworkFetches:0})});
  it("caches identical spec URL once and resets between runs",async()=>{let calls=0;const fake=async(_s:string,u:string)=>{calls++;return {text:"{}",content_type:"application/json",final_url:u}};const ledger=new RecoveryLedger();await fetchSpecTextSafe4M("https://example.test","https://example.test/openapi.json",1000,ledger,fake as any);await fetchSpecTextSafe4M("https://example.test","https://example.test/openapi.json",1000,ledger,fake as any);expect(calls).toBe(1);expect(acquisitionCacheMetrics4M().specProbeCacheHits).toBe(1);resetAcquisitionCache4M();await fetchSpecTextSafe4M("https://example.test","https://example.test/openapi.json",1000,ledger,fake as any);expect(calls).toBe(2)});
  it("keeps implementation provider-blind",async()=>{const request=await readFile(new URL("../src/experiment4mRequest.ts",import.meta.url),"utf8"),contract=await readFile(new URL("../src/experiment4mContract.ts",import.meta.url),"utf8");expect(request+contract).not.toMatch(/openfoodfacts|nhtsa|registry\.npmjs|metmuseum|vpic\./i);expect(contract).toContain('prefix="4M_EXECUTED_ACQUISITION_TRACE:"')});
  it("derives frozen 4M cache, trace gates and base",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4mSource(src);expect(out).toContain("GO_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF");expect(out).toContain("REASSESS_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF");expect(out).toContain('base_sha:"a936218a82f8c38156dbef516c1271159b1b18c4"');expect(out).toContain("acquisition_trace_confirmed_recipe");expect(out).toContain("fetchDocTextSafe4M");expect(out).toContain("fetchSpecTextSafe4M")});
  it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4mSource(src);const result=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4m.ts"});const errs=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);expect(errs.map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
