import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import type {P1RequestHypothesis} from "../src/experiment4ap1Model.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {compileEvidenceNativeSemantics4G} from "../src/experiment4gSemantics.js";
import {induceRouteFamilyHypotheses4K,prepareRequestGraph4K,rebuildRequestGraph4K} from "../src/experiment4kRequest.js";
import {deriveExperiment4kSource} from "../src/experiment4kDerivation.js";

let seq=0;
const ev=(text:string,expanded=false)=>{
  const n=++seq;
  return {evidence_id:expanded?`4g_ref_${n}`:`ev${n}`,provider_candidate_id:"synthetic",requested_url:"https://docs.example.test/reference",resolved_url:"https://docs.example.test/reference",verified_at:new Date().toISOString(),status:200,content_type:"text/html",body_fingerprint:`fp${n}`,text,state:"ok",...(expanded?{source_kind:"4g_reference_expansion"}:{})} as any;
};
function induced(text:string,caseId:string){return induceRouteFamilyHypotheses4K(compileEvidenceNativeSemantics4G([ev(text)]),caseId)}
async function graph(text:string,caseId:string,expanded=false){return prepareRequestGraph4K([ev(text,expanded)],caseId,new RecoveryLedger())}

describe("4K route-family variable slot induction",()=>{
  it("induces one whole path-segment slot from two same-family requests",()=>{
    const r=induced('<h2>Product lookup</h2><p>Lookup a food product and return product code and product name.</p><pre>GET https://api.example.test/api/product/111111\nGET https://api.example.test/api/product/222222</pre>',"food_barcode_metadata");
    const h=r.hypotheses.find((x:P1RequestHypothesis)=>x.full_path.includes("{barcode}"));
    expect(h).toBeTruthy();expect(r.metrics.routeFamilyInducedPathSlots).toBeGreaterThan(0);expect(r.metrics.routeFamilyDistinctObservedValues).toBeGreaterThanOrEqual(2);expect(compileRequestHypothesisP1(h!,{barcode:"3017620422003"})).toContain("/api/product/3017620422003");
  });
  it("induces a query-value slot from three same-family requests",()=>{
    const r=induced('<h2>Product lookup</h2><p>Lookup food products by code and return product code and name.</p><pre>GET https://api.example.test/product?code=111111\nGET https://api.example.test/product?code=222222\nGET https://api.example.test/product?code=333333</pre>',"food_barcode_metadata");
    const h=r.hypotheses.find((x:P1RequestHypothesis)=>x.slots.some(s=>s.in==="query"&&s.name==="code"));expect(h).toBeTruthy();expect(r.metrics.routeFamilyInducedQuerySlots).toBeGreaterThan(0);const url=new URL(compileRequestHypothesisP1(h!,{barcode:"3017620422003"}));expect(url.searchParams.get("code")).toBe("3017620422003");
  });
  it("never forms one family across different API origins",()=>{const r=induced('<h2>Product lookup</h2><p>Lookup a food product and return code and name.</p><pre>GET https://one.example.test/product/111111\nGET https://two.example.test/product/222222</pre>',"food_barcode_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0);expect(r.metrics.routeFamiliesRejectedOriginMismatch).toBeGreaterThan(0)});
  it("rejects a pair when more than one request position varies",()=>{const r=induced('<h2>Vehicle lookup</h2><p>Decode vehicle identifiers and return VIN and make.</p><pre>GET https://api.example.test/vehicle/AAA/history?mode=short\nGET https://api.example.test/vehicle/BBB/recalls?mode=long</pre>',"vin_vehicle_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0);expect(r.metrics.routeFamiliesRejectedMultipleVariablePositions).toBeGreaterThan(0)});
  it("does not accept repeated identical examples as variable evidence",()=>{const r=induced('<h2>Product lookup</h2><p>Lookup a food product and return code and name.</p><pre>GET https://api.example.test/product/111111\nGET https://api.example.test/product/111111</pre>',"food_barcode_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0)});
  it("does not induce an auth-like query key",()=>{const r=induced('<h2>Product lookup</h2><p>Lookup a food product and return code and name. API key optional.</p><pre>GET https://api.example.test/product?key=AAA\nGET https://api.example.test/product?key=BBB</pre>',"food_barcode_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0)});
  it("accepts OFF-style unnamed product identifiers from a route family",()=>{const r=induced('<h2>Product metadata lookup</h2><p>Lookup a retail food product and return product code and product name.</p><pre>GET https://api.example.test/api/v2/product/111111\nGET https://api.example.test/api/v2/product/222222</pre>',"food_barcode_metadata");const h=r.hypotheses.find((x:P1RequestHypothesis)=>x.full_path.includes("{barcode}"));expect(h).toBeTruthy();expect(h!.input_bindings.barcode).toBeTruthy();expect(r.metrics.routeFamiliesAccepted).toBeGreaterThan(0)});
  it("accepts NHTSA-style unnamed vehicle identifiers from a route family",()=>{const r=induced('<h2>Vehicle decoder</h2><p>Decode a vehicle identification value and return VIN and vehicle make.</p><pre>GET https://api.example.test/vehicles/DecodeVin/AAA111\nGET https://api.example.test/vehicles/DecodeVin/BBB222</pre>',"vin_vehicle_metadata");const h=r.hypotheses.find((x:P1RequestHypothesis)=>x.full_path.includes("{vin}"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{vin:"1HGCM82633A004352"})).toContain("/DecodeVin/1HGCM82633A004352")});
  it("rejects a book route family for a fictional-character task",()=>{const r=induced('<h2>Book metadata</h2><p>Get books and return book id and book name.</p><pre>GET https://api.example.test/api/books/1\nGET https://api.example.test/api/books/2</pre>',"fictional_character_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0);expect(r.metrics.routeFamilyEntityRejectedBindings).toBeGreaterThan(0)});
  it("rejects an unrelated route family despite a single task input",()=>{const r=induced('<h2>Team schedule</h2><p>Get football team fixtures and scores.</p><pre>GET https://api.example.test/team/11/fixtures\nGET https://api.example.test/team/22/fixtures</pre>',"food_barcode_metadata");expect(r.hypotheses.filter((h:P1RequestHypothesis)=>h.proof_type.startsWith("4k_route_family_")).length).toBe(0)});
  it("retains expanded-evidence provenance for family members",async()=>{const g=await graph('<h2>Product metadata lookup</h2><p>Lookup a retail food product and return product code and product name.</p><pre>GET https://api.example.test/product/111111\nGET https://api.example.test/product/222222</pre>',"food_barcode_metadata",true);const h=(g.hypotheses as P1RequestHypothesis[]).find((x:P1RequestHypothesis)=>x.proof_type.startsWith("4k_route_family_"));expect(h).toBeTruthy();expect(h!.evidence_ids.some((id:string)=>id.startsWith("4g_ref_"))).toBe(true)});
  it("retains npm and Met documented-placeholder bindings from 4J",async()=>{const npm=await graph('<h2>Package metadata</h2><p>Get a package and return package name and version.</p><code>GET https://api.example.test/{package}</code>',"npm_package_metadata");const nh=(npm.hypotheses as P1RequestHypothesis[]).find((h:P1RequestHypothesis)=>h.full_path.includes("{package}"));expect(nh).toBeTruthy();expect(compileRequestHypothesisP1(nh!,{package_name:"lodash"})).toContain("/lodash");const met=await graph('<h2>Artwork object metadata</h2><p>Get artwork object metadata and return objectID and title.</p><code>GET https://api.example.test/objects/{objectID}</code>',"artwork_object_metadata");const mh=(met.hypotheses as P1RequestHypothesis[]).find((h:P1RequestHypothesis)=>h.full_path.includes("{objectID}"));expect(mh).toBeTruthy();expect(compileRequestHypothesisP1(mh!,{object_id:436121})).toContain("/objects/436121")});
  it("rebuilds an identical 4K graph",()=>{const evidence=[ev('<h2>Product lookup</h2><p>Lookup food product and return product code and name.</p><pre>GET https://api.example.test/product/111111\nGET https://api.example.test/product/222222</pre>')];const a=rebuildRequestGraph4K(evidence,"food_barcode_metadata"),b=rebuildRequestGraph4K(evidence,"food_barcode_metadata");expect(a.graph_fingerprint).toBe(b.graph_fingerprint);expect((a.hypotheses as P1RequestHypothesis[]).map((h:P1RequestHypothesis)=>h.id)).toEqual((b.hypotheses as P1RequestHypothesis[]).map((h:P1RequestHypothesis)=>h.id))});
  it("keeps implementation provider-blind and 4K provenance exclusive",async()=>{const request=await readFile(new URL("../src/experiment4kRequest.ts",import.meta.url),"utf8"),contract=await readFile(new URL("../src/experiment4kContract.ts",import.meta.url),"utf8");expect(request).not.toMatch(/openfoodfacts|nhtsa|registry\.npmjs|metmuseum|anapioficeandfire/i);expect(contract).toContain('prefix="4K_ROUTE_FAMILY_VARIABLE_SLOT:"');expect(contract).not.toContain('prefix="4J_ENTITY_GATED_IDENTIFIER_ROLE:"')});
  it("derives the frozen 4K base and formal gate",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4kSource(src);expect(out).toContain("GO_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION");expect(out).toContain("REASSESS_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION");expect(out).toContain('base_sha:"93b3aef43f0c35657bc222629ce85fb9d22fad95"');expect(out).toContain("route_family_confirmed_recipe");expect(out).toContain("routeFamilyConfirmedRecipes")});
  it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4kSource(src);const result=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4k.ts"});const syntactic=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);expect(syntactic.map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
