import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {prepareRequestGraph4J} from "../src/experiment4jRequest.js";
import {operationLocalAnchorContradiction4J} from "../src/experiment4jAudit.js";
import {deriveExperiment4jSource} from "../src/experiment4jDerivation.js";

function ev(text:string){return {evidence_id:"ev4j",provider_candidate_id:"synthetic",requested_url:"https://docs.example.test/reference",resolved_url:"https://docs.example.test/reference",verified_at:new Date().toISOString(),status:200,content_type:"text/html",body_fingerprint:"fp4j",text,state:"ok"} as any}

describe("4J operation-local slot anchoring",()=>{
  it("keeps npm placeholders literal",async()=>{const g=await prepareRequestGraph4J([ev('<h2>Package metadata</h2><code>GET https://api.example.test/{package}</code>')],"npm_package_metadata",new RecoveryLedger());expect(g.hypotheses.some(h=>h.full_path.includes("{package}"))).toBe(true);expect(g.metrics.placeholderPreservationFailures).toBe(0)});
  it("can bind a page query key to page_title with page-local evidence",async()=>{const g=await prepareRequestGraph4J([ev('<h2>Page metadata API</h2><p>Parse a page title and return title and description.</p><code>GET https://api.example.test/w/api.php?action=parse&page=Main_Page&format=json</code>')],"wikipedia_page_metadata",new RecoveryLedger());const h=g.hypotheses.find(x=>Object.values(x.input_bindings).some(id=>x.slots.find(s=>s.id===id)?.name==="page"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{page_title:"Python (programming language)"})).toContain("page=Python")});
  it("generalizes an OFF-style documented barcode example",async()=>{const g=await prepareRequestGraph4J([ev('<h2>Product barcode lookup</h2><p>Get a retail food product by barcode and return code and product name.</p><code>GET https://api.example.test/api/v2/product/737628064502.xml</code>')],"food_barcode_metadata",new RecoveryLedger());const h=g.hypotheses.find(x=>x.full_path.includes("slot4j_barcode"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{barcode:"3017620422003"})).toContain("3017620422003.xml")});
  it("generalizes an NHTSA-style documented VIN example and preserves fixed query literals",async()=>{const g=await prepareRequestGraph4J([ev('<h2>Decode VIN vehicle metadata</h2><p>Decode a VIN and return VIN and vehicle make.</p><code>GET https://api.example.test/api/vehicles/decodevin/5UXWX7C5*BA?format=json&modelyear=2011</code>')],"vin_vehicle_metadata",new RecoveryLedger());const h=g.hypotheses.find(x=>x.full_path.includes("slot4j_vin"));expect(h).toBeTruthy();const u=compileRequestHypothesisP1(h!,{vin:"1HGCM82633A004352"});expect(u).toContain("1HGCM82633A004352");expect(u).toContain("format=json");expect(u).toContain("modelyear=2011")});
  it("rejects a books endpoint as an entity contradiction for fictional characters",()=>{expect(operationLocalAnchorContradiction4J("fictional_character_metadata","/api/books/{slot4j_character}")).toBe(true);expect(operationLocalAnchorContradiction4J("fictional_character_metadata","/api/characters/{slot4j_character}")).toBe(false)});
  it("never emits obvious auth query material",async()=>{const g=await prepareRequestGraph4J([ev('<h2>Package metadata API</h2><p>API key is optional for higher rate limits.</p><code>GET https://api.example.test/{package}?key=demo&format=json</code>')],"npm_package_metadata",new RecoveryLedger());expect(g.metrics.authLikeRenderedRequests).toBe(0);expect(g.hypotheses.every(h=>!/[?&]key=/i.test(h.full_path))).toBe(true)});
  it("derives 4J decision, gate and frozen base",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4jSource(src);expect(out).toContain("GO_4J_OPERATION_LOCAL_SLOT_ANCHORING");expect(out).toContain("endpoint_entity_anchor_recipe_clean");expect(out).toContain('base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"')});
});
