import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {executeProgram,type ProjectionExpr} from "../src/experiment3xCore.js";
import {summarizeRelational4O,rowLookupHasNumericIndex4O} from "../src/experiment4oRelational.js";
import {allowedInputSources4P,deterministicProjection4P} from "../src/experiment4pCore.js";
import {plannerSchema4P} from "../src/experiment4pPlanner.js";
import {boundedOrderedMap4P} from "../src/experiment4pSchedule.js";
import {deriveExperiment4pSource} from "../src/experiment4pDerivation.js";

function hyp(){return {id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/x/{name}",proof_type:"documented",evidence_ids:["e"],source_urls:["https://api.example.test/x/a"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true}}
function field(id:string,path:string,leaf:string,tokens:string[],rels:string[]=[]){return {id,path,leaf,tokens,sample_type:"string",sample_value:"x",build_value_relations:rels}}
function proof(fields:any[]){return {hypothesis:hyp(),record:{hypothesis_id:"h",disposition:"success",requested_url:"https://api.example.test/x/a",requested_at:new Date().toISOString(),final_url:"https://api.example.test/x/a",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:fields,observed_path_count:fields.length,bytes:100,error:null}} as any}

describe("4P projection compatibility envelope",()=>{
 it("restores exact observed numeric FIELD paths",()=>{const p=proof([field("cat","meals.0.strCategory","strCategory",["str","category","category"])]),d=deterministicProjection4P(p,null,["name"],["category"])!;expect(d).toBeTruthy();expect(d.projection.category).toEqual({op:"FIELD",path:"meals.0.strCategory"});expect(executeProgram(d.projection as any,{meals:[{strCategory:"Seafood"}]},{name:"x"})).toEqual({category:"Seafood"})});
 it("does not invent FIELD paths outside the probe proof",()=>{const p=proof([field("cat","meals.0.strCategory","strCategory",["category"])]),d=deterministicProjection4P(p,null,[],["title"]);expect(d).toBeNull()});
 it("preserves index-free ROW_LOOKUP",()=>{const body={Results:[{Variable:"VIN",Value:"ABC"},{Variable:"Make",Value:"HONDA"}]},s=summarizeRelational4O(body),p=proof([]),d=deterministicProjection4P(p,s,["vin"],["vin","make"])!;expect(d.projection.vin).toEqual({op:"INPUT",name:"vin"});expect((d.projection.make as ProjectionExpr).op).toBe("ROW_LOOKUP");expect(rowLookupHasNumericIndex4O(d.projection.make)).toBe(false);expect(executeProgram(d.projection as any,body,{vin:"ABC"})).toEqual({vin:"ABC",make:"HONDA"})});
 it("keeps compatible INPUT and forbids incompatible INPUT",()=>{expect(allowedInputSources4P("vin",["vin"])).toEqual(["vin"]);expect(allowedInputSources4P("name",["name"])).toEqual(["name"]);expect(allowedInputSources4P("make",["vin"])).toEqual([])});
 it("fallback schema has no oneOf and is keyed by required outputs",()=>{const p=proof([field("v","dist-tags.latest","latest",["latest"])]),s:any=plannerSchema4P([p],["package"],["name","version"]);const text=JSON.stringify(s);expect(text).not.toContain('"oneOf"');const ob=s.schema.properties.output_bindings;expect(ob.type).toBe("object");expect(ob.required).toEqual(["name","version"]);expect(Object.keys(ob.properties)).toEqual(["name","version"])});
 it("fallback schema excludes TASK_INPUT:vin from make",()=>{const s:any=plannerSchema4P([proof([])],["vin"],["vin","make"]),props=s.schema.properties.output_bindings.properties;expect(props.vin.properties.source_id.enum).toContain("TASK_INPUT:vin");expect(props.make.properties.source_id.enum).not.toContain("TASK_INPUT:vin")});
 it("fallback schema retains numeric observed FIELD IDs",()=>{const p=proof([field("cat","drinks.0.strCategory","strCategory",["category"])]),s:any=plannerSchema4P([p],["name"],["category"]);expect(s.schema.properties.output_bindings.properties.category.properties.source_id.enum).toContain("cat")});
 it("bounded scheduler never exceeds concurrency three and preserves order",async()=>{let active=0,max=0;const delays=[50,5,30,1,20,10],done:number[]=[];const r=await boundedOrderedMap4P(delays,3,async(ms,i)=>{active++;max=Math.max(max,active);await new Promise(res=>setTimeout(res,ms));done.push(i);active--;return `r${i}`});expect(max).toBeLessThanOrEqual(3);expect(r.maxObservedConcurrency).toBeLessThanOrEqual(3);expect(r.results).toEqual(delays.map((_,i)=>`r${i}`));expect(done).not.toEqual([0,1,2,3,4,5])});
 it("executes every scheduled task exactly once",async()=>{const seen=new Map<number,number>(),items=Array.from({length:24},(_,i)=>i);const r=await boundedOrderedMap4P(items,3,async i=>{seen.set(i,(seen.get(i)||0)+1);return i});expect(r.results).toEqual(items);expect([...seen.values()]).toEqual(Array(24).fill(1))});
 it("propagates a task failure only after scheduled work is drained",async()=>{const seen:number[]=[];await expect(boundedOrderedMap4P([0,1,2,3,4],3,async i=>{seen.push(i);if(i===2)throw new Error("boom");return i})).rejects.toThrow("boom");expect(new Set(seen).size).toBe(5)});
 it("keeps 4P source provider-blind",async()=>{const paths=["experiment4pCore.ts","experiment4pPlanner.ts","experiment4pContract.ts","experiment4pSchedule.ts"],src=(await Promise.all(paths.map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/nhtsa|vpic\.|openfoodfacts|metmuseum|registry\.npmjs|themealdb|cocktaildb/i)});
 it("derives bounded rerank prephase and frozen 4O base",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4pSource(src);expect(out).toContain("GO_4P_PROJECTION_COMPATIBILITY_ENVELOPE");expect(out).toContain("REASSESS_4P_PROJECTION_COMPATIBILITY_ENVELOPE");expect(out).toContain('base_sha:"3a1fffc82d3854302b34e9bcfc1a4e1f44ac0744"');expect(out).toContain("boundedOrderedMap4P(FOUR_A_CASES,rerankConcurrencyLimit4p");expect(out).toContain("rerankConcurrencyLimit:rerankConcurrencyLimit4p");expect(out).toContain("rerank_concurrency_bounded")});
 it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4pSource(src),r=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4p.ts"});expect((r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
