import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {decodeStructured4R} from "../src/experiment4rDecode.js";
import {deterministicPartialProjection4R} from "../src/experiment4rCore.js";
import {summarizeRelational4O} from "../src/experiment4oRelational.js";
import {executeProgram} from "../src/experiment3xCore.js";
import {deriveExperiment4rSource} from "../src/experiment4rDerivation.js";
function hyp(){return {id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/x/{vin}",proof_type:"4n_executed_trace_documented_role_path",evidence_ids:["e"],source_urls:["https://api.example.test/x/a"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true}}
function proof(fields:any[]){return {hypothesis:hyp(),record:{hypothesis_id:"h",disposition:"success",requested_url:"https://api.example.test/x/a",requested_at:new Date().toISOString(),final_url:"https://api.example.test/x/a",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:fields,observed_path_count:fields.length,bytes:100,error:null}} as any}
describe("4R representation agnostic response IR",()=>{
 it("decodes JSON without changing shape",()=>{const d=decodeStructured4R('{"code":"123","name":"X"}',"application/json","https://x.test/a");expect(d.format).toBe("json");expect(d.body).toEqual({code:"123",name:"X"})});
 it("decodes bounded XML into canonical object",()=>{const d=decodeStructured4R('<product><code>3017620422003</code><product_name>Nutella</product_name></product>',"application/xml","https://x.test/product.xml");expect(d.format).toBe("xml");expect(d.metrics.structuredDecoderNonJsonSuccesses).toBe(1);expect(d.body.product.code).toBe("3017620422003");expect(d.body.product.product_name).toBe("Nutella")});
 it("decodes CSV header rows",()=>{const d=decodeStructured4R('Variable,Value\nVIN,ABC\nMake,HONDA',"text/csv","https://x.test/a.csv");expect(d.format).toBe("csv");expect(d.body.rows[1]).toEqual({Variable:"Make",Value:"HONDA"})});
 it("fails closed on malformed CSV",()=>{expect(()=>decodeStructured4R('A,B\n1',"text/csv","https://x.test/a.csv")).toThrow(/width/)});
 it("exact relational label Make wins over NCSA Make",()=>{const body={Results:[{Variable:"VIN",Value:"ABC"},{Variable:"NCSA Make",Value:"OTHER"},{Variable:"Make",Value:"HONDA"}]},s=summarizeRelational4O(body),d=deterministicPartialProjection4R(proof([]),s,["vin"],["vin","make"]);expect(d.unresolved).toEqual([]);expect(d.exactRelationalLabels).toBe(1);expect((d.projection.make as any).label_value).toBe("Make");expect(executeProgram(d.projection as any,body,{vin:"ABC"})).toEqual({vin:"ABC",make:"HONDA"})});
 it("locks proven outputs and leaves only unresolved outputs",()=>{const p=proof([{id:"cat",path:"meals.0.strCategory",leaf:"strCategory",tokens:["str","category"],sample_type:"string",sample_value:"Vegetarian",build_value_relations:[]}]),d=deterministicPartialProjection4R(p,null,["meal_name"],["name","category","description"]);expect(d.projection.name).toEqual({op:"INPUT",name:"meal_name"});expect(d.projection.category).toEqual({op:"FIELD",path:"meals.0.strCategory"});expect(d.unresolved).toEqual(["description"]);expect(d.locked).toEqual(["name","category"])});
 it("does not map make from vin",()=>{const d=deterministicPartialProjection4R(proof([]),null,["vin"],["make"]);expect(d.locked).toEqual([]);expect(d.unresolved).toEqual(["make"])});
 it("keeps source provider blind",async()=>{const src=(await Promise.all(["experiment4rDecode.ts","experiment4rProbe.ts","experiment4rCore.ts","experiment4rPlanner.ts","experiment4rContract.ts"].map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/nhtsa|vpic\.|openfoodfacts|themealdb|cocktaildb|metmuseum|registry\.npmjs/i)});
 it("derives frozen 4Q base and runtime concurrency",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4rSource(src);expect(out).toContain('base_sha:"fd5a32ace7cfbf6b11e86040da892b1d0a1238b1"');expect(out).toContain("GO_4R_REPRESENTATION_AGNOSTIC_RESPONSE_IR_COMPOSITIONAL_PROJECTION");expect(out).toContain("structured_decoder_non_json_success");expect(out).toContain("rerankConcurrencyLimit4p=3")});
 it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4rSource(src),r=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4r.ts"});expect((r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
