import {readFile} from "node:fs/promises";
import {describe,expect,it} from "vitest";
import {qualifyMachineSpec4U,resolveLocalRef4U,resolveServerOrigin4U,responseHasDeferredRefs4U,securityRequired4U,splitServerRequest4U,type RefMetrics4U} from "../src/experiment4uOpenApi.js";
import {freezeRequestProof4U,verifyFrozenRequestProof4U} from "../src/experiment4uNativeOperation.js";
import {deriveExperiment4uSource} from "../src/experiment4uDerivation.js";
import type {P1RequestHypothesis} from "../src/experiment4ap1Model.js";

const metrics=():RefMetrics4U=>({operationLocalRefsResolved4u:0,operationLocalRefsRejected4u:0,operationExternalRefsRejected4u:0,operationExternalRefFetches4u:0,operationRefCyclesRejected4u:0,unrelatedRefFailuresIsolated4u:0});
describe("Experiment 4U spec-qualified lazy OpenAPI compiler",()=>{
  it("derives the complete 4U benchmark source from the frozen experiment source",async()=>{const source=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),derived=deriveExperiment4uSource(source);expect(derived).toContain('experiment:"4U"');expect(derived).toContain("machineDocumentFetches4u");expect(derived).toContain("GO_4U_SPEC_QUALIFIED_LAZY_OPENAPI_COMPILER_UNIVERSAL_FROZEN_PROOF")});
  it("rejects valid JSON and YAML that are not OpenAPI",()=>{const j=qualifyMachineSpec4U(JSON.stringify({hello:"world"}));expect(j.spec).toBeNull();expect(j.nonSpecJson).toBe(true);const y=qualifyMachineSpec4U("hello: world\nitems:\n  - one\n");expect(y.spec).toBeNull();expect(y.nonSpecYaml).toBe(true)});
  it("parses qualified OpenAPI YAML with nested arrays, multiline text, enums and local refs",()=>{const q=qualifyMachineSpec4U(`openapi: 3.0.3\nservers:\n  - url: https://example.com\npaths:\n  /search:\n    get:\n      operationId: search\n      description: |\n        Search safely\n        across records.\n      parameters:\n        - $ref: '#/components/parameters/Q'\n      responses:\n        '200':\n          description: ok\ncomponents:\n  parameters:\n    Q:\n      name: q\n      in: query\n      required: true\n      schema:\n        type: string\n        enum: [alpha, beta]\n`);expect(q.spec?.kind).toBe("openapi3");expect(q.spec?.spec.servers[0].url).toBe("https://example.com");expect(q.spec?.spec.paths["/search"].get.parameters[0].$ref).toBe("#/components/parameters/Q")});
  it("resolves only requested local refs, rejects external refs, and never fetches them",()=>{const root={components:{parameters:{Q:{name:"q",in:"query",required:true}}}};const m=metrics();expect(resolveLocalRef4U(root,{$ref:"#/components/parameters/Q"},m).name).toBe("q");expect(m.operationLocalRefsResolved4u).toBe(1);expect(()=>resolveLocalRef4U(root,{$ref:"https://other.example/x"},m)).toThrow("4u_external_ref");expect(m.operationExternalRefsRejected4u).toBe(1);expect(m.operationExternalRefFetches4u).toBe(0)});
  it("rejects missing and circular request refs without touching unrelated response refs",()=>{const root={components:{parameters:{A:{$ref:"#/components/parameters/B"},B:{$ref:"#/components/parameters/A"}}}};const m=metrics();expect(()=>resolveLocalRef4U(root,{$ref:"#/components/parameters/A"},m)).toThrow("4u_ref_cycle");expect(()=>resolveLocalRef4U(root,{$ref:"#/components/parameters/Missing"},m)).toThrow("4u_ref_missing");const op={responses:{"200":{content:{"application/json":{schema:{$ref:"#/components/schemas/MissingUnused"}}}}}};expect(responseHasDeferredRefs4U(op)).toBe(true)});
  it("resolves servers and preserves base paths in the executable request",()=>{const o=qualifyMachineSpec4U(JSON.stringify({openapi:"3.0.3",servers:[{url:"/api"}],paths:{}})),oServer=resolveServerOrigin4U(o.spec!,"https://example.com/openapi.json");expect(oServer).toBe("https://example.com/api");expect(splitServerRequest4U(oServer!,"/search")).toEqual({origin:"https://example.com",full_path:"/api/search"});const s=qualifyMachineSpec4U(JSON.stringify({swagger:"2.0",schemes:["https"],host:"example.com",basePath:"/v1",paths:{}})),sServer=resolveServerOrigin4U(s.spec!,"https://example.com/swagger.json");expect(splitServerRequest4U(sServer!,"/items/{id}")).toEqual({origin:"https://example.com",full_path:"/v1/items/{id}"})});
  it("rejects cross-provider and unresolved templated servers",()=>{const templated=qualifyMachineSpec4U(JSON.stringify({openapi:"3.0.3",servers:[{url:"https://{region}.example.com",variables:{region:{}}}],paths:{}}));expect(resolveServerOrigin4U(templated.spec!,"https://example.com/openapi.json")).toBeNull();const cross=qualifyMachineSpec4U(JSON.stringify({openapi:"3.0.3",servers:[{url:"https://other.example.net/api"}],paths:{}}));expect(resolveServerOrigin4U(cross.spec!,"https://example.com/openapi.json")).toBeNull()});
  it("honors operation security override and rejects inherited global security otherwise",()=>{const spec={security:[{apiKey:[]}]};expect(securityRequired4U(spec,{})).toBe(true);expect(securityRequired4U(spec,{security:[]})).toBe(false)});
  it("freezes inherited or native request proof and rejects path, input and literal mutation",()=>{const h:P1RequestHypothesis={id:"req_x",source_operation_id:"op_x",origin:"https://example.com",full_path:"/search",proof_type:"4n_executed_trace_documented_role_path",evidence_ids:["e1"],source_urls:["https://example.com/docs"],slots:[{id:"p1",name:"q",in:"query",required:true,auth_like:false,literals:[{id:"lit1",value:"fixed"}]}],input_bindings:{name:"p1"},literal_bindings:{},score:1000,concrete_relation:false};const proof=freezeRequestProof4U(h);expect(verifyFrozenRequestProof4U(h,proof)).toBe(true);expect(verifyFrozenRequestProof4U({...h,full_path:"/mutated"},proof)).toBe(false);expect(verifyFrozenRequestProof4U({...h,input_bindings:{other:"p1"}},proof)).toBe(false);expect(verifyFrozenRequestProof4U({...h,literal_bindings:{p1:"lit1"}},proof)).toBe(false)});
});
