import {beforeEach,describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import type {DocEvidence} from "../src/experiment3wCore.js";
import type {P1ProbeProof,P1RequestHypothesis} from "../src/experiment4ap1Model.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {resetAcquisitionCache4M} from "../src/experiment4mFetch.js";
import {executedTraces4N,executedTraceRegistryMetrics4N,fetchDocTextSafe4N,fetchSpecTextSafe4N,resetExecutedTraceGraph4N,type ExecutedGetTrace4N} from "../src/experiment4nTrace.js";
import {expandReferenceEvidence4N} from "../src/experiment4nReference.js";
import {buildExecutedTraceHypotheses4N,rebuildRequestGraph4N} from "../src/experiment4nRequest.js";
import {validate4n} from "../src/experiment4nContract.js";
import {deriveExperiment4nSource} from "../src/experiment4nDerivation.js";

let seq=0;
function doc(id:string,text:string,url="https://docs.example.com/reference",provider="p1",content="text/html"):DocEvidence{return {evidence_id:id,provider_candidate_id:provider,requested_url:url,resolved_url:url,verified_at:new Date().toISOString(),status:200,content_type:content,body_fingerprint:`d${++seq}`,text,state:"ok"} as any}
function traceObj(url:string,text:string,caseId:string,provider="p1",parents:string[]=[],content="application/json",stage:"CRAWL"|"REFERENCE_EXPANSION"|"STANDARD_SPEC"="CRAWL"):ExecutedGetTrace4N{return {trace_id:`t${++seq}`,case_id:caseId,provider_candidate_id:provider,stage,parent_evidence_ids:parents,requested_url:url,final_url:url,requested_at:new Date().toISOString(),disposition:"success",content_type:content,body_fingerprint:`b${seq}`,body_bytes:Buffer.byteLength(text),response_text:text,network_origin:"network",error:null}}
function built(traces:ExecutedGetTrace4N[],evidence:DocEvidence[],caseId:string,provider="p1",base:P1RequestHypothesis[]=[]){return buildExecutedTraceHypotheses4N(traces,evidence,base,caseId,provider)}
beforeEach(()=>{resetAcquisitionCache4M();resetExecutedTraceGraph4N()});

describe("4N first-class executed request evidence graph",()=>{
  it("emits an immutable trace at the crawl network boundary",async()=>{let calls=0;const fake=async(_s:string,u:string)=>{calls++;return {text:JSON.stringify({product:"food",code:"3017620422003",name:"Nutella"}),content_type:"application/json",final_url:u}};await fetchDocTextSafe4N({case_id:"food_barcode_metadata",provider_candidate_id:"p1",stage:"CRAWL",parent_evidence_ids:["parent1"]},"https://docs.example.com","https://api.example.com/api/product/3017620422003",10000,new RecoveryLedger(),fake as any);const rows=executedTraces4N("food_barcode_metadata","p1");expect(calls).toBe(1);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({stage:"CRAWL",network_origin:"network",parent_evidence_ids:["parent1"],disposition:"success"});expect(rows[0].body_fingerprint).toBeTruthy()});
  it("cache reuse emits a second consumer trace without a second network call",async()=>{let calls=0;const fake=async(_s:string,u:string)=>{calls++;return {text:JSON.stringify({id:1}),content_type:"application/json",final_url:u}},ledger=new RecoveryLedger(),url="https://api.example.com/api/item/1";await fetchDocTextSafe4N({case_id:"fictional_character_metadata",provider_candidate_id:"p1",stage:"CRAWL",parent_evidence_ids:["a"]},"https://docs.example.com",url,10000,ledger,fake as any);await fetchDocTextSafe4N({case_id:"fictional_character_metadata",provider_candidate_id:"p1",stage:"CRAWL",parent_evidence_ids:["b"]},"https://docs.example.com",url,10000,ledger,fake as any);const rows=executedTraces4N();expect(calls).toBe(1);expect(rows).toHaveLength(2);expect(rows.map(r=>r.network_origin)).toEqual(["network","cache"]);expect(rows[0].trace_id).not.toBe(rows[1].trace_id);expect(rows[0].body_fingerprint).toBe(rows[1].body_fingerprint);expect(rows[1].parent_evidence_ids).toEqual(["b"]);expect(executedTraceRegistryMetrics4N().executedTraceCacheReuseEvents).toBe(1)});
  it("emits a STANDARD_SPEC trace through the spec boundary",async()=>{const fake=async(_s:string,u:string)=>({text:'{"openapi":"3.0.0"}',content_type:"application/json",final_url:u});await fetchSpecTextSafe4N({case_id:"npm_package_metadata",provider_candidate_id:"p1",stage:"STANDARD_SPEC",parent_evidence_ids:[]},"https://docs.example.com","https://api.example.com/openapi.json",10000,new RecoveryLedger(),fake as any);expect(executedTraces4N()[0].stage).toBe("STANDARD_SPEC")});
  it("emits a REFERENCE_EXPANSION trace with parent lineage",async()=>{const evidence=[doc("root",'<a href="https://docs.example.com/api-reference">API Reference</a>')],fake=async(_s:string,u:string)=>({text:'{"reference":"api"}',content_type:"application/json",final_url:u});const m=await expandReferenceEvidence4N(evidence,"npm_package_metadata","p1",new RecoveryLedger(),3,fake as any),rows=executedTraces4N();expect(m.referenceExpansionFetches4n).toBe(1);expect(rows).toHaveLength(1);expect(rows[0].stage).toBe("REFERENCE_EXPANSION");expect(rows[0].parent_evidence_ids).toEqual(["root"])});
  it("induces exact whole barcode while preserving origin and path suffix",()=>{const parent=doc("pdoc","Retail food product API returns product code and product name for a barcode."),t=traceObj("https://api.example.com/api/v2/product/3017620422003.json",JSON.stringify({product:"food",code:"3017620422003",name:"Nutella"}),"food_barcode_metadata","p1",["pdoc"]),r=built([t],[parent],"food_barcode_metadata"),h=r.hypotheses.find(x=>x.proof_type==="4n_executed_trace_exact_path");expect(h).toBeTruthy();expect(h!.origin).toBe("https://api.example.com");expect(h!.full_path).toBe("/api/v2/product/{barcode}.json");expect(compileRequestHypothesisP1(h!,{barcode:"737628064502"})).toBe("https://api.example.com/api/v2/product/737628064502.json")});
  it("induces exact VIN while preserving executed origin",()=>{const parent=doc("vdoc","Vehicle API Decode VIN request returns VIN and vehicle make."),t=traceObj("https://data.example.com/api/vehicles/decodevin/1HGCM82633A004352?format=json",JSON.stringify({vehicle:"car",VIN:"1HGCM82633A004352",Make:"HONDA"}),"vin_vehicle_metadata","p1",["vdoc"]),r=built([t],[parent],"vin_vehicle_metadata"),h=r.hypotheses.find(x=>x.proof_type==="4n_executed_trace_exact_path");expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{vin:"1M8GDM9AXKP042788"})).toContain("data.example.com/api/vehicles/decodevin/1M8GDM9AXKP042788")});
  it("rejects substring-only and ambiguous repeated build values",()=>{const p=doc("pdoc","Retail food product API barcode code name."),a=traceObj("https://api.example.com/product/x3017620422003x",JSON.stringify({product:"food",code:"3017620422003",name:"x"}),"food_barcode_metadata","p1",["pdoc"]),b=traceObj("https://api.example.com/3017620422003/product/3017620422003",JSON.stringify({product:"food",code:"3017620422003",name:"x"}),"food_barcode_metadata","p1",["pdoc"]);expect(built([a],[p],"food_barcode_metadata").hypotheses.filter(h=>h.proof_type.includes("exact")).length).toBe(0);expect(built([b],[p],"food_barcode_metadata").hypotheses.filter(h=>h.proof_type.includes("exact")).length).toBe(0)});
  it("induces one same-origin family slot and rejects different origins",()=>{const p=doc("pdoc","Retail food product API returns code and product name."),a=traceObj("https://api.example.com/api/product/111111",JSON.stringify({product:"food",code:"111111",name:"a"}),"food_barcode_metadata","p1",["pdoc"]),b=traceObj("https://api.example.com/api/product/222222",JSON.stringify({product:"food",code:"222222",name:"b"}),"food_barcode_metadata","p1",["pdoc"]),c=traceObj("https://other.example.com/api/product/333333",JSON.stringify({product:"food",code:"333333",name:"c"}),"food_barcode_metadata","p1",["pdoc"]);const same=built([a,b],[p],"food_barcode_metadata");expect(same.hypotheses.some(h=>h.proof_type==="4n_executed_trace_family_path"&&h.full_path==="/api/product/{barcode}")).toBe(true);const cross=built([a,c],[p],"food_barcode_metadata");expect(cross.hypotheses.some(h=>h.proof_type==="4n_executed_trace_family_path")).toBe(false)});
  it("does not bind VIN to format=json/xml/csv family variation",()=>{const p=doc("vdoc","Vehicle Decode VIN API returns VIN and Make."),mk=(format:string)=>traceObj(`https://api.example.com/api/vehicles/decodevin/5UXWX7C5*BA?format=${format}`,JSON.stringify({vehicle:"car",VIN:"5UXWX7C5*BA",Make:"BMW"}),"vin_vehicle_metadata","p1",["vdoc"]);const r=built([mk("json"),mk("xml"),mk("csv")],[p],"vin_vehicle_metadata");expect(r.hypotheses.some(h=>h.proof_type==="4n_executed_trace_family_query")).toBe(false)});
  it("joins a different executed sample to a documented VIN role",()=>{const parent=doc("vdoc",'<h2>Decode VIN</h2><p>Vehicle API endpoint returns VIN and vehicle make.</p><code>GET /api/vehicles/DecodeVin/5UXWX7C5*BA?format=json</code>'),t=traceObj("https://api.example.com/api/vehicles/DecodeVin/5UXWX7C5*BA?format=json",JSON.stringify({vehicle:"car",VIN:"5UXWX7C5*BA",Make:"BMW"}),"vin_vehicle_metadata","p1",["vdoc"]),r=built([t],[parent],"vin_vehicle_metadata"),h=r.hypotheses.find(x=>x.proof_type==="4n_executed_trace_documented_role_path");expect(h).toBeTruthy();expect(h!.full_path).toBe("/api/vehicles/DecodeVin/{vin}?format=json");expect(compileRequestHypothesisP1(h!,{vin:"1HGCM82633A004352"})).toContain("/DecodeVin/1HGCM82633A004352?format=json");expect(r.metrics.executedTraceDocumentedRoleJoins).toBeGreaterThan(0)});
  it("joins a documented barcode role while preserving an executed JSON suffix",()=>{const parent=doc("pdoc",'<h2>Product by barcode</h2><p>Retail food product API returns product code and name.</p><code>GET /api/v2/product/737628064502.json</code>'),t=traceObj("https://api.example.com/api/v2/product/737628064502.json",JSON.stringify({product:"food",code:"737628064502",name:"sample"}),"food_barcode_metadata","p1",["pdoc"]),r=built([t],[parent],"food_barcode_metadata"),h=r.hypotheses.find(x=>x.proof_type==="4n_executed_trace_documented_role_path");expect(h).toBeTruthy();expect(h!.full_path).toBe("/api/v2/product/{barcode}.json")});
  it("uses an inherited documented placeholder when it exactly reconstructs the executed request",()=>{const p=doc("pdoc","Vehicle API returns VIN and make."),t=traceObj("https://api.example.com/api/vehicle/ABC123",JSON.stringify({vehicle:"car",vin:"ABC123",make:"X"}),"vin_vehicle_metadata","p1",["pdoc"]),slot={id:"s",name:"VIN",in:"path" as const,required:true,auth_like:false,literals:[]},base={id:"base",source_operation_id:"o",origin:"https://api.example.com",full_path:"/api/vehicle/{VIN}",proof_type:"documented",evidence_ids:["pdoc"],source_urls:[p.requested_url],slots:[slot],input_bindings:{vin:"s"},literal_bindings:{},score:1,concrete_relation:false} as P1RequestHypothesis,r=built([t],[p],"vin_vehicle_metadata","p1",[base]);expect(r.hypotheses.some(h=>h.proof_type==="4n_executed_trace_documented_role_path"&&h.full_path==="/api/vehicle/{vin}")).toBe(true)});
  it("rejects ambiguous documented-role substitutions",()=>{const p=doc("pdoc","Vehicle VIN API returns VIN and make."),t=traceObj("https://api.example.com/api/ABC123/vehicle/XYZ987",JSON.stringify({vehicle:"car",VIN:"ABC123",Make:"X"}),"vin_vehicle_metadata","p1",["pdoc"]),r=built([t],[p],"vin_vehicle_metadata");expect(r.hypotheses.filter(h=>h.proof_type.includes("documented_role")).length).toBe(0);expect(r.metrics.executedTraceDocumentedRoleJoinRejects).toBeGreaterThan(0)});
  it("hard-rejects documentation routes even when /api/ appears later",()=>{const parent=doc("d","Vehicle API VIN make."),paths=["/documentation/api/ABC123","/docs/api/ABC123","/reference/api/ABC123","/sdk/api/ABC123","/guide/api/ABC123","/help/api/ABC123"];for(const path of paths){const t=traceObj(`https://api.example.com${path}`,JSON.stringify({vehicle:"car",VIN:"ABC123",Make:"X"}),"vin_vehicle_metadata","p1",["d"]),r=built([t],[parent],"vin_vehicle_metadata");expect(r.hypotheses).toHaveLength(0);expect(r.metrics.executedTraceRejectedDocumentation).toBe(1)}});
  it("rejects OpenAPI/Swagger documents and assets as direct targets",()=>{const p=doc("d","Vehicle API VIN make."),rows=[traceObj("https://api.example.com/openapi.json","{}","vin_vehicle_metadata","p1",["d"]),traceObj("https://api.example.com/swagger.yaml","openapi: 3","vin_vehicle_metadata","p1",["d"],"text/yaml"),traceObj("https://api.example.com/static/images/ABC123.png","x","vin_vehicle_metadata","p1",["d"],"image/png")],r=built(rows,[p],"vin_vehicle_metadata");expect(r.hypotheses).toHaveLength(0);expect(Number(r.metrics.executedTraceRejectedDocumentation)+Number(r.metrics.executedTraceRejectedAsset)).toBe(3)});
  it("rejects auth-like trace query and cross-provider lineage",()=>{const p=doc("d","Retail food product API barcode code name."),auth=traceObj("https://api.example.com/api/product/3017620422003?key=secret",JSON.stringify({product:"food",code:"3017620422003",name:"x"}),"food_barcode_metadata","p1",["d"]),other=traceObj("https://api.example.com/api/product/3017620422003",JSON.stringify({product:"food",code:"3017620422003",name:"x"}),"food_barcode_metadata","p2",["d"]),r=built([auth,other],[p],"food_barcode_metadata","p1");expect(r.hypotheses).toHaveLength(0);expect(r.metrics.executedTraceRejectedAuthLike).toBe(1);expect(r.metrics.executedTraceRejectedLineage).toBe(1)});
  it("response echo alone cannot create a role for an unrelated route",()=>{const p=doc("d","Team statistics endpoint."),t=traceObj("https://api.example.com/api/team/3017620422003",JSON.stringify({code:"3017620422003",team:"United"}),"food_barcode_metadata","p1",["d"]),r=built([t],[p],"food_barcode_metadata");expect(r.hypotheses).toHaveLength(0)});
  it("validator accepts same trace graph and rejects origin/path drift",async()=>{let calls=0;const parent=doc("pdoc","Retail food product API barcode returns product code and name."),fake=async(_s:string,u:string)=>{calls++;return {text:JSON.stringify({product:"food",code:"3017620422003",name:"Nutella"}),content_type:"application/json",final_url:u}},ledger=new RecoveryLedger();await fetchDocTextSafe4N({case_id:"food_barcode_metadata",provider_candidate_id:"p1",stage:"CRAWL",parent_evidence_ids:["pdoc"]},"https://docs.example.com","https://api.example.com/api/product/3017620422003",10000,ledger,fake as any);const g=rebuildRequestGraph4N([parent],"food_barcode_metadata","p1"),h=(g.hypotheses as P1RequestHypothesis[]).find(x=>x.proof_type==="4n_executed_trace_exact_path")!;expect(h).toBeTruthy();const proof:P1ProbeProof={hypothesis:h,record:{hypothesis_id:h.id,disposition:"success",requested_url:"https://api.example.com/api/product/3017620422003",requested_at:new Date().toISOString(),final_url:"https://api.example.com/api/product/3017620422003",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:[{id:"c",path:"code",leaf:"code",tokens:["code"],sample_type:"string",sample_value:"3017620422003",build_value_relations:["TASK_INPUT:barcode:normalized_equal"]},{id:"n",path:"name",leaf:"name",tokens:["name"],sample_type:"string",sample_value:"Nutella",build_value_relations:[]}],observed_path_count:2,bytes:10,error:null}},provider:any={case_id:"food_barcode_metadata",candidate_id:"p1",name:"synthetic",start_url:"https://docs.example.com"},raw:any={case_id:"food_barcode_metadata",provider_candidate_id:"p1",decision:"COMPILE",method:"GET",base_url:h.origin,path_template:h.full_path,path_bindings:{barcode:"$input.barcode"},query_bindings:{},reason:`4N_FIRST_CLASS_EXECUTED_TRACE:${h.id}`,projection:{code:{op:"FIELD",path:"code"},name:{op:"FIELD",path:"name"}},probe_schema_fingerprint:"sf",probe_body_fingerprint:"bf"};expect(validate4n(raw,provider,[parent],ledger,proof).errors).toEqual([]);expect(validate4n({...raw,base_url:"https://www.example.com"},provider,[parent],ledger,proof).errors).toContain("4n_trace_origin_drift");expect(validate4n({...raw,path_template:"/api/product/{barcode}/extra"},provider,[parent],ledger,proof).errors).toContain("4n_trace_request_mutation")});
  it("planner and validator rebuild the same trace graph fingerprint",async()=>{const p=doc("pdoc","Retail food product API barcode code name."),fake=async(_s:string,u:string)=>({text:JSON.stringify({product:"food",code:"3017620422003",name:"x"}),content_type:"application/json",final_url:u});await fetchDocTextSafe4N({case_id:"food_barcode_metadata",provider_candidate_id:"p1",stage:"CRAWL",parent_evidence_ids:["pdoc"]},"https://docs.example.com","https://api.example.com/api/product/3017620422003",10000,new RecoveryLedger(),fake as any);const a=rebuildRequestGraph4N([p],"food_barcode_metadata","p1"),b=rebuildRequestGraph4N([p],"food_barcode_metadata","p1");expect(a.graph_fingerprint).toBe(b.graph_fingerprint);expect((a.hypotheses as P1RequestHypothesis[]).map(h=>h.id)).toEqual((b.hypotheses as P1RequestHypothesis[]).map(h=>h.id))});
  it("retains inherited npm and Met documented placeholders",()=>{const npm=doc("n",'<h2>Package API</h2><p>GET returns package name and version.</p><code>GET https://api.example.com/{package}</code>'),met=doc("m",'<h2>Artwork object API</h2><p>GET returns objectID and title.</p><code>GET https://api.example.com/objects/{objectID}</code>');const ng=rebuildRequestGraph4N([npm],"npm_package_metadata","p1"),mg=rebuildRequestGraph4N([met],"artwork_object_metadata","p1");expect((ng.hypotheses as P1RequestHypothesis[]).some(h=>h.full_path.includes("{package}"))).toBe(true);expect((mg.hypotheses as P1RequestHypothesis[]).some(h=>h.full_path.includes("{objectID}"))).toBe(true)});
  it("does not reintroduce fictional-character to books",()=>{const p=doc("d","Book API returns book id and book name."),t=traceObj("https://api.example.com/api/books/1",JSON.stringify({book:"volume",id:1,name:"A Book"}),"fictional_character_metadata","p1",["d"]),r=built([t],[p],"fictional_character_metadata");expect(r.hypotheses.filter(h=>h.proof_type.startsWith("4n_executed_trace_")).length).toBe(0)});
  it("keeps implementation provider-blind",async()=>{const paths=["experiment4nTrace.ts","experiment4nReference.ts","experiment4nRequest.ts","experiment4nPlanner.ts","experiment4nContract.ts"],src=(await Promise.all(paths.map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/openfoodfacts|nhtsa|vpic\.|registry\.npmjs|metmuseum/i)});
  it("derives first-class crawl/spec tracing and strict 4N gates",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4nSource(src);expect(out).toContain("GO_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH");expect(out).toContain("REASSESS_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH");expect(out).toContain('base_sha:"9d30929caec004ef4c5fc2bbf2afa4eafeb4ff26"');expect(out).toContain('stage:"CRAWL"');expect(out).toContain('stage:"STANDARD_SPEC"');expect(out).toContain("executed_trace_documented_role_confirmed_recipe");expect(out).toContain("documentation_route_probe_attempts_zero")});
  it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4nSource(src),result=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4n.ts"}),errs=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);expect(errs.map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
