import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import type {DocEvidence} from "../src/experiment3wCore.js";
import type {Provider4A} from "../src/experiment4aContract.js";
import type {P1RequestHypothesis} from "../src/experiment4ap1Model.js";
import {alignHypothesesToSections5B5,extractRouteSections5B5,localizeHypothesisEvidence5B5,normalizedPathShape5B5,sectionRoleCoverage5B5} from "../src/experiment5b5Section.js";

const provider:Provider4A={case_id:"synthetic_case",candidate_id:"provider",name:"Synthetic API",start_url:"https://docs.example.test/api"};
const doc=(text:string,id="doc",candidate="provider"):DocEvidence=>({evidence_id:id,provider_candidate_id:candidate,requested_url:"https://docs.example.test/api",resolved_url:"https://docs.example.test/api",verified_at:"now",status:200,content_type:"text/html",body_fingerprint:`fp_${id}`,text,state:"ok"});
const h=(id:string,path:string,evidenceIds=["doc"]):P1RequestHypothesis=>({id,source_operation_id:id,origin:"https://api.example.test",full_path:path,proof_type:"synthetic",evidence_ids:evidenceIds,source_urls:["https://docs.example.test/api"],slots:[{id:"slot",name:"username",in:"path",required:true,auth_like:false,literals:[]}],input_bindings:{username:"slot"},literal_bindings:{},score:1,concrete_relation:true});
const html=`<p><a id="profile" name="profile"></a></p><h6>Resource Profile</h6><p><strong>URL pattern:</strong> <a href="https://api.example.test/resource/">https://api.example.test/resource/</a>{username}</p><p><strong>Data format:</strong></p><pre>{ "username": "string", "title": "string" }</pre><p><a id="stats" name="stats"></a></p><h6>Resource Stats</h6><p><strong>URL pattern:</strong> <a href="https://api.example.test/resource/">https://api.example.test/resource/</a>{username}/stats</p><pre>{ "rating": 1234, "wins": 10 }</pre>`;

describe("Experiment 5B5 normalized operation identity",()=>{
 it("normalizes variable spellings and ignores query/fragment",()=>{expect(normalizedPathShape5B5("https://api.example.test/resource/{username}?x=1#z")).toBe("/resource/{}");expect(normalizedPathShape5B5("/resource/{{name}}")).toBe("/resource/{}");expect(normalizedPathShape5B5("/resource/:user/")).toBe("/resource/{}");expect(normalizedPathShape5B5("/resource/{id}/stats")).not.toBe(normalizedPathShape5B5("/resource/{id}"))});
});

describe("Experiment 5B5 section extraction and alignment",()=>{
 it("extracts route-local profile and stats sections without sibling leakage",()=>{const a=extractRouteSections5B5([doc(html)],provider),b=extractRouteSections5B5([doc(html)],provider);expect(a.fingerprint).toBe(b.fingerprint);expect(a.sections).toHaveLength(2);const profile=a.sections.find(s=>s.path_shape==="/resource/{}")!;const stats=a.sections.find(s=>s.path_shape==="/resource/{}/stats")!;expect(profile.section_text).toContain("title");expect(profile.section_text).not.toContain("rating");expect(stats.section_text).toContain("rating");expect(stats.section_text).not.toContain('"title"')});
 it("aligns the exact profile path and transfers only its local evidence",()=>{const extracted=extractRouteSections5B5([doc(html)],provider),hyp=h("profile","/resource/{username}"),alignment=alignHypothesesToSections5B5([hyp],extracted.sections,provider),localized=localizeHypothesisEvidence5B5([hyp],extracted.sections,alignment,[doc(html)],new Set());expect(alignment.witnesses.has("profile")).toBe(true);expect(alignment.metrics.crossDocumentAlignmentsAccepted5b5).toBe(1);expect(localized.hypotheses[0].evidence_ids).not.toContain("doc");expect(localized.evidence).toHaveLength(1);expect(localized.evidence[0].text).toContain("title");expect(localized.evidence[0].text).not.toContain("rating")});
 it("gives required output support only from the aligned local section",()=>{const extracted=extractRouteSections5B5([doc(html)],provider),profile=extracted.sections.find(s=>s.path_shape==="/resource/{}")!,stats=extracted.sections.find(s=>s.path_shape==="/resource/{}/stats")!;const p=sectionRoleCoverage5B5(["username","title"],profile.section_text),s=sectionRoleCoverage5B5(["username","title"],stats.section_text);expect(p.supported_roles).toContain("title");expect(p.score).toBeGreaterThan(s.score)});
 it("rejects explicit method conflicts",()=>{const htmlPost=`<h2>Resource</h2><p>POST /resource/{id}</p><pre>{"title":"x"}</pre><h2>Other</h2><p>GET /other/{id}</p>`,extracted=extractRouteSections5B5([doc(htmlPost)],provider),alignment=alignHypothesesToSections5B5([h("get","/resource/{id}")],extracted.sections,provider);expect(alignment.witnesses.has("get")).toBe(false);expect(alignment.metrics.operationIdentityMethodConflictRejects5b5).toBeGreaterThan(0)});
 it("rejects non-equivalent ambiguous exact sections",()=>{const ambiguous=`<p><a id="one"></a></p><h6>One</h6><p>URL pattern: https://api.example.test/resource/{id}</p><pre>{"title":"one"}</pre><p><a id="two"></a></p><h6>Two</h6><p>URL pattern: https://api.example.test/resource/{id}</p><pre>{"title":"different"}</pre>`,extracted=extractRouteSections5B5([doc(ambiguous)],provider),alignment=alignHypothesesToSections5B5([h("get","/resource/{id}")],extracted.sections,provider);expect(alignment.witnesses.has("get")).toBe(false);expect(alignment.metrics.crossDocumentAlignmentAmbiguousRejects5b5).toBe(1)});
 it("cannot transfer a section from another provider candidate",()=>{const extracted=extractRouteSections5B5([doc(html,"foreign","other")],provider);expect(extracted.sections).toHaveLength(0)});
});

describe("Experiment 5B5 runtime neutrality",()=>{
 it("contains no development provider, case, route or exemplar hardcodes",async()=>{const files=["experiment5b5Section.ts","experiment5b5Planner.ts","experiment5b5Contract.ts","experiment5b5Derivation.ts"],text=(await Promise.all(files.map(f=>readFile(new URL(`../src/${f}`,import.meta.url),"utf8")))).join("\n");expect(text).not.toMatch(/chess\.com|collection-dev|magnuscarlsen|\berik\b|warnely|ipwhois|pokeapi|dictionaryapi|orbitalwiki|chess_player_metadata|country_alpha_metadata|english_word_definition_metadata|dns_a_record_metadata|ip_geolocation_metadata/i)});
});
