import {describe,expect,it} from "vitest";
import {FIVE_A_CASES,fiveAWorkloadFingerprint} from "../src/experiment5aCore.js";
import {buildFiveB3Report} from "../src/experiment5b3Decision.js";
import type {FiveB3Integrity} from "../src/experiment5b3Harness.js";

function integrity():FiveB3Integrity{return {ok:true,base_sha:"cd85224d9e21ba3e0ddf5de02e371872a2931c37",prereg_commit:"ae30ca15dd4db4cc6b24e979ba43f298a369f291",head_sha:"head",base_is_ancestor:true,changed_files:[],unexpected_files:[],first_5b3_commit:"ae30ca15dd4db4cc6b24e979ba43f298a369f291",prereg_unchanged:true,workload_fingerprint:fiveAWorkloadFingerprint(),runtime_provider_url_literals:0,errors:[]}}
function raw(){const picked:any[]=[];const fam=new Set<string>();for(const c of FIVE_A_CASES){if(picked.length>=6)break;if(!fam.has(c.family)){fam.add(c.family);picked.push(c)}}const ids=new Set(picked.map(c=>c.case_id)),caseEvidence=FIVE_A_CASES.map(c=>({case_id:c.case_id,family:c.family,success:ids.has(c.case_id)?{host:"x"}:null,elapsed_ms:1000})),recipes=picked.map((c,i)=>({case_id:c.case_id,provider_start_url:`https://provider${i}.example/docs`,semantic_identity_witness_5b2:{input_witnesses:[{}],input_output_bindings:[],projected_response_paths:["x"]},response_role_witness_5b:i===0?{mappings:[{output_role:"x",observed_path:"x"}]}:null,request_utility_recovered_5b3:i===1})),replay=picked.map(c=>({case_id:c.case_id,success:true})),rerankEvidence=FIVE_A_CASES.map((c,i)=>({case_id:c.case_id,phase:"deterministic_5b3",ordering_fingerprint:`provider_fp_${i}`,metrics:{providerOrderingNondeterminismRejects5b3:0,deterministicProviderCandidates5b3:120,deterministicProviderSelected5b3:12,deterministicProviderTaskOverlap5b3:4,deterministicProviderOutputSupport5b3:2,deterministicProviderApiEvidence5b3:1,deterministicProviderNoisePenalties5b3:0,deterministicProviderTieBreaks5b3:0}})),synthesisEvidence=picked.map((c,i)=>({case_id:c.case_id,provider_candidate_id:`p${i}`,request_ordering_fingerprint_5b3:`req_fp_${i}`,request_hypotheses:[{},{}],requestUtilityPrimaryDisplaced5b3:i===0?1:0,requestUtilitySecondProbeCalls5b3:i===0?1:0,requestUtilityRecoveredRecipes5b3:i===1?1:0,requestUtilityCandidates5b3:2,requestUtilityOutputCoverage5b3:300,semanticWitnessStrongerCandidateSuperseded5b2:0,responseGroundedResolverCalls5b:i===0?1:0,requestOrderingNondeterminismRejects5b3:0}));return {decision:"engine",fingerprint:"engine",caseEvidence,recipes,replay,rerankEvidence,synthesisEvidence,metrics:{total_llm_cost_usd:.1,rerankerCalls:0,replay_deltas:{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,schema_probe_calls:0},authLikeRenderedRequests:0,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,entityIncompatibleStructuralProbeAttempts:0,executedTraceOriginDriftRejects:0,executedTraceRequestMutationRejects:0,nonAuthRequestTextMutations:0,operationExternalRefFetches4u:0,validatorGraphMismatchRejects:0,duplicateProbeNetworkFetches:0,duplicateAcquisitionNetworkFetches:0,duplicateSpecProbeNetworkFetches:0}}}

describe("Experiment 5B3 strict decision",()=>{
 it("GO requires deterministic provider ordering, output-aware recovery, six successes and replay",()=>{const report=buildFiveB3Report(raw(),integrity());expect(report.decision).toBe("GO_5B3_DETERMINISTIC_PROVIDER_OUTPUT_AWARE_BEAM");expect(report.metrics.strict_successes).toBe(6);expect(report.metrics.replay_rate).toBe(1);expect(Object.values(report.gates).every(Boolean)).toBe(true)});
 it("rejects any stochastic provider reranker call",()=>{const x=raw();x.metrics.rerankerCalls=1;const report=buildFiveB3Report(x,integrity());expect(report.gates.stochastic_provider_reranker_zero).toBe(false);expect(report.decision).toBe("REASSESS_5B3_DETERMINISTIC_PROVIDER_OUTPUT_AWARE_BEAM")});
 it("requires request ordering fingerprints for every synthesis",()=>{const x=raw();delete x.synthesisEvidence[0].request_ordering_fingerprint_5b3;const report=buildFiveB3Report(x,integrity());expect(report.gates.request_ordering_fingerprint_all_synthesis).toBe(false);expect(report.decision).toBe("REASSESS_5B3_DETERMINISTIC_PROVIDER_OUTPUT_AWARE_BEAM")});
 it("does not accept beam activity without an actual recovered recipe",()=>{const x=raw();for(const r of x.recipes)r.request_utility_recovered_5b3=false;const report=buildFiveB3Report(x,integrity());expect(report.gates.output_aware_recovery_active).toBe(false);expect(report.decision).toBe("REASSESS_5B3_DETERMINISTIC_PROVIDER_OUTPUT_AWARE_BEAM")});
});
