import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {executeExpr,executeProgram,type ProjectionExpr} from "../src/experiment3xCore.js";
import {summarizeRelational4O,uniqueRowLookup4O,identityCompatible4O,rowLookupHasNumericIndex4O,validateRowLookupObserved4O} from "../src/experiment4oRelational.js";
import {allowedInputSources4O,deterministicProjection4O} from "../src/experiment4oCore.js";
import {deriveExperiment4oSource} from "../src/experiment4oDerivation.js";

const vin="1HGCM82633A004352";
function nhtsa(extra:any[]=[]){return {Count:140,Results:[{Value:vin,Variable:"VIN",VariableId:142},...extra,{Value:"HONDA",Variable:"Make",VariableId:26},{Value:"ACCORD",Variable:"Model",VariableId:28}]}}
function proof(body:any){return {hypothesis:{id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/api/vehicles/decodevin/{vin}?format=json",proof_type:"4n_executed_trace_documented_role_path",evidence_ids:["e"],source_urls:["https://api.example.test/api/vehicles/decodevin/sample?format=json"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://api.example.test/api/vehicles/decodevin/x?format=json",requested_at:new Date().toISOString(),final_url:"https://api.example.test/api/vehicles/decodevin/x?format=json",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:[],observed_path_count:0,bytes:100,error:null}} as any}

describe("4O relational response IR",()=>{
 it("induces a labeled repeated-row set",()=>{const s=summarizeRelational4O(nhtsa());expect(s.row_sets.length).toBeGreaterThan(0);const rs=s.row_sets.find(r=>r.array_path==="Results")!;expect(rs).toBeTruthy();expect(rs.label_field).toBe("Variable");expect(rs.value_field).toBe("Value");expect(rs.observed_labels).toContain("Make");expect(s.metrics.relationalRowSetsAccepted).toBeGreaterThan(0)});
 it("grounds make to one observed label and persists no numeric index",()=>{const s=summarizeRelational4O(nhtsa()),r=uniqueRowLookup4O(s,"make")!;expect(r.label).toBe("Make");expect(r.expr).toEqual({op:"ROW_LOOKUP",array_path:"Results",label_field:"Variable",label_value:"Make",value_field:"Value"});expect(rowLookupHasNumericIndex4O(r.expr)).toBe(false);expect(validateRowLookupObserved4O(r.expr,s)).toBe(true)});
 it("ROW_LOOKUP is invariant to row order and inserted unrelated rows",()=>{const expr:ProjectionExpr={op:"ROW_LOOKUP",array_path:"Results",label_field:"Variable",label_value:"Make",value_field:"Value"};const many=Array.from({length:49},(_,i)=>({Variable:`Noise ${i}`,Value:String(i)}));expect(executeExpr(expr,nhtsa(many),{})).toBe("HONDA");const reordered={Results:[{Variable:"Model",Value:"ACCORD"},{Variable:"Make",Value:"HONDA"},{Variable:"VIN",Value:vin}]};expect(executeExpr(expr,reordered,{})).toBe("HONDA")});
 it("ROW_LOOKUP rejects duplicate label, missing label and missing value",()=>{const expr:ProjectionExpr={op:"ROW_LOOKUP",array_path:"Results",label_field:"Variable",label_value:"Make",value_field:"Value"};expect(()=>executeExpr(expr,{Results:[{Variable:"Make",Value:"A"},{Variable:"Make",Value:"B"}]},{})).toThrow("row_lookup_match_not_unique");expect(()=>executeExpr(expr,{Results:[{Variable:"VIN",Value:vin}]},{})).toThrow("row_lookup_match_not_found");expect(()=>executeExpr(expr,{Results:[{Variable:"Make"},{Variable:"VIN",Value:vin}]},{})).toThrow("row_lookup_value_missing")});
 it("does not treat primitive or single-row arrays as relational row sets",()=>{expect(summarizeRelational4O({Results:[1,2,3]}).row_sets).toHaveLength(0);expect(summarizeRelational4O({Results:[{Variable:"Make",Value:"HONDA"}]}).row_sets).toHaveLength(0)});
 it("rejects object arrays without shared scalar schema",()=>{const s=summarizeRelational4O({Results:[{Variable:"Make",Value:"HONDA"},{Foo:{nested:1},Bar:[1,2]}]});expect(s.row_sets).toHaveLength(0);expect(s.metrics.relationalRowSetsRejectedNoSharedSchema).toBeGreaterThan(0)});
 it("enforces input-output semantic identity",()=>{expect(identityCompatible4O("vin","vin")).toBe(true);expect(identityCompatible4O("make","vin")).toBe(false);expect(allowedInputSources4O("vin",["vin"])).toEqual(["vin"]);expect(allowedInputSources4O("make",["vin"])).toEqual([])});
 it("compiles NHTSA-shaped vin plus make without numeric index",()=>{const s=summarizeRelational4O(nhtsa()),d=deterministicProjection4O(proof(nhtsa()),s,["vin"],["vin","make"])!;expect(d).toBeTruthy();expect(d.projection.vin).toEqual({op:"INPUT",name:"vin"});expect((d.projection.make as any).op).toBe("ROW_LOOKUP");expect(rowLookupHasNumericIndex4O(d.projection.make)).toBe(false);expect(executeProgram(d.projection as any,nhtsa(),{vin})).toEqual({vin,make:"HONDA"})});
 it("fails closed when make label is not uniquely grounded",()=>{const s=summarizeRelational4O({Results:[{Variable:"Make Name",Value:"A"},{Variable:"Make Code",Value:"B"},{Variable:"VIN",Value:vin}]});expect(uniqueRowLookup4O(s,"make")).toBeNull()});
 it("keeps FIELD and identity INPUT execution unchanged",()=>{expect(executeProgram({a:{op:"FIELD",path:"x"},vin:{op:"INPUT",name:"vin"}} as any,{x:7},{vin})).toEqual({a:7,vin})});
 it("keeps implementation provider-blind",async()=>{const paths=["experiment4oRelational.ts","experiment4oCore.ts","experiment4oPlanner.ts","experiment4oContract.ts"],src=(await Promise.all(paths.map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/nhtsa|vpic\.|openfoodfacts|metmuseum|registry\.npmjs/i)});
 it("derives strict 4O gates and frozen base",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4oSource(src);expect(out).toContain("GO_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION");expect(out).toContain("REASSESS_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION");expect(out).toContain('base_sha:"07997e9e791f159b118349ef55e5a45a1c92fa5e"');expect(out).toContain("row_lookup_confirmed_recipe");expect(out).toContain("forbidden_input_source_selections_zero");expect(out).toContain("numeric_index_row_lookup_recipes_zero")});
 it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4oSource(src),r=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4o.ts"});expect((r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
