import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import type {P1ProbeProof} from "../src/experiment4ap1Model.js";
import {deriveSemanticIdentityWitness5B2,outputInputCompatibility5B2,sanitizeProjectionInputs5B2,verifySemanticIdentityReplay5B2} from "../src/experiment5b2Semantics.js";
import {deriveExperiment5b2Source} from "../src/experiment5b2Derivation.js";
import {buildFiveB2Report,type FiveB2Integrity} from "../src/experiment5b2Harness.js";
import {FIVE_A_CASES,fiveAWorkloadFingerprint} from "../src/experiment5aCore.js";

const field=(path:string,leaf:string,value:any)=>({id:`f_${path}`,path,leaf,tokens:[leaf],sample_type:typeof value,sample_value:String(value),build_value_relations:[]});
function proof(fields:any[]):P1ProbeProof{return {hypothesis:{id:"h",source_operation_id:"o",origin:"https://example.invalid",full_path:"/x",proof_type:"test",evidence_ids:["e"],source_urls:["https://example.invalid/doc"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://example.invalid/x",requested_at:"now",final_url:"https://example.invalid/x",content_type:"application/json",response_body_fingerprint:"b",schema_fingerprint:"s",observed_fields:fields,observed_path_count:fields.length,bytes:1,error:null}}}

describe("Experiment 5B2 semantic identity roles",()=>{
 it("prefers exact word identity over definition containment",()=>{const p=proof([field("0.meanings.0.definitions.0.definition","definition",'"Hello!" or an equivalent greeting.'),field("0.word","word","hello")]),projection={word:{op:"INPUT",name:"word"},definition:{op:"FIELD",path:"0.meanings.0.definitions.0.definition"}},r=deriveSemanticIdentityWitness5B2({inputNames:["word"],input:{word:"hello"},projection,proof:p});expect(r.ok).toBe(true);expect(r.witness!.input_witnesses[0].observed_path).toBe("0.word");expect(r.witness!.input_witnesses[0].relation).toBe("normalized_equal");expect(r.metrics.semanticWitnessDescriptiveTextRejects5b2).toBeGreaterThan(0);expect(r.metrics.semanticWitnessStrongerCandidateSuperseded5b2).toBe(0)});
 it("rejects pagination text as an identifier witness",()=>{const p=proof([field("items.0.page","page","1342-1342"),field("items.0.title","title","Unrelated")]),projection={id:{op:"INPUT",name:"book_id"},title:{op:"FIELD",path:"items.0.title"}},r=deriveSemanticIdentityWitness5B2({inputNames:["book_id"],input:{book_id:1342},projection,proof:p});expect(r.ok).toBe(false);expect(r.metrics.semanticWitnessPaginationRejects5b2).toBeGreaterThan(0)});
 it("accepts exact numeric identifier in the same entity",()=>{const p=proof([field("items.0.id","id",1342),field("items.0.title","title","Book")]),projection={id:{op:"INPUT",name:"book_id"},title:{op:"FIELD",path:"items.0.title"}},r=deriveSemanticIdentityWitness5B2({inputNames:["book_id"],input:{book_id:1342},projection,proof:p});expect(r.ok).toBe(true);expect(["normalized_equal","numeric_equal"]).toContain(r.witness!.input_witnesses[0].relation)});
 it("accepts composite owner/repository identity",()=>{const p=proof([field("full_name","full_name","torvalds/linux"),field("default_branch","default_branch","master")]),projection={full_name:{op:"FIELD",path:"full_name"},default_branch:{op:"FIELD",path:"default_branch"}},r=deriveSemanticIdentityWitness5B2({inputNames:["owner","repository"],input:{owner:"torvalds",repository:"linux"},projection,proof:p});expect(r.ok).toBe(true);expect(r.witness!.input_witnesses).toHaveLength(2);expect(r.witness!.input_witnesses.every((x:any)=>x.relation==="composite_contains_all")).toBe(true)});
});

describe("Experiment 5B2 INPUT/output compatibility",()=>{
 it("rejects human name copied from a code input",()=>{expect(outputInputCompatibility5B2("country_name","country_code").ok).toBe(false);const s=sanitizeProjectionInputs5B2({country_code:{op:"INPUT",name:"country_code"},country_name:{op:"INPUT",name:"country_code"},region:{op:"FIELD",path:"country.region"}});expect(s.projection.country_code).toBeTruthy();expect(s.projection.country_name).toBeUndefined();expect(s.metrics.projectionHumanNameFromCodeRejects5b2).toBe(1)});
 it("allows compatible identity/name copies",()=>{expect(outputInputCompatibility5B2("name","pokemon_name").ok).toBe(true);expect(outputInputCompatibility5B2("id","book_id").ok).toBe(true);expect(outputInputCompatibility5B2("username","username").ok).toBe(true)});
});

describe("Experiment 5B2 semantic witness replay",()=>{
 it("re-verifies exact identity on changed replay input",()=>{const p=proof([field("word","word","hello"),field("definition","definition","Greeting")]),projection={word:{op:"INPUT",name:"word"},definition:{op:"FIELD",path:"definition"}},r=deriveSemanticIdentityWitness5B2({inputNames:["word"],input:{word:"hello"},projection,proof:p});expect(r.ok).toBe(true);expect(verifySemanticIdentityReplay5B2(r.witness!,["word"],{word:"world"},{word:"world",definition:"The earth"})).toBe(true);expect(verifySemanticIdentityReplay5B2(r.witness!,["word"],{word:"world"},{word:"wrong",definition:"world in prose"})).toBe(false)});
});

function integrity():FiveB2Integrity{return {ok:true,base_sha:"8648ab3a97b98aaa61ec4feec7752f01423b36c4",prereg_commit:"57430c5b2a908bfa7f6fec4d668c9d07ed2d1fd7",head_sha:"head",base_is_ancestor:true,changed_files:[],unexpected_files:[],first_5b2_commit:"57430c5b2a908bfa7f6fec4d668c9d07ed2d1fd7",prereg_unchanged:true,workload_fingerprint:fiveAWorkloadFingerprint(),runtime_provider_url_literals:0,errors:[]}}
function syntheticRaw(n:number){const picked:any[]=[];const fam=new Set<string>();for(const c of FIVE_A_CASES){if(picked.length>=n)break;if(!fam.has(c.family)){fam.add(c.family);picked.push(c)}}for(const c of FIVE_A_CASES){if(picked.length>=n)break;if(!picked.includes(c))picked.push(c)}const ids=new Set(picked.map(c=>c.case_id)),caseEvidence=FIVE_A_CASES.map(c=>({case_id:c.case_id,family:c.family,success:ids.has(c.case_id)?{provider:"x"}:null,elapsed_ms:1000})),recipes=picked.map((c,i)=>({case_id:c.case_id,provider_start_url:`https://provider${i}.example/docs`,semantic_identity_witness_5b2:{input_witnesses:[{input_name:"x",observed_path:"x",relation:"normalized_equal"}],input_output_bindings:[],projected_response_paths:["y"]},response_role_witness_5b:i===0?{mappings:[{output_role:"y",observed_path:"y"}]}:null,cross_graph_recovered_5b2:i===1})),replay=picked.map(c=>({case_id:c.case_id,success:true})),rerankEvidence=FIVE_A_CASES.map(c=>({case_id:c.case_id}));return {decision:"engine",fingerprint:"engine",caseEvidence,recipes,replay,rerankEvidence,synthesisEvidence:[{strictInheritedRepairSuccesses5b2:1,crossGraphSecondHypothesisAttempts5b2:1,crossGraphAdditionalProbeCalls5b2:1,crossGraphRecoveredRecipes5b2:1,semanticWitnessStrongerCandidateSuperseded5b2:0,cross_graph_beam_5b2:[{},{}]}],metrics:{total_llm_cost_usd:.1,replay_deltas:{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,schema_probe_calls:0},authLikeRenderedRequests:0,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,entityIncompatibleStructuralProbeAttempts:0,executedTraceOriginDriftRejects:0,executedTraceRequestMutationRejects:0,nonAuthRequestTextMutations:0,operationExternalRefFetches4u:0,validatorGraphMismatchRejects:0,duplicateProbeNetworkFetches:0,duplicateAcquisitionNetworkFetches:0,duplicateSpecProbeNetworkFetches:0}}}

describe("Experiment 5B2 decision and generated source",()=>{
 it("retains six-of-eighteen plus replay and treatment gates",()=>{expect(buildFiveB2Report(syntheticRaw(6),integrity()).decision).toBe("GO_5B2_SEMANTIC_IDENTITY_WITNESS_CROSS_GRAPH_BEAM");expect(buildFiveB2Report(syntheticRaw(5),integrity()).decision).toBe("REASSESS_5B2_SEMANTIC_IDENTITY_WITNESS_CROSS_GRAPH_BEAM")});
 it("generates 5B2 persistence and replay enforcement",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment5b2Source(src);expect(out).toContain('from "./experiment5b2Planner.js"');expect(out).toContain('from "./experiment5b2Contract.js"');expect(out).toContain("semantic_identity_witness_5b2");expect(out).toContain("verifySemanticIdentityReplay5B2");expect(out).toContain("results/experiment-5b2-engine")});
 it("does not delegate to synthesize4s and caps beam at two",async()=>{const text=await readFile(new URL("../src/experiment5b2Planner.ts",import.meta.url),"utf8");expect(text).not.toContain("synthesize4s(");expect(text).toContain("ordered.slice(0,2)")});
 it("keeps runtime free of development provider/case hardcodes",async()=>{const files=["experiment5b2Semantics.ts","experiment5b2Planner.ts","experiment5b2Contract.ts"],text=(await Promise.all(files.map(f=>readFile(new URL(`../src/${f}`,import.meta.url),"utf8")))).join("\n");expect(text).not.toMatch(/warnely|dictionaryapi|crossref|pokeapi|hackmyip|country_alpha_metadata|english_word_definition_metadata|public_domain_book_metadata|dns_a_record_metadata/i)});
});
