import {describe,it,expect} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {executeProgram} from "../src/experiment3xCore.js";
import {summarizeRelational4O,rowLookupHasNumericIndex4O} from "../src/experiment4oRelational.js";
import {allowedInputSources4Q,deterministicProjection4Q} from "../src/experiment4qCore.js";
import {identityCompatible4Q,preferEquivalentExecutedTraces4Q,representationRank4Q} from "../src/experiment4qPreference.js";
import {plannerSchema4Q} from "../src/experiment4qPlanner.js";
import {boundedOrderedMap4P} from "../src/experiment4pSchedule.js";
import {deriveExperiment4qSource} from "../src/experiment4qDerivation.js";

function hyp(id:string,traceId:string,path:string,score=1){return {id,source_operation_id:`trace4n_${traceId}`,origin:"https://api.example.test",full_path:path,proof_type:"4n_executed_trace_documented_role_path",evidence_ids:[`e-${id}`],source_urls:[`https://api.example.test${path}`],slots:[{id:`s-${id}`,name:"vin",in:"path",required:true,auth_like:false,literals:[]}],input_bindings:{vin:`s-${id}`},literal_bindings:{},score,concrete_relation:true} as any}
function trace(trace_id:string,url:string,content_type:string,text:string){return {trace_id,case_id:"vin_vehicle_metadata",provider_candidate_id:"p",stage:"CRAWL",parent_evidence_ids:[`e-${trace_id}`],requested_url:url,final_url:url,requested_at:new Date().toISOString(),disposition:"success",content_type,body_fingerprint:"bf",body_bytes:text.length,response_text:text,network_origin:"network",error:null} as any}
function field(id:string,path:string,leaf:string,tokens:string[],rels:string[]=[]){return {id,path,leaf,tokens,sample_type:"string",sample_value:"x",build_value_relations:rels}}
function proof(fields:any[]){return {hypothesis:{id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/x/{name}",proof_type:"documented",evidence_ids:["e"],source_urls:[],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:true},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://api.example.test/x/a",requested_at:new Date().toISOString(),final_url:"https://api.example.test/x/a",content_type:"application/json",response_body_fingerprint:"bf",schema_fingerprint:"sf",observed_fields:fields,observed_path_count:fields.length,bytes:100,error:null}} as any}

describe("4Q evidence preference and identity projection",()=>{
 it("treats generic output name as identity-equivalent to meal_name",()=>{expect(identityCompatible4Q("name","meal_name")).toBe(true);expect(allowedInputSources4Q("name",["meal_name"])).toEqual(["meal_name"])});
 it("preserves exact VIN identity",()=>expect(identityCompatible4Q("vin","vin")).toBe(true));
 it("rejects make from VIN",()=>expect(identityCompatible4Q("make","vin")).toBe(false));
 it("rejects category from meal_name and version from package_name",()=>{expect(identityCompatible4Q("category","meal_name")).toBe(false);expect(identityCompatible4Q("version","package_name")).toBe(false)});
 it("prefers identity INPUT before an alternate same-name API FIELD",()=>{const p=proof([field("meal","meals.0.strMeal","strMeal",["meal","name"]),field("cat","meals.0.strCategory","strCategory",["category"])]),d=deterministicProjection4Q(p,null,["meal_name"],["name","category"])!;expect(d.projection.name).toEqual({op:"INPUT",name:"meal_name"});expect(d.projection.category).toEqual({op:"FIELD",path:"meals.0.strCategory"});expect(executeProgram(d.projection as any,{meals:[{strMeal:"Spicy Arrabiata Penne",strCategory:"Vegetarian"}]},{meal_name:"Arrabiata"})).toEqual({name:"Arrabiata",category:"Vegetarian"})});
 it("retains ROW_LOOKUP while identity VIN is preserved",()=>{const body={Results:[{Variable:"VIN",Value:"ABC"},{Variable:"Make",Value:"HONDA"}]},s=summarizeRelational4O(body),d=deterministicProjection4Q(proof([]),s,["vin"],["vin","make"])!;expect(d.projection.vin).toEqual({op:"INPUT",name:"vin"});expect((d.projection.make as any).op).toBe("ROW_LOOKUP");expect(rowLookupHasNumericIndex4O(d.projection.make)).toBe(false)});
 it("ranks valid JSON above CSV and XML",()=>{const j=trace("j","https://api.example.test/decode/X?format=json","application/json",'{"Results":[]}'),c=trace("c","https://api.example.test/decode/X?format=csv","text/csv","a,b"),x=trace("x","https://api.example.test/decode/X?format=xml","application/xml","<x/>");expect(representationRank4Q(j)).toBeGreaterThan(representationRank4Q(x));expect(representationRank4Q(x)).toBeGreaterThan(representationRank4Q(c))});
 it("moves already-executed JSON ahead of equivalent CSV without dropping evidence",()=>{const csv=trace("c","https://api.example.test/decode/X?format=csv","text/csv","a,b"),json=trace("j","https://api.example.test/decode/X?format=json","application/json",'{"Results":[]}'),packet=[hyp("csv","c","/decode/{vin}?format=csv",50),hyp("other","o","/other/{vin}",100),hyp("json","j","/decode/{vin}?format=json",10)],r=preferEquivalentExecutedTraces4Q(packet,[csv,json]);expect(r.packet.map(x=>x.id)).toEqual(["json","other","csv"]);expect(r.packet).toHaveLength(packet.length);expect(r.metrics.representationPreferenceSwaps).toBeGreaterThan(0);expect(r.metrics.lowerPreferenceEquivalentTraceBeforeJson).toBe(0)});
 it("does not reorder non-equivalent operations merely because one is JSON",()=>{const csv=trace("c","https://api.example.test/decodevalues/X?format=csv","text/csv","a,b"),json=trace("j","https://api.example.test/decode/X?format=json","application/json",'{"Results":[]}'),packet=[hyp("csv","c","/decodevalues/{vin}?format=csv",50),hyp("json","j","/decode/{vin}?format=json",10)],r=preferEquivalentExecutedTraces4Q(packet,[csv,json]);expect(r.packet.map(x=>x.id)).toEqual(["csv","json"])});
 it("fallback schema offers identity input only to compatible output",()=>{const s:any=plannerSchema4Q([proof([])],["meal_name"],["name","category"]),p=s.schema.properties.output_bindings.properties;expect(p.name.properties.source_id.enum).toContain("TASK_INPUT:meal_name");expect(p.category.properties.source_id.enum).not.toContain("TASK_INPUT:meal_name")});
 it("planner and validator use the same identity predicate",async()=>{const [planner,contract]=await Promise.all([readFile(new URL("../src/experiment4qPlanner.ts",import.meta.url),"utf8"),readFile(new URL("../src/experiment4qContract.ts",import.meta.url),"utf8")]);expect(planner).toContain("allowedInputSources4Q");expect(contract).toContain("identityCompatible4Q(output,e.name)")});
 it("keeps rerank concurrency bounded at three and result order stable",async()=>{let active=0,max=0;const items=[40,5,20,1,10,3],r=await boundedOrderedMap4P(items,3,async(ms,i)=>{active++;max=Math.max(max,active);await new Promise(res=>setTimeout(res,ms));active--;return i});expect(max).toBeLessThanOrEqual(3);expect(r.maxObservedConcurrency).toBeLessThanOrEqual(3);expect(r.results).toEqual(items.map((_,i)=>i))});
 it("keeps 4Q source provider-blind",async()=>{const paths=["experiment4qCore.ts","experiment4qPlanner.ts","experiment4qContract.ts","experiment4qPreference.ts","experiment4qRequest.ts"],src=(await Promise.all(paths.map(p=>readFile(new URL(`../src/${p}`,import.meta.url),"utf8")))).join("\n");expect(src).not.toMatch(/nhtsa|vpic\.|openfoodfacts|metmuseum|registry\.npmjs|themealdb|cocktaildb/i)});
 it("derives frozen 4P base, JSON preference gate and preserved concurrency",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4qSource(src);expect(out).toContain("GO_4Q_EVIDENCE_PREFERENCE_IDENTITY_PRESERVING_PROJECTION");expect(out).toContain('base_sha:"89360e887796f967d987d9c08a4841d457cb66c1"');expect(out).toContain("representation_json_preference_integrity");expect(out).toContain("identity_projection_integrity");expect(out).toContain("boundedOrderedMap4P(FOUR_A_CASES,rerankConcurrencyLimit4p")});
 it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4qSource(src),r=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4q.ts"});expect((r.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
