import {readFile} from "node:fs/promises";
import {describe,it,expect} from "vitest";
import {specSummaryR6,extractDocumentedOperationsR6,materializeSelectionR6,operationPacketFingerprintR6} from "../src/experiment4ar6Core.js";
import {validate4ar6} from "../src/experiment4ar6Contract.js";
import {RecoveryLedger} from "../src/experiment3yrCore.js";

const ev=(text:string,url="https://api.example.test/openapi.json"):any=>({evidence_id:"p-e01",provider_candidate_id:"p",requested_url:url,resolved_url:url,verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"application/json",body_fingerprint:"x",text,state:"ok"});

describe("4A-R6 documented operation IR",()=>{
 it("preserves documented server base path and endpoint parameter names",()=>{const spec={openapi:"3.0.0",servers:[{url:"https://api.example.test/api/v1"}],paths:{"/artworks/{id}":{get:{parameters:[{name:"id",in:"path",required:true,schema:{type:"integer"}}],responses:{"200":{content:{"application/json":{schema:{type:"object",properties:{data:{type:"object",properties:{id:{type:"integer"},title:{type:"string"}}}}}}}}}}}}}};const evidence=[ev(specSummaryR6(spec,"artwork_object_metadata","https://api.example.test/openapi.json"))],ops=extractDocumentedOperationsR6(evidence,"artwork_object_metadata");expect(ops[0]).toMatchObject({origin:"https://api.example.test",base_path:"/api/v1",operation_path:"/artworks/{id}",full_path:"/api/v1/artworks/{id}"});expect(ops[0].path_parameters.map(x=>x.name)).toEqual(["id"]);expect(ops[0].response_paths).toEqual(expect.arrayContaining(["data.id","data.title"]));});
 it("maps a task input to the documented parameter without renaming it",()=>{const spec={openapi:"3.0.0",servers:[{url:"https://api.example.test/api/v1"}],paths:{"/artworks/{id}":{get:{parameters:[{name:"id",in:"path",required:true}],responses:{"200":{content:{"application/json":{schema:{properties:{data:{properties:{id:{type:"integer"},title:{type:"string"}}}}}}}}}}}}}};const evidence=[ev(specSummaryR6(spec,"artwork_object_metadata","https://api.example.test/openapi.json"))],ops=extractDocumentedOperationsR6(evidence,"artwork_object_metadata"),op=ops[0],idIndex=op.response_paths.indexOf("data.id"),titleIndex=op.response_paths.indexOf("data.title"),m=materializeSelectionR6("artwork_object_metadata","p",ops,{decision:"COMPILE",operation_index:0,path_bindings:[{parameter_index:0,input_name:"object_id"}],query_bindings:[],output_mappings:[{output_name:"id",source_kind:"FIELD",response_path_index:idIndex,input_name:null},{output_name:"title",source_kind:"FIELD",response_path_index:titleIndex,input_name:null}],reason:"fit"});expect(m.raw.path_template).toBe("/api/v1/artworks/{id}");expect(m.raw.path_bindings).toEqual({id:"$input.object_id"});expect(m.raw.path_template).not.toContain("object_id");});
 it("allows only documented query literals",()=>{const spec={openapi:"3.0.0",servers:[{url:"https://api.example.test"}],paths:{"/decode/{vin}":{get:{parameters:[{name:"vin",in:"path",required:true},{name:"format",in:"query",required:true,schema:{enum:["json","xml"]}}],responses:{"200":{content:{"application/json":{schema:{properties:{vin:{type:"string"},make:{type:"string"}}}}}}}}}}}};const ops=extractDocumentedOperationsR6([ev(specSummaryR6(spec,"vin_vehicle_metadata","https://api.example.test/openapi.json"))],"vin_vehicle_metadata");expect(ops[0].query_parameters[0]).toMatchObject({name:"format",literals:["json","xml"]});expect(()=>materializeSelectionR6("vin_vehicle_metadata","p",ops,{decision:"COMPILE",operation_index:0,path_bindings:[{parameter_index:0,input_name:"vin"}],query_bindings:[{parameter_index:0,source_kind:"LITERAL",input_name:null,literal_index:9}],output_mappings:[{output_name:"vin",source_kind:"INPUT",response_path_index:null,input_name:"vin"},{output_name:"make",source_kind:"FIELD",response_path_index:ops[0].response_paths.indexOf("make"),input_name:null}],reason:"x"})).toThrow(/literal_index/);});
 it("extracts parameter names and JSON response paths from exact URL examples",()=>{const text='Example: https://api.example.test/?name=peter\n```json\n{"name":"peter","gender":"male"}\n```';const ops=extractDocumentedOperationsR6([ev(text,"https://example.test/docs")],"gender_estimate_by_name");const op=ops.find(x=>x.origin==="https://api.example.test")!;expect(op.query_parameters.map(x=>x.name)).toContain("name");expect(op.response_paths).toEqual(expect.arrayContaining(["name","gender"]));});
 it("validates a mechanically materialized contract against the same operation proof",()=>{const spec={openapi:"3.0.0",servers:[{url:"https://api.example.test"}],paths:{"/art/{id}":{get:{parameters:[{name:"id",in:"path",required:true}],responses:{"200":{content:{"application/json":{schema:{properties:{id:{type:"integer"},title:{type:"string"}}}}}}}}}}}};const evidence=[ev(specSummaryR6(spec,"artwork_object_metadata","https://api.example.test/openapi.json"))],ops=extractDocumentedOperationsR6(evidence,"artwork_object_metadata"),m=materializeSelectionR6("artwork_object_metadata","p",ops,{decision:"COMPILE",operation_index:0,path_bindings:[{parameter_index:0,input_name:"object_id"}],query_bindings:[],output_mappings:[{output_name:"id",source_kind:"INPUT",response_path_index:null,input_name:"object_id"},{output_name:"title",source_kind:"FIELD",response_path_index:ops[0].response_paths.indexOf("title"),input_name:null}],reason:"x"}),v=validate4ar6(m.raw,{case_id:"artwork_object_metadata",candidate_id:"p",name:"P",start_url:"https://example.test"},evidence,new RecoveryLedger());expect(v.errors).toEqual([]);expect(v.operation_proof.operation_id).toBe(ops[0].operation_id);});
 it("operation packet fingerprints change when documented facts change",()=>{const a:any=[{operation_id:"x",origin:"https://a.test",base_path:"",operation_path:"/x",full_path:"/x",method:"GET",path_parameters:[],query_parameters:[],response_paths:["id"],evidence_ids:["e"],source_urls:["https://a.test/docs"],proof_type:"openapi",score:1}],b=structuredClone(a);b[0].response_paths.push("name");expect(operationPacketFingerprintR6(a)).not.toBe(operationPacketFingerprintR6(b));});
 it("contains no provider-specific seeds and keeps frozen derivation anchors",async()=>{const core=await readFile(new URL("../src/experiment4ar6Core.ts",import.meta.url),"utf8"),planner=await readFile(new URL("../src/experiment4ar6Planner.ts",import.meta.url),"utf8"),runner=await readFile(new URL("../src/experiment4ar6.ts",import.meta.url),"utf8");for(const s of [core,planner])expect(s).not.toMatch(/thecocktaildb|openfoodfacts|genderize|metmuseum|nhtsa|registry\.npmjs|openlibrary|ziptastic/i);expect(runner).toContain('base_sha:"a5beb7049dcceadcd7e40b6190fa453ba22e4f79"');expect(runner).toContain("GO_4A_R6_DOCUMENTED_OPERATION_IR_RECOVERY");});
});
