import {readFile} from "node:fs/promises";
import {describe,it,expect} from "vitest";
import {composeVerifiedOpenApiServerPath,exactOriginGrounding,packEvidenceR5R,FOUR_AR5R_EVIDENCE_MAX_CHARS} from "../src/experiment4ar5rCore.js";

const evidence=(text:string,resolved="https://api.example.test/openapi.json"):any=>({evidence_id:"p-e01",provider_candidate_id:"p",requested_url:resolved,resolved_url:resolved,verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"application/json",body_fingerprint:"x",text,state:"ok"});

describe("4A-R5R evidence alignment recovery",()=>{
 it("composes a verified OpenAPI server path with an exact GET operation",()=>{const text='R5_VERIFIED_API_SPEC\n'+JSON.stringify({servers:[{url:"https://api.example.test/api/v1"}],operations:[{method:"GET",path:"/search/{id}"}]});const raw={decision:"COMPILE",base_url:"https://api.example.test/api/v1",path_template:"/search/{id}",evidence_ids:["p-e01"]};expect(composeVerifiedOpenApiServerPath(raw,[evidence(text)],"p")).toMatchObject({base_url:"https://api.example.test",path_template:"/api/v1/search/{id}",proof:{kind:"openapi_server_path"}});});
 it("refuses OpenAPI composition when the operation path was not documented",()=>{const text='R5_VERIFIED_API_SPEC\n'+JSON.stringify({servers:[{url:"https://api.example.test/api/v1"}],operations:[{method:"GET",path:"/other"}]});const raw={decision:"COMPILE",base_url:"https://api.example.test/api/v1",path_template:"/search",evidence_ids:["p-e01"]};expect(composeVerifiedOpenApiServerPath(raw,[evidence(text)],"p")).toBeNull();});
 it("grounds only the exact HTTPS origin of cited verified evidence",()=>{const raw={decision:"COMPILE",base_url:"https://api.example.test",evidence_ids:["p-e01"]};expect(exactOriginGrounding(raw,[evidence("docs without literal origin")],"p")).toMatchObject({source:"resolved_url_origin",origin:"https://api.example.test"});const wrong=evidence("docs","https://docs.example.test/reference");expect(exactOriginGrounding(raw,[wrong],"p")).toBeNull();});
 it("does not allow cross-provider evidence to ground an origin",()=>{const e=evidence("docs");e.provider_candidate_id="other";expect(exactOriginGrounding({decision:"COMPILE",base_url:"https://api.example.test",evidence_ids:["p-e01"]},[e],"p")).toBeNull();});
 it("caps and diversifies evidence packets below the R5 52k boundary",()=>{const spec=evidence('R5_VERIFIED_API_SPEC\n'+JSON.stringify({operation_count:1,response_property_count:2,operations:[{path:"/{package_name}",response_properties:["name","version"]}]}));const api={...evidence("GET /pkg response name version parameter package_name","https://api.example.test/docs"),evidence_id:"p-e02",content_type:"text/html"};const prose={...evidence("package_name name version ".repeat(1000),"https://api.example.test/guide"),evidence_id:"p-e03",content_type:"text/html"};const packet=packEvidenceR5R([prose,api,spec],"npm_package_metadata");expect(packet.total_chars).toBeLessThanOrEqual(FOUR_AR5R_EVIDENCE_MAX_CHARS);expect(FOUR_AR5R_EVIDENCE_MAX_CHARS).toBe(18000);expect(packet.items.some((x:any)=>x.evidence_class==="verified_spec")).toBe(true);expect(packet.stats.selected_chars_by_group.spec).toBeGreaterThan(0);expect(packet.stats.selected_chars_by_group.api).toBeGreaterThan(0);});
 it("deduplicates near-identical evidence windows",()=>{const a=evidence("GET endpoint response name version package_name ".repeat(100));const b={...a,evidence_id:"p-e02",resolved_url:"https://api.example.test/docs2"};const packet=packEvidenceR5R([a,b],"npm_package_metadata");expect(packet.stats.dropped.duplicate).toBeGreaterThanOrEqual(1);});
 it("keeps R5R provider-blind and derivation anchors intact",async()=>{const base=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),core=await readFile(new URL("../src/experiment4ar5rCore.ts",import.meta.url),"utf8"),contract=await readFile(new URL("../src/experiment4ar5rContract.ts",import.meta.url),"utf8"),planner=await readFile(new URL("../src/experiment4ar5rPlanner.ts",import.meta.url),"utf8");expect(base).toContain('import {resolveSelected,providerSelectionFingerprint} from "./experiment3vCore.js";');expect(base).toContain('"GO_4A_R_BREADTH_RECOVERY":"REASSESS_4A_R_BREADTH_RECOVERY"');for(const s of [core,contract,planner])expect(s).not.toMatch(/thecocktaildb|openfoodfacts|genderize|metmuseum|nhtsa|registry\.npmjs|openlibrary/i);});
});
