import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {deriveExperiment5b8Source} from "../src/experiment5b8Derivation.js";
import {deriveExperiment5b8PlannerSource} from "../src/experiment5b8PlannerDerivation.js";

describe("Experiment 5B8 generated benchmark integrity",()=>{
 it("produces syntactically valid generated benchmark and planner TypeScript",async()=>{const core=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),planner=await readFile(new URL("../src/experiment5b6Planner.ts",import.meta.url),"utf8"),outs=[deriveExperiment5b8Source(core),deriveExperiment5b8PlannerSource(planner)];for(const [i,out] of outs.entries()){const result=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:`generated-5b8-${i}.ts`}),errors=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"));expect(errors).toEqual([])}});
 it("replaces only the query source, preserves 5B6 compiler determinism, and persists full 5B8 audit lineage",async()=>{const planner=await readFile(new URL("../src/experiment5b6Planner.ts",import.meta.url),"utf8"),out=deriveExperiment5b8PlannerSource(planner);expect(out).toContain('import {queryCompilerDeterminism5B6} from "./experiment5b6Query.js"');expect(out).toContain('from "./experiment5b8Gate.js"');expect(out).toContain("buildGatedQueryHypotheses5B8(baseEvidence,provider)");expect(out).toContain("queryCompilerDeterminism5B6(baseEvidence,provider)");expect(out).toContain("querySemanticGateDeterminism5B8(baseEvidence,provider)");expect(out).toContain("query_semantic_gate_witness_5b8");expect(out).toContain("query_semantic_audits_5b8:query.audits");expect(out).toContain("dedup.slice(0,2)")});
 it("preserves strict semantic replay and 5B6 query witness in generated benchmark",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment5b8Source(src);expect(out).toContain('from "./.generated-experiment5b8Planner.js"');expect(out).toContain("query_semantic_gate_witness_5b8");expect(out).toContain("query_operation_witness_5b6");expect(out).toContain("verifySemanticIdentityReplay5B2");expect(out).toContain("results/experiment-5b8-engine")});
});
