import {readFile} from "node:fs/promises";
import {describe,it,expect} from "vitest";
import {deterministicRerankR5,extractEvidenceFrontierR5,packEvidenceR5,specSummaryR5,fourAr5Sha} from "../src/experiment4ar5Core.js";

const broad=[{candidate_id:"a",lexical_rank:2,name:"A",description:"",category:"",auth:"",https:"true",link:"https://a.test",score:1},{candidate_id:"b",lexical_rank:1,name:"B",description:"",category:"",auth:"",https:"true",link:"https://b.test",score:1}];

describe("4A-R5 deterministic evidence recovery",()=>{
 it("sorts scored providers deterministically with frozen tie breaks",()=>{const rows=[{candidate_id:"a",functional_fit:4,evidence_likelihood:3,anonymous_get_likelihood:5},{candidate_id:"b",functional_fit:4,evidence_likelihood:3,anonymous_get_likelihood:5}];expect(deterministicRerankR5(rows,broad).map(x=>x.candidate_id)).toEqual(["b","a"]);});
 it("weights functional fit ahead of documentation and anonymous likelihood",()=>{const rows=[{candidate_id:"a",functional_fit:5,evidence_likelihood:1,anonymous_get_likelihood:1},{candidate_id:"b",functional_fit:3,evidence_likelihood:5,anonymous_get_likelihood:5}];expect(deterministicRerankR5(rows,broad)[0].candidate_id).toBe("a");});
 it("extracts same-domain spec config references and rejects cross-domain links",()=>{const html='<script>const specUrl="/openapi.json"</script><a href="https://evil.test/swagger.json">bad</a>';const rows=extractEvidenceFrontierR5("https://docs.example.test/start","https://docs.example.test/start",html,"e1",(a,b)=>new URL(a).hostname===new URL(b).hostname,"npm_package_metadata");expect(rows.some(x=>x.target_url==="https://docs.example.test/openapi.json"&&x.accepted&&x.kind==="spec")).toBe(true);expect(rows.some(x=>x.target_url.includes("evil.test")&&!x.accepted)).toBe(true);});
 it("summarizes GET response properties from a local OpenAPI schema",()=>{const spec={openapi:"3.0.0",paths:{"/pkg/{name}":{get:{parameters:[{name:"name",in:"path"}],responses:{"200":{content:{"application/json":{schema:{type:"object",properties:{name:{type:"string"},version:{type:"string"}}}}}}}}}}};const text=specSummaryR5(spec,"npm_package_metadata");expect(text).toContain('"name"');expect(text).toContain('"version"');expect(text).toContain('"operation_count": 1');});
 it("packs spec evidence before prose deterministically",()=>{const docs:any[]=[{evidence_id:"e2",provider_candidate_id:"p",resolved_url:"https://x.test/about",requested_url:"",verified_at:"",status:200,content_type:"text/html",body_fingerprint:"2",text:"general prose",state:"ok"},{evidence_id:"e1",provider_candidate_id:"p",resolved_url:"https://x.test/openapi.json",requested_url:"",verified_at:"",status:200,content_type:"application/json",body_fingerprint:"1",text:'R5_VERIFIED_API_SPEC\n{"operation_count":1,"response_property_count":2,"operations":[{"path":"/{package_name}","response_properties":["name","version"]}]}',state:"ok"}];const p1=packEvidenceR5(docs,"npm_package_metadata"),p2=packEvidenceR5([...docs].reverse(),"npm_package_metadata");expect(p1.items[0].evidence_id).toBe("e1");expect(p1.fingerprint).toBe(p2.fingerprint);});
 it("evidence packet fingerprint changes when structural evidence changes",()=>{expect(fourAr5Sha({a:1})).not.toBe(fourAr5Sha({a:2}));});
 it("keeps derivation anchors and provider-blind R5 source",async()=>{const base=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),core=await readFile(new URL("../src/experiment4ar5Core.ts",import.meta.url),"utf8"),rerank=await readFile(new URL("../src/experiment4ar5Reranker.ts",import.meta.url),"utf8"),planner=await readFile(new URL("../src/experiment4ar5Planner.ts",import.meta.url),"utf8");expect(base).toContain('import {resolveSelected,providerSelectionFingerprint} from "./experiment3vCore.js";');expect(base).toContain('"GO_4A_R_BREADTH_RECOVERY":"REASSESS_4A_R_BREADTH_RECOVERY"');for(const s of [core,rerank,planner])expect(s).not.toMatch(/thecocktaildb|openfoodfacts|genderize|metmuseum|nhtsa|registry\.npmjs|openlibrary/i);});
});
