import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {MCP_REGISTRY_URL,PUBLIC_APIS_URL,STANDARD_SPEC_PATHS,classifyMcpTool,extractMcpCandidates,parsePublicApis,publicApiEligible,rankPublicApis,runNegativeControls,standardProbeUrl} from "../src/experiment3tCore.js";

const readme=readFileSync("experiments/3t/README.md","utf8"),runner=readFileSync("src/experiment3t.ts","utf8");
describe("Experiment 3T",()=>{
  it("freezes three independent substrates and unchanged semantic cases",()=>{expect(PUBLIC_APIS_URL).toContain("public-apis/public-apis");expect(MCP_REGISTRY_URL).toContain("registry.modelcontextprotocol.io");expect(readme).toContain("APIs.guru OpenAPI registry");expect(readme).toContain("Official MCP Registry");expect(readme).toContain("Public-APIs catalog");expect(readme).toContain("same semantic cases and build/replay inputs as 3R/3S");});
  it("parses curated public-api rows generically",()=>{const md="### Games\nAPI | Description | Auth | HTTPS | CORS\n|:---|:---|:---|:---|:---|\n| [Demo](https://demo.example/docs) | fantasy role playing API | No | Yes | Yes |\n";const rows=parsePublicApis(md);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({name:"Demo",category:"Games",https:"Yes",link:"https://demo.example/docs"});expect(publicApiEligible(rows[0])).toBe(true);});
  it("uses only the frozen standard spec paths",()=>{expect(STANDARD_SPEC_PATHS).toHaveLength(5);expect(standardProbeUrl("https://example.com/docs",STANDARD_SPEC_PATHS[0])).toBe("https://example.com/openapi.json");expect(()=>standardProbeUrl("https://example.com/docs","/custom.json")).toThrow("probe_path_not_allowed");});
  it("ranks public catalog without provider-specific mappings",()=>{const c:any={intent:"currency metadata",input_names:["currency_id"],required_output_leaf_names:["code","name"]};const rows:any[]=[{name:"Money",description:"currency code metadata",auth:"No",https:"Yes",cors:"",link:"https://a.test",category:"Finance",score:0},{name:"Cats",description:"cat images",auth:"No",https:"Yes",cors:"",link:"https://b.test",category:"Animals",score:0}];expect(rankPublicApis(c,rows)[0].name).toBe("Money");for(const p of ["dnd5eapi","openfintech","github.com/repos","frankfurter"])expect(runner.toLowerCase()).not.toContain(p);});
  it("rejects MCP endpoints with unresolved headers and unsafe tools",()=>{const raw={servers:[{server:{name:"x/y",remotes:[{type:"streamable-http",url:"https://mcp.example/mcp",headers:{Authorization:{value:"${TOKEN}"}}}]}}]};expect(extractMcpCandidates(raw)).toHaveLength(0);expect(classifyMcpTool({name:"delete_item",description:"delete item",inputSchema:{type:"object"},annotations:{readOnlyHint:true}}).safe).toBe(false);expect(classifyMcpTool({name:"read_info",description:"read info",inputSchema:{type:"object"},annotations:{readOnlyHint:true}}).safe).toBe(true);});
  it("executes all eighteen active negative controls",()=>{const controls=runNegativeControls();expect(controls).toHaveLength(18);expect(controls.every(x=>x.executed&&x.rejected)).toBe(true);expect(new Set(controls.map(x=>x.control)).size).toBe(18);});
  it("freezes non-APIs.guru success and live MCP gates",()=>{expect(readme).toContain("at least one successful semantic supplier originates from `public_apis`");expect(readme).toContain("at least 2 MCP servers from distinct namespaces");expect(readme).toContain("GO_MULTI_SUBSTRATE_LIVE_SUPPLY_ACQUISITION");expect(readme).toContain("REASSESS_MULTI_SUBSTRATE_LIVE_SUPPLY_ACQUISITION");});
});
