import {describe,expect,it} from "vitest";
import {buildFiveB16Report} from "../src/experiment5b16Decision.js";
import {loadFiveB16Workload} from "../src/experiment5b16Workload.js";

const integrity:any={ok:true,base_sha:"base",prereg_commit:"pre",workload_commit:"work",runtime_provider_url_literals:0,runtime_case_family_hardcoding:0};
function fixture(){const workload=loadFiveB16Workload(),unhealthy=workload.primaries.find(p=>p.unhealthy_after_5b15)!,other=workload.primaries.find(p=>p.family!==unhealthy.family)!,alt=(p:any,i:number)=>({family:p.family,case_id:p.case_id,primary_recipe_fingerprint:p.primary_recipe_fingerprint,provider_start_url:`https://alternate-${i}.example.test`,recipe_fingerprint:`alternate-${i}`,first_verification:{requested_at:"a"},confirmation_verification:{requested_at:"b"},changed_input_replay:{success:true}}),recipes=[alt(unhealthy,1),alt(other,2)],caseEvidence=workload.primaries.map(p=>({family:p.family,case_id:p.case_id,selected:workload.raw_tail_entries.filter(x=>x.case_id===p.case_id).map(x=>({...x,identity_resolved:true})),attempts:[],success:recipes.find(r=>r.case_id===p.case_id)?{recipe_fingerprint:recipes.find(r=>r.case_id===p.case_id)!.recipe_fingerprint}:null})),raw:any={fingerprint:"engine",metrics:{catalogIdentityResolutionFetches5b16:1,docFetches:10,synthesisCalls:2,synthesisRepairs:0,rerankerCalls:0,broadRetrievalCalls5b16:0,newProviderSelectionCalls5b16:0,total_llm_cost_usd:.10,mean_llm_cost_per_qualifying_alternate_usd:.05,authLikeRenderedRequests5b16:0,wrongTaskProbeAttempts5b16:0,replay_deltas:{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0}},caseEvidence,recipes,replay:recipes.map(r=>({case_id:r.case_id,success:true}))};return {raw,workload,unhealthy,other}}

describe("Experiment 5B16 formal decision",()=>{
 it("allows GO only with multi-family replayable redundancy and unhealthy-primary coverage",()=>{const {raw,workload}=fixture(),report=buildFiveB16Report(raw,integrity,workload);expect(report.decision).toBe("GO_5B16_VERIFIED_RECIPE_REDUNDANCY_ACQUISITION");expect(Object.values(report.gates).every(Boolean)).toBe(true)});
 it("keeps REASSESS when the persistently unhealthy primary is not covered",()=>{const {raw,workload,unhealthy}=fixture();raw.recipes=raw.recipes.filter((r:any)=>r.case_id!==unhealthy.case_id);raw.replay=raw.replay.filter((r:any)=>r.case_id!==unhealthy.case_id);const report=buildFiveB16Report(raw,integrity,workload);expect(report.decision).toBe("REASSESS_5B16_VERIFIED_RECIPE_REDUNDANCY_ACQUISITION");expect(report.gates.every_unhealthy_primary_covered).toBe(false)});
 it("keeps REASSESS with fewer than two capabilities or families",()=>{const {raw,workload}=fixture();raw.recipes=raw.recipes.slice(0,1);raw.replay=raw.replay.slice(0,1);const report=buildFiveB16Report(raw,integrity,workload);expect(report.gates.at_least_2_capabilities_with_alternates).toBe(false);expect(report.gates.at_least_2_families_with_alternates).toBe(false);expect(report.decision).toBe("REASSESS_5B16_VERIFIED_RECIPE_REDUNDANCY_ACQUISITION")});
 it("rejects candidate-order mutation and replay cognitive activity",()=>{const {raw,workload}=fixture();raw.caseEvidence[0].selected=[...raw.caseEvidence[0].selected].reverse();raw.metrics.replay_deltas.documentation_fetches=1;const report=buildFiveB16Report(raw,integrity,workload);expect(report.gates.frozen_candidate_order_preserved).toBe(false);expect(report.gates.replay_discovery_cognitive_zero).toBe(false);expect(report.decision).toBe("REASSESS_5B16_VERIFIED_RECIPE_REDUNDANCY_ACQUISITION")});
});
