import {readFile} from "node:fs/promises";
import {describe,it,expect} from "vitest";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {materializeSelectionP1} from "../src/experiment4ap1Core.js";
import {buildStructuredRequestGraph4D,extractStructuredRequestBlocks4D} from "../src/experiment4dRequest.js";
import {validate4d} from "../src/experiment4dContract.js";
import {deriveExperiment4dSource} from "../src/experiment4dDerivation.js";
function ev(text:string,url="https://docs.example.test/reference",id="p-e01"):any{return{evidence_id:id,provider_candidate_id:"p",requested_url:url,resolved_url:url,verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"text/html",body_fingerprint:"x",text,state:"ok"}}
function proof(h:any):any{return{hypothesis:h,record:{hypothesis_id:h.id,disposition:"success",requested_url:"https://api.example.test/estimate?name=michael",requested_at:"2026-01-01T00:00:00Z",final_url:"https://api.example.test/estimate?name=michael",content_type:"application/json",response_body_fingerprint:"bodyfp",schema_fingerprint:"schemafp",observed_fields:[{id:"f_name",path:"name",leaf:"name",tokens:["name"],sample_type:"string",sample_value:"michael",build_value_relations:["TASK_INPUT:name:michael"]},{id:"f_age",path:"age",leaf:"age",tokens:["age"],sample_type:"number",sample_value:"50",build_value_relations:[]}],observed_path_count:2,bytes:40,error:null}}}
describe("4D structured request block compiler",()=>{
 it("does not promote standalone URLs",()=>{const d=[ev("Read https://api.example.test/estimate?name={name} for details")];expect(extractStructuredRequestBlocks4D(d)).toHaveLength(0);expect(buildStructuredRequestGraph4D(d,"age_estimate_by_name").hypotheses).toHaveLength(0)});
 it("normalizes colon placeholders",()=>{const g=buildStructuredRequestGraph4D([ev("GET https://api.example.test/estimate/:name")],"age_estimate_by_name");expect(g.hypotheses[0].full_path).toContain("{name}");expect(g.hypotheses[0].input_bindings.name).toBeTruthy()});
 it("normalizes bracket angle and double-brace placeholders provider-blindly",()=>{for(const p of ["[name]","<name>","{{name}}"]){const g=buildStructuredRequestGraph4D([ev(`GET https://api.example.test/estimate/${p}`)],"age_estimate_by_name");expect(g.hypotheses[0].full_path).toContain("{name}")}});
 it("links a relative GET to an API base only inside the bounded block",()=>{const g=buildStructuredRequestGraph4D([ev("Base URL: https://api.example.test\nGET /estimate/[name]\nReturns an age estimate")],"age_estimate_by_name");expect(g.hypotheses.length).toBeGreaterThan(0);expect(g.hypotheses[0].origin).toBe("https://api.example.test");expect(g.metrics.baseRelativeLinksFormed).toBeGreaterThan(0)});
 it("does not associate a distant curl keyword with an unrelated URL",()=>{const filler="x".repeat(900);const d=[ev(`curl documentation ${filler}\nhttps://api.example.test/estimate?name={name}`)];expect(extractStructuredRequestBlocks4D(d).some(b=>b.proof_kind==="curl_request_block"&&b.absolute_url)).toBe(false)});
 it("validates materialized COMPILE against the same 4D graph",()=>{const docs=[ev("GET https://api.example.test/estimate?name={name}")],g=buildStructuredRequestGraph4D(docs,"age_estimate_by_name"),h=g.hypotheses[0],p=proof(h),m=materializeSelectionP1("age_estimate_by_name","p",p,{decision:"SELECT",hypothesis_id:h.id,output_bindings:[{task_output:"name",source_id:"f_name"},{task_output:"age",source_id:"f_age"}],reason:"ok"});m.raw.reason=`4D_STRUCTURED_REQUEST:${h.id}`;const v=validate4d(m.raw,{case_id:"age_estimate_by_name",candidate_id:"p",name:"P",start_url:"https://docs.example.test/reference"},docs,new RecoveryLedger(),p);expect(v.errors).toEqual([]);expect(v.contract?.decision).toBe("COMPILE")});
 it("rejects old graph prefixes",()=>{const docs=[ev("GET https://api.example.test/estimate?name={name}")],g=buildStructuredRequestGraph4D(docs,"age_estimate_by_name"),h=g.hypotheses[0],p=proof(h),m=materializeSelectionP1("age_estimate_by_name","p",p,{decision:"SELECT",hypothesis_id:h.id,output_bindings:[{task_output:"name",source_id:"f_name"},{task_output:"age",source_id:"f_age"}],reason:"ok"});m.raw.reason=`4C_TYPED_REQUEST:${h.id}`;expect(validate4d(m.raw,{case_id:"age_estimate_by_name",candidate_id:"p",name:"P",start_url:"https://docs.example.test/reference"},docs,new RecoveryLedger(),p).errors).toContain("4d_request_hypothesis_not_in_structured_graph")});
 it("derives 4D runner with structured metrics and exact 4C parent",async()=>{const base=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),g=deriveExperiment4dSource(base);expect(g).toContain('const OUT="results/experiment-4d"');expect(g).toContain("synthesize4d as synthesize4ar");expect(g).toContain("validate4d as validate4ar");expect(g).toContain("structuredRequestBlocks");expect(g).toContain("baseRelativeLinksFormed");expect(g).toContain("GO_4D_STRUCTURED_REQUEST_BLOCK_COMPILER");expect(g).toContain('base_sha:"3c3871cde4252782d7734990307ae681423544d1"')});
});
