import {describe,expect,it} from "vitest";
import {qualifyRequestHypotheses5B20,qualificationDeterminism5B20} from "../src/experiment5b20Qualification.js";

const slot=(id:string,name:string,where:"path"|"query"="path")=>({id,name,in:where,required:true,auth_like:false,literals:[]});
const hyp=(id:string,path:string,input:string,slotName:string,proof_type="5b12_documentary_request_template",where:"path"|"query"="path")=>({id,source_operation_id:`op-${id}`,origin:"https://api.example.test",full_path:path,proof_type,evidence_ids:["e1"],source_urls:["https://docs.example.test"],slots:[slot("s1",slotName,where)],input_bindings:{[input]:"s1"},literal_bindings:{},score:1,concrete_relation:false});
const ev=(text:string)=>[{evidence_id:"e1",provider_candidate_id:"p",requested_url:"https://docs.example.test",resolved_url:"https://docs.example.test",verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"text/html",body_fingerprint:"fp",text,state:"ok" as const}];
const empty=()=>new Map<string,any>();
const args=(h:any,text:string,intent:string,input:string,witness=true)=>({hypotheses:[h],evidence:ev(text),intent,inputNames:[input],nativeProofById:empty(),collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:witness?new Map([[h.id,{source_evidence_id:"e1"}]]):empty()});

describe("Experiment 5B20 strict request-local typed qualification",()=>{
 it("admits native machine-contract operations with lexical bindings",()=>{const h:any=hyp("h1","/country/{country_code}","country_code","country_code","4w_linked_native_openapi_operation"),native=new Map([[h.id,{source_document_evidence_id:"e1",operation_pointer:"#/paths/x/get",method:"GET",contract_url:"https://api.example.test/openapi.json"}]]),a:any={hypotheses:[h],evidence:ev("country API operation"),intent:"Get country metadata",inputNames:["country_code"],nativeProofById:native,collectionProofById:empty(),queryProofById:empty(),documentaryWitnessById:empty()},r=qualifyRequestHypotheses5B20(a);expect(r.hypotheses).toHaveLength(1);expect(r.witnesses.get(h.id)?.qualification_class).toBe("machine_contract");expect(r.witnesses.get(h.id)?.input_bindings[0].binding_class).toBe("lexical");expect(r.witnesses.get(h.id)?.ranking_bonus).toBe(false);expect(qualificationDeterminism5B20(a).ok).toBe(true)});
 it("admits a generic query only when typed input and task anchors are parameter-local",()=>{const h:any=hyp("h2","/search?q={word}","word","q","5b6_query_oriented_parameter_local","query"),r=qualifyRequestHypotheses5B20(args(h,"Dictionary API reference\nGET /search?q={word}\nReturn the English word definition.","Return English word definition","word"));expect(r.hypotheses).toHaveLength(1);expect(r.witnesses.get(h.id)?.input_bindings[0].binding_class).toBe("generic_query_typed_local");expect(r.witnesses.get(h.id)?.input_bindings[0].matched_typed_tokens).toContain("word");expect(r.metrics.fullDocumentBindingContextUses5b20).toBe(0);expect(r.metrics.offLocalAnchorAdmissions5b20).toBe(0)});
 it("rejects anchors that exist only outside the request-local capsule",()=>{const h:any=hyp("h3","/search?q={word}","word","q","5b6_query_oriented_parameter_local","query"),text=`English word definition ${"x".repeat(1500)} API reference GET /search?q={word} result`,r=qualifyRequestHypotheses5B20(args(h,text,"Return English word definition","word"));expect(r.hypotheses).toHaveLength(0);expect(r.metrics.rejectedGenericQueryTypedLocalMismatch5b20).toBe(1);expect(r.metrics.fullDocumentBindingContextUses5b20).toBe(0)});
 it("rejects static image-optimizer request geometry before semantic binding",()=>{const h:any=hyp("h4","/_next/image?url=%2Flogo.png&w=640&q={ip_address}","ip_address","q","5b6_query_oriented_parameter_local","query"),r=qualifyRequestHypotheses5B20(args(h,"IP geolocation API reference GET /_next/image?url=%2Flogo.png&w=640&q={ip_address}","Get IP geolocation metadata","ip_address"));expect(r.hypotheses).toHaveLength(0);expect(r.metrics.rejectedStaticNavigationGeometry5b20).toBe(1);expect(r.metrics.staticNavigationRequestAdmissions5b20).toBe(0)});
 it("rejects country_code to generic q when local evidence lacks the typed code token",()=>{const h:any=hyp("h5","/countries/v5?q={country_code}","country_code","q","5b6_query_oriented_parameter_local","query"),r=qualifyRequestHypotheses5B20(args(h,"Country API reference\nGET /countries/v5?q=canada\nReturn country metadata.","Get country metadata","country_code"));expect(r.hypotheses).toHaveLength(0);expect(r.metrics.rejectedGenericQueryTypedLocalMismatch5b20).toBe(1);expect(r.metrics.genericQueryAdmissionsWithoutTypedLocalInput5b20).toBe(0)});
});
