import {describe,expect,it} from "vitest";
import {selectionFingerprint5b17,validateCapabilityEquivalence5b17} from "../src/experiment5b17Reranker.js";

const c:any={case_id:"synthetic_capability",intent:"Resolve a value",input_names:["query"],required_output_leaf_names:["name","id"]};
const broad:any[]=[{candidate_id:"r2001_a",lexical_rank:1,name:"A",description:"A",category:"Test",auth:"No",https:"Yes",link:"https://a.example.test",score:1},{candidate_id:"r2002_b",lexical_rank:2,name:"B",description:"B",category:"Test",auth:"No",https:"Yes",link:"https://b.example.test",score:1}];

describe("Experiment 5B17 capability-equivalence reranker contract",()=>{
 it("accepts only full exact input/output role coverage",()=>{const x={case_id:c.case_id,selected:[{candidate_id:"r2001_a",reason:"same transformation",input_roles_supported:["query"],output_roles_supported:["id","name"]}]},v=validateCapabilityEquivalence5b17(x,broad,c);expect(v.error).toBeNull();expect(v.selection?.selected).toHaveLength(1)});
 it("rejects topic-adjacent partial-role claims before acquisition",()=>{const missingInput=validateCapabilityEquivalence5b17({case_id:c.case_id,selected:[{candidate_id:"r2001_a",reason:"related",input_roles_supported:[],output_roles_supported:["id","name"]}]},broad,c),missingOutput=validateCapabilityEquivalence5b17({case_id:c.case_id,selected:[{candidate_id:"r2001_a",reason:"related",input_roles_supported:["query"],output_roles_supported:["name"]}]},broad,c);expect(missingInput.error).toContain("input_role_coverage");expect(missingOutput.error).toContain("output_role_coverage")});
 it("rejects unknown and duplicate candidates",()=>{const unknown=validateCapabilityEquivalence5b17({case_id:c.case_id,selected:[{candidate_id:"outside",reason:"x",input_roles_supported:["query"],output_roles_supported:["name","id"]}]},broad,c),duplicate=validateCapabilityEquivalence5b17({case_id:c.case_id,selected:[{candidate_id:"r2001_a",reason:"x",input_roles_supported:["query"],output_roles_supported:["name","id"]},{candidate_id:"r2001_a",reason:"x",input_roles_supported:["query"],output_roles_supported:["name","id"]}]},broad,c);expect(unknown.error).toContain("unknown_candidate_id");expect(duplicate.error).toContain("duplicate_candidate_id")});
 it("fingerprints selection order deterministically",()=>{const s:any={case_id:c.case_id,selected:[{candidate_id:"r2001_a",reason:"x",input_roles_supported:["query"],output_roles_supported:["name","id"]},{candidate_id:"r2002_b",reason:"y",input_roles_supported:["query"],output_roles_supported:["id","name"]}]};expect(selectionFingerprint5b17(s)).toBe(selectionFingerprint5b17(s));expect(selectionFingerprint5b17(s)).not.toBe(selectionFingerprint5b17({...s,selected:[...s.selected].reverse()}))});
});
