import {describe,expect,it} from "vitest";
import {FIVE_A_CASES} from "../src/experiment5aCore.js";
import {buildFiveB17Report} from "../src/experiment5b17Decision.js";
import {loadFiveB17Workload} from "../src/experiment5b17Workload.js";

const integrity:any={ok:true,base_sha:"base",prereg_commit:"pre",workload_commit:"work",runtime_provider_url_literals:0,runtime_primary_name_hardcoding:0,runtime_case_family_hardcoding:0};
function fixture(){const workload=loadFiveB17Workload(),unhealthy=workload.primaries.find(p=>p.unhealthy_after_5b15)!,other=workload.primaries.find(p=>p.family!==unhealthy.family)!,make=(p:any,i:number)=>{const c=FIVE_A_CASES.find(x=>x.case_id===p.case_id)!;return {recipe:{family:p.family,case_id:p.case_id,primary_recipe_fingerprint:p.primary_recipe_fingerprint,provider_start_url:`https://alternate-${i}.example.test`,recipe_fingerprint:`alternate-${i}`,first_verification:{requested_at:"a"},confirmation_verification:{requested_at:"b"},changed_input_replay:{success:true}},selected:{candidate_id:`candidate-${i}`,reason:"full functional substitute",input_roles_supported:[...c.input_names],output_roles_supported:[...c.required_output_leaf_names],selected_position:1}}},a=make(unhealthy,1),b=make(other,2),recipes=[a.recipe,b.recipe],caseEvidence=workload.primaries.map(p=>{const pair=p.case_id===unhealthy.case_id?a:p.case_id===other.case_id?b:null;return {family:p.family,case_id:p.case_id,broad_count:120,broad_frontier_fingerprint:`frontier-${p.case_id}`,selected:pair?[pair.selected]:[],attempts:pair?[{candidate_id:pair.selected.candidate_id,selected_position:1,status:"qualified_alternate"}]:[],success:pair?{recipe_fingerprint:pair.recipe.recipe_fingerprint}:null}}),raw:any={fingerprint:"engine",metrics:{catalogSnapshotFetches5b17:1,broadRetrievalCalls5b17:7,maxBroadFrontierSize5b17:120,broadFrontierNondeterminismViolations5b17:0,primaryDomainExclusions5b17:7,equivalenceRerankerCalls5b17:7,equivalenceRerankerRepairCalls5b17:0,equivalenceRoleClaimValidationFailures5b17:0,selectionOrderingNondeterminismViolations5b17:0,selectedOutsideFrontierViolations5b17:0,selectedPrimaryDomainViolations5b17:0,attemptBudgetViolations5b17:0,attemptedProviders5b17:2,secondaryProviderRerankerCalls5b17:0,manualProviderSelectionCalls5b17:0,docFetches:16,synthesisCalls:2,synthesisRepairs:0,total_llm_cost_usd:.12,mean_llm_cost_per_qualifying_alternate_usd:.06,authLikeRenderedRequests5b17:0,wrongTaskProbeAttempts5b17:0,replay_deltas:{catalog_fetches:0,equivalence_reranker_calls:0,secondary_reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0}},caseEvidence,recipes,replay:recipes.map(r=>({case_id:r.case_id,success:true}))};return {raw,workload,unhealthy,other}}

describe("Experiment 5B17 formal decision",()=>{
 it("permits GO only with multi-family replayable substitutes including the unhealthy primary",()=>{const {raw,workload}=fixture(),report=buildFiveB17Report(raw,integrity,workload);expect(report.decision).toBe("GO_5B17_CAPABILITY_EQUIVALENT_PROVIDER_RETRIEVAL");expect(Object.values(report.gates).every(Boolean)).toBe(true)});
 it("keeps REASSESS when the unhealthy primary is not covered",()=>{const {raw,workload,unhealthy}=fixture();raw.recipes=raw.recipes.filter((r:any)=>r.case_id!==unhealthy.case_id);raw.replay=raw.replay.filter((r:any)=>r.case_id!==unhealthy.case_id);const report=buildFiveB17Report(raw,integrity,workload);expect(report.gates.every_unhealthy_primary_covered).toBe(false);expect(report.decision).toBe("REASSESS_5B17_CAPABILITY_EQUIVALENT_PROVIDER_RETRIEVAL")});
 it("rejects candidates attempted without exact role claims",()=>{const {raw,workload}=fixture(),row=raw.caseEvidence.find((x:any)=>x.selected.length);row.selected[0].output_roles_supported=[];const report=buildFiveB17Report(raw,integrity,workload);expect(report.gates.attempted_candidates_full_role_claim).toBe(false);expect(report.decision).toBe("REASSESS_5B17_CAPABILITY_EQUIVALENT_PROVIDER_RETRIEVAL")});
 it("rejects secondary reranking or replay-time cognitive work",()=>{const {raw,workload}=fixture();raw.metrics.secondaryProviderRerankerCalls5b17=1;raw.metrics.replay_deltas.equivalence_reranker_calls=1;const report=buildFiveB17Report(raw,integrity,workload);expect(report.gates.no_secondary_or_manual_provider_selection).toBe(false);expect(report.gates.replay_discovery_cognitive_zero).toBe(false);expect(report.decision).toBe("REASSESS_5B17_CAPABILITY_EQUIVALENT_PROVIDER_RETRIEVAL")});
});
