import {readFile} from "node:fs/promises";
import {describe,it,expect} from "vitest";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {materializeSelectionP1} from "../src/experiment4ap1Core.js";
import {buildTypedRequestGraph4C,extractTypedRequestEvidence4C} from "../src/experiment4cRequest.js";
import {validate4c} from "../src/experiment4cContract.js";
import {deriveExperiment4cSource} from "../src/experiment4cDerivation.js";

function ev(text:string,url="https://docs.example.test/reference",id="p-e01"):any{return {evidence_id:id,provider_candidate_id:"p",requested_url:url,resolved_url:url,verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"text/html",body_fingerprint:"x",text,state:"ok"};}
function proof(h:any):any{return {hypothesis:h,record:{hypothesis_id:h.id,disposition:"success",requested_url:"https://api.example.test/estimate?name=michael",requested_at:"2026-01-01T00:00:00Z",final_url:"https://api.example.test/estimate?name=michael",content_type:"application/json",response_body_fingerprint:"bodyfp",schema_fingerprint:"schemafp",observed_fields:[{id:"f_name",path:"name",leaf:"name",tokens:["name"],sample_type:"string",sample_value:"michael",build_value_relations:["TASK_INPUT:name:michael"]},{id:"f_age",path:"age",leaf:"age",tokens:["age"],sample_type:"number",sample_value:"50",build_value_relations:[]}],observed_path_count:2,bytes:40,error:null}};}

describe("4C typed request evidence acquisition",()=>{
 it("does not promote an arbitrary standalone absolute URL",()=>{const docs=[ev('Read more at https://api.example.test/estimate?name={name}')];expect(extractTypedRequestEvidence4C(docs)).toHaveLength(0);expect(buildTypedRequestGraph4C(docs,"age_estimate_by_name").hypotheses).toHaveLength(0);});
 it("accepts an explicit HTTP GET request line",()=>{const g=buildTypedRequestGraph4C([ev('Example request: GET https://api.example.test/estimate?name={name}')],"age_estimate_by_name");expect(g.hypotheses.length).toBeGreaterThan(0);expect(g.hypotheses[0].proof_type).toBe("4c_http_get_line");expect(g.metrics.standaloneUrlPromotions).toBe(0);});
 it("accepts curl, fetch and axios GET syntax but rejects curl POST",()=>{const docs=[ev('curl https://api.example.test/a?name={name}\nfetch("https://api.example.test/b?name={name}")\naxios.get("https://api.example.test/c?name={name}")\ncurl -X POST https://api.example.test/d?name={name}')];const types=extractTypedRequestEvidence4C(docs).map(x=>x.type);expect(types).toContain("curl_get");expect(types).toContain("fetch_get");expect(types).toContain("axios_get");expect(extractTypedRequestEvidence4C(docs).some(x=>x.url?.includes('/d'))).toBe(false);});
 it("deduplicates identical rendered probe URLs",()=>{const docs=[ev('GET https://api.example.test/estimate?name={name}\nRequest URL: https://api.example.test/estimate?name={name}')];const g=buildTypedRequestGraph4C(docs,"age_estimate_by_name");expect(g.probe_packet).toHaveLength(1);expect(g.metrics.duplicateRenderedProbeUrlsRejected).toBeGreaterThanOrEqual(1);});
 it("validates a materialized COMPILE against the same 4C graph",()=>{const docs=[ev('GET https://api.example.test/estimate?name={name}')],g=buildTypedRequestGraph4C(docs,"age_estimate_by_name"),h=g.hypotheses[0],p=proof(h),made=materializeSelectionP1("age_estimate_by_name","p",p,{decision:"SELECT",hypothesis_id:h.id,output_bindings:[{task_output:"name",source_id:"f_name"},{task_output:"age",source_id:"f_age"}],reason:"ok"});made.raw.reason=`4C_TYPED_REQUEST:${h.id}`;const v=validate4c(made.raw,{case_id:"age_estimate_by_name",candidate_id:"p",name:"P",start_url:"https://docs.example.test/reference"},docs,new RecoveryLedger(),p);expect(v.errors).toEqual([]);expect(v.contract?.decision).toBe("COMPILE");expect(v.projection).toBeTruthy();});
 it("rejects the old 4B/P1 reason prefixes instead of silently switching graphs",()=>{const docs=[ev('GET https://api.example.test/estimate?name={name}')],g=buildTypedRequestGraph4C(docs,"age_estimate_by_name"),h=g.hypotheses[0],p=proof(h),made=materializeSelectionP1("age_estimate_by_name","p",p,{decision:"SELECT",hypothesis_id:h.id,output_bindings:[{task_output:"name",source_id:"f_name"},{task_output:"age",source_id:"f_age"}],reason:"ok"});made.raw.reason=`4B_PROVENANCE_REQUEST:${h.id}`;expect(validate4c(made.raw,{case_id:"age_estimate_by_name",candidate_id:"p",name:"P",start_url:"https://docs.example.test/reference"},docs,new RecoveryLedger(),p).errors).toContain("4c_request_hypothesis_not_in_typed_graph");});
 it("derives 4C runner with typed metrics, own validator and exact 4B parent",async()=>{const base=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),g=deriveExperiment4cSource(base);expect(g).toContain('const OUT="results/experiment-4c"');expect(g).toContain("synthesize4c as synthesize4ar");expect(g).toContain("validate4c as validate4ar");expect(g).toContain("typedEvidenceItems");expect(g).toContain("validatorGraphMismatchRejects");expect(g).toContain("GO_4C_TYPED_REQUEST_EVIDENCE_ACQUISITION");expect(g).toContain('base_sha:"818ec4d7dc0f47f39ff09444f422ddb6c7761dd8"');});
});
