import {describe,expect,it} from "vitest";
import type {DocEvidence} from "../src/experiment3wCore.js";
import type {Provider4A} from "../src/experiment4aContract.js";
import {FOUR_A_CASES} from "../src/experiment4aCore.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import {buildStructuredCollectionHypotheses5B4} from "../src/experiment5b4Collection.js";
import {rankRequestBeam5B3} from "../src/experiment5b3RequestUtility.js";

const CASE_ID="chess_player_metadata";
const task=FOUR_A_CASES.find(c=>c.case_id===CASE_ID)!;
const provider:Provider4A={case_id:CASE_ID,candidate_id:"synthetic_provider",name:"Synthetic API",start_url:"https://www.example.test/docs"};
function evidence(root:any):DocEvidence{return {evidence_id:"ev_collection",provider_candidate_id:provider.candidate_id,requested_url:"https://www.example.test/collection.json",resolved_url:"https://www.example.test/collection.json",verified_at:"2026-01-01T00:00:00Z",status:200,content_type:"application/json",body_fingerprint:"body_fp",text:JSON.stringify(root),state:"ok"}}
function collection(items:any[]){return {info:{name:"Synthetic API",schema:"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},item:[{name:"Account",item:items}]}}
const get=(name:string,url:string,response:any[]=[])=>({name,request:{method:"GET",header:[],body:{},url,description:""},response});

describe("Experiment 5B4 structured collection compiler",()=>{
 it("parses folders and induces one repeated exemplar slot across sibling operations",()=>{const root=collection([get("Account Profile","https://api.example.test/pub/account/alice"),get("Account Stats","https://api.example.test/pub/account/alice/stats"),get("Account History","https://api.example.test/pub/account/alice/history")]),r=buildStructuredCollectionHypotheses5B4([evidence(root)],provider);expect(r.metrics.structuredCollectionsParsed5b4).toBe(1);expect(r.hypotheses.length).toBeGreaterThanOrEqual(3);const profile=r.hypotheses.find(h=>h.full_path==="/pub/account/{username}");expect(profile).toBeTruthy();expect(profile!.proof_type).toBe("5b4_structured_collection_operation");expect(profile!.input_bindings.username).toBeTruthy();expect(compileRequestHypothesisP1(profile!,{username:"bob"})).toBe("https://api.example.test/pub/account/bob");expect(r.metrics.collectionRepeatedExemplarWitnesses5b4).toBeGreaterThan(0)});
 it("keeps operation-local capsule semantics isolated from sibling-only words",()=>{const root=collection([get("Account Profile","https://api.example.test/pub/account/alice"),{...get("Account Stats","https://api.example.test/pub/account/alice/stats"),description:"ratings wins losses"}]),r=buildStructuredCollectionHypotheses5B4([evidence(root)],provider),profileProof=r.proofs.find(p=>p.operation_name==="Account Profile")!,cap=r.capsules.find(e=>e.evidence_id===profileProof.operation_local_evidence_id)!;expect(cap.text).toContain("Account Profile");expect(cap.text).not.toContain("ratings");expect(cap.text).not.toContain("wins");expect(cap.text).not.toContain("Account Stats")});
 it("binds an explicit path variable without literal exemplar induction",()=>{const root=collection([get("Account Profile","https://api.example.test/pub/account/{{username}}")]),r=buildStructuredCollectionHypotheses5B4([evidence(root)],provider);expect(r.hypotheses).toHaveLength(1);expect(r.hypotheses[0].full_path).toBe("/pub/account/{username}");expect(r.metrics.collectionExplicitVariableWitnesses5b4).toBe(1)});
 it("does not generalize an arbitrary single literal path segment",()=>{const root=collection([get("Account Profile","https://api.example.test/pub/account/alice")]),r=buildStructuredCollectionHypotheses5B4([evidence(root)],provider);expect(r.hypotheses).toHaveLength(0);expect(r.metrics.collectionExemplarUnsafeRejects5b4).toBeGreaterThan(0)});
 it("rejects auth-bearing and request-body collection operations",()=>{const auth={name:"Account Profile",request:{method:"GET",header:[{key:"Authorization",value:"Bearer x"}],body:{},url:"https://api.example.test/pub/account/{{username}}"},response:[]},body={name:"Account Profile",request:{method:"POST",header:[],body:{mode:"raw",raw:"{}"},url:"https://api.example.test/pub/account/{{username}}"},response:[]},r=buildStructuredCollectionHypotheses5B4([evidence(collection([auth,body]))],provider);expect(r.hypotheses).toHaveLength(0);expect(r.metrics.structuredCollectionAuthRejects5b4).toBe(1);expect(r.metrics.structuredCollectionGetOperations5b4).toBe(1)});
 it("ranks a profile operation above a sibling stats operation from local semantics only",()=>{const root=collection([get("Account Profile","https://api.example.test/pub/account/alice"),get("Account Stats","https://api.example.test/pub/account/alice/stats")]),r=buildStructuredCollectionHypotheses5B4([evidence(root)],provider),ranked=rankRequestBeam5B3(task,r.hypotheses,r.capsules,new Map(),undefined);expect(ranked.hypotheses[0].full_path).toBe("/pub/account/{username}");expect(ranked.ordering[0].task_score).toBeGreaterThan(ranked.ordering[1].task_score)});
});
