import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
import {sha3yr} from "../src/experiment3yrCore.js";
import {FIVE_B16_FROZEN_TAIL_FINGERPRINT,FIVE_B16_PUBLIC_APIS_COMMIT,FIVE_B16_UNHEALTHY_SET_FINGERPRINT,loadFiveB16Workload,resolveFrozenTail5b16,workloadShapeValid5b16} from "../src/experiment5b16Workload.js";

describe("Experiment 5B16 frozen redundancy workload",()=>{
 it("locks the preregistered workload shape and snapshot",()=>{const w=loadFiveB16Workload();expect(workloadShapeValid5b16(w)).toBe(true);expect(w.primaries).toHaveLength(7);expect(w.raw_tail_entries).toHaveLength(26);expect(new Set(w.raw_tail_entries.map(x=>`${x.case_id}|${x.url_fingerprint}`)).size).toBe(25);expect(w.raw_tail_entries.every(x=>x.selected_position<=8)).toBe(true);expect(w.raw_tail_entries.filter(x=>x.duplicate_url_identity)).toHaveLength(1);expect(w.unhealthy_primary_recipe_fingerprints).toHaveLength(1);expect(w.public_apis_snapshot.commit).toBe(FIVE_B16_PUBLIC_APIS_COMMIT);expect(w.frozen_tail_fingerprint).toBe(FIVE_B16_FROZEN_TAIL_FINGERPRINT);expect(w.unhealthy_primary_set_fingerprint).toBe(FIVE_B16_UNHEALTHY_SET_FINGERPRINT)});
 it("resolves only a frozen candidate whose URL fingerprint and deterministic candidate suffix both match",()=>{const link="https://example.test/docs",caseId="synthetic_case",name="Synthetic Provider",rank=7,suffix=sha3yr(`${caseId}|${name}|${link}`).slice(0,10),entry:any={family:"synthetic",case_id:caseId,primary_recipe_fingerprint:"primary",candidate_id:`r2${String(rank).padStart(3,"0")}_${suffix}`,candidate_name:name,selected_position:2,deterministic_rank:rank,url_fingerprint:sha3yr(link),duplicate_url_identity:false},workload:any={raw_tail_entries:[entry]};const catalog=`### Test\n| API | Description | Auth | HTTPS | CORS |\n|:---|:---|:---|:---|:---|\n| [${name}](${link}) | Synthetic | No | Yes | Yes |`;const rows=resolveFrozenTail5b16(workload,catalog,caseId);expect(rows).toHaveLength(1);expect(rows[0].identity_resolved).toBe(true);expect(rows[0].link).toBe(link);const bad=resolveFrozenTail5b16({...workload,raw_tail_entries:[{...entry,url_fingerprint:sha3yr("https://example.test/other")}]},catalog,caseId);expect(bad[0].identity_resolved).toBe(false);expect(bad[0].link).toBeNull()});
 it("keeps preregistration and workload files distinct",()=>{const prereg=readFileSync("experiments/5b16/README.md","utf8"),w=readFileSync("experiments/5b16/frozen-redundancy-workload.json","utf8");expect(prereg).toContain("GO_5B16_VERIFIED_RECIPE_REDUNDANCY_ACQUISITION");expect(w).toContain('"raw_tail_count": 26')});
});
