import {describe,expect,it} from "vitest";
import {qualifyMachineSpec4U,resolveLocalRef4U,resolveServerOrigin4U,type RefMetrics4U} from "../src/experiment4uOpenApi.js";
import {freezeRequestProof4U,verifyFrozenRequestProof4U} from "../src/experiment4uNativeOperation.js";
import type {P1RequestHypothesis} from "../src/experiment4ap1Model.js";

const metrics=():RefMetrics4U=>({operationLocalRefsResolved4u:0,operationLocalRefsRejected4u:0,operationExternalRefsRejected4u:0,operationRefCyclesRejected4u:0,unrelatedRefFailuresIsolated4u:0});
describe("Experiment 4U spec-qualified lazy OpenAPI compiler",()=>{
  it("rejects valid JSON that is not OpenAPI",()=>{const q=qualifyMachineSpec4U(JSON.stringify({hello:"world"}));expect(q.spec).toBeNull();expect(q.nonSpecJson).toBe(true)});
  it("parses qualified OpenAPI YAML with arrays and local refs",()=>{const q=qualifyMachineSpec4U(`openapi: 3.0.3\nservers:\n  - url: https://example.com\npaths:\n  /search:\n    get:\n      operationId: search\n      parameters:\n        - $ref: '#/components/parameters/Q'\n      responses:\n        '200':\n          description: ok\ncomponents:\n  parameters:\n    Q:\n      name: q\n      in: query\n      required: true\n      schema:\n        type: string\n`);expect(q.spec?.kind).toBe("openapi3");expect(q.spec?.spec.paths["/search"].get.parameters[0].$ref).toBe("#/components/parameters/Q")});
  it("resolves only requested local refs and rejects external refs",()=>{const root={components:{parameters:{Q:{name:"q",in:"query",required:true}}}};const m=metrics();expect(resolveLocalRef4U(root,{$ref:"#/components/parameters/Q"},m).name).toBe("q");expect(m.operationLocalRefsResolved4u).toBe(1);expect(()=>resolveLocalRef4U(root,{$ref:"https://other.example/x"},m)).toThrow("4u_external_ref")});
  it("detects circular request refs",()=>{const root={components:{parameters:{A:{$ref:"#/components/parameters/B"},B:{$ref:"#/components/parameters/A"}}}};const m=metrics();expect(()=>resolveLocalRef4U(root,{$ref:"#/components/parameters/A"},m)).toThrow("4u_ref_cycle");expect(m.operationRefCyclesRejected4u).toBe(1)});
  it("resolves relative OAS3 servers and Swagger 2 base paths",()=>{const o=qualifyMachineSpec4U(JSON.stringify({openapi:"3.0.3",servers:[{url:"/api"}],paths:{}}));expect(resolveServerOrigin4U(o.spec!,"https://example.com/openapi.json")).toBe("https://example.com/api");const s=qualifyMachineSpec4U(JSON.stringify({swagger:"2.0",schemes:["https"],host:"example.com",basePath:"/v1",paths:{}}));expect(resolveServerOrigin4U(s.spec!,"https://example.com/swagger.json")).toBe("https://example.com/v1")});
  it("freezes inherited or native request proof and rejects any mutation",()=>{const h:P1RequestHypothesis={id:"req_x",source_operation_id:"op_x",origin:"https://example.com",full_path:"/search",proof_type:"4n_executed_trace_documented_role_path",evidence_ids:["e1"],source_urls:["https://example.com/docs"],slots:[{id:"p1",name:"q",in:"query",required:true,auth_like:false,literals:[]}],input_bindings:{name:"p1"},literal_bindings:{},score:1000,concrete_relation:false};const proof=freezeRequestProof4U(h);expect(verifyFrozenRequestProof4U(h,proof)).toBe(true);expect(verifyFrozenRequestProof4U({...h,full_path:"/mutated"},proof)).toBe(false)});
});
