import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {extractLinks,isValidContract,operationCount,promoteOrdinaryHtmlLink,registrableDomain,standardCandidates,validateScopedUrl} from "../src/experiment3uCore.js";
import {acquisitionSourceAllowed,budgetAllows,isPublicAddress,javascriptExecutionAllowed} from "../src/experiment3uNetwork.js";

const readme=readFileSync("experiments/3u/README.md","utf8"),runner=readFileSync("src/experiment3u.ts","utf8");
describe("Experiment 3U",()=>{
  it("freezes documentation-only acquisition without provider mappings",()=>{expect(readme).toContain("maximum crawl depth = 2");expect(readme).toContain("maximum fetched HTML pages = 8");expect(readme).toContain("maximum candidate contract fetches = 12");for(const s of ["dnd5eapi","openfintech","api.github.com","frankfurter"])expect(runner.toLowerCase()).not.toContain(s);});
  it("enforces registrable-domain and HTTPS scope",()=>{expect(registrableDomain("docs.api.example.com")).toBe("example.com");expect(registrableDomain("docs.example.co.uk")).toBe("example.co.uk");expect(validateScopedUrl("https://docs.example.com/start","https://api.example.com/openapi.json",1).ok).toBe(true);expect(validateScopedUrl("https://docs.example.com/start","https://evil.test/openapi.json",1).reason).toBe("cross_registrable_domain");expect(validateScopedUrl("https://docs.example.com","http://docs.example.com/openapi.json",1).reason).toBe("http_downgrade");});
  it("extracts static Swagger/ReDoc/config references without JS execution",()=>{const html=`<script>const ui={url:'/spec/openapi.json'}</script><a href='/developer/reference'>API Reference</a><div data-spec-url='/v2/swagger.json'></div>`;const links=extractLinks("https://docs.example.com/start","https://docs.example.com/start",html,1);expect(links.some(x=>x.kind==="contract"&&x.url.endsWith("/spec/openapi.json"))).toBe(true);expect(links.some(x=>x.kind==="contract"&&x.url.endsWith("/v2/swagger.json"))).toBe(true);expect(links.some(x=>x.kind==="page"&&x.url.endsWith("/developer/reference"))).toBe(true);expect(javascriptExecutionAllowed()).toBe(false);});
  it("keeps standard paths bounded and validates real operation presence",()=>{expect(standardCandidates("https://docs.example.com/start")).toHaveLength(5);expect(isValidContract({openapi:"3.0.3",paths:{"/x":{get:{responses:{"200":{description:"ok"}}}}}})).toBe(true);expect(operationCount({openapi:"3.0.3",paths:{"/x":{get:{},post:{}}}})).toBe(2);expect(isValidContract({openapi:"3.0.3",paths:{}})).toBe(false);});
  it("actively enforces budgets and acquisition-source boundary",()=>{expect(budgetAllows("html",7)).toBe(true);expect(budgetAllows("html",8)).toBe(false);expect(budgetAllows("contract",11)).toBe(true);expect(budgetAllows("contract",12)).toBe(false);expect(acquisitionSourceAllowed("documentation_link")).toBe(true);expect(acquisitionSourceAllowed("planner")).toBe(false);});
  it("recognizes private addresses and ordinary links",()=>{expect(isPublicAddress("127.0.0.1")).toBe(false);expect(isPublicAddress("10.0.0.1")).toBe(false);expect(isPublicAddress("8.8.8.8")).toBe(true);expect(promoteOrdinaryHtmlLink("/about","About us")).toBe(false);expect(promoteOrdinaryHtmlLink("/developer/reference","API reference")).toBe(true);});
  it("freezes GO and REASSESS decisions",()=>{expect(readme).toContain("GO_AUTONOMOUS_DOCUMENTATION_CONTRACT_ACQUISITION");expect(readme).toContain("REASSESS_AUTONOMOUS_DOCUMENTATION_CONTRACT_ACQUISITION");expect(readme).toContain("all 16 frozen negative controls");});
});
