import {describe,expect,it} from "vitest";
import {buildFiveB9Report} from "../src/experiment5b9Decision.js";
import {fiveAWorkloadFingerprint} from "../src/experiment5aCore.js";
import type {FiveB9Integrity} from "../src/experiment5b9Harness.js";
function integrity():FiveB9Integrity{return {ok:true,base_sha:"0abd49ebb2e4c081e1f92f0fb178b49091c7499e",prereg_commit:"c7f168cbe0dc736aa2855898b2d6b0e910714fe4",head_sha:"head",base_is_ancestor:true,changed_files:[],unexpected_files:[],first_5b9_commit:"c7f168cbe0dc736aa2855898b2d6b0e910714fe4",prereg_unchanged:true,workload_fingerprint:fiveAWorkloadFingerprint(),runtime_provider_url_literals:0,errors:[]}}
function raw(){return {decision:"engine",fingerprint:"engine",caseEvidence:[],recipes:[],replay:[],rerankEvidence:[],synthesisEvidence:[],metrics:{selectedProviderRecoveryActivated5b9:1,recoveryFetchAttempts5b9:1,recoveryFetchSuccesses5b9:1,recoveryExecutableOperationsAdded5b9:1,recoveryRequestHypothesesAdded5b9:1,recoveryDerivedHypothesesEnteredBeam5b9:1,maxDocumentationFetchesPerProvider5b9:8,maxRecoveryPlusOrdinaryDepth5b9:2,recoveryLinkOrderingNondeterminismRejects5b9:0,replay_deltas:{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0},total_llm_cost_usd:0,rerankerCalls:0,authLikeRenderedRequests:0,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,entityIncompatibleStructuralProbeAttempts:0,executedTraceOriginDriftRejects:0,executedTraceRequestMutationRejects:0,nonAuthRequestTextMutations:0,operationExternalRefFetches4u:0,validatorGraphMismatchRejects:0,duplicateProbeNetworkFetches:0,duplicateAcquisitionNetworkFetches:0,duplicateSpecProbeNetworkFetches:0}}}
describe("Experiment 5B9 strict decision",()=>{
 it("does not GO from recovery activity alone without strict recipe, replay and family diversity",()=>{const report=buildFiveB9Report(raw(),integrity());expect(report.decision).toBe("REASSESS_5B9_VERIFIED_SELECTED_PROVIDER_ACQUISITION_RECOVERY");expect(report.gates.recovery_strict_recipe_active).toBe(false);expect(report.gates.recovery_changed_input_replay_active).toBe(false);expect(report.gates.at_least_6_families).toBe(false)});
 it("keeps recovery budget and replay-acquisition gates explicit",()=>{const x=raw();x.metrics.maxDocumentationFetchesPerProvider5b9=9;x.metrics.replay_deltas.recovery_fetches=1;const report=buildFiveB9Report(x,integrity());expect(report.gates.documentation_budget_8).toBe(false);expect(report.gates.replay_recovery_acquisition_zero).toBe(false)});
});
