import {describe,expect,it} from "vitest";
import {readFile} from "node:fs/promises";
import {bindInputs4V,operationIntentScore4V,rankOperation4V} from "../src/experiment4vBinding.js";
import {responseUsable4V,semanticErrorEnvelope4V} from "../src/experiment4vResponse.js";
import {createSchemaRoleWitness4V,verifySchemaRoleWitness4V} from "../src/experiment4vSchemaWitness.js";
import {deriveExperiment4vSource} from "../src/experiment4vDerivation.js";
import type {P1ProbeProof,P1RequestSlot} from "../src/experiment4ap1Model.js";

const slots=(defs:any[]):P1RequestSlot[]=>defs.map((p,i)=>({id:`p${i}`,name:p.name,in:p.in||"query",required:!!p.required,auth_like:false,literals:[]}));
describe("Experiment 4V parameter-local semantics",()=>{
 it("does not leak operation text into a wrong parameter",()=>{const ps=[{name:"country",in:"query",required:true,description:"ISO country"}],r=bindInputs4V(["postal_code"],ps,slots(ps),"search postal codes",["postal_code","country_name"],{summary:"search postal codes"},"/preview");expect(r.bindings).toBeNull()});
 it("uses sole required generic q when operation intent matches",()=>{const ps=[{name:"q",in:"query",required:true},{name:"country",in:"query",required:false}],r=bindInputs4V(["postal_code"],ps,slots(ps),"search postal codes",["postal_code","country_name"],{summary:"search postal codes"},"/search");expect(r.bindings?.postal_code).toBe("p0");expect(r.evidence[0].binding_kind).toBe("generic_required_fallback")});
 it("rejects unrelated generic id fallback",()=>{const ps=[{name:"id",in:"path",required:true}],r=bindInputs4V(["accession"],ps,slots(ps),"protein accession metadata",["accession","name"],{summary:"job status"},"/jobs/{id}");expect(operationIntentScore4V("protein accession metadata",["accession","name"],{summary:"job status"},"/jobs/{id}")).toBe(0);expect(r.bindings).toBeNull()});
 it("ranks stronger binding above verbose weak operation context",()=>{expect(rankOperation4V(400,1,0,1,1)).toBeGreaterThan(rankOperation4V(25,20,2,1,3))});
 it("rejects strong structured error envelopes but keeps valid data with warning",()=>{expect(semanticErrorEnvelope4V({error:"invalid"},0)).toBe(true);expect(semanticErrorEnvelope4V({errors:["bad"]},0)).toBe(true);expect(semanticErrorEnvelope4V({success:false},0)).toBe(true);expect(responseUsable4V({transport2xx:true,structured:true,body:{name:"ok",warning:"stale"},groundedRequired:1,schemaWitnessAvailable:false}).usable).toBe(true)});
 it("creates and verifies a documented schema role witness without generating values",()=>{const proof:P1ProbeProof={hypothesis:{id:"h",source_operation_id:"o",origin:"https://example.com",full_path:"/search",proof_type:"4v_linked_native_openapi_operation",evidence_ids:["e"],source_urls:["https://example.com/spec"],slots:[],input_bindings:{},literal_bindings:{},score:1,concrete_relation:false},record:{hypothesis_id:"h",disposition:"success",requested_url:"https://example.com/search",requested_at:"now",final_url:"https://example.com/search",content_type:"application/json",response_body_fingerprint:"b",schema_fingerprint:"s",observed_fields:[{id:"f",path:"0.sub",leaf:"sub",tokens:["sub"],sample_type:"string",sample_value:"United States",build_value_relations:[]}],observed_path_count:1,bytes:1,error:null}};const root={paths:{},components:{}},op={responses:{"200":{description:"results",content:{"application/json":{schema:{type:"array",items:{type:"object",properties:{sub:{type:"string",description:"country name"}}}}}}}}};const made=createSchemaRoleWitness4V({root,op,proof,unresolved:["country_name"],specFingerprint:"fp",operationPointer:"#/paths/x/get"});expect(made.witness.mappings[0].observed_path).toBe("0.sub");expect(verifySchemaRoleWitness4V(made.witness,proof)).toBe(true);expect(JSON.stringify(made.witness)).not.toContain("United States")});
 it("rejects witness mutation",()=>{const proof:any={record:{observed_fields:[{path:"x"}]}};const w:any={mappings:[{output_role:"name",schema_path:"x",observed_path:"x"}],classifier_output_fingerprint:"bad"};expect(verifySchemaRoleWitness4V(w,proof)).toBe(false)});
 it("derives the full 4V benchmark source",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4vSource(src);expect(out).toContain('experiment:"4V"');expect(out).toContain("GO_4V_PARAMETER_LOCAL_SEMANTICS_ERROR_AWARE_SCHEMA_ROLE_WITNESS");expect(out).toContain("nativeOperationUsableStructured2xx4v")});
});
