import {describe,it,expect,beforeEach} from "vitest";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {RecoveryLedger} from "../src/experiment3yrCore.js";
import {compileEvidenceNativeSemantics4G} from "../src/experiment4gSemantics.js";
import {compileRequestHypothesisP1} from "../src/experiment4ap1Request.js";
import type {P1RequestHypothesis} from "../src/experiment4ap1Model.js";
import {executableOperationDecision4L,induceExecutableRouteFamilies4L,prepareRequestGraph4L,rebuildRequestGraph4L} from "../src/experiment4lRequest.js";
import {probeCacheMetrics4L,probeHypothesis4L,resetProbeCache4L} from "../src/experiment4lProbe.js";
import {deriveExperiment4lSource} from "../src/experiment4lDerivation.js";

let seq=0;
const ev=(text:string)=>({evidence_id:`ev${++seq}`,provider_candidate_id:"synthetic",requested_url:"https://docs.example.test/reference",resolved_url:"https://docs.example.test/reference",verified_at:new Date().toISOString(),status:200,content_type:"text/html",body_fingerprint:`fp${seq}`,text,state:"ok"} as any);
function semantics(text:string){return compileEvidenceNativeSemantics4G([ev(text)])}
function route(text:string,caseId:string){return induceExecutableRouteFamilies4L(semantics(text),caseId)}
function routeHyps(r:any){return (r.hypotheses as P1RequestHypothesis[]).filter(h=>h.proof_type.startsWith("4l_executable_route_family_"))}
beforeEach(()=>resetProbeCache4L());

describe("4L executable API operation family gating",()=>{
  it("accepts explicit API/data request operations",()=>{const s=semantics('<h2>Product API</h2><p>API endpoint returns JSON product data.</p><pre>GET https://api.example.test/api/v2/product/111111</pre>');const op=s.operations.find(o=>o.path.includes("/api/v2/product/111111"))!;const d=executableOperationDecision4L(s,op);expect(d.accepted).toBe(true);expect(d.positive.length).toBeGreaterThan(0)});
  it("rejects static JavaScript assets before family induction",()=>{const r=route('<h2>Product API</h2><p>API response data and examples.</p><pre>GET https://static.example.test/js/dist/app-a.js\nGET https://static.example.test/js/dist/app-b.js</pre>',"food_barcode_metadata");expect(routeHyps(r)).toHaveLength(0);expect(Number(r.metrics.executableGateRejectedAsset)).toBeGreaterThan(0)});
  it("rejects image, logo, icon and font families",()=>{const r=route('<h2>Product API</h2><p>API response data.</p><pre>GET https://cdn.example.test/images/logo/a.png\nGET https://cdn.example.test/images/logo/b.png</pre>',"food_barcode_metadata");expect(routeHyps(r)).toHaveLength(0);expect(Number(r.metrics.executableGateRejectedAsset)).toBeGreaterThan(0)});
  it("rejects documentation/navigation families",()=>{const r=route('<h2>Product API</h2><p>Developer documentation.</p><pre>GET https://example.test/docs/product-one\nGET https://example.test/docs/product-two</pre>',"food_barcode_metadata");expect(routeHyps(r)).toHaveLength(0);expect(Number(r.metrics.executableGateRejectedNavigation)+Number(r.metrics.executableGateRejectedDocumentation)).toBeGreaterThan(0)});
  it("hard asset evidence overrides API-like surrounding context",()=>{const r=route('<h2>Vehicle API endpoint response JSON</h2><pre>GET https://api.example.test/api/v1/images/a.svg\nGET https://api.example.test/api/v1/images/b.svg</pre>',"vin_vehicle_metadata");expect(routeHyps(r)).toHaveLength(0);expect(Number(r.metrics.executableGateRejectedAsset)).toBeGreaterThan(0)});
  it("keeps a provider-blind product API family while rejecting neighboring static assets",()=>{const r=route('<h2>Product API lookup</h2><p>Request endpoint returns JSON product code and product name.</p><pre>GET https://static.example.test/js/dist/a.js\nGET https://static.example.test/js/dist/b.js\nGET https://data.example.test/api/v2/product/111111\nGET https://data.example.test/api/v2/product/222222</pre>',"food_barcode_metadata");const hs=routeHyps(r);expect(hs.some(h=>h.full_path.includes("/api/v2/product/{barcode}"))).toBe(true);expect(hs.every(h=>!h.full_path.includes("/js/"))).toBe(true)});
  it("keeps a provider-blind vehicle decode API family while rejecting website images",()=>{const r=route('<h2>Vehicle decoder API</h2><p>Decode vehicle identification values; response returns VIN and vehicle make JSON data.</p><pre>GET https://www.example.test/images/car/a.png\nGET https://www.example.test/images/car/b.png\nGET https://data.example.test/api/vehicles/DecodeVin/AAA111\nGET https://data.example.test/api/vehicles/DecodeVin/BBB222</pre>',"vin_vehicle_metadata");const hs=routeHyps(r);expect(hs.some(h=>h.full_path.includes("/DecodeVin/{vin}"))).toBe(true);expect(hs.every(h=>!h.full_path.includes("images"))).toBe(true)});
  it("does not treat generic root navigation as an executable family",()=>{const r=route('<h2>Vehicle information</h2><p>Information site pages.</p><pre>GET https://www.example.test/car-a\nGET https://www.example.test/car-b</pre>',"vin_vehicle_metadata");expect(routeHyps(r)).toHaveLength(0)});
  it("preserves 4J documented npm-style placeholders",async()=>{const g=await prepareRequestGraph4L([ev('<h2>Package API</h2><p>API request returns package name and version JSON.</p><code>GET https://api.example.test/{package}</code>')],"npm_package_metadata",new RecoveryLedger());const h=(g.hypotheses as P1RequestHypothesis[]).find(x=>x.full_path.includes("{package}"));expect(h).toBeTruthy();expect(compileRequestHypothesisP1(h!,{package_name:"lodash"})).toContain("/lodash")});
  it("rebuilds the identical graph for validator use",()=>{const e=[ev('<h2>Product API</h2><p>Lookup endpoint returns product code and name JSON.</p><pre>GET https://api.example.test/api/product/111111\nGET https://api.example.test/api/product/222222</pre>')],a=rebuildRequestGraph4L(e,"food_barcode_metadata"),b=rebuildRequestGraph4L(e,"food_barcode_metadata");expect(a.graph_fingerprint).toBe(b.graph_fingerprint);expect((a.hypotheses as P1RequestHypothesis[]).map(h=>h.id)).toEqual((b.hypotheses as P1RequestHypothesis[]).map(h=>h.id))});
  it("uses one network fetch for two hypotheses rendering the same URL",async()=>{let calls=0;const fake=async()=>{calls++;return {text:JSON.stringify({name:"x",id:1}),final_url:"https://api.example.test/item/1",content_type:"application/json"}};const slot={id:"s",name:"id",in:"path" as const,required:true,auth_like:false,literals:[]},base={origin:"https://api.example.test",full_path:"/item/{id}",proof_type:"4l_executable_route_family_path_explicit_http_same_section",evidence_ids:["e"],source_urls:["https://docs.example.test"],slots:[slot],input_bindings:{id:"s"},literal_bindings:{},score:1,concrete_relation:true};const h1={...base,id:"h1",source_operation_id:"o1"} as P1RequestHypothesis,h2={...base,id:"h2",source_operation_id:"o2"} as P1RequestHypothesis;const ledger=new RecoveryLedger();const a=await probeHypothesis4L(h1,{id:1},ledger,fake as any),b=await probeHypothesis4L(h2,{id:1},ledger,fake as any);expect(a.network_fetch).toBe(true);expect(b.cache_hit).toBe(true);expect(calls).toBe(1);expect(probeCacheMetrics4L()).toEqual({probeCacheHits:1,probeNetworkFetches:1,duplicateProbeNetworkFetches:0});expect(a.proof.record.response_body_fingerprint).toBe(b.proof.record.response_body_fingerprint)});
  it("cache is run-local and resettable",async()=>{let calls=0;const fake=async()=>{calls++;return {text:JSON.stringify({id:1}),final_url:"https://api.example.test/item/1",content_type:"application/json"}};const h={id:"h",source_operation_id:"o",origin:"https://api.example.test",full_path:"/item/{id}",proof_type:"x",evidence_ids:["e"],source_urls:["s"],slots:[{id:"s",name:"id",in:"path",required:true,auth_like:false,literals:[]}],input_bindings:{id:"s"},literal_bindings:{},score:1,concrete_relation:true} as P1RequestHypothesis;const ledger=new RecoveryLedger();await probeHypothesis4L(h,{id:1},ledger,fake as any);resetProbeCache4L();await probeHypothesis4L(h,{id:1},ledger,fake as any);expect(calls).toBe(2);expect(probeCacheMetrics4L().probeNetworkFetches).toBe(1)});
  it("keeps implementation provider-blind",async()=>{const src=await readFile(new URL("../src/experiment4lRequest.ts",import.meta.url),"utf8");expect(src).not.toMatch(/openfoodfacts|nhtsa|registry\.npmjs|metmuseum|wayback\/available/i)});
  it("uses exclusive 4L provenance in validator",async()=>{const src=await readFile(new URL("../src/experiment4lContract.ts",import.meta.url),"utf8");expect(src).toContain('prefix="4L_EXECUTABLE_API_OPERATION_FAMILY:"');expect(src).not.toContain('prefix="4K_ROUTE_FAMILY_VARIABLE_SLOT:"')});
  it("derives 4L formal decision, runtime metrics and frozen base",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4lSource(src);expect(out).toContain("GO_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING");expect(out).toContain("REASSESS_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING");expect(out).toContain('base_sha:"6681c0f681959597ab75d2130fa15c37d8b979fa"');expect(out).toContain("benchmark_duration_ms");expect(out).toContain("duplicate_probe_network_fetches_zero")});
  it("produces syntactically valid generated benchmark TypeScript",async()=>{const src=await readFile(new URL("../src/experiment4ar.ts",import.meta.url),"utf8"),out=deriveExperiment4lSource(src);const result=ts.transpileModule(out,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true,fileName:"generated-4l.ts"});const errs=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);expect(errs.map(d=>ts.flattenDiagnosticMessageText(d.messageText,"\n"))).toEqual([])});
});
