import {describe,expect,it} from "vitest";
import {buildFiveB18Report} from "../src/experiment5b18Decision.js";
import {loadFiveB18Workload} from "../src/experiment5b18Workload.js";

const integrity:any={ok:true,base_sha:"base",prereg_commit:"pre",workload_commit:"work",runtime_provider_url_literals:0,runtime_provider_name_hardcoding:0,runtime_case_family_hardcoding:0};
function fixture(){const w=loadFiveB18Workload(),unhealthy=w.primaries.find(x=>x.unhealthy_after_5b15)!,other=w.primaries.find(x=>x.family!==unhealthy.family)!,mk=(p:any,n:number,recovered:boolean)=>({family:p.family,case_id:p.case_id,primary_recipe_fingerprint:p.primary_recipe_fingerprint,provider_start_url:`https://alternate-${n}.example.test`,recipe_fingerprint:`recipe-${n}`,became_executable_from_reserved_recovery:recovered,first_verification:{requested_at:"a"},confirmation_verification:{requested_at:"b"},changed_input_replay:{success:true}}),recipes=[mk(unhealthy,1,true),mk(other,2,false)],caseEvidence=w.primaries.map(p=>({family:p.family,case_id:p.case_id,selected:w.candidates.filter(c=>c.case_id===p.case_id).sort((a,b)=>a.selected_position-b.selected_position).map(c=>({candidate_id:c.candidate_id,selected_position:c.selected_position})),attempts:[],success:recipes.find(r=>r.case_id===p.case_id)?{recipe_fingerprint:recipes.find(r=>r.case_id===p.case_id)!.recipe_fingerprint}:null})),audits=w.candidates.map((c,i)=>({case_id:c.case_id,provider_candidate_id:c.candidate_id,ordinary_fetches:4,reserved_recovery_fetches:i===0?4:0,total_acquisition_fetches:i===0?8:4})),raw:any={fingerprint:"engine",metrics:{catalogIdentityResolutionFetches5b18:1,identityResolutionFailures5b18:0,attemptOrderingViolations5b18:0,attemptedProviders5b18:21,broadRetrievalCalls5b18:0,equivalenceRerankerCalls5b18:0,secondaryProviderRerankerCalls5b18:0,newProviderSelectionCalls5b18:0,manualProviderSubstitutions5b18:0,ordinaryReserveBorrowingViolations5b18:0,totalFetchBudgetViolations5b18:0,reservedRecoveryEligible5b18:1,reservedRecoveryActivated5b18:1,reservedRecoveryFetches5b18:4,reservedRecoveryProvidersBecameExecutable5b18:1,reservedRecoveryUnhealthyProvidersBecameExecutable5b18:1,reservedRecoveryOrderingNondeterminismViolations5b18:0,docFetches:88,synthesisCalls:21,synthesisRepairs:0,total_llm_cost_usd:.1,mean_llm_cost_per_qualifying_alternate_usd:.05,authLikeRenderedRequests5b18:0,wrongTaskProbeAttempts5b18:0,replay_deltas:{catalog_fetches:0,broad_retrieval_calls:0,equivalence_reranker_calls:0,secondary_reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0}},caseEvidence,recipes,replay:recipes.map(r=>({case_id:r.case_id,success:true})),providerFetchAudit5b18:audits};return {w,raw,unhealthy}}

describe("Experiment 5B18 formal decision",()=>{
 it("permits GO only when fixed-budget recovery yields multi-family replayable alternates including unhealthy recovery lineage",()=>{const {w,raw}=fixture(),report=buildFiveB18Report(raw,integrity,w);expect(report.decision).toBe("GO_5B18_EXECUTABLE_SURFACE_BUDGET_RESERVATION");expect(Object.values(report.gates).every(Boolean)).toBe(true)});
 it("rejects any ordinary or total budget violation",()=>{const {w,raw}=fixture();raw.providerFetchAudit5b18[0].ordinary_fetches=5;raw.providerFetchAudit5b18[0].total_acquisition_fetches=9;const report=buildFiveB18Report(raw,integrity,w);expect(report.gates.ordinary_fetch_limit).toBe(false);expect(report.gates.total_acquisition_fetch_limit).toBe(false);expect(report.decision).toBe("REASSESS_5B18_EXECUTABLE_SURFACE_BUDGET_RESERVATION")});
 it("rejects unhealthy coverage without reserved-recovery lineage",()=>{const {w,raw,unhealthy}=fixture(),recipe=raw.recipes.find((x:any)=>x.case_id===unhealthy.case_id);recipe.became_executable_from_reserved_recovery=false;const report=buildFiveB18Report(raw,integrity,w);expect(report.gates.every_unhealthy_primary_covered).toBe(true);expect(report.gates.unhealthy_coverage_has_reserved_recovery_lineage).toBe(false);expect(report.decision).toBe("REASSESS_5B18_EXECUTABLE_SURFACE_BUDGET_RESERVATION")});
 it("rejects any reintroduced provider discovery or replay-time cognitive work",()=>{const {w,raw}=fixture();raw.metrics.broadRetrievalCalls5b18=1;raw.metrics.replay_deltas.recovery_fetches=1;const report=buildFiveB18Report(raw,integrity,w);expect(report.gates.no_broad_provider_retrieval).toBe(false);expect(report.gates.replay_discovery_cognitive_zero).toBe(false);expect(report.decision).toBe("REASSESS_5B18_EXECUTABLE_SURFACE_BUDGET_RESERVATION")});
});
