import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4L,rebuildRequestGraph4L} from "./experiment4lRequest.js";
import {expandReferenceEvidence4N} from "./experiment4nReference.js";
import {executedTraces4N,type ExecutedGetTrace4N} from "./experiment4nTrace.js";

const AUTH=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const ASSET_EXT=/\.(?:js|mjs|css|map|png|jpe?g|gif|svg|webp|ico|bmp|avif|woff2?|ttf|otf|eot|mp4|webm|mp3|wav|pdf|zip|gz|tar)(?:$|[?#])/i;
const ASSET_SEG=/(?:^|\/)(?:static|assets?|images?|img|icons?|logos?|fonts?|styles?|scripts?|css|js|media|thumbnails?|avatars?)(?:\/|$)/i;
const DOC_SEG=/(?:^|\/)(?:docs?|documentation|reference|sdk|guide|help|support)(?:\/|$)/i;
const NAV_SEG=/(?:^|\/)(?:blog|about|contact|login|signin|signup|register|pricing|careers?|press|terms|privacy|downloads?)(?:\/|$)/i;
const SPEC_DOC=/(?:^|\/)(?:openapi|swagger)(?:[._-][^/?#]+)?\.(?:json|ya?ml)(?:$|[?#])|(?:^|\/)(?:openapi|swagger)(?:\.json|\.ya?ml)?(?:$|[?#])/i;
const ACTION=new Set(["get","lookup","search","find","retrieve","fetch","decode","estimate","resolve","convert","list","identify"]);
const NOISE=new Set(["given","public","machine","readable","api","operation","return","returns","canonical","current","human","identify","identifier","identification","metadata","string","numeric","number","matching","queried","query","estimated","information","data","value","values","result","results","using","use","provide","provides"]);
const RESERVED_PATH=new Set(["api","rest","v1","v2","v3","v4","get","search","query","lookup","decode","vehicle","vehicles","product","products","object","objects","data","json","xml","csv"]);

type Pos={kind:"path";index:number;core:string;suffix:string}|{kind:"query";key:string;core:string;suffix:string};
type ParsedTrace={trace:ExecutedGetTrace4N;origin:string;path:string;segments:string[];query:{key:string;rawKey:string;value:string}[]};
type Family={signature:string;position:Pos;members:Map<string,{parsed:ParsedTrace;value:string}>};
type Metrics=Record<string,any>;

function norm(v:any){let s=String(v??"");try{s=decodeURIComponent(s.replace(/\+/g," "))}catch{}return s.trim().toLowerCase()}
function stem(v:string){return v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"").replace(/_(?:identifier|name|code|id)$/,"_").replace(/_+$/,"_").replace(/^_+|_+$/g,"")}
function toks(v:string){return lexicalTokensP1(v)}
function overlap(a:string,b:string){const x=new Set(toks(a)),y=new Set(toks(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function splitPath(path:string){const q=path.indexOf("?");return {head:q<0?path:path.slice(0,q),query:q<0?"":path.slice(q+1)}}
function parseQuery(raw:string){if(!raw)return [] as ParsedTrace["query"];return raw.split("&").filter(Boolean).map(part=>{const i=part.indexOf("="),rawKey=i<0?part:part.slice(0,i),value=i<0?"":part.slice(i+1);return {key:norm(rawKey.replace(/^amp;/i,"")),rawKey,value:norm(value)}})}
function coreSuffix(raw:string){let d=raw;try{d=decodeURIComponent(raw)}catch{}const m=d.match(/^(.+?)(\.(?:json|xml|csv))$/i);return m?{core:m[1],suffix:m[2]}:{core:d,suffix:""}}
function hardReject(t:ExecutedGetTrace4N){if(t.disposition!=="success")return "error";let u:URL;try{u=new URL(t.requested_url)}catch{return "navigation"}const target=`${u.pathname}${u.search}`;if(ASSET_EXT.test(target)||ASSET_SEG.test(u.pathname))return "asset";if(DOC_SEG.test(u.pathname)||SPEC_DOC.test(target))return "documentation";if(NAV_SEG.test(u.pathname))return "navigation";for(const [name] of u.searchParams)if(AUTH.test(norm(name.replace(/^amp;/i,""))))return "auth";if(/text\/html/i.test(t.content_type||""))return "documentation";return null}
function parseTrace(t:ExecutedGetTrace4N){const reason=hardReject(t);if(reason)return {reason,parsed:null};let u:URL;try{u=new URL(t.requested_url)}catch{return {reason:"navigation",parsed:null}};return {reason:null,parsed:{trace:t,origin:u.origin,path:u.pathname+u.search,segments:u.pathname.split("/"),query:parseQuery(u.search.slice(1))} satisfies ParsedTrace}}
function evidenceById(evidence:DocEvidence[],id:string){return evidence.find(e=>e.evidence_id===id&&e.state==="ok")}
function localContext(p:ParsedTrace,evidence:DocEvidence[]){const parents=p.trace.parent_evidence_ids.map(id=>evidenceById(evidence,id)).filter(Boolean) as DocEvidence[];const parentText=parents.map(e=>e.text).join("\n").slice(0,40000);return `${p.path}\n${parentText}\n${p.trace.response_text.slice(0,40000)}`}
function semanticSupport(caseId:string,p:ParsedTrace,evidence:DocEvidence[]){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {entity:false,secondary:false,role:false};const text=localContext(p,evidence),op=new Set(toks(text)),intent=new Set(toks(c.intent||"")),outputs=new Set(c.required.flatMap(x=>toks(x))),inputs=new Set(c.input_names.flatMap(x=>toks(x))),entity=[...intent].filter(x=>!ACTION.has(x)&&!outputs.has(x)&&!inputs.has(x)&&!NOISE.has(x)&&x.length>2),actions=[...intent].filter(x=>ACTION.has(x)),input=c.input_names[0]||"",inputStem=stem(input);return {entity:entity.some(x=>op.has(x)),secondary:[...outputs].some(x=>op.has(x))||(actions.length>0&&actions.some(x=>op.has(x))),role:overlap(input,text)>0||(inputStem.length>=2&&norm(text).includes(inputStem))}}
function echo(text:string,value:string){const n=norm(value);if(n.length<3)return false;try{const body=JSON.parse(text),stack=[body];while(stack.length){const x=stack.pop();if(x===null||x===undefined)continue;if(["string","number","boolean"].includes(typeof x)){if(norm(x)===n)return true;continue}if(Array.isArray(x)){for(const y of x)stack.push(y);continue}if(typeof x==="object")for(const y of Object.values(x))stack.push(y)}}catch{}return norm(text).includes(n)}
function opaque(raw:string){const {core}=coreSuffix(raw),n=norm(core);if(n.length<2||RESERVED_PATH.has(n))return false;if(/^v\d+$/i.test(n))return false;return /\d/.test(n)||/[*_-]/.test(n)||(/[a-z]/i.test(n)&&n.length>=8)}
function posValue(p:ParsedTrace,pos:Pos){if(pos.kind==="path")return coreSuffix(p.segments[pos.index]||"").core;return p.query.find(q=>q.key===pos.key)?.value||""}
function familySig(p:ParsedTrace,pos:Pos){const seg=p.segments.map(norm);if(pos.kind==="path")seg[pos.index]="*";const q=p.query.map(x=>[x.key,pos.kind==="query"&&x.key===pos.key?"*":x.value] as const).sort((a,b)=>a[0].localeCompare(b[0]));return fourAp1Sha({o:p.origin,s:seg,q,pos:pos.kind==="path"?{kind:"path",index:pos.index}:{kind:"query",key:pos.key}})}
function replacePos(p:ParsedTrace,pos:Pos,input:string){if(pos.kind==="query")return p.path;const {head,query}=splitPath(p.path),seg=head.split("/"),original=seg[pos.index]||"",cs=coreSuffix(original);seg[pos.index]=original.replace(cs.core,`{${input}}`);return seg.join("/")+(query?`?${query}`:"")}
function makeHyp(p:ParsedTrace,pos:Pos,input:string,proof:string,score:number,evidenceIds:string[]){const slotName=pos.kind==="path"?input:pos.key,slot:P1RequestSlot={id:`4n_slot_${fourAp1Sha({t:p.trace.trace_id,pos,input}).slice(0,14)}`,name:slotName,in:pos.kind,required:true,auth_like:false,literals:[]};return {id:`req4n_${fourAp1Sha({t:p.trace.trace_id,pos,input,proof}).slice(0,16)}`,source_operation_id:`trace4n_${p.trace.trace_id}`,origin:p.origin,full_path:replacePos(p,pos,input),proof_type:proof,evidence_ids:[...new Set([...p.trace.parent_evidence_ids,...evidenceIds])],source_urls:[p.trace.requested_url],slots:[slot],input_bindings:{[input]:slot.id},literal_bindings:{},score,concrete_relation:true} satisfies P1RequestHypothesis}
function candidates(p:ParsedTrace,input:string,requireRole:boolean,contextRole:boolean){const out:Pos[]=[];const inputStem=stem(input);for(let i=1;i<p.segments.length;i++){const raw=p.segments[i]||"",cs=coreSuffix(raw),prev=norm(p.segments[i-1]||"");if(!opaque(raw))continue;const prevRole=inputStem.length>=2&&(prev.includes(inputStem)||inputStem.includes(prev));if(!requireRole||prevRole||contextRole)out.push({kind:"path",index:i,core:cs.core,suffix:cs.suffix})}for(const q of p.query){if(AUTH.test(q.key)||!q.value)continue;const keyRole=stem(q.key)===inputStem||overlap(q.key,input)>0;if(!requireRole||keyRole||contextRole)out.push({kind:"query",key:q.key,core:q.value,suffix:""})}return out}
function sameRoleStructure(base:P1RequestHypothesis,p:ParsedTrace,input:string){const slotId=base.input_bindings[input];if(!slotId)return null;const slot=base.slots.find(s=>s.id===slotId);if(!slot||slot.auth_like||base.origin!==p.origin)return null;const b=splitPath(base.full_path),t=splitPath(p.path),bs=b.head.split("/"),ts=t.head.split("/");if(bs.length!==ts.length)return null;if(slot.in==="path"){const indexes=bs.map((v,i)=>v.includes(`{${slot.name}}`)?i:-1).filter(i=>i>=0);if(indexes.length!==1)return null;const idx=indexes[0];for(let i=0;i<bs.length;i++)if(i!==idx&&norm(bs[i])!==norm(ts[i]))return null;const cs=coreSuffix(ts[idx]||"");return {kind:"path",index:idx,core:cs.core,suffix:cs.suffix} as Pos}const bq=parseQuery(b.query),tq=parseQuery(t.query),bv=bq.find(q=>q.key===norm(slot.name)),tv=tq.find(q=>q.key===norm(slot.name));if(!tv)return null;for(const q of bq){if(q.key===norm(slot.name))continue;const other=tq.find(x=>x.key===q.key);if(!other||other.value!==q.value)return null}return {kind:"query",key:tv.key,core:tv.value,suffix:""} as Pos}
function metrics0():Metrics{return {executedTraceEligible:0,executedTraceRejectedAsset:0,executedTraceRejectedNavigation:0,executedTraceRejectedDocumentation:0,executedTraceRejectedAuthLike:0,executedTraceRejectedLineage:0,executedTraceExactBuildSlots:0,executedTraceFamilySlots:0,executedTraceDocumentedRoleJoins:0,executedTraceDocumentedRoleJoinRejects:0,executedTraceEchoSupportedSlots:0,executedTraceHypotheses:0,documentationRouteProbeAttempts:0}}

export function buildExecutedTraceHypotheses4N(traces:ExecutedGetTrace4N[],evidence:DocEvidence[],baseHypotheses:P1RequestHypothesis[],caseId:string,providerId:string){
  const metrics=metrics0(),c=FOUR_A_CASES.find(x=>x.case_id===caseId),rows:P1RequestHypothesis[]=[];if(!c||c.input_names.length!==1)return {hypotheses:rows,metrics};const input=c.input_names[0],build=norm(c.build[input]),eligible:ParsedTrace[]=[];
  for(const t of traces){if(t.case_id!==caseId||t.provider_candidate_id!==providerId){metrics.executedTraceRejectedLineage++;continue}const x=parseTrace(t);if(x.reason){if(x.reason==="asset")metrics.executedTraceRejectedAsset++;else if(x.reason==="documentation")metrics.executedTraceRejectedDocumentation++;else if(x.reason==="auth")metrics.executedTraceRejectedAuthLike++;else metrics.executedTraceRejectedNavigation++;continue}eligible.push(x.parsed!)}
  metrics.executedTraceEligible=eligible.length;
  for(const p of eligible){const support=semanticSupport(caseId,p,evidence);if(!support.entity||!support.secondary)continue;const exact:Pos[]=[];for(let i=1;i<p.segments.length;i++){const cs=coreSuffix(p.segments[i]||"");if(norm(cs.core)===build)exact.push({kind:"path",index:i,core:cs.core,suffix:cs.suffix})}for(const q of p.query)if(q.value===build)exact.push({kind:"query",key:q.key,core:q.value,suffix:""});if(exact.length===1){if(echo(p.trace.response_text,build))metrics.executedTraceEchoSupportedSlots++;rows.push(makeHyp(p,exact[0],input,`4n_executed_trace_exact_${exact[0].kind}`,1360,p.trace.parent_evidence_ids));metrics.executedTraceExactBuildSlots++;}}
  const families=new Map<string,Family>();for(const p of eligible){for(const pos of candidates(p,input,false,false)){const key=familySig(p,pos),f=families.get(key)||{signature:key,position:pos,members:new Map()};f.members.set(p.trace.trace_id,{parsed:p,value:posValue(p,pos)});families.set(key,f)}}
  for(const f of families.values()){const ms=[...f.members.values()],values=[...new Set(ms.map(m=>norm(m.value)).filter(Boolean))];if(ms.length<2||values.length<2)continue;const support=semanticSupport(caseId,ms[0].parsed,evidence);if(!support.entity||!support.secondary)continue;const rep=[...ms].sort((a,b)=>a.parsed.trace.trace_id.localeCompare(b.parsed.trace.trace_id))[0];if(ms.some(m=>echo(m.parsed.trace.response_text,m.value)))metrics.executedTraceEchoSupportedSlots++;rows.push(makeHyp(rep.parsed,f.position,input,`4n_executed_trace_family_${f.position.kind}`,1280,ms.flatMap(m=>m.parsed.trace.parent_evidence_ids)));metrics.executedTraceFamilySlots++;}
  for(const p of eligible){const support=semanticSupport(caseId,p,evidence);if(!support.entity||!support.secondary)continue;const inherited=baseHypotheses.map(h=>sameRoleStructure(h,p,input)).filter(Boolean) as Pos[];let roleCandidates=[...inherited];if(!roleCandidates.length)roleCandidates=candidates(p,input,true,support.role);const unique=new Map<string,Pos>();for(const pos of roleCandidates){const key=pos.kind==="path"?`p:${pos.index}`:`q:${pos.key}`;unique.set(key,pos)}const candidatesUnique=[...unique.values()];if(candidatesUnique.length!==1){if(candidatesUnique.length>1)metrics.executedTraceDocumentedRoleJoinRejects++;continue}const pos=candidatesUnique[0],value=posValue(p,pos);if(!value){metrics.executedTraceDocumentedRoleJoinRejects++;continue}const parentText=p.trace.parent_evidence_ids.map(id=>evidenceById(evidence,id)?.text||"").join("\n"),roleProof=inherited.length===1||overlap(input,parentText)>0||(stem(input).length>=2&&norm(parentText).includes(stem(input)))||(pos.kind==="path"&&norm(p.segments[pos.index-1]||"").includes(stem(input)));if(!roleProof){metrics.executedTraceDocumentedRoleJoinRejects++;continue}if(echo(p.trace.response_text,value))metrics.executedTraceEchoSupportedSlots++;rows.push(makeHyp(p,pos,input,`4n_executed_trace_documented_role_${pos.kind}`,1320,p.trace.parent_evidence_ids));metrics.executedTraceDocumentedRoleJoins++;}
  const dedup=new Map<string,P1RequestHypothesis>();for(const h of rows){const key=fourAp1Sha({o:h.origin,p:h.full_path,b:h.input_bindings});const prior=dedup.get(key);if(!prior||h.score>prior.score)dedup.set(key,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));metrics.executedTraceHypotheses=hypotheses.length;return {hypotheses,metrics};
}
function rendered(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;try{return compileRequestHypothesisP1(h,c.build)}catch{return null}}
function augment(base:any,traces:ExecutedGetTrace4N[],evidence:DocEvidence[],caseId:string,providerId:string){const trace=buildExecutedTraceHypotheses4N(traces,evidence,base.hypotheses as P1RequestHypothesis[],caseId,providerId),dedup=new Map<string,P1RequestHypothesis>();for(const h of [...(base.hypotheses as P1RequestHypothesis[]),...trace.hypotheses]){const key=fourAp1Sha({o:h.origin,p:h.full_path,b:h.input_bindings,l:h.literal_bindings}),prior=dedup.get(key);if(!prior||h.score>prior.score)dedup.set(key,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));return {...base,hypotheses,metrics:{...base.metrics,...trace.metrics},graph_fingerprint:fourAp1Sha({base:base.graph_fingerprint,traces:traces.map(t=>t.trace_id),h:hypotheses.map(h=>h.id)})}}
function packet(hypotheses:P1RequestHypothesis[],caseId:string){const trace=hypotheses.filter(h=>h.proof_type.startsWith("4n_executed_trace_")),legacy=hypotheses.filter(h=>!h.proof_type.startsWith("4n_executed_trace_")),ordered=trace.length?[trace[0],...legacy.slice(0,1),...trace.slice(1),...legacy.slice(1)]:legacy,seen=new Set<string>(),out:P1RequestHypothesis[]=[];let dup=0,docs=0;for(const h of ordered){const url=rendered(h,caseId);if(!url)continue;let path="";try{path=new URL(url).pathname}catch{}if(DOC_SEG.test(path)||SPEC_DOC.test(path)){docs++;continue}if(seen.has(url)){dup++;continue}seen.add(url);out.push(h);if(out.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return {out,seen,dup,docs}}
export async function prepareRequestGraph4N(evidence:DocEvidence[],caseId:string,providerId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4N(evidence,caseId,providerId,ledger,3),base=await prepareRequestGraph4L(evidence,caseId,ledger),traces=executedTraces4N(caseId,providerId),g=augment(base,traces,evidence,caseId,providerId),p=packet(g.hypotheses as P1RequestHypothesis[],caseId);return {...g,probe_packet:p.out,metrics:{...g.metrics,...expansion,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:p.seen.size,duplicateRenderedProbeUrlsRejected4n:p.dup,documentationRouteProbeAttempts:p.docs,executedTracePacketHypotheses:p.out.filter(h=>h.proof_type.startsWith("4n_executed_trace_")).length,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0}}}
export function rebuildRequestGraph4N(evidence:DocEvidence[],caseId:string,providerId:string){const base=rebuildRequestGraph4L(evidence,caseId),traces=executedTraces4N(caseId,providerId);return augment(base,traces,evidence,caseId,providerId)}
