import {lexicalTokensP1} from "./experiment4ap1Request.js";
import type {P1RequestSlot} from "./experiment4ap1Model.js";

const GENERIC=/^(?:id|name|q|s|query|search|term|value|input)$/i;
const tok=(v:any)=>new Set(lexicalTokensP1(String(v||"")).map(x=>x.toLowerCase()));
const overlap=(a:any,b:any)=>{const x=tok(a),y=tok(b);let n=0;for(const t of x)if(y.has(t))n++;return n};
export type BindingEvidence4V={input_name:string;parameter_name:string;parameter_location:string;name_overlap:number;description_overlap:number;schema_overlap:number;placeholder_overlap:number;binding_kind:"exact_parameter_role"|"parameter_description_role"|"path_placeholder_role"|"generic_required_fallback";binding_score:number};
export function operationIntentScore4V(intent:string,required:readonly string[],op:any,path:string){const context=[op?.operationId,op?.summary,op?.description,...(Array.isArray(op?.tags)?op.tags:[]),path].filter(Boolean).join(" ");return overlap(intent,context)*20+required.reduce((n,r)=>n+overlap(r,context)*8,0)}
function localEvidence(input:string,p:any,path:string){const name=overlap(input,p?.name),desc=overlap(input,p?.description),schema=overlap(input,`${p?.schema?.title||""} ${p?.schema?.description||""}`),placeholder=p?.in==="path"&&String(path).includes(`{${p?.name}}`)?overlap(input,p?.name):0;const score=name*400+desc*180+schema*140+placeholder*220;return {name,desc,schema,placeholder,score}}
export function bindInputs4V(inputNames:readonly string[],params:any[],slots:P1RequestSlot[],intent:string,required:readonly string[],op:any,path:string){const metrics={parameterBindingCandidates4v:0,parameterBindingAcceptedLocal4v:0,parameterBindingRejectedContextLeak4v:0,parameterBindingGenericFallbacks4v:0,parameterBindingGenericFallbackRejectedIntent4v:0,parameterBindingAmbiguousRejects4v:0};const byName=new Map(slots.map(s=>[`${s.in}:${s.name}`,s])),used=new Set<string>(),bindings:Record<string,string>={},evidence:BindingEvidence4V[]=[];for(const input of inputNames){const candidates=params.filter(p=>p&&(p.in==="path"||p.in==="query")&&!used.has(`${p.in}:${p.name}`)).map(p=>{metrics.parameterBindingCandidates4v++;return {p,ev:localEvidence(input,p,path)}}).filter(x=>x.ev.score>0).sort((a,b)=>b.ev.score-a.ev.score||String(a.p.name).localeCompare(String(b.p.name)));if(candidates.length>1&&candidates[0].ev.score===candidates[1].ev.score){metrics.parameterBindingAmbiguousRejects4v++;return {bindings:null,evidence,metrics,bindingConfidence:0,intentScore:operationIntentScore4V(intent,required,op,path)}}let chosen=candidates[0],kind:BindingEvidence4V["binding_kind"]|null=null;if(chosen){kind=chosen.ev.name>0?"exact_parameter_role":chosen.ev.placeholder>0?"path_placeholder_role":"parameter_description_role";metrics.parameterBindingAcceptedLocal4v++}else if(inputNames.length===1){const unresolved=params.filter(p=>p&&(p.in==="path"||p.in==="query")&&(p.required===true||p.in==="path")&&!used.has(`${p.in}:${p.name}`));const intentScore=operationIntentScore4V(intent,required,op,path);if(unresolved.length===1&&GENERIC.test(String(unresolved[0].name||""))){if(intentScore>0){chosen={p:unresolved[0],ev:{name:0,desc:0,schema:0,placeholder:0,score:25}};kind="generic_required_fallback";metrics.parameterBindingGenericFallbacks4v++}else metrics.parameterBindingGenericFallbackRejectedIntent4v++}}if(!chosen||!kind)return {bindings:null,evidence,metrics,bindingConfidence:0,intentScore:operationIntentScore4V(intent,required,op,path)};const slot=byName.get(`${chosen.p.in}:${chosen.p.name}`);if(!slot)return {bindings:null,evidence,metrics,bindingConfidence:0,intentScore:operationIntentScore4V(intent,required,op,path)};bindings[input]=slot.id;used.add(`${chosen.p.in}:${chosen.p.name}`);evidence.push({input_name:input,parameter_name:String(chosen.p.name),parameter_location:String(chosen.p.in),name_overlap:chosen.ev.name,description_overlap:chosen.ev.desc,schema_overlap:chosen.ev.schema,placeholder_overlap:chosen.ev.placeholder,binding_kind:kind,binding_score:chosen.ev.score})}return {bindings,evidence,metrics,bindingConfidence:evidence.reduce((n,e)=>n+e.binding_score,0),intentScore:operationIntentScore4V(intent,required,op,path)}}
export function rankOperation4V(bindingConfidence:number,intentScore:number,responseCoverage:number,requiredParams:number,totalParams:number){return bindingConfidence*10+intentScore*4+responseCoverage*80-Math.max(0,requiredParams-1)*20-Math.max(0,totalParams-3)*3}
