import {mkdir,writeFile} from "node:fs/promises";
import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {createHash} from "node:crypto";
import {loadConfig} from "./config/index.js";

const TIMEOUT_MS=12000,MAX_OPS=8;
const CASES=[
 {case_id:"country_capital_coordinates",intent:"Given a country name, return coordinates for that country's capital city.",build:{country:"Costa Rica"},replay:{country:"Japan"},requires_composition:true},
 {case_id:"country_capital_name",intent:"Given a country name, return the capital city name using a manufactured missing primitive.",build:{country:"Canada"},replay:{country:"Brazil"},requires_composition:false}
] as const;
const RAW_SOURCES={worldbank_countries:{source_id:"worldbank_countries",method:"GET",url:"https://api.worldbank.org/v2/country?format=json&per_page=400",description:"World Bank public country metadata. JSON response is a two-element array: metadata then country records. Country records include name and capitalCity."}};
const EXISTING_SUPPLY={city_geocode:{capability_id:"city_geocode",description:"Geocode a city name and return first result latitude, longitude, country, and name.",input:{city:"string"},output:{latitude:"number",longitude:"number",country:"string",name:"string"},url_template:"https://geocoding-api.open-meteo.com/v1/search?name={city}&count=1&language=en&format=json"}};
const OPS=new Set(["SOURCE","ARRAY_GET","FILTER_EQ","FIRST","SELECT","TRIM","LOWERCASE","OUTPUT"]);
let plannerCalls=0,repairCalls=0,replayPlannerCalls=0,sourceViolations=0,operationViolations=0,hostViolations=0,redirectsFollowed=0,credentialsSupplied=0,arbitraryCodeExecuted=0;

type Op={op:string,source_id?:string,index?:number,path?:string,ref?:string};
type Plan={case_id:string,decision:"ROUTE"|"COMPOSE"|"MANUFACTURE"|"REJECT",reason?:string,primitive?:{primitive_id:string,input_contract:Record<string,string>,output_contract:{type:"string"|"number"|"boolean"},ops:Op[]},composition?:{downstream_capability_id:string,input_from_primitive:boolean}};

function sha(v:any){return createHash("sha256").update(JSON.stringify(v)).digest("hex");}
function timeout<T>(p:Promise<T>){return new Promise<T>((res,rej)=>{const t=setTimeout(()=>rej(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);res(v)},e=>{clearTimeout(t);rej(e)});});}
function pathGet(v:any,path:string){return path.split(".").filter(Boolean).reduce((x,k)=>x?.[k],v);}
function placeholder(v:any){return typeof v==="string"&&["","unknown","none","null","n/a","na","undefined","error","failed"].includes(v.trim().toLowerCase());}

function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const [a,b,c]=p;
 if(a===0||a===10||a===127||a>=224)return false;
 if(a===100&&b>=64&&b<=127)return false;
 if(a===169&&b===254)return false;
 if(a===172&&b>=16&&b<=31)return false;
 if(a===192&&b===0&&c===0)return false;
 if(a===192&&b===0&&c===2)return false;
 if(a===192&&b===168)return false;
 if(a===198&&b>=18&&b<=19)return false;
 if(a===198&&b===51&&c===100)return false;
 if(a===203&&b===0&&c===113)return false;
 return true;
}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1")return false;if(s.startsWith("fc")||s.startsWith("fd")||s.startsWith("fe8")||s.startsWith("fe9")||s.startsWith("fea")||s.startsWith("feb"))return false;if(s.startsWith("ff"))return false;if(s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const tail=s.slice(7);return isIP(tail)===4&&publicIPv4(tail);}return true;}
function isPublicIp(ip:string){const v=isIP(ip);return v===4?publicIPv4(ip):v===6?publicIPv6(ip):false;}
async function safeUrl(raw:string){const u=new URL(raw);const evidence:any={url:raw,protocol:u.protocol,hostname:u.hostname,resolved:[],allowed:false};if(u.protocol!=="https:"){hostViolations++;evidence.reason="non_https";throw Object.assign(new Error("host_policy_non_https"),{evidence});}if(isIP(u.hostname)){hostViolations++;evidence.reason="ip_literal";throw Object.assign(new Error("host_policy_ip_literal"),{evidence});}let addrs:{address:string,family:number}[]=[];try{addrs=await lookup(u.hostname,{all:true,verbatim:true});}catch(e){hostViolations++;evidence.reason=`dns_failure:${String(e)}`;throw Object.assign(new Error("host_policy_dns_failure"),{evidence});}evidence.resolved=addrs;if(!addrs.length||addrs.some(a=>!isPublicIp(a.address))){hostViolations++;evidence.reason="non_public_dns_answer";throw Object.assign(new Error("host_policy_non_public_dns"),{evidence});}evidence.allowed=true;return evidence;}
async function safeFetchJson(url:string,networkEvidence:any[]){const e=await safeUrl(url);networkEvidence.push(e);const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3M/0.1"},redirect:"manual",signal:ctrl.signal});if(r.status>=300&&r.status<400)throw new Error(`redirect_rejected_${r.status}`);if(!r.ok)throw new Error(`http_${r.status}`);const ct=r.headers.get("content-type")??"";if(!ct.toLowerCase().includes("json"))throw new Error("non_json_content_type");return await r.json();}finally{clearTimeout(timer);}}

function validatePlan(plan:Plan,c:any){const errors:string[]=[];if(plan.case_id!==c.case_id)errors.push("case_id_mismatch");if(plan.decision!=="MANUFACTURE")return errors;const p=plan.primitive;if(!p){errors.push("missing_primitive");return errors;}if(!p.primitive_id||!p.input_contract||!p.output_contract||!Array.isArray(p.ops))errors.push("invalid_primitive_contract");if(p.ops.length<2||p.ops.length>MAX_OPS)errors.push("invalid_op_count");let seenSource=false,seenOutput=false;for(const [i,o] of p.ops.entries()){if(!OPS.has(o.op)){operationViolations++;errors.push(`unknown_op:${o.op}`);continue;}if(seenOutput)errors.push(`op_after_output:${i}`);if(o.op==="SOURCE"){if(seenSource)errors.push("multiple_sources");seenSource=true;if(o.source_id!=="worldbank_countries"){sourceViolations++;errors.push(`unknown_source:${o.source_id}`);}}else if(!seenSource)errors.push(`op_before_source:${o.op}`);if(o.op==="ARRAY_GET"&&(!Number.isInteger(o.index)||o.index!<0))errors.push("bad_array_index");if(o.op==="FILTER_EQ"){if(!o.path||o.ref!=="$input.country")errors.push("bad_filter_eq");}if(o.op==="SELECT"&&!o.path)errors.push("bad_select");if(o.op==="OUTPUT")seenOutput=true;}if(!seenOutput)errors.push("missing_output");if(p.input_contract.country!=="string")errors.push("input_contract_must_country_string");if(p.output_contract.type!=="string")errors.push("output_contract_must_string");if(c.requires_composition){if(plan.composition?.downstream_capability_id!=="city_geocode"||plan.composition?.input_from_primitive!==true)errors.push("missing_required_composition");}return errors;}

async function executePrimitive(plan:Plan,input:any,networkEvidence:any[]){let value:any;for(const o of plan.primitive!.ops){switch(o.op){case "SOURCE":value=await safeFetchJson(RAW_SOURCES.worldbank_countries.url,networkEvidence);break;case "ARRAY_GET":if(!Array.isArray(value))throw new Error("array_get_non_array");value=value[o.index!];break;case "FILTER_EQ":if(!Array.isArray(value))throw new Error("filter_non_array");value=value.filter((x:any)=>String(pathGet(x,o.path!))===String(input.country));break;case "FIRST":if(!Array.isArray(value)||!value.length)throw new Error("first_empty");value=value[0];break;case "SELECT":value=pathGet(value,o.path!);break;case "TRIM":if(typeof value!=="string")throw new Error("trim_non_string");value=value.trim();break;case "LOWERCASE":if(typeof value!=="string")throw new Error("lower_non_string");value=value.toLowerCase();break;case "OUTPUT":return value;default:throw new Error(`unsupported_op:${o.op}`);}}throw new Error("no_output");}
async function geocode(city:string,networkEvidence:any[]){const url=EXISTING_SUPPLY.city_geocode.url_template.replace("{city}",encodeURIComponent(city));const body:any=await safeFetchJson(url,networkEvidence);const r=body?.results?.[0];if(!r||typeof r.latitude!=="number"||typeof r.longitude!=="number")throw new Error("geocode_no_result");return {latitude:r.latitude,longitude:r.longitude,country:r.country,name:r.name};}
async function executePlan(plan:Plan,c:any,input:any,networkEvidence:any[]){const primitive=await executePrimitive(plan,input,networkEvidence);if(typeof primitive!==plan.primitive!.output_contract.type||placeholder(primitive))throw new Error("primitive_output_contract_failure");if(c.requires_composition){const downstream=await geocode(String(primitive),networkEvidence);return {primitive_output:primitive,final_output:downstream};}return {primitive_output:primitive,final_output:primitive};}

async function callPlanner(config:any,c:any,failed?:string){plannerCalls++;if(failed)repairCalls++;const system=`You are MISSING Autonomous Gap Fill Planner. Existing capability supply is intentionally incomplete. Decide ROUTE, COMPOSE, MANUFACTURE, or REJECT. If existing supply cannot satisfy the intent but an approved raw source plus the frozen DSL can, choose MANUFACTURE. You may use only SOURCE, ARRAY_GET, FILTER_EQ, FIRST, SELECT, TRIM, LOWERCASE, OUTPUT. One SOURCE only, max ${MAX_OPS} ops. FILTER_EQ ref must be $input.country. Never invent URLs, code, credentials, transforms, sources, constants, or fields not described by source metadata. For Case A, if manufacturing yields the capital name, composition may call existing city_geocode with the manufactured output. Return JSON only.`;const payload={case:{case_id:c.case_id,intent:c.intent,input_schema:{country:"string"},requires_composition:c.requires_composition},existing_supply:Object.values(EXISTING_SUPPLY).map(x=>({capability_id:x.capability_id,description:x.description,input:x.input,output:x.output})),approved_raw_sources:Object.values(RAW_SOURCES),dsl:["SOURCE(source_id)","ARRAY_GET(index)","FILTER_EQ(path,$input.country)","FIRST","SELECT(path)","TRIM","LOWERCASE","OUTPUT"],output_contract:{case_id:c.case_id,decision:"ROUTE|COMPOSE|MANUFACTURE|REJECT",reason:"string",primitive:{primitive_id:"string",input_contract:{country:"string"},output_contract:{type:"string"},ops:[{op:"SOURCE",source_id:"worldbank_countries"},{op:"ARRAY_GET",index:1},{op:"FILTER_EQ",path:"name",ref:"$input.country"},{op:"FIRST"},{op:"SELECT",path:"capitalCity"},{op:"TRIM"},{op:"OUTPUT"}]},composition:c.requires_composition?{downstream_capability_id:"city_geocode",input_from_primitive:true}:undefined},previous_failure:failed??null};const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`planner_${r.status}:${await r.text()}`);const b:any=await r.json();return JSON.parse(b.choices?.[0]?.message?.content??"{}");}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3M");const results:any[]=[],persisted:any[]=[];
for(const c of CASES){let plan:Plan=await callPlanner(config,c);let staticErrors=validatePlan(plan,c);let execution:any=null,repaired=false,networkEvidence:any[]=[];if(plan.decision==="MANUFACTURE"&&staticErrors.length===0){try{execution=await executePlan(plan,c,c.build,networkEvidence);}catch(e){plan=await callPlanner(config,c,"The statically valid manufactured recipe failed live execution or output contract validation. Repair only using the same approved source, DSL, intent, and safety rules.");repaired=true;staticErrors=validatePlan(plan,c);networkEvidence=[];if(plan.decision==="MANUFACTURE"&&staticErrors.length===0)try{execution=await executePlan(plan,c,c.build,networkEvidence);}catch(e2){execution={error:String(e2)};}else execution={error:"repair_not_manufacture_or_static_invalid"};}}const validated=plan.decision==="MANUFACTURE"&&staticErrors.length===0&&execution&&!execution.error;if(validated)persisted.push({case_id:c.case_id,plan,execution,recipe_fingerprint:sha(plan)});results.push({case_id:c.case_id,plan,static_errors:staticErrors,static_valid:staticErrors.length===0,validated,repaired,execution,network_evidence:networkEvidence});}
const replay:any[]=[];for(const p of persisted){const c=CASES.find(x=>x.case_id===p.case_id)!;const before=plannerCalls;const networkEvidence:any[]=[];try{const out=await executePlan(p.plan,c,c.replay,networkEvidence);replay.push({case_id:p.case_id,success:true,input:c.replay,output:out,network_evidence:networkEvidence,recipe_fingerprint:p.recipe_fingerprint});}catch(e){replay.push({case_id:p.case_id,success:false,input:c.replay,error:String(e),network_evidence:networkEvidence,recipe_fingerprint:p.recipe_fingerprint});}replayPlannerCalls+=plannerCalls-before;}
const replaySuccess=replay.filter(x=>x.success).length,replayRate=persisted.length?replaySuccess/persisted.length:0;const caseA=results.find(x=>x.case_id==="country_capital_coordinates");const criteria={one_manufacture:results.some(x=>x.plan.decision==="MANUFACTURE"),one_static_missing_primitive:results.some(x=>x.plan.decision==="MANUFACTURE"&&x.static_valid),one_live_manufactured_primitive:persisted.length>=1,case_a_composed_result:Boolean(caseA?.validated&&typeof caseA.execution?.final_output?.latitude==="number"&&typeof caseA.execution?.final_output?.longitude==="number"),one_independent_replay:replaySuccess>=1,replay_success_rate:replayRate===1,replay_llm_calls_zero:replayPlannerCalls===0,source_operation_policy_zero:sourceViolations===0&&operationViolations===0,host_policy_zero:hostViolations===0,redirects_followed_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,evidence_fingerprints_persisted:persisted.every(x=>typeof x.recipe_fingerprint==="string"&&x.recipe_fingerprint.length===64)};const decision=Object.values(criteria).every(Boolean)?"GO_AUTONOMOUS_GAP_FILL_COMPOSITION":"REASSESS_AUTONOMOUS_GAP_FILL_COMPOSITION";
const summary={experiment:"MISSING Experiment 3M — Autonomous Gap Fill Composition",created_at:new Date().toISOString(),metrics:{cases:CASES.length,planner_calls:plannerCalls,repair_calls:repairCalls,manufacture_decisions:results.filter(x=>x.plan.decision==="MANUFACTURE").length,static_valid_primitives:results.filter(x=>x.plan.decision==="MANUFACTURE"&&x.static_valid).length,validated_primitives:persisted.length,replay_successes:replaySuccess,replay_success_rate:replayRate,replay_planner_calls:replayPlannerCalls,source_policy_violations:sourceViolations,operation_policy_violations:operationViolations,host_policy_violations:hostViolations,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted},criteria,decision,results:results.map(x=>({case_id:x.case_id,plan:x.plan,static_errors:x.static_errors,static_valid:x.static_valid,validated:x.validated,repaired:x.repaired,execution:x.execution})),replay:replay.map(x=>({case_id:x.case_id,success:x.success,input:x.input,output:x.output,error:x.error,recipe_fingerprint:x.recipe_fingerprint}))};
await mkdir("results/experiment-3m",{recursive:true});await writeFile("results/experiment-3m/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3m/evidence.json",JSON.stringify({raw_sources:RAW_SOURCES,existing_supply:EXISTING_SUPPLY,results,persisted,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
