import {readFile,writeFile} from "node:fs/promises";
import {deriveExperiment5b9Source} from "./experiment5b9Derivation.js";
import {deriveExperiment5b9PlannerSource} from "./experiment5b9PlannerDerivation.js";
const planner=await readFile(new URL("./experiment5b6Planner.ts",import.meta.url),"utf8");
await writeFile(new URL("./.generated-experiment5b9Planner.ts",import.meta.url),deriveExperiment5b9PlannerSource(planner));
const source=await readFile(new URL("./experiment4ar.ts",import.meta.url),"utf8");
const generated=deriveExperiment5b9Source(source).replace("async function rerank(async function rerank(","async function rerank(");
await writeFile(new URL("./.generated-experiment5b9.ts",import.meta.url),generated);
const generatedImport="./.generated-experiment5b9.js";
await import(generatedImport);
