import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4I,rebuildRequestGraph4I} from "./experiment4iRequest.js";
import type {Operation4G} from "./experiment4gSemantics.js";

const AUTH=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const GENERIC=new Set(["id","identifier","code","name","value","key","query","q"]);
const ACTION=new Set(["get","lookup","search","find","retrieve","fetch","decode","estimate","metadata","identify","resolve","convert","list","return","given","public","machine","readable","api","operation"]);
const WEAK=new Set(["human","canonical","current","matching","numeric","string","label","number"]);
function toks(v:string){return lexicalTokensP1(v)}
function stem(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const z of ["_identifier","_name","_code","_id"])if(s.endsWith(z)&&s.length>z.length){s=s.slice(0,-z.length);break}return s}
function taskFrame(caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {entity:new Set<string>(),action:new Set<string>(),all:new Set<string>()};const all=new Set(toks(`${c.intent} ${c.input_names.join(" ")} ${c.required.join(" ")}`)),action=new Set([...all].filter(x=>ACTION.has(x))),entity=new Set([...all].filter(x=>!ACTION.has(x)&&!WEAK.has(x)&&!GENERIC.has(x)&&x.length>2));return{entity,action,all}}
function opFrame(s:any,op:Operation4G){const sec=s.ir.sections.find((x:any)=>x.id===op.section_id);const all=new Set(toks(`${op.title} ${sec?.title||""} ${op.path} ${op.context}`)),path=new Set(toks(op.path));return{all,path}}
function overlap(a:Set<string>,b:Set<string>){let n=0;for(const x of a)if(b.has(x))n++;return n}
function entityCompatible(caseId:string,s:any,op:Operation4G,metrics:any){metrics.entityGuardCandidates++;const t=taskFrame(caseId),o=opFrame(s,op),entityOverlap=overlap(t.entity,o.all);if(entityOverlap>0){metrics.entityGuardAccepted++;return true}const pathNouns=[...o.path].filter(x=>!ACTION.has(x)&&!WEAK.has(x)&&!GENERIC.has(x)&&!/^v\d+$/.test(x)&&x.length>3);if(pathNouns.length){metrics.entityGuardRejectedExplicitMismatch++;return false}metrics.entityGuardRejectedInsufficientEntityEvidence++;return false}
function slotFor(op:Operation4G,name:string,where:"path"|"query"):P1RequestSlot{return{id:`4j_${where}_${fourAp1Sha({op:op.id,name,where}).slice(0,12)}`,name,in:where,required:true,auth_like:AUTH.test(name),literals:[]}}
function baseFor(s:any,op:Operation4G){return s.ir.api_bases.find((b:any)=>b.id===op.api_base_id)}
function genericAllowed(caseId:string,s:any,op:Operation4G,label:string,metrics:any){if(!GENERIC.has(stem(label)))return true;if(!entityCompatible(caseId,s,op,metrics)){metrics.variableRoleRejectedNoEvidence++;return false}metrics.variableRoleAcceptedGenericContextual++;return true}
function hypothesis(caseId:string,s:any,op:Operation4G,path:string,slot:P1RequestSlot,metrics:any,kind:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId),base=baseFor(s,op);if(!c||c.input_names.length!==1||!base||slot.auth_like){if(slot.auth_like)metrics.variableRoleRejectedNoEvidence++;return null}if(!entityCompatible(caseId,s,op,metrics))return null;const input=c.input_names[0],inputStem=stem(input),labelStem=stem(slot.name);if(labelStem===inputStem)metrics.variableRoleAcceptedNamed++;else if(GENERIC.has(labelStem)){if(!genericAllowed(caseId,s,op,slot.name,metrics))return null}else{const task=taskFrame(caseId);if(!task.entity.has(labelStem)&&!task.all.has(labelStem)){metrics.variableRoleRejectedNoEvidence++;return null}metrics.variableRoleAcceptedNamed++}const h:P1RequestHypothesis={id:`req4j_${fourAp1Sha({op:op.id,path,slot:slot.name,input,kind}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:path,proof_type:`4j_variable_role_${kind}_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots:[slot],input_bindings:{[input]:slot.id},literal_bindings:{},score:1500+(op.source.expanded?30:0),concrete_relation:op.absolute_url===null};return h}
function placeholderCandidates(caseId:string,s:any,op:Operation4G,metrics:any){const out:P1RequestHypothesis[]=[];for(const m of op.path.matchAll(/\{([^}]+)\}/g)){metrics.variableRoleCandidates++;const name=m[1],slot=slotFor(op,name,"path"),h=hypothesis(caseId,s,op,op.path,slot,metrics,"placeholder");if(h)out.push(h)}return out}
function queryCandidates(caseId:string,s:any,op:Operation4G,metrics:any){const out:P1RequestHypothesis[]=[];const q=op.path.indexOf("?");if(q<0)return out;for(const part of op.path.slice(q+1).split("&")){const eq=part.indexOf("=");if(eq<1)continue;const name=part.slice(0,eq),value=part.slice(eq+1);if(AUTH.test(name))continue;if(!value||/\{[^}]+\}/.test(value)){metrics.variableRoleCandidates++;const clean=op.path.slice(0,q)+"?"+op.path.slice(q+1).split("&").filter(x=>x!==part).join("&").replace(/\?$/,""),slot=slotFor(op,name,"query"),h=hypothesis(caseId,s,op,clean,slot,metrics,"query_key");if(h)out.push(h)}}return out}
function routeShapeCandidates(caseId:string,s:any,ops:Operation4G[],metrics:any){const out:P1RequestHypothesis[]=[];for(let i=0;i<ops.length;i++)for(let j=i+1;j<ops.length;j++){const a=ops[i],b=ops[j];if(a.api_base_id!==b.api_base_id)continue;const aq=a.path.split("?")[0].split("/"),bq=b.path.split("?")[0].split("/");if(aq.length!==bq.length)continue;const diff:number[]=[];for(let k=0;k<aq.length;k++)if(aq[k]!==bq[k])diff.push(k);if(diff.length!==1)continue;const k=diff[0];if(!aq[k]||!bq[k]||aq[k].includes("{")||bq[k].includes("{"))continue;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c||c.input_names.length!==1)continue;metrics.variableRoleCandidates++;if(!entityCompatible(caseId,s,a,metrics)||!entityCompatible(caseId,s,b,metrics))continue;const name=stem(c.input_names[0])||"identifier",path=[...aq];path[k]=`{${name}}`;const slot=slotFor(a,name,"path"),h=hypothesis(caseId,s,a,path.join("/"),slot,metrics,"route_shape");if(h){metrics.variableRoleAcceptedRouteShape++;out.push(h)}}return out}
function authLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let u:URL;try{u=new URL(compileRequestHypothesisP1(h,c.build))}catch{return true}for(const [n] of u.searchParams)if(AUTH.test(n))return true;return h.slots.some(s=>s.auth_like)}
function augment(base:any,evidence:DocEvidence[],caseId:string){const metrics:any={...base.metrics,variableRoleCandidates:0,variableRoleAcceptedNamed:0,variableRoleAcceptedGenericContextual:0,variableRoleAcceptedRouteShape:0,variableRoleRejectedAmbiguous:0,variableRoleRejectedNoEvidence:0,entityGuardCandidates:0,entityGuardAccepted:0,entityGuardRejectedExplicitMismatch:0,entityGuardRejectedInsufficientEntityEvidence:0,actionGuardRejectedMismatch:0,wrongEntityHypothesesBeforeProbe:0};const acceptedBase:P1RequestHypothesis[]=[];for(const h of base.hypotheses){const op=base.semantics.operations.find((x:Operation4G)=>x.id===h.source_operation_id);if(op&&entityCompatible(caseId,base.semantics,op,metrics))acceptedBase.push(h);else metrics.wrongEntityHypothesesBeforeProbe++}const extra=base.semantics.operations.flatMap((op:Operation4G)=>[...placeholderCandidates(caseId,base.semantics,op,metrics),...queryCandidates(caseId,base.semantics,op,metrics)]);extra.push(...routeShapeCandidates(caseId,base.semantics,base.semantics.operations,metrics));const dedup=new Map<string,P1RequestHypothesis>();for(const h of [...acceptedBase,...extra]){if(authLike(h,caseId))continue;const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});const prior=dedup.get(k);if(!prior||h.score>prior.score)dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));return{...base,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:base.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4J(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const raw=await prepareRequestGraph4I(evidence,caseId,ledger),g=augment(raw,evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return{...g,probe_packet:packet,metrics:{...g.metrics,authLikeRenderedRequests:0,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0,expandedEvidenceHypotheses:g.hypotheses.filter(h=>g.semantics.operations.find((o:Operation4G)=>o.id===h.source_operation_id)?.source.expanded).length}}}
export function rebuildRequestGraph4J(evidence:DocEvidence[],caseId:string){const raw=rebuildRequestGraph4I(evidence,caseId),g=augment(raw,evidence,caseId);return{...g,hypotheses:g.hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:g.hypotheses.map(h=>h.id)})}}
