import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileEvidenceNativeSemantics4G,type Operation4G,type SemanticIr4G} from "./experiment4gSemantics.js";
import type {IrParameter} from "./experiment4fIr.js";

const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const GENERIC=new Set(["id","name","code","value","key","identifier"]);
function tokens(v:string){return lexicalTokensP1(v)}
function overlap(a:string,b:string){const x=new Set(tokens(a)),y=new Set(tokens(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function norm(v:any){return String(v??"").trim().toLowerCase()}
function morphology(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const suf of ["_identifier","_name","_code","_id"])if(s.endsWith(suf)&&s.length>suf.length){s=s.slice(0,-suf.length);break}return s}
function operationText(s:SemanticIr4G,op:Operation4G){const sec=s.ir.sections.find(x=>x.id===op.section_id);return `${op.title} ${sec?.title||""} ${op.context}`}
function paramsFor(s:SemanticIr4G,op:Operation4G){return op.parameter_ids.map(id=>s.parameters.find(p=>p.id===id)).filter(Boolean) as IrParameter[]}
function findConcrete(op:Operation4G,input:string,build:string){if(!build)return null;const raw=op.raw_target;const hits:number[]=[];let pos=raw.indexOf(build);while(pos>=0){hits.push(pos);pos=raw.indexOf(build,pos+build.length)}if(hits.length!==1)return null;const inQuery=raw.slice(0,hits[0]).lastIndexOf("?")>=raw.slice(0,hits[0]).lastIndexOf("/");let name=input;if(inQuery){const prefix=raw.slice(0,hits[0]),m=prefix.match(/(?:[?&])([^=&]+)=$/);if(m)name=m[1]}return {name,in:inQuery?"query" as const:"path" as const}}
function taskBindings(caseId:string,s:SemanticIr4G,op:Operation4G,params:IrParameter[],metrics:any){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;const text=operationText(s,op),bindings:Record<string,string>={},used=new Set<string>();for(const input of c.input_names){const build=String(c.build[input]??""),inStem=morphology(input),scored=params.filter(p=>!p.auth_like&&!used.has(p.id)).map(p=>{const pStem=morphology(p.name),exact=norm(input)===norm(p.name)?420:0,morph=inStem&&pStem&&inStem===pStem?260:0,lex=overlap(input,`${p.name} ${p.description}`)*160,example=p.example!==null&&norm(p.example)===norm(build)?300:0,context=overlap(c.intent||"",text)>0?80:0,generic=(GENERIC.has(inStem)||GENERIC.has(pStem))?1:0;return {p,score:exact+morph+lex+example+context,morph:morph>0,generic}}).sort((a,b)=>b.score-a.score);let best=scored.find(x=>x.score>=240&&(!x.generic||x.score>=380));if(best?.morph){metrics.parameterMorphologyCandidates++;if(best.generic&&best.score<380){metrics.parameterMorphologyRejectedGeneric++;best=undefined}else metrics.parameterMorphologyAccepted++}
if(!best){const concrete=findConcrete(op,input,build);if(concrete&&overlap(c.intent||"",text)>0){const p:IrParameter={id:`par4g_${fourAp1Sha({o:op.id,input,build}).slice(0,16)}`,name:concrete.name,in:concrete.in,required:true,auth_like:AUTH_NAME.test(concrete.name),example:build,description:"documented concrete example",section_id:op.section_id,source:op.source};if(!p.auth_like){params.push(p);metrics.concreteExampleBindings++;best={p,score:400,morph:false,generic:GENERIC.has(morphology(p.name))}}}}
if(!best)return null;bindings[input]=best.p.id;used.add(best.p.id)}return bindings}
function make(caseId:string,s:SemanticIr4G,op:Operation4G,metrics:any){const base=s.ir.api_bases.find(b=>b.id===op.api_base_id);if(!base){if(op.source.expanded)metrics.expandedRejectNoApiBase++;return {h:null,reason:"no_base"}}const params=[...paramsFor(s,op)];if(op.auth_class==="REQUIRED"){metrics.authRequiredOperationsRejected++;if(op.source.expanded)metrics.expandedRejectAuthRequired++;return {h:null,reason:"auth"}}const bindings=taskBindings(caseId,s,op,params,metrics);if(!bindings){metrics.operationCorrespondenceRejected++;if(op.source.expanded)metrics.expandedRejectParameterOrTask++;return {h:null,reason:"correspondence"}}let path=op.path;for(const [input,pid] of Object.entries(bindings)){const p=params.find(x=>x.id===pid);if(p?.description==="documented concrete example"&&p.example){const enc=encodeURIComponent(p.example);path=path.replace(p.example,`{${input}}`).replace(enc,`{${input}}`)}}
const slots:P1RequestSlot[]=params.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:p.auth_like||AUTH_NAME.test(p.name),literals:p.example!==null?[{id:`lit4g_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:p.example}]:[]}));const input_bindings:Record<string,string>={...bindings},literal_bindings:Record<string,string>={};for(const slot of slots){if(Object.values(input_bindings).includes(slot.id)||slot.auth_like)continue;if(slot.literals.length===1&&/json/i.test(slot.literals[0].value)&&/(?:format|response|output|type)/i.test(slot.name))literal_bindings[slot.id]=slot.literals[0].id}
const h:P1RequestHypothesis={id:`req4g_${fourAp1Sha({op:op.id,base:base.id,path,input_bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:path,proof_type:`4g_evidence_native_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings,literal_bindings,score:900+(op.source.expanded?30:0)+(op.form==="4f"?0:10),concrete_relation:op.absolute_url===null};metrics.operationCorrespondenceAccepted++;return {h,reason:"ok"}}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let url="";try{url=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(url)}catch{return true}for(const [n] of u.searchParams)if(AUTH_NAME.test(n))return true;for(const slot of h.slots)if(slot.auth_like&&(slot.in==="path"||u.searchParams.has(slot.name)))return true;return false}
function buildGraph(evidence:DocEvidence[],caseId:string){const semantics=compileEvidenceNativeSemantics4G(evidence),metrics:any={...semantics.metrics,authRequiredOperationsRejected:0,parameterMorphologyCandidates:0,parameterMorphologyAccepted:0,parameterMorphologyRejectedGeneric:0,concreteExampleBindings:0,operationCorrespondenceAccepted:0,operationCorrespondenceRejected:0,expandedRejectNoApiBase:0,expandedRejectAuthRequired:0,expandedRejectParameterOrTask:0,expandedRejectRenderedAuth:0,expandedRejectDuplicate:0};const built=semantics.operations.map(op=>make(caseId,semantics,op,metrics));const dedup=new Map<string,P1RequestHypothesis>();for(const h of built.map(x=>x.h).filter(Boolean) as P1RequestHypothesis[]){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score),expandedOps=new Set(semantics.operations.filter(o=>o.source.expanded).map(o=>o.id));metrics.expandedEvidenceHypotheses=hypotheses.filter(h=>expandedOps.has(h.source_operation_id)).length;return {semantics,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4G(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),g=buildGraph(evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let authLikeRenderedRequests=0,duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;const expanded=g.semantics.operations.find(o=>o.id===h.source_operation_id)?.source.expanded===true;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;if(expanded)g.metrics.expandedRejectRenderedAuth++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;if(expanded)g.metrics.expandedRejectDuplicate++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}const metrics={...g.metrics,...expansion,authLikeRenderedRequests,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0};return {...g,probe_packet:packet,metrics}}
export function rebuildRequestGraph4G(evidence:DocEvidence[],caseId:string){const g=buildGraph(evidence,caseId),hypotheses=g.hypotheses.filter(h=>!renderedAuthLike(h,caseId));return {...g,hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
