import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {buildRequestHypothesesP1,compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";

const AUTH_LIKE=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|app[_-]?id|appid|client[_-]?id|client[_-]?secret)$/i;
const MUTATING=/\b(?:POST|PUT|PATCH|DELETE)\b/i;
const NAV_PATH=/(?:^|\/)(?:privacy|terms|legal|license|contact|about|login|signin|signup|register|account|blog|news|careers?|press|status)(?:\/|$)/i;
const ASSET=/\.(?:png|jpe?g|gif|svg|css|m?js|woff2?|pdf|zip|tar|gz)(?:$|\?)/i;
const REF_LINK=/(?:API\s*Reference|REST\s*API|Endpoints?|OpenAPI|Swagger|Developer\s*API|API\s*Docs?)/i;
export type ProofKind="openapi_operation"|"http_request_block"|"curl_request_block"|"fetch_request_block"|"axios_request_block"|"endpoint_labeled_block"|"base_relative_operation_block"|"structured_endpoint_example";
export type RequestBlock={id:string;proof_kind:ProofKind;evidence_id:string;source_url:string;raw:string;start:number;end:number;method:"GET";api_base:string|null;operation_path:string|null;absolute_url:string|null;};
function tok(v:string){return lexicalTokensP1(v)};function ov(a:string,b:string){const x=new Set(tok(a)),y=new Set(tok(b));let n=0;for(const t of x)if(y.has(t))n++;return n};function norm(v:any){return String(v??"").trim().toLowerCase()}
function normalizeTemplateSyntax(raw:string){return raw.replace(/\{\{([A-Za-z_][\w.-]*)\}\}/g,"{$1}").replace(/:([A-Za-z_][\w.-]*)/g,"{$1}").replace(/\[([A-Za-z_][\w.-]*)\]/g,"{$1}").replace(/<([A-Za-z_][\w.-]*)>/g,"{$1}")}
function safeAbs(raw:string){try{const u=new URL(normalizeTemplateSyntax(raw.replace(/[),;\]}]+$/g,"").replace(/&amp;/g,"&")));if(u.protocol!=="https:"||u.username||u.password||ASSET.test(u.pathname)||NAV_PATH.test(u.pathname))return null;return u}catch{return null}}
function windows(text:string){const out:{raw:string,start:number,end:number}[]=[];for(const m of text.matchAll(/```[\s\S]{0,1800}?```/g))out.push({raw:m[0],start:m.index??0,end:(m.index??0)+m[0].length});for(const m of text.matchAll(/(?:^|\n)(?:GET\s+[^\n]+|curl\s+[^\n]+|fetch\s*\([^\n]+|axios\.get\s*\([^\n]+|(?:Base\s+URL|Endpoint|Request\s+URL|API\s+URL)\s*:[^\n]+)(?:\n[^\n]{0,300}){0,4}/gmi))out.push({raw:m[0],start:m.index??0,end:(m.index??0)+m[0].length});return [...new Map(out.map(x=>[`${x.start}:${x.end}`,x])).values()]}
function blockFrom(ev:DocEvidence,w:{raw:string,start:number,end:number}):RequestBlock[]{const raw=w.raw;if(MUTATING.test(raw)&&!/\bGET\b/i.test(raw))return[];let kind:ProofKind|null=null;if(/\baxios\.get\s*\(/i.test(raw))kind="axios_request_block";else if(/\bfetch\s*\(/i.test(raw))kind="fetch_request_block";else if(/\bcurl\b/i.test(raw))kind="curl_request_block";else if(/\bGET\s+/i.test(raw))kind="http_request_block";else if(/\b(?:Endpoint|Request\s+URL|API\s+URL)\s*:/i.test(raw))kind="endpoint_labeled_block";if(!kind)return[];let abs:string|null=null,rel:string|null=null,base:string|null=null;const get=raw.match(/\bGET\s+(https:\/\/[^\s"'`\\]+|\/[^\s"'`\\]+)/i);const curl=raw.match(/\bcurl\b[^\n]*?(https:\/\/[^\s"'`\\]+)/i);const fetch=raw.match(/\bfetch\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/i);const axios=raw.match(/\baxios\.get\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/i);const lab=raw.match(/\b(?:Endpoint|Request\s+URL|API\s+URL)\s*:\s*(https:\/\/[^\s"'`\\]+)/i);const bm=raw.match(/\b(?:Base\s+URL|API\s+Base)\s*:\s*(https:\/\/[^\s"'`\\]+)/i);const cand=(get?.[1]?.startsWith("https://")?get[1]:null)||curl?.[1]||fetch?.[1]||axios?.[1]||lab?.[1]||null;if(cand){const u=safeAbs(cand);if(!u)return[];abs=u.toString();base=u.origin;rel=normalizeTemplateSyntax(`${u.pathname}${u.search}`);}else if(get?.[1]?.startsWith("/"))rel=normalizeTemplateSyntax(get[1]);if(bm){const u=safeAbs(bm[1]);if(u)base=u.origin;}if(rel&&base&&!abs)kind="base_relative_operation_block";return [{id:`blk_${fourAp1Sha({e:ev.evidence_id,s:w.start,k:kind,raw}).slice(0,16)}`,proof_kind:kind,evidence_id:ev.evidence_id,source_url:ev.resolved_url||ev.requested_url,raw,start:w.start,end:w.end,method:"GET",api_base:base,operation_path:rel,absolute_url:abs}]}
export function extractStructuredRequestBlocks4D(evidence:DocEvidence[]){const out:RequestBlock[]=[];for(const ev of evidence){if(ev.state!=="ok")continue;for(const w of windows(ev.text))out.push(...blockFrom(ev,w));}return [...new Map(out.map(x=>[x.id,x])).values()]}
function normalizePath(path:string){return normalizeTemplateSyntax(path)}
function hypothesis(b:RequestBlock,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c||!b.api_base||!b.operation_path)return null;let path=normalizePath(b.operation_path),u=new URL(path,b.api_base),slots:P1RequestSlot[]=[];for(const m of path.matchAll(/\{([A-Za-z_][\w.-]*)\}/g))slots.push({id:`par_${fourAp1Sha({b:b.id,n:m[1],p:true}).slice(0,14)}`,name:m[1],in:"path",required:true,auth_like:AUTH_LIKE.test(m[1]),literals:[]});for(const [name,value] of u.searchParams)slots.push({id:`par_${fourAp1Sha({b:b.id,n:name,q:true}).slice(0,14)}`,name,in:"query",required:false,auth_like:AUTH_LIKE.test(name),literals:value?[{id:`lit_${fourAp1Sha({b:b.id,name,value}).slice(0,14)}`,value}]:[]});const bindings:Record<string,string>={},used=new Set<string>();for(const input of c.input_names){const build=String(c.build[input]??"");let cand=slots.filter(s=>!s.auth_like&&!used.has(s.id)).map(s=>({s,n:ov(input,s.name)*120+(s.literals.some(l=>norm(l.value)===norm(build))?220:0)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n);if(!cand.length&&c.input_names.length===1&&slots.length===1)cand=[{s:slots[0],n:25}];if(!cand.length){const seg=path.split("/"),hits:number[]=[];for(let i=0;i<seg.length;i++){let d=seg[i];try{d=decodeURIComponent(d)}catch{}if(norm(d)===norm(build))hits.push(i)}if(hits.length===1){seg[hits[0]]=`{${input}}`;path=seg.join("/");const s={id:`par_${fourAp1Sha({b:b.id,input}).slice(0,14)}`,name:input,in:"path" as const,required:true,auth_like:false,literals:[]};slots.push(s);cand=[{s,n:180}]}}if(!cand.length)return null;bindings[input]=cand[0].s.id;used.add(cand[0].s.id)}if(slots.some(s=>s.required&&s.auth_like))return null;const literals:Record<string,string>={};for(const s of slots)if(!used.has(s.id)&&s.literals.length===1&&/json/i.test(s.literals[0].value)&&/(?:format|response|output|type)/i.test(s.name))literals[s.id]=s.literals[0].id;return {id:`req_${fourAp1Sha({b:b.id,path,bindings,literals}).slice(0,16)}`,source_operation_id:b.id,origin:b.api_base,full_path:path,proof_type:`4d_${b.proof_kind}`,evidence_ids:[b.evidence_id],source_urls:[b.source_url],slots,input_bindings:bindings,literal_bindings:literals,score:600,concrete_relation:!b.absolute_url} satisfies P1RequestHypothesis}
export function buildStructuredRequestGraph4D(evidence:DocEvidence[],caseId:string){const blocks=extractStructuredRequestBlocks4D(evidence),direct=blocks.map(b=>hypothesis(b,caseId)).filter(Boolean) as P1RequestHypothesis[];const specIds=new Set(evidence.filter(e=>e.state==="ok"&&e.text.startsWith("R6R_VERIFIED_API_SPEC\n")).map(e=>e.evidence_id));const inherited=specIds.size?buildRequestHypothesesP1(evidence,caseId).hypotheses.filter(h=>h.evidence_ids.some(id=>specIds.has(id))).map(h=>({...h,proof_type:`4d_structured_${h.proof_type}`,score:h.score+300})):[];const dedup=new Map<string,P1RequestHypothesis>();for(const h of [...direct,...inherited]){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score),packet:P1RequestHypothesis[]=[],rendered=new Set<string>();let duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of hypotheses){if(!c)break;let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(rendered.has(url)){duplicateRenderedProbeUrlsRejected++;continue}rendered.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}const kinds:Record<string,number>={};for(const b of blocks)kinds[b.proof_kind]=(kinds[b.proof_kind]||0)+1;const placeholderSyntaxCounts={brace:blocks.reduce((n,b)=>n+(b.raw.match(/\{[A-Za-z_][\w.-]*\}/g)?.length||0),0),colon:blocks.reduce((n,b)=>n+(b.raw.match(/:[A-Za-z_][\w.-]*/g)?.length||0),0),bracket:blocks.reduce((n,b)=>n+(b.raw.match(/\[[A-Za-z_][\w.-]*\]/g)?.length||0),0),angle:blocks.reduce((n,b)=>n+(b.raw.match(/<[A-Za-z_][\w.-]*>/g)?.length||0),0),double_brace:blocks.reduce((n,b)=>n+(b.raw.match(/\{\{[A-Za-z_][\w.-]*\}\}/g)?.length||0),0)};return {blocks,hypotheses,probe_packet:packet,metrics:{structuredRequestBlocks:blocks.length,blocksByProofKind:kinds,placeholderSyntaxCounts,baseRelativeLinksFormed:blocks.filter(b=>b.proof_kind==="base_relative_operation_block").length,boundedReferenceExpansions:evidence.filter(e=>e.state==="ok"&&REF_LINK.test(e.text)).length,noStructuredRequestBlock:blocks.length===0,structuredBlockUnusable:blocks.length>0&&hypotheses.length===0,structuredRequestHypotheses:hypotheses.length,uniqueRenderedProbeUrls:rendered.size,duplicateRenderedProbeUrlsRejected,standaloneUrlPromotions:0,documentationOriginFallbacks:0},graph_fingerprint:fourAp1Sha({blocks:blocks.map(b=>b.id),hypotheses:hypotheses.map(h=>h.id)})}}
