import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type Config={source_base_url:string;capability_queries:string[];search_results_per_query:number;max_services_per_group:number;checks_per_service:number;checks_page_size:number;min_total_checks:number;min_overlap_hours:number;failure_hour_threshold:number;behavioral_phi_threshold:number;joint_failure_multiplier_threshold:number;min_failure_hours_per_service:number;min_joint_failure_hours:number;request_spacing_ms:number};
type Service={id?:string;slug?:string;name?:string;title?:string;url?:string;endpoint?:string;uptime?:number;[key:string]:unknown};
type Check={created_at?:string;checked_at?:string;timestamp?:string;success?:boolean;status?:string;status_code?:number;http_status?:number;[key:string]:unknown};

type HourState={hour:string;down:boolean;checks:number;failed:number};

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const arr=(v:any):any[]=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:Array.isArray(v?.services)?v.services:Array.isArray(v?.checks)?v.checks:Array.isArray(v?.items)?v.items:[];
const serviceId=(s:Service)=>String(s.id??s.slug??s.name??s.url??s.endpoint??"");

async function getJson(url:string){const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-1C/0.1"}});if(!r.ok)throw new Error(`${r.status} ${r.statusText} for ${url}`);return r.json();}
function ts(c:Check){return String(c.checked_at??c.created_at??c.timestamp??"");}
function ok(c:Check){if(typeof c.success==="boolean")return c.success;if(typeof c.status_code==="number")return c.status_code>=200&&c.status_code<500;if(typeof c.http_status==="number")return c.http_status>=200&&c.http_status<500;const s=String(c.status??"").toLowerCase();return ["ok","up","healthy","success","passed"].includes(s);}
function hourly(checks:Check[],threshold:number):HourState[]{const m=new Map<string,{checks:number;failed:number}>();for(const c of checks){const d=new Date(ts(c));if(Number.isNaN(d.getTime()))continue;const h=d.toISOString().slice(0,13)+":00:00.000Z";const x=m.get(h)??{checks:0,failed:0};x.checks++;if(!ok(c))x.failed++;m.set(h,x);}return [...m.entries()].sort().map(([hour,x])=>({hour,checks:x.checks,failed:x.failed,down:x.checks>0&&x.failed/x.checks>=threshold}));}
function pairStats(a:HourState[],b:HourState[]){const bm=new Map(b.map(x=>[x.hour,x]));const pairs=a.filter(x=>bm.has(x.hour)).map(x=>[x,bm.get(x.hour)!] as const);let n11=0,n10=0,n01=0,n00=0;for(const [x,y] of pairs){if(x.down&&y.down)n11++;else if(x.down)n10++;else if(y.down)n01++;else n00++;}const n=pairs.length;const fa=n11+n10,fb=n11+n01;const pa=n?fa/n:0,pb=n?fb/n:0;const expected=n*pa*pb;const denom=Math.sqrt((n11+n10)*(n01+n00)*(n11+n01)*(n10+n00));const phi=denom?((n11*n00-n10*n01)/denom):0;return {overlap_hours:n,failure_hours_a:fa,failure_hours_b:fb,joint_failure_hours:n11,expected_joint_failures_independent:expected,joint_failure_multiplier:expected?n11/expected:0,phi,n11,n10,n01,n00};}

async function fetchServices(base:string,q:string,limit:number){const u=new URL(`${base}/services`);u.searchParams.set("q",q);u.searchParams.set("per_page",String(limit));return arr(await getJson(u.toString())) as Service[];}
async function fetchChecks(base:string,id:string,cfg:Config){const all:Check[]=[];const pageSize=Math.min(100,cfg.checks_page_size);let offset=0;while(all.length<cfg.checks_per_service){const u=new URL(`${base}/services/${encodeURIComponent(id)}/checks`);u.searchParams.set("limit",String(pageSize));u.searchParams.set("offset",String(offset));let rows:Check[];try{rows=arr(await getJson(u.toString())) as Check[];}catch(e){if(offset===0)throw e;break;}if(!rows.length)break;all.push(...rows);if(rows.length<pageSize)break;offset+=rows.length;await sleep(cfg.request_spacing_ms);}return all.slice(0,cfg.checks_per_service);}

const cfg=JSON.parse(await readFile(resolve("experiments/experiment-1c/config.json"),"utf8")) as Config;
const rawGroups:any[]=[];const serviceCache=new Map<string,{service:Service;checks:Check[];hours:HourState[]}>();
for(const query of cfg.capability_queries){const services=(await fetchServices(cfg.source_base_url,query,cfg.search_results_per_query)).slice(0,cfg.max_services_per_group);const group:any={query,services:[]};for(const s of services){const id=serviceId(s);if(!id)continue;let rec=serviceCache.get(id);if(!rec){await sleep(cfg.request_spacing_ms);let checks:Check[]=[];try{checks=await fetchChecks(cfg.source_base_url,id,cfg);}catch(e){group.services.push({id,service:s,error:String(e)});continue;}rec={service:s,checks,hours:hourly(checks,cfg.failure_hour_threshold)};serviceCache.set(id,rec);}group.services.push({id,service:s,total_checks:rec.checks.length,hour_observations:rec.hours.length});}rawGroups.push(group);await sleep(cfg.request_spacing_ms);}

const pairs:any[]=[];const qualifyingGroups=[] as string[];
for(const g of rawGroups){const eligible=g.services.filter((x:any)=>!x.error&&(serviceCache.get(x.id)?.checks.length??0)>=cfg.min_total_checks);if(eligible.length>=2)qualifyingGroups.push(g.query);for(let i=0;i<eligible.length;i++)for(let j=i+1;j<eligible.length;j++){const a=serviceCache.get(eligible[i].id)!,b=serviceCache.get(eligible[j].id)!;const stats=pairStats(a.hours,b.hours);const enoughFailures=stats.failure_hours_a>=cfg.min_failure_hours_per_service&&stats.failure_hours_b>=cfg.min_failure_hours_per_service;const candidate=stats.overlap_hours>=cfg.min_overlap_hours&&enoughFailures&&stats.joint_failure_hours>=cfg.min_joint_failure_hours&&stats.phi>=cfg.behavioral_phi_threshold&&stats.joint_failure_multiplier>=cfg.joint_failure_multiplier_threshold;pairs.push({query:g.query,service_a:eligible[i].id,service_b:eligible[j].id,...stats,correlated_failure_candidate:candidate});}}
const comparable=pairs.filter(p=>p.overlap_hours>=cfg.min_overlap_hours);const failureComparable=comparable.filter(p=>p.failure_hours_a>=cfg.min_failure_hours_per_service&&p.failure_hours_b>=cfg.min_failure_hours_per_service);const candidates=pairs.filter(p=>p.correlated_failure_candidate);
const criteria={two_groups_with_supply:qualifyingGroups.length>=2,five_comparable_pairs:comparable.length>=5,at_least_one_pair_with_failures:failureComparable.length>=1,at_least_one_correlated_candidate:candidates.length>=1,raw_and_hourly_evidence_persisted:true};
const decision=Object.values(criteria).every(Boolean)?"GO_REAL_INDEPENDENCE_GRAPH":"INSUFFICIENT_REAL_EVIDENCE";
const evidence={created_at:new Date().toISOString(),source:cfg.source_base_url,source_limitation:"Health checks measure x402/payment-handshake availability, not semantic correctness of paid execution.",groups:rawGroups,services:[...serviceCache.entries()].map(([id,r])=>({id,service:r.service,checks:r.checks,hourly:r.hours}))};
const summary={experiment:"MISSING Experiment 1C — Real Supply Independence Graph",created_at:new Date().toISOString(),config:cfg,metrics:{qualifying_groups:qualifyingGroups.length,total_unique_services:serviceCache.size,total_pairs:pairs.length,comparable_pairs:comparable.length,pairs_with_failures:failureComparable.length,correlated_failure_candidates:candidates.length},criteria,decision,pairs};
await mkdir("results/experiment-1c",{recursive:true});await writeFile("results/experiment-1c/evidence.json",JSON.stringify(evidence,null,2)+"\n");await writeFile("results/experiment-1c/summary.json",JSON.stringify(summary,null,2)+"\n");console.log(JSON.stringify(summary,null,2));
