import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {parsePublicApis} from "./experiment3tCore.js";
import {registrableDomain} from "./experiment3uCore.js";
import {RecoveryLedger,normalizeTokenText,parseOpenApiText,sha3yr} from "./experiment3yrCore.js";

export const RECOVERY_R2_TOP_K=120;
const GENERIC=new Set(["api","public","name","id","code","metadata","machine","readable","canonical","return","given","identify","operation"]);
const STOP=new Set(["a","an","the","and","or","of","to","for","from","in","on","by","with","without","that","this","these","those","can","could","should","would","may","might","be","is","are","was","were","as","at","via","about","into","using","use","get"]);

export function singularizeToken(raw:string){const w=normalizeTokenText(raw);if(w.length<=3)return w;if(w.endsWith("ies")&&w.length>4)return `${w.slice(0,-3)}y`;if(w.endsWith("sses"))return w.slice(0,-2);if(w.endsWith("xes")||w.endsWith("ches")||w.endsWith("shes"))return w.slice(0,-2);if(w.endsWith("s")&&!w.endsWith("ss"))return w.slice(0,-1);return w;}
export function semanticTokens(s:string){const raw=(normalizeTokenText(s).match(/[\p{L}\p{N}]+/gu)||[]);return raw.map(singularizeToken).filter(x=>x.length>=2&&!GENERIC.has(x)&&!STOP.has(x));}
export function uniqueSemanticTokens(s:string){return [...new Set(semanticTokens(s))];}

export function recoveredBroadRetrieveR2(c:any,md:string){const entries=parsePublicApis(md),q=uniqueSemanticTokens(`${c.intent} ${c.input_names.join(" ")} ${c.required_output_leaf_names.join(" ")}`),docs=entries.map(e=>semanticTokens(`${e.name} ${e.description} ${e.category}`)),df=new Map<string,number>();for(const d of docs)for(const w of new Set(d))df.set(w,(df.get(w)||0)+1);const N=Math.max(entries.length,1);const scored=entries.map((e,i)=>{const d=docs[i],freq=new Map<string,number>();for(const w of d)freq.set(w,(freq.get(w)||0)+1);let score=0;for(const w of q){const n=df.get(w)||0,idf=Math.log(1+(N-n+0.5)/(n+0.5)),tf=freq.get(w)||0;if(tf)score+=idf*((tf*2.2)/(tf+1.2));else if(w.length>=5&&d.some(x=>x.length>=5&&(x.includes(w)||w.includes(x))))score+=idf*0.12;}return {...e,score};});return scored.sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,RECOVERY_R2_TOP_K).map((e,i)=>({candidate_id:`r2${String(i+1).padStart(3,"0")}_${sha3yr(`${c.case_id}|${e.name}|${e.link}`).slice(0,10)}`,lexical_rank:i+1,...e}));}

function privateIpv4(ip:string){const p=ip.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===198&&(p[1]===18||p[1]===19))||p[0]>=224;}
export function privateAddress(ip:string){if(isIP(ip)===4)return privateIpv4(ip);if(isIP(ip)===6){const n=ip.toLowerCase();return n==="::"||n==="::1"||n.startsWith("fc")||n.startsWith("fd")||n.startsWith("fe8")||n.startsWith("fe9")||n.startsWith("fea")||n.startsWith("feb")||n.startsWith("ff");}return true;}
export async function validatePublicHostname(hostname:string,ledger?:RecoveryLedger,resolver=lookup){if(isIP(hostname)){ledger?.record("guard","private_hosts",false,hostname);throw new Error("hostname_ip_literal");}let rows:{address:string;family:number}[];try{rows=await resolver(hostname,{all:true,verbatim:true}) as any;}catch(e){ledger?.record("guard","dns_resolution",false,{hostname,error:String(e)});throw new Error("dns_resolution_failed");}if(!rows.length)throw new Error("dns_empty");for(const row of rows)if(privateAddress(row.address)){ledger?.record("guard","private_hosts",false,{hostname,address:row.address});throw new Error("dns_private_address");}ledger?.record("guard","public_dns",true,{hostname,addresses:rows.map(x=>x.address)});return rows.map(x=>x.address);}

export async function validateSafeUrlR2(startRaw:string,currentRaw:string,targetRaw:string,ledger:RecoveryLedger,resolver=lookup){let start:URL,current:URL,next:URL;try{start=new URL(startRaw);current=new URL(currentRaw);next=new URL(targetRaw,current);}catch{ledger.record("guard","invalid_url",false,targetRaw);throw new Error("invalid_url");}if(next.protocol!=="https:"){ledger.record("guard","non_https",false,next.toString());throw new Error("non_https");}if(next.username||next.password){ledger.record("guard","credentials",false);throw new Error("credentials");}if(registrableDomain(start.hostname)!==registrableDomain(next.hostname)){ledger.record("guard","cross_domain_docs",false,next.hostname);throw new Error("cross_domain");}await validatePublicHostname(next.hostname,ledger,resolver);return next.toString();}

export async function fetchTextSafeR2(startUrl:string,url:string,maxBytes:number,ledger:RecoveryLedger,resolver=lookup){let current=await validateSafeUrlR2(startUrl,startUrl,url,ledger,resolver);for(let hop=0;hop<=2;hop++){ledger.record("network","fetch",true,{url:current,hop});const r=await fetch(current,{redirect:"manual",headers:{accept:"application/json,application/yaml,text/yaml,application/x-yaml,text/html,text/plain,*/*"}});if(r.status>=300&&r.status<400){const loc=r.headers.get("location");if(!loc)throw new Error("redirect_without_location");if(hop===2)throw new Error("redirect_limit_exceeded");current=await validateSafeUrlR2(startUrl,current,loc,ledger,resolver);continue;}if(!r.ok)throw new Error(`http_${r.status}`);const text=await r.text();if(Buffer.byteLength(text)>maxBytes)throw new Error("body_too_large");return {text,content_type:r.headers.get("content-type")||"",final_url:current};}throw new Error("redirect_limit_exceeded");}

export function parseRepresentativeYaml(){const fixture=`openapi: 3.0.3\ninfo:\n  title: Representative API\n  version: 1.0.0\npaths:\n  /resource/{id}:\n    get:\n      parameters:\n        - name: id\n          in: path\n          required: true\n      responses:\n        '200':\n          description: ok\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  id:\n                    type: string\n`;return parseOpenApiText(fixture);}

export function safetyGateFromLedger(ledger:RecoveryLedger,counters:Record<string,number>){const unsafeAccepted=ledger.events.filter(e=>e.accepted&&["credentials","authorization_headers","non_get","non_https","private_hosts","cross_domain_docs","endpoint_mutations","invented_parameters","invented_output_fields","arbitrary_code","ungrounded_projection_fields","replay_external_calls"].includes(e.kind));return unsafeAccepted.length===0&&Object.values(counters).every(v=>v===0);}
