import {deriveExperiment4pSource} from "./experiment4pDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4q_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4qSource(source:string){
 let x=deriveExperiment4pSource(source);
 x=r(x,'import {compile4p as compile4ar,project4p as project4ar,scope4p as scope4ar,validate4p as validate4ar,validateProjected4p as validateProjected4ar} from "./experiment4pContract.js";','import {compile4q as compile4ar,project4q as project4ar,scope4q as scope4ar,validate4q as validate4ar,validateProjected4q as validateProjected4ar} from "./experiment4qContract.js";');
 x=r(x,'import {synthesize4p as synthesize4ar} from "./experiment4pPlanner.js";','import {synthesize4q as synthesize4ar} from "./experiment4qPlanner.js";');
 x=r(x,'const OUT="results/experiment-4p",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4q",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
 x=r(x,'const llmUsage:any[]=[];let rerankPreparedCases4p=0,rerankCompletedCases4p=0,rerankMaxObservedConcurrency4p=0,rerankWallPhaseMs4p=0,rerankAggregateCaseLatencyMs4p=0;const rerankConcurrencyLimit4p=3;','const llmUsage:any[]=[];let rerankPreparedCases4p=0,rerankCompletedCases4p=0,rerankMaxObservedConcurrency4p=0,rerankWallPhaseMs4p=0,rerankAggregateCaseLatencyMs4p=0,representationPreferenceGroups4q=0,representationPreferenceSwaps4q=0,representationJsonPreferredGroups4q=0,lowerPreferenceEquivalentTraceBeforeJson4q=0,identityProjectionSelections4q=0;const rerankConcurrencyLimit4p=3;');
 x=r(x,'executedTraceDocumentedRoleProbeCalls4n+=a.executedTraceDocumentedRoleProbeCalls||0;executedTraceDocumentedRoleProbe2xxJson4n+=a.executedTraceDocumentedRoleProbe2xxJson||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;','executedTraceDocumentedRoleProbeCalls4n+=a.executedTraceDocumentedRoleProbeCalls||0;executedTraceDocumentedRoleProbe2xxJson4n+=a.executedTraceDocumentedRoleProbe2xxJson||0;representationPreferenceGroups4q+=a.alignment_metrics?.representationPreferenceGroups||0;representationPreferenceSwaps4q+=a.alignment_metrics?.representationPreferenceSwaps||0;representationJsonPreferredGroups4q+=a.alignment_metrics?.representationJsonPreferredGroups||0;lowerPreferenceEquivalentTraceBeforeJson4q+=a.alignment_metrics?.lowerPreferenceEquivalentTraceBeforeJson||0;if(a.identity_projection_selected)identityProjectionSelections4q++;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;');
 x=x.replaceAll('4o_request_hypothesis_not_in_trace_graph','4q_request_hypothesis_not_in_trace_graph').replaceAll('4o_trace_origin_drift','4q_trace_origin_drift').replaceAll('4o_trace_request_mutation','4q_trace_request_mutation').replaceAll('4o_row_lookup_not_observed','4q_row_lookup_not_observed').replaceAll('4o_forbidden_input_source','4q_forbidden_input_source');
 x=r(x,'forbiddenInputSourceSelections:forbiddenInputSourceSelections4o,rerankPreparedCases:rerankPreparedCases4p','forbiddenInputSourceSelections:forbiddenInputSourceSelections4o,representationPreferenceGroups:representationPreferenceGroups4q,representationPreferenceSwaps:representationPreferenceSwaps4q,representationJsonPreferredGroups:representationJsonPreferredGroups4q,lowerPreferenceEquivalentTraceBeforeJson:lowerPreferenceEquivalentTraceBeforeJson4q,identityProjectionSelections:identityProjectionSelections4q,rerankPreparedCases:rerankPreparedCases4p');
 x=r(x,'rerank_concurrency_bounded:rerankMaxObservedConcurrency4p<=rerankConcurrencyLimit4p&&rerankMaxObservedConcurrency4p>0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,','rerank_concurrency_bounded:rerankMaxObservedConcurrency4p<=rerankConcurrencyLimit4p&&rerankMaxObservedConcurrency4p>0,representation_json_preference_integrity:lowerPreferenceEquivalentTraceBeforeJson4q===0,identity_projection_integrity:forbiddenInputSourceSelections4o===0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,');
 x=x.replaceAll('4P_PROJECTION_COMPATIBILITY:','4Q_EVIDENCE_PREFERENCE_IDENTITY:').replaceAll('4P_MAPPING_REJECT','4Q_MAPPING_REJECT').replaceAll('GO_4P_PROJECTION_COMPATIBILITY_ENVELOPE','GO_4Q_EVIDENCE_PREFERENCE_IDENTITY_PRESERVING_PROJECTION').replaceAll('REASSESS_4P_PROJECTION_COMPATIBILITY_ENVELOPE','REASSESS_4Q_EVIDENCE_PREFERENCE_IDENTITY_PRESERVING_PROJECTION');
 x=r(x,'experiment:"4P",purpose:"development_projection_compatibility_envelope"','experiment:"4Q",purpose:"development_evidence_preference_identity_preserving_projection"');
 x=r(x,'base_sha:"3a1fffc82d3854302b34e9bcfc1a4e1f44ac0744"','base_sha:"89360e887796f967d987d9c08a4841d457cb66c1"');
 x=x.replaceAll('./experiment4pPlanner.ts','./experiment4qPlanner.ts').replaceAll('./experiment4pContract.ts','./experiment4qContract.ts').replaceAll('./experiment4pDerivation.ts','./experiment4qDerivation.ts');
 x=x.replace('plannerSource=(await readFile(new URL("./experiment4qPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4pCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oRelational.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4pSchedule.ts",import.meta.url),"utf8"))','plannerSource=(await readFile(new URL("./experiment4qPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qPreference.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oRelational.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4pSchedule.ts",import.meta.url),"utf8"))');
 return x;
}
