import {FOUR_A_CASES} from "./experiment4aCore.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import type {IrParameter} from "./experiment4fIr.js";
import type {Operation4G,SemanticIr4G} from "./experiment4gSemantics.js";

const GENERIC=new Set(["id","name","code","value","key","identifier"]);
const ACTION=new Set(["get","lookup","search","find","retrieve","fetch","decode","estimate","metadata","identify","resolve","convert","list"]);
function toks(v:string){return lexicalTokensP1(v)}
function stem(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const suffix of ["_identifier","_name","_code","_id"])if(s.endsWith(suffix)&&s.length>suffix.length){s=s.slice(0,-suffix.length);break}return s}
function overlap(a:Iterable<string>,b:Iterable<string>){const y=new Set(b);let n=0;for(const x of a)if(y.has(x))n++;return n}
function set(v:string){return new Set(toks(v))}
function opText(s:SemanticIr4G,op:Operation4G){const sec=s.ir.sections.find(x=>x.id===op.section_id);return `${op.title} ${sec?.title||""} ${op.path} ${op.context}`}
export type AlignmentResult={accepted:boolean;bindings:Record<string,string>;score:number;reason:string;signals:{identifier:number;entity:number;action:number;output:number;generic:boolean;concrete:boolean;morphology:boolean}};
export function alignTaskOperation4H(caseId:string,s:SemanticIr4G,op:Operation4G,params:IrParameter[],metrics:any):AlignmentResult{const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {accepted:false,bindings:{},score:0,reason:"unknown_case",signals:{identifier:0,entity:0,action:0,output:0,generic:false,concrete:false,morphology:false}};metrics.operationFrameCandidates++;const text=opText(s,op),opTokens=set(text),intentTokens=set(c.intent||""),outputTokens=new Set(c.required.flatMap(x=>toks(x))),actionTask=new Set([...intentTokens].filter(x=>ACTION.has(x))),actionOp=new Set([...opTokens].filter(x=>ACTION.has(x)));const entity=Math.min(3,overlap(new Set([...intentTokens,...outputTokens]),opTokens));const action=Math.min(2,overlap(actionTask,actionOp));const output=Math.min(3,overlap(outputTokens,opTokens));if(entity)metrics.operationFrameWithEntitySignal++;if(action)metrics.operationFrameWithActionSignal++;if(output)metrics.operationFrameWithOutputSignal++;const bindings:Record<string,string>={},used=new Set<string>();let identifier=0,concreteAny=false,morphAny=false,genericAny=false;for(const input of c.input_names){const build=String(c.build[input]??""),is=stem(input);let best:{p:IrParameter;score:number;concrete:boolean;morph:boolean;generic:boolean}|null=null;for(const p of params){if(p.auth_like||used.has(p.id))continue;const ps=stem(p.name),morph=!!is&&!!ps&&is===ps,exact=input.toLowerCase()===p.name.toLowerCase(),concrete=p.example!==null&&String(p.example).toLowerCase()===build.toLowerCase();const generic=GENERIC.has(is)||GENERIC.has(ps);const sc=(exact?5:0)+(morph?4:0)+(concrete?6:0)+overlap(toks(input),toks(`${p.name} ${p.description}`))*2;if(!best||sc>best.score)best={p,score:sc,concrete,morph,generic}}
if(!best||best.score<4){metrics.alignmentRejectedNoIdentifier++;return {accepted:false,bindings:{},score:0,reason:"no_identifier",signals:{identifier:0,entity,action,output,generic:false,concrete:false,morphology:false}}}identifier++;concreteAny||=best.concrete;morphAny||=best.morph;genericAny||=best.generic;bindings[input]=best.p.id;used.add(best.p.id)}if(identifier)metrics.operationFrameWithIdentifierSignal++;const support=(entity>0?1:0)+(action>0?1:0)+(output>0?1:0);if(genericAny&&support<2){metrics.alignmentRejectedGenericIdentifier++;return {accepted:false,bindings:{},score:identifier*10+entity*3+action*3+output*2,reason:"generic_identifier",signals:{identifier,entity,action,output,generic:true,concrete:concreteAny,morphology:morphAny}}}if(support<1){metrics.alignmentRejectedInsufficientSupport++;return {accepted:false,bindings:{},score:identifier*10,reason:"insufficient_support",signals:{identifier,entity,action,output,generic:genericAny,concrete:concreteAny,morphology:morphAny}}}const score=identifier*10+entity*3+action*3+output*2+(concreteAny?5:0)+(morphAny?3:0);metrics.alignmentAccepted++;if(concreteAny)metrics.alignmentAcceptedByConcreteExample++;if(morphAny)metrics.alignmentAcceptedByMorphology++;metrics.alignmentScoreHistogram[String(Math.min(40,Math.floor(score/5)*5))]=(metrics.alignmentScoreHistogram[String(Math.min(40,Math.floor(score/5)*5))]||0)+1;return {accepted:true,bindings,score,reason:"accepted",signals:{identifier,entity,action,output,generic:genericAny,concrete:concreteAny,morphology:morphAny}}}
