import { mkdir, writeFile } from "node:fs/promises";

const LIST_URL="https://api.apis.guru/v2/list.json";
const MAX_APIS=300,MAX_SPECS=150,MAX_PREFLIGHTS=40,MAX_SECOND_PROBES=15,MAX_ADMITTED=15,SPACING_MS=150;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
type ScalarType="string"|"number"|"integer"|"boolean";
type Contract={api_id:string;provider_key:string;spec_url:string;url:string;export_path:string;export_type:ScalarType;operation_id?:string|null};
function deref(root:any,node:any,seen=new Set<string>()):any{if(!node||typeof node!=="object")return node;if(node.$ref&&typeof node.$ref==="string"&&node.$ref.startsWith("#/")){if(seen.has(node.$ref))return node;seen.add(node.$ref);return deref(root,node.$ref.slice(2).split("/").reduce((x:any,k:string)=>x?.[k.replace(/~1/g,"/").replace(/~0/g,"~")],root),seen);}return node;}
function scalarLeaf(root:any,s:any,prefix="",depth=0):{path:string;type:ScalarType}|null{if(depth>6)return null;const x=deref(root,s);if(!x||typeof x!=="object")return null;const t=x.type;if(["string","number","integer","boolean"].includes(t))return {path:prefix||"$",type:t};if(t==="array"||x.items)return scalarLeaf(root,x.items,prefix?`${prefix}.0`:"0",depth+1);for(const k of Object.keys(x.properties??{}).sort()){const r=scalarLeaf(root,x.properties[k],prefix?`${prefix}.${k}`:k,depth+1);if(r)return r;}if(x.allOf)for(const p of x.allOf){const r=scalarLeaf(root,p,prefix,depth+1);if(r)return r;}return null;}
function pathGet(v:any,path:string){if(path==="$"||path==="")return v;return path.split(".").reduce((x,k)=>x?.[k],v);}
function observedType(v:any){if(Array.isArray(v))return "array";return typeof v;}
function paramValue(root:any,p:any){const x=deref(root,p),s=deref(root,x.schema??{});return x.example??s.example??s.default??(Array.isArray(s.enum)?s.enum[0]:undefined);}
function secured(spec:any,op:any){const sec=op.security!==undefined?op.security:spec.security;return Array.isArray(sec)&&sec.length>0;}
function baseUrl(spec:any){if(Array.isArray(spec.servers)&&spec.servers[0]?.url)return spec.servers[0].url.replace(/\/$/,"");if(spec.swagger==="2.0"){const scheme=(spec.schemes??[]).includes("https")?"https":spec.schemes?.[0];if(!scheme||!spec.host)return null;return `${scheme}://${spec.host}${spec.basePath??""}`.replace(/\/$/,"");}return null;}
function responseSchema(spec:any,op:any){for(const code of Object.keys(op.responses??{}).sort()){if(!/^2\d\d$/.test(code)&&code!=="default")continue;const r=deref(spec,op.responses[code]);if(spec.openapi){const content=r?.content??{};const k=Object.keys(content).find((x:string)=>x.includes("json"));if(k&&content[k]?.schema)return content[k].schema;}if(spec.swagger==="2.0"&&r?.schema)return r.schema;}return null;}
function providerKey(apiId:string){return apiId.split(":")[0].replace(/^www\./,"");}
function buildCandidate(spec:any,apiId:string,specUrl:string,path:string,op:any):Contract|null{if(secured(spec,op))return null;const base=baseUrl(spec);if(!base?.startsWith("https://"))return null;let rendered=path;const q=new URLSearchParams();for(const p0 of [...(spec.paths?.[path]?.parameters??[]),...(op.parameters??[])]){const p=deref(spec,p0);if(!p?.required)continue;const v=paramValue(spec,p);if(v===undefined)return null;if(p.in==="path")rendered=rendered.replace(`{${p.name}}`,encodeURIComponent(String(v)));else if(p.in==="query")q.set(p.name,String(v));else return null;}if(/\{[^}]+\}/.test(rendered))return null;const schema=responseSchema(spec,op),leaf=schema&&scalarLeaf(spec,schema);if(!leaf)return null;let url=`${base}${rendered.startsWith("/")?rendered:`/${rendered}`}`;if([...q.keys()].length)url+=`${url.includes("?")?"&":"?"}${q.toString()}`;try{if(new URL(url).protocol!=="https:")return null;}catch{return null;}return {api_id:apiId,provider_key:providerKey(apiId),spec_url:specUrl,url,export_path:leaf.path,export_type:leaf.type,operation_id:op.operationId??null};}
async function fetchJson(url:string){const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3C/0.1"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function preflight(c:Contract){try{const r=await fetch(c.url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3C/0.1"}});const ct=r.headers.get("content-type")??"";if(!r.ok)return {http_json:false,status:r.status,error:`http_${r.status}`};if(!ct.toLowerCase().includes("json"))return {http_json:false,status:r.status,error:"non_json_content_type"};const body=await r.json();const v=pathGet(body,c.export_path),actual=observedType(v),expected=c.export_type==="integer"?"number":c.export_type;return {http_json:true,schema_match:actual===expected,status:r.status,actual_type:actual,value:v,error:actual===expected?null:`type_or_path_mismatch:${actual}->${expected}`};}catch(e){return {http_json:false,error:String(e)};}}

const list=await fetchJson(LIST_URL);const allIds=Object.keys(list).sort();const stride=Math.max(1,Math.floor(allIds.length/300));const walked:string[]=[];for(let i=0;i<allIds.length&&walked.length<MAX_APIS;i+=stride)walked.push(allIds[i]);
const uniqueProviders:string[]=[];const repeats:string[]=[];const seenProviders=new Set<string>();for(const id of walked){const p=providerKey(id);if(seenProviders.has(p))repeats.push(id);else{seenProviders.add(p);uniqueProviders.push(id);}}const ids=[...uniqueProviders,...repeats].slice(0,MAX_APIS);
const evidence:any={directory_url:LIST_URL,stride,sampling_order:ids.map(id=>({api_id:id,provider_key:providerKey(id)})),inspected:[],admitted:[]};let specCount=0,preflights=0,preflightSuccess=0,schemaMatches=0,secondProbes=0,hostPolicyViolations=0;
for(const apiId of ids){if(specCount>=MAX_SPECS||preflights>=MAX_PREFLIGHTS||evidence.admitted.length>=MAX_ADMITTED)break;const e=list[apiId],v=e?.versions?.[e?.preferred],specUrl=v?.swaggerUrl??v?.swaggerYamlUrl;if(!specUrl){evidence.inspected.push({api_id:apiId,rejected:"no_spec_url"});continue;}let spec:any;try{spec=await fetchJson(specUrl);specCount++;}catch(err){evidence.inspected.push({api_id:apiId,spec_url:specUrl,rejected:`spec_fetch:${String(err)}`});continue;}await sleep(SPACING_MS);let c:Contract|null=null;for(const path of Object.keys(spec.paths??{}).sort()){const op=spec.paths[path]?.get;if(!op)continue;c=buildCandidate(spec,apiId,specUrl,path,op);if(c)break;}if(!c){evidence.inspected.push({api_id:apiId,spec_url:specUrl,rejected:"no_constructed_candidate"});continue;}try{const u=new URL(c.url);if(u.protocol!=="https:"){hostPolicyViolations++;continue;}}catch{hostPolicyViolations++;continue;}const p1=await preflight(c);preflights++;if(p1.http_json)preflightSuccess++;if(p1.http_json&&p1.schema_match)schemaMatches++;await sleep(SPACING_MS);if(!p1.http_json||!p1.schema_match){evidence.inspected.push({api_id:apiId,contract:c,preflight:p1,rejected:!p1.http_json?"preflight_failed":"schema_mismatch"});continue;}if(secondProbes>=MAX_SECOND_PROBES)break;const p2=await preflight(c);secondProbes++;await sleep(SPACING_MS);if(!p2.http_json||!p2.schema_match){evidence.inspected.push({api_id:apiId,contract:c,preflight:p1,second_probe:p2,rejected:"second_probe_failed"});continue;}const admitted={...c,preflight:p1,second_probe:p2};evidence.admitted.push(admitted);evidence.inspected.push({api_id:apiId,contract:c,preflight:p1,second_probe:p2,admitted:true});}
const distinctProviders=new Set(evidence.admitted.map((x:any)=>x.provider_key)).size;const preflightRate=preflights?preflightSuccess/preflights:0;const schemaRate=preflightSuccess?schemaMatches/preflightSuccess:0;const criteria={five_contracts_admitted:evidence.admitted.length>=5,five_distinct_root_providers:distinctProviders>=5,preflight_http_json_success_rate:preflightRate>=0.5,schema_export_match_rate:schemaRate>=0.7,second_probe_validation_rate:evidence.admitted.length>0&&evidence.admitted.every((x:any)=>x.second_probe?.http_json&&x.second_probe?.schema_match),no_declared_security_on_admitted:true,host_policy_violations_zero:hostPolicyViolations===0,evidence_persisted:true};const decision=Object.values(criteria).every(Boolean)?"GO_STRATIFIED_PRIMITIVE_DISCOVERY":"REASSESS_STRATIFIED_PRIMITIVE_DISCOVERY";const summary={experiment:"MISSING Experiment 3C — Stratified Primitive Discovery",created_at:new Date().toISOString(),metrics:{directory_ids:allIds.length,stride,apis_sampled:ids.length,specs_fetched:specCount,preflights,preflight_http_json_successes:preflightSuccess,preflight_http_json_success_rate:preflightRate,schema_matches:schemaMatches,schema_export_match_rate:schemaRate,second_probes:secondProbes,admitted_contracts:evidence.admitted.length,distinct_root_providers:distinctProviders,host_policy_violations:hostPolicyViolations},criteria,decision,admitted:evidence.admitted};await mkdir("results/experiment-3c",{recursive:true});await writeFile("results/experiment-3c/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3c/evidence.json",JSON.stringify(evidence,null,2)+"\n");console.log(JSON.stringify(summary,null,2));
