import {createHash} from "node:crypto";
import {isIP} from "node:net";
import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {ProjectionPlan} from "./experiment4arCore.js";

export const FOUR_AR6_BASE_SHA="a5beb7049dcceadcd7e40b6190fa453ba22e4f79";
export const FOUR_AR6_FROZEN_RUN=33033653560;
export const FOUR_AR6_FROZEN_ARTIFACT=9631986496;
export const FOUR_AR6_FROZEN_DIGEST="sha256:30edd3ba75e1aa384d4193a13d4e52843da0af1d5dcecd8a4b229a2efbbafac0";
export const FOUR_AR6_FROZEN_REPORT_FP="66c775d9532df7a10521a0d2a2bea3c19c192be4c52401f3b774e39c1e673105";
export const FOUR_AR6_FROZEN_LEDGER_FP="cbdcf9b7a51feff4d00b2d7ff1fa48b2dcb4396b2afee8e0303e4e6ac6aa049e";
export const FOUR_AR6_MAX_OPERATIONS=24;
export const fourAr6Sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");

type Param={name:string;in:"path"|"query";required:boolean;literals:string[]};
export type DocumentedOperation={operation_id:string;origin:string;base_path:string;operation_path:string;full_path:string;method:"GET";path_parameters:Param[];query_parameters:Param[];response_paths:string[];evidence_ids:string[];source_urls:string[];proof_type:"openapi"|"url_example";score:number};
export type R6Selection={decision:"COMPILE"|"REJECT";operation_index:number;path_bindings:{parameter_index:number;input_name:string}[];query_bindings:{parameter_index:number;source_kind:"INPUT"|"LITERAL"|"OMIT";input_name:string|null;literal_index:number|null}[];output_mappings:{output_name:string;source_kind:"FIELD"|"INPUT";response_path_index:number|null;input_name:string|null}[];reason:string};

function refResolve(spec:any,node:any){if(node&&typeof node==="object"&&typeof node.$ref==="string"&&node.$ref.startsWith("#/")){let cur=spec;for(const p of node.$ref.slice(2).split("/"))cur=cur?.[p.replace(/~1/g,"/").replace(/~0/g,"~")];return cur??node;}return node;}
function schemaPaths(spec:any,schema:any,prefix="",depth=0,seen=new Set<any>()):string[]{schema=refResolve(spec,schema);if(!schema||typeof schema!=="object"||depth>6||seen.has(schema))return [];seen.add(schema);const out:string[]=[];if(schema.properties&&typeof schema.properties==="object")for(const [k,v] of Object.entries(schema.properties)){const p=prefix?`${prefix}.${k}`:k;out.push(p);out.push(...schemaPaths(spec,v,p,depth+1,new Set(seen)));}if(schema.items)out.push(...schemaPaths(spec,schema.items,prefix?`${prefix}.0`:"0",depth+1,new Set(seen)));for(const k of ["allOf","oneOf","anyOf"])if(Array.isArray(schema[k]))for(const x of schema[k])out.push(...schemaPaths(spec,x,prefix,depth+1,new Set(seen)));return [...new Set(out)];}
function responsePaths(spec:any,responses:any){const out:string[]=[];for(const [code,r0] of Object.entries(responses||{})){if(!/^2\d\d$/.test(code)&&code!=="default")continue;const r=refResolve(spec,r0);for(const media of Object.values(r?.content||{}) as any[])out.push(...schemaPaths(spec,media?.schema));if(r?.schema)out.push(...schemaPaths(spec,r.schema));}return [...new Set(out)].slice(0,200);}
function literalsFrom(p:any){const vals:any[]=[];const s=refResolve({},p?.schema)||p?.schema||{};for(const v of [...(Array.isArray(s?.enum)?s.enum:[]),p?.example,p?.default,s?.example,s?.default])if(v!==undefined&&v!==null&&["string","number","boolean"].includes(typeof v))vals.push(String(v));if(p?.examples&&typeof p.examples==="object")for(const x of Object.values(p.examples) as any[]){const v=x?.value??x;if(v!==undefined&&v!==null&&["string","number","boolean"].includes(typeof v))vals.push(String(v));}return [...new Set(vals)].slice(0,16);}
function normalizedBasePath(path:string){const p=String(path||"").trim();if(!p||p==="/")return "";const x=(p.startsWith("/")?p:`/${p}`).replace(/\/+$/g,"");return x==="/"?"":x;}
function normalizedOperationPath(path:string){let p=String(path||"").trim().replace(/%7B/gi,"{").replace(/%7D/gi,"}").replace(/<([A-Za-z_][A-Za-z0-9_-]*)>/g,"{$1}").replace(/:([A-Za-z_][A-Za-z0-9_-]*)(?=\/|$)/g,"{$1}");if(!p.startsWith("/"))p=`/${p}`;return p.replace(/\/{2,}/g,"/");}
function combine(base:string,op:string){return `${normalizedBasePath(base)}${normalizedOperationPath(op)}`.replace(/\/{2,}/g,"/")||"/";}
function staticServers(spec:any,resolvedUrl:string){const out:{origin:string;base_path:string}[]=[];const add=(raw:string)=>{try{if(raw.includes("{"))return;const u=new URL(raw,resolvedUrl);if(u.protocol!=="https:"||u.username||u.password||isIP(u.hostname)||u.search||u.hash)return;out.push({origin:u.origin,base_path:normalizedBasePath(u.pathname)});}catch{}};for(const s of spec?.servers||[])if(typeof s?.url==="string")add(s.url);if(spec?.host){const schemes=Array.isArray(spec.schemes)?spec.schemes:["https"];if(schemes.includes("https"))add(`https://${spec.host}${spec.basePath||""}`);}if(!out.length)try{const u=new URL(resolvedUrl);if(u.protocol==="https:"&&!isIP(u.hostname))out.push({origin:u.origin,base_path:""});}catch{}return [...new Map(out.map(x=>[`${x.origin}${x.base_path}`,x])).values()];}
function parameterRows(spec:any,item:any,op:any):Param[]{return [...(item?.parameters||[]),...(op?.parameters||[])].map((x:any)=>refResolve(spec,x)).filter((p:any)=>p&&["path","query"].includes(p.in)&&typeof p.name==="string").map((p:any)=>({name:p.name,in:p.in,required:p.in==="path"||Boolean(p.required),literals:literalsFrom(p)}));}
export function specSummaryR6(spec:any,caseId:string,resolvedUrl:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId),servers=staticServers(spec,resolvedUrl),ops:any[]=[];for(const [path,item] of Object.entries(spec?.paths||{}) as any[]){const op=item?.get;if(!op)continue;const parameters=parameterRows(spec,item,op),response_paths=responsePaths(spec,op.responses||{});const hay=`${path} ${op.operationId||""} ${op.summary||""} ${op.description||""} ${parameters.map(p=>p.name).join(" ")} ${response_paths.join(" ")}`.toLowerCase();let relevance=0;for(const i of c?.input_names||[])if(hay.includes(i.toLowerCase()))relevance+=8;for(const r of c?.required||[])if(hay.includes(r.toLowerCase()))relevance+=10;if(/search|lookup|decode|detail|metadata/.test(hay))relevance+=2;ops.push({method:"GET",path:normalizedOperationPath(path),operation_id:op.operationId||null,summary:op.summary||null,parameters,response_paths,relevance});}ops.sort((a,b)=>b.relevance-a.relevance||a.path.localeCompare(b.path));return `R6_VERIFIED_API_SPEC\n${JSON.stringify({servers,operation_count:ops.length,response_property_count:[...new Set(ops.flatMap(x=>x.response_paths))].length,operations:ops.slice(0,80)},null,2)}`;}

function decodeText(s:string){return s.replace(/&quot;|&#34;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function jsonPaths(v:any,prefix="",depth=0):string[]{if(depth>6||v===null||v===undefined)return [];const out:string[]=[];if(Array.isArray(v)){if(v.length){const p=prefix?`${prefix}.0`:"0";out.push(p,...jsonPaths(v[0],p,depth+1));}}else if(typeof v==="object")for(const [k,x] of Object.entries(v)){const p=prefix?`${prefix}.${k}`:k;out.push(p,...jsonPaths(x,p,depth+1));}return [...new Set(out)];}
function exampleJsonPaths(text:string){const decoded=decodeText(text),out:string[]=[];const blocks=[...decoded.matchAll(/```(?:json)?\s*([\s\S]*?)```/gi),...decoded.matchAll(/<pre[^>]*>([\s\S]*?)<\/pre>/gi)];for(const m of blocks){const raw=m[1].replace(/<[^>]+>/g,"").trim();try{out.push(...jsonPaths(JSON.parse(raw)));}catch{}}return [...new Set(out)].slice(0,160);}
function caseScore(caseId:string,op:{operation_path:string;path_parameters:Param[];query_parameters:Param[];response_paths:string[]}){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return 0;const hay=`${op.operation_path} ${op.path_parameters.map(x=>x.name).join(" ")} ${op.query_parameters.map(x=>x.name).join(" ")} ${op.response_paths.join(" ")}`.toLowerCase();let s=0;for(const i of c.input_names)if(hay.includes(i.toLowerCase())||i.split("_").some(t=>t.length>2&&hay.includes(t)))s+=8;for(const r of c.required)if(hay.includes(r.toLowerCase()))s+=10;return s;}
function parseSummary(e:DocEvidence):DocumentedOperation[]{if(!e.text.startsWith("R6_VERIFIED_API_SPEC"))return [];let s:any;try{s=JSON.parse(e.text.slice(e.text.indexOf("\n")+1));}catch{return [];}const out:DocumentedOperation[]=[];for(const server of s.servers||[])for(const op of s.operations||[]){if(op.method!=="GET")continue;const params=(op.parameters||[]) as Param[],base_path=normalizedBasePath(server.base_path||""),operation_path=normalizedOperationPath(op.path),full_path=combine(base_path,operation_path),base={origin:server.origin,base_path,operation_path,full_path,method:"GET" as const,path_parameters:params.filter(x=>x.in==="path"),query_parameters:params.filter(x=>x.in==="query"),response_paths:[...new Set((op.response_paths||[]).map(String))],evidence_ids:[e.evidence_id],source_urls:[e.resolved_url],proof_type:"openapi" as const,score:0};if(!/^https:\/\//.test(base.origin))continue;base.score=caseScore((e as any).case_id||"",base);base.operation_id=`op_${fourAr6Sha({origin:base.origin,full_path,params,response_paths:base.response_paths,e:e.evidence_id}).slice(0,16)}`;out.push(base);}return out;}
function absExamples(e:DocEvidence,caseId:string){const text=decodeText(e.text),out:DocumentedOperation[]=[];const re=/https:\/\/[A-Za-z0-9.-]+(?::\d+)?[^\s"'`\])}]*/g;let m:RegExpExecArray|null;while((m=re.exec(text))){let raw=m[0].replace(/[.,;:]+$/g,"");try{const marker=raw.indexOf("?");const noQuery=marker>=0?raw.slice(0,marker):raw,query=marker>=0?raw.slice(marker+1):"",u=new URL(noQuery.replace(/<([A-Za-z_][A-Za-z0-9_-]*)>/g,"{$1}"));if(u.protocol!=="https:"||u.username||u.password||isIP(u.hostname))continue;const operation_path=normalizedOperationPath(decodeURIComponent(u.pathname)),pathNames=[...(operation_path.matchAll(/\{([^}]+)\}/g))].map(x=>x[1]),qs=new URLSearchParams(query),q:Param[]=[];for(const name of new Set([...qs.keys()]))q.push({name,in:"query",required:false,literals:[...new Set(qs.getAll(name))].slice(0,8)});const window=text.slice(Math.max(0,m.index-2400),Math.min(text.length,m.index+raw.length+3200)),response_paths=exampleJsonPaths(window),base={origin:u.origin,base_path:"",operation_path,full_path:operation_path,method:"GET" as const,path_parameters:pathNames.map(name=>({name,in:"path" as const,required:true,literals:[]})),query_parameters:q,response_paths,evidence_ids:[e.evidence_id],source_urls:[e.resolved_url],proof_type:"url_example" as const,score:0};base.score=caseScore(caseId,base);base.operation_id=`op_${fourAr6Sha({origin:base.origin,path:base.full_path,p:base.path_parameters,q:base.query_parameters,e:e.evidence_id}).slice(0,16)}`;out.push(base);}catch{}}return out;}
function summaryOps(e:DocEvidence,caseId:string){const rows=parseSummary(e);for(const r of rows)r.score=caseScore(caseId,r);return rows;}
export function extractDocumentedOperationsR6(evidence:DocEvidence[],caseId:string){const all:DocumentedOperation[]=[];for(const e of evidence.filter(x=>x.state==="ok")){all.push(...summaryOps(e,caseId),...absExamples(e,caseId));}const by=new Map<string,DocumentedOperation>();for(const op of all){const key=fourAr6Sha({origin:op.origin,path:op.full_path,p:op.path_parameters.map(x=>[x.name,x.in,x.required]),q:op.query_parameters.map(x=>[x.name,x.in,x.required]),r:op.response_paths});const prev=by.get(key);if(!prev)by.set(key,op);else{prev.evidence_ids=[...new Set([...prev.evidence_ids,...op.evidence_ids])];prev.source_urls=[...new Set([...prev.source_urls,...op.source_urls])];prev.score=Math.max(prev.score,op.score);}}const rows=[...by.values()].sort((a,b)=>b.score-a.score||(a.proof_type==="openapi"?-1:1)-(b.proof_type==="openapi"?-1:1)||a.origin.localeCompare(b.origin)||a.full_path.localeCompare(b.full_path));return rows.slice(0,FOUR_AR6_MAX_OPERATIONS).map((x,i)=>({...x,operation_id:`r6o${String(i).padStart(2,"0")}_${fourAr6Sha({origin:x.origin,path:x.full_path,e:x.evidence_ids}).slice(0,10)}`}));}
export function operationPacketFingerprintR6(ops:DocumentedOperation[]){return fourAr6Sha(ops.map(x=>({operation_id:x.operation_id,origin:x.origin,base_path:x.base_path,operation_path:x.operation_path,full_path:x.full_path,path_parameters:x.path_parameters,query_parameters:x.query_parameters,response_paths:x.response_paths,evidence_ids:x.evidence_ids,proof_type:x.proof_type,score:x.score})));}

export function materializeSelectionR6(caseId:string,providerId:string,ops:DocumentedOperation[],sel:R6Selection){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)throw new Error("r6_unknown_case");if(sel.decision!=="COMPILE")return {raw:{case_id:caseId,provider_candidate_id:providerId,decision:"REJECT",reason:sel.reason},operation:null,proof:null};const op=ops[sel.operation_index];if(!op)throw new Error("r6_operation_index_invalid");const pb:Record<string,string>={},qb:Record<string,string>={};for(const b of sel.path_bindings){const p=op.path_parameters[b.parameter_index];if(!p)throw new Error("r6_path_parameter_index_invalid");if(!c.input_names.includes(b.input_name))throw new Error("r6_path_input_invalid");if(pb[p.name])throw new Error("r6_duplicate_path_binding");pb[p.name]=`$input.${b.input_name}`;}for(const p of op.path_parameters)if(!(p.name in pb))throw new Error(`r6_unbound_path:${p.name}`);for(const b of sel.query_bindings){const p=op.query_parameters[b.parameter_index];if(!p)throw new Error("r6_query_parameter_index_invalid");if(b.source_kind==="OMIT"){if(p.required)throw new Error(`r6_required_query_omitted:${p.name}`);continue;}if(qb[p.name]!==undefined)throw new Error("r6_duplicate_query_binding");if(b.source_kind==="INPUT"){if(!b.input_name||!c.input_names.includes(b.input_name))throw new Error("r6_query_input_invalid");qb[p.name]=`$input.${b.input_name}`;}else{const lit=b.literal_index===null?undefined:p.literals[b.literal_index];if(lit===undefined)throw new Error("r6_query_literal_index_invalid");qb[p.name]=lit;}}for(const p of op.query_parameters)if(p.required&&qb[p.name]===undefined)throw new Error(`r6_required_query_unbound:${p.name}`);const projection:ProjectionPlan={};const seen=new Set<string>();for(const m of sel.output_mappings){if(!c.required.includes(m.output_name)||seen.has(m.output_name))throw new Error("r6_output_name_invalid");seen.add(m.output_name);if(m.source_kind==="INPUT"){if(!m.input_name||!c.input_names.includes(m.input_name))throw new Error("r6_output_input_invalid");projection[m.output_name]={op:"INPUT",name:m.input_name} as any;}else{const path=m.response_path_index===null?undefined:op.response_paths[m.response_path_index];if(!path)throw new Error("r6_response_path_index_invalid");projection[m.output_name]={op:"FIELD",path} as any;}}for(const r of c.required)if(!seen.has(r))throw new Error(`r6_missing_output:${r}`);const raw:any={case_id:caseId,provider_candidate_id:providerId,decision:"COMPILE",method:"GET",base_url:op.origin,path_template:op.full_path,path_bindings:pb,query_bindings:qb,evidence_ids:op.evidence_ids,reason:`R6_OPERATION:${op.operation_id}`,projection};return {raw,operation:op,proof:{operation_id:op.operation_id,proof_type:op.proof_type,evidence_ids:op.evidence_ids,source_urls:op.source_urls,input_mapping:{path:pb,query:qb},output_mapping:projection}};}
export function contractFromR6Raw(raw:any):MicroContract{return {case_id:raw.case_id,provider_candidate_id:raw.provider_candidate_id,decision:raw.decision,method:raw.method,base_url:raw.base_url,path_template:raw.path_template,path_bindings:raw.path_bindings,query_bindings:raw.query_bindings,evidence_ids:raw.evidence_ids,reason:raw.reason};}
