import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {validate4u,compile4u,project4u,validateProjected4u,scope4u} from "./experiment4uContract.js";
import {verifyResponseRoleWitness5B} from "./experiment5bResponse.js";
import {outputInputCompatibility5B2,verifySemanticIdentityWitness5B2} from "./experiment5b2Semantics.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(c=>[c.case_id,c]));
function proxy(ledger:RecoveryLedger,allowed:Set<string>){return {record:(layer:any,kind:string,accepted:boolean,detail?:any)=>{if(kind==="ungrounded_projection_fields"&&accepted===false&&detail&&typeof detail==="object"&&allowed.has(`${String(detail.output||"")}:${String(detail.path||"")}`))return;ledger.record(layer,kind,accepted,detail)}} as RecoveryLedger}
export function validate5b2(raw:any,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger,probeProof:P1ProbeProof|null){const c=BY_ID[provider.case_id],base={semanticIdentityWitnessValidationSuccesses5b2:0,semanticIdentityWitnessMutationRejects5b2:0,projectionInputCompatibilityValidationSuccesses5b2:0,projectionInputCompatibilityRejects5b2:0,responseGroundedWitnessValidationSuccesses5b2:0,responseGroundedWitnessMutationRejects5b2:0};if(raw?.decision!=="COMPILE")return {...validate4u(raw,provider,evidence,ledger,probeProof),...base};if(!c||!probeProof)return {errors:["5b2_missing_case_or_probe"],contract:null as any,projection:null as any,probe_proof:null,...base};for(const [output,e] of Object.entries<any>(raw?.projection||{})){if(e?.op==="INPUT"&&!outputInputCompatibility5B2(output,String(e.name||"")).ok){ledger.record("guard","ungrounded_projection_fields",false,{reason:"5b2_projection_input_role_incompatible",output,input:e.name});return {errors:[`5b2_projection_input_role_incompatible:${output}:${e.name}`],contract:null as any,projection:null as any,probe_proof:null,...base,projectionInputCompatibilityRejects5b2:1}}}const semantic=raw?.semantic_identity_witness_5b2;if(!semantic||!verifySemanticIdentityWitness5B2(semantic,{inputNames:c.input_names,input:c.build,projection:raw.projection,proof:probeProof})){ledger.record("guard","ungrounded_projection_fields",false,{reason:"5b2_semantic_identity_witness_invalid"});return {errors:["5b2_semantic_identity_witness_invalid"],contract:null as any,projection:null as any,probe_proof:null,...base,semanticIdentityWitnessMutationRejects5b2:1}}const response=raw?.response_role_witness_5b,allowed=new Set<string>();if(response){if(!verifyResponseRoleWitness5B(response,probeProof)){ledger.record("guard","ungrounded_projection_fields",false,{reason:"5b2_response_role_witness_invalid"});return {errors:["5b2_response_role_witness_invalid"],contract:null as any,projection:null as any,probe_proof:null,...base,responseGroundedWitnessMutationRejects5b2:1}}for(const m of response.mappings||[])allowed.add(`${m.output_role}:${m.observed_path}`)}const checked:any=validate4u(raw,provider,evidence,allowed.size?proxy(ledger,allowed):ledger,probeProof);let bypass=0;const errors=(checked.errors||[]).filter((e:string)=>{const m=/^4u_ungrounded_output:([^:]+):(.+)$/.exec(e),ok=!!(m&&allowed.has(`${m[1]}:${m[2]}`));if(ok)bypass++;return !ok});return {...checked,errors,projection:errors.length?null:(raw.projection as ProjectionPlan),probe_proof:errors.length?null:probeProof,semanticGroundingValidatorRejects:Math.max(0,Number(checked.semanticGroundingValidatorRejects||0)-bypass),...base,semanticIdentityWitnessValidationSuccesses5b2:errors.length?0:1,projectionInputCompatibilityValidationSuccesses5b2:errors.length?0:1,responseGroundedWitnessValidationSuccesses5b2:response&&!errors.length?1:0}}
export function compile5b2(contract:MicroContract,input:Record<string,unknown>){return compile4u(contract,input)}
export function project5b2(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return project4u(plan,body,input)}
export function validateProjected5b2(caseId:string,input:Record<string,any>,out:Record<string,any>){return validateProjected4u(caseId,input,out)}
export function scope5b2(start:string,target:string){return scope4u(start,target)}
