import {lexicalTokensP1} from "./experiment4ap1Request.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {sha4u,resolveLocalRef4U,type RefMetrics4U} from "./experiment4uOpenApi.js";

const toks=(v:any)=>new Set(lexicalTokensP1(String(v||"")).map(x=>x.toLowerCase()));
const overlap=(a:any,b:any)=>{const x=toks(a),y=toks(b);let n=0;for(const t of x)if(y.has(t))n++;return n};
function emptyMetrics():RefMetrics4U{return {operationLocalRefsResolved4u:0,operationLocalRefsRejected4u:0,operationExternalRefsRejected4u:0,operationExternalRefFetches4u:0,operationRefCyclesRejected4u:0,unrelatedRefFailuresIsolated4u:0}}
function successfulSchema(root:any,op:any){const entries=Object.entries(op?.responses||{}).filter(([k])=>/^2\d\d$/.test(k)).sort(([a],[b])=>a.localeCompare(b));for(const [,respRaw] of entries){let resp:any=respRaw;try{resp=resolveLocalRef4U(root,resp,emptyMetrics())}catch{}const content=resp?.content||{};for(const ct of Object.keys(content).sort()){let schema=content[ct]?.schema;if(!schema)continue;try{schema=resolveLocalRef4U(root,schema,emptyMetrics())}catch{}return {schema,responseDescription:String(resp?.description||""),contentType:ct}}}return null}
function flatten(root:any,node:any,path:string[],enclosing:string,responseDescription:string,out:any[],depth=0){if(depth>8||!node||typeof node!=="object")return;try{node=resolveLocalRef4U(root,node,emptyMetrics())}catch{return}if(node.type==="array"&&node.items){flatten(root,node.items,path,enclosing,responseDescription,out,depth+1);return}const props=node.properties&&typeof node.properties==="object"?node.properties:null;if(!props)return;for(const [name,raw] of Object.entries(props)){let p:any=raw;try{p=resolveLocalRef4U(root,p,emptyMetrics())}catch{}const pth=[...path,name];out.push({schema_path:pth.join("."),property_name:name,property_title:String(p?.title||""),property_description:String(p?.description||""),bounded_documented_examples:[p?.example,...(Array.isArray(p?.examples)?p.examples:[])].filter(v=>v!==undefined).slice(0,3).map(String),enclosing_schema_name:String(node?.title||enclosing||""),response_description:responseDescription});if(p?.properties||p?.items)flatten(root,p,pth,String(p?.title||name),responseDescription,out,depth+1)}}
export function schemaDescriptors4V(root:any,op:any){const s=successfulSchema(root,op);if(!s)return [];const out:any[]=[];flatten(root,s.schema,[],String(s.schema?.title||""),s.responseDescription,out);return out}
export function createSchemaRoleWitness4V(args:{root:any;op:any;proof:P1ProbeProof;unresolved:readonly string[];specFingerprint:string;operationPointer:string}){const descriptors=schemaDescriptors4V(args.root,args.op),mappings:any[]=[];let candidates=0,rejectedAmbiguous=0,rejectedUndocumented=0;for(const output of args.unresolved){const ranked=descriptors.map(d=>{const local=`${d.property_name} ${d.property_title} ${d.property_description} ${d.enclosing_schema_name} ${d.response_description}`;const score=overlap(output,local)*100;const fields=args.proof.record.observed_fields.filter(f=>f.leaf===d.property_name||f.path.endsWith(`.${d.property_name}`)||f.path===d.property_name);return {d,score,fields}}).filter(x=>x.score>0&&x.fields.length===1).sort((a,b)=>b.score-a.score||a.d.schema_path.localeCompare(b.d.schema_path));candidates+=ranked.length;if(!ranked.length){rejectedUndocumented++;continue}if(ranked.length>1&&ranked[0].score===ranked[1].score){rejectedAmbiguous++;continue}const top=ranked[0];mappings.push({output_role:output,schema_path:top.d.schema_path,observed_path:top.fields[0].path,confidence:Math.min(1,top.score/200),evidence_fields:[top.d.property_name,top.d.property_title,top.d.property_description].filter(Boolean)})}const responseSchemaFingerprint=sha4u(args.op?.responses||{}),semanticEvidenceFingerprint=sha4u(descriptors),classifierOutputFingerprint=sha4u(mappings);return {witness:{spec_fingerprint:args.specFingerprint,operation_pointer:args.operationPointer,response_schema_fingerprint:responseSchemaFingerprint,mappings,semantic_evidence_fingerprint:semanticEvidenceFingerprint,classifier_output_fingerprint:classifierOutputFingerprint},metrics:{schemaRoleWitnessCalls4v:0,schemaRoleWitnessCandidates4v:candidates,schemaRoleWitnessAccepted4v:mappings.length,schemaRoleWitnessRejectedAmbiguous4v:rejectedAmbiguous,schemaRoleWitnessRejectedUndocumented4v:rejectedUndocumented}}}
export function verifySchemaRoleWitness4V(w:any,proof:P1ProbeProof){if(!w||!Array.isArray(w.mappings)||w.classifier_output_fingerprint!==sha4u(w.mappings))return false;const paths=new Set(proof.record.observed_fields.map(f=>f.path));return w.mappings.every((m:any)=>typeof m.output_role==="string"&&typeof m.schema_path==="string"&&typeof m.observed_path==="string"&&paths.has(m.observed_path))}
export function applySchemaWitnessProjection4V(projection:any,w:any){const out={...projection};for(const m of w?.mappings||[])if(!out[m.output_role])out[m.output_role]={op:"FIELD",path:m.observed_path};return out}
