import {deriveExperiment5bSource} from "./experiment5bDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b2_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b2Source(source:string){let x=deriveExperiment5bSource(source);
x=r(x,'import {compile5b as compile4ar,project5b as project4ar,scope5b as scope4ar,validate5b as validate4ar,validateProjected5b as validateProjected4ar} from "./experiment5bContract.js";','import {compile5b2 as compile4ar,project5b2 as project4ar,scope5b2 as scope4ar,validate5b2 as validate4ar,validateProjected5b2 as validateProjected4ar} from "./experiment5b2Contract.js";');
x=r(x,'import {synthesize5b as synthesize4ar} from "./experiment5bPlanner.js";','import {synthesize5b2 as synthesize4ar} from "./experiment5b2Planner.js";');
x=r(x,'import {verifyEntityCouplingReplay5B,verifyResponseRoleReplay5B} from "./experiment5bResponse.js";','import {verifyResponseRoleReplay5B} from "./experiment5bResponse.js";\nimport {verifySemanticIdentityReplay5B2} from "./experiment5b2Semantics.js";');
x=r(x,'const OUT="results/experiment-5b-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b2-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'response_role_witness_5b:a.parsed_json?.response_role_witness_5b??null,entity_coupling_witness_5b:a.parsed_json?.entity_coupling_witness_5b??null,request_first_5b:String(a.parsed_json?.reason||"").startsWith("5B_REQUEST_FIRST_")};','response_role_witness_5b:a.parsed_json?.response_role_witness_5b??null,semantic_identity_witness_5b2:a.parsed_json?.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:a.parsed_json?.input_output_compatibility_fingerprint_5b2??null,cross_graph_rank_5b2:a.parsed_json?.cross_graph_rank_5b2??null,cross_graph_recovered_5b2:a.parsed_json?.cross_graph_recovered_5b2===true};');
x=r(x,'response_role_witness_5b:syn.response_role_witness_5b??null,entity_coupling_witness_5b:syn.entity_coupling_witness_5b??null,request_first_5b:syn.request_first_5b===true,contract,contract_fingerprint:sha3yr(contract)','response_role_witness_5b:syn.response_role_witness_5b??null,semantic_identity_witness_5b2:syn.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:syn.input_output_compatibility_fingerprint_5b2??null,cross_graph_rank_5b2:syn.cross_graph_rank_5b2??null,cross_graph_recovered_5b2:syn.cross_graph_recovered_5b2===true,contract,contract_fingerprint:sha3yr(contract)');
x=r(x,'if(recipe.response_role_witness_5b&&!verifyResponseRoleReplay5B(recipe.response_role_witness_5b,got.body))throw new Error("5b_replay_response_role_witness_path_missing");if(!recipe.entity_coupling_witness_5b||!verifyEntityCouplingReplay5B(recipe.entity_coupling_witness_5b,c.input_names,c.replay,got.body))throw new Error("5b_replay_entity_coupling_failed");const out=project4ar(recipe.projection,got.body,c.replay);','if(recipe.response_role_witness_5b&&!verifyResponseRoleReplay5B(recipe.response_role_witness_5b,got.body))throw new Error("5b2_replay_response_role_witness_path_missing");if(!recipe.semantic_identity_witness_5b2||!verifySemanticIdentityReplay5B2(recipe.semantic_identity_witness_5b2,c.input_names,c.replay,got.body))throw new Error("5b2_replay_semantic_identity_failed");const out=project4ar(recipe.projection,got.body,c.replay);');
x=x.replaceAll('experiment:"5B-ENGINE"','experiment:"5B2-ENGINE"').replaceAll('purpose:"development_request_first_response_grounded_entity_coupled_engine"','purpose:"development_semantic_identity_witness_cross_graph_beam_engine"').replaceAll('base_sha:"03d0ec9fcf50b3ba72f98b99130c301044383a56"','base_sha:"8648ab3a97b98aaa61ec4feec7752f01423b36c4"');
x=x.replaceAll('./experiment5bPlanner.ts','./experiment5b2Planner.ts').replaceAll('./experiment5bContract.ts','./experiment5b2Contract.ts').replaceAll('./experiment5bDerivation.ts','./experiment5b2Derivation.ts');
x=x.replace('(await readFile(new URL("./experiment5bResponse.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5bResponse.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b2Semantics.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
