import {deriveExperiment4ap1Source} from "./experiment4ap1Derivation.js";

function replaceOnce(source:string,from:string,to:string){if(!source.includes(from))throw new Error(`4b_derivation_anchor_missing:${from.slice(0,160)}`);return source.replace(from,to);}

const B_SYNTH=`async function synthesize(config:any,p:Provider4A,docs:DocEvidence[],ledger:RecoveryLedger,evidence:any[]){synthesisCalls++;const a=await synthesize4ar(config,p,docs,ledger);schemaProbeCalls+=a.schemaProbeCalls||0;schemaProbe2xxJson+=a.schemaProbe2xxJson||0;schemaProbeRejected+=a.schemaProbeRejected||0;schemaProbeBytes+=a.schemaProbeBytes||0;const gm=a.request_graph_metrics||{};requestGraphNodes+=gm.requestGraphNodes||0;requestGraphEdges+=gm.requestGraphEdges||0;provenApiOrigins+=gm.provenApiOrigins||0;provenRequestTemplates+=gm.provenRequestTemplates||0;unboundRelativePaths+=gm.unboundRelativePaths||0;crossSourceJoinRejects+=gm.crossSourceJoinRejects||0;documentationOriginFallbacks+=gm.documentationOriginFallbacks||0;if((a.request_inventory_count||0)===0)requestInventoryZeroAttempts++;else requestInventoryNonZeroAttempts++;const v=a.parsed_json?validate4ar(a.parsed_json,p,docs,ledger,a.probe_proof??null):{errors:[a.parse_error||\`planner_http_\${a.http_status}\`],contract:null,projection:null,probe_proof:null};recordUsage("synthesis",p.case_id,p.candidate_id,a.usage,a.latency_ms);evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...a,static_errors:v.errors,validated_active_schema_proof:v.probe_proof?{hypothesis_id:v.probe_proof.hypothesis.id,probe_schema_fingerprint:v.probe_proof.record.schema_fingerprint,probe_body_fingerprint:v.probe_proof.record.response_body_fingerprint}:null});if(a.parsed_json?.decision==="REJECT"&&!v.errors.length)return {contract:a.parsed_json,projection:null,error:null,probe_proof:null};if(v.errors.length)return {contract:null,projection:null,error:v.errors.join(",")||a.parse_error||null,probe_proof:null};if(v.contract?.decision==="COMPILE"&&v.projection&&v.probe_proof)probeDerivedContracts++;return {contract:v.contract,projection:v.projection,error:null,probe_proof:v.probe_proof};}\n`;

export function deriveExperiment4bSource(source:string){
  let result=deriveExperiment4ap1Source(source);
  result=replaceOnce(result,'import {synthesize4ap1 as synthesize4ar} from "./experiment4ap1Planner.js";','import {synthesize4b as synthesize4ar} from "./experiment4bPlanner.js";');
  result=replaceOnce(result,'const OUT="results/experiment-4ap1",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4b",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
  result=replaceOnce(result,'let catalogFetches=0,rerankerCalls=0,docFetches=0,synthesisCalls=0,synthesisRepairs=0,liveCalls=0,specProbeFetches=0,schemaProbeCalls=0,schemaProbe2xxJson=0,schemaProbeRejected=0,schemaProbeBytes=0,probeDerivedContracts=0,probeConfirmedContracts=0;','let catalogFetches=0,rerankerCalls=0,docFetches=0,synthesisCalls=0,synthesisRepairs=0,liveCalls=0,specProbeFetches=0,schemaProbeCalls=0,schemaProbe2xxJson=0,schemaProbeRejected=0,schemaProbeBytes=0,probeDerivedContracts=0,probeConfirmedContracts=0,requestGraphNodes=0,requestGraphEdges=0,provenApiOrigins=0,provenRequestTemplates=0,unboundRelativePaths=0,crossSourceJoinRejects=0,documentationOriginFallbacks=0,requestInventoryZeroAttempts=0,requestInventoryNonZeroAttempts=0;');
  const synthStart=result.indexOf('async function synthesize('),synthEnd=result.indexOf('function sameRequired',synthStart);if(synthStart<0||synthEnd<0)throw new Error("4b_synthesize_section_missing");result=result.slice(0,synthStart)+B_SYNTH+result.slice(synthEnd);
  const auditStart=result.indexOf('coreSource='),auditEnd=result.indexOf(',families=new Set',auditStart);if(auditStart<0||auditEnd<0)throw new Error("4b_source_audit_section_missing");
  const audit='coreSource=(await readFile(new URL("./experiment4ap1Core.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4bDerivation.ts",import.meta.url),"utf8")),plannerSource=(await readFile(new URL("./experiment4bPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4bRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Probe.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Model.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar6rEvidence.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar6rModel.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar5Reranker.ts",import.meta.url),"utf8")),contractSource=await readFile(new URL("./experiment4ap1Contract.ts",import.meta.url),"utf8"),seedFree=auditProviderBlindSource([coreSource,plannerSource,contractSource]).clean';
  result=result.slice(0,auditStart)+audit+result.slice(auditEnd);
  result=replaceOnce(result,'probe_derived_contract_present:recipes.length>0&&recipes.some(r=>r.active_schema_proof?.probe_schema_fingerprint)','probe_derived_contract_present:recipes.length>0&&recipes.some(r=>r.active_schema_proof?.probe_schema_fingerprint),provenance_integrity:documentationOriginFallbacks===0');
  result=replaceOnce(result,'specProbeFetches,schemaProbeCalls,schemaProbe2xxJson,schemaProbeRejected,schemaProbeBytes,probeDerivedContracts,probeConfirmedContracts,synthesisCalls,synthesisRepairs,liveCalls,replay_deltas','specProbeFetches,requestGraphNodes,requestGraphEdges,provenApiOrigins,provenRequestTemplates,unboundRelativePaths,crossSourceJoinRejects,documentationOriginFallbacks,requestInventoryZeroAttempts,requestInventoryNonZeroAttempts,schemaProbeCalls,schemaProbe2xxJson,schemaProbeRejected,schemaProbeBytes,probeDerivedContracts,probeConfirmedContracts,synthesisCalls,synthesisRepairs,liveCalls,replay_deltas');
  result=replaceOnce(result,'"GO_4A_P1_ACTIVE_SCHEMA_INDUCTION":"REASSESS_4A_P1_ACTIVE_SCHEMA_INDUCTION"','"GO_4B_PROVENANCE_REQUEST_GRAPH":"REASSESS_4B_PROVENANCE_REQUEST_GRAPH"');
  result=replaceOnce(result,'experiment:"4A-P1",purpose:"development_active_schema_induction"','experiment:"4B",purpose:"development_provenance_request_graph"');
  result=replaceOnce(result,'base_sha:"c152a2370ec3640f85e54f435980208f934baef8"','base_sha:"08cf59875690709990a20ff93f31a8e72c0891a9"');
  return result;
}
