import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileEvidenceNativeSemantics4G,type Operation4G} from "./experiment4gSemantics.js";
import type {IrParameter} from "./experiment4fIr.js";
import {alignTaskOperation4H} from "./experiment4hAlignment.js";

const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|app[_-]?id|appid|client[_-]?id|client[_-]?secret)$/i;
const REQUIRED_AUTH_LOCAL=/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth).{0,100}(?:required|must|need|mandatory)|(?:required|must|need|mandatory).{0,100}(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i;
const GENERIC=new Set(["id","name","code","value","key","identifier","q","query","search","term","input"]);
const STOP=new Set(["given","public","machine","readable","api","operation","return","returns","canonical","human","readable","current","identify","that","the","and","for","with","from","into","value","metadata"]);
function paramsFor(s:any,op:Operation4G){return op.parameter_ids.map((id:string)=>s.parameters.find((p:IrParameter)=>p.id===id)).filter(Boolean) as IrParameter[]}
function toks(v:string){return lexicalTokensP1(v)}
function stem(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const suffix of ["_identifier","_name","_code","_id"])if(s.endsWith(suffix)&&s.length>suffix.length){s=s.slice(0,-suffix.length);break}return s}
function sourceSectionText(evidence:DocEvidence[],s:any,op:Operation4G){const ev=evidence.find(e=>e.evidence_id===op.source.evidence_id);if(!ev)return "";const sec=s.ir.sections.find((x:any)=>x.id===op.section_id),raw=String(ev.text||"");return raw.slice(Math.max(0,sec?.start??op.source.start??0),Math.min(raw.length,sec?.end??op.source.end??raw.length))}
function taskFrame(caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;const inputTokens=new Set(c.input_names.flatMap(toks)),outputTokens=new Set(c.required.flatMap(toks)),intentTokens=new Set(toks(c.intent).filter(x=>!STOP.has(x))),entityTokens=new Set([...intentTokens].filter(x=>!inputTokens.has(x)&&!outputTokens.has(x)));return{c,inputTokens,outputTokens,intentTokens,entityTokens}}
function localFrame(caseId:string,s:any,op:Operation4G,evidence:DocEvidence[]){const t=taskFrame(caseId);if(!t)return null;const sec=s.ir.sections.find((x:any)=>x.id===op.section_id),raw=sourceSectionText(evidence,s,op),localText=`${op.title} ${sec?.title||""} ${op.path} ${op.context} ${raw}`,localTokens=new Set(toks(localText));let inputSupport=0,entitySupport=0,outputSupport=0;for(const x of t.inputTokens)if(localTokens.has(x)||[...localTokens].some(y=>y.includes(x)&&x.length>=3))inputSupport++;for(const x of t.entityTokens)if(localTokens.has(x)||[...localTokens].some(y=>y.includes(x)&&x.length>=4))entitySupport++;for(const x of t.outputTokens)if(localTokens.has(x))outputSupport++;return{...t,localText,localTokens,inputSupport,entitySupport,outputSupport,support:Number(inputSupport>0)+Number(entitySupport>0)+Number(outputSupport>0)}}
function decoded(v:string){try{return decodeURIComponent(v.replace(/\+/g," "))}catch{return v}}
function isAuthName(v:string){return AUTH_NAME.test(decoded(v))}
function pruneAuthQueryPreserving(path:string,metrics:any){const q=path.indexOf("?");if(q<0)return path;const head=path.slice(0,q),tail=path.slice(q+1),parts=tail.split("&"),kept:string[]=[];let pruned=0;for(const part of parts){const eq=part.indexOf("="),name=eq<0?part:part.slice(0,eq);if(isAuthName(name)){pruned++;continue}kept.push(part)}metrics.authPairsPrunedSurgically+=pruned;metrics.optionalAuthSlotsPruned+=pruned;metrics.authNameGuardPruned+=pruned;const out=kept.length?`${head}?${kept.join("&")}`:head;if(out.replace(/\?.*$/,"")!==head)metrics.nonAuthRequestTextMutations++;return out}
function shape(v:any){const s=String(v??"").trim().replace(/^['"]|['"]$/g,"");if(/^[-+]?\d+(?:\.\d+)?$/.test(s))return "numeric";if(/^[A-Za-z][A-Za-z .()'-]*$/.test(s))return "alpha";if(/^[A-Za-z0-9*._:-]+$/.test(s)&&/[A-Za-z]/.test(s)&&/\d/.test(s))return "alnum";return "other"}
function compatibleShape(example:string,build:any){const a=shape(example),b=shape(build);return a===b||(a==="alnum"&&b==="alnum")}
function staticAnchor(path:string,placeholder:string){const head=path.split("?")[0],segments=head.split("/").filter(Boolean),idx=segments.findIndex(x=>x.includes(placeholder));if(idx<0)return "";for(let i=idx-1;i>=0;i--){const s=decoded(segments[i]).toLowerCase();if(!s||/^v?\d{1,4}$/.test(s)||/^(?:api|rest|v\d+)$/.test(s))continue;return s.replace(/[^a-z0-9]+/g," ").trim()}return ""}
function anchorPositive(anchor:string,frame:any){if(!anchor)return false;const at=toks(anchor);for(const a of at){if(frame.inputTokens.has(a)||frame.intentTokens.has(a)||frame.entityTokens.has(a))return true;for(const x of frame.inputTokens)if(x.length>=3&&a.includes(x))return true;for(const x of frame.entityTokens)if(x.length>=4&&a.includes(x))return true}return false}
function anchorContradiction(anchor:string,frame:any){if(!anchor)return false;if(anchorPositive(anchor,frame))return false;const at=toks(anchor).filter((x:string)=>!STOP.has(x)&&!GENERIC.has(x));if(!at.length)return false;return at.some((x:string)=>x.length>=4)}
function partialNameMatch(input:string,name:string){const a=toks(input).filter(x=>!GENERIC.has(x)),b=toks(name).filter(x=>!GENERIC.has(x));return a.some(x=>b.includes(x))}
function fixedSegment(core:string){const s=decoded(core).toLowerCase();return s.length<3||/^v?\d{1,4}$/.test(s)||/^(?:api|rest|json|xml|csv|http|https)$/.test(s)}
function queryParts(path:string){const q=path.indexOf("?");if(q<0)return[] as {name:string;value:string}[];return path.slice(q+1).split("&").filter(Boolean).map(part=>{const eq=part.indexOf("=");return{name:eq<0?part:part.slice(0,eq),value:eq<0?"":part.slice(eq+1)}})}
function pathExampleCandidates(path:string){const head=path.split("?")[0],absolute=/^https?:\/\//i.test(head),prefix=absolute?head.match(/^https?:\/\/[^/]+/i)?.[0]||"":"",rest=absolute?head.slice(prefix.length):head,segments=rest.split("/"),out:{index:number,raw:string,core:string,suffix:string}[]=[];for(let i=0;i<segments.length;i++){const raw=segments[i];if(!raw||raw.includes("{")||fixedSegment(raw))continue;const m=decoded(raw).match(/^(.+?)(\.(?:json|xml|csv))?$/i);if(!m)continue;const core=m[1],suffix=m[2]||"";if(fixedSegment(core))continue;out.push({index:i,raw,core,suffix})}return out}
function replacePathSegment(path:string,index:number,placeholder:string,suffix:string){const q=path.indexOf("?"),head=q<0?path:path.slice(0,q),tail=q<0?"":path.slice(q),absolute=/^https?:\/\//i.test(head),prefix=absolute?head.match(/^https?:\/\/[^/]+/i)?.[0]||"":"",rest=absolute?head.slice(prefix.length):head,segments=rest.split("/");segments[index]=`${placeholder}${suffix}`;return`${prefix}${segments.join("/")}${tail}`}
function structuralSlot(caseId:string,s:any,op:Operation4G,params:IrParameter[],metrics:any,evidence:DocEvidence[]){const frame=localFrame(caseId,s,op,evidence);if(!frame||frame.c.input_names.length!==1)return null;const input=frame.c.input_names[0],build=frame.c.build[input];metrics.operationLocalSlotCandidates++;
for(const p of params){const auth=p.auth_like||isAuthName(p.name);if(auth)continue;if(stem(p.name)===stem(input)||p.name.toLowerCase()===input.toLowerCase()){metrics.slotAcceptedExactOrMorph++;return{binding:p.id,param:p,score:30,kind:"named"}}}
for(const p of params){const auth=p.auth_like||isAuthName(p.name);if(auth)continue;if(p.in==="query"&&partialNameMatch(input,p.name)&&frame.support>0){metrics.slotAcceptedPartialQueryKey++;return{binding:p.id,param:p,score:26,kind:"query"}}}
for(const q of queryParts(op.path)){if(isAuthName(q.name))continue;if(partialNameMatch(input,decoded(q.name))&&frame.support>0){const name=decoded(q.name),p:IrParameter={id:`4j_query_${fourAp1Sha({op:op.id,name}).slice(0,12)}`,name,in:"query",required:true,description:"operation-local query key role",example:q.value?decoded(q.value):null,auth_like:false,source:op.source} as any;metrics.slotAcceptedPartialQueryKey++;return{binding:p.id,param:p,score:25,kind:"query"}}}
const candidates=pathExampleCandidates(op.path);for(const cand of candidates){const ph=`{slot4j_${stem(input)||"value"}}`,candidatePath=replacePathSegment(op.path,cand.index,ph,cand.suffix),anchor=staticAnchor(candidatePath,ph);if(!compatibleShape(cand.core,build)){metrics.slotRejectedShapeMismatch++;continue}const positive=anchorPositive(anchor,frame);if(anchorContradiction(anchor,frame)){metrics.slotRejectedEntityContradiction++;continue}if(!positive&&frame.inputSupport===0&&frame.support<2){metrics.slotRejectedNoLocalRoleEvidence++;continue}const name=`slot4j_${stem(input)||"value"}`,p:IrParameter={id:`4j_path_${fourAp1Sha({op:op.id,input,cand:cand.raw}).slice(0,12)}`,name,in:"path",required:true,description:"operation-local documented example slot",example:cand.core,auth_like:false,source:op.source} as any;metrics.slotAcceptedConcreteExample++;if(positive)metrics.slotAcceptedByAnchorContainment++;return{binding:p.id,param:p,score:24+(positive?4:0),kind:"concrete",path:candidatePath,anchor}}
metrics.slotRejectedNoLocalRoleEvidence++;return null}
function make(caseId:string,s:any,op:Operation4G,metrics:any,evidence:DocEvidence[]){metrics.alignmentCandidates++;const base=s.ir.api_bases.find((b:any)=>b.id===op.api_base_id);if(!base)return null;let params=paramsFor(s,op),path=op.path;const originalSection=sourceSectionText(evidence,s,op),localRequired=REQUIRED_AUTH_LOCAL.test(`${op.title} ${op.context}`)||REQUIRED_AUTH_LOCAL.test(originalSection);if(op.auth_class==="REQUIRED"||localRequired){metrics.requiredAuthSlotsBlocked+=params.filter(p=>p.auth_like||isAuthName(p.name)).length||1;return null}let a=alignTaskOperation4H(caseId,s,op,params.filter(p=>!isAuthName(p.name)),metrics),structural:any=null;if(!a.accepted&&a.reason==="no_identifier"){structural=structuralSlot(caseId,s,op,params,metrics,evidence);if(!structural)return null;params=[...params,structural.param];path=structural.path||path;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;a={accepted:true,bindings:{[c.input_names[0]]:structural.binding},score:10+structural.score,reason:"operation_local_slot",signals:{identifier:1,entity:1,action:0,output:0,generic:false,concrete:structural.kind==="concrete",morphology:structural.kind==="named"}} as any}
if(!a.accepted)return null;const bound=new Set(Object.values(a.bindings)),safeParams:IrParameter[]=[];for(const p of params){const nameAuth=isAuthName(p.name),auth=p.auth_like||nameAuth;if(!auth){safeParams.push(p);continue}if(bound.has(p.id)){metrics.authNameGuardRejected++;return null}if(nameAuth)metrics.authNameGuardPruned++;if(["OPTIONAL","RATE_LIMIT_UPGRADE","UNRELATED","UNKNOWN"].includes(op.auth_class))continue;metrics.requiredAuthSlotsBlocked++;return null}
if(path.includes("{")){metrics.placeholderBearingOperations++;metrics.placeholderPreservationChecks++}const pruned=pruneAuthQueryPreserving(path,metrics);if(path.includes("{")&&!pruned.includes("{"))metrics.placeholderPreservationFailures++;const slots:P1RequestSlot[]=safeParams.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:false,literals:p.example!==null?[{id:`lit4j_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:String(p.example)}]:[]})),literal_bindings:Record<string,string>={};for(const slot of slots){if(bound.has(slot.id))continue;if(slot.literals.length===1&&/json/i.test(slot.literals[0].value)&&/(?:format|response|output|type)/i.test(slot.name))literal_bindings[slot.id]=slot.literals[0].id}return{id:`req4j_${fourAp1Sha({op:op.id,base:base.id,path:pruned,input:a.bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:pruned,proof_type:`4j_operation_local_slot_anchor_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings:a.bindings,literal_bindings,score:1000+a.score+(structural?50:0)+(op.source.expanded?30:0),concrete_relation:op.absolute_url===null} as P1RequestHypothesis}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;if(h.slots.some(s=>s.auth_like||isAuthName(s.name)))return true;let url="";try{url=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(url)}catch{return true}for(const [n] of u.searchParams)if(isAuthName(n))return true;return false}
function buildGraph(evidence:DocEvidence[],caseId:string){const semantics=compileEvidenceNativeSemantics4G(evidence),metrics:any={...semantics.metrics,alignmentCandidates:0,alignmentAccepted:0,alignmentRejectedNoIdentifier:0,alignmentRejectedInsufficientSupport:0,alignmentRejectedGenericIdentifier:0,alignmentAcceptedByConcreteExample:0,alignmentAcceptedByMorphology:0,alignmentScoreHistogram:{},operationFrameCandidates:0,operationFrameWithIdentifierSignal:0,operationFrameWithEntitySignal:0,operationFrameWithActionSignal:0,operationFrameWithOutputSignal:0,optionalAuthSlotsPruned:0,requiredAuthSlotsBlocked:0,authLikeHypothesesRejectedBeforeRender:0,placeholderBearingOperations:0,placeholderPreservationChecks:0,placeholderPreservationFailures:0,authPairsPrunedSurgically:0,nonAuthRequestTextMutations:0,identifierRoleCandidates:0,identifierRoleAcceptedNamedParameter:0,identifierRoleAcceptedPlaceholder:0,identifierRoleAcceptedUniqueBuildValue:0,identifierRoleAcceptedQueryKey:0,identifierRoleAcceptedPathSegment:0,identifierRoleRejectedAmbiguousOccurrence:0,identifierRoleRejectedNoSemanticSupport:0,identifierRoleRejectedGeneric:0,identifierRoleRejectedAuthLike:0,operationLocalSlotCandidates:0,slotAcceptedExactOrMorph:0,slotAcceptedPartialQueryKey:0,slotAcceptedConcreteExample:0,slotAcceptedByAnchorContainment:0,slotRejectedShapeMismatch:0,slotRejectedNoLocalRoleEvidence:0,slotRejectedEntityContradiction:0,slotRejectedVersionOrFixedSegment:0,authNameGuardPruned:0,authNameGuardRejected:0};const built=semantics.operations.map(op=>make(caseId,semantics,op,metrics,evidence)).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of built){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score);return{semantics,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4J(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),g=buildGraph(evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let authLikeRenderedRequests=0,duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return{...g,probe_packet:packet,metrics:{...g.metrics,...expansion,authLikeRenderedRequests,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0,expandedEvidenceHypotheses:g.hypotheses.filter(h=>g.semantics.operations.find(o=>o.id===h.source_operation_id)?.source.expanded).length}}}
export function rebuildRequestGraph4J(evidence:DocEvidence[],caseId:string){const g=buildGraph(evidence,caseId),hypotheses=g.hypotheses.filter(h=>!renderedAuthLike(h,caseId));return{...g,hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
