import {deriveExperiment4iSource} from "./experiment4iDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4j_anchor_missing:${a.slice(0,140)}`);return s.replace(a,b)}
export function deriveExperiment4jSource(source:string){let x=deriveExperiment4iSource(source);
x=r(x,'import {compile4i as compile4ar,project4i as project4ar,scope4i as scope4ar,validate4i as validate4ar,validateProjected4i as validateProjected4ar} from "./experiment4iContract.js";','import {compile4j as compile4ar,project4j as project4ar,scope4j as scope4ar,validate4j as validate4ar,validateProjected4j as validateProjected4ar} from "./experiment4jContract.js";');
x=r(x,'import {synthesize4i as synthesize4ar} from "./experiment4iPlanner.js";','import {synthesize4j as synthesize4ar} from "./experiment4jPlanner.js";');
x=r(x,'const OUT="results/experiment-4i",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4j",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'identifierRoleRejectedAuthLike4i=0;','identifierRoleRejectedAuthLike4i=0,variableRoleCandidates4j=0,variableRoleAcceptedNamed4j=0,variableRoleAcceptedGenericContextual4j=0,variableRoleAcceptedRouteShape4j=0,variableRoleRejectedAmbiguous4j=0,variableRoleRejectedNoEvidence4j=0,entityGuardCandidates4j=0,entityGuardAccepted4j=0,entityGuardRejectedExplicitMismatch4j=0,entityGuardRejectedInsufficientEntityEvidence4j=0,actionGuardRejectedMismatch4j=0,wrongEntityHypothesesBeforeProbe4j=0;');
x=r(x,'identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;','identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;variableRoleCandidates4j+=sm.variableRoleCandidates||0;variableRoleAcceptedNamed4j+=sm.variableRoleAcceptedNamed||0;variableRoleAcceptedGenericContextual4j+=sm.variableRoleAcceptedGenericContextual||0;variableRoleAcceptedRouteShape4j+=sm.variableRoleAcceptedRouteShape||0;variableRoleRejectedAmbiguous4j+=sm.variableRoleRejectedAmbiguous||0;variableRoleRejectedNoEvidence4j+=sm.variableRoleRejectedNoEvidence||0;entityGuardCandidates4j+=sm.entityGuardCandidates||0;entityGuardAccepted4j+=sm.entityGuardAccepted||0;entityGuardRejectedExplicitMismatch4j+=sm.entityGuardRejectedExplicitMismatch||0;entityGuardRejectedInsufficientEntityEvidence4j+=sm.entityGuardRejectedInsufficientEntityEvidence||0;actionGuardRejectedMismatch4j+=sm.actionGuardRejectedMismatch||0;wrongEntityHypothesesBeforeProbe4j+=sm.wrongEntityHypothesesBeforeProbe||0;');
x=r(x,'identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,schemaProbeCalls','identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,variableRoleCandidates:variableRoleCandidates4j,variableRoleAcceptedNamed:variableRoleAcceptedNamed4j,variableRoleAcceptedGenericContextual:variableRoleAcceptedGenericContextual4j,variableRoleAcceptedRouteShape:variableRoleAcceptedRouteShape4j,variableRoleRejectedAmbiguous:variableRoleRejectedAmbiguous4j,variableRoleRejectedNoEvidence:variableRoleRejectedNoEvidence4j,entityGuardCandidates:entityGuardCandidates4j,entityGuardAccepted:entityGuardAccepted4j,entityGuardRejectedExplicitMismatch:entityGuardRejectedExplicitMismatch4j,entityGuardRejectedInsufficientEntityEvidence:entityGuardRejectedInsufficientEntityEvidence4j,actionGuardRejectedMismatch:actionGuardRejectedMismatch4j,wrongEntityHypothesesBeforeProbe:wrongEntityHypothesesBeforeProbe4j,schemaProbeCalls');
x=x.replaceAll('4I_STRUCTURAL_IDENTIFIER_ROLE:','4J_VARIABLE_ROLE_ENTITY_COMPATIBILITY:').replaceAll('GO_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','GO_4J_VARIABLE_ROLE_ENTITY_COMPATIBILITY').replaceAll('REASSESS_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','REASSESS_4J_VARIABLE_ROLE_ENTITY_COMPATIBILITY');
x=r(x,'experiment:"4I",purpose:"development_structural_identifier_role_inference"','experiment:"4J",purpose:"development_variable_role_entity_compatibility"');
x=r(x,'base_sha:"28c83671b4aa38bd87bf6ddefd540e1b5d6035c1"','base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"');
x=r(x,'wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,','wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,wrong_entity_hypotheses_before_probe_zero:wrongEntityHypothesesBeforeProbe4j===0,');
return x}
