import {mkdir,writeFile} from "node:fs/promises";
import {Client,StreamableHTTPClientTransport,SSEClientTransport} from "@modelcontextprotocol/client";
import {loadConfig} from "./config/index.js";
import {CASES,MAX_REGISTRY_BYTES,MAX_SPEC_BYTES,REGISTRY_URL,candidateSummary,casesContainNoMappings,flattenRegistry,parseContractDocument,rankRegistryRecords,validateSpecUrlSyntax,type CaseDef,type LiveContract,type RegistryRecord} from "./experiment3qCore.js";
import {fetchTextBounded} from "./experiment3qNetwork.js";
import {EXEC_CASES,compileRequest,executionReadiness,induceProjection,makeRecipe,project,semanticValidate,validateBindingProgram} from "./experiment3rCore.js";
import {callProcurementPlanner,parseProcurementPlan} from "./experiment3rPlanner.js";
import {buildSupplierCandidates,recipeHas3SFingerprintEvidence,verificationTraceFingerprint} from "./experiment3sCore.js";
import {verifyJsonRequest} from "./experiment3sNetwork.js";
import {MCP_MAX_EXECUTIONS,MCP_MAX_SERVERS,MCP_REGISTRY_URL,PUBLIC_APIS_URL,STANDARD_SPEC_PATHS,classifyMcpTool,extractMcpCandidates,parsePublicApis,publicApiEligible,rankPublicApis,runNegativeControls,sha,standardProbeUrl,type McpCandidate,type PublicApiEntry} from "./experiment3tCore.js";

const OUTDIR="results/experiment-3t";
const MAX_EXEC_BYTES=4*1024*1024;
const TIMEOUT_MS=12000;
let apisGuruFetches=0,publicCatalogFetches=0,mcpRegistryFetches=0,specFetches=0,publicSpecProbes=0,plannerCalls=0,plannerRepairs=0,projectionInductions=0,mcpToolCalls=0;
let credentialsSupplied=0,unsafeMcpExecutions=0,requiredParamMcpExecutions=0,nonEmptyMcpArgs=0,hostPolicyViolationsAccepted=0,arbitraryCodeExecuted=0;

function withTimeout<T>(p:Promise<T>):Promise<T>{return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error("timeout")),TIMEOUT_MS);p.then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)});});}
async function getApisGuru(){apisGuruFetches++;const {text}=await fetchTextBounded(REGISTRY_URL,MAX_REGISTRY_BYTES,"application/json");const raw=JSON.parse(text);return {records:flattenRegistry(raw),count:Object.keys(raw).length};}
async function getPublicCatalog(){publicCatalogFetches++;const {text}=await fetchTextBounded(PUBLIC_APIS_URL,16*1024*1024,"text/markdown,text/plain");return {entries:parsePublicApis(text)};}
async function getMcpRegistry(){mcpRegistryFetches++;const {text}=await fetchTextBounded(MCP_REGISTRY_URL,16*1024*1024,"application/json");const raw=JSON.parse(text);const records=Array.isArray(raw)?raw:Array.isArray(raw?.servers)?raw.servers:Array.isArray(raw?.data)?raw.data:Array.isArray(raw?.items)?raw.items:[];return {records,candidates:extractMcpCandidates(raw)};}

async function fetchGuruContracts(c:CaseDef,records:RegistryRecord[],cache:Map<string,LiveContract|null>){const ranked=rankRegistryRecords(c,records),out:LiveContract[]=[];for(const r of ranked.filter((x,i,a)=>a.findIndex(y=>y.spec_url===x.spec_url)===i).slice(0,20)){let contract=cache.get(r.spec_url);if(contract===undefined){specFetches++;try{const syntax=validateSpecUrlSyntax(r.spec_url);if(!syntax.ok)throw new Error("unsafe_spec");const {text}=await fetchTextBounded(r.spec_url,MAX_SPEC_BYTES,"application/json");contract=parseContractDocument(r,text);(contract as any).substrate="apis_guru";}catch{contract=null;}cache.set(r.spec_url,contract);}if(contract)out.push({...contract,registry_rank:r.registry_rank,registry_score:r.registry_score});}return out;}
async function probePublicEntry(entry:PublicApiEntry,rank:number){if(!publicApiEligible(entry))return null;for(const path of STANDARD_SPEC_PATHS){publicSpecProbes++;try{const url=standardProbeUrl(entry.link,path),{text}=await fetchTextBounded(url,MAX_SPEC_BYTES,"application/json");const record:RegistryRecord={api_key:`public_apis::${entry.name}@${new URL(entry.link).hostname}`,version:"live",spec_url:url,title:entry.name,description:entry.description,categories:[entry.category],registry_score:entry.score,registry_rank:rank};const contract=parseContractDocument(record,text);(contract as any).substrate="public_apis";return contract;}catch{}}return null;}
async function fetchPublicContracts(c:CaseDef,entries:PublicApiEntry[]){const ranked=rankPublicApis(c,entries),contracts:LiveContract[]=[];let next=0;const workers=Array.from({length:4},async()=>{while(true){const i=next++;if(i>=ranked.length)return;const found=await probePublicEntry(ranked[i],i+1);if(found)contracts.push(found);}});await Promise.all(workers);return {ranked,contracts};}

function makeTransport(c:McpCandidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function mcpList(c:McpCandidate){const client=new Client({name:"missing-3t",version:"0.1.0"});try{await withTimeout(client.connect(makeTransport(c)));const listed:any=await withTimeout(client.listTools());return {client,tools:listed.tools??[]};}catch(e){try{await client.close();}catch{}throw e;}}
async function verifyMcpSupply(c:McpCandidate){let first:any;try{first=await mcpList(c);}catch(e){return {ok:false,state:"unreachable",error:String(e)};}const safe=first.tools.find((t:any)=>classifyMcpTool(t).safe);if(!safe){await first.client.close();return {ok:false,state:"no_safe_tool"};}if(Array.isArray(safe.inputSchema?.required)&&safe.inputSchema.required.length)requiredParamMcpExecutions++;if(!classifyMcpTool(safe).safe)unsafeMcpExecutions++;mcpToolCalls++;try{await withTimeout(first.client.callTool({name:safe.name,arguments:{}}));}catch(e){await first.client.close();return {ok:false,state:"execution_error",error:String(e)};}await first.client.close();let second:any;try{second=await mcpList(c);}catch(e){return {ok:false,state:"confirmation_unreachable",error:String(e)};}const same=second.tools.find((t:any)=>t.name===safe.name&&classifyMcpTool(t).safe);if(!same){await second.client.close();return {ok:false,state:"tool_not_stable"};}mcpToolCalls++;try{await withTimeout(second.client.callTool({name:same.name,arguments:{}}));}catch(e){await second.client.close();return {ok:false,state:"confirmation_error",error:String(e)};}await second.client.close();return {ok:true,state:"verified_live",tool_name:safe.name,tool_schema_fingerprint:sha(safe.inputSchema),trace_fingerprint:sha({name:c.name,url:c.url,tool:safe.name})};}

async function procure(config:any,c:CaseDef,execCase:any,supplier:any,evidence:any[]):Promise<any>{const readiness=executionReadiness(supplier.contract,supplier.candidate);if(!readiness.ready)return {ok:false,status:"not_publicly_executable",readiness};plannerCalls++;let attempt=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"initial");let parsed=parseProcurementPlan(attempt),plan=parsed.plan,stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,substrate:(supplier.contract as any).substrate,...attempt,static_errors:stat.errors});if(parsed.error||stat.errors.length){plannerCalls++;plannerRepairs++;const repair=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"repair",(parsed.error?[parsed.error]:stat.errors).join(","));parsed=parseProcurementPlan(repair);plan=parsed.plan;stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,substrate:(supplier.contract as any).substrate,...repair,static_errors:stat.errors});}if(!plan||plan.decision!=="COMPILE"||stat.errors.length)return {ok:false,status:"binding_reject",readiness,plan,stat};return {ok:true,readiness,plan,bindings:stat.bindings};}

async function main(){await mkdir(OUTDIR,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");const controls=runNegativeControls(),started_at=new Date().toISOString(),plannerEvidence:any[]=[],caseEvidence:any[]=[],recipes:any[]=[],liveIndex:any[]=[];const guru=await getApisGuru(),catalog=await getPublicCatalog(),mcp=await getMcpRegistry(),guruCache=new Map<string,LiveContract|null>();
  for(const c of CASES){const execCase=EXEC_CASES[c.case_id],guruContracts=await fetchGuruContracts(c,guru.records,guruCache),publicResult=await fetchPublicContracts(c,catalog.entries),contracts=[...guruContracts,...publicResult.contracts],suppliers=buildSupplierCandidates(candidateSummary(c,contracts),contracts),attempts:any[]=[];let selected:any=null;
    for(const supplier of suppliers){const substrate=(supplier.contract as any).substrate||"apis_guru",proc=await procure(config,c,execCase,supplier,plannerEvidence);if(!proc.ok){attempts.push({substrate,api_key:supplier.candidate.api_key,status:proc.status});continue;}try{const r=proc.readiness;if(!r.server_base||!r.allowed_host)throw new Error("missing_base");const url=compileRequest(r.server_base,r.allowed_host,supplier.candidate.path,r.params,proc.bindings,execCase.build),verified=await verifyJsonRequest(url,MAX_EXEC_BYTES);projectionInductions++;const projection=induceProjection(verified.body,execCase,execCase.build),out=project(verified.body,projection);if(!semanticValidate(execCase,execCase.build,out))throw new Error("semantic_mismatch");const descriptor={case_id:c.case_id,api_key:supplier.contract.api_key,title:supplier.contract.title,spec_url:supplier.contract.spec_url,spec_fingerprint:supplier.contract.spec_fingerprint,operation_path:supplier.candidate.path,descriptor_fingerprint:sha({case_id:c.case_id,api_key:supplier.contract.api_key,spec:supplier.contract.spec_fingerprint,path:supplier.candidate.path})};let recipe:any=makeRecipe(execCase,descriptor,r,proc.bindings,projection);recipe={...recipe,substrate,verification_trace_fingerprint:verificationTraceFingerprint({substrate,api_key:supplier.candidate.api_key,url,output:out})};recipe.recipe_fingerprint=sha({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);liveIndex.push({substrate,identity:supplier.candidate.api_key,endpoint_fingerprint:sha(r.server_base),contract_fingerprint:supplier.contract.spec_fingerprint,verification_status:"verified_live",capability:c.case_id,verification_trace_fingerprint:recipe.verification_trace_fingerprint});selected={substrate,api_key:supplier.candidate.api_key,output:out,recipe};attempts.push({substrate,api_key:supplier.candidate.api_key,status:"verified_live"});break;}catch(e){attempts.push({substrate,api_key:supplier.candidate.api_key,status:"live_failed",error:String(e)});}}
    caseEvidence.push({case_id:c.case_id,guru_contracts:guruContracts.length,public_catalog_ranked:publicResult.ranked.map(x=>({name:x.name,score:x.score,link:x.link})),public_contracts:publicResult.contracts.length,supplier_count:suppliers.length,attempts,selected});}
  const mcpEvidence:any[]=[];let verifiedMcpCount=0;for(const c of mcp.candidates.slice(0,MCP_MAX_SERVERS)){if(verifiedMcpCount>=MCP_MAX_EXECUTIONS)break;const r=await verifyMcpSupply(c);mcpEvidence.push({...c,...r});if(r.ok){verifiedMcpCount++;liveIndex.push({substrate:"mcp_registry",identity:c.name,endpoint_fingerprint:sha(c.url),contract_fingerprint:r.tool_schema_fingerprint,verification_status:"verified_live",capability:r.tool_name,verification_trace_fingerprint:r.trace_fingerprint});}}
  const before={apisGuruFetches,publicCatalogFetches,mcpRegistryFetches,specFetches,publicSpecProbes,plannerCalls,projectionInductions},replay:any[]=[];for(const recipe of recipes){const execCase=EXEC_CASES[recipe.case_id];try{const url=compileRequest(recipe.server_base,recipe.allowed_host,recipe.operation_path,recipe.params,recipe.bindings,execCase.replay),verified=await verifyJsonRequest(url,MAX_EXEC_BYTES),out=project(verified.body,recipe.projection);if(!semanticValidate(execCase,execCase.replay,out))throw new Error("semantic_mismatch");replay.push({case_id:recipe.case_id,success:true,substrate:recipe.substrate,output:out});}catch(e){replay.push({case_id:recipe.case_id,success:false,substrate:recipe.substrate,error:String(e)});}}
  const replayDeltas={apis_guru_fetches:apisGuruFetches-before.apisGuruFetches,public_catalog_fetches:publicCatalogFetches-before.publicCatalogFetches,mcp_registry_fetches:mcpRegistryFetches-before.mcpRegistryFetches,spec_fetches:specFetches-before.specFetches,public_spec_probes:publicSpecProbes-before.publicSpecProbes,planner_calls:plannerCalls-before.plannerCalls,projection_inductions:projectionInductions-before.projectionInductions};const success=caseEvidence.filter(x=>x.selected),distinctProviders=new Set(success.map(x=>x.selected.api_key)).size,publicSuccess=success.filter(x=>x.selected.substrate==="public_apis").length,fallbackSuccess=caseEvidence.filter(x=>x.selected&&x.attempts.findIndex((a:any)=>a.status==="verified_live")>0).length,replaySuccess=replay.filter(x=>x.success).length,replayRate=recipes.length?replaySuccess/recipes.length:0,verifiedMcp=mcpEvidence.filter(x=>x.ok),mcpNamespaces=new Set(verifiedMcp.map(x=>x.namespace)).size,substrates=new Set(liveIndex.map(x=>x.substrate)).size,controlsExecuted=controls.filter(x=>x.executed).length,controlsVerified=controls.filter(x=>x.executed&&x.rejected).length,allFingerprints=liveIndex.length>=4&&liveIndex.every(x=>x.endpoint_fingerprint&&x.contract_fingerprint&&x.verification_trace_fingerprint),recipeFingerprints=recipeHas3SFingerprintEvidence(recipes);
  const metrics={apis_guru_entries:guru.count,public_api_entries:catalog.entries.length,mcp_registry_records:mcp.records.length,semantic_successes:success.length,distinct_semantic_providers:distinctProviders,public_apis_semantic_successes:publicSuccess,fallback_successes:fallbackSuccess,persisted_recipes:recipes.length,replay_successes:replaySuccess,replay_rate:replayRate,verified_mcp_servers:verifiedMcp.length,verified_mcp_namespaces:mcpNamespaces,verified_live_supply_records:liveIndex.length,verified_substrates:substrates,controls_executed:controlsExecuted,controls_verified:controlsVerified,mcp_tool_calls:mcpToolCalls,unsafe_mcp_executions:unsafeMcpExecutions,required_param_mcp_executions:requiredParamMcpExecutions,nonempty_mcp_args:nonEmptyMcpArgs,credentials_supplied:credentialsSupplied,host_policy_violations_accepted:hostPolicyViolationsAccepted,arbitrary_code_executed:arbitraryCodeExecuted,replay_deltas:replayDeltas};
  const gates={all_three_substrates_fetched:apisGuruFetches===1&&publicCatalogFetches===1&&mcpRegistryFetches===1,apis_guru_at_least_1000:guru.count>=1000,public_apis_at_least_200:catalog.entries.length>=200,mcp_registry_at_least_20:mcp.records.length>=20,zero_case_mappings:casesContainNoMappings(),at_least_2_semantic_successes:success.length>=2,at_least_2_semantic_providers:distinctProviders>=2,at_least_1_public_apis_success:publicSuccess>=1,at_least_1_fallback_success:fallbackSuccess>=1,replay_100_percent:recipes.length>=2&&replayRate===1,replay_control_calls_zero:Object.values(replayDeltas).every(v=>v===0),at_least_2_live_mcp_distinct_namespaces:verifiedMcp.length>=2&&mcpNamespaces>=2,at_least_2_verified_substrates:substrates>=2,at_least_4_live_supply_records:liveIndex.length>=4,all_supply_fingerprints_nonempty:allFingerprints&&recipeFingerprints,all_18_controls_verified:controlsExecuted===18&&controlsVerified===18,credentials_zero:credentialsSupplied===0,unsafe_mcp_zero:unsafeMcpExecutions===0,required_param_mcp_zero:requiredParamMcpExecutions===0,nonempty_mcp_args_zero:nonEmptyMcpArgs===0,host_policy_zero:hostPolicyViolationsAccepted===0,arbitrary_code_zero:arbitraryCodeExecuted===0};const formal_decision=Object.values(gates).every(Boolean)?"GO_MULTI_SUBSTRATE_LIVE_SUPPLY_ACQUISITION":"REASSESS_MULTI_SUBSTRATE_LIVE_SUPPLY_ACQUISITION";const report={experiment:"3T",title:"Multi-Substrate Live Supply Acquisition",started_at,finished_at:new Date().toISOString(),formal_decision,metrics,gates,cases:caseEvidence,mcp:mcpEvidence,replay,live_supply_index:liveIndex,negative_controls:controls};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUTDIR}/planner-evidence.json`,JSON.stringify(plannerEvidence,null,2));await writeFile(`${OUTDIR}/live-supply-index.json`,JSON.stringify(liveIndex,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));}
main().catch(async e=>{await mkdir(OUTDIR,{recursive:true});await writeFile(`${OUTDIR}/report.json`,JSON.stringify({experiment:"3T",formal_decision:"REASSESS_MULTI_SUBSTRATE_LIVE_SUPPLY_ACQUISITION",fatal_error:String(e)},null,2));console.error(e);process.exitCode=1;});
