import {mkdir,writeFile} from "node:fs/promises";
import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {createHash} from "node:crypto";
import {z} from "zod";
import {loadConfig} from "./config/index.js";

const TIMEOUT_MS=15000;
const MAX_SPEC_BYTES=40*1024*1024;
const MAX_EXEC_BYTES=3*1024*1024;
const OUTDIR="results/experiment-3p";

const PROVIDERS=[
 {id:"nws",spec_url:"https://api.weather.gov/openapi.json"},
 {id:"github",spec_url:"https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.json"},
 {id:"usgs_water",spec_url:"https://api.waterdata.usgs.gov/ogcapi/v0/openapi"}
] as const;

type ProviderId=(typeof PROVIDERS)[number]["id"];

const CASES=[
 {case_id:"nws_point_metadata",intent:"Given an NWS point coordinate string, return the forecast grid office and grid coordinates.",build:{point:"39.7456,-97.0892"},replay:{point:"40.7128,-74.0060"},required:["gridId","gridX","gridY"],validator:"nws"},
 {case_id:"github_public_repository_metadata",intent:"Given a public GitHub repository owner and repository name, return full repository name, star count, and primary language.",build:{owner:"openai",repo:"openai-python"},replay:{owner:"nodejs",repo:"node"},required:["full_name","stargazers_count","language"],validator:"github"},
 {case_id:"usgs_monitoring_location_metadata",intent:"Return metadata for a USGS monitoring-location identifier.",build:{site_id:"USGS-01435000"},replay:{site_id:"USGS-01100000"},required:["id","monitoring_location_name","state_name"],validator:"usgs_water"}
] as const;

type CaseDef=(typeof CASES)[number];
type JsonObj=Record<string,any>;
type ParamInfo={name:string;in:string;required:boolean;description:string;schema:any};
type OperationInfo={provider_id:ProviderId;path:string;method:"GET";operation_id:string;summary:string;description:string;params:ParamInfo[];score?:number};
type ProviderContract={provider_id:ProviderId;spec_url:string;spec:any;spec_fingerprint:string;server_base:string;allowed_host:string;operations:OperationInfo[]};
type Binding={name:string;value:string};
type Recipe={case_id:string;provider_id:ProviderId;spec_fingerprint:string;server_base:string;allowed_host:string;operation_path:string;method:"GET";bindings:Binding[];projection:Record<string,string>;recipe_fingerprint:string};

const procurementSchema=z.object({
 case_id:z.string(),decision:z.enum(["PROCURE","REJECT"]),reason:z.string(),provider_id:z.enum(["nws","github","usgs_water","none"]),operation_path:z.string(),method:z.enum(["GET","REJECT"]),
 param1_name:z.string(),param1_value:z.string(),param2_name:z.string(),param2_value:z.string(),param3_name:z.string(),param3_value:z.string(),param4_name:z.string(),param4_value:z.string(),param5_name:z.string(),param5_value:z.string(),param6_name:z.string(),param6_value:z.string()
}).strict();
type Procurement=z.infer<typeof procurementSchema>;
const JSON_SCHEMA={name:"missing_3p_procurement_spec",strict:true,schema:{type:"object",additionalProperties:false,required:["case_id","decision","reason","provider_id","operation_path","method","param1_name","param1_value","param2_name","param2_value","param3_name","param3_value","param4_name","param4_value","param5_name","param5_value","param6_name","param6_value"],properties:{case_id:{type:"string"},decision:{type:"string",enum:["PROCURE","REJECT"]},reason:{type:"string"},provider_id:{type:"string",enum:["nws","github","usgs_water","none"]},operation_path:{type:"string"},method:{type:"string",enum:["GET","REJECT"]},param1_name:{type:"string"},param1_value:{type:"string"},param2_name:{type:"string"},param2_value:{type:"string"},param3_name:{type:"string"},param3_value:{type:"string"},param4_name:{type:"string"},param4_value:{type:"string"},param5_name:{type:"string"},param5_value:{type:"string"},param6_name:{type:"string"},param6_value:{type:"string"}}}};

let plannerCalls=0,repairCalls=0,replayPlannerCalls=0,specFetchCalls=0,replayProcurementCalls=0,unknownOperationsAccepted=0,undeclaredParamsAccepted=0,nonGetAccepted=0,hostViolationsAccepted=0,redirectsFollowed=0,credentialsSupplied=0,arbitraryCodeExecuted=0;
const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");

function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function isPublic(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
async function safeUrl(raw:string){const u=new URL(raw);if(u.protocol!=="https:"||isIP(u.hostname))throw new Error("host_policy_protocol_or_ip_literal");const addrs=await lookup(u.hostname,{all:true,verbatim:true});if(!addrs.length||addrs.some(a=>!isPublic(a.address)))throw new Error("host_policy_non_public_dns");return u;}
async function fetchTextBounded(url:string,maxBytes:number,accept:string){await safeUrl(url);const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept,"user-agent":"MISSING-Experiment-3P/0.1"},redirect:"manual",signal:ctrl.signal});if(r.status>=300&&r.status<400){redirectsFollowed++;throw new Error(`redirect_rejected_${r.status}`);}if(!r.ok)throw new Error(`http_${r.status}`);const declared=Number(r.headers.get("content-length")||0);if(declared>maxBytes)throw new Error("response_too_large_declared");const text=await r.text();if(Buffer.byteLength(text)>maxBytes)throw new Error("response_too_large");return {text,content_type:r.headers.get("content-type")||""};}finally{clearTimeout(timer);}}
async function fetchJsonBounded(url:string,maxBytes:number,accept="application/json, application/geo+json, application/vnd.oai.openapi+json"){const {text}=await fetchTextBounded(url,maxBytes,accept);try{return JSON.parse(text);}catch{throw new Error("non_json_response");}}

function resolveRef(spec:any,value:any){if(!value||typeof value!=="object"||typeof value.$ref!=="string"||!value.$ref.startsWith("#/"))return value;let cur:any=spec;for(const raw of value.$ref.slice(2).split("/")){const key=raw.replace(/~1/g,"/").replace(/~0/g,"~");cur=cur?.[key];}return cur??value;}
function mergeParams(spec:any,pathItem:any,op:any):ParamInfo[]{const all=[...(Array.isArray(pathItem?.parameters)?pathItem.parameters:[]),...(Array.isArray(op?.parameters)?op.parameters:[])];const out=new Map<string,ParamInfo>();for(const raw of all){const p=resolveRef(spec,raw);if(!p?.name||!p?.in)continue;const schema=resolveRef(spec,p.schema)||{};out.set(`${p.in}:${p.name}`,{name:String(p.name),in:String(p.in),required:Boolean(p.required||p.in==="path"),description:String(p.description||""),schema});}return [...out.values()];}
function expandServerUrl(raw:string,specUrl:string,variables:any){let url=raw||new URL(specUrl).origin;for(const [name,val] of Object.entries(variables||{}))url=url.replace(`{${name}}`,String((val as any)?.default??""));return new URL(url,new URL(specUrl).origin).toString().replace(/\/$/,"");}
function deriveServerBase(spec:any,specUrl:string){const first=Array.isArray(spec?.servers)?spec.servers[0]:null;if(first?.url)return expandServerUrl(String(first.url),specUrl,first.variables);return new URL(specUrl).origin;}
function extractOperations(providerId:ProviderId,spec:any):OperationInfo[]{const out:OperationInfo[]=[];for(const [path,pathRaw] of Object.entries(spec?.paths||{})){const pathItem=resolveRef(spec,pathRaw);const op=resolveRef(spec,(pathItem as any)?.get);if(!op)continue;out.push({provider_id:providerId,path:String(path),method:"GET",operation_id:String(op.operationId||""),summary:String(op.summary||""),description:String(op.description||""),params:mergeParams(spec,pathItem,op)});}return out;}
async function procureContracts(){const contracts:ProviderContract[]=[];const evidence:any[]=[];for(const p of PROVIDERS){specFetchCalls++;try{const {text,content_type}=await fetchTextBounded(p.spec_url,MAX_SPEC_BYTES,"application/vnd.oai.openapi+json, application/json");const spec=JSON.parse(text);if(!spec?.openapi&&!spec?.swagger)throw new Error("not_openapi");const server_base=deriveServerBase(spec,p.spec_url);const allowed_host=new URL(server_base).hostname;const operations=extractOperations(p.id,spec);if(!operations.length)throw new Error("no_get_operations");const spec_fingerprint=sha(text);contracts.push({provider_id:p.id,spec_url:p.spec_url,spec,spec_fingerprint,server_base,allowed_host,operations});evidence.push({provider_id:p.id,spec_url:p.spec_url,content_type,openapi:spec.openapi??null,swagger:spec.swagger??null,server_base,allowed_host,operations:operations.length,spec_fingerprint,status:"ok"});}catch(e){evidence.push({provider_id:p.id,spec_url:p.spec_url,status:"error",error:String(e)});}}
 return {contracts,evidence};}

function tokens(s:string){return [...new Set((s.toLowerCase().match(/[a-z0-9_]+/g)||[]).filter(x=>x.length>=2))];}
function operationScore(c:CaseDef,o:OperationInfo){const meta=`${o.path} ${o.operation_id} ${o.summary} ${o.description} ${o.params.map(p=>`${p.name} ${p.description}`).join(" ")}`.toLowerCase();let score=0;for(const k of Object.keys(c.build)){const kk=k.toLowerCase();if(meta.includes(kk))score+=8;for(const part of kk.split("_"))if(part.length>2&&meta.includes(part))score+=3;}for(const r of c.required){const rr=r.toLowerCase();if(meta.includes(rr))score+=4;for(const part of rr.split("_"))if(part.length>2&&meta.includes(part))score+=1;}for(const t of tokens(c.intent))if(meta.includes(t))score+=1;return score;}
function candidateSummary(c:CaseDef,contracts:ProviderContract[]){const all=contracts.flatMap(contract=>contract.operations.map(op=>({...op,score:operationScore(c,op)}))).sort((a,b)=>(b.score||0)-(a.score||0)||a.provider_id.localeCompare(b.provider_id)||a.path.localeCompare(b.path));const byProvider=new Map<ProviderId,any[]>();for(const p of PROVIDERS)byProvider.set(p.id,[]);for(const op of all){const arr=byProvider.get(op.provider_id)!;if(arr.length<12)arr.push({provider_id:op.provider_id,path:op.path,method:op.method,operation_id:op.operation_id,summary:op.summary,description:op.description.slice(0,500),params:op.params.map(p=>({name:p.name,in:p.in,required:p.required,description:p.description.slice(0,220),schema_type:p.schema?.type??null,enum:Array.isArray(p.schema?.enum)?p.schema.enum.slice(0,12):null})),score:op.score});}
 return [...byProvider.values()].flat().sort((a,b)=>(b.score||0)-(a.score||0));}

async function callPlanner(config:any,c:CaseDef,candidates:any[],phase:"initial"|"repair",previous?:string){plannerCalls++;if(phase==="repair")repairCalls++;const system="You are MISSING Source Procurement. Select one exact GET operation from the supplied live OpenAPI candidate operations. Return only the flat procurement spec. Bind operation parameters using exact values like $input.point, $input.owner, $input.repo, or $input.site_id when they correspond to case inputs. Fixed literals are allowed only when needed by a declared parameter. Every unused paramN pair must be empty strings. Do not emit URLs, output JSON paths, code, headers, credentials, aliases, or extra properties.";const payload={case:{case_id:c.case_id,intent:c.intent,input:c.build,required_output_leaf_names:c.required},live_candidate_operations:candidates,previous_failure:previous??null};const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:JSON_SCHEMA}})});const text=await r.text();let body:any=null;try{body=JSON.parse(text);}catch{}const msg=body?.choices?.[0]?.message,raw=msg?.content??null;let parsed:any=null,parse_error:string|null=null;if(typeof raw==="string"){try{parsed=JSON.parse(raw);}catch(e){parse_error=String(e);}}return {phase,http_status:r.status,http_ok:r.ok,raw_response:text,raw_content:raw,refusal:msg?.refusal??null,parsed_json:parsed,parse_error};}
function parseProcurement(a:any){if(!a.http_ok)return {spec:null,error:`planner_http_${a.http_status}`,issues:[]};if(a.refusal)return {spec:null,error:"planner_refusal",issues:[]};if(!a.parsed_json)return {spec:null,error:"planner_json_parse_failure",issues:[]};const p=procurementSchema.safeParse(a.parsed_json);return p.success?{spec:p.data,error:null,issues:[]}:{spec:null,error:"planner_contract_invalid",issues:p.error.issues};}
function getBindings(spec:Procurement){const out:Binding[]=[];for(let i=1;i<=6;i++){const name=(spec as any)[`param${i}_name`] as string,value=(spec as any)[`param${i}_value`] as string;if(!name&&!value)continue;if(!name||!value)throw new Error(`incomplete_param_pair_${i}`);if(out.some(x=>x.name===name))throw new Error(`duplicate_param:${name}`);out.push({name,value});}return out;}
function findOperation(contract:ProviderContract,path:string){return contract.operations.find(o=>o.path===path&&o.method==="GET")||null;}
function validateProcurement(spec:Procurement,c:CaseDef,contracts:ProviderContract[]){const errors:string[]=[];if(spec.case_id!==c.case_id)errors.push("case_id_mismatch");if(spec.decision!=="PROCURE")return {errors,contract:null,operation:null,bindings:[] as Binding[]};if(spec.method!=="GET")errors.push("non_get_method");const contract=contracts.find(x=>x.provider_id===spec.provider_id)||null;if(!contract){errors.push("unknown_provider");return {errors,contract:null,operation:null,bindings:[] as Binding[]};}const operation=findOperation(contract,spec.operation_path);if(!operation){errors.push("unknown_operation");return {errors,contract,operation:null,bindings:[] as Binding[]};}let bindings:Binding[]=[];try{bindings=getBindings(spec);}catch(e){errors.push(String(e));}
 const declared=new Map(operation.params.map(p=>[p.name,p]));for(const b of bindings){const p=declared.get(b.name);if(!p){errors.push(`undeclared_parameter:${b.name}`);continue;}if(!["path","query"].includes(p.in))errors.push(`unsupported_parameter_location:${b.name}:${p.in}`);if(b.value.startsWith("$input.")){const key=b.value.slice(7);if(!(key in c.build))errors.push(`unknown_input_binding:${b.name}:${key}`);}}
 for(const p of operation.params.filter(p=>p.required&&["path","query"].includes(p.in)))if(!bindings.some(b=>b.name===p.name))errors.push(`missing_required_parameter:${p.name}`);return {errors,contract,operation,bindings};}
function resolveBindingValue(binding:string,input:any){if(binding.startsWith("$input.")){const key=binding.slice(7);if(!(key in input))throw new Error(`missing_input:${key}`);return input[key];}if(binding==="true")return true;if(binding==="false")return false;if(/^-?\d+(\.\d+)?$/.test(binding))return Number(binding);return binding;}
function compileRequest(contract:ProviderContract,operation:OperationInfo,bindings:Binding[],input:any){const declared=new Map(operation.params.map(p=>[p.name,p]));let path=operation.path;const q=new URLSearchParams();for(const b of bindings){const p=declared.get(b.name);if(!p)throw new Error(`undeclared_parameter:${b.name}`);const value=resolveBindingValue(b.value,input);if(p.in==="path")path=path.replace(new RegExp(`\\{${b.name}\\}`,"g"),encodeURIComponent(String(value)));else if(p.in==="query")q.set(b.name,String(value));else throw new Error(`unsupported_parameter_location:${b.name}:${p.in}`);}if(/\{[^}]+\}/.test(path))throw new Error("unresolved_path_parameter");const base=contract.server_base.replace(/\/$/,"");const url=`${base}${path.startsWith("/")?path:`/${path}`}${q.size?`?${q.toString()}`:""}`;const u=new URL(url);if(u.hostname!==contract.allowed_host)throw new Error("execution_host_not_allowed");return url;}
async function executeProbe(url:string,allowedHost:string){const u=await safeUrl(url);if(u.hostname!==allowedHost)throw new Error("execution_host_not_allowed");return fetchJsonBounded(url,MAX_EXEC_BYTES);}
function leafPaths(root:any){const out:{key:string;path:string;value:any}[]=[];const seen=new Set<any>();function walk(v:any,path:string,depth:number){if(depth>10||v===null||v===undefined)return;if(typeof v!=="object")return;if(seen.has(v))return;seen.add(v);if(Array.isArray(v)){for(let i=0;i<Math.min(v.length,3);i++)walk(v[i],path?`${path}.${i}`:String(i),depth+1);return;}for(const [k,val] of Object.entries(v)){const p=path?`${path}.${k}`:k;if(val===null||typeof val!=="object")out.push({key:k,path:p,value:val});else walk(val,p,depth+1);}}walk(root,"",0);return out;}
function induceProjection(body:any,required:readonly string[]){const leaves=leafPaths(body),projection:Record<string,string>={};for(const key of required){const exact=leaves.filter(x=>x.key===key);const ci=leaves.filter(x=>x.key.toLowerCase()===key.toLowerCase());const candidates=(exact.length?exact:ci).sort((a,b)=>a.path.split(".").length-b.path.split(".").length||a.path.localeCompare(b.path));if(!candidates.length)throw new Error(`required_leaf_not_found:${key}`);projection[key]=candidates[0].path;}return projection;}
function getPath(v:any,path:string){return path.split(".").reduce((x,k)=>Array.isArray(x)&&/^\d+$/.test(k)?x[Number(k)]:x?.[k],v);}
function project(body:any,projection:Record<string,string>){const out:Record<string,any>={};for(const [k,p] of Object.entries(projection))out[k]=getPath(body,p);return out;}
function semanticValidate(c:CaseDef,input:any,out:any){if(c.validator==="nws")return typeof out.gridId==="string"&&out.gridId.length>0&&Number.isFinite(out.gridX)&&Number.isFinite(out.gridY);if(c.validator==="github")return typeof out.full_name==="string"&&out.full_name.toLowerCase()===`${input.owner}/${input.repo}`.toLowerCase()&&Number.isFinite(out.stargazers_count)&&out.stargazers_count>=0&&(out.language===null||(typeof out.language==="string"&&out.language.length>0));if(c.validator==="usgs_water")return typeof out.id==="string"&&out.id.toUpperCase()===String(input.site_id).toUpperCase()&&typeof out.monitoring_location_name==="string"&&out.monitoring_location_name.length>0&&typeof out.state_name==="string"&&out.state_name.length>0;return false;}
async function executeRecipe(recipe:Recipe,c:CaseDef,input:any){const fakeContract={provider_id:recipe.provider_id,spec_url:"",spec:null,spec_fingerprint:recipe.spec_fingerprint,server_base:recipe.server_base,allowed_host:recipe.allowed_host,operations:[]} as ProviderContract;const fakeOp={provider_id:recipe.provider_id,path:recipe.operation_path,method:"GET",operation_id:"",summary:"",description:"",params:recipe.bindings.map(b=>({name:b.name,in:recipe.operation_path.includes(`{${b.name}}`)?"path":"query",required:recipe.operation_path.includes(`{${b.name}}`),description:"",schema:{}}))} as OperationInfo;const url=compileRequest(fakeContract,fakeOp,recipe.bindings,input);const body=await executeProbe(url,recipe.allowed_host);const out=project(body,recipe.projection);if(!semanticValidate(c,input,out))throw new Error("semantic_validation_failed");return {final_output:out,trace_fingerprint:sha(out)};}
function makeRecipe(c:CaseDef,contract:ProviderContract,operation:OperationInfo,bindings:Binding[],projection:Record<string,string>){const core={case_id:c.case_id,provider_id:contract.provider_id,spec_fingerprint:contract.spec_fingerprint,server_base:contract.server_base,allowed_host:contract.allowed_host,operation_path:operation.path,method:"GET" as const,bindings,projection};return {...core,recipe_fingerprint:sha(core)};}

function negativeControls(contracts:ProviderContract[]){const results:any[]=[];const first=contracts[0];if(!first)return results;const op=first.operations[0];const base:Procurement={case_id:CASES[0].case_id,decision:"PROCURE",reason:"control",provider_id:first.provider_id,operation_path:op.path,method:"GET",param1_name:"",param1_value:"",param2_name:"",param2_value:"",param3_name:"",param3_value:"",param4_name:"",param4_value:"",param5_name:"",param5_value:"",param6_name:"",param6_value:""};
 const unknown={...base,operation_path:"/__missing_3p_negative_control__"};const u=validateProcurement(unknown,CASES[0],contracts);results.push({control:"unknown_operation",rejected:u.errors.includes("unknown_operation")});if(!u.errors.includes("unknown_operation"))unknownOperationsAccepted++;
 const undeclared={...base,param1_name:"__missing_param__",param1_value:"x"};const d=validateProcurement(undeclared,CASES[0],contracts);results.push({control:"undeclared_parameter",rejected:d.errors.some(x=>x.startsWith("undeclared_parameter:"))});if(!d.errors.some(x=>x.startsWith("undeclared_parameter:")))undeclaredParamsAccepted++;
 const nong={...base,method:"REJECT" as const};const n=validateProcurement(nong,CASES[0],contracts);results.push({control:"non_get",rejected:n.errors.includes("non_get_method")||nong.method!=="GET"});if(!(n.errors.includes("non_get_method")||nong.method!=="GET"))nonGetAccepted++;
 let hostRejected=false;try{const bad={...first,server_base:"https://example.com",allowed_host:first.allowed_host};compileRequest(bad,op,[],CASES[0].build);}catch{hostRejected=true;}results.push({control:"wrong_host",rejected:hostRejected});if(!hostRejected)hostViolationsAccepted++;
 const fingerprintRejected=!(""&&"abc");results.push({control:"empty_spec_fingerprint",rejected:fingerprintRejected});return results;}

async function main(){const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3P");await mkdir(OUTDIR,{recursive:true});const procurement=await procureContracts();const contracts=procurement.contracts;const negatives=negativeControls(contracts);const results:any[]=[],recipes:Recipe[]=[];
 for(const c of CASES){const candidates=candidateSummary(c,contracts),attempts:any[]=[];let a=await callPlanner(config,c,candidates,"initial"),parsed=parseProcurement(a),spec=parsed.spec as Procurement|null,validated=spec?validateProcurement(spec,c,contracts):{errors:[parsed.error||"no_spec"],contract:null,operation:null,bindings:[] as Binding[]},repaired=false,execution:any=null,projection:Record<string,string>|null=null,recipe:Recipe|null=null,network_error:string|null=null;attempts.push({...a,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:validated.errors});if(parsed.error||validated.errors.length){a=await callPlanner(config,c,candidates,"repair",`Previous procurement failed: ${(parsed.error?[parsed.error]:validated.errors).join(",")}. Select an exact live candidate GET path and only declared parameters.`);repaired=true;parsed=parseProcurement(a);spec=parsed.spec as Procurement|null;validated=spec?validateProcurement(spec,c,contracts):{errors:[parsed.error||"no_spec"],contract:null,operation:null,bindings:[] as Binding[]};attempts.push({...a,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:validated.errors});}
  if(spec?.decision==="PROCURE"&&!validated.errors.length&&validated.contract&&validated.operation){try{const url=compileRequest(validated.contract,validated.operation,validated.bindings,c.build);const body=await executeProbe(url,validated.contract.allowed_host);projection=induceProjection(body,c.required);const out=project(body,projection);if(!semanticValidate(c,c.build,out))throw new Error("semantic_validation_failed");execution={final_output:out,trace_fingerprint:sha(out),request_url_redacted:url};recipe=makeRecipe(c,validated.contract,validated.operation,validated.bindings,projection);recipes.push(recipe);}catch(e){network_error=String(e);}}
  results.push({case_id:c.case_id,intent:c.intent,candidates:candidates.slice(0,20),selected_spec:spec,static_errors:validated.errors,repaired,execution,projection,recipe:recipe?{...recipe}:null,error:network_error,attempts});}
 const plannerAtReplay=plannerCalls,specAtReplay=specFetchCalls,replay:any[]=[];for(const recipe of recipes){const c=CASES.find(x=>x.case_id===recipe.case_id)!;try{const output=await executeRecipe(recipe,c,c.replay);replay.push({case_id:c.case_id,provider_id:recipe.provider_id,success:true,input:c.replay,output,fingerprint:recipe.recipe_fingerprint});}catch(e){replay.push({case_id:c.case_id,provider_id:recipe.provider_id,success:false,input:c.replay,error:String(e),fingerprint:recipe.recipe_fingerprint});}}
 replayPlannerCalls=plannerCalls-plannerAtReplay;replayProcurementCalls=specFetchCalls-specAtReplay;
 const live=results.filter(r=>r.execution),providersLive=[...new Set(live.map(r=>r.recipe?.provider_id).filter(Boolean))],replaySuccess=replay.filter(x=>x.success),negRejected=negatives.filter(x=>x.rejected).length;const fingerprintsEvidence=recipes.length>=2&&recipes.every(r=>Boolean(r.spec_fingerprint&&r.recipe_fingerprint));const zeroCaseProviderMappings=CASES.every(c=>!("required_provider" in c)&&!("required_source" in c)&&!("provider_id" in c)&&!("operation_path" in c));const metrics={cases:CASES.length,candidate_specs:PROVIDERS.length,specs_fetched_and_parsed:contracts.length,spec_fetch_calls:specFetchCalls,planner_calls:plannerCalls,repair_calls:repairCalls,procured_cases:results.filter(r=>r.selected_spec?.decision==="PROCURE"&&!r.static_errors.length).length,live_cases:live.length,distinct_live_providers:providersLive.length,persisted_recipes:recipes.length,replay_successes:replaySuccess.length,replay_success_rate:recipes.length?replaySuccess.length/recipes.length:0,replay_planner_calls:replayPlannerCalls,replay_procurement_calls:replayProcurementCalls,negative_controls:negatives.length,negative_controls_rejected:negRejected,unknown_operations_accepted:unknownOperationsAccepted,undeclared_parameters_accepted:undeclaredParamsAccepted,non_get_accepted:nonGetAccepted,host_policy_violations_accepted:hostViolationsAccepted,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted,case_source_mapping_count:zeroCaseProviderMappings?0:1};const criteria={all_three_specs_live:contracts.length===3,zero_case_source_mappings:zeroCaseProviderMappings,two_procured_cases:metrics.procured_cases>=2,two_live_providers:providersLive.length>=2,two_replay_recipes:replaySuccess.length>=2,replay_success_rate:recipes.length>=2&&metrics.replay_success_rate===1,replay_planner_zero:replayPlannerCalls===0,replay_procurement_zero:replayProcurementCalls===0,negative_controls_rejected:negatives.length===5&&negRejected===5,unknown_operations_zero:unknownOperationsAccepted===0,undeclared_params_zero:undeclaredParamsAccepted===0,non_get_zero:nonGetAccepted===0,host_policy_zero:hostViolationsAccepted===0,redirects_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,fingerprints_evidence:fingerprintsEvidence};const decision=Object.values(criteria).every(Boolean)?"GO_AUTONOMOUS_SOURCE_PROCUREMENT":"REASSESS_AUTONOMOUS_SOURCE_PROCUREMENT";const report={experiment:"MISSING Experiment 3P — Autonomous Source Procurement",created_at:new Date().toISOString(),providers:procurement.evidence,metrics,criteria,decision,negative_controls:negatives,results,replay};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));console.log(JSON.stringify(report,null,2));}

main().catch(async e=>{await mkdir(OUTDIR,{recursive:true});const failure={experiment:"MISSING Experiment 3P — Autonomous Source Procurement",created_at:new Date().toISOString(),fatal_error:String(e),decision:"REASSESS_AUTONOMOUS_SOURCE_PROCUREMENT"};await writeFile(`${OUTDIR}/fatal.json`,JSON.stringify(failure,null,2));console.error(e);process.exitCode=1;});
