import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileEvidenceNativeSemantics4G,type Operation4G} from "./experiment4gSemantics.js";
import type {IrParameter} from "./experiment4fIr.js";
import {alignTaskOperation4H} from "./experiment4hAlignment.js";
const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const REQUIRED_AUTH_LOCAL=/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth).{0,100}(?:required|must|need|mandatory)|(?:required|must|need|mandatory).{0,100}(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i;
const GENERIC=new Set(["id","name","code","value","key","identifier"]),NOISE=new Set(["api","get","lookup","search","find","retrieve","fetch","decode","estimate","metadata","identify","resolve","convert","list","public","collection","v","json","format"]);
function paramsFor(s:any,op:Operation4G){return op.parameter_ids.map((id:string)=>s.parameters.find((p:IrParameter)=>p.id===id)).filter(Boolean) as IrParameter[]}
function toks(v:string){return lexicalTokensP1(v)}
function stem(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const suffix of ["_identifier","_name","_code","_id"])if(s.endsWith(suffix)&&s.length>suffix.length){s=s.slice(0,-suffix.length);break}return s.replace(/s$/,"")}
function sourceSectionText(evidence:DocEvidence[],s:any,op:Operation4G){const ev=evidence.find(e=>e.evidence_id===op.source.evidence_id);if(!ev)return "";const sec=s.ir.sections.find((x:any)=>x.id===op.section_id),raw=String(ev.text||"");return raw.slice(Math.max(0,sec?.start??op.source.start??0),Math.min(raw.length,sec?.end??op.source.end??raw.length))}
function originalLocal(evidence:DocEvidence[],s:any,op:Operation4G){const sec=s.ir.sections.find((x:any)=>x.id===op.section_id);return `${op.title} ${sec?.title||""} ${op.context} ${sourceSectionText(evidence,s,op)}`}
function roleTokens(input:string){return new Set(toks(input).map(stem).filter(x=>x&&!GENERIC.has(x)))}
function semanticSupport(caseId:string,op:Operation4G,s:any){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return 0;const o=new Set(toks(`${op.title} ${s.ir.sections.find((x:any)=>x.id===op.section_id)?.title||""} ${op.path} ${op.context}`).map(stem)),t=new Set(toks(`${c.intent} ${c.required.join(" ")}`).map(stem).filter(x=>!NOISE.has(x)));let n=0;for(const x of t)if(o.has(x))n++;return n}
function hasLocalRole(input:string,local:string){const l=new Set(toks(local).map(stem));for(const r of roleTokens(input))if(l.has(r))return true;return false}
function entityCompatible(caseId:string,op:Operation4G,s:any,metrics:any){metrics.entityTargetChecks++;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return false;const inputRoles=new Set(c.input_names.flatMap(x=>[...roleTokens(x)]));const task=new Set(toks(`${c.intent} ${c.required.join(" ")}`).map(stem).filter(x=>x.length>2&&!NOISE.has(x)&&!GENERIC.has(x))),path=new Set(toks(op.path).map(stem).filter(x=>x.length>2&&!NOISE.has(x)&&!GENERIC.has(x)));let taskHit=0;for(const x of task)if(path.has(x))taskHit++;let roleHit=0;for(const x of inputRoles)if(path.has(x))roleHit++;if(taskHit||roleHit){metrics.entityTargetAccepted++;return true}const resource=[...path].filter(x=>!/^[0-9]+$/.test(x)&&!/^https?$/.test(x));if(resource.length){metrics.entityTargetRejectedMismatch++;return false}metrics.entityTargetAccepted++;return true}
function pruneAuthQueryPreserving(path:string,metrics:any){const q=path.indexOf("?");if(q<0)return path;const head=path.slice(0,q),parts=path.slice(q+1).split("&"),kept:string[]=[];let pruned=0;for(const part of parts){const eq=part.indexOf("="),name=eq<0?part:part.slice(0,eq);let d=name;try{d=decodeURIComponent(name.replace(/\+/g," "))}catch{}if(AUTH_NAME.test(d)){pruned++;continue}kept.push(part)}metrics.authPairsPrunedSurgically+=pruned;metrics.optionalAuthSlotsPruned+=pruned;const out=kept.length?`${head}?${kept.join("&")}`:head;if(out.replace(/\?.*$/,"")!==head)metrics.nonAuthRequestTextMutations++;return out}
function mutableCandidates(path:string){const q=path.indexOf("?"),pathname=q<0?path:path.slice(0,q),query=q<0?"":path.slice(q+1),out:{start:number,end:number,label:string,in:"path"|"query",generic:boolean}[]=[];for(const m of pathname.matchAll(/\{([^}]+)\}/g)){const label=m[1],start=m.index??0;out.push({start,end:start+m[0].length,label,in:"path",generic:GENERIC.has(stem(label))})}let offset=q<0?0:q+1;for(const part of query.split("&")){if(!part){offset++;continue}const eq=part.indexOf("="),name=eq<0?part:part.slice(0,eq),value=eq<0?"":part.slice(eq+1);if(value&&value!=="json"&&value!=="xml"&&!AUTH_NAME.test(name)){const start=offset+eq+1;out.push({start,end:start+value.length,label:name,in:"query",generic:GENERIC.has(stem(name))})}offset+=part.length+1}const segRe=/\/([^/?#{}]+)/g;for(const m of pathname.matchAll(segRe)){const value=m[1],start=(m.index??0)+1;if(/^(?:api|v\d+|public|collection|objects?|products?|characters?|books?|lookup|search|decode|decodevin)$/i.test(value))continue;if(/^[A-Za-z][A-Za-z_-]{1,24}$/.test(value))continue;out.push({start,end:start+value.length,label:"segment",in:"path",generic:true})}return out}
function addContextualSlot(caseId:string,s:any,op:Operation4G,params:IrParameter[],metrics:any,evidence:DocEvidence[]){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c||c.input_names.length!==1)return null;const input=c.input_names[0],value=String(c.build[input]??""),sup=semanticSupport(caseId,op,s),local=originalLocal(evidence,s,op);metrics.identifierRoleCandidates++;const named=params.find(p=>!p.auth_like&&!AUTH_NAME.test(p.name)&&(stem(p.name)===stem(input)||p.name.toLowerCase()===input.toLowerCase()));if(named){metrics.identifierRoleAcceptedNamedParameter++;return{binding:named.id,param:named,score:20}}
const placeholders=[...op.path.matchAll(/\{([^}]+)\}/g)];for(const m of placeholders){const label=m[1],generic=GENERIC.has(stem(label));if(stem(label)===stem(input)&&(!generic||sup>=2)){metrics.identifierRoleAcceptedPlaceholder++;const p:any={id:`4j_path_${fourAp1Sha({op:op.id,label}).slice(0,12)}`,name:label,in:"path",required:true,description:"documented placeholder",example:null,auth_like:false,source:op.source};return{binding:p.id,param:p,score:18}}}
const lower=op.path.toLowerCase(),needle=value.toLowerCase(),first=lower.indexOf(needle);if(first>=0&&lower.indexOf(needle,first+needle.length)<0&&sup>=1){const label=`structural_${stem(input)||"value"}`,path=`${op.path.slice(0,first)}{${label}}${op.path.slice(first+value.length)}`,p:any={id:`4j_struct_${fourAp1Sha({op:op.id,input,first}).slice(0,12)}`,name:label,in:path.includes("?")&&first>path.indexOf("?")?"query":"path",required:true,description:"unique documented build value occurrence",example:value,auth_like:false,source:op.source};metrics.identifierRoleAcceptedUniqueBuildValue++;return{binding:p.id,param:p,score:16,path}}
metrics.contextualRoleCandidates++;if(!hasLocalRole(input,local)){metrics.contextualRoleRejectedNoLocalRole++;metrics.identifierRoleRejectedNoSemanticSupport++;return null}const candidates=mutableCandidates(op.path);const role=[...roleTokens(input)][0]||stem(input);const exact=candidates.filter(x=>stem(x.label)===role),usable=exact.length?exact:candidates;if(usable.length!==1){metrics.contextualRoleRejectedAmbiguousPosition++;metrics.identifierRoleRejectedAmbiguousOccurrence++;return null}const cand=usable[0];if(AUTH_NAME.test(cand.label)){metrics.contextualRoleRejectedAuthLike++;return null}if(sup<1){metrics.contextualRoleRejectedInsufficientSupport++;return null}if(cand.generic&&sup<2){metrics.contextualRoleRejectedInsufficientSupport++;return null}const label=`contextual_${role}`,path=`${op.path.slice(0,cand.start)}{${label}}${op.path.slice(cand.end)}`,p:any={id:`4j_ctx_${fourAp1Sha({op:op.id,input,start:cand.start}).slice(0,12)}`,name:label,in:cand.in,required:true,description:"explicit local identifier role transferred to unique documented request position",example:null,auth_like:false,source:op.source};metrics.contextualRoleAcceptedExplicitLocalLabel++;if(cand.generic)metrics.contextualRoleAcceptedGenericWithTwoSupports++;return{binding:p.id,param:p,score:22,path}}
function make(caseId:string,s:any,op:Operation4G,metrics:any,evidence:DocEvidence[]){metrics.alignmentCandidates++;const base=s.ir.api_bases.find((b:any)=>b.id===op.api_base_id);if(!base)return null;let params=paramsFor(s,op),path=op.path;const originalSection=sourceSectionText(evidence,s,op),localRequired=REQUIRED_AUTH_LOCAL.test(`${op.title} ${op.context}`)||REQUIRED_AUTH_LOCAL.test(originalSection);if(op.auth_class==="REQUIRED"||localRequired){metrics.requiredAuthSlotsBlocked+=params.filter(p=>p.auth_like||AUTH_NAME.test(p.name)).length||1;return null}params=params.filter(p=>{if(p.auth_like||AUTH_NAME.test(p.name)){metrics.optionalAuthSlotsPruned++;return false}return true});let a=alignTaskOperation4H(caseId,s,op,params,metrics),structural:any=null;if(!a.accepted&&a.reason==="no_identifier"){structural=addContextualSlot(caseId,s,op,params,metrics,evidence);if(!structural)return null;params=[...params,structural.param];path=structural.path||path;a=alignTaskOperation4H(caseId,s,{...op,path} as any,params,metrics);if(!a.accepted){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;a={accepted:true,bindings:{[c.input_names[0]]:structural.binding},score:10+structural.score,reason:"contextual",signals:{identifier:1,entity:1,action:0,output:0,generic:false,concrete:true,morphology:false}} as any}}
if(!a.accepted)return null;if(!entityCompatible(caseId,{...op,path:op.path} as any,s,metrics))return null;const bound=new Set(Object.values(a.bindings));if(path.includes("{")){metrics.placeholderBearingOperations++;metrics.placeholderPreservationChecks++}const pruned=pruneAuthQueryPreserving(path,metrics);if(path.includes("{")&&!pruned.includes("{"))metrics.placeholderPreservationFailures++;const slots:P1RequestSlot[]=params.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:false,literals:p.example!==null?[{id:`lit4j_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:p.example}]:[]})),literal_bindings:Record<string,string>={};for(const slot of slots){if(bound.has(slot.id))continue;if(slot.literals.length===1&&/json/i.test(slot.literals[0].value)&&/(?:format|response|output|type)/i.test(slot.name))literal_bindings[slot.id]=slot.literals[0].id}return{id:`req4j_${fourAp1Sha({op:op.id,base:base.id,path:pruned,input:a.bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:pruned,proof_type:`4j_contextual_identifier_role_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings:a.bindings,literal_bindings,score:1000+a.score+(structural?50:0)+(op.source.expanded?30:0),concrete_relation:op.absolute_url===null} as P1RequestHypothesis}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let url="";try{url=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(url)}catch{return true}for(const [n] of u.searchParams)if(AUTH_NAME.test(n))return true;return h.slots.some(s=>s.auth_like||AUTH_NAME.test(s.name))}
function buildGraph(evidence:DocEvidence[],caseId:string){const semantics=compileEvidenceNativeSemantics4G(evidence),metrics:any={...semantics.metrics,alignmentCandidates:0,alignmentAccepted:0,alignmentRejectedNoIdentifier:0,alignmentRejectedInsufficientSupport:0,alignmentRejectedGenericIdentifier:0,alignmentAcceptedByConcreteExample:0,alignmentAcceptedByMorphology:0,alignmentScoreHistogram:{},operationFrameCandidates:0,operationFrameWithIdentifierSignal:0,operationFrameWithEntitySignal:0,operationFrameWithActionSignal:0,operationFrameWithOutputSignal:0,optionalAuthSlotsPruned:0,requiredAuthSlotsBlocked:0,placeholderBearingOperations:0,placeholderPreservationChecks:0,placeholderPreservationFailures:0,authPairsPrunedSurgically:0,nonAuthRequestTextMutations:0,identifierRoleCandidates:0,identifierRoleAcceptedNamedParameter:0,identifierRoleAcceptedPlaceholder:0,identifierRoleAcceptedUniqueBuildValue:0,identifierRoleRejectedAmbiguousOccurrence:0,identifierRoleRejectedNoSemanticSupport:0,contextualRoleCandidates:0,contextualRoleAcceptedExplicitLocalLabel:0,contextualRoleAcceptedGenericWithTwoSupports:0,contextualRoleAcceptedCrossExampleVariation:0,contextualRoleRejectedNoLocalRole:0,contextualRoleRejectedAmbiguousPosition:0,contextualRoleRejectedInsufficientSupport:0,contextualRoleRejectedAuthLike:0,entityTargetChecks:0,entityTargetAccepted:0,entityTargetRejectedMismatch:0,entityTargetRejectedNoEntityEvidence:0};const built=semantics.operations.map(op=>make(caseId,semantics,op,metrics,evidence)).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of built){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score);return{semantics,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4J(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),g=buildGraph(evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let authLikeRenderedRequests=0,duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return{...g,probe_packet:packet,metrics:{...g.metrics,...expansion,authLikeRenderedRequests,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,wrongEntityProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0,expandedEvidenceHypotheses:g.hypotheses.filter(h=>g.semantics.operations.find(o=>o.id===h.source_operation_id)?.source.expanded).length}}}
export function rebuildRequestGraph4J(evidence:DocEvidence[],caseId:string){const g=buildGraph(evidence,caseId),hypotheses=g.hypotheses.filter(h=>!renderedAuthLike(h,caseId));return{...g,hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
