import {deriveExperiment4lSource} from "./experiment4lDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4m_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4mSource(source:string){
  let x=deriveExperiment4lSource(source);
  x=r(x,'import {compile4l as compile4ar,project4l as project4ar,scope4l as scope4ar,validate4l as validate4ar,validateProjected4l as validateProjected4ar} from "./experiment4lContract.js";','import {compile4m as compile4ar,project4m as project4ar,scope4m as scope4ar,validate4m as validate4ar,validateProjected4m as validateProjected4ar} from "./experiment4mContract.js";');
  x=r(x,'import {synthesize4l as synthesize4ar} from "./experiment4lPlanner.js";','import {synthesize4m as synthesize4ar} from "./experiment4mPlanner.js";');
  x=r(x,'import {fetchTextSafeR2,recoveredBroadRetrieveR2,safetyGateFromLedger,RECOVERY_R2_TOP_K} from "./experiment3yr2Core.js";',`import {fetchTextSafeR2,recoveredBroadRetrieveR2,safetyGateFromLedger,RECOVERY_R2_TOP_K} from "./experiment3yr2Core.js";
import {fetchDocTextSafe4M,fetchSpecTextSafe4M,resetAcquisitionCache4M,acquisitionCacheMetrics4M} from "./experiment4mFetch.js";`);
  x=r(x,'const OUT="results/experiment-4l",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4m",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
  x=r(x,'const got=await fetchTextSafeR2(provider.start_url,item.url,MAX_BYTES,ledger)','const got=await fetchDocTextSafe4M(provider.start_url,item.url,MAX_BYTES,ledger)');
  x=r(x,'const got=await fetchTextSafeR2(provider.start_url,url,MAX_BYTES,ledger)','const got=await fetchSpecTextSafe4M(provider.start_url,url,MAX_BYTES,ledger)');
  x=r(x,'async function main(){await mkdir(OUT,{recursive:true});','async function main(){resetAcquisitionCache4M();await mkdir(OUT,{recursive:true});');

  x=r(x,'executableGateProbe2xxJson4l=0,probeCacheHits4l=0,probeNetworkFetches4l=0,duplicateProbeNetworkFetches4l=0;',`executableGateProbe2xxJson4l=0,probeCacheHits4l=0,probeNetworkFetches4l=0,duplicateProbeNetworkFetches4l=0,
acquisitionTraceEvents4m=0,acquisitionTraceDistinctUrls4m=0,acquisitionTraceEligible4m=0,acquisitionTraceRejectedAsset4m=0,acquisitionTraceRejectedNavigation4m=0,acquisitionTraceRejectedDocumentation4m=0,acquisitionTraceRejectedLineage4m=0,acquisitionTraceRejectedAuthLike4m=0,acquisitionTraceExactBuildValueSlots4m=0,acquisitionTraceFamilySlots4m=0,acquisitionTraceEchoSupportedSlots4m=0,acquisitionTraceHypotheses4m=0,acquisitionTraceProbeCalls4m=0,acquisitionTraceProbe2xxJson4m=0,acquisitionTraceOriginDriftRejects4m=0,acquisitionTraceRequestMutationRejects4m=0;`);
  x=r(x,'executableGateProbeCalls4l+=a.executableGateProbeCalls||0;executableGateProbe2xxJson4l+=a.executableGateProbe2xxJson||0;probeCacheHits4l+=a.probeCacheHits||0;probeNetworkFetches4l+=a.probeNetworkFetches||0;duplicateProbeNetworkFetches4l+=a.duplicateProbeNetworkFetches||0;',`executableGateProbeCalls4l+=a.executableGateProbeCalls||0;executableGateProbe2xxJson4l+=a.executableGateProbe2xxJson||0;probeCacheHits4l+=a.probeCacheHits||0;probeNetworkFetches4l+=a.probeNetworkFetches||0;duplicateProbeNetworkFetches4l+=a.duplicateProbeNetworkFetches||0;acquisitionTraceProbeCalls4m+=a.acquisitionTraceProbeCalls||0;acquisitionTraceProbe2xxJson4m+=a.acquisitionTraceProbe2xxJson||0;`);
  x=r(x,'executableGateRouteFamilyHypotheses4l+=sm.executableGateRouteFamilyHypotheses||0;',`executableGateRouteFamilyHypotheses4l+=sm.executableGateRouteFamilyHypotheses||0;acquisitionTraceEvents4m+=sm.acquisitionTraceEvents||0;acquisitionTraceDistinctUrls4m+=sm.acquisitionTraceDistinctUrls||0;acquisitionTraceEligible4m+=sm.acquisitionTraceEligible||0;acquisitionTraceRejectedAsset4m+=sm.acquisitionTraceRejectedAsset||0;acquisitionTraceRejectedNavigation4m+=sm.acquisitionTraceRejectedNavigation||0;acquisitionTraceRejectedDocumentation4m+=sm.acquisitionTraceRejectedDocumentation||0;acquisitionTraceRejectedLineage4m+=sm.acquisitionTraceRejectedLineage||0;acquisitionTraceRejectedAuthLike4m+=sm.acquisitionTraceRejectedAuthLike||0;acquisitionTraceExactBuildValueSlots4m+=sm.acquisitionTraceExactBuildValueSlots||0;acquisitionTraceFamilySlots4m+=sm.acquisitionTraceFamilySlots||0;acquisitionTraceEchoSupportedSlots4m+=sm.acquisitionTraceEchoSupportedSlots||0;acquisitionTraceHypotheses4m+=sm.acquisitionTraceHypotheses||0;`);
  x=r(x,'if(v.errors?.includes?.("4l_request_hypothesis_not_in_executable_graph"))validatorGraphMismatchRejects4h++;',`if(v.errors?.includes?.("4m_request_hypothesis_not_in_trace_graph"))validatorGraphMismatchRejects4h++;if(v.errors?.includes?.("4m_trace_origin_drift"))acquisitionTraceOriginDriftRejects4m++;if(v.errors?.includes?.("4m_trace_request_mutation"))acquisitionTraceRequestMutationRejects4m++;`);
  x=r(x,'if(a.parsed_json?.reason?.startsWith?.("4L_SUCCESSFUL_PROBE_MAPPING_REJECT"))successfulProbeMappingRejects4h++;','if(a.parsed_json?.reason?.startsWith?.("4M_SUCCESSFUL_PROBE_MAPPING_REJECT"))successfulProbeMappingRejects4h++;');

  x=r(x,'controls:controls.length,controls_verified:verifiedControls,benchmark_duration_ms:Date.now()-Date.parse(started_at)',`controls:controls.length,controls_verified:verifiedControls,benchmark_duration_ms:Date.now()-Date.parse(started_at),...acquisitionCacheMetrics4M()`);
  x=r(x,'executableGateConfirmedRecipes:routeFamilyConfirmedRecipes,probeCacheHits:probeCacheHits4l',`executableGateConfirmedRecipes:routeFamilyConfirmedRecipes,acquisitionTraceEvents:acquisitionTraceEvents4m,acquisitionTraceDistinctUrls:acquisitionTraceDistinctUrls4m,acquisitionTraceEligible:acquisitionTraceEligible4m,acquisitionTraceRejectedAsset:acquisitionTraceRejectedAsset4m,acquisitionTraceRejectedNavigation:acquisitionTraceRejectedNavigation4m,acquisitionTraceRejectedDocumentation:acquisitionTraceRejectedDocumentation4m,acquisitionTraceRejectedLineage:acquisitionTraceRejectedLineage4m,acquisitionTraceRejectedAuthLike:acquisitionTraceRejectedAuthLike4m,acquisitionTraceExactBuildValueSlots:acquisitionTraceExactBuildValueSlots4m,acquisitionTraceFamilySlots:acquisitionTraceFamilySlots4m,acquisitionTraceEchoSupportedSlots:acquisitionTraceEchoSupportedSlots4m,acquisitionTraceHypotheses:acquisitionTraceHypotheses4m,acquisitionTraceProbeCalls:acquisitionTraceProbeCalls4m,acquisitionTraceProbe2xxJson:acquisitionTraceProbe2xxJson4m,acquisitionTraceConfirmedRecipes:acquisitionTraceConfirmedRecipes,acquisitionTraceOriginDriftRejects:acquisitionTraceOriginDriftRejects4m,acquisitionTraceRequestMutationRejects:acquisitionTraceRequestMutationRejects4m,probeCacheHits:probeCacheHits4l`);

  x=r(x,'falseCharacterBooksRecipe=recipes.some(r=>r.case_id==="fictional_character_metadata"&&/(?:^|\\/)api\\/books(?:\\/|$)/i.test(String(r.contract?.path_template||""))),routeFamilyConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4l_executable_route_family_")).length,routeFamilyExpandedEvidenceRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4l_executable_route_family_")&&r.expanded_evidence_request).length;',`falseCharacterBooksRecipe=recipes.some(r=>r.case_id==="fictional_character_metadata"&&/(?:^|\\/)api\\/books(?:\\/|$)/i.test(String(r.contract?.path_template||""))),routeFamilyConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4l_executable_route_family_")).length,routeFamilyExpandedEvidenceRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4l_executable_route_family_")&&r.expanded_evidence_request).length,acquisitionTraceConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4m_executed_trace_")).length;`);
  x=r(x,'executable_route_family_confirmed_recipe:routeFamilyConfirmedRecipes>=1,duplicate_probe_network_fetches_zero:duplicateProbeNetworkFetches4l===0,',`acquisition_trace_confirmed_recipe:acquisitionTraceConfirmedRecipes>=1,duplicate_probe_network_fetches_zero:duplicateProbeNetworkFetches4l===0,duplicate_acquisition_network_fetches_zero:acquisitionCacheMetrics4M().duplicateAcquisitionNetworkFetches===0,duplicate_spec_probe_network_fetches_zero:acquisitionCacheMetrics4M().duplicateSpecProbeNetworkFetches===0,`);

  x=x.replaceAll('4L_EXECUTABLE_API_OPERATION_FAMILY:','4M_EXECUTED_ACQUISITION_TRACE:')
    .replaceAll('4L_SUCCESSFUL_PROBE_MAPPING_REJECT','4M_SUCCESSFUL_PROBE_MAPPING_REJECT')
    .replaceAll('GO_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING','GO_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF')
    .replaceAll('REASSESS_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING','REASSESS_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF');
  x=r(x,'experiment:"4L",purpose:"development_executable_api_operation_family_gating"','experiment:"4M",purpose:"development_executed_acquisition_trace_operation_proof"');
  x=r(x,'base_sha:"6681c0f681959597ab75d2130fa15c37d8b979fa"','base_sha:"a936218a82f8c38156dbef516c1271159b1b18c4"');
  x=x.replaceAll('./experiment4lPlanner.ts','./experiment4mPlanner.ts').replaceAll('./experiment4lRequest.ts','./experiment4mRequest.ts').replaceAll('./experiment4lContract.ts','./experiment4mContract.ts').replaceAll('./experiment4lDerivation.ts','./experiment4mDerivation.ts');
  return x;
}
