import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileEvidenceNativeSemantics4G,type Operation4G} from "./experiment4gSemantics.js";
import type {IrParameter} from "./experiment4fIr.js";
import {alignTaskOperation4H} from "./experiment4hAlignment.js";
const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const REQUIRED_AUTH_LOCAL=/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth).{0,100}(?:required|must|need|mandatory)|(?:required|must|need|mandatory).{0,100}(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i;
const GENERIC=new Set(["id","name","code","value","key","identifier"]);
function paramsFor(s:any,op:Operation4G){return op.parameter_ids.map((id:string)=>s.parameters.find((p:IrParameter)=>p.id===id)).filter(Boolean) as IrParameter[]}
function toks(v:string){return lexicalTokensP1(v)}
function stem(v:string){let s=v.replace(/([a-z0-9])([A-Z])/g,"$1_$2").replace(/[^a-z0-9]+/gi,"_").toLowerCase().replace(/^_+|_+$/g,"");for(const suffix of ["_identifier","_name","_code","_id"])if(s.endsWith(suffix)&&s.length>suffix.length){s=s.slice(0,-suffix.length);break}return s}
function support(caseId:string,op:Operation4G,s:any){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return 0;const opTokens=new Set(toks(`${op.title} ${s.ir.sections.find((x:any)=>x.id===op.section_id)?.title||""} ${op.path} ${op.context}`));const taskTokens=new Set(toks(`${c.intent} ${c.required.join(" ")}`));let n=0;for(const x of taskTokens)if(opTokens.has(x))n++;return n}
function sourceSectionText(evidence:DocEvidence[],s:any,op:Operation4G){const ev=evidence.find(e=>e.evidence_id===op.source.evidence_id);if(!ev)return "";const sec=s.ir.sections.find((x:any)=>x.id===op.section_id),raw=String(ev.text||"");return raw.slice(Math.max(0,sec?.start??op.source.start??0),Math.min(raw.length,sec?.end??op.source.end??raw.length))}
function pruneAuthQueryPreserving(path:string,metrics:any){const q=path.indexOf("?");if(q<0)return path;const head=path.slice(0,q),tail=path.slice(q+1),parts=tail.split("&"),kept:string[]=[];let pruned=0;for(const part of parts){const eq=part.indexOf("="),name=(eq<0?part:part.slice(0,eq));let decoded=name;try{decoded=decodeURIComponent(name.replace(/\+/g," "))}catch{}if(AUTH_NAME.test(decoded)){pruned++;continue}kept.push(part)}metrics.authPairsPrunedSurgically+=pruned;metrics.optionalAuthSlotsPruned+=pruned;const out=kept.length?`${head}?${kept.join("&")}`:head;if(out.replace(/\?.*$/,"")!==head)metrics.nonAuthRequestTextMutations++;return out}
function addStructuralSlot(caseId:string,s:any,op:Operation4G,params:IrParameter[],metrics:any){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c||c.input_names.length!==1)return null;const input=c.input_names[0],value=String(c.build[input]??""),sup=support(caseId,op,s);metrics.identifierRoleCandidates++;const named=params.find(p=>!p.auth_like&&(stem(p.name)===stem(input)||p.name.toLowerCase()===input.toLowerCase()));if(named){metrics.identifierRoleAcceptedNamedParameter++;return {binding:named.id,param:named,score:20}}
const placeholders=[...op.path.matchAll(/\{([^}]+)\}/g)];for(const m of placeholders){const label=m[1],generic=GENERIC.has(stem(label));if(stem(label)===stem(input)&&(!generic||sup>=2)){metrics.identifierRoleAcceptedPlaceholder++;const p:IrParameter={id:`4i_path_${fourAp1Sha({op:op.id,label}).slice(0,12)}`,name:label,in:"path",required:true,description:"documented placeholder",example:null,auth_like:false,source:op.source} as any;return {binding:p.id,param:p,score:18}}}
const lower=op.path.toLowerCase(),needle=value.toLowerCase(),first=lower.indexOf(needle);if(first>=0){if(lower.indexOf(needle,first+needle.length)>=0){metrics.identifierRoleRejectedAmbiguousOccurrence++;return null}const before=op.path.slice(0,first),after=op.path.slice(first+value.length);if(/^https?:\/\//i.test(op.path)&&first<op.path.indexOf("/",8)){metrics.identifierRoleRejectedNoSemanticSupport++;return null}if(sup<1){metrics.identifierRoleRejectedNoSemanticSupport++;return null}const label=`structural_${stem(input)||"value"}`,replacement=`{${label}}`,path=`${before}${replacement}${after}`,p:IrParameter={id:`4i_struct_${fourAp1Sha({op:op.id,input,first}).slice(0,12)}`,name:label,in:path.includes(`?`)&&first>path.indexOf("?")?"query":"path",required:true,description:"unique documented build value occurrence",example:value,auth_like:false,source:op.source} as any;metrics.identifierRoleAcceptedUniqueBuildValue++;return {binding:p.id,param:p,score:16,path}}
metrics.identifierRoleRejectedNoSemanticSupport++;return null}
function make(caseId:string,s:any,op:Operation4G,metrics:any,evidence:DocEvidence[]){metrics.alignmentCandidates++;const base=s.ir.api_bases.find((b:any)=>b.id===op.api_base_id);if(!base)return null;let params=paramsFor(s,op),path=op.path;const originalSection=sourceSectionText(evidence,s,op),localRequired=REQUIRED_AUTH_LOCAL.test(`${op.title} ${op.context}`)||REQUIRED_AUTH_LOCAL.test(originalSection);if(op.auth_class==="REQUIRED"||localRequired){metrics.requiredAuthSlotsBlocked+=params.filter(p=>p.auth_like).length||1;return null}let a=alignTaskOperation4H(caseId,s,op,params,metrics),structural:any=null;if(!a.accepted&&a.reason==="no_identifier"){structural=addStructuralSlot(caseId,s,op,params,metrics);if(!structural)return null;params=[...params,structural.param];path=structural.path||path;a=alignTaskOperation4H(caseId,s,{...op,path} as any,params,metrics);if(!a.accepted){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;a={accepted:true,bindings:{[c.input_names[0]]:structural.binding},score:10+structural.score,reason:"structural",signals:{identifier:1,entity:1,action:0,output:0,generic:false,concrete:true,morphology:false}} as any}}
if(!a.accepted)return null;const bound=new Set(Object.values(a.bindings)),safeParams:IrParameter[]=[];for(const p of params){if(!p.auth_like){safeParams.push(p);continue}if(bound.has(p.id)){metrics.identifierRoleRejectedAuthLike++;return null}if(["OPTIONAL","RATE_LIMIT_UPGRADE","UNRELATED","UNKNOWN"].includes(op.auth_class))continue;metrics.requiredAuthSlotsBlocked++;return null}
if(path.includes("{")){metrics.placeholderBearingOperations++;metrics.placeholderPreservationChecks++}const pruned=pruneAuthQueryPreserving(path,metrics);if(path.includes("{")&&!pruned.includes("{"))metrics.placeholderPreservationFailures++;const slots:P1RequestSlot[]=safeParams.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:false,literals:p.example!==null?[{id:`lit4i_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:p.example}]:[]})),literal_bindings:Record<string,string>={};for(const slot of slots){if(bound.has(slot.id))continue;if(slot.literals.length===1&&/json/i.test(slot.literals[0].value)&&/(?:format|response|output|type)/i.test(slot.name))literal_bindings[slot.id]=slot.literals[0].id}return{id:`req4i_${fourAp1Sha({op:op.id,base:base.id,path:pruned,input:a.bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:pruned,proof_type:`4i_structural_identifier_role_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings:a.bindings,literal_bindings,score:1000+a.score+(structural?40:0)+(op.source.expanded?30:0),concrete_relation:op.absolute_url===null} as P1RequestHypothesis}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let url="";try{url=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(url)}catch{return true}for(const [n] of u.searchParams)if(AUTH_NAME.test(n))return true;return h.slots.some(s=>s.auth_like)}
function buildGraph(evidence:DocEvidence[],caseId:string){const semantics=compileEvidenceNativeSemantics4G(evidence),metrics:any={...semantics.metrics,alignmentCandidates:0,alignmentAccepted:0,alignmentRejectedNoIdentifier:0,alignmentRejectedInsufficientSupport:0,alignmentRejectedGenericIdentifier:0,alignmentAcceptedByConcreteExample:0,alignmentAcceptedByMorphology:0,alignmentScoreHistogram:{},operationFrameCandidates:0,operationFrameWithIdentifierSignal:0,operationFrameWithEntitySignal:0,operationFrameWithActionSignal:0,operationFrameWithOutputSignal:0,optionalAuthSlotsPruned:0,requiredAuthSlotsBlocked:0,authLikeHypothesesRejectedBeforeRender:0,placeholderBearingOperations:0,placeholderPreservationChecks:0,placeholderPreservationFailures:0,authPairsPrunedSurgically:0,nonAuthRequestTextMutations:0,identifierRoleCandidates:0,identifierRoleAcceptedNamedParameter:0,identifierRoleAcceptedPlaceholder:0,identifierRoleAcceptedUniqueBuildValue:0,identifierRoleAcceptedQueryKey:0,identifierRoleAcceptedPathSegment:0,identifierRoleRejectedAmbiguousOccurrence:0,identifierRoleRejectedNoSemanticSupport:0,identifierRoleRejectedGeneric:0,identifierRoleRejectedAuthLike:0};const built=semantics.operations.map(op=>make(caseId,semantics,op,metrics,evidence)).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of built){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score);return{semantics,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4I(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),g=buildGraph(evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let authLikeRenderedRequests=0,duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return{...g,probe_packet:packet,metrics:{...g.metrics,...expansion,authLikeRenderedRequests,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0,expandedEvidenceHypotheses:g.hypotheses.filter(h=>g.semantics.operations.find(o=>o.id===h.source_operation_id)?.source.expanded).length}}}
export function rebuildRequestGraph4I(evidence:DocEvidence[],caseId:string){const g=buildGraph(evidence,caseId),hypotheses=g.hypotheses.filter(h=>!renderedAuthLike(h,caseId));return{...g,hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
