import {deriveExperiment4iSource} from "./experiment4iDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4j_anchor_missing:${a.slice(0,120)}`);return s.replace(a,b)}
export function deriveExperiment4jSource(source:string){let x=deriveExperiment4iSource(source);
x=r(x,'import {compile4i as compile4ar,project4i as project4ar,scope4i as scope4ar,validate4i as validate4ar,validateProjected4i as validateProjected4ar} from "./experiment4iContract.js";','import {compile4j as compile4ar,project4j as project4ar,scope4j as scope4ar,validate4j as validate4ar,validateProjected4j as validateProjected4ar} from "./experiment4jContract.js";');
x=r(x,'import {synthesize4i as synthesize4ar} from "./experiment4iPlanner.js";','import {synthesize4j as synthesize4ar} from "./experiment4jPlanner.js";');
x=r(x,'const OUT="results/experiment-4i",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4j",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'identifierRoleRejectedAuthLike4i=0;','identifierRoleRejectedAuthLike4i=0,contextualRoleCandidates4j=0,contextualRoleAcceptedExplicitLocalLabel4j=0,contextualRoleAcceptedGenericWithTwoSupports4j=0,contextualRoleAcceptedCrossExampleVariation4j=0,contextualRoleRejectedNoLocalRole4j=0,contextualRoleRejectedAmbiguousPosition4j=0,contextualRoleRejectedInsufficientSupport4j=0,contextualRoleRejectedAuthLike4j=0,entityTargetChecks4j=0,entityTargetAccepted4j=0,entityTargetRejectedMismatch4j=0,entityTargetRejectedNoEntityEvidence4j=0,wrongEntityProbeAttempts4j=0;');
x=r(x,'identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;','identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;contextualRoleCandidates4j+=sm.contextualRoleCandidates||0;contextualRoleAcceptedExplicitLocalLabel4j+=sm.contextualRoleAcceptedExplicitLocalLabel||0;contextualRoleAcceptedGenericWithTwoSupports4j+=sm.contextualRoleAcceptedGenericWithTwoSupports||0;contextualRoleAcceptedCrossExampleVariation4j+=sm.contextualRoleAcceptedCrossExampleVariation||0;contextualRoleRejectedNoLocalRole4j+=sm.contextualRoleRejectedNoLocalRole||0;contextualRoleRejectedAmbiguousPosition4j+=sm.contextualRoleRejectedAmbiguousPosition||0;contextualRoleRejectedInsufficientSupport4j+=sm.contextualRoleRejectedInsufficientSupport||0;contextualRoleRejectedAuthLike4j+=sm.contextualRoleRejectedAuthLike||0;entityTargetChecks4j+=sm.entityTargetChecks||0;entityTargetAccepted4j+=sm.entityTargetAccepted||0;entityTargetRejectedMismatch4j+=sm.entityTargetRejectedMismatch||0;entityTargetRejectedNoEntityEvidence4j+=sm.entityTargetRejectedNoEntityEvidence||0;wrongEntityProbeAttempts4j+=sm.wrongEntityProbeAttempts||0;');
x=r(x,'identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,schemaProbeCalls','identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,contextualRoleCandidates:contextualRoleCandidates4j,contextualRoleAcceptedExplicitLocalLabel:contextualRoleAcceptedExplicitLocalLabel4j,contextualRoleAcceptedGenericWithTwoSupports:contextualRoleAcceptedGenericWithTwoSupports4j,contextualRoleAcceptedCrossExampleVariation:contextualRoleAcceptedCrossExampleVariation4j,contextualRoleRejectedNoLocalRole:contextualRoleRejectedNoLocalRole4j,contextualRoleRejectedAmbiguousPosition:contextualRoleRejectedAmbiguousPosition4j,contextualRoleRejectedInsufficientSupport:contextualRoleRejectedInsufficientSupport4j,contextualRoleRejectedAuthLike:contextualRoleRejectedAuthLike4j,entityTargetChecks:entityTargetChecks4j,entityTargetAccepted:entityTargetAccepted4j,entityTargetRejectedMismatch:entityTargetRejectedMismatch4j,entityTargetRejectedNoEntityEvidence:entityTargetRejectedNoEntityEvidence4j,wrongEntityProbeAttempts:wrongEntityProbeAttempts4j,schemaProbeCalls');
x=x.replaceAll('4I_STRUCTURAL_IDENTIFIER_ROLE:','4J_CONTEXTUAL_IDENTIFIER_ROLE:').replaceAll('GO_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','GO_4J_CONTEXTUAL_IDENTIFIER_ROLE_TRANSFER').replaceAll('REASSESS_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','REASSESS_4J_CONTEXTUAL_IDENTIFIER_ROLE_TRANSFER');
x=r(x,'experiment:"4I",purpose:"development_structural_identifier_role_inference"','experiment:"4J",purpose:"development_contextual_identifier_role_transfer"');
x=r(x,'base_sha:"28c83671b4aa38bd87bf6ddefd540e1b5d6035c1"','base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"');
x=r(x,'wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,','wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,wrong_entity_probe_attempts_zero:wrongEntityProbeAttempts4j===0,');
return x}
