import {deriveExperiment5b8Source} from "./experiment5b8Derivation.js";
import {RECOVERY_CRAWL_5B9,RECOVERY_GLOBALS_5B9} from "./experiment5b9GeneratedFragments.js";

function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b9_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
function rr(s:string,re:RegExp,replace:(m:string,...args:any[])=>string,label:string){if(!re.test(s))throw new Error(`5b9_regex_anchor_missing:${label}`);re.lastIndex=0;return s.replace(re,replace)}
function replaceBetween(s:string,start:string,end:string,replacement:string){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);if(a<0||b<0)throw new Error(`5b9_range_anchor_missing:${start}`);return s.slice(0,a)+replacement+s.slice(b)}

export function deriveExperiment5b9Source(source:string){let x=deriveExperiment5b8Source(source);
 x='import {buildRecoveryLinkQueue5B9,httpsUpgradeCandidate5B9,recoveryLineageFingerprint5B9,recoveryLinkOrderingDeterminism5B9,recoverySurface5B9} from "./experiment5b9Recovery.js";\n'+x;
 x=r(x,'import {compile5b8 as compile4ar,project5b8 as project4ar,scope5b8 as scope4ar,validate5b8 as validate4ar,validateProjected5b8 as validateProjected4ar} from "./experiment5b8Contract.js";','import {compile5b9 as compile4ar,project5b9 as project4ar,scope5b9 as scope4ar,validate5b9 as validate4ar,validateProjected5b9 as validateProjected4ar} from "./experiment5b9Contract.js";');
 x=r(x,'import {synthesize5b8 as synthesize4ar} from "./.generated-experiment5b8Planner.js";','import {synthesize5b9 as synthesize4ar} from "./.generated-experiment5b9Planner.js";');
 x=r(x,'const OUT="results/experiment-5b8-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b9-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;\n'+RECOVERY_GLOBALS_5B9);
 x=replaceBetween(x,'async function crawl(provider:Provider4A,ledger:RecoveryLedger){','async function rerank(',RECOVERY_CRAWL_5B9);
 x=r(x,'for(const s of selected.slice(0,FOUR_A_BUDGET.max_provider_attempts_per_case)){if(!String(s.link).startsWith("https://")){attempts.push({candidate_id:s.candidate_id,name:s.name,status:"provider_ineligible",reason:"non_https_catalog_start"});continue;}const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:s.link},cr=await crawl(p,ledger),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence);','for(const s of selected.slice(0,FOUR_A_BUDGET.max_provider_attempts_per_case)){const originalStart=String(s.link),upgrade=originalStart.startsWith("http://")?httpsUpgradeCandidate5B9(originalStart):null,effectiveStart=originalStart.startsWith("https://")?originalStart:upgrade?.url??null;if(!effectiveStart){attempts.push({candidate_id:s.candidate_id,name:s.name,status:"provider_ineligible",reason:"non_https_catalog_start_not_upgradeable"});continue;}const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:effectiveStart},cr=await crawl5b9(p,ledger,originalStart),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence);if(cr.recovery?.became_executable&&syn.contract?.decision==="COMPILE")recoveryMetrics5b9.recoveryDerivedHypothesesEnteredBeam5b9++;');
 x=r(x,'provider_start_url:p.start_url,provider_selection_fingerprint:selectionFp,documentation_fingerprint:','provider_start_url:p.start_url,provider_catalog_start_url:originalStart,provider_selection_fingerprint:selectionFp,documentation_fingerprint:');
 x=r(x,'query_semantic_gate_witness_5b8:syn.query_semantic_gate_witness_5b8??null,contract,contract_fingerprint:sha3yr(contract)','query_semantic_gate_witness_5b8:syn.query_semantic_gate_witness_5b8??null,recovery_lineage_5b9:cr.recovery?.became_executable?cr.recovery.lineages:[],recovery_surface_witness_5b9:cr.recovery?.became_executable?cr.recovery.summary:null,contract,contract_fingerprint:sha3yr(contract)');
 x=rr(x,/const before=\{([^{}]*)\},replay:any\[\]=\[\];/,(m,inside)=>`const before={${inside},recoveryFetchAttempts5b9:recoveryMetrics5b9.recoveryFetchAttempts5b9},replay:any[]=[];`,'replay_before');
 x=rr(x,/replayDeltas=\{([^{}]*)\}/,(m,inside)=>`replayDeltas={${inside},recovery_fetches:recoveryMetrics5b9.recoveryFetchAttempts5b9-before.recoveryFetchAttempts5b9}`,'replay_deltas');
 x=r(x,'metrics:{cases:24,families:8,successful_manufactures:successful.length,','metrics:{...recoveryMetrics5b9,cases:24,families:8,successful_manufactures:successful.length,');
 x=r(x,'synthesisEvidence,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};','synthesisEvidence,recoveryLineage5b9,providerFetchAudit5b9,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};');
 x=x.replaceAll('experiment:"5B8-ENGINE"','experiment:"5B9-ENGINE"').replaceAll('purpose:"development_role_segmented_typed_operation_transfer_engine"','purpose:"development_verified_selected_provider_acquisition_recovery_engine"').replaceAll('base_sha:"3c946337f75079f22ab9b07d0a48d3fe574d9c98"','base_sha:"0abd49ebb2e4c081e1f92f0fb178b49091c7499e"');
 x=x.replaceAll('./experiment5b8Contract.ts','./experiment5b9Contract.ts').replaceAll('./experiment5b8Derivation.ts','./experiment5b9Derivation.ts');
 x=x.replace('(await readFile(new URL("./experiment5b8Gate.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b8Gate.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b9Recovery.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
 return x}
