import {deriveExperiment5b10PlannerSource} from "./experiment5b10PlannerDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b11_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b11PlannerSource(source:string){let x=deriveExperiment5b10PlannerSource(source);
 x='import {evidenceFaithfulTemplateFilter5B11} from "./experiment5b11Template.js";\n'+x;
 x=r(x,'const localized=localizeHypothesisEvidence5B5(originalAll,sectioned.sections,alignment,[...baseEvidence,...collection.capsules,...query.capsules],new Set());add(metrics,localized.metrics);metrics.sectionOrderingNondeterminismRejects5b5=Math.max(metrics.sectionOrderingNondeterminismRejects5b5,Number(localized.metrics.sectionOrderingNondeterminismRejects5b5||0));','const localized=localizeHypothesisEvidence5B5(originalAll,sectioned.sections,alignment,[...baseEvidence,...collection.capsules,...query.capsules],new Set());add(metrics,localized.metrics);metrics.sectionOrderingNondeterminismRejects5b5=Math.max(metrics.sectionOrderingNondeterminismRejects5b5,Number(localized.metrics.sectionOrderingNondeterminismRejects5b5||0));const template5b11=evidenceFaithfulTemplateFilter5B11(localized.hypotheses,c.build);add(metrics,template5b11.metrics);const plannerHypotheses5b11=template5b11.hypotheses;');
 x=r(x,'const historicalPrimary=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,det=requestOrderingDeterminism5B3(c,localized.hypotheses,localized.evidence,utilityProofById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B3(c,localized.hypotheses,localized.evidence,utilityProofById,historicalPrimary);','const historicalPrimary=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,det=requestOrderingDeterminism5B3(c,plannerHypotheses5b11,localized.evidence,utilityProofById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B3(c,plannerHypotheses5b11,localized.evidence,utilityProofById,historicalPrimary);');
 x=r(x,'const beam=dedup.slice(0,2);metrics.globalBeamSizeMax5b10=Math.max(metrics.globalBeamSizeMax5b10,beam.length);','const beam=dedup.slice(0,2);metrics.globalBeamSizeMax5b10=Math.max(metrics.globalBeamSizeMax5b10,beam.length);metrics.templateBeamEntries5b11=beam.filter((h:any)=>template5b11.witnesses.has(h.id)).length;');
 x=r(x,'for(let i=0;i<beam.length;i++){const h=beam[i],isNative=nativeProofById.has(h.id),isCollection=collectionProofById.has(h.id),isQuery=queryProofById.has(h.id),alignmentWitness=alignment.witnesses.get(h.id)||null,isRecovery5b10=recoveryDerivedIds5b10.has(h.id);if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;','for(let i=0;i<beam.length;i++){const h=beam[i],isNative=nativeProofById.has(h.id),isCollection=collectionProofById.has(h.id),isQuery=queryProofById.has(h.id),alignmentWitness=alignment.witnesses.get(h.id)||null,isRecovery5b10=recoveryDerivedIds5b10.has(h.id),templateWitness5b11=template5b11.witnesses.get(h.id)||null;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;if(templateWitness5b11)metrics.templateExecutedCandidates5b11=(metrics.templateExecutedCandidates5b11||0)+1;');
 x=r(x,'materialized.raw.recovery_candidate_witness_5b10=isRecovery5b10?{candidate_id:h.id,request_fingerprint:shape(h),beam_position:i+1,recovery_lineage_fingerprints:recoveryLineages5b10.map((z:any)=>z?.lineage_fingerprint).filter(Boolean),source_evidence_ids:[...recoveredEvidenceIds5b10],ranking_bonus:false}:null;if(isRecovery5b10)metrics.recoveryStrictRecipes5b10++;','materialized.raw.recovery_candidate_witness_5b10=isRecovery5b10?{candidate_id:h.id,request_fingerprint:shape(h),beam_position:i+1,recovery_lineage_fingerprints:recoveryLineages5b10.map((z:any)=>z?.lineage_fingerprint).filter(Boolean),source_evidence_ids:[...recoveredEvidenceIds5b10],ranking_bonus:false}:null;materialized.raw.template_witness_5b11=templateWitness5b11?{...templateWitness5b11,beam_position:i+1,request_fingerprint:shape(h)}:null;if(isRecovery5b10)metrics.recoveryStrictRecipes5b10++;if(templateWitness5b11)metrics.templateStrictRecipes5b11=(metrics.templateStrictRecipes5b11||0)+1;');
 x=x.replaceAll('export async function synthesize5b10','export async function synthesize5b11').replaceAll('5b10_unknown_case','5b11_unknown_case').replaceAll('5B10_BEAM_EXHAUSTED','5B11_BEAM_EXHAUSTED');
 return x}
