import {createHash} from "node:crypto";
import {extname} from "node:path";
import {isIP} from "node:net";
import {docScopeAllowed,type DocEvidence} from "./experiment3wCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {buildRequestHypothesesP1} from "./experiment4ap1Request.js";
import {extractOperationInventoryR6R} from "./experiment4ar6rEvidence.js";
import {buildGatedQueryHypotheses5B8} from "./experiment5b8Gate.js";

const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
const AUTH=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|app[_-]?id|appid|client[_-]?id|client[_-]?secret|password|passwd)$/i;
const MUTATION=/(?:^|\/)(?:create|delete|remove|update|write|insert|patch|upload|submit|mutate)(?:\/|$)/i;
const NOISE=/(?:^|\/)(?:login|signin|signup|register|account|pricing|careers?|jobs?|blog|news|privacy|terms|legal|press)(?:\/|$)/i;
const ASSET=new Set([".png",".jpg",".jpeg",".gif",".webp",".svg",".ico",".css",".js",".mjs",".map",".woff",".woff2",".ttf",".eot",".mp3",".mp4",".webm",".zip",".gz",".tgz",".exe",".dmg"]);
const POSITIVE:[RegExp,number,string][]= [
  [/\bopenapi\b/i,10,"openapi"],[/\bswagger\b/i,10,"swagger"],[/\b(?:schema|specification|spec)\b/i,7,"spec"],[/\bmachine[- ]?readable\b/i,7,"machine_readable"],
  [/\b(?:api\s+)?reference\b/i,6,"reference"],[/\bdocumentation\b/i,6,"documentation"],[/\bdocs?\b/i,5,"docs"],[/\bdeveloper\b/i,4,"developer"],[/\brest\b/i,4,"rest"],
  [/\bendpoints?\b/i,4,"endpoint"],[/\boperations?\b/i,3,"operation"],[/\bmethods?\b/i,2,"method"],[/\bjson\b/i,2,"json"],[/\byaml\b|\byml\b/i,2,"yaml"]
];
export type RecoveryLinkCandidate5B9={source_evidence_id:string;source_body_fingerprint:string;target_url:string;target_url_fingerprint:string;anchor_context_fingerprint:string;score:number;reasons:string[];depth:number;ordering_fingerprint:string};
export type RecoveryLinkMetrics5B9={recoveryLinkCandidates5b9:number;recoveryLinkAccepted5b9:number;recoveryLinkRejectedScope5b9:number;recoveryLinkRejectedNoise5b9:number;recoveryLinkAlreadyFetched5b9:number;recoveryLinkOrderingFingerprintCount5b9:number;recoveryLinkOrderingNondeterminismRejects5b9:number};
export type RecoverySurface5B9={get_operations:number;request_hypotheses:number;query_hypotheses:number;executable_hypotheses:number;fingerprint:string};
export function httpsUpgradeCandidate5B9(raw:string){try{const u=new URL(raw);if(u.protocol!=="http:"||u.username||u.password||isIP(u.hostname))return null;const before={host:u.hostname.toLowerCase(),path:u.pathname,search:u.search,port:u.port};u.protocol="https:";if(before.port==="80")u.port="";if(u.hostname.toLowerCase()!==before.host||u.pathname!==before.path||u.search!==before.search)return null;return {url:u.toString(),fingerprint:sha({kind:"scheme_only_https_upgrade",host:before.host,path:before.path,search:before.search,port_before:before.port,port_after:u.port})}}catch{return null}}
function explicitLinks(text:string){const re=/(?:href|src)\s*=\s*["']([^"']+)["']|<link\b[^>]*href\s*=\s*["']([^"']+)["']/gi,out:{href:string;offset:number}[]=[];let m;while((m=re.exec(text))){const href=String(m[1]||m[2]||"").trim();if(href)out.push({href,offset:m.index})}return out}
function safeTarget(base:string,href:string){if(!href||href.startsWith("#"))return null;try{let u=new URL(href,base);if(u.protocol==="http:"){const up=httpsUpgradeCandidate5B9(u.toString());if(!up)return null;u=new URL(up.url)}if(u.protocol!=="https:"||u.username||u.password||isIP(u.hostname))return null;u.hash="";return u}catch{return null}}
function noisy(u:URL){const p=u.pathname.toLowerCase();if(NOISE.test(p)||MUTATION.test(p)||ASSET.has(extname(p).toLowerCase()))return true;for(const k of u.searchParams.keys())if(AUTH.test(k))return true;return false}
function scoreCandidate(u:URL,context:string){const hay=`${u.pathname} ${u.search} ${context}`.toLowerCase();let score=0;const reasons:string[]=[];for(const [re,w,reason] of POSITIVE)if(re.test(hay)){score+=w;reasons.push(reason)}if(/\.(?:json|ya?ml)$/i.test(u.pathname)){score+=5;reasons.push("machine_readable_extension")}return {score,reasons:[...new Set(reasons)].sort()}}
export function buildRecoveryLinkQueue5B9(evidence:DocEvidence[],provider:Provider4A,seen:ReadonlySet<string>,depthByEvidence:ReadonlyMap<string,number>){const metrics:RecoveryLinkMetrics5B9={recoveryLinkCandidates5b9:0,recoveryLinkAccepted5b9:0,recoveryLinkRejectedScope5b9:0,recoveryLinkRejectedNoise5b9:0,recoveryLinkAlreadyFetched5b9:0,recoveryLinkOrderingFingerprintCount5b9:1,recoveryLinkOrderingNondeterminismRejects5b9:0},byUrl=new Map<string,RecoveryLinkCandidate5B9>();for(const e of evidence){if(e.state!=="ok")continue;const base=e.resolved_url||e.requested_url,depth=depthByEvidence.get(e.evidence_id)??0;for(const row of explicitLinks(e.text)){metrics.recoveryLinkCandidates5b9++;const u=safeTarget(base,row.href);if(!u){metrics.recoveryLinkRejectedNoise5b9++;continue}const target=u.toString();if(!docScopeAllowed(provider.start_url,target)){metrics.recoveryLinkRejectedScope5b9++;continue}if(seen.has(target)){metrics.recoveryLinkAlreadyFetched5b9++;continue}if(noisy(u)){metrics.recoveryLinkRejectedNoise5b9++;continue}const context=e.text.slice(Math.max(0,row.offset-220),Math.min(e.text.length,row.offset+420)).replace(/\s+/g," ").trim(),sc=scoreCandidate(u,context);if(sc.score<=0){metrics.recoveryLinkRejectedNoise5b9++;continue}const candidate:RecoveryLinkCandidate5B9={source_evidence_id:e.evidence_id,source_body_fingerprint:e.body_fingerprint,target_url:target,target_url_fingerprint:sha(target),anchor_context_fingerprint:sha(context),score:sc.score,reasons:sc.reasons,depth:depth+1,ordering_fingerprint:""},prior=byUrl.get(target);if(!prior||candidate.score>prior.score||candidate.source_evidence_id.localeCompare(prior.source_evidence_id)<0)byUrl.set(target,candidate)}}let queue=[...byUrl.values()].sort((a,b)=>b.score-a.score||a.target_url.localeCompare(b.target_url)||a.source_evidence_id.localeCompare(b.source_evidence_id));const ordering=sha(queue.map(x=>({url:x.target_url,score:x.score,reasons:x.reasons,source:x.source_evidence_id,depth:x.depth})));queue=queue.map(x=>({...x,ordering_fingerprint:ordering}));metrics.recoveryLinkAccepted5b9=queue.length;return {queue,metrics,fingerprint:ordering}}
export function recoveryLinkOrderingDeterminism5B9(evidence:DocEvidence[],provider:Provider4A,seen:ReadonlySet<string>,depthByEvidence:ReadonlyMap<string,number>){const a=buildRecoveryLinkQueue5B9(evidence,provider,seen,depthByEvidence),b=buildRecoveryLinkQueue5B9(evidence,provider,seen,depthByEvidence);return {ok:a.fingerprint===b.fingerprint&&JSON.stringify(a.queue)===JSON.stringify(b.queue),fingerprint:a.fingerprint}}
export function recoverySurface5B9(evidence:DocEvidence[],provider:Provider4A):RecoverySurface5B9{const inventory=extractOperationInventoryR6R(evidence,provider.case_id).inventory.filter(op=>op.method==="GET"),request=buildRequestHypothesesP1(evidence,provider.case_id).hypotheses,query=buildGatedQueryHypotheses5B8(evidence,provider).hypotheses,ids=new Set([...request.map(x=>x.id),...query.map(x=>x.id)]),base={get_operations:inventory.length,request_hypotheses:request.length,query_hypotheses:query.length,executable_hypotheses:ids.size};return {...base,fingerprint:sha(base)}}
export function recoveryLineageFingerprint5B9(row:any){return sha(row)}
