import {deriveExperiment4kSource} from "./experiment4kDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4l_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4lSource(source:string){
  let x=deriveExperiment4kSource(source);
  x=r(x,'import {compile4k as compile4ar,project4k as project4ar,scope4k as scope4ar,validate4k as validate4ar,validateProjected4k as validateProjected4ar} from "./experiment4kContract.js";','import {compile4l as compile4ar,project4l as project4ar,scope4l as scope4ar,validate4l as validate4ar,validateProjected4l as validateProjected4ar} from "./experiment4lContract.js";');
  x=r(x,'import {synthesize4k as synthesize4ar} from "./experiment4kPlanner.js";','import {synthesize4l as synthesize4ar} from "./experiment4lPlanner.js";');
  x=r(x,'const OUT="results/experiment-4k",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4l",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
  x=r(x,'routeFamilyProbeCalls4k=0,routeFamilyProbe2xxJson4k=0;',`routeFamilyProbeCalls4k=0,routeFamilyProbe2xxJson4k=0,
executableGateCandidates4l=0,executableGateAccepted4l=0,executableGateRejectedAsset4l=0,executableGateRejectedNavigation4l=0,executableGateRejectedDocumentation4l=0,executableGateRejectedNoPositiveSignal4l=0,executableGateAcceptedByOpenApi4l=0,executableGateAcceptedByExplicitRequest4l=0,executableGateAcceptedByEndpointLabel4l=0,executableGateAcceptedByResponseDataContext4l=0,executableGateAcceptedByApiBaseRelation4l=0,executableGateRouteFamilyHypotheses4l=0,executableGateProbeCalls4l=0,executableGateProbe2xxJson4l=0,probeCacheHits4l=0,probeNetworkFetches4l=0,duplicateProbeNetworkFetches4l=0;`);
  x=r(x,'routeFamilyProbeCalls4k+=a.routeFamilyProbeCalls||0;routeFamilyProbe2xxJson4k+=a.routeFamilyProbe2xxJson||0;',`routeFamilyProbeCalls4k+=a.routeFamilyProbeCalls||0;routeFamilyProbe2xxJson4k+=a.routeFamilyProbe2xxJson||0;executableGateProbeCalls4l+=a.executableGateProbeCalls||0;executableGateProbe2xxJson4l+=a.executableGateProbe2xxJson||0;probeCacheHits4l+=a.probeCacheHits||0;probeNetworkFetches4l+=a.probeNetworkFetches||0;duplicateProbeNetworkFetches4l+=a.duplicateProbeNetworkFetches||0;`);
  x=r(x,'routeFamilyHypotheses4k+=sm.routeFamilyHypotheses||0;',`routeFamilyHypotheses4k+=sm.routeFamilyHypotheses||0;executableGateCandidates4l+=sm.executableGateCandidates||0;executableGateAccepted4l+=sm.executableGateAccepted||0;executableGateRejectedAsset4l+=sm.executableGateRejectedAsset||0;executableGateRejectedNavigation4l+=sm.executableGateRejectedNavigation||0;executableGateRejectedDocumentation4l+=sm.executableGateRejectedDocumentation||0;executableGateRejectedNoPositiveSignal4l+=sm.executableGateRejectedNoPositiveSignal||0;executableGateAcceptedByOpenApi4l+=sm.executableGateAcceptedByOpenApi||0;executableGateAcceptedByExplicitRequest4l+=sm.executableGateAcceptedByExplicitRequest||0;executableGateAcceptedByEndpointLabel4l+=sm.executableGateAcceptedByEndpointLabel||0;executableGateAcceptedByResponseDataContext4l+=sm.executableGateAcceptedByResponseDataContext||0;executableGateAcceptedByApiBaseRelation4l+=sm.executableGateAcceptedByApiBaseRelation||0;executableGateRouteFamilyHypotheses4l+=sm.executableGateRouteFamilyHypotheses||0;`);
  x=r(x,'routeFamilyConfirmedRecipes:routeFamilyConfirmedRecipes,routeFamilyExpandedEvidenceRecipes:routeFamilyExpandedEvidenceRecipes,schemaProbeCalls',`routeFamilyConfirmedRecipes:routeFamilyConfirmedRecipes,routeFamilyExpandedEvidenceRecipes:routeFamilyExpandedEvidenceRecipes,executableGateCandidates:executableGateCandidates4l,executableGateAccepted:executableGateAccepted4l,executableGateRejectedAsset:executableGateRejectedAsset4l,executableGateRejectedNavigation:executableGateRejectedNavigation4l,executableGateRejectedDocumentation:executableGateRejectedDocumentation4l,executableGateRejectedNoPositiveSignal:executableGateRejectedNoPositiveSignal4l,executableGateAcceptedByOpenApi:executableGateAcceptedByOpenApi4l,executableGateAcceptedByExplicitRequest:executableGateAcceptedByExplicitRequest4l,executableGateAcceptedByEndpointLabel:executableGateAcceptedByEndpointLabel4l,executableGateAcceptedByResponseDataContext:executableGateAcceptedByResponseDataContext4l,executableGateAcceptedByApiBaseRelation:executableGateAcceptedByApiBaseRelation4l,executableGateRouteFamilyHypotheses:executableGateRouteFamilyHypotheses4l,executableGateProbeCalls:executableGateProbeCalls4l,executableGateProbe2xxJson:executableGateProbe2xxJson4l,executableGateConfirmedRecipes:routeFamilyConfirmedRecipes,probeCacheHits:probeCacheHits4l,probeNetworkFetches:probeNetworkFetches4l,duplicateProbeNetworkFetches:duplicateProbeNetworkFetches4l,schemaProbeCalls`);
  x=r(x,'controls:controls.length,controls_verified:verifiedControls','controls:controls.length,controls_verified:verifiedControls,benchmark_duration_ms:Date.now()-Date.parse(started_at)');
  x=r(x,'route_family_confirmed_recipe:routeFamilyConfirmedRecipes>=1,','executable_route_family_confirmed_recipe:routeFamilyConfirmedRecipes>=1,duplicate_probe_network_fetches_zero:duplicateProbeNetworkFetches4l===0,');
  x=x.replaceAll('4K_ROUTE_FAMILY_VARIABLE_SLOT:','4L_EXECUTABLE_API_OPERATION_FAMILY:')
    .replaceAll('4K_SUCCESSFUL_PROBE_MAPPING_REJECT','4L_SUCCESSFUL_PROBE_MAPPING_REJECT')
    .replaceAll('4k_request_hypothesis_not_in_route_family_graph','4l_request_hypothesis_not_in_executable_graph')
    .replaceAll('GO_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION','GO_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING')
    .replaceAll('REASSESS_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION','REASSESS_4L_EXECUTABLE_API_OPERATION_FAMILY_GATING')
    .replaceAll('4k_route_family_','4l_executable_route_family_');
  x=r(x,'experiment:"4K",purpose:"development_route_family_variable_slot_induction"','experiment:"4L",purpose:"development_executable_api_operation_family_gating"');
  x=r(x,'base_sha:"93b3aef43f0c35657bc222629ce85fb9d22fad95"','base_sha:"6681c0f681959597ab75d2130fa15c37d8b979fa"');
  x=x.replaceAll('./experiment4kPlanner.ts','./experiment4lPlanner.ts').replaceAll('./experiment4kRequest.ts','./experiment4lRequest.ts').replaceAll('./experiment4kContract.ts','./experiment4lContract.ts').replaceAll('./experiment4kDerivation.ts','./experiment4lDerivation.ts');
  return x;
}
