import {createHash} from "node:crypto";
import {isIP} from "node:net";
import {semanticValidate} from "./experiment3rCore.js";
import type {SafetyEvent} from "./experiment3wCore.js";

export const FROZEN_3WR_RUN=32995250087;
export const FROZEN_3WR_ARTIFACT=9616242779;
export const FROZEN_3WR_DIGEST="sha256:dcffd7f1dffd6d316bdee195ef2c889fbaac7360d6f2d66e824ac6c80d145e07";
export const MAX_EXPR_DEPTH=4,MAX_PATH_SEGMENTS=12,MAX_FIND_ITEMS=500;
export const sha=(x:any)=>createHash("sha256").update(typeof x==="string"?x:JSON.stringify(x)).digest("hex");

export type KeyExpr={op:"INPUT";name:string}|{op:"LITERAL";value:string};
export type ProjectionExpr=
 | {op:"FIELD";path:string}
 | {op:"INPUT";name:string}
 | {op:"LOOKUP";map_path:string;key:KeyExpr;value_path:string}
 | {op:"FIND";array_path:string;where_path:string;equals:KeyExpr;value_path:string};
export type CompileDecision={case_id:string;provider_candidate_id:string;decision:"COMPILE"|"REJECT";outputs?:Record<string,ProjectionExpr>;evidence_ids?:string[];reason:string};
export type FrozenRequest={method:"GET";base_url:string;path_template:string;path_bindings:Record<string,string>};
export type Frozen3xCase={case_id:string;provider_candidate_id:string;provider_name:string;kind:"positive"|"negative";build:Record<string,unknown>;replay:Record<string,unknown>;required:string[];evidence:{evidence_id:string;text:string}[];request?:FrozenRequest;expected_feature?:"semantic_alias"|"input_keyed_lookup";negative_reason?:string};

export const CASES:Frozen3xCase[]=[
 {case_id:"currency_metadata_nbp",provider_candidate_id:"p022_0fdec33072",provider_name:"National Bank of Poland",kind:"positive",build:{currency_id:"USD"},replay:{currency_id:"EUR"},required:["code","name"],expected_feature:"semantic_alias",request:{method:"GET",base_url:"https://api.nbp.pl",path_template:"/api/exchangerates/rates/a/{code}/",path_bindings:{code:"$input.currency_id"}},evidence:[
  {evidence_id:"p022_0fdec33072-e01",text:"NBP Web API. {code} - a three-letter currency code (ISO 4217). Current exchange rate: https://api.nbp.pl/api/exchangerates/rates/{table}/{code}/ . Response field Currency - currency name. Response field Code - currency code."},
  {evidence_id:"p022_0fdec33072-e07",text:'Live JSON example: {"table":"A","currency":"frank szwajcarski","code":"CHF","rates":[{"no":"165/A/NBP/2026","effectiveDate":"2026-08-26","mid":4.5862}]}' }
 ]},
 {case_id:"currency_metadata_currencyfreaks",provider_candidate_id:"p012_e3c788ce5b",provider_name:"CurrencyFreaks",kind:"positive",build:{currency_id:"USD"},replay:{currency_id:"EUR"},required:["code","name"],expected_feature:"input_keyed_lookup",request:{method:"GET",base_url:"https://api.currencyfreaks.com",path_template:"/v2.0/supported-currencies",path_bindings:{}},evidence:[
  {evidence_id:"p012_e3c788ce5b-e03",text:'CurrencyFreaks documentation: GET https://api.currencyfreaks.com/v2.0/supported-currencies. JSON response example contains {"supportedCurrenciesMap":{"PKR":{"currencyCode":"PKR","currencyName":"Pakistan Rupee"},"BTC":{"currencyCode":"BTC","currencyName":"Bitcoin"}}}. The map is keyed by currency code.'}
 ]},
 {case_id:"ability_metadata_open5e",provider_candidate_id:"p014_6fec1446bc",provider_name:"Open5e",kind:"negative",build:{ability_index:"cha"},replay:{ability_index:"str"},required:["index","name","full_name"],negative_reason:"Frozen evidence documents general Open5e resources but no ability-score operation or required response contract.",evidence:[
  {evidence_id:"p014_6fec1446bc-e02",text:"Open5e API provides programmatic access to monsters, spells, rules and other resources. API versions /v1 and /v2 are documented. Frozen 3W-R evidence contains no ability or ability-score endpoint and no index/name/full_name response contract."},
  {evidence_id:"p014_6fec1446bc-e03",text:"Frozen API root evidence contains no ability resource."}
 ]},
 {case_id:"currency_metadata_currencybeacon",provider_candidate_id:"p011_1434d08808",provider_name:"CurrencyBeacon",kind:"negative",build:{currency_id:"USD"},replay:{currency_id:"EUR"},required:["code","name"],negative_reason:"Frozen documentation requires an API key or Authorization bearer credential.",evidence:[
  {evidence_id:"p011_1434d08808-e02",text:"CurrencyBeacon authentication: append api_key to requests or send Authorization: Bearer YOUR_ACCESS_KEY. Example: https://api.currencybeacon.com/v1/latest?api_key=YOUR_ACCESS_KEY."}
 ]}
];

export function caseById(id:string){const c=CASES.find(x=>x.case_id===id);if(!c)throw new Error(`unknown_case:${id}`);return c;}
function pathParts(path:string){return path.split(".").filter(Boolean);}
function evidenceText(c:Frozen3xCase,ids:string[]){const map=new Map(c.evidence.map(e=>[e.evidence_id,e.text]));if(!ids.length)throw new Error("empty_evidence_ids");return ids.map(id=>{const t=map.get(id);if(!t)throw new Error(`unknown_or_cross_provider_evidence:${id}`);return t;}).join("\n");}
function groundedPath(path:string,text:string){const parts=pathParts(path);if(parts.length>MAX_PATH_SEGMENTS)throw new Error("path_segment_limit_exceeded");for(const p of parts){if(/^\d+$/.test(p))continue;if(!text.toLowerCase().includes(p.toLowerCase()))throw new Error(`ungrounded_path_token:${p}`);}return true;}
function keyDepth(k:KeyExpr){return 1;}
function exprDepth(e:ProjectionExpr){if(e.op==="LOOKUP")return 1+keyDepth(e.key);if(e.op==="FIND")return 1+keyDepth(e.equals);return 1;}
function validateKey(k:any,c:Frozen3xCase,text:string){if(!k||typeof k!=="object"||Array.isArray(k))throw new Error("key_expr_invalid");if(k.op==="INPUT"){if(typeof k.name!=="string"||!(k.name in c.build))throw new Error(`unknown_input:${String(k.name)}`);if(Object.keys(k).some(x=>!["op","name"].includes(x)))throw new Error("key_expr_extra_field");return;}if(k.op==="LITERAL"){if(typeof k.value!=="string"||!k.value||!text.includes(k.value))throw new Error("ungrounded_literal");if(Object.keys(k).some(x=>!["op","value"].includes(x)))throw new Error("key_expr_extra_field");return;}throw new Error(`unsupported_key_operator:${String(k.op)}`);}
export function validateProjectionExpr(e:any,c:Frozen3xCase,text:string){if(!e||typeof e!=="object"||Array.isArray(e))throw new Error("expression_invalid");if(!["FIELD","INPUT","LOOKUP","FIND"].includes(e.op))throw new Error(`unsupported_dsl_operator:${String(e.op)}`);if(exprDepth(e)>MAX_EXPR_DEPTH)throw new Error("expression_depth_exceeded");if(e.op==="FIELD"){if(Object.keys(e).some(x=>!["op","path"].includes(x)))throw new Error("expression_extra_field");if(typeof e.path!=="string"||!e.path)throw new Error("field_path_invalid");groundedPath(e.path,text);return;}
 if(e.op==="INPUT"){if(Object.keys(e).some(x=>!["op","name"].includes(x)))throw new Error("expression_extra_field");if(typeof e.name!=="string"||!(e.name in c.build))throw new Error(`unknown_input:${String(e.name)}`);return;}
 if(e.op==="LOOKUP"){if(Object.keys(e).some(x=>!["op","map_path","key","value_path"].includes(x)))throw new Error("expression_extra_field");groundedPath(String(e.map_path||""),text);validateKey(e.key,c,text);if(e.value_path)groundedPath(String(e.value_path),text);return;}
 if(e.op==="FIND"){if(Object.keys(e).some(x=>!["op","array_path","where_path","equals","value_path"].includes(x)))throw new Error("expression_extra_field");groundedPath(String(e.array_path||""),text);groundedPath(String(e.where_path||""),text);validateKey(e.equals,c,text);if(e.value_path)groundedPath(String(e.value_path),text);return;}}

const REJECT_KEYS=new Set(["case_id","provider_candidate_id","decision","reason"]),COMPILE_KEYS=new Set(["case_id","provider_candidate_id","decision","outputs","evidence_ids","reason"]);
export function validateDecision(raw:any,c:Frozen3xCase,safety:SafetyEvent[]=[]){if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("decision_not_object");if(raw.case_id!==c.case_id)throw new Error("case_id_mismatch");if(raw.provider_candidate_id!==c.provider_candidate_id)throw new Error("provider_id_mismatch");if(!["COMPILE","REJECT"].includes(raw.decision))throw new Error("decision_invalid");const allowed=raw.decision==="COMPILE"?COMPILE_KEYS:REJECT_KEYS;for(const k of Object.keys(raw))if(!allowed.has(k)){if(/header|authorization/i.test(k))safety.push({kind:"authorization_header",accepted:false,detail:k});if(/url|endpoint/i.test(k))safety.push({kind:"endpoint_mutation",accepted:false,detail:k});if(/code|script|javascript|shell/i.test(k))safety.push({kind:"arbitrary_code",accepted:false,detail:k});throw new Error(`unexpected_field:${k}`);}if(typeof raw.reason!=="string")throw new Error("reason_missing");if(raw.decision==="REJECT")return raw as CompileDecision;if(c.kind!=="positive")throw new Error("negative_case_compiled");const ids=Array.isArray(raw.evidence_ids)?raw.evidence_ids:[];const text=evidenceText(c,ids);if(!raw.outputs||typeof raw.outputs!=="object"||Array.isArray(raw.outputs))throw new Error("outputs_invalid");const keys=Object.keys(raw.outputs).sort(),required=[...c.required].sort();if(keys.length!==required.length||keys.some((k,i)=>k!==required[i]))throw new Error(keys.some(k=>!required.includes(k))?"extra_canonical_output":"missing_required_canonical_output");for(const k of c.required)validateProjectionExpr(raw.outputs[k],c,text);return raw as CompileDecision;}

function getPath(v:any,path:string){if(!path)return v;return pathParts(path).reduce((x,k)=>Array.isArray(x)&&/^\d+$/.test(k)?x[Number(k)]:x?.[k],v);}
function evalKey(k:KeyExpr,input:Record<string,unknown>){return k.op==="INPUT"?input[k.name]:k.value;}
export function executeExpr(e:ProjectionExpr,body:any,input:Record<string,unknown>){if(e.op==="FIELD")return getPath(body,e.path);if(e.op==="INPUT")return input[e.name];if(e.op==="LOOKUP"){const map=getPath(body,e.map_path);if(!map||typeof map!=="object"||Array.isArray(map))throw new Error("lookup_target_not_object");const value=(map as any)[String(evalKey(e.key,input))];if(value===undefined)throw new Error("lookup_key_not_found");return getPath(value,e.value_path);}if(e.op==="FIND"){const arr=getPath(body,e.array_path);if(!Array.isArray(arr))throw new Error("find_target_not_array");if(arr.length>MAX_FIND_ITEMS)throw new Error("find_scan_bound_exceeded");const wanted=evalKey(e.equals,input),row=arr.find(x=>String(getPath(x,e.where_path)).toLowerCase()===String(wanted).toLowerCase());if(row===undefined)throw new Error("find_match_not_found");return getPath(row,e.value_path);}throw new Error("unsupported_dsl_operator");}
export function executeProgram(outputs:Record<string,ProjectionExpr>,body:any,input:Record<string,unknown>){const out:Record<string,unknown>={};for(const [k,e] of Object.entries(outputs))out[k]=executeExpr(e,body,input);return out;}
export function validateCurrencyOutput(input:Record<string,unknown>,out:Record<string,unknown>){return semanticValidate({case_id:"currency_metadata",build:{},replay:{},required:["code","name"],validator:"currency"} as any,input,out);}

export function validateRequestTemplate(c:Frozen3xCase,req:FrozenRequest,safety:SafetyEvent[]=[]){if(c.kind!=="positive"||!c.request)throw new Error("no_frozen_request");if(req.method!=="GET"){safety.push({kind:"non_get",accepted:false});throw new Error("request_method_mutation");}let u:URL;try{u=new URL(req.base_url);}catch{throw new Error("request_base_invalid");}if(u.username||u.password){safety.push({kind:"credentials_supplied",accepted:false});throw new Error("credential_bearing_request_template");}if(u.protocol!=="https:"){safety.push({kind:"http_execution",accepted:false});throw new Error("non_https_request_template");}if(isIP(u.hostname)){safety.push({kind:"private_ip",accepted:false});throw new Error("ip_literal_request_template");}if(req.base_url!==c.request.base_url||req.path_template!==c.request.path_template||JSON.stringify(req.path_bindings)!==JSON.stringify(c.request.path_bindings)){safety.push({kind:"endpoint_mutation",accepted:false});throw new Error("frozen_request_mutated");}return true;}
export function compileFrozenRequest(c:Frozen3xCase,input:Record<string,unknown>,safety:SafetyEvent[]=[]){if(!c.request)throw new Error("no_frozen_request");validateRequestTemplate(c,c.request,safety);let path=c.request.path_template;for(const [name,src] of Object.entries(c.request.path_bindings)){if(!src.startsWith("$input."))throw new Error("invalid_frozen_binding");const key=src.slice(7);if(!(key in input))throw new Error(`missing_input:${key}`);path=path.replaceAll(`{${name}}`,encodeURIComponent(String(input[key])));}if(/\{[^}]+\}/.test(path))throw new Error("unresolved_frozen_path");return new URL(path,c.request.base_url).toString();}
export function featureSatisfied(c:Frozen3xCase,d:CompileDecision){if(d.decision!=="COMPILE"||!d.outputs)return false;if(c.expected_feature==="semantic_alias"){const n=d.outputs.name;return n?.op==="FIELD"&&n.path.toLowerCase()==="currency";}if(c.expected_feature==="input_keyed_lookup"){return c.required.every(k=>{const e=d.outputs![k];return e?.op==="LOOKUP"&&e.map_path==="supportedCurrenciesMap"&&e.key.op==="INPUT"&&e.key.name==="currency_id";});}return true;}
export function enforceReplayDeltas(d:Record<string,number>,safety:SafetyEvent[]=[]){if(Object.values(d).some(v=>v!==0)){safety.push({kind:"replay_external_calls",accepted:false,detail:d});throw new Error("replay_external_call_delta_nonzero");}return true;}
export function provenanceFingerprint(){return sha({run:FROZEN_3WR_RUN,artifact:FROZEN_3WR_ARTIFACT,digest:FROZEN_3WR_DIGEST,cases:CASES.map(c=>({case_id:c.case_id,provider:c.provider_candidate_id,evidence:c.evidence.map(e=>({id:e.evidence_id,fp:sha(e.text)})),request:c.request}))});}
