import {deriveExperiment5b11PlannerSource} from "./experiment5b11PlannerDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b12_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b12PlannerSource(source:string){let x=deriveExperiment5b11PlannerSource(source);
 x='import {buildDocumentaryRequestHypotheses5B12} from "./experiment5b12Documentary.js";\n'+x;
 x=r(x,'const linked=await ingestLinkedContracts4S(evidence,provider,ledger),baseEvidence=[...evidence,...linked.evidence],request=await prepareRequestGraph4Q(baseEvidence,provider.case_id,provider.candidate_id,ledger),native=await buildNativeHypotheses5B(baseEvidence,provider,ledger),collection=buildStructuredCollectionHypotheses5B4(baseEvidence,provider),query=buildQueryHypotheses5B6(baseEvidence,provider);add(metrics,linked.metrics);add(metrics,native.metrics);add(metrics,collection.metrics);add(metrics,query.metrics);','const linked=await ingestLinkedContracts4S(evidence,provider,ledger),baseEvidence=[...evidence,...linked.evidence],documentary=buildDocumentaryRequestHypotheses5B12(baseEvidence,provider,c),request=await prepareRequestGraph4Q(baseEvidence,provider.case_id,provider.candidate_id,ledger),native=await buildNativeHypotheses5B(baseEvidence,provider,ledger),collection=buildStructuredCollectionHypotheses5B4(baseEvidence,provider),query=buildQueryHypotheses5B6(baseEvidence,provider);add(metrics,linked.metrics);add(metrics,documentary.metrics);add(metrics,native.metrics);add(metrics,collection.metrics);add(metrics,query.metrics);');
 x=r(x,'const originalAll=[...(request.probe_packet||[]),...(native.hypotheses||[]),...(collection.hypotheses||[]),...(query.hypotheses||[])],alignment=','const originalAll=[...(documentary.hypotheses||[]),...(request.probe_packet||[]),...(native.hypotheses||[]),...(collection.hypotheses||[]),...(query.hypotheses||[])],alignment=');
 x=r(x,'const nativeProofById=new Map((native.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),collectionProofById=new Map((collection.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),queryProofById=new Map((query.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),sectionById=new Map(sectioned.sections.map(s=>[s.section_id,s]));','const nativeProofById=new Map((native.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),collectionProofById=new Map((collection.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),queryProofById=new Map((query.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),documentaryWitnessById=documentary.witnesses,sectionById=new Map(sectioned.sections.map(s=>[s.section_id,s]));');
 x=r(x,'if((sid&&recoveredEvidenceIds5b10.has(sid))||(sfp&&recoveredBodyFps5b10.has(sfp)))recoveryDerivedIds5b10.add(h.id)','if((sid&&recoveredEvidenceIds5b10.has(sid))||(sfp&&recoveredBodyFps5b10.has(sfp))||(h.evidence_ids||[]).some((id:string)=>recoveredEvidenceIds5b10.has(String(id))))recoveryDerivedIds5b10.add(h.id)');
 x=r(x,'metrics.templateBeamEntries5b11=beam.filter((h:any)=>template5b11.witnesses.has(h.id)).length;','metrics.templateBeamEntries5b11=beam.filter((h:any)=>template5b11.witnesses.has(h.id)).length;metrics.documentaryBeamEntries5b12=beam.filter((h:any)=>documentaryWitnessById.has(h.id)).length;');
 x=r(x,'templateWitness5b11=template5b11.witnesses.get(h.id)||null;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;if(templateWitness5b11)metrics.templateExecutedCandidates5b11=(metrics.templateExecutedCandidates5b11||0)+1;','templateWitness5b11=template5b11.witnesses.get(h.id)||null,documentaryWitness5b12=documentaryWitnessById.get(h.id)||null;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;if(templateWitness5b11)metrics.templateExecutedCandidates5b11=(metrics.templateExecutedCandidates5b11||0)+1;if(documentaryWitness5b12)metrics.documentaryExecutedCandidates5b12=(metrics.documentaryExecutedCandidates5b12||0)+1;');
 x=r(x,'metrics.requestFirstTransport2xx5b+=transport?1:0;metrics.requestFirstStructured2xx5b+=structured?1:0;if(!structured)continue;','metrics.requestFirstTransport2xx5b+=transport?1:0;metrics.requestFirstStructured2xx5b+=structured?1:0;if(documentaryWitness5b12){metrics.documentaryTransport2xx5b12=(metrics.documentaryTransport2xx5b12||0)+(transport?1:0);metrics.documentaryStructured2xx5b12=(metrics.documentaryStructured2xx5b12||0)+(structured?1:0);}if(!structured)continue;');
 x=r(x,'materialized.raw.template_witness_5b11=templateWitness5b11?{...templateWitness5b11,beam_position:i+1,request_fingerprint:shape(h)}:null;if(isRecovery5b10)metrics.recoveryStrictRecipes5b10++;if(templateWitness5b11)metrics.templateStrictRecipes5b11=(metrics.templateStrictRecipes5b11||0)+1;','materialized.raw.template_witness_5b11=templateWitness5b11?{...templateWitness5b11,beam_position:i+1,request_fingerprint:shape(h)}:null;materialized.raw.documentary_witness_5b12=documentaryWitness5b12?{...documentaryWitness5b12,beam_position:i+1,request_fingerprint:shape(h),rendered_build_url:row?.proof?.record?.requested_url||null}:null;if(isRecovery5b10)metrics.recoveryStrictRecipes5b10++;if(templateWitness5b11)metrics.templateStrictRecipes5b11=(metrics.templateStrictRecipes5b11||0)+1;if(documentaryWitness5b12)metrics.documentaryStrictRecipes5b12=(metrics.documentaryStrictRecipes5b12||0)+1;');
 x=r(x,'selected={row,h,isNative,isCollection,isQuery,materialized,responseWitness,semantic,locked,rawD,alignmentWitness};break','selected={row,h,isNative,isCollection,isQuery,materialized,responseWitness,semantic,locked,rawD,alignmentWitness,documentaryWitness5b12};break');
 x=r(x,'const {row,h,isNative,isCollection,isQuery,materialized,responseWitness,semantic,locked,rawD,alignmentWitness}=selected;return {','const {row,h,isNative,isCollection,isQuery,materialized,responseWitness,semantic,locked,rawD,alignmentWitness,documentaryWitness5b12}=selected;return {');
 x=r(x,'query_operation_witness_5b6:materialized.raw.query_operation_witness_5b6,...common}','query_operation_witness_5b6:materialized.raw.query_operation_witness_5b6,documentary_witness_5b12:materialized.raw.documentary_witness_5b12,selected_from_documentary_5b12:!!documentaryWitness5b12,...common}');
 x=x.replaceAll('export async function synthesize5b11','export async function synthesize5b12').replaceAll('5b11_unknown_case','5b12_unknown_case').replaceAll('5B11_BEAM_EXHAUSTED','5B12_BEAM_EXHAUSTED');
 return x}
