import {deriveExperiment5b18Source} from "./experiment5b18Derivation.js";

function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b19_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}

export function deriveExperiment5b19Source(source:string){let x=deriveExperiment5b18Source(source);
 x=x.replace('import {authLikeRenderedUrl5b18,frozenAttemptOrderingFingerprint5b18,frozenCandidatesForCase5b18,independentPrimaryDomain5b18,loadFiveB18Workload,resolveFrozenCandidates5b18} from "./experiment5b18Workload.js";','import {authLikeRenderedUrl5b19,frozenAttemptOrderingFingerprint5b19,frozenCandidatesForCase5b19,independentPrimaryDomain5b19,loadFiveB19Workload,resolveFrozenCandidates5b19} from "./experiment5b19Workload.js";');
 x=x.replace('import {synthesize5b14 as synthesize4ar} from "./.generated-experiment5b14Planner.js";','import {synthesize5b19 as synthesize4ar} from "./.generated-experiment5b19Planner.js";');
 x=x.replaceAll('frozen5b18','frozen5b19').replaceAll('resolved5b18','resolved5b19').replaceAll('loadFiveB18Workload','loadFiveB19Workload').replaceAll('resolveFrozenCandidates5b18','resolveFrozenCandidates5b19').replaceAll('frozenCandidatesForCase5b18','frozenCandidatesForCase5b19').replaceAll('frozenAttemptOrderingFingerprint5b18','frozenAttemptOrderingFingerprint5b19').replaceAll('independentPrimaryDomain5b18','independentPrimaryDomain5b19').replaceAll('authLikeRenderedUrl5b18','authLikeRenderedUrl5b19');
 x=x.replaceAll('results/experiment-5b18-engine','results/experiment-5b19-engine').replaceAll('experiment:"5B18-ENGINE"','experiment:"5B19-ENGINE"').replaceAll('purpose:"development_executable_surface_budget_reservation_engine"','purpose:"development_evidence_qualified_executable_request_induction_engine"').replaceAll('base_sha:"a094a2ac809486c28474b9754a31d076fb8e938b"','base_sha:"c34be729b6f67dc460ed669ebb8fdf534589fddb"');
 x=r(x,'function plannerOutput5b14(evidence:any[],caseId:string,providerId:string){return [...evidence].reverse().find((e:any)=>e.case_id===caseId&&e.provider_candidate_id===providerId&&e.parsed_json?.decision==="COMPILE")?.parsed_json??null}',
 'function plannerOutput5b14(evidence:any[],caseId:string,providerId:string){return [...evidence].reverse().find((e:any)=>e.case_id===caseId&&e.provider_candidate_id===providerId&&e.parsed_json?.decision==="COMPILE")?.parsed_json??null}\nfunction plannerAudit5b19(evidence:any[],caseId:string,providerId:string){return [...evidence].reverse().find((e:any)=>e.case_id===caseId&&e.provider_candidate_id===providerId)??null}\nconst qualificationAudit5b19:any[]=[];');
 x=r(x,'const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.candidate_name,start_url:effectiveStart},cr=await crawl5b18(p,ledger,Boolean(primary.unhealthy_after_5b15)),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence,cr.recovery?.lineages||[]);',
 'const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.candidate_name,start_url:effectiveStart},cr=await crawl5b18(p,ledger,Boolean(primary.unhealthy_after_5b15)),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence,cr.recovery?.lineages||[]),qa=plannerAudit5b19(synthesisEvidence,p.case_id,p.candidate_id);qualificationAudit5b19.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,raw_request_hypotheses:Number(qa?.rawRequestHypotheses5b19||0),admitted_request_hypotheses:Number(qa?.admittedRequestHypotheses5b19||0),rejected_request_hypotheses:Number(qa?.rejectedRequestHypotheses5b19||0),rejected_no_strong_provenance:Number(qa?.rejectedNoStrongProvenance5b19||0),rejected_weak_input_binding:Number(qa?.rejectedWeakInputBinding5b19||0),admitted_machine_contract:Number(qa?.admittedMachineContract5b19||0),admitted_structured_collection:Number(qa?.admittedStructuredCollection5b19||0),admitted_executed_trace:Number(qa?.admittedExecutedTrace5b19||0),admitted_documented_local_http:Number(qa?.admittedDocumentedLocalHttp5b19||0),url_presence_only_admissions:Number(qa?.urlPresenceOnlyAdmissions5b19||0),broad_identity_only_binding_admissions:Number(qa?.broadIdentityOnlyBindingAdmissions5b19||0),qualification_nondeterminism_violations:Number(qa?.qualificationNondeterminismViolations5b19||0),qualification_ranking_bonus_uses:Number(qa?.qualificationRankingBonusUses5b19||0),qualification_beam_entries:Number(qa?.qualificationBeamEntries5b19||0),beam_entries_without_qualification_witness:Number(qa?.beamEntriesWithoutQualificationWitness5b19||0),probed_with_qualification_witness:Number(qa?.probedRequestsWithQualificationWitness5b19||0),probed_without_qualification_witness:Number(qa?.probedRequestsWithoutQualificationWitness5b19||0),qualification_fingerprint:qa?.request_qualification_fingerprint_5b19||null,qualification_witnesses:qa?.request_qualification_witnesses_5b19||[],qualification_rejections:qa?.request_qualification_rejections_5b19||[]});');
 x=x.replaceAll('recovery_fetches:Number(recoveryMetrics5b18.reservedRecoveryFetches5b18||0)}','recovery_fetches:Number(recoveryMetrics5b18.reservedRecoveryFetches5b18||0),qualification_audits:qualificationAudit5b19.length}');
 x=x.replaceAll('recovery_fetches:Number(recoveryMetrics5b18.reservedRecoveryFetches5b18||0)-replayBefore.recovery_fetches}','recovery_fetches:Number(recoveryMetrics5b18.reservedRecoveryFetches5b18||0)-replayBefore.recovery_fetches,qualification_audits:qualificationAudit5b19.length-replayBefore.qualification_audits}');
 x=x.replace('recovery_fetches:a.recovery_fetches+Number(d.recovery_fetches||0)}),{catalog_fetches:0,broad_retrieval_calls:0,equivalence_reranker_calls:0,secondary_reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0})','recovery_fetches:a.recovery_fetches+Number(d.recovery_fetches||0),qualification_audits:a.qualification_audits+Number(d.qualification_audits||0)}),{catalog_fetches:0,broad_retrieval_calls:0,equivalence_reranker_calls:0,secondary_reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0,qualification_audits:0})');
 x=x.replace('synthesisEvidence,providerFetchAudit5b18,recoveryLineage5b18,','synthesisEvidence,qualificationAudit5b19,providerFetchAudit5b18,recoveryLineage5b18,');
 x=x.replace('documentary_witness_5b12:po?.documentary_witness_5b12??null,request_utility_5b14:po?.request_utility_5b14??null,contract,','documentary_witness_5b12:po?.documentary_witness_5b12??null,request_utility_5b14:po?.request_utility_5b14??null,evidence_qualification_witness_5b19:po?.evidence_qualification_witness_5b19??null,contract,');
 return x;
}
