import {deriveExperiment4iSource} from "./experiment4iDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4j_anchor_missing:${a.slice(0,120)}`);return s.replace(a,b)}
export function deriveExperiment4jSource(source:string){let x=deriveExperiment4iSource(source);
x=r(x,'import {compile4i as compile4ar,project4i as project4ar,scope4i as scope4ar,validate4i as validate4ar,validateProjected4i as validateProjected4ar} from "./experiment4iContract.js";','import {compile4j as compile4ar,project4j as project4ar,scope4j as scope4ar,validate4j as validate4ar,validateProjected4j as validateProjected4ar} from "./experiment4jContract.js";');
x=r(x,'import {synthesize4i as synthesize4ar} from "./experiment4iPlanner.js";','import {synthesize4j as synthesize4ar} from "./experiment4jPlanner.js";');
x=r(x,'const OUT="results/experiment-4i",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4j",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'identifierRoleRejectedAuthLike4i=0;','identifierRoleRejectedAuthLike4i=0,shapeRoleCandidates4j=0,shapeRoleUniqueCompatible4j=0,shapeRoleRejectedAmbiguous4j=0,shapeRoleRejectedFixedLiteral4j=0,shapeRoleRejectedNoEntityCompatibility4j=0,taskOperationCompatibilityAccepted4j=0,taskOperationCompatibilityRejected4j=0,taskEntityTokens4j=0,operationIdentityTokens4j=0,wrongEntityHypothesesRejected4j=0,authLikeHypothesesRejectedPreGraph4j=0,acceptedEntityMismatch4j=0;');
x=r(x,'identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;','identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;shapeRoleCandidates4j+=sm.shapeRoleCandidates||0;shapeRoleUniqueCompatible4j+=sm.shapeRoleUniqueCompatible||0;shapeRoleRejectedAmbiguous4j+=sm.shapeRoleRejectedAmbiguous||0;shapeRoleRejectedFixedLiteral4j+=sm.shapeRoleRejectedFixedLiteral||0;shapeRoleRejectedNoEntityCompatibility4j+=sm.shapeRoleRejectedNoEntityCompatibility||0;taskOperationCompatibilityAccepted4j+=sm.taskOperationCompatibilityAccepted||0;taskOperationCompatibilityRejected4j+=sm.taskOperationCompatibilityRejected||0;taskEntityTokens4j+=sm.taskEntityTokens||0;operationIdentityTokens4j+=sm.operationIdentityTokens||0;wrongEntityHypothesesRejected4j+=sm.wrongEntityHypothesesRejected||0;authLikeHypothesesRejectedPreGraph4j+=sm.authLikeHypothesesRejectedPreGraph||0;acceptedEntityMismatch4j+=sm.acceptedEntityMismatch||0;');
x=r(x,'identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,schemaProbeCalls','identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,shapeRoleCandidates:shapeRoleCandidates4j,shapeRoleUniqueCompatible:shapeRoleUniqueCompatible4j,shapeRoleRejectedAmbiguous:shapeRoleRejectedAmbiguous4j,shapeRoleRejectedFixedLiteral:shapeRoleRejectedFixedLiteral4j,shapeRoleRejectedNoEntityCompatibility:shapeRoleRejectedNoEntityCompatibility4j,taskOperationCompatibilityAccepted:taskOperationCompatibilityAccepted4j,taskOperationCompatibilityRejected:taskOperationCompatibilityRejected4j,taskEntityTokens:taskEntityTokens4j,operationIdentityTokens:operationIdentityTokens4j,wrongEntityHypothesesRejected:wrongEntityHypothesesRejected4j,authLikeHypothesesRejectedPreGraph:authLikeHypothesesRejectedPreGraph4j,acceptedEntityMismatch:acceptedEntityMismatch4j,schemaProbeCalls');
x=x.replaceAll('4I_STRUCTURAL_IDENTIFIER_ROLE:','4J_SHAPE_AWARE_IDENTIFIER_COMPATIBILITY:').replaceAll('GO_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','GO_4J_SHAPE_AWARE_IDENTIFIER_COMPATIBILITY').replaceAll('REASSESS_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE','REASSESS_4J_SHAPE_AWARE_IDENTIFIER_COMPATIBILITY');
x=r(x,'experiment:"4I",purpose:"development_structural_identifier_role_inference"','experiment:"4J",purpose:"development_shape_aware_identifier_compatibility"');
x=r(x,'base_sha:"28c83671b4aa38bd87bf6ddefd540e1b5d6035c1"','base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"');
x=r(x,'wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,','wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,no_entity_mismatch_recipes:acceptedEntityMismatch4j===0,');
return x}
