import {isIP} from "node:net";
import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {compileMicroRequest} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {FOUR_A_CASES,semanticValidate4a} from "./experiment4aCore.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import {executeProgram} from "./experiment3xCore.js";
import {scope4ar4} from "./experiment4ar4Contract.js";
import {contractFromR6RRaw,extractOperationInventoryR6R} from "./experiment4ar6rCore.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(x=>[x.case_id,x]));
const sourceKey=(s:string)=>s.startsWith("$input.")?s.slice(7):null;

export function validate4ar6r(raw:any,p:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){const c=BY_ID[p.case_id],errors:string[]=[];if(!c)return {errors:["unknown_case"],contract:null as any,projection:null as any,operation_proof:null};if(!raw||typeof raw!=="object"||Array.isArray(raw))return {errors:["contract_not_object"],contract:null as any,projection:null as any,operation_proof:null};if(raw.case_id!==p.case_id)errors.push("case_id_mismatch");if(raw.provider_candidate_id!==p.candidate_id)errors.push("provider_id_mismatch");if(raw.decision==="REJECT")return {errors,contract:contractFromR6RRaw(raw),projection:null,operation_proof:null};if(raw.decision!=="COMPILE")return {errors:[...errors,"decision_invalid"],contract:null,projection:null,operation_proof:null};if(raw.method!=="GET"){errors.push("method_not_get");ledger.record("guard","non_get",false,raw.method);}const opId=String(raw.reason||"").startsWith("R6R_OPERATION:")?String(raw.reason).slice(14):"",inventory=extractOperationInventoryR6R(evidence,p.case_id),op=inventory.packet.find(x=>x.operation_id===opId);if(!op){errors.push("r6r_operation_proof_missing");return {errors,contract:null,projection:null,operation_proof:null};}
 try{const u=new URL(String(raw.base_url||""));if(u.protocol!=="https:"){errors.push("base_non_https");ledger.record("guard","non_https",false,u.toString());}if(u.username||u.password)errors.push("credential_bearing_base");if(isIP(u.hostname)){errors.push("base_ip_literal");ledger.record("guard","private_hosts",false,u.hostname);}if(u.origin!==op.origin){errors.push("r6r_origin_not_operation_proven");ledger.record("guard","endpoint_mutations",false,{got:u.origin,expected:op.origin});}}catch{errors.push("invalid_base_url");}
 if(raw.path_template!==op.full_path){errors.push("r6r_path_not_operation_proven");ledger.record("guard","endpoint_mutations",false,{got:raw.path_template,expected:op.full_path});}
 const evidenceById=new Map(evidence.map(x=>[x.evidence_id,x]));for(const id of op.evidence_ids){const e=evidenceById.get(id);if(!e||e.provider_candidate_id!==p.candidate_id||e.state!=="ok")errors.push(`r6r_invalid_proof_evidence:${id}`);}
 const pb=raw.path_bindings&&typeof raw.path_bindings==="object"&&!Array.isArray(raw.path_bindings)?raw.path_bindings:{},qb=raw.query_bindings&&typeof raw.query_bindings==="object"&&!Array.isArray(raw.query_bindings)?raw.query_bindings:{};for(const pp of op.path_parameters){const src=pb[pp.name],key=typeof src==="string"?sourceKey(src):null;if(!key||!c.input_names.includes(key)){errors.push(`r6r_unbound_documented_path_parameter:${pp.name}`);ledger.record("guard","invented_parameters",false,pp.name);}}for(const key of Object.keys(pb))if(!op.path_parameters.some(x=>x.name===key)){errors.push(`r6r_undocumented_path_parameter:${key}`);ledger.record("guard","invented_parameters",false,key);}for(const [name,src0] of Object.entries(qb)){const param=op.query_parameters.find(x=>x.name===name),src=String(src0);if(!param){errors.push(`r6r_undocumented_query_parameter:${name}`);ledger.record("guard","invented_parameters",false,name);continue;}if(src.startsWith("$input.")){const key=sourceKey(src);if(!key||!c.input_names.includes(key)){errors.push(`r6r_invalid_query_input:${name}`);ledger.record("guard","invented_parameters",false,name);}}else if(!param.literals.includes(src)){errors.push(`r6r_undocumented_query_literal:${name}`);ledger.record("guard","invented_parameters",false,{name,src});}}for(const q of op.query_parameters)if(q.required&&qb[q.name]===undefined)errors.push(`r6r_required_query_unbound:${q.name}`);
 const plan=raw.projection as ProjectionPlan;if(!plan||typeof plan!=="object"||Array.isArray(plan))errors.push("projection_plan_invalid");else{const keys=Object.keys(plan).sort(),required=[...c.required].sort();if(keys.length!==required.length||keys.some((k,i)=>k!==required[i]))errors.push("projection_keys_mismatch");for(const output of c.required){const x:any=(plan as any)[output];if(!x){errors.push(`projection_missing:${output}`);continue;}if(x.op==="INPUT"){if(!c.input_names.includes(x.name)){errors.push(`projection_input_invalid:${output}`);ledger.record("guard","ungrounded_projection_fields",false,x.name);}}else if(x.op==="FIELD"){if(!op.response_paths.includes(x.path)){errors.push(`r6r_response_path_not_operation_proven:${output}:${x.path}`);ledger.record("guard","ungrounded_projection_fields",false,x.path);}}else{errors.push(`r6r_projection_op_forbidden:${output}`);ledger.record("guard","ungrounded_projection_fields",false,x.op);}}}
 if(errors.length)errors.push(`r6r_selected_operation_id=${op.operation_id}`);const contract:MicroContract=contractFromR6RRaw(raw);return {errors,contract,projection:errors.length?null:plan,operation_proof:{operation_id:op.operation_id,proof_type:op.proof_type,evidence_ids:op.evidence_ids,source_urls:op.source_urls,origin:op.origin,full_path:op.full_path,inventory_fingerprint:inventory.inventory_fingerprint,packet_fingerprint:inventory.packet_fingerprint}};}

export function compile4ar6r(c:MicroContract,input:Record<string,unknown>){return compileMicroRequest(c,input);}
export function project4ar6r(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return executeProgram(plan,body,input) as Record<string,any>;}
export function validateProjected4ar6r(caseId:string,input:Record<string,any>,out:Record<string,any>){return semanticValidate4a(caseId,input,out);}
export function scope4ar6r(start:string,target:string){return scope4ar4(start,target);}
