import {mkdir,writeFile} from "node:fs/promises";
import {Client,StreamableHTTPClientTransport,SSEClientTransport} from "@modelcontextprotocol/client";
import {loadConfig} from "./config/index.js";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=58,TIMEOUT_MS=12000;
const READ=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUT=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
const PLACE=new Set(["unable","unknown","none","null","n/a","na","undefined","error","failed",""]);
const CASES=[
 {case_id:"github_repository_owner_profile",intent:"Given a GitHub repository identifier, return a public profile fact about the repository owner that cannot be obtained from the seed alone.",build:{repository:"openai/openai-python"},replay:{repository:"pallets/flask"}},
 {case_id:"country_to_capital_fact",intent:"Given a country name, use one capability to derive a capital/city entity and a second capability to return a public fact about that derived entity.",build:{country:"Costa Rica"},replay:{country:"Japan"}},
 {case_id:"city_to_country_fact",intent:"Given a city name, use one capability to derive a country entity and a second capability to return a public fact about that derived country.",build:{city:"San Jose"},replay:{city:"Tokyo"}}
] as const;
const KNOWN_3I={a:"search_news",b:"advisors_store_readiness_check"};
let unsafeExecuted=0,credentialsSupplied=0,replayPlannerCalls=0,errorSuccess=0,known3iUsed=0,plannerCalls=0,repairCalls=0;
type Candidate={name:string,url:string,transport:string}; type ToolRef={server:Candidate,tool:any,safe:boolean,reasons:string[]};
type Recipe={case_id:string,decision:"BUILD"|"REJECT",step_a_server?:string,step_a_tool?:string,step_a_args?:Record<string,string>,step_a_output_path?:string,step_a_output_concept?:string,step_b_server?:string,step_b_tool?:string,step_b_arg_name?:string,final_output_description?:string,reason?:string};
function timeout<T>(p:Promise<T>){return new Promise<T>((res,rej)=>{const t=setTimeout(()=>rej(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);res(v)},e=>{clearTimeout(t);rej(e)});});}
function remoteType(x:any){return String(x?.type??x?.transport??"").toLowerCase();} function remoteUrl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligible(r:any){const t=remoteType(r),u=remoteUrl(r);if(!["streamable-http","sse"].includes(t)||typeof u!=="string"||!u.startsWith("https://")||/[{}]/.test(u))return false;const h=r?.headers;return !(h&&((Array.isArray(h)&&h.length)||(!Array.isArray(h)&&Object.keys(h).length)));}
async function getRegistry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3L/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function records(b:any){return Array.isArray(b)?b:Array.isArray(b?.servers)?b.servers:Array.isArray(b?.data)?b.data:Array.isArray(b?.items)?b.items:[];}
function candidates(rs:any[]){const o:Candidate[]=[];for(const raw of rs){const s=raw?.server??raw,n=String(s?.name??raw?.name??"");if(!n)continue;const r=(s?.remotes??raw?.remotes??[]).find(eligible);if(r)o.push({name:n,url:remoteUrl(r),transport:remoteType(r)});}o.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return o.filter(x=>!seen.has(x.name)&&!!seen.add(x.name));}
function has(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));} function req(t:any){return Array.isArray(t?.inputSchema?.required)?t.inputSchema.required:[];}
function classify(t:any){const r:string[]=[];if(!t?.inputSchema||typeof t.inputSchema!=="object"||Array.isArray(t.inputSchema))r.push("invalid_schema");if(t?.annotations?.readOnlyHint!==true)r.push("missing_readonly");if(t?.annotations?.destructiveHint===true)r.push("destructive");const text=`${t?.name??""} ${t?.description??""}`;if(!has(text,READ))r.push("no_read_signal");if(has(text,MUT))r.push("mutation_signal");return {safe:r.length===0,reasons:r};}
function transport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function list(c:Candidate){const client=new Client({name:"missing-experiment-3l",version:"0.1.0"});await timeout(client.connect(transport(c)));const x:any=await timeout(client.listTools());return {client,tools:x.tools??[]};}
async function call(client:Client,t:any,args:any){if(!classify(t).safe)unsafeExecuted++;return timeout(client.callTool({name:t.name,arguments:args}));}
function structured(r:any){if(r?.structuredContent&&typeof r.structuredContent==="object")return r.structuredContent;const texts=(r?.content??[]).filter((x:any)=>x?.type==="text"&&typeof x.text==="string");if(texts.length===1)try{return JSON.parse(texts[0].text);}catch{}return null;}
function functional(r:any){if(!r||r.isError===true)return false;const b=r.structuredContent;if(b&&typeof b==="object"&&b.ok===false)return false;const nonempty=(Array.isArray(r.content)&&r.content.length>0)||(b&&typeof b==="object"&&Object.keys(b).length>0);if(!nonempty)return false;const s=JSON.stringify(r);return !/authentication required|unauthorized|forbidden|requires a subscriber|requires an api key|"error"\s*:\s*"[^"\n]+"|\berror:/i.test(s);}
function pathGet(v:any,p:string){if(p==="$"||!p)return v;return p.split(".").reduce((x,k)=>x?.[k],v);} function scalarType(v:any){return typeof v==="string"?"string":typeof v==="number"&&Number.isFinite(v)?"number":typeof v==="boolean"?"boolean":null;} function placeholder(v:any){return typeof v==="string"&&PLACE.has(v.trim().toLowerCase());}
function findRef(tools:ToolRef[],server?:string,name?:string){return tools.find(x=>x.server.name===server&&x.tool.name===name);}
function staticValidate(r:Recipe,c:any,tools:ToolRef[]){const e:string[]=[];if(r.case_id!==c.case_id)e.push("case_id_mismatch");if(r.decision!=="BUILD")return e;if(!r.step_a_server||!r.step_a_tool||!r.step_b_server||!r.step_b_tool||!r.step_b_arg_name||!r.step_a_output_path)e.push("missing_fields");const a=findRef(tools,r.step_a_server,r.step_a_tool),b=findRef(tools,r.step_b_server,r.step_b_tool);if(!a||!b)e.push("unknown_tool");if(a&&!a.safe)e.push("unsafe_a");if(b&&!b.safe)e.push("unsafe_b");if(r.step_a_server===r.step_b_server)e.push("same_server");if(r.step_a_tool===KNOWN_3I.a&&r.step_b_tool===KNOWN_3I.b)e.push("known_3i_pair");for(const [k,v] of Object.entries(r.step_a_args??{})){if(!/^\$seed\.[A-Za-z][A-Za-z0-9_]*$/.test(v))e.push(`bad_seed_ref:${k}`);else if(!(v.slice(6) in c.build))e.push(`unknown_seed_ref:${k}`);}if(a){const required=req(a.tool);for(const p of required)if(!(p in (r.step_a_args??{})))e.push(`missing_a_arg:${p}`);for(const p of Object.keys(r.step_a_args??{}))if(!a.tool.inputSchema?.properties?.[p])e.push(`extra_a_arg:${p}`);}if(b){const required=req(b.tool);if(required.length!==1||required[0]!==r.step_b_arg_name)e.push("b_not_single_required_scalar");const s=b.tool.inputSchema?.properties?.[r.step_b_arg_name!];const type=s?.type==="integer"?"number":s?.type;if(!["string","number","boolean"].includes(type))e.push("b_arg_not_scalar");}return e;}
async function planner(config:any,c:any,catalog:any[],failed?:string){plannerCalls++;if(failed)repairCalls++;const system="You are MISSING Seeded Intent Composer. Select exactly two already-discovered safe read-only MCP tools to satisfy the case. Step A arguments may reference only $seed.field. Step B must have exactly one required scalar argument and consume one scalar extracted from Step A at step_a_output_path. Use only server/tool/schema metadata supplied. Do not invent tools, constants, transforms, credentials, URLs, or values. Different servers required. If no credible chain exists, REJECT. Return one JSON object only.";const user={case:{case_id:c.case_id,intent:c.intent,seed_fields:Object.keys(c.build)},catalog,previous_failure:failed??null,output_contract:{case_id:c.case_id,decision:"BUILD|REJECT",step_a_server:"string",step_a_tool:"string",step_a_args:{arg:"$seed.field"},step_a_output_path:"dot.path",step_a_output_concept:"string",step_b_server:"string",step_b_tool:"string",step_b_arg_name:"string",final_output_description:"string",reason:"string"}};const resp=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(user)}],response_format:{type:"json_object"}})});if(!resp.ok)throw new Error(`planner_${resp.status}:${await resp.text()}`);const body:any=await resp.json();return JSON.parse(body.choices?.[0]?.message?.content??"{}");}
async function executeRecipe(r:Recipe,c:any,seed:any,tools:ToolRef[]){const a=findRef(tools,r.step_a_server,r.step_a_tool)!,b=findRef(tools,r.step_b_server,r.step_b_tool)!;const aArgs:any={};for(const [k,v] of Object.entries(r.step_a_args??{}))aArgs[k]=seed[String(v).slice(6)];const la=await list(a.server);const ta=la.tools.find((x:any)=>x.name===a.tool.name);try{const ar=await call(la.client,ta,aArgs);if(!functional(ar))throw new Error("step_a_functional_failure");const value=pathGet(structured(ar),r.step_a_output_path!);const vt=scalarType(value);if(!vt||placeholder(value))throw new Error("step_a_output_not_scalar");const bs=b.tool.inputSchema?.properties?.[r.step_b_arg_name!];const bt=bs?.type==="integer"?"number":bs?.type;if(vt!==bt)throw new Error(`type_mismatch:${vt}->${bt}`);await la.client.close();const lb=await list(b.server);const tb=lb.tools.find((x:any)=>x.name===b.tool.name);try{const br=await call(lb.client,tb,{[r.step_b_arg_name!]:value});if(!functional(br))throw new Error("step_b_functional_failure");return {step_a_args:aArgs,step_a_value:value,step_a_result:ar,step_b_args:{[r.step_b_arg_name!]:value},step_b_result:br};}finally{await lb.client.close();}}catch(e){try{await la.client.close();}catch{}throw e;}}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3L");const reg=await getRegistry(),rs=records(reg),cs=candidates(rs),tools:ToolRef[]=[],discovery:any[]=[];
for(const c of cs.slice(0,MAX_SERVERS)){try{const {client,tools:listTools}=await list(c);for(const t of listTools){const d=classify(t);tools.push({server:c,tool:t,...d});}discovery.push({server:c,tool_count:listTools.length});await client.close();}catch(e){discovery.push({server:c,error:String(e)});}}
const safe=tools.filter(x=>x.safe);const catalog=safe.map(x=>({server:x.server.name,tool:x.tool.name,description:x.tool.description??"",inputSchema:x.tool.inputSchema,outputSchema:x.tool.outputSchema??null}));const results:any[]=[];const persisted:any[]=[];
for(const c of CASES){let recipe:Recipe=await planner(config,c,catalog);let staticErrors=staticValidate(recipe,c,tools);let validation:any=null,repaired=false;if(recipe.decision==="BUILD"&&staticErrors.length===0){try{validation=await executeRecipe(recipe,c,c.build,tools);}catch(e){recipe=await planner(config,c,catalog,"Statically valid two-step recipe failed live validation. Repair only by selecting other discovered safe tools or a different declared Step A output path.");repaired=true;staticErrors=staticValidate(recipe,c,tools);if(recipe.decision==="BUILD"&&staticErrors.length===0)try{validation=await executeRecipe(recipe,c,c.build,tools);}catch(e2){validation={error:String(e2)};}else validation={error:"repair_not_build_or_static_invalid"};}}const validated=recipe.decision==="BUILD"&&staticErrors.length===0&&validation&&!validation.error;if(validated){if(recipe.step_a_tool===KNOWN_3I.a&&recipe.step_b_tool===KNOWN_3I.b)known3iUsed++;persisted.push({case_id:c.case_id,recipe,validation});}results.push({case_id:c.case_id,recipe,static_errors:staticErrors,static_valid:staticErrors.length===0,validated,repaired,validation});}
const replay:any[]=[];for(const p of persisted){const c=CASES.find(x=>x.case_id===p.case_id)!;const before=plannerCalls;try{const out=await executeRecipe(p.recipe,c,c.replay,tools);replay.push({case_id:p.case_id,success:true,seed:c.replay,output:out});}catch(e){replay.push({case_id:p.case_id,success:false,seed:c.replay,error:String(e)});}replayPlannerCalls+=plannerCalls-before;}
const replaySuccess=replay.filter(x=>x.success).length,replayRate=persisted.length?replaySuccess/persisted.length:0;const criteria={one_static_recipe:results.filter(x=>x.recipe.decision==="BUILD"&&x.static_valid).length>=1,one_live_validation:persisted.length>=1,one_independent_replay:replaySuccess>=1,replay_success_rate:replayRate===1,cross_server_two_step:persisted.every(x=>x.recipe.step_a_server!==x.recipe.step_b_server),step_a_seed_only:persisted.every(x=>Object.values(x.recipe.step_a_args??{}).every((v:any)=>/^\$seed\./.test(v))),step_b_from_a_only:persisted.every(x=>!!x.recipe.step_a_output_path&&!!x.recipe.step_b_arg_name),zero_invented_literals:persisted.every(x=>Object.values(x.recipe.step_a_args??{}).every((v:any)=>/^\$seed\./.test(v))),zero_unsafe:unsafeExecuted===0,zero_credentials:credentialsSupplied===0,known_3i_pair_zero:known3iUsed===0,zero_replay_planner_calls:replayPlannerCalls===0,zero_error_success:errorSuccess===0,evidence_persisted:true};const decision=Object.values(criteria).every(Boolean)?"GO_SEEDED_INTENT_COMPOSITION":"REASSESS_SEEDED_INTENT_COMPOSITION";
const summary={experiment:"MISSING Experiment 3L — Seeded Intent Composition",created_at:new Date().toISOString(),metrics:{registry_records:rs.length,eligible_servers:cs.length,servers_inspected:discovery.length,discovered_tools:tools.length,safe_tools:safe.length,cases:CASES.length,planner_calls:plannerCalls,repair_calls:repairCalls,static_builds:results.filter(x=>x.recipe.decision==="BUILD"&&x.static_valid).length,validated_recipes:persisted.length,replay_successes:replaySuccess,replay_success_rate:replayRate,unsafe_tools_executed:unsafeExecuted,credentials_supplied:credentialsSupplied,known_3i_pair_used:known3iUsed,replay_planner_calls:replayPlannerCalls},criteria,decision,results:results.map(x=>({case_id:x.case_id,recipe:x.recipe,static_errors:x.static_errors,static_valid:x.static_valid,validated:x.validated,repaired:x.repaired})),replay:replay.map(x=>({case_id:x.case_id,success:x.success,seed:x.seed,error:x.error}))};
await mkdir("results/experiment-3l",{recursive:true});await writeFile("results/experiment-3l/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3l/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:reg,discovery,catalog,results,persisted,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
