import {compile4ar,project4ar} from "./experiment4arContract.js";
import {semanticValidate4a} from "./experiment5aCore.js";
import {fetchTextSafeR2} from "./experiment3yr2Core.js";
import {RecoveryLedger} from "./experiment3yrCore.js";
import {authLikeRenderedRequest5B15,classifyFiveB15Failure,fiveB15Sha,requestFingerprint5B15} from "./experiment5b15Policy.js";

const MAX_BYTES=4*1024*1024;
export const lineageFingerprintFiveB15=(r:any)=>fiveB15Sha({documentary_witness_5b12:r?.documentary_witness_5b12??null,request_utility_5b14:r?.request_utility_5b14??null});
export type FiveB15Attempt={case_id:string;recipe_fingerprint:string;attempt:number;success:boolean;retryable:boolean;outcome_class:string;http_status:number|null;request_fingerprint:string|null;rendered_url_fingerprint:string|null;changed_input_fingerprint:string;http_fetches:number;latency_ms:number;final_url_fingerprint?:string;body_fingerprint?:string;output?:any;error?:string};
export type FiveB15RunState={ledger:RecoveryLedger;logicalAttempts:number;requestComparisons:number;requestMismatchViolations:number;changedInputMutationViolations:number;recipeMutationViolations:number;authLikeRenderedRequests:number;wrongTaskProbeAttempts:number;firstRequestFingerprint:Map<string,string>;firstRenderedUrl:Map<string,string>;recipeBaseline:Map<string,string>;inputBaseline:Map<string,string>};
export function createFiveB15RunState():FiveB15RunState{return {ledger:new RecoveryLedger(),logicalAttempts:0,requestComparisons:0,requestMismatchViolations:0,changedInputMutationViolations:0,recipeMutationViolations:0,authLikeRenderedRequests:0,wrongTaskProbeAttempts:0,firstRequestFingerprint:new Map(),firstRenderedUrl:new Map(),recipeBaseline:new Map(),inputBaseline:new Map()}}

export async function executeFiveB15Attempt(recipe:any,attempt:number,state:FiveB15RunState):Promise<FiveB15Attempt>{
 const t0=Date.now(),key=String(recipe.recipe_fingerprint),changedInputFingerprint=fiveB15Sha(recipe.changed_input);state.logicalAttempts++;
 if(changedInputFingerprint!==state.inputBaseline.get(key))state.changedInputMutationViolations++;
 if(fiveB15Sha(recipe)!==state.recipeBaseline.get(key))state.recipeMutationViolations++;
 let url="",requestFingerprint:string|null=null;
 try{url=compile4ar(recipe.contract,recipe.changed_input);requestFingerprint=requestFingerprint5B15(url)}catch(e){const f=classifyFiveB15Failure("render",e);return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:false,retryable:f.retryable,outcome_class:f.outcome_class,http_status:f.http_status,request_fingerprint:null,rendered_url_fingerprint:null,changed_input_fingerprint:changedInputFingerprint,http_fetches:0,latency_ms:Date.now()-t0,error:String(e)}}
 if(attempt===1){state.firstRequestFingerprint.set(key,requestFingerprint);state.firstRenderedUrl.set(key,url)}else{state.requestComparisons++;if(requestFingerprint!==state.firstRequestFingerprint.get(key)){state.requestMismatchViolations++;state.wrongTaskProbeAttempts++}if(url!==state.firstRenderedUrl.get(key))state.wrongTaskProbeAttempts++}
 if(authLikeRenderedRequest5B15(url))state.authLikeRenderedRequests++;
 const beforeFetches=state.ledger.count("fetch");let got:any;
 try{got=await fetchTextSafeR2(url,url,MAX_BYTES,state.ledger)}catch(e){const f=classifyFiveB15Failure("transport",e);return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:false,retryable:f.retryable,outcome_class:f.outcome_class,http_status:f.http_status,request_fingerprint:requestFingerprint,rendered_url_fingerprint:fiveB15Sha(url),changed_input_fingerprint:changedInputFingerprint,http_fetches:state.ledger.count("fetch")-beforeFetches,latency_ms:Date.now()-t0,error:String(e)}}
 let body:any;try{body=JSON.parse(got.text)}catch(e){const f=classifyFiveB15Failure("decode",e);return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:false,retryable:f.retryable,outcome_class:f.outcome_class,http_status:f.http_status,request_fingerprint:requestFingerprint,rendered_url_fingerprint:fiveB15Sha(url),changed_input_fingerprint:changedInputFingerprint,http_fetches:state.ledger.count("fetch")-beforeFetches,latency_ms:Date.now()-t0,final_url_fingerprint:fiveB15Sha(got.final_url),body_fingerprint:fiveB15Sha(got.text),error:String(e)}}
 let output:any;try{output=project4ar(recipe.projection,body,recipe.changed_input)}catch(e){const f=classifyFiveB15Failure("projection",e);return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:false,retryable:f.retryable,outcome_class:f.outcome_class,http_status:f.http_status,request_fingerprint:requestFingerprint,rendered_url_fingerprint:fiveB15Sha(url),changed_input_fingerprint:changedInputFingerprint,http_fetches:state.ledger.count("fetch")-beforeFetches,latency_ms:Date.now()-t0,final_url_fingerprint:fiveB15Sha(got.final_url),body_fingerprint:fiveB15Sha(got.text),error:String(e)}}
 if(!semanticValidate4a(recipe.case_id,recipe.changed_input,output)){const f=classifyFiveB15Failure("semantic","semantic_verification_failed");return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:false,retryable:f.retryable,outcome_class:f.outcome_class,http_status:f.http_status,request_fingerprint:requestFingerprint,rendered_url_fingerprint:fiveB15Sha(url),changed_input_fingerprint:changedInputFingerprint,http_fetches:state.ledger.count("fetch")-beforeFetches,latency_ms:Date.now()-t0,final_url_fingerprint:fiveB15Sha(got.final_url),body_fingerprint:fiveB15Sha(got.text),output,error:"semantic_verification_failed"}}
 return {case_id:recipe.case_id,recipe_fingerprint:key,attempt,success:true,retryable:false,outcome_class:"semantic_success",http_status:200,request_fingerprint:requestFingerprint,rendered_url_fingerprint:fiveB15Sha(url),changed_input_fingerprint:changedInputFingerprint,http_fetches:state.ledger.count("fetch")-beforeFetches,latency_ms:Date.now()-t0,final_url_fingerprint:fiveB15Sha(got.final_url),body_fingerprint:fiveB15Sha(got.text),output};
}
