import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileEvidenceNativeSemantics4G,type Operation4G} from "./experiment4gSemantics.js";
import type {IrParameter} from "./experiment4fIr.js";
import {alignTaskOperation4H} from "./experiment4hAlignment.js";

const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const REQUIRED_AUTH_LOCAL=/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth).{0,100}(?:required|must|need|mandatory)|(?:required|must|need|mandatory).{0,100}(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i;
function paramsFor(s:any,op:Operation4G){return op.parameter_ids.map((id:string)=>s.parameters.find((p:IrParameter)=>p.id===id)).filter(Boolean) as IrParameter[]}
function pruneAuthQuery(path:string,metrics:any){try{const u=new URL(path,"https://placeholder.invalid"),removed:string[]=[];for(const [name] of [...u.searchParams])if(AUTH_NAME.test(name)){u.searchParams.delete(name);removed.push(name)}metrics.optionalAuthSlotsPruned+=removed.length;return `${u.pathname}${u.search}` }catch{return path}}
function make(caseId:string,s:any,op:Operation4G,metrics:any){metrics.alignmentCandidates++;const base=s.ir.api_bases.find((b:any)=>b.id===op.api_base_id);if(!base)return null;const params=paramsFor(s,op),localRequired=REQUIRED_AUTH_LOCAL.test(`${op.title} ${op.context}`);if(op.auth_class==="REQUIRED"||localRequired){metrics.requiredAuthSlotsBlocked+=params.filter(p=>p.auth_like).length||1;return null}const a=alignTaskOperation4H(caseId,s,op,params,metrics);if(!a.accepted)return null;const bound=new Set(Object.values(a.bindings));const safeParams:IrParameter[]=[];for(const p of params){if(!p.auth_like){safeParams.push(p);continue}if(bound.has(p.id)){metrics.authLikeHypothesesRejectedBeforeRender++;return null}if(op.auth_class==="OPTIONAL"||op.auth_class==="RATE_LIMIT_UPGRADE"||op.auth_class==="UNRELATED"||op.auth_class==="UNKNOWN")continue;metrics.requiredAuthSlotsBlocked++;return null}
const path=pruneAuthQuery(op.path,metrics),slots:P1RequestSlot[]=safeParams.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:false,literals:p.example!==null?[{id:`lit4h_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:p.example}]:[]}));const literal_bindings:Record<string,string>={};for(const slot of slots){if(bound.has(slot.id))continue;if(slot.literals.length===1&&/json/i.test(slot.literals[0].value)&&/(?:format|response|output|type)/i.test(slot.name))literal_bindings[slot.id]=slot.literals[0].id}
const h:P1RequestHypothesis={id:`req4h_${fourAp1Sha({op:op.id,base:base.id,path,input:a.bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:path,proof_type:`4h_task_operation_alignment_${op.form}_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings:a.bindings,literal_bindings,score:1000+a.score+(op.source.expanded?30:0),concrete_relation:op.absolute_url===null};return h}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let url="";try{url=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(url)}catch{return true}for(const [n] of u.searchParams)if(AUTH_NAME.test(n))return true;return h.slots.some(s=>s.auth_like)}
function buildGraph(evidence:DocEvidence[],caseId:string){const semantics=compileEvidenceNativeSemantics4G(evidence),metrics:any={...semantics.metrics,taskFrameTokens:0,taskFrameEntityTokens:0,taskFrameActionTokens:0,taskFrameIdentifierTokens:0,taskFrameOutputTokens:0,operationFrameCandidates:0,operationFrameWithIdentifierSignal:0,operationFrameWithEntitySignal:0,operationFrameWithActionSignal:0,operationFrameWithOutputSignal:0,alignmentCandidates:0,alignmentAccepted:0,alignmentRejectedNoIdentifier:0,alignmentRejectedInsufficientSupport:0,alignmentRejectedGenericIdentifier:0,alignmentAcceptedByConcreteExample:0,alignmentAcceptedByMorphology:0,alignmentScoreHistogram:{},optionalAuthSlotsPruned:0,requiredAuthSlotsBlocked:0,authLikeHypothesesRejectedBeforeRender:0};const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(c){const all=[c.intent,...c.input_names,...c.required].join(" ").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);metrics.taskFrameTokens=new Set(all).size;metrics.taskFrameIdentifierTokens=c.input_names.length;metrics.taskFrameOutputTokens=c.required.length;metrics.taskFrameActionTokens=(c.intent.match(/\b(?:get|lookup|search|find|retrieve|fetch|decode|estimate|metadata|identify|resolve|convert|list)\b/gi)||[]).length;metrics.taskFrameEntityTokens=Math.max(0,metrics.taskFrameTokens-metrics.taskFrameIdentifierTokens-metrics.taskFrameOutputTokens-metrics.taskFrameActionTokens)}const built=semantics.operations.map(op=>make(caseId,semantics,op,metrics)).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of built){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score);return {semantics,hypotheses,metrics,graph_fingerprint:fourAp1Sha({s:semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
export async function prepareRequestGraph4H(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),g=buildGraph(evidence,caseId),packet:P1RequestHypothesis[]=[],seen=new Set<string>();let authLikeRenderedRequests=0,duplicateRenderedProbeUrlsRejected=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of g.hypotheses){if(!c)break;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(seen.has(url)){duplicateRenderedProbeUrlsRejected++;continue}seen.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}const metrics={...g.metrics,...expansion,authLikeRenderedRequests,knownAuthProbeAttempts:0,wrongTaskProbeAttempts:0,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:seen.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0,expandedEvidenceHypotheses:g.hypotheses.filter(h=>g.semantics.operations.find(o=>o.id===h.source_operation_id)?.source.expanded).length};return {...g,probe_packet:packet,metrics}}
export function rebuildRequestGraph4H(evidence:DocEvidence[],caseId:string){const g=buildGraph(evidence,caseId),hypotheses=g.hypotheses.filter(h=>!renderedAuthLike(h,caseId));return {...g,hypotheses,graph_fingerprint:fourAp1Sha({s:g.semantics.fingerprint,h:hypotheses.map(h=>h.id)})}}
