import {deriveExperiment5b13Source} from "./experiment5b13Derivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b14_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b14Source(source:string){let x=deriveExperiment5b13Source(source);
 x=r(x,'import {synthesize5b13 as synthesize4ar} from "./.generated-experiment5b13Planner.js";','import {synthesize5b14 as synthesize4ar} from "./.generated-experiment5b14Planner.js";');
 x=r(x,'const OUT="results/experiment-5b13-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b14-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
 x=r(x,'async function synthesize(config:any,p:Provider4A,docs:DocEvidence[],ledger:RecoveryLedger,evidence:any[]){synthesisCalls++;let a=await synthesize4ar(config,p,docs,"initial"),v=a.parsed_json?validate4ar(a.parsed_json,p,docs,ledger):{errors:[a.parse_error||`planner_http_${a.http_status}`],contract:null,projection:null};recordUsage("synthesis",p.case_id,p.candidate_id,a.usage,a.latency_ms);evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...a,static_errors:v.errors});if(a.parsed_json?.decision==="REJECT"&&!v.errors.length)return {contract:a.parsed_json,projection:null,error:null};if(v.errors.length){synthesisCalls++;synthesisRepairs++;const b=await synthesize4ar(config,p,docs,"repair",v.errors.join(","));recordUsage("synthesis_repair",p.case_id,p.candidate_id,b.usage,b.latency_ms);v=b.parsed_json?validate4ar(b.parsed_json,p,docs,ledger):{errors:[b.parse_error||`planner_http_${b.http_status}`],contract:null,projection:null};evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...b,static_errors:v.errors});return {contract:v.errors.length?null:v.contract,projection:v.errors.length?null:v.projection,error:v.errors.join(",")||null};}return {contract:v.contract,projection:v.projection,error:null};}','async function synthesize(config:any,p:Provider4A,docs:DocEvidence[],ledger:RecoveryLedger,evidence:any[]){synthesisCalls++;let a=await synthesize4ar(config,p,docs,"initial"),planner=a.parsed_json,v=planner?validate4ar(planner,p,docs,ledger):{errors:[a.parse_error||`planner_http_${a.http_status}`],contract:null,projection:null};recordUsage("synthesis",p.case_id,p.candidate_id,a.usage,a.latency_ms);evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...a,static_errors:v.errors});if(planner?.decision==="REJECT"&&!v.errors.length)return {contract:planner,projection:null,error:null,planner_output:planner};if(v.errors.length){synthesisCalls++;synthesisRepairs++;const b=await synthesize4ar(config,p,docs,"repair",v.errors.join(","));recordUsage("synthesis_repair",p.case_id,p.candidate_id,b.usage,b.latency_ms);planner=b.parsed_json;v=planner?validate4ar(planner,p,docs,ledger):{errors:[b.parse_error||`planner_http_${b.http_status}`],contract:null,projection:null};evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...b,static_errors:v.errors});return {contract:v.errors.length?null:v.contract,projection:v.errors.length?null:v.projection,error:v.errors.join(",")||null,planner_output:planner||null};}return {contract:v.contract,projection:v.projection,error:null,planner_output:planner||null};}');
 x=r(x,'documentary_witness_5b12:(syn?.contract as any)?.documentary_witness_5b12??(syn?.contract as any)?.raw?.documentary_witness_5b12??null,contract,contract_fingerprint:sha3yr(contract)','documentary_witness_5b12:(syn as any)?.planner_output?.documentary_witness_5b12??(syn?.contract as any)?.documentary_witness_5b12??(syn?.contract as any)?.raw?.documentary_witness_5b12??null,request_utility_5b14:(syn as any)?.planner_output?.request_utility_5b14??(syn?.contract as any)?.request_utility_5b14??(syn?.contract as any)?.raw?.request_utility_5b14??null,contract,contract_fingerprint:sha3yr(contract)');
 x=x.replaceAll('experiment:"5B13-ENGINE"','experiment:"5B14-ENGINE"').replaceAll('purpose:"development_request_local_documentary_semantic_utility_engine"','purpose:"development_symmetric_request_local_operation_compatibility_engine"');
 x=x.replaceAll('./experiment5b13Derivation.ts','./experiment5b14Derivation.ts');
 return x}
