function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b8_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b8PlannerSource(source:string){let x=source;
x=r(x,'import {buildQueryHypotheses5B6,queryCompilerDeterminism5B6} from "./experiment5b6Query.js";','import {queryCompilerDeterminism5B6} from "./experiment5b6Query.js";\nimport {buildGatedQueryHypotheses5B8,querySemanticGateDeterminism5B8} from "./experiment5b8Gate.js";');
x=x.replaceAll('buildQueryHypotheses5B6(baseEvidence,provider)','buildGatedQueryHypotheses5B8(baseEvidence,provider)');
x=r(x,'const queryDet=queryCompilerDeterminism5B6(baseEvidence,provider);metrics.queryCompilerNondeterminismRejects5b6=queryDet.ok?0:1;metrics.queryCompilerFingerprintCount5b6=1;','const queryDet=queryCompilerDeterminism5B6(baseEvidence,provider);metrics.queryCompilerNondeterminismRejects5b6=queryDet.ok?0:1;metrics.queryCompilerFingerprintCount5b6=1;const gateDet=querySemanticGateDeterminism5B8(baseEvidence,provider);metrics.querySemanticGateNondeterminismRejects5b8=gateDet.ok?0:1;metrics.queryExactOperationTransferNondeterminismRejects5b8=gateDet.ok?0:1;metrics.taskIntentSegmentationNondeterminismRejects5b8=gateDet.ok?0:1;');
x=r(x,'materialized.raw.query_operation_witness_5b6=isQuery?{...queryProofById.get(h.id),final_request_ordering_fingerprint:finalFingerprint}:null;','materialized.raw.query_operation_witness_5b6=isQuery?{...queryProofById.get(h.id),final_request_ordering_fingerprint:finalFingerprint}:null;materialized.raw.query_semantic_gate_witness_5b8=isQuery?(queryProofById.get(h.id) as any)?.semantic_gate_witness_5b8??null:null;');
x=r(x,'query_hypothesis_ids_5b6:query.hypotheses.map(h=>h.id),query_proofs_5b6:query.proofs,query_compiler_fingerprint_5b6:query.fingerprint,','query_hypothesis_ids_5b6:query.hypotheses.map(h=>h.id),query_proofs_5b6:query.proofs,query_compiler_fingerprint_5b6:query.fingerprint,query_semantic_audits_5b8:query.audits,query_semantic_gate_fingerprint_5b8:query.fingerprint,');
x=r(x,'query_operation_witness_5b6:materialized.raw.query_operation_witness_5b6,...common}','query_operation_witness_5b6:materialized.raw.query_operation_witness_5b6,query_semantic_gate_witness_5b8:materialized.raw.query_semantic_gate_witness_5b8,...common}');
x=x.replaceAll('export async function synthesize5b6','export async function synthesize5b8').replaceAll('5b6_unknown_case','5b8_unknown_case').replaceAll('5B6_QUERY_ORIENTED:','5B8_ROLE_SEGMENTED_QUERY:').replaceAll('5B6_ALIGNED_OPERATION:','5B8_ALIGNED_OPERATION:').replaceAll('5B6_SECTION_LOCAL_BEAM:','5B8_SECTION_LOCAL_BEAM:').replaceAll('5B6_BEAM_EXHAUSTED','5B8_BEAM_EXHAUSTED');
return x}
