import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {fourAr5Sha} from "./experiment4ar5Core.js";

export const FOUR_AR5R_BASE_SHA="17497b056f633c6d4bc2cef59ea9ba733981a703";
export const FOUR_AR5R_FROZEN_RUN=33030100703;
export const FOUR_AR5R_FROZEN_ARTIFACT=9630749593;
export const FOUR_AR5R_FROZEN_DIGEST="sha256:40cbdb4c4bf325126eb8cebbb6ea7f7c20204ca3df6b425fcfd8905105a6a00b";
export const FOUR_AR5R_FROZEN_REPORT_FP="08f39d2c652a220d750cee4339f6ae4d2045fff0587b89c33a6f536792c70e48";
export const FOUR_AR5R_FROZEN_LEDGER_FP="88d623ed7f96d81477b4dc684c06071231b699359c9b6458e9af515d262eb6f0";
export const FOUR_AR5R_EVIDENCE_MAX_CHARS=18000;

function cited(raw:any,evidence:DocEvidence[],providerId:string){const ids=new Set(Array.isArray(raw?.evidence_ids)?raw.evidence_ids:[]);return evidence.filter(e=>ids.has(e.evidence_id)&&e.provider_candidate_id===providerId&&e.state==="ok");}
function parseVerifiedSummary(text:string){if(!text.startsWith("R5_VERIFIED_API_SPEC"))return null;try{return JSON.parse(text.slice(text.indexOf("\n")+1));}catch{return null;}}
function urlsFrom(v:any,out:string[]=[]):string[]{if(typeof v==="string"){for(const m of v.match(/https:\/\/[^\s"'<>]+/g)||[])out.push(m.replace(/[),;]+$/,""));}else if(Array.isArray(v))for(const x of v)urlsFrom(x,out);else if(v&&typeof v==="object"){if(typeof v.url==="string")urlsFrom(v.url,out);for(const [k,x] of Object.entries(v))if(k!=="url")urlsFrom(x,out);}return [...new Set(out)];}
function sameUrl(a:string,b:string){try{const x=new URL(a),y=new URL(b);return x.protocol===y.protocol&&x.hostname===y.hostname&&x.port===y.port&&x.pathname.replace(/\/$/,"")===y.pathname.replace(/\/$/,"")&&!x.search&&!x.hash&&!y.search&&!y.hash;}catch{return false;}}
export function composeVerifiedOpenApiServerPath(raw:any,evidence:DocEvidence[],providerId:string){if(raw?.decision!=="COMPILE")return null;const base=String(raw?.base_url||""),path=String(raw?.path_template||"");if(!path.startsWith("/")||path.includes("?")||path.includes("#")||path.split("/").includes(".."))return null;let bu:URL;try{bu=new URL(base);}catch{return null;}if(bu.protocol!=="https:"||bu.username||bu.password||bu.search||bu.hash||bu.pathname==="/"||bu.pathname==="")return null;
 for(const e of cited(raw,evidence,providerId)){const summary=parseVerifiedSummary(e.text);if(!summary)continue;const op=Array.isArray(summary.operations)&&summary.operations.some((x:any)=>String(x?.method||"").toUpperCase()==="GET"&&x?.path===path);if(!op)continue;for(const server of urlsFrom(summary.servers||[])){if(!sameUrl(server,base))continue;const su=new URL(server);const prefix=su.pathname.replace(/\/$/,"");const combined=`${prefix}${path}`.replace(/\/{2,}/g,"/");if(!combined.startsWith("/")||combined.split("/").includes(".."))continue;return {base_url:su.origin,path_template:combined,proof:{kind:"openapi_server_path",evidence_id:e.evidence_id,server_url:server,operation_path:path,derived_base_url:su.origin,derived_path_template:combined}};}}
 return null;
}
export function exactOriginGrounding(raw:any,evidence:DocEvidence[],providerId:string){if(raw?.decision!=="COMPILE")return null;let origin:string;try{const u=new URL(String(raw.base_url||""));if(u.protocol!=="https:"||u.username||u.password)return null;origin=u.origin;}catch{return null;}for(const e of cited(raw,evidence,providerId)){if(e.text.includes(origin))return {source:"text_literal" as const,evidence_id:e.evidence_id,origin};try{const eu=new URL(e.resolved_url);if(eu.protocol==="https:"&&eu.origin===origin)return {source:"resolved_url_origin" as const,evidence_id:e.evidence_id,origin};}catch{}}return null;}

function cls(e:DocEvidence){if(e.text.startsWith("R5_VERIFIED_API_SPEC"))return "verified_spec";const t=e.text.toLowerCase(),ct=(e.content_type||"").toLowerCase();if(/openapi|swagger|api-docs/.test(t))return "spec_like";if(/\b(get|endpoint|response|example|schema|parameter)\b/.test(t))return "api_docs";if(ct.includes("json")||ct.includes("yaml"))return "structured_doc";return "prose";}
function genericPenalty(e:DocEvidence){let path="";try{path=new URL(e.resolved_url).pathname.toLowerCase();}catch{}const head=e.text.slice(0,2500).toLowerCase();return /(terms|privacy|cookie|legal|acceptable-use|security-policy|code-of-conduct|community-guidelines)/.test(`${path} ${head}`)?35:0;}
function focus(text:string,needles:string[],budget:number){const lower=text.toLowerCase(),hits:number[]=[];for(const n of needles){let p=0,i=-1;while(n&&(i=lower.indexOf(n.toLowerCase(),p))>=0&&hits.length<20){hits.push(i);p=i+n.length;}}if(!hits.length)return text.slice(0,budget);hits.sort((a,b)=>a-b);const chunks:string[]=[];for(const i of hits){const c=text.slice(Math.max(0,i-500),Math.min(text.length,i+1800));if(!chunks.some(x=>x===c))chunks.push(c);if(chunks.join("\n---\n").length>=budget)break;}return chunks.join("\n---\n").slice(0,budget);}
function group(k:string){if(k==="verified_spec")return "spec";if(k==="spec_like"||k==="api_docs"||k==="structured_doc")return "api";return "prose";}
export function packEvidenceR5R(evidence:DocEvidence[],caseId:string,maxChars=FOUR_AR5R_EVIDENCE_MAX_CHARS){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {items:[],fingerprint:fourAr5Sha([]),total_chars:0,stats:{}};const needles=["https://"," GET ","endpoint","response","example","schema","parameter",...c.input_names,...c.required],perItem={spec:6500,api:4500,prose:2500},quota={spec:7000,api:7500,prose:3500};const seen=new Set<string>(),dropped:any={duplicate:0,quota:0,generic:0},rows=evidence.filter(e=>e.state==="ok").map(e=>{const evidence_class=cls(e),g=group(evidence_class),text=focus(e.text,needles,perItem[g as keyof typeof perItem]),lower=text.toLowerCase();let score=evidence_class==="verified_spec"?120:evidence_class==="spec_like"?80:evidence_class==="api_docs"?60:evidence_class==="structured_doc"?45:20;for(const r of c.required)if(lower.includes(String(r).toLowerCase()))score+=12;for(const i of c.input_names)if(lower.includes(String(i).toLowerCase()))score+=7;const penalty=genericPenalty(e);score-=penalty;const opm=text.match(/"operation_count"\s*:\s*(\d+)/),rpm=text.match(/"response_property_count"\s*:\s*(\d+)/);return {evidence_id:e.evidence_id,url:e.resolved_url,content_type:e.content_type,evidence_class,group:g,score,generic_penalty:penalty,spec_operation_count:Number(opm?.[1]||0),response_property_count:Number(rpm?.[1]||0),text};}).sort((a,b)=>b.score-a.score||a.evidence_id.localeCompare(b.evidence_id)||a.url.localeCompare(b.url));
 const unique=rows.filter(r=>{const fp=fourAr5Sha(r.text.toLowerCase().replace(/\s+/g," ").slice(0,10000));if(seen.has(fp)){dropped.duplicate++;return false;}seen.add(fp);return true;}),items:any[]=[],used:any={spec:0,api:0,prose:0};for(const r of unique){const g=r.group as keyof typeof quota;if(r.generic_penalty&&g==="prose"){dropped.generic++;continue;}const room=Math.min(quota[g]-used[g],maxChars-items.reduce((n,x)=>n+x.text.length,0));if(room<=0){dropped.quota++;continue;}const text=r.text.slice(0,room);if(!text){dropped.quota++;continue;}items.push({...r,text});used[g]+=text.length;}
 const total_chars=items.reduce((n,x)=>n+x.text.length,0),fingerprint=fourAr5Sha(items.map(x=>({evidence_id:x.evidence_id,url:x.url,evidence_class:x.evidence_class,score:x.score,text_fingerprint:fourAr5Sha(x.text)})));return {items,fingerprint,total_chars,stats:{input_items:rows.length,selected_items:items.length,selected_chars_by_group:used,dropped,limit:maxChars}};}
