import {mkdir,writeFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {CASES,MAX_REGISTRY_BYTES,MAX_SPEC_BYTES,PLANNER_CANDIDATE_LIMIT,REGISTRY_TOP_K,REGISTRY_URL,SPEC_FETCH_LIMIT,buildDescriptor,candidateSummary,casesContainNoMappings,descriptorEligibility,flattenRegistry,operationExists,parseContractDocument,rankRegistryRecords,sha,validateSelection,validateSpecUrlSyntax,type Candidate,type CaseDef,type DiscoveryDescriptor,type LiveContract,type RegistryRecord} from "./experiment3qCore.js";
import {fetchTextBounded} from "./experiment3qNetwork.js";
import {callPlanner as callDiscoveryPlanner,parsePlannerSelection} from "./experiment3qPlanner.js";
import {EXEC_CASES,compileRequest,executionReadiness,hasRecipeFingerprintEvidence,induceProjection,makeRecipe,project,runNegativeControls,semanticValidate,validateBindingProgram,type ExecutionCase,type ProcurementPlan,type Recipe} from "./experiment3rCore.js";
import {callProcurementPlanner,parseProcurementPlan} from "./experiment3rPlanner.js";

const OUTDIR="results/experiment-3r";
const MAX_EXEC_BYTES=4*1024*1024;
let registryFetchCalls=0,specFetchCalls=0,discoveryPlannerCalls=0,discoveryRepairCalls=0,procurementPlannerCalls=0,procurementRepairCalls=0,projectionInductionCalls=0;
let authRequiredOperationsExecuted=0,nonGetOperationsExecuted=0,credentialsSupplied=0,arbitraryCodeExecuted=0,redirectsFollowed=0;

async function fetchRegistry(){
  registryFetchCalls++;const {text,content_type}=await fetchTextBounded(REGISTRY_URL,MAX_REGISTRY_BYTES,"application/json");const raw=JSON.parse(text);const records=flattenRegistry(raw);return {records,content_type,registry_fingerprint:sha(text),raw_entry_count:Object.keys(raw).length};
}
async function fetchCaseContracts(c:CaseDef,ranked:RegistryRecord[],cache:Map<string,{contract:LiveContract|null;evidence:any}>){
  const contracts:LiveContract[]=[],evidence:any[]=[];const unique=ranked.filter((r,i,a)=>a.findIndex(x=>x.spec_url===r.spec_url)===i).slice(0,SPEC_FETCH_LIMIT);
  for(const record of unique){let cached=cache.get(record.spec_url);if(!cached){specFetchCalls++;try{const syntax=validateSpecUrlSyntax(record.spec_url);if(!syntax.ok)throw new Error(`spec_url_${syntax.reason}`);const {text,content_type}=await fetchTextBounded(record.spec_url,MAX_SPEC_BYTES,"application/vnd.oai.openapi+json, application/json");const contract=parseContractDocument(record,text);cached={contract,evidence:{api_key:record.api_key,version:record.version,spec_url:record.spec_url,registry_rank:record.registry_rank,registry_score:record.registry_score,content_type,status:"ok",operations:contract.operations.length,spec_fingerprint:contract.spec_fingerprint}};}catch(e){cached={contract:null,evidence:{api_key:record.api_key,version:record.version,spec_url:record.spec_url,registry_rank:record.registry_rank,registry_score:record.registry_score,status:"error",error:String(e)}};}cache.set(record.spec_url,cached);}evidence.push({...cached.evidence,case_id:c.case_id});if(cached.contract)contracts.push({...cached.contract,registry_rank:record.registry_rank,registry_score:record.registry_score});}
  return {contracts,evidence};
}
async function executeJson(url:string){const {text,content_type}=await fetchTextBounded(url,MAX_EXEC_BYTES,"application/json, application/vnd.api+json");let body:any;try{body=JSON.parse(text);}catch{throw new Error("non_json_response");}return {body,content_type};}
function findSelectedContract(contracts:LiveContract[],candidate:Candidate){return contracts.find(x=>x.api_key===candidate.api_key&&operationExists(x.spec,candidate.path,"GET"))||null;}

async function discover(config:any,c:CaseDef,contracts:LiveContract[],candidates:Candidate[],evidence:any[]){
  discoveryPlannerCalls++;let attempt=await callDiscoveryPlanner(config,c,candidates,"initial");evidence.push({case_id:c.case_id,...attempt});let parsed=parsePlannerSelection(attempt);
  if(parsed.error&&(parsed.error.startsWith("planner_contract_invalid")||parsed.error==="planner_json_parse_failure")){discoveryPlannerCalls++;discoveryRepairCalls++;const repair=await callDiscoveryPlanner(config,c,candidates,"repair",parsed.error);evidence.push({case_id:c.case_id,...repair});attempt=repair;parsed=parsePlannerSelection(repair);}
  if(parsed.error||!parsed.selection)return {status:"planner_error",selection:null,candidate:null,contract:null,descriptor:null,error:parsed.error};const validated=validateSelection(parsed.selection,c,candidates);if(validated.errors.length||parsed.selection.decision!=="DISCOVER"||!validated.candidate)return {status:parsed.selection.decision==="REJECT"?"planner_reject":"selection_invalid",selection:parsed.selection,candidate:null,contract:null,descriptor:null,error:validated.errors.join(",")};const candidate=validated.candidate,contract=findSelectedContract(contracts,candidate),eligibility=descriptorEligibility(candidate,contract);if(!eligibility.ok||!contract)return {status:"descriptor_rejected",selection:parsed.selection,candidate,contract,descriptor:null,error:eligibility.errors.join(",")};const descriptor=buildDescriptor(c,parsed.selection,candidate,contract);return {status:"discovered",selection:parsed.selection,candidate,contract,descriptor,error:null};
}

async function procure(config:any,c:CaseDef,execCase:ExecutionCase,candidate:Candidate,readiness:any,evidence:any[]){
  procurementPlannerCalls++;let attempt=await callProcurementPlanner(config,c,execCase,candidate,readiness,"initial");let parsed=parseProcurementPlan(attempt),plan=parsed.plan;let staticResult=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};if(plan&&plan.candidate_id!==candidate.candidate_id)staticResult.errors.push("candidate_id_mismatch");evidence.push({case_id:c.case_id,...attempt,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:staticResult.errors});
  if(parsed.error||staticResult.errors.length){procurementPlannerCalls++;procurementRepairCalls++;const previous=(parsed.error?[parsed.error]:staticResult.errors).join(",");const repair=await callProcurementPlanner(config,c,execCase,candidate,readiness,"repair",previous);parsed=parseProcurementPlan(repair);plan=parsed.plan;staticResult=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};if(plan&&plan.candidate_id!==candidate.candidate_id)staticResult.errors.push("candidate_id_mismatch");evidence.push({case_id:c.case_id,...repair,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:staticResult.errors});}
  return {plan:plan as ProcurementPlan|null,staticResult};
}

async function main(){
  await mkdir(OUTDIR,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3R");const started_at=new Date().toISOString(),controls=runNegativeControls(),controlMap=Object.fromEntries(controls.map(c=>[c.control,c]));const discoveryPlannerEvidence:any[]=[],procurementPlannerEvidence:any[]=[],specEvidence:any[]=[],caseEvidence:any[]=[],recipes:Recipe[]=[];let registry:any={records:[] as RegistryRecord[],content_type:"",registry_fingerprint:"",raw_entry_count:0},registryError:string|null=null;
  try{registry=await fetchRegistry();}catch(e){registryError=String(e);}const cache=new Map<string,{contract:LiveContract|null;evidence:any}>();
  if(!registryError){
    for(const c of CASES){
      const execCase=EXEC_CASES[c.case_id];if(!execCase){caseEvidence.push({case_id:c.case_id,status:"missing_execution_case"});continue;}const ranked=rankRegistryRecords(c,registry.records),fetched=await fetchCaseContracts(c,ranked,cache);specEvidence.push(...fetched.evidence);const candidates=candidateSummary(c,fetched.contracts),discovery=await discover(config,c,fetched.contracts,candidates,discoveryPlannerEvidence);const common={registry_top:ranked.slice(0,10).map(r=>({api_key:r.api_key,title:r.title,score:r.registry_score,rank:r.registry_rank})),contracts_live:fetched.contracts.length,candidate_count:candidates.length,top_candidates:candidates.slice(0,8)};
      if(!discovery.descriptor||!discovery.candidate||!discovery.contract){caseEvidence.push({case_id:c.case_id,status:discovery.status,selection:discovery.selection,error:discovery.error,...common});continue;}
      const readiness=executionReadiness(discovery.contract,discovery.candidate);if(!readiness.ready){caseEvidence.push({case_id:c.case_id,status:"not_publicly_executable",descriptor:discovery.descriptor,candidate:discovery.candidate,readiness,...common});continue;}
      const procurement=await procure(config,c,execCase,discovery.candidate,readiness,procurementPlannerEvidence);if(!procurement.plan||procurement.plan.decision!=="COMPILE"||procurement.staticResult.errors.length){caseEvidence.push({case_id:c.case_id,status:procurement.plan?.decision==="REJECT"?"procurement_reject":"static_reject",descriptor:discovery.descriptor,candidate:discovery.candidate,readiness,procurement_plan:procurement.plan,static_errors:procurement.staticResult.errors,...common});continue;}
      let live:any=null,projection:Record<string,string>|null=null,recipe:Recipe|null=null,error:string|null=null;
      try{if(!readiness.server_base||!readiness.allowed_host)throw new Error("missing_ready_base");const url=compileRequest(readiness.server_base,readiness.allowed_host,discovery.candidate.path,readiness.params,procurement.staticResult.bindings,execCase.build);const response=await executeJson(url);projectionInductionCalls++;projection=induceProjection(response.body,execCase,execCase.build);const out=project(response.body,projection);if(!semanticValidate(execCase,execCase.build,out))throw new Error("semantic_validation_failed");live={request_url_redacted:url,content_type:response.content_type,final_output:out,trace_fingerprint:sha(out)};recipe=makeRecipe(execCase,discovery.descriptor,readiness,procurement.staticResult.bindings,projection);recipes.push(recipe);}catch(e){error=String(e);}
      caseEvidence.push({case_id:c.case_id,status:live?"live_valid":"live_failed",descriptor:discovery.descriptor,candidate:discovery.candidate,readiness:{ready:readiness.ready,errors:readiness.errors,server_base:readiness.server_base,allowed_host:readiness.allowed_host,params:readiness.params},procurement_plan:procurement.plan,static_errors:procurement.staticResult.errors,live,projection,recipe,error,...common});
    }
  }

  const replayCountersBefore={registryFetchCalls,specFetchCalls,discoveryPlannerCalls,procurementPlannerCalls,projectionInductionCalls},replay:any[]=[];
  for(const recipe of recipes){const execCase=EXEC_CASES[recipe.case_id];try{const url=compileRequest(recipe.server_base,recipe.allowed_host,recipe.operation_path,recipe.params,recipe.bindings,execCase.replay);const response=await executeJson(url),out=project(response.body,recipe.projection);if(!semanticValidate(execCase,execCase.replay,out))throw new Error("semantic_validation_failed");replay.push({case_id:recipe.case_id,api_key:recipe.api_key,success:true,input:execCase.replay,final_output:out,request_url_redacted:url,recipe_fingerprint:recipe.recipe_fingerprint,trace_fingerprint:sha(out)});}catch(e){replay.push({case_id:recipe.case_id,api_key:recipe.api_key,success:false,input:execCase.replay,error:String(e),recipe_fingerprint:recipe.recipe_fingerprint});}}
  const replayDeltas={registry_fetch_calls:registryFetchCalls-replayCountersBefore.registryFetchCalls,spec_fetch_calls:specFetchCalls-replayCountersBefore.specFetchCalls,discovery_planner_calls:discoveryPlannerCalls-replayCountersBefore.discoveryPlannerCalls,procurement_planner_calls:procurementPlannerCalls-replayCountersBefore.procurementPlannerCalls,projection_induction_calls:projectionInductionCalls-replayCountersBefore.projectionInductionCalls};

  const discovered=caseEvidence.filter(x=>x.descriptor),ready=caseEvidence.filter(x=>x.readiness?.ready),compiled=caseEvidence.filter(x=>x.procurement_plan?.decision==="COMPILE"&&Array.isArray(x.static_errors)&&x.static_errors.length===0),liveValid=caseEvidence.filter(x=>x.live),replaySuccess=replay.filter(x=>x.success);const distinctDiscovered=new Set(discovered.map(x=>x.descriptor.api_key)).size,distinctReady=new Set(ready.map(x=>x.descriptor.api_key)).size,distinctLive=new Set(liveValid.map(x=>x.descriptor.api_key)).size,distinctRecipeProviders=new Set(recipes.map(x=>x.api_key)).size,replayRate=recipes.length?replaySuccess.length/recipes.length:0,controlsExecuted=controls.filter(x=>x.executed).length,controlsVerified=controls.filter(x=>x.executed&&x.rejected).length,fingerprintEvidence=hasRecipeFingerprintEvidence(recipes);
  const unknownOperationsAccepted=controlMap.operation_absent_from_contract?.rejected?0:1,undeclaredParametersAccepted=controlMap.undeclared_bound_parameter?.rejected?0:1,invalidTypedBindingsAccepted=(controlMap.missing_required_parameter?.rejected&&controlMap.direct_missing_input?.rejected&&controlMap.split_out_of_range?.rejected)?0:1,unsupportedTransformsAccepted=controlMap.unsupported_transform?.rejected?0:1,hostPolicyViolationsAccepted=(controlMap.non_https_execution_base?.rejected&&controlMap.ip_literal_execution_host?.rejected)?0:1;
  const metrics={cases:CASES.length,registry_entry_count:registry.raw_entry_count,registry_fetch_calls:registryFetchCalls,spec_fetch_calls:specFetchCalls,discovery_planner_calls:discoveryPlannerCalls,discovery_repair_calls:discoveryRepairCalls,procurement_planner_calls:procurementPlannerCalls,procurement_repair_calls:procurementRepairCalls,projection_induction_calls:projectionInductionCalls,discovered_cases:discovered.length,distinct_discovered_api_keys:distinctDiscovered,public_ready_cases:ready.length,distinct_public_ready_api_keys:distinctReady,static_compiled_cases:compiled.length,live_valid_cases:liveValid.length,distinct_live_api_keys:distinctLive,persisted_recipes:recipes.length,distinct_recipe_api_keys:distinctRecipeProviders,replay_successes:replaySuccess.length,replay_success_rate:replayRate,replay_deltas:replayDeltas,negative_controls_executed:controlsExecuted,negative_controls_verified:controlsVerified,unknown_operations_accepted:unknownOperationsAccepted,undeclared_parameters_accepted:undeclaredParametersAccepted,invalid_typed_bindings_accepted:invalidTypedBindingsAccepted,unsupported_transforms_accepted:unsupportedTransformsAccepted,auth_required_operations_executed:authRequiredOperationsExecuted,non_get_operations_executed:nonGetOperationsExecuted,host_policy_violations_accepted:hostPolicyViolationsAccepted,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted,fingerprint_evidence:fingerprintEvidence};
  const gates={live_registry_fetched:!registryError&&registry.raw_entry_count>=1,registry_at_least_1000_entries:registry.raw_entry_count>=1000,zero_case_source_mappings:casesContainNoMappings(),at_least_2_cases_discovered:discovered.length>=2,at_least_2_distinct_public_ready_providers:distinctReady>=2,at_least_2_static_compiled_cases:compiled.length>=2,at_least_2_distinct_live_valid_providers:distinctLive>=2,at_least_2_distinct_provider_recipes:recipes.length>=2&&distinctRecipeProviders>=2,replay_100_percent:recipes.length>=2&&replayRate===1,replay_registry_zero:replayDeltas.registry_fetch_calls===0,replay_spec_fetch_zero:replayDeltas.spec_fetch_calls===0,replay_discovery_planner_zero:replayDeltas.discovery_planner_calls===0,replay_procurement_planner_zero:replayDeltas.procurement_planner_calls===0,replay_projection_induction_zero:replayDeltas.projection_induction_calls===0,all_11_negative_controls_verified:controlsExecuted===11&&controlsVerified===11,unknown_operations_zero:unknownOperationsAccepted===0,undeclared_parameters_zero:undeclaredParametersAccepted===0,invalid_typed_bindings_zero:invalidTypedBindingsAccepted===0,unsupported_transforms_zero:unsupportedTransformsAccepted===0,auth_required_executed_zero:authRequiredOperationsExecuted===0,non_get_executed_zero:nonGetOperationsExecuted===0,host_policy_zero:hostPolicyViolationsAccepted===0,redirects_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,fingerprint_evidence_non_vacuous:fingerprintEvidence};
  const formal_decision=Object.values(gates).every(Boolean)?"GO_AUTONOMOUS_DISCOVERY_TO_EXECUTION":"REASSESS_AUTONOMOUS_DISCOVERY_TO_EXECUTION";const report={experiment:"3R",title:"Autonomous Discovery-to-Execution",started_at,finished_at:new Date().toISOString(),formal_decision,registry:{url:REGISTRY_URL,error:registryError,entry_count:registry.raw_entry_count,records_with_spec_url:registry.records.length,content_type:registry.content_type,registry_fingerprint:registry.registry_fingerprint},limits:{registry_top_k:REGISTRY_TOP_K,spec_fetch_limit_per_case:SPEC_FETCH_LIMIT,planner_candidate_limit:PLANNER_CANDIDATE_LIMIT},metrics,gates,cases:caseEvidence,replay,negative_controls:controls};
  await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUTDIR}/discovery-planner-evidence.json`,JSON.stringify(discoveryPlannerEvidence,null,2));await writeFile(`${OUTDIR}/procurement-planner-evidence.json`,JSON.stringify(procurementPlannerEvidence,null,2));await writeFile(`${OUTDIR}/spec-evidence.json`,JSON.stringify(specEvidence,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));
}

main().catch(async e=>{await mkdir(OUTDIR,{recursive:true});const fatal={experiment:"3R",formal_decision:"REASSESS_AUTONOMOUS_DISCOVERY_TO_EXECUTION",fatal_error:String(e),finished_at:new Date().toISOString()};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(fatal,null,2));console.error(e);process.exitCode=1;});
