import {deriveExperiment5b4Source} from "./experiment5b4Derivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b5_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b5Source(source:string){let x=deriveExperiment5b4Source(source);
x=r(x,'import {compile5b4 as compile4ar,project5b4 as project4ar,scope5b4 as scope4ar,validate5b4 as validate4ar,validateProjected5b4 as validateProjected4ar} from "./experiment5b4Contract.js";','import {compile5b5 as compile4ar,project5b5 as project4ar,scope5b5 as scope4ar,validate5b5 as validate4ar,validateProjected5b5 as validateProjected4ar} from "./experiment5b5Contract.js";');
x=r(x,'import {synthesize5b4 as synthesize4ar} from "./experiment5b4Planner.js";','import {synthesize5b5 as synthesize4ar} from "./experiment5b5Planner.js";');
x=r(x,'const OUT="results/experiment-5b4-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b5-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'structured_collection_witness_5b4:a.parsed_json?.structured_collection_witness_5b4??null};','structured_collection_witness_5b4:a.parsed_json?.structured_collection_witness_5b4??null,cross_document_alignment_witness_5b5:a.parsed_json?.cross_document_alignment_witness_5b5??null};');
x=r(x,'structured_collection_witness_5b4:syn.structured_collection_witness_5b4??null,contract,contract_fingerprint:sha3yr(contract)','structured_collection_witness_5b4:syn.structured_collection_witness_5b4??null,cross_document_alignment_witness_5b5:syn.cross_document_alignment_witness_5b5??null,contract,contract_fingerprint:sha3yr(contract)');
x=x.replaceAll('experiment:"5B4-ENGINE"','experiment:"5B5-ENGINE"').replaceAll('purpose:"development_structured_collection_operation_local_utility_engine"','purpose:"development_cross_document_operation_alignment_section_local_evidence_engine"').replaceAll('base_sha:"fc88d67b47edca26c4cc9bdcc0e500370857338d"','base_sha:"7e4471b7eea7fdc958c03d6be7b65b9c4c26adfc"');
x=x.replaceAll('./experiment5b4Planner.ts','./experiment5b5Planner.ts').replaceAll('./experiment5b4Contract.ts','./experiment5b5Contract.ts').replaceAll('./experiment5b4Derivation.ts','./experiment5b5Derivation.ts');
x=x.replace('(await readFile(new URL("./experiment5b4Collection.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b4Collection.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b5Section.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
