import type {P1ProbeProof} from "./experiment4ap1Model.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import {validateRowLookupObserved4O,type RelationalSummary4O} from "./experiment4oRelational.js";
import {materialize4Q} from "./experiment4qCore.js";
import {identityCompatible4Q} from "./experiment4qPreference.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";

export function allowedInputSources4R(output:string,inputs:readonly string[]){return inputs.filter(input=>identityCompatible4Q(output,input))}
function norm(v:string){return lexicalTokensP1(v).join("_")}
function exactRowLookup(summary:RelationalSummary4O,output:string){const target=norm(output),matches:any[]=[];for(const rs of summary.row_sets)for(const label of rs.observed_labels)if(norm(label)===target)matches.push({op:"ROW_LOOKUP",array_path:rs.array_path,label_field:rs.label_field,label_value:label,value_field:rs.value_field});if(matches.length!==1)return null;return matches[0]}
function partialRowLookup(summary:RelationalSummary4O,output:string){const ot=new Set(lexicalTokensP1(output)),rows:any[]=[];for(const rs of summary.row_sets)for(const label of rs.observed_labels){const lt=lexicalTokensP1(label),score=lt.filter(t=>ot.has(t)).length;if(score>0)rows.push({score,expr:{op:"ROW_LOOKUP",array_path:rs.array_path,label_field:rs.label_field,label_value:label,value_field:rs.value_field}})}rows.sort((a,b)=>b.score-a.score||String(a.expr.label_value).localeCompare(String(b.expr.label_value)));if(!rows.length||rows.length>1&&rows[0].score===rows[1].score)return null;return rows[0].expr}
export function deterministicPartialProjection4R(proof:P1ProbeProof,summary:RelationalSummary4O|null,inputs:readonly string[],required:readonly string[]){(proof as any).relational_summary=summary;const projection:ProjectionPlan={},locked:string[]=[],unresolved:string[]=[],used=new Set<string>();let rowLookups=0,identityInputs=0,exactRelationalLabels=0;for(const output of required){const inputMatches=allowedInputSources4R(output,inputs);if(inputMatches.length===1){projection[output]={op:"INPUT",name:inputMatches[0]} as any;locked.push(output);identityInputs++;continue}const outNorm=norm(output),exactFields=proof.record.observed_fields.filter(f=>!used.has(f.id)&&norm(f.leaf)===outNorm);if(exactFields.length===1){used.add(exactFields[0].id);projection[output]={op:"FIELD",path:exactFields[0].path} as any;locked.push(output);continue}const outTokens=new Set(lexicalTokensP1(output)),lexicalFields=proof.record.observed_fields.filter(f=>!used.has(f.id)&&(f.tokens||[]).some(t=>outTokens.has(t)));if(lexicalFields.length===1){used.add(lexicalFields[0].id);projection[output]={op:"FIELD",path:lexicalFields[0].path} as any;locked.push(output);continue}if(summary){const exact=exactRowLookup(summary,output);if(exact&&validateRowLookupObserved4O(exact,summary)){projection[output]=exact as any;locked.push(output);rowLookups++;exactRelationalLabels++;continue}const partial=partialRowLookup(summary,output);if(partial&&validateRowLookupObserved4O(partial,summary)){projection[output]=partial as any;locked.push(output);rowLookups++;continue}}unresolved.push(output)}return {projection,locked,unresolved,rowLookups,identityInputs,exactRelationalLabels}}
export function materialize4R(caseId:string,providerId:string,proof:P1ProbeProof,projection:ProjectionPlan,summary:RelationalSummary4O|null=null){const m=materialize4Q(caseId,providerId,proof,projection,summary);m.raw.reason=String(m.raw.reason||"").replace(/^4Q_EVIDENCE_PREFERENCE_IDENTITY:/,"4R_STRUCTURED_IR_COMPOSITIONAL:");return m}
