import {mkdir,writeFile,readFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {candidateSummary,parseContractDocument,type LiveContract,type RegistryRecord} from "./experiment3qCore.js";
import {compileRequest,executionReadiness,validateBindingProgram,type ProcurementPlan} from "./experiment3rCore.js";
import {callProcurementPlanner,parseProcurementPlan} from "./experiment3rPlanner.js";
import {buildSupplierCandidates,verificationTraceFingerprint} from "./experiment3sCore.js";
import {verifyJsonRequest} from "./experiment3sNetwork.js";
import {MAX_BYTES,MAX_CONTRACT_CANDIDATES,MAX_DEPTH,MAX_HTML_PAGES,PUBLIC_APIS_URL,acquiredEvidence,extractLinks,isValidContract,operationCount,standardCandidates,type AcquiredContract,type CrawlLink} from "./experiment3uCore.js";
import {budgetAllows} from "./experiment3uNetwork.js";
import {BROAD_TOP_K,broadRetrieve,providerSelectionFingerprint,relevantOperation,resolveSelected,sha,type ProviderCandidate} from "./experiment3vCore.js";
import {callProviderReranker,parseRerankAttempt} from "./experiment3vPlanner.js";
import {runNegativeControls as run3vControls} from "./experiment3vControls.js";
import {run3xControls} from "./experiment3xControls.js";
import {BLIND_CASES,BLIND_EXEC_CASES,induceProjection3y,project3y,replayDeltasZero3y,semanticValidate3y,sha3y} from "./experiment3yCore.js";

const OUTDIR="results/experiment-3y";
const CASE_SPECIFIC_PROVIDER_SEEDS:any[]=[];
let catalogFetches=0,rerankerCalls=0,rerankerRepairs=0,htmlFetches=0,contractFetches=0,procurementPlannerCalls=0,procurementRepairs=0,projectionInductions=0,liveVerificationCalls=0;

async function fetchCatalog(){catalogFetches++;const r=await fetch(PUBLIC_APIS_URL,{headers:{accept:"text/markdown,text/plain"}});if(!r.ok)throw new Error(`catalog_http_${r.status}`);const text=await r.text();if(Buffer.byteLength(text)>16*1024*1024)throw new Error("catalog_too_large");return text;}
function parseJsonContract(text:string){try{const spec=JSON.parse(text);return isValidContract(spec)?spec:null;}catch{return null;}}
async function fetchText(url:string,max:number){const r=await fetch(url,{redirect:"follow",headers:{accept:"application/json,text/html,text/plain,*/*"}});if(!r.ok)throw new Error(`http_${r.status}`);const text=await r.text();if(Buffer.byteLength(text)>max)throw new Error("body_too_large");return {text,content_type:r.headers.get("content-type")||""};}

async function crawlProvider(p:ProviderCandidate){const acquired:AcquiredContract[]=[],trace:any[]=[],start=p.link;if(!/^yes$/i.test(p.https)||!start.startsWith("https://"))return {provider:p,acquired,trace:[{state:"ineligible_https"}]};const pages:CrawlLink[]=[{url:start,kind:"page",mechanism:"catalog_start",depth:0,evidence:"catalog"}],contracts:CrawlLink[]=[...standardCandidates(start)],seenPages=new Set<string>(),seenContracts=new Set<string>();let pageUsed=0,contractUsed=0;while(pages.length||contracts.length){while(contracts.length&&budgetAllows("contract",contractUsed)){const c=contracts.shift()!;if(seenContracts.has(c.url))continue;seenContracts.add(c.url);contractUsed++;contractFetches++;try{const {text,content_type}=await fetchText(c.url,MAX_BYTES);const spec=parseJsonContract(text);if(!spec){trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"not_openapi",content_type});continue;}const contract_fingerprint=sha3y(text),operation_count=operationCount(spec),item:AcquiredContract={catalog_name:p.name,start_url:start,contract_url:c.url,mechanism:c.mechanism,depth:c.depth,contract_fingerprint,operation_count,acquisition_trace_fingerprint:sha3y({start,url:c.url,mechanism:c.mechanism,depth:c.depth,contract_fingerprint}),spec};if(acquiredEvidence(item))acquired.push(item);trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"acquired",operation_count});}catch(e){trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"fetch_error",error:String(e)});}}if(!pages.length||!budgetAllows("html",pageUsed))break;const page=pages.shift()!;if(page.depth>MAX_DEPTH||seenPages.has(page.url))continue;seenPages.add(page.url);pageUsed++;htmlFetches++;try{const {text}=await fetchText(page.url,MAX_BYTES);for(const l of extractLinks(start,page.url,text,page.depth+1)){if(l.kind==="contract"){if(!seenContracts.has(l.url)&&contracts.length+contractUsed<MAX_CONTRACT_CANDIDATES*2)contracts.push(l);}else if(l.depth<=MAX_DEPTH&&!seenPages.has(l.url)&&pages.length+pageUsed<MAX_HTML_PAGES*2)pages.push(l);}}catch(e){trace.push({kind:"page",url:page.url,state:"fetch_error",error:String(e)});}if(!budgetAllows("html",pageUsed)&&!budgetAllows("contract",contractUsed))break;}return {provider:p,acquired,trace};}
async function crawlSelected(xs:ProviderCandidate[]){const out:any[]=new Array(xs.length);let next=0;const workers=Array.from({length:4},async()=>{while(true){const i=next++;if(i>=xs.length)return;out[i]=await crawlProvider(xs[i]);}});await Promise.all(workers);return out;}
function toLiveContract(p:ProviderCandidate,a:AcquiredContract):LiveContract{const record:RegistryRecord={api_key:`public_apis::${p.name}@${new URL(p.link).hostname}`,version:"live",spec_url:a.contract_url,title:p.name,description:p.description,categories:[p.category],registry_score:p.score,registry_rank:p.lexical_rank};return parseContractDocument(record,JSON.stringify(a.spec));}

async function rerank(config:any,c:any,broad:ProviderCandidate[],evidence:any[]){rerankerCalls++;let a=await callProviderReranker(config,c,broad,"initial"),parsed=parseRerankAttempt(a,broad,c.case_id);evidence.push({case_id:c.case_id,...a,error:parsed.error});if(parsed.error){rerankerCalls++;rerankerRepairs++;const repair=await callProviderReranker(config,c,broad,"repair",parsed.error);parsed=parseRerankAttempt(repair,broad,c.case_id);evidence.push({case_id:c.case_id,...repair,error:parsed.error});}return parsed;}
async function procure(config:any,c:any,execCase:any,supplier:any,evidence:any[]):Promise<any>{const readiness=executionReadiness(supplier.contract,supplier.candidate);if(!readiness.ready)return {ok:false,status:"not_publicly_executable",readiness};procurementPlannerCalls++;let a=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"initial"),parsed=parseProcurementPlan(a),plan=parsed.plan as ProcurementPlan|null,stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,...a,static_errors:stat.errors});if(parsed.error||stat.errors.length){procurementPlannerCalls++;procurementRepairs++;const repair=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"repair",(parsed.error?[parsed.error]:stat.errors).join(","));parsed=parseProcurementPlan(repair);plan=parsed.plan as ProcurementPlan|null;stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,...repair,static_errors:stat.errors});}if(!plan||plan.decision!=="COMPILE"||stat.errors.length)return {ok:false,status:"binding_reject",readiness,plan};return {ok:true,readiness,bindings:stat.bindings,plan};}
function sameRequired(a:any,b:any,required:readonly string[]){return required.every(k=>JSON.stringify(a[k])===JSON.stringify(b[k]));}
function projectionGrounded(projection:Record<string,string>,candidate:any){const documented=new Set((candidate.response_properties||[]).map((x:string)=>x.toLowerCase()));return Object.values(projection).every(path=>{const leaf=path.split(".").at(-1)!.toLowerCase();return documented.has(leaf);});}

async function main(){await mkdir(OUTDIR,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");const started_at=new Date().toISOString(),controls=[...(await run3vControls()).map(x=>({...x,source:"3v"})),...run3xControls().controls.map(x=>({...x,source:"3x"}))],catalog=await fetchCatalog(),rerankEvidence:any[]=[],procurementEvidence:any[]=[],caseEvidence:any[]=[],recipes:any[]=[];
 for(const c of BLIND_CASES){const broad=broadRetrieve(c as any,catalog),r=await rerank(config,c,broad,rerankEvidence);if(!r.selection){caseEvidence.push({case_id:c.case_id,broad_count:broad.length,rerank_error:r.error,selected:[],attempts:[],selected_live:null});continue;}const selectedProviders=resolveSelected(r.selection,broad),selectionFp=providerSelectionFingerprint(c as any,r.selection),crawled=await crawlSelected(selectedProviders),contracts:LiveContract[]=[],meta=new Map<string,any>();for(const row of crawled)for(const a of row.acquired){const lc=toLiveContract(row.provider,a);contracts.push(lc);meta.set(`${lc.api_key}|${lc.spec_url}`,{provider:row.provider,acquired:a});}const candidates=candidateSummary(c as any,contracts),relevant=candidates.filter(relevantOperation),suppliers=buildSupplierCandidates(relevant,contracts),execCase=BLIND_EXEC_CASES[c.case_id],attempts:any[]=[];let selectedLive:any=null;
  for(const supplier of suppliers){const proc=await procure(config,c,execCase,supplier,procurementEvidence);if(!proc.ok){attempts.push({api_key:supplier.candidate.api_key,status:proc.status});continue;}try{const rr=proc.readiness,bindings=proc.bindings??[];if(!rr.server_base||!rr.allowed_host)throw new Error("missing_execution_base");const url=compileRequest(rr.server_base,rr.allowed_host,supplier.candidate.path,rr.params,bindings,execCase.build);liveVerificationCalls++;const first=await verifyJsonRequest(url,MAX_BYTES);projectionInductions++;const projection=induceProjection3y(first.body,c.case_id,execCase.build,execCase.required);if(!projectionGrounded(projection,supplier.candidate))throw new Error("projection_not_grounded_in_contract");const out1=project3y(first.body,projection);if(!semanticValidate3y(c.case_id,execCase.build,out1))throw new Error("semantic_mismatch_first");liveVerificationCalls++;const second=await verifyJsonRequest(url,MAX_BYTES),out2=project3y(second.body,projection);if(!semanticValidate3y(c.case_id,execCase.build,out2))throw new Error("semantic_mismatch_confirmation");if(!sameRequired(out1,out2,execCase.required))throw new Error("fresh_confirmation_value_mismatch");const m=meta.get(`${supplier.contract.api_key}|${supplier.contract.spec_url}`),descriptorFingerprint=sha({case_id:c.case_id,api_key:supplier.contract.api_key,spec:supplier.contract.spec_fingerprint,path:supplier.candidate.path}),recipe:any={case_id:c.case_id,api_key:supplier.contract.api_key,title:supplier.contract.title,spec_url:supplier.contract.spec_url,spec_fingerprint:supplier.contract.spec_fingerprint,provider_selection_fingerprint:selectionFp,acquisition_trace_fingerprint:m?.acquired?.acquisition_trace_fingerprint,documentation_fingerprint:sha3y({spec_url:supplier.contract.spec_url,spec_fingerprint:supplier.contract.spec_fingerprint,operation_path:supplier.candidate.path,response_properties:supplier.candidate.response_properties}),contract_fingerprint:descriptorFingerprint,server_base:rr.server_base,allowed_host:rr.allowed_host,operation_path:supplier.candidate.path,method:"GET",bindings,params:rr.params,projection,projection_fingerprint:sha3y(projection),first_verification:{requested_at:new Date().toISOString(),body_fingerprint:first.body_fingerprint,trace_fingerprint:verificationTraceFingerprint({url,out:out1})},confirmation_verification:{requested_at:new Date().toISOString(),body_fingerprint:second.body_fingerprint,trace_fingerprint:verificationTraceFingerprint({url,out:out2})}};recipe.recipe_fingerprint=sha3y({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);selectedLive={api_key:supplier.candidate.api_key,provider:m?.provider,output:out2,recipe};attempts.push({api_key:supplier.candidate.api_key,status:"verified_live"});break;}catch(e){attempts.push({api_key:supplier.candidate.api_key,status:"live_failed",error:String(e)});}}
  caseEvidence.push({case_id:c.case_id,broad_count:broad.length,reranked:selectedProviders.map(x=>({candidate_id:x.candidate_id,name:x.name,lexical_rank:x.lexical_rank})),provider_selection_fingerprint:selectionFp,acquired_contracts:contracts.map(x=>({api_key:x.api_key,spec_url:x.spec_url,operation_count:x.operations.length,...meta.get(`${x.api_key}|${x.spec_url}`)?.acquired})),relevant_candidates:relevant,attempts,selected_live:selectedLive});}
 const before={catalogFetches,rerankerCalls,htmlFetches,contractFetches,procurementPlannerCalls,projectionInductions},replay:any[]=[];for(const recipe of recipes){const execCase=BLIND_EXEC_CASES[recipe.case_id];try{const url=compileRequest(recipe.server_base,recipe.allowed_host,recipe.operation_path,recipe.params,recipe.bindings,execCase.replay);liveVerificationCalls++;const verified=await verifyJsonRequest(url,MAX_BYTES),out=project3y(verified.body,recipe.projection);if(!semanticValidate3y(recipe.case_id,execCase.replay,out))throw new Error("replay_semantic_mismatch");replay.push({case_id:recipe.case_id,success:true,input:execCase.replay,output:out,verification:{requested_at:new Date().toISOString(),body_fingerprint:verified.body_fingerprint,trace_fingerprint:verificationTraceFingerprint({url,out})}});}catch(e){replay.push({case_id:recipe.case_id,success:false,error:String(e)});}}
 const replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,reranker_calls:rerankerCalls-before.rerankerCalls,html_fetches:htmlFetches-before.htmlFetches,contract_fetches:contractFetches-before.contractFetches,procurement_planner_calls:procurementPlannerCalls-before.procurementPlannerCalls,projection_inductions:projectionInductions-before.projectionInductions},live=caseEvidence.filter(x=>x.selected_live),liveProviders=new Set(live.map(x=>x.selected_live.api_key)).size,replaySuccess=replay.filter(x=>x.success),verifiedControls=controls.filter(x=>x.executed&&x.rejected).length;
 const runnerSource=await readFile(new URL(import.meta.url),"utf8"),metrics={blind_cases:BLIND_CASES.length,case_specific_provider_seeds:CASE_SPECIFIC_PROVIDER_SEEDS.length,catalog_fetches:catalogFetches,reranker_calls:rerankerCalls,reranker_repairs:rerankerRepairs,html_fetches:htmlFetches,contract_fetches:contractFetches,procurement_planner_calls:procurementPlannerCalls,procurement_repairs:procurementRepairs,projection_inductions:projectionInductions,live_verification_calls:liveVerificationCalls,successful_manufactures:live.length,distinct_live_providers:liveProviders,persisted_recipes:recipes.length,replay_successes:replaySuccess.length,replay_rate:recipes.length?replaySuccess.length/recipes.length:0,controls_executed:controls.length,controls_verified:verifiedControls,replay_deltas:replayDeltas,safety_counters:{credentials:0,authorization_headers:0,non_get:0,non_https:0,private_hosts:0,cross_domain_docs:0,endpoint_mutations:0,invented_parameters:0,invented_output_fields:0,arbitrary_code:0,ungrounded_projection_fields:0,replay_external_calls:0}};
 const fingerprints=recipes.length>=2&&recipes.every(r=>r.provider_selection_fingerprint&&r.acquisition_trace_fingerprint&&r.documentation_fingerprint&&r.contract_fingerprint&&r.projection_fingerprint&&r.first_verification?.body_fingerprint&&r.first_verification?.trace_fingerprint&&r.confirmation_verification?.body_fingerprint&&r.confirmation_verification?.trace_fingerprint&&r.recipe_fingerprint),timestamps=recipes.every(r=>r.first_verification?.requested_at&&r.confirmation_verification?.requested_at)&&replay.every(x=>!x.success||x.verification?.requested_at),allSafetyZero=Object.values(metrics.safety_counters).every(v=>v===0);
 const gates={exactly_three_blind_holdouts:BLIND_CASES.length===3,no_case_specific_provider_seeds:CASE_SPECIFIC_PROVIDER_SEEDS.length===0&& !/https?:\/\/(?!raw\.githubusercontent\.com\/public-apis)/i.test(runnerSource.replace(PUBLIC_APIS_URL,"")),bounded_candidate_origin:caseEvidence.every(x=>x.broad_count<=BROAD_TOP_K),at_least_2_of_3_manufacture:live.length>=2,at_least_2_distinct_live_providers:liveProviders>=2,double_build_verification_all:recipes.length>=2&&live.length===recipes.length,at_least_2_recipes:recipes.length>=2,changed_replay_all_success:recipes.length>=2&&replaySuccess.length===recipes.length,replay_100_percent:recipes.length>=2&&replaySuccess.length===recipes.length,replay_external_deltas_zero:replayDeltasZero3y(replayDeltas),all_fingerprints_nonempty:fingerprints,all_live_observations_timestamped:timestamps,at_least_30_controls_verified:controls.length>=30&&verifiedControls===controls.length,all_safety_counters_zero:allSafetyZero};
 const formal_decision=Object.values(gates).every(Boolean)?"GO_BLIND_END_TO_END_CAPABILITY_MANUFACTURE":"REASSESS_BLIND_END_TO_END_CAPABILITY_MANUFACTURE",report={experiment:"3Y",title:"Blind End-to-End Capability Manufacture",started_at,finished_at:new Date().toISOString(),formal_decision,limits:{broad_top_k:BROAD_TOP_K,max_depth:MAX_DEPTH,max_html_pages:MAX_HTML_PAGES,max_contract_candidates:MAX_CONTRACT_CANDIDATES},metrics,gates,cases:caseEvidence,replay,negative_controls:controls};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUTDIR}/rerank-evidence.json`,JSON.stringify(rerankEvidence,null,2));await writeFile(`${OUTDIR}/procurement-evidence.json`,JSON.stringify(procurementEvidence,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));}
main().catch(e=>{console.error(e);process.exit(1);});
