export const RECOVERY_GLOBALS_5B18='const recoveryMetrics5b18:any={ordinaryFetches5b18:0,reservedRecoveryEligible5b18:0,reservedRecoveryActivated5b18:0,reservedRecoveryFetches5b18:0,reservedRecoveryFetchSuccesses5b18:0,reservedRecoveryFetchFailures5b18:0,reservedRecoveryProvidersBecameExecutable5b18:0,reservedRecoveryUnhealthyProvidersBecameExecutable5b18:0,reservedRecoveryOrderingFingerprintCount5b18:0,reservedRecoveryOrderingNondeterminismViolations5b18:0,ordinaryReserveBorrowingViolations5b18:0,totalFetchBudgetViolations5b18:0,maxOrdinaryFetchesPerProvider5b18:0,maxReservedRecoveryFetchesPerProvider5b18:0,maxTotalAcquisitionFetchesPerProvider5b18:0,maxAcquisitionDepth5b18:0};\nconst recoveryLineage5b18:any[]=[],providerFetchAudit5b18:any[]=[];';

export const RECOVERY_CRAWL_5B18=`async function crawl5b18(provider:Provider4A,ledger:RecoveryLedger,unhealthyAfter5b15:boolean){
 const evidence:DocEvidence[]=[],frontier:any[]=[],queue:any[]=[{url:provider.start_url,depth:0,parent_evidence_ids:[] as string[]}],seen=new Set<string>(),depthByEvidence=new Map<string,number>(),lineages:any[]=[];
 let seq=0,ordinaryFetches=0,reservedFetches=0,totalFetches=0,becameExecutable=false;const queueFingerprints:string[]=[];
 const pushEvidence=(requested_url:string,resolved_url:string,content_type:string,text:string,state:"ok"|"error",depth:number,error?:string)=>{const evidence_id=provider.candidate_id+"-e"+String(++seq).padStart(2,"0");evidence.push({evidence_id,provider_candidate_id:provider.candidate_id,requested_url,resolved_url,verified_at:new Date().toISOString(),status:state==="ok"?200:0,content_type,body_fingerprint:state==="ok"?sha3yr(text):"",text,state,error});depthByEvidence.set(evidence_id,depth);return evidence_id;};
 const fetchOrdinary=async(item:any)=>{if(ordinaryFetches>=FIVE_B18_ORDINARY_FETCH_LIMIT){recoveryMetrics5b18.ordinaryReserveBorrowingViolations5b18++;return null}ordinaryFetches++;totalFetches++;docFetches++;recoveryMetrics5b18.ordinaryFetches5b18++;recoveryMetrics5b18.maxAcquisitionDepth5b18=Math.max(recoveryMetrics5b18.maxAcquisitionDepth5b18,Number(item.depth||0));seen.add(item.url);try{const got=await fetchDocTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"CRAWL",parent_evidence_ids:item.parent_evidence_ids||[]},provider.start_url,item.url,MAX_BYTES,ledger),id=pushEvidence(item.url,got.final_url,got.content_type,got.text,"ok",item.depth);if(/text\\/html/i.test(got.content_type)){const links=extractFrontierLinks(got.final_url,provider.start_url,got.text,id,scope4ar);frontier.push(...links);for(const link of links.filter((z:any)=>z.accepted).slice(0,16))if(item.depth+1<=FOUR_A_BUDGET.max_doc_depth&&!seen.has(link.target_url))queue.push({url:link.target_url,depth:item.depth+1,parent_evidence_ids:[id]});}return {got,id}}catch(e){pushEvidence(item.url,item.url,"","","error",item.depth,String(e));return null}};
 while(queue.length&&ordinaryFetches<FIVE_B18_ORDINARY_FETCH_LIMIT){const item=queue.shift()!;if(item.depth>FOUR_A_BUDGET.max_doc_depth||seen.has(item.url))continue;await fetchOrdinary(item)}
 let surface=recoverySurface5B9(evidence,provider),surfaceBeforeReserved=surface;const reservedEligible=!surface.executable_hypotheses;if(reservedEligible)recoveryMetrics5b18.reservedRecoveryEligible5b18++;
 while(reservedEligible&&!surface.executable_hypotheses&&reservedFetches<FIVE_B18_RESERVED_RECOVERY_LIMIT){const det=reservedRecoveryOrderingDeterminism5B18(evidence,provider,seen,depthByEvidence);recoveryMetrics5b18.reservedRecoveryOrderingFingerprintCount5b18++;queueFingerprints.push(det.fingerprint);if(!det.ok){recoveryMetrics5b18.reservedRecoveryOrderingNondeterminismViolations5b18++;break}const built=buildReservedRecoveryQueue5B18(evidence,provider,seen,depthByEvidence);const candidate=built.queue[0];if(!candidate)break;if(reservedFetches===0)recoveryMetrics5b18.reservedRecoveryActivated5b18++;if(totalFetches>=FIVE_B18_TOTAL_FETCH_LIMIT){recoveryMetrics5b18.totalFetchBudgetViolations5b18++;break}seen.add(candidate.target_url);reservedFetches++;totalFetches++;docFetches++;recoveryMetrics5b18.reservedRecoveryFetches5b18++;recoveryMetrics5b18.maxAcquisitionDepth5b18=Math.max(recoveryMetrics5b18.maxAcquisitionDepth5b18,Number(candidate.depth||0));const before=surface;let fetchOk=false,resultingEvidenceId="",bodyFingerprint="",contentType="",finalUrl=candidate.target_url;
  try{if(candidate.kind==="standard_machine_contract"){specProbeFetches++;const got=await fetchSpecTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"STANDARD_SPEC",parent_evidence_ids:[]},provider.start_url,candidate.target_url,MAX_BYTES,ledger),spec=parseOpenApiText(got.text);contentType=got.content_type;finalUrl=got.final_url;if(spec){const text="Verified API specification at "+got.final_url+"\\n"+specSummary(spec,provider.case_id,got.final_url);resultingEvidenceId=pushEvidence(candidate.target_url,got.final_url,got.content_type,text,"ok",candidate.depth);bodyFingerprint=sha3yr(text);fetchOk=true}else resultingEvidenceId=pushEvidence(candidate.target_url,got.final_url,got.content_type,"","error",candidate.depth,"not_machine_readable_spec");}else{const got=await fetchDocTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"REFERENCE_EXPANSION",parent_evidence_ids:candidate.source_evidence_id?[candidate.source_evidence_id]:[]},provider.start_url,candidate.target_url,MAX_BYTES,ledger);contentType=got.content_type;finalUrl=got.final_url;resultingEvidenceId=pushEvidence(candidate.target_url,got.final_url,got.content_type,got.text,"ok",candidate.depth);bodyFingerprint=sha3yr(got.text);fetchOk=true;if(/text\\/html/i.test(got.content_type)){const links=extractFrontierLinks(got.final_url,provider.start_url,got.text,resultingEvidenceId,scope4ar);frontier.push(...links);}}
   if(fetchOk)recoveryMetrics5b18.reservedRecoveryFetchSuccesses5b18++;else recoveryMetrics5b18.reservedRecoveryFetchFailures5b18++;
  }catch(e){recoveryMetrics5b18.reservedRecoveryFetchFailures5b18++;resultingEvidenceId=pushEvidence(candidate.target_url,candidate.target_url,"","","error",candidate.depth,String(e))}
  surface=recoverySurface5B9(evidence,provider);const base:any={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,recovery_kind:candidate.kind,candidate_url_fingerprint:candidate.target_url_fingerprint,source_evidence_id:candidate.source_evidence_id,queue_ordering_fingerprint:candidate.ordering_fingerprint,fetch_index:reservedFetches,fetch_success:fetchOk,resulting_evidence_id:resultingEvidenceId,resulting_body_fingerprint:bodyFingerprint,content_type:contentType,final_url_fingerprint:sha3yr(finalUrl),surface_before:before,surface_after:surface};const row={...base,lineage_fingerprint:recoveryLineageFingerprint5B9(base)};lineages.push(row);recoveryLineage5b18.push(row);if(!before.executable_hypotheses&&surface.executable_hypotheses){becameExecutable=true;recoveryMetrics5b18.reservedRecoveryProvidersBecameExecutable5b18++;if(unhealthyAfter5b15)recoveryMetrics5b18.reservedRecoveryUnhealthyProvidersBecameExecutable5b18++;break}
 }
 recoveryMetrics5b18.maxOrdinaryFetchesPerProvider5b18=Math.max(recoveryMetrics5b18.maxOrdinaryFetchesPerProvider5b18,ordinaryFetches);recoveryMetrics5b18.maxReservedRecoveryFetchesPerProvider5b18=Math.max(recoveryMetrics5b18.maxReservedRecoveryFetchesPerProvider5b18,reservedFetches);recoveryMetrics5b18.maxTotalAcquisitionFetchesPerProvider5b18=Math.max(recoveryMetrics5b18.maxTotalAcquisitionFetchesPerProvider5b18,totalFetches);if(ordinaryFetches>FIVE_B18_ORDINARY_FETCH_LIMIT)recoveryMetrics5b18.ordinaryReserveBorrowingViolations5b18++;if(reservedFetches>FIVE_B18_RESERVED_RECOVERY_LIMIT||totalFetches>FIVE_B18_TOTAL_FETCH_LIMIT)recoveryMetrics5b18.totalFetchBudgetViolations5b18++;
 providerFetchAudit5b18.push({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,ordinary_fetches:ordinaryFetches,reserved_recovery_eligible:reservedEligible,reserved_recovery_fetches:reservedFetches,total_acquisition_fetches:totalFetches,surface_before_reserved:surfaceBeforeReserved,surface_after_reserved:surface,became_executable_from_reserved_recovery:becameExecutable,recovery_queue_fingerprints:queueFingerprints,lineage_fingerprints:lineages.map(x=>x.lineage_fingerprint)});
 return {evidence,frontier,recovery:{reserved_eligible:reservedEligible,became_executable:becameExecutable,lineages,summary:{ordinary_fetches:ordinaryFetches,reserved_recovery_fetches:reservedFetches,total_fetches:totalFetches,surface_before_reserved:surfaceBeforeReserved,surface_after_reserved:surface,queue_fingerprints:queueFingerprints}}};
}
`;
