import {deriveExperiment4ar7Source} from "./experiment4ar7Derivation.js";

function replaceOnce(source:string,from:string,to:string){
  if(!source.includes(from))throw new Error(`4ap1_derivation_anchor_missing:${from.slice(0,180)}`);
  return source.replace(from,to);
}

const P1_SYNTH=`async function synthesize(config:any,p:Provider4A,docs:DocEvidence[],ledger:RecoveryLedger,evidence:any[]){synthesisCalls++;const a=await synthesize4ar(config,p,docs,ledger);schemaProbeCalls+=a.schemaProbeCalls||0;schemaProbe2xxJson+=a.schemaProbe2xxJson||0;schemaProbeRejected+=a.schemaProbeRejected||0;schemaProbeBytes+=a.schemaProbeBytes||0;const v=a.parsed_json?validate4ar(a.parsed_json,p,docs,ledger,a.probe_proof??null):{errors:[a.parse_error||\`planner_http_\${a.http_status}\`],contract:null,projection:null,probe_proof:null};recordUsage("synthesis",p.case_id,p.candidate_id,a.usage,a.latency_ms);evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...a,static_errors:v.errors,validated_active_schema_proof:v.probe_proof?{hypothesis_id:v.probe_proof.hypothesis.id,probe_schema_fingerprint:v.probe_proof.record.schema_fingerprint,probe_body_fingerprint:v.probe_proof.record.response_body_fingerprint}:null});if(a.parsed_json?.decision==="REJECT"&&!v.errors.length)return {contract:a.parsed_json,projection:null,error:null,probe_proof:null};if(v.errors.length)return {contract:null,projection:null,error:v.errors.join(",")||a.parse_error||null,probe_proof:null};if(v.contract?.decision==="COMPILE"&&v.projection&&v.probe_proof)probeDerivedContracts++;return {contract:v.contract,projection:v.projection,error:null,probe_proof:v.probe_proof};}\n`;

export function deriveExperiment4ap1Source(source:string){
  let result=deriveExperiment4ar7Source(source);
  result=replaceOnce(result,'import {extractFrontierLinks,specSummaryR7,auditProviderBlindSource} from "./experiment4ar7Runtime.js";','import {extractFrontierLinks,specSummaryP1,auditProviderBlindSource} from "./experiment4ap1Runtime.js";');
  result=replaceOnce(result,'import {compile4ar7 as compile4ar,project4ar7 as project4ar,scope4ar7 as scope4ar,validate4ar7 as validate4ar,validateProjected4ar7 as validateProjected4ar} from "./experiment4ar7Contract.js";','import {compile4ap1 as compile4ar,project4ap1 as project4ar,scope4ap1 as scope4ar,validate4ap1 as validate4ar,validateProjected4ap1 as validateProjected4ar} from "./experiment4ap1Contract.js";');
  result=replaceOnce(result,'import {synthesize4ar7 as synthesize4ar} from "./experiment4ar7Planner.js";','import {synthesize4ap1 as synthesize4ar} from "./experiment4ap1Planner.js";');
  result=replaceOnce(result,'const OUT="results/experiment-4ar7",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4ap1",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
  result=replaceOnce(result,'let catalogFetches=0,rerankerCalls=0,docFetches=0,synthesisCalls=0,synthesisRepairs=0,liveCalls=0,specProbeFetches=0;','let catalogFetches=0,rerankerCalls=0,docFetches=0,synthesisCalls=0,synthesisRepairs=0,liveCalls=0,specProbeFetches=0,schemaProbeCalls=0,schemaProbe2xxJson=0,schemaProbeRejected=0,schemaProbeBytes=0,probeDerivedContracts=0,probeConfirmedContracts=0;');
  result=replaceOnce(result,'function specSummary(spec:any,caseId:string,resolvedUrl:string){return specSummaryR7(spec,caseId,resolvedUrl);}','function specSummary(spec:any,caseId:string,resolvedUrl:string){return specSummaryP1(spec,caseId,resolvedUrl);}');

  const synthStart=result.indexOf('async function synthesize('),synthEnd=result.indexOf('function sameRequired',synthStart);
  if(synthStart<0||synthEnd<0)throw new Error("4ap1_synthesize_section_missing");
  result=result.slice(0,synthStart)+P1_SYNTH+result.slice(synthEnd);

  result=replaceOnce(result,'frontier_fingerprint:frontierFingerprint(cr.frontier),documented_operation_proof:syn.operation_proof,contract,contract_fingerprint:sha3yr(contract)','frontier_fingerprint:frontierFingerprint(cr.frontier),active_schema_proof:syn.probe_proof?{hypothesis_id:syn.probe_proof.hypothesis.id,request_proof_type:syn.probe_proof.hypothesis.proof_type,evidence_ids:syn.probe_proof.hypothesis.evidence_ids,source_urls:syn.probe_proof.hypothesis.source_urls,probe_requested_at:syn.probe_proof.record.requested_at,probe_final_url:syn.probe_proof.record.final_url,probe_body_fingerprint:syn.probe_proof.record.response_body_fingerprint,probe_schema_fingerprint:syn.probe_proof.record.schema_fingerprint,observed_path_count:syn.probe_proof.record.observed_path_count}:null,contract,contract_fingerprint:sha3yr(contract)');
  result=replaceOnce(result,'recipes.push(recipe);success={candidate_id:p.candidate_id','recipes.push(recipe);probeConfirmedContracts++;success={candidate_id:p.candidate_id');
  result=replaceOnce(result,'const before={catalogFetches,rerankerCalls,docFetches,synthesisCalls},replay:any[]=[];','const before={catalogFetches,rerankerCalls,docFetches,synthesisCalls,schemaProbeCalls},replay:any[]=[];');
  result=replaceOnce(result,'synthesis_calls:synthesisCalls-before.synthesisCalls}','synthesis_calls:synthesisCalls-before.synthesisCalls,schema_probe_calls:schemaProbeCalls-before.schemaProbeCalls}');

  const auditStart=result.indexOf('coreSource='),auditEnd=result.indexOf(',families=new Set',auditStart);
  if(auditStart<0||auditEnd<0)throw new Error("4ap1_source_audit_section_missing");
  const audit='coreSource=(await readFile(new URL("./experiment4ap1Core.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Runtime.ts",import.meta.url),"utf8")),plannerSource=(await readFile(new URL("./experiment4ap1Planner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Request.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Probe.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ap1Model.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar6rEvidence.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar6rModel.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4ar5Reranker.ts",import.meta.url),"utf8")),contractSource=await readFile(new URL("./experiment4ap1Contract.ts",import.meta.url),"utf8"),seedFree=auditProviderBlindSource([coreSource,plannerSource,contractSource]).clean';
  result=result.slice(0,auditStart)+audit+result.slice(auditEnd);

  result=replaceOnce(result,'fingerprints_timestamps_present:recipes.length>0&&recipes.every(r=>r.provider_selection_fingerprint&&r.documentation_fingerprint&&r.contract_fingerprint&&r.projection_fingerprint&&r.recipe_fingerprint&&r.first_verification?.requested_at&&r.confirmation_verification?.requested_at&&r.documented_operation_proof?.operation_id),real_3x_projection:recipes.length>0&&recipes.every(r=>r.projection_kind==="3x_typed_program")','fingerprints_timestamps_present:recipes.length>0&&recipes.every(r=>r.provider_selection_fingerprint&&r.documentation_fingerprint&&r.contract_fingerprint&&r.projection_fingerprint&&r.recipe_fingerprint&&r.first_verification?.requested_at&&r.confirmation_verification?.requested_at&&r.active_schema_proof?.hypothesis_id&&r.active_schema_proof?.probe_schema_fingerprint&&r.active_schema_proof?.probe_body_fingerprint),real_3x_projection:recipes.length>0&&recipes.every(r=>r.projection_kind==="3x_typed_program"),probe_derived_contract_present:recipes.length>0&&recipes.some(r=>r.active_schema_proof?.probe_schema_fingerprint)');
  result=replaceOnce(result,'specProbeFetches,synthesisCalls,synthesisRepairs,liveCalls,replay_deltas','specProbeFetches,schemaProbeCalls,schemaProbe2xxJson,schemaProbeRejected,schemaProbeBytes,probeDerivedContracts,probeConfirmedContracts,synthesisCalls,synthesisRepairs,liveCalls,replay_deltas');
  result=replaceOnce(result,'"GO_4A_R7_PROOF_GRAPH_FEASIBILITY_SOLVER":"REASSESS_4A_R7_PROOF_GRAPH_FEASIBILITY_SOLVER"','"GO_4A_P1_ACTIVE_SCHEMA_INDUCTION":"REASSESS_4A_P1_ACTIVE_SCHEMA_INDUCTION"');
  result=replaceOnce(result,'experiment:"4A-R7",purpose:"development_proof_graph_feasibility_solver"','experiment:"4A-P1",purpose:"development_active_schema_induction"');
  result=replaceOnce(result,'base_sha:"aa661eb494a2d1bf4c50ee2987da518d8713ed09"','base_sha:"c152a2370ec3640f85e54f435980208f934baef8"');
  return result;
}
