import {readFile,writeFile} from "node:fs/promises";
import {deriveExperiment5b12Source} from "./experiment5b12Derivation.js";
import {deriveExperiment5b12PlannerSource} from "./experiment5b12PlannerDerivation.js";
const planner=await readFile(new URL("./experiment5b6Planner.ts",import.meta.url),"utf8");
await writeFile(new URL("./.generated-experiment5b12Planner.ts",import.meta.url),deriveExperiment5b12PlannerSource(planner));
const source=await readFile(new URL("./experiment4ar.ts",import.meta.url),"utf8");
const generated=deriveExperiment5b12Source(source).replace("async function rerank(async function rerank(","async function rerank(");
await writeFile(new URL("./.generated-experiment5b12.ts",import.meta.url),generated);
const generatedImport="./.generated-experiment5b12.js";
await import(generatedImport);
