import {createHash} from "node:crypto";
import type {DocEvidence} from "./experiment3wCore.js";
import type {P1RequestHypothesis,P1RequestSlot} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import {semanticRole5B2} from "./experiment5b2Semantics.js";

const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
const GENERIC=new Set(["id","identifier","code","name","value","key","q","s","query","search","term","input","number","param","parameter"]);
const GENERIC_QUERY=/^(?:q|s|query|search|term|value|input)$/i;
const HTTP_MARKER=/\b(?:GET|curl|fetch\s*\(|method\s*[:=]\s*["']?GET["']?|"method"\s*:\s*"GET"|endpoint|request|reference)\b/i;
const API_ORIGIN=/\b(?:api|base\s*url|base\s*uri|endpoint|developer|reference)\b/i;
const NAV_HINT=/\b(?:login|signin|signup|register|privacy|terms|careers?|mailing\s*list|postorius|redirect)\b/i;
const JS_NOISE=/(?:=>|function\s*\(|\bconst\b|\blet\b|\bwebpack\b|sourceMappingURL|\.js(?:\?|$))/i;

type ProvenanceClass="machine_contract"|"structured_request_collection"|"executed_structured_trace"|"documented_local_http_example";
export type QualificationWitness5B19={candidate_id:string;qualification_class:ProvenanceClass;source_evidence_ids:string[];source_body_fingerprints:string[];operation_provenance_fingerprint:string;input_bindings:{input:string;slot_name:string;slot_in:"path"|"query";binding_class:"lexical"|"semantic_role_local_anchor"|"generic_query_local_anchors";binding_fingerprint:string}[];qualification_fingerprint:string;ranking_bonus:false};
export type QualificationResult5B19={hypotheses:P1RequestHypothesis[];witnesses:Map<string,QualificationWitness5B19>;metrics:Record<string,number>;fingerprint:string;rejections:{candidate_id:string;reason:string;fingerprint:string}[]};

function norm(v:any){return String(v??"").trim().toLowerCase()}
function tokens(v:any){return lexicalTokensP1(String(v??""))}
function strongTokens(v:any){return tokens(v).filter(t=>t.length>1&&!GENERIC.has(t))}
function overlap(a:any,b:any){const x=new Set(tokens(a));return tokens(b).filter(t=>x.has(t)).length}
function strongOverlap(a:any,b:any){const x=new Set(strongTokens(a));return strongTokens(b).filter(t=>x.has(t)).length}
function evidenceByIds(evidence:DocEvidence[],ids:string[]){const set=new Set(ids);return evidence.filter(e=>set.has(e.evidence_id)&&e.state==="ok")}
function pathOnly(h:P1RequestHypothesis){try{return new URL(h.full_path,h.origin).pathname}catch{return String(h.full_path||"").split("?")[0]||"/"}}
function regexEscape(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function routeRegex(path:string){const escaped=regexEscape(path).replace(/\\\{[^}]+\\\}/g,"[^\\s/?#&<>\"']+");return new RegExp(escaped,"i")}
function localWindow(text:string,index:number,len:number){return text.slice(Math.max(0,index-800),Math.min(text.length,index+len+1000))}
function localRouteEvidence(h:P1RequestHypothesis,rows:DocEvidence[]){const path=pathOnly(h),rr=routeRegex(path);for(const e of rows){const text=String(e.text||"");let m:RegExpExecArray|null;const g=new RegExp(rr.source,"ig");while((m=g.exec(text))){const w=localWindow(text,m.index,m[0].length);if(NAV_HINT.test(w)&&!/(?:curl|\bGET\b|fetch\s*\()/i.test(w))continue;if(JS_NOISE.test(w)&&!/(?:curl|\bGET\b|fetch\s*\()/i.test(w))continue;const marker=HTTP_MARKER.test(w),api=API_ORIGIN.test(w);if(marker&&(api||/(?:curl|\bGET\b|fetch\s*\(|"method"\s*:\s*"GET")/i.test(w)))return {ok:true,evidence:e,span_fingerprint:sha(w),path_fingerprint:sha(path),marker_fingerprint:sha(w.match(HTTP_MARKER)?.[0]||"marker")};} }return {ok:false,evidence:null as DocEvidence|null,span_fingerprint:null,path_fingerprint:sha(path),marker_fingerprint:null}}
function slotFor(h:P1RequestHypothesis,input:string){const id=h.input_bindings?.[input];return h.slots.find(s=>s.id===id)||null}
function localTextForBinding(h:P1RequestHypothesis,rows:DocEvidence[],slot:P1RequestSlot,extra:any){const text=[...rows.map(e=>e.text),JSON.stringify(extra||{}),h.full_path,slot.name].join("\n");return text.slice(0,100000)}
function distinctiveInputAnchors(input:string){return strongTokens(input)}
function distinctiveTaskAnchors(intent:string,input:string){const inputSet=new Set(tokens(input));return strongTokens(intent).filter(t=>!inputSet.has(t))}
function bindingWitness(input:string,slot:P1RequestSlot,intent:string,context:string){const direct=strongOverlap(input,slot.name)>0||norm(input)===norm(slot.name);if(direct)return {ok:true,binding_class:"lexical" as const};const ir=semanticRole5B2(input),sr=semanticRole5B2(slot.name),inputAnchors=distinctiveInputAnchors(input),ctx=new Set(tokens(context));if(GENERIC_QUERY.test(slot.name)){const inputHit=inputAnchors.some(t=>ctx.has(t)),taskHit=distinctiveTaskAnchors(intent,input).some(t=>ctx.has(t));return inputHit&&taskHit?{ok:true,binding_class:"generic_query_local_anchors" as const}:{ok:false,reason:"generic_query_without_dual_local_anchors"}}const sameRole=ir===sr&&ir!=="generic";const localAnchor=inputAnchors.some(t=>ctx.has(t));if(sameRole&&localAnchor)return {ok:true,binding_class:"semantic_role_local_anchor" as const};return {ok:false,reason:`weak_input_parameter_grounding:${ir}:${sr}`}}
function provenance(h:P1RequestHypothesis,rows:DocEvidence[],nativeProof:any,collectionProof:any,queryProof:any,documentaryWitness:any){if(nativeProof)return {ok:true,classification:"machine_contract" as const,source_ids:[nativeProof.source_document_evidence_id,nativeProof.linked_contract_evidence_id,...(h.evidence_ids||[])].filter(Boolean).map(String),meta:{operation_pointer:nativeProof.operation_pointer,method:nativeProof.method,contract_url_fingerprint:sha(nativeProof.contract_url||"")}};if(collectionProof)return {ok:true,classification:"structured_request_collection" as const,source_ids:[collectionProof.source_evidence_id,collectionProof.operation_local_evidence_id,...(h.evidence_ids||[])].filter(Boolean).map(String),meta:{original_method:collectionProof.original_method,original_url_fingerprint:collectionProof.original_url_fingerprint,collection_schema_fingerprint:collectionProof.collection_schema_fingerprint}};if(String(h.proof_type||"").startsWith("4n_executed_trace_"))return {ok:true,classification:"executed_structured_trace" as const,source_ids:(h.evidence_ids||[]).map(String),meta:{proof_type:h.proof_type,source_urls:(h.source_urls||[]).map((x:string)=>sha(x))}};const sourceIds=[queryProof?.source_evidence_id,documentaryWitness?.source_evidence_id,...(h.evidence_ids||[])].filter(Boolean).map(String),sourceRows=evidenceByIds(rows,sourceIds),local=localRouteEvidence(h,sourceRows);if(!local.ok)return {ok:false,reason:"no_explicit_local_http_operation",source_ids:sourceIds,meta:{path_fingerprint:local.path_fingerprint}};return {ok:true,classification:"documented_local_http_example" as const,source_ids:[local.evidence!.evidence_id],meta:{path_fingerprint:local.path_fingerprint,source_span_fingerprint:local.span_fingerprint,marker_fingerprint:local.marker_fingerprint,query_proof_fingerprint:queryProof?sha(queryProof):null,documentary_witness_fingerprint:documentaryWitness?sha(documentaryWitness):null}}}
function metrics0(){return {rawRequestHypotheses5b19:0,admittedRequestHypotheses5b19:0,rejectedRequestHypotheses5b19:0,rejectedNoStrongProvenance5b19:0,rejectedWeakInputBinding5b19:0,admittedMachineContract5b19:0,admittedStructuredCollection5b19:0,admittedExecutedTrace5b19:0,admittedDocumentedLocalHttp5b19:0,urlPresenceOnlyAdmissions5b19:0,broadIdentityOnlyBindingAdmissions5b19:0,qualificationFingerprintCount5b19:1,qualificationNondeterminismViolations5b19:0,qualificationRankingBonusUses5b19:0}}

export function qualifyRequestHypotheses5B19(args:{hypotheses:P1RequestHypothesis[];evidence:DocEvidence[];intent:string;inputNames:readonly string[];nativeProofById:Map<string,any>;collectionProofById:Map<string,any>;queryProofById:Map<string,any>;documentaryWitnessById:Map<string,any>}):QualificationResult5B19{const metrics=metrics0(),witnesses=new Map<string,QualificationWitness5B19>(),kept:P1RequestHypothesis[]=[],rejections:QualificationResult5B19["rejections"]=[];metrics.rawRequestHypotheses5b19=args.hypotheses.length;for(const h of args.hypotheses){const native=args.nativeProofById.get(h.id),collection=args.collectionProofById.get(h.id),query=args.queryProofById.get(h.id),documentary=args.documentaryWitnessById.get(h.id),p=provenance(h,args.evidence,native,collection,query,documentary);if(!p.ok){metrics.rejectedNoStrongProvenance5b19++;metrics.rejectedRequestHypotheses5b19++;rejections.push({candidate_id:h.id,reason:p.reason!,fingerprint:sha({id:h.id,reason:p.reason,source:p.source_ids})});continue}const sourceRows=evidenceByIds(args.evidence,p.source_ids),bindings:QualificationWitness5B19["input_bindings"]=[];let bindingError:string|null=null;for(const input of args.inputNames){const slot=slotFor(h,input);if(!slot){bindingError=`missing_input_slot:${input}`;break}const context=localTextForBinding(h,sourceRows,slot,{native,collection,query,documentary,provenance:p.meta}),b=bindingWitness(input,slot,args.intent,context);if(!b.ok){bindingError=String(b.reason);break}bindings.push({input,slot_name:slot.name,slot_in:slot.in,binding_class:b.binding_class!,binding_fingerprint:sha({input,slot:slot.name,in:slot.in,class:b.binding_class,context_tokens:[...new Set(tokens(context))].sort().slice(0,300)})})}if(bindingError){metrics.rejectedWeakInputBinding5b19++;metrics.rejectedRequestHypotheses5b19++;rejections.push({candidate_id:h.id,reason:bindingError,fingerprint:sha({id:h.id,reason:bindingError})});continue}const bodyFps=sourceRows.map(e=>e.body_fingerprint).filter(Boolean).sort(),provFp=sha({class:p.classification,source:p.source_ids.slice().sort(),meta:p.meta}),base={candidate_id:h.id,qualification_class:p.classification!,source_evidence_ids:[...new Set(p.source_ids)].sort(),source_body_fingerprints:bodyFps,operation_provenance_fingerprint:provFp,input_bindings:bindings,ranking_bonus:false as const},witness:any={...base,qualification_fingerprint:sha(base)};witnesses.set(h.id,witness);kept.push(h);metrics.admittedRequestHypotheses5b19++;if(p.classification==="machine_contract")metrics.admittedMachineContract5b19++;else if(p.classification==="structured_request_collection")metrics.admittedStructuredCollection5b19++;else if(p.classification==="executed_structured_trace")metrics.admittedExecutedTrace5b19++;else metrics.admittedDocumentedLocalHttp5b19++}const fingerprint=sha(kept.map(h=>({id:h.id,w:witnesses.get(h.id)?.qualification_fingerprint})));return {hypotheses:kept,witnesses,metrics,fingerprint,rejections}}

export function qualificationDeterminism5B19(args:Parameters<typeof qualifyRequestHypotheses5B19>[0]){const a=qualifyRequestHypotheses5B19(args),b=qualifyRequestHypotheses5B19(args);return {ok:a.fingerprint===b.fingerprint&&JSON.stringify(a.hypotheses)===JSON.stringify(b.hypotheses)&&JSON.stringify([...a.witnesses.values()])===JSON.stringify([...b.witnesses.values()]),fingerprint:a.fingerprint}}
