import {execFileSync} from "node:child_process";
import {readFileSync} from "node:fs";
import {fiveAWorkloadFingerprint} from "./experiment5aCore.js";
export const FIVE_B14_BASE_SHA="024f9f15660254521519c8984d9c60283ac59d00";
export const FIVE_B14_PREREG_COMMIT="5a652b7356af83fccce45dd08fb65a9b0264e42a";
export function fiveB14PathAllowed(path:string){return path.startsWith("experiments/5b14/")||/^src\/experiment5b14[^/]*\.ts$/.test(path)||/^tests\/experiment5b14[^/]*\.test\.ts$/.test(path)||path===".github/workflows/run-experiment-5b14.yml"}
function git(args:string[],cwd=process.cwd()){return execFileSync("git",args,{cwd,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}
function lines(v:string){return v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
const RESERVED=[".invalid",".test",".example",".localhost"];
export function countRuntimeProviderUrlLiterals5B14(source:string){let count=0;for(const raw of source.match(/https?:\/\/[^\s"'`<>)]+/g)||[]){try{const host=new URL(raw).hostname.toLowerCase();if(host==="localhost"||RESERVED.some(s=>host.endsWith(s)))continue;count++}catch{count++}}return count}
export type FiveB14Integrity={ok:boolean;base_sha:string;prereg_commit:string;head_sha:string;base_is_ancestor:boolean;changed_files:string[];unexpected_files:string[];first_5b14_commit:string|null;prereg_unchanged:boolean;workload_fingerprint:string;runtime_provider_url_literals:number;errors:string[]};
export function inspectFiveB14Integrity(cwd=process.cwd()):FiveB14Integrity{const errors:string[]=[];let head="",ancestor=false,changed:string[]=[],first:string|null=null,prereg=true,urlLiterals=0;try{head=git(["rev-parse","HEAD"],cwd)}catch(e){errors.push(`head_unavailable:${String(e)}`)}try{execFileSync("git",["merge-base","--is-ancestor",FIVE_B14_BASE_SHA,"HEAD"],{cwd,stdio:"ignore"});ancestor=true}catch{errors.push("base_not_ancestor")}try{changed=lines(git(["diff","--name-only",`${FIVE_B14_BASE_SHA}..HEAD`],cwd))}catch(e){errors.push(`diff_unavailable:${String(e)}`)}const unexpected=changed.filter(p=>!fiveB14PathAllowed(p));if(unexpected.length)errors.push(`unexpected_changed_files:${unexpected.join(",")}`);try{const commits=lines(git(["log","--reverse","--format=%H",`${FIVE_B14_BASE_SHA}..HEAD`,`--`,`experiments/5b14`,`src`,`tests`,`.github/workflows/run-experiment-5b14.yml`],cwd));first=commits[0]||null;if(first!==FIVE_B14_PREREG_COMMIT)errors.push(`prereg_not_first:${first||"none"}`)}catch(e){errors.push(`history_unavailable:${String(e)}`)}try{prereg=!git(["diff","--name-only",`${FIVE_B14_PREREG_COMMIT}..HEAD`,`--`,`experiments/5b14/README.md`],cwd);if(!prereg)errors.push("prereg_modified")}catch(e){errors.push(`prereg_diff_unavailable:${String(e)}`)}for(const file of changed.filter(p=>/^src\/experiment5b14.*\.ts$/.test(p))){try{urlLiterals+=countRuntimeProviderUrlLiterals5B14(readFileSync(`${cwd}/${file}`,"utf8"))}catch{}}if(urlLiterals)errors.push(`runtime_provider_url_literals:${urlLiterals}`);return {ok:errors.length===0,base_sha:FIVE_B14_BASE_SHA,prereg_commit:FIVE_B14_PREREG_COMMIT,head_sha:head,base_is_ancestor:ancestor,changed_files:changed,unexpected_files:unexpected,first_5b14_commit:first,prereg_unchanged:prereg,workload_fingerprint:fiveAWorkloadFingerprint(),runtime_provider_url_literals:urlLiterals,errors}}
