import {deriveExperiment5b8Source} from "./experiment5b8Derivation.js";

function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b9_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
function replaceBetween(s:string,start:string,end:string,replacement:string){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);if(a<0||b<0)throw new Error(`5b9_range_anchor_missing:${start}`);return s.slice(0,a)+replacement+s.slice(b)}

const RECOVERY_CRAWL=`async function crawl5b9(provider:Provider4A,ledger:RecoveryLedger,originalStart:string){
 const evidence:DocEvidence[]=[],frontier:any[]=[],queue:any[]=[{url:provider.start_url,depth:0}],seen=new Set<string>(),depthByEvidence=new Map<string,number>(),lineages:any[]=[];
 let seq=0,fetchCount=0,recoveryFetchCount=0,recoveryActivated=false,becameExecutable=false;
 const maxPages=FOUR_A_BUDGET.max_doc_pages_per_provider,initialUpgrade=String(originalStart).startsWith("http://")?httpsUpgradeCandidate5B9(originalStart):null;
 if(String(originalStart).startsWith("http://")){recoveryMetrics5b9.httpsUpgradeCandidates5b9++;recoveryMetrics5b9.selectedProviderAcquisitionStarved5b9++;if(initialUpgrade){recoveryActivated=true;recoveryMetrics5b9.selectedProviderRecoveryActivated5b9++;}else recoveryMetrics5b9.httpsUpgradeRejectedScope5b9++;}
 const pushEvidence=(requested_url:string,resolved_url:string,content_type:string,text:string,state:"ok"|"error",depth:number,error?:string)=>{const evidence_id=provider.candidate_id+"-e"+String(++seq).padStart(2,"0");evidence.push({evidence_id,provider_candidate_id:provider.candidate_id,requested_url,resolved_url,verified_at:new Date().toISOString(),status:state==="ok"?200:0,content_type,body_fingerprint:state==="ok"?sha3yr(text):"",text,state,error});depthByEvidence.set(evidence_id,depth);return evidence_id;};
 const persistLineage=(reason:"https_upgrade"|"explicit_same_provider_link",candidate:any,item:any,fetchStatus:number,contentType:string,resultingEvidenceId:string,resultingBodyFingerprint:string,before:any,after:any,finalUrl:string)=>{const base:any={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,source_evidence_ids:candidate?[candidate.source_evidence_id]:[],source_body_fingerprints:candidate?[candidate.source_body_fingerprint]:[],candidate_url_fingerprint:candidate?.target_url_fingerprint??sha3yr(item.url),normalized_origin_fingerprint:sha3yr((()=>{try{return new URL(finalUrl||provider.start_url).origin.toLowerCase()}catch{return provider.start_url}})()),recovery_reason:reason,anchor_context_fingerprint:candidate?.anchor_context_fingerprint??null,recovery_utility_tuple:candidate?[candidate.score,candidate.reasons]:[0,["scheme_only_https_upgrade"]],recovery_ordering_fingerprint:candidate?.ordering_fingerprint??initialUpgrade?.fingerprint??"",fetch_status:fetchStatus,fetch_content_type:contentType,resulting_evidence_id:resultingEvidenceId,resulting_body_fingerprint:resultingBodyFingerprint,operation_inventory_before:before.get_operations,operation_inventory_after:after.get_operations,request_hypotheses_before:before.executable_hypotheses,request_hypotheses_after:after.executable_hypotheses,budget_slot_index:fetchCount};const row={...base,lineage_fingerprint:recoveryLineageFingerprint5B9(base)};lineages.push(row);recoveryLineage5b9.push(row);};
 const fetchOne=async(item:any,reason:null|"https_upgrade"|"explicit_same_provider_link",candidate:any=null)=>{if(fetchCount>=maxPages)return null;const before=recoverySurface5B9(evidence,provider);seen.add(item.url);fetchCount++;docFetches++;recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9=Math.max(recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9,Number(item.depth||0));if(reason){recoveryFetchCount++;recoveryMetrics5b9.recoveryFetchAttempts5b9++;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeFetches5b9++;}
  try{const got=await fetchTextSafeR2(provider.start_url,item.url,MAX_BYTES,ledger),id=pushEvidence(item.url,got.final_url,got.content_type,got.text,"ok",item.depth);if(reason){recoveryMetrics5b9.recoveryFetchSuccesses5b9++;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeAccepted5b9++;const after=recoverySurface5B9(evidence,provider),opDelta=Math.max(0,after.get_operations-before.get_operations),hypDelta=Math.max(0,after.executable_hypotheses-before.executable_hypotheses);recoveryMetrics5b9.recoveryExecutableOperationsAdded5b9+=opDelta;recoveryMetrics5b9.recoveryRequestHypothesesAdded5b9+=hypDelta;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeRecoveredOperations5b9+=opDelta;if(!before.executable_hypotheses&&after.executable_hypotheses){becameExecutable=true;recoveryMetrics5b9.recoveryStoppedOnExecutableSurface5b9++;}persistLineage(reason,candidate,item,200,got.content_type,id,sha3yr(got.text),before,after,got.final_url);}return {got,id};}
  catch(e){const id=pushEvidence(item.url,item.url,"","","error",item.depth,String(e));if(reason){recoveryMetrics5b9.recoveryFetchFailures5b9++;persistLineage(reason,candidate,item,0,"",id,"",before,before,item.url);}return null;}
 };
 while(queue.length&&fetchCount<maxPages){const item=queue.shift()!;if(item.depth>FOUR_A_BUDGET.max_doc_depth||seen.has(item.url))continue;const first=fetchCount===0&&!!initialUpgrade&&item.url===provider.start_url,result=await fetchOne(item,first?"https_upgrade":null);if(result&&/text\\/html/i.test(result.got.content_type)){const links=extractFrontierLinks(result.got.final_url,provider.start_url,result.got.text,result.id,scope4ar);frontier.push(...links);for(const link of links.filter((z:any)=>z.accepted).slice(0,16))if(item.depth+1<=FOUR_A_BUDGET.max_doc_depth&&!seen.has(link.target_url))queue.push({url:link.target_url,depth:item.depth+1});}}
 let origin:string|null=null;try{origin=new URL(provider.start_url).origin}catch{}
 if(origin){for(const path of STANDARD_SPEC_PATHS){if(fetchCount>=maxPages)break;const url=new URL(path,origin).toString();if(seen.has(url))continue;seen.add(url);fetchCount++;specProbeFetches++;docFetches++;recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9=Math.max(recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9,1);try{const got=await fetchTextSafeR2(provider.start_url,url,MAX_BYTES,ledger),spec=parseOpenApiText(got.text);if(spec)pushEvidence(url,got.final_url,got.content_type,"Verified API specification at "+got.final_url+"\\n"+specSummary(spec),"ok",1);else pushEvidence(url,got.final_url,got.content_type,"","error",1,"not_machine_readable_spec");}catch(e){pushEvidence(url,url,"","","error",1,String(e));}}}
 let surface=recoverySurface5B9(evidence,provider);
 if(!surface.executable_hypotheses&&!recoveryActivated){recoveryMetrics5b9.selectedProviderAcquisitionStarved5b9++;if(fetchCount<maxPages){recoveryActivated=true;recoveryMetrics5b9.selectedProviderRecoveryActivated5b9++;}else recoveryMetrics5b9.selectedProviderRecoverySkippedBudgetExhausted5b9++;}else if(surface.executable_hypotheses&&!recoveryActivated)recoveryMetrics5b9.selectedProviderRecoverySkippedExecutableSurfacePresent5b9++;
 while(recoveryActivated&&!surface.executable_hypotheses&&fetchCount<maxPages){const det=recoveryLinkOrderingDeterminism5B9(evidence,provider,seen,depthByEvidence);recoveryMetrics5b9.recoveryLinkOrderingFingerprintCount5b9++;if(!det.ok){recoveryMetrics5b9.recoveryLinkOrderingNondeterminismRejects5b9++;break}const built=buildRecoveryLinkQueue5B9(evidence,provider,seen,depthByEvidence);addRecoveryMetrics5b9({...built.metrics,recoveryLinkOrderingFingerprintCount5b9:0,recoveryLinkOrderingNondeterminismRejects5b9:0});const candidate=built.queue.find((z:any)=>z.depth<=FOUR_A_BUDGET.max_doc_depth);if(!candidate)break;await fetchOne({url:candidate.target_url,depth:candidate.depth},"explicit_same_provider_link",candidate);surface=recoverySurface5B9(evidence,provider);if(surface.executable_hypotheses)break;}
 if(recoveryActivated&&!surface.executable_hypotheses&&fetchCount>=maxPages)recoveryMetrics5b9.recoveryStoppedOnBudget5b9++;
 recoveryMetrics5b9.maxDocumentationFetchesPerProvider5b9=Math.max(recoveryMetrics5b9.maxDocumentationFetchesPerProvider5b9,fetchCount);providerFetchAudit5b9.push({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,ordinary_plus_recovery_fetches:fetchCount,recovery_fetches:recoveryFetchCount,max_depth:Math.max(0,...depthByEvidence.values()),recovery_activated:recoveryActivated,executable_surface:surface,lineage_fingerprints:lineages.map(x=>x.lineage_fingerprint)});
 return {evidence,frontier,recovery:{activated:recoveryActivated,became_executable:becameExecutable,lineages,summary:{fetches:fetchCount,recovery_fetches:recoveryFetchCount,surface}}};
}
`;

const RECOVERY_GLOBALS='const recoveryMetrics5b9:any={selectedProviderAcquisitionStarved5b9:0,selectedProviderRecoveryActivated5b9:0,selectedProviderRecoverySkippedBudgetExhausted5b9:0,selectedProviderRecoverySkippedExecutableSurfacePresent5b9:0,httpsUpgradeCandidates5b9:0,httpsUpgradeFetches5b9:0,httpsUpgradeAccepted5b9:0,httpsUpgradeRejectedScope5b9:0,httpsUpgradeRecoveredOperations5b9:0,recoveryLinkCandidates5b9:0,recoveryLinkAccepted5b9:0,recoveryLinkRejectedScope5b9:0,recoveryLinkRejectedNoise5b9:0,recoveryLinkAlreadyFetched5b9:0,recoveryLinkOrderingFingerprintCount5b9:0,recoveryLinkOrderingNondeterminismRejects5b9:0,recoveryFetchAttempts5b9:0,recoveryFetchSuccesses5b9:0,recoveryFetchFailures5b9:0,recoveryStoppedOnExecutableSurface5b9:0,recoveryStoppedOnBudget5b9:0,recoveryExecutableOperationsAdded5b9:0,recoveryRequestHypothesesAdded5b9:0,recoveryDerivedHypothesesEnteredBeam5b9:0,maxDocumentationFetchesPerProvider5b9:0,maxRecoveryPlusOrdinaryDepth5b9:0};\nconst recoveryLineage5b9:any[]=[],providerFetchAudit5b9:any[]=[];\nfunction addRecoveryMetrics5b9(src:any){for(const [k,v] of Object.entries(src||{}))if(typeof v==="number")recoveryMetrics5b9[k]=(recoveryMetrics5b9[k]||0)+v;}';

export function deriveExperiment5b9Source(source:string){let x=deriveExperiment5b8Source(source);
 x='import {buildRecoveryLinkQueue5B9,httpsUpgradeCandidate5B9,recoveryLineageFingerprint5B9,recoveryLinkOrderingDeterminism5B9,recoverySurface5B9} from "./experiment5b9Recovery.js";\n'+x;
 x=r(x,'import {compile5b8 as compile4ar,project5b8 as project4ar,scope5b8 as scope4ar,validate5b8 as validate4ar,validateProjected5b8 as validateProjected4ar} from "./experiment5b8Contract.js";','import {compile5b9 as compile4ar,project5b9 as project4ar,scope5b9 as scope4ar,validate5b9 as validate4ar,validateProjected5b9 as validateProjected4ar} from "./experiment5b9Contract.js";');
 x=r(x,'import {synthesize5b8 as synthesize4ar} from "./.generated-experiment5b8Planner.js";','import {synthesize5b9 as synthesize4ar} from "./.generated-experiment5b9Planner.js";');
 x=r(x,'const OUT="results/experiment-5b8-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b9-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;\n'+RECOVERY_GLOBALS);
 x=replaceBetween(x,'async function crawl(provider:Provider4A,ledger:RecoveryLedger){','async function rerank(',RECOVERY_CRAWL);
 x=r(x,'for(const s of selected.slice(0,FOUR_A_BUDGET.max_provider_attempts_per_case)){if(!String(s.link).startsWith("https://")){attempts.push({candidate_id:s.candidate_id,name:s.name,status:"provider_ineligible",reason:"non_https_catalog_start"});continue;}const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:s.link},cr=await crawl(p,ledger),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence);','for(const s of selected.slice(0,FOUR_A_BUDGET.max_provider_attempts_per_case)){const originalStart=String(s.link),upgrade=originalStart.startsWith("http://")?httpsUpgradeCandidate5B9(originalStart):null,effectiveStart=originalStart.startsWith("https://")?originalStart:upgrade?.url??null;if(!effectiveStart){attempts.push({candidate_id:s.candidate_id,name:s.name,status:"provider_ineligible",reason:"non_https_catalog_start_not_upgradeable"});continue;}const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:effectiveStart},cr=await crawl5b9(p,ledger,originalStart),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence);if(cr.recovery?.became_executable&&syn.contract?.decision==="COMPILE")recoveryMetrics5b9.recoveryDerivedHypothesesEnteredBeam5b9++;');
 x=r(x,'provider_start_url:p.start_url,provider_selection_fingerprint:selectionFp,documentation_fingerprint:','provider_start_url:p.start_url,provider_catalog_start_url:originalStart,provider_selection_fingerprint:selectionFp,documentation_fingerprint:');
 x=r(x,'query_semantic_gate_witness_5b8:syn.query_semantic_gate_witness_5b8??null,contract,contract_fingerprint:sha3yr(contract)','query_semantic_gate_witness_5b8:syn.query_semantic_gate_witness_5b8??null,recovery_lineage_5b9:cr.recovery?.became_executable?cr.recovery.lineages:[],recovery_surface_witness_5b9:cr.recovery?.became_executable?cr.recovery.summary:null,contract,contract_fingerprint:sha3yr(contract)');
 x=r(x,'const before={catalogFetches,rerankerCalls,docFetches,synthesisCalls},replay:any[]=[];','const before={catalogFetches,rerankerCalls,docFetches,synthesisCalls,recoveryFetchAttempts5b9:recoveryMetrics5b9.recoveryFetchAttempts5b9},replay:any[]=[];');
 x=r(x,'replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,reranker_calls:rerankerCalls-before.rerankerCalls,documentation_fetches:docFetches-before.docFetches,synthesis_calls:synthesisCalls-before.synthesisCalls}','replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,reranker_calls:rerankerCalls-before.rerankerCalls,documentation_fetches:docFetches-before.docFetches,synthesis_calls:synthesisCalls-before.synthesisCalls,recovery_fetches:recoveryMetrics5b9.recoveryFetchAttempts5b9-before.recoveryFetchAttempts5b9}');
 x=r(x,'metrics:{cases:24,families:8,successful_manufactures:successful.length,','metrics:{...recoveryMetrics5b9,cases:24,families:8,successful_manufactures:successful.length,');
 x=r(x,'synthesisEvidence,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};','synthesisEvidence,recoveryLineage5b9,providerFetchAudit5b9,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};');
 x=x.replaceAll('experiment:"5B8-ENGINE"','experiment:"5B9-ENGINE"').replaceAll('purpose:"development_role_segmented_typed_operation_transfer_engine"','purpose:"development_verified_selected_provider_acquisition_recovery_engine"').replaceAll('base_sha:"3c946337f75079f22ab9b07d0a48d3fe574d9c98"','base_sha:"0abd49ebb2e4c081e1f92f0fb178b49091c7499e"');
 x=x.replaceAll('./experiment5b8Contract.ts','./experiment5b9Contract.ts').replaceAll('./experiment5b8Derivation.ts','./experiment5b9Derivation.ts');
 x=x.replace('(await readFile(new URL("./experiment5b8Gate.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b8Gate.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b9Recovery.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
 return x}
