import {createHash} from "node:crypto";
import type {FiveB11Integrity} from "./experiment5b11Harness.js";
const sha=(v:any)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
function collect(node:any,out:any){if(Array.isArray(node)){for(const x of node)collect(x,out);return}if(!node||typeof node!=="object")return;for(const [k,v] of Object.entries(node)){if(typeof v==="number"&&/(5b10|5b11)$/i.test(k))out[k]=(out[k]||0)+v;else if(v&&typeof v==="object")collect(v,out)}}
function templateWitness(r:any){return r?.template_witness_5b11||r?.contract?.raw?.template_witness_5b11||null}
export function buildFiveB11Report(raw:any,integrity:FiveB11Integrity,baseline:any){const planner:any={};collect(raw?.synthesisEvidence||[],planner);const ce=Array.isArray(raw?.caseEvidence)?raw.caseEvidence:[],success=ce.filter((r:any)=>r?.success),recipes=Array.isArray(raw?.recipes)?raw.recipes:[],replay=Array.isArray(raw?.replay)?raw.replay:[],successIds=new Set(success.map((r:any)=>String(r.case_id))),strictRecipes=recipes.filter((r:any)=>successIds.has(String(r.case_id))),templateRecipes=strictRecipes.filter((r:any)=>templateWitness(r)),templateIds=new Set(templateRecipes.map((r:any)=>String(r.case_id))),templateReplay=replay.filter((r:any)=>templateIds.has(String(r.case_id))&&r.success===true),familyByCase=new Map(success.map((r:any)=>[String(r.case_id),String(r.family)])),frozenFamilies=new Set((baseline?.strict_success_families||[]).map(String)),newFamily=templateRecipes.filter((r:any)=>{const f=familyByCase.get(String(r.case_id));return !!f&&!frozenFamilies.has(f)}),rm=raw?.metrics||{},replayRate=strictRecipes.length?replay.filter((r:any)=>r.success===true).length/strictRecipes.length:0;
 const metrics:any={cases:ce.length,strict_successes:success.length,families_with_success:new Set(success.map((r:any)=>r.family)).size,distinct_providers:new Set(success.map((r:any)=>r?.success?.host).filter(Boolean)).size,persisted_recipes:strictRecipes.length,replay_successes:replay.filter((r:any)=>r.success===true).length,replay_rate:replayRate,...planner,template_strict_recipes:templateRecipes.length,template_changed_input_replay_successes:templateReplay.length,template_new_family_recipes:newFamily.length,template_end_to_end_lineage_complete:templateRecipes.length>0&&templateRecipes.every((r:any)=>{const w=templateWitness(r);return w&&Number(w.beam_position)>=1&&Number(w.beam_position)<=2&&w.ranking_bonus===false}),frozen_5b10_success_family_count:frozenFamilies.size};
 const gates:any={integrity:integrity.ok,all_18_cases_complete:ce.length===18,at_least_6_successes:success.length>=6,at_least_6_families:metrics.families_with_success>=6,at_least_6_providers:metrics.distinct_providers>=6,replay_rate_95:replayRate>=.95,every_success_has_recipe:strictRecipes.length===success.length,template_built:Number(planner.documentedTemplatesBuilt5b11||0)>=1,template_binding_active:Number(planner.templateBindingsAccepted5b11||0)>=1,template_beam_entry:Number(planner.templateBeamEntries5b11||0)>=1,template_executed:Number(planner.templateExecutedCandidates5b11||0)>=1,template_strict_recipe:templateRecipes.length>=1,template_replay:templateReplay.length>=1,template_new_family:newFamily.length>=1,template_lineage_complete:metrics.template_end_to_end_lineage_complete,template_geometry_clean:Number(planner.templateGeometryMutationRejects5b11||0)>=0,bound_example_values_retained_zero:Number(planner.templateBoundExampleValuesRetained5b11||0)===0,ungrounded_example_constants_zero:Number(planner.templateUngroundedExampleConstants5b11||0)===0,template_ranking_bonus_zero:Number(planner.templateRankingBonusUses5b11||0)===0,global_beam_size_2:Number(planner.globalBeamSizeMax5b10||0)<=2,provider_ordering_nondeterminism_zero:Number(rm.providerOrderingNondeterminismRejects5b3||rm.provider_ordering_nondeterminism_rejects||0)===0,request_ordering_nondeterminism_zero:Number(rm.requestOrderingNondeterminismRejects5b3||rm.request_ordering_nondeterminism_rejects||0)===0,replay_recovery_zero:Number(rm?.replay_deltas?.recovery_fetches||0)===0,prior_baseline_present:frozenFamilies.size===5};
 const report:any={experiment:"5B11",purpose:"development_evidence_faithful_documented_request_template_compilation",base_sha:"87c5f9569b82b725cdd8a46f21b9bb67d4bbc778",prereg_commit:"52726a695e518686689eea1f3cc8475392d86425",decision:Object.values(gates).every(Boolean)?"GO_5B11_EVIDENCE_FAITHFUL_DOCUMENTED_REQUEST_TEMPLATE_COMPILATION":"REASSESS_5B11_EVIDENCE_FAITHFUL_DOCUMENTED_REQUEST_TEMPLATE_COMPILATION",metrics,gates,integrity,frozen_5b10_success_families:[...frozenFamilies].sort(),engine_decision:raw?.decision||null,engine_fingerprint:raw?.fingerprint||null};report.fingerprint=sha(report);return report}
