import {deriveExperiment4sSource} from "./experiment4sDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4t_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4tSource(source:string){let x=deriveExperiment4sSource(source);
x=r(x,'import {compile4s as compile4ar,project4s as project4ar,scope4s as scope4ar,validate4s as validate4ar,validateProjected4s as validateProjected4ar} from "./experiment4sContract.js";','import {compile4t as compile4ar,project4t as project4ar,scope4t as scope4ar,validate4t as validate4ar,validateProjected4t as validateProjected4ar} from "./experiment4tContract.js";');
x=r(x,'import {synthesize4s as synthesize4ar} from "./experiment4sPlanner.js";','import {synthesize4t as synthesize4ar} from "./experiment4tPlanner.js";');
x=r(x,'const OUT="results/experiment-4s",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4t",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'linkedContractResponseGroundings4s=0;const rerankConcurrencyLimit4p=3;','linkedContractResponseGroundings4s=0,nativeContractsParsed4t=0,nativeContractsJsonParsed4t=0,nativeContractsYamlParsed4t=0,nativeLocalRefsResolved4t=0,nativeLocalRefsRejected4t=0,nativeExternalRefsRejected4t=0,nativeOperationsDiscovered4t=0,nativeOperationsEligible4t=0,nativeOperationsRejectedAuth4t=0,nativeOperationsRejectedUnsupportedRequest4t=0,nativeOperationsRejectedSemanticMismatch4t=0,nativeOperationHypotheses4t=0,nativeOperationUniqueInputBindings4t=0,nativeOperationAmbiguousBindings4t=0,nativeOperationProbeCalls4t=0,nativeOperationProbeStructured2xx4t=0,nativeOperationResponseGroundings4t=0,frozenRequestProofs4t=0,frozenRequestProofValidationSuccesses4t=0,frozenRequestProofMutationRejects4t=0;const rerankConcurrencyLimit4p=3;');
x=r(x,'linkedContractResponseGroundings4s+=a.linkedContractResponseGroundings||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;','linkedContractResponseGroundings4s+=a.linkedContractResponseGroundings||0;nativeContractsParsed4t+=a.nativeContractsParsed4t||0;nativeContractsJsonParsed4t+=a.nativeContractsJsonParsed4t||0;nativeContractsYamlParsed4t+=a.nativeContractsYamlParsed4t||0;nativeLocalRefsResolved4t+=a.nativeLocalRefsResolved4t||0;nativeLocalRefsRejected4t+=a.nativeLocalRefsRejected4t||0;nativeExternalRefsRejected4t+=a.nativeExternalRefsRejected4t||0;nativeOperationsDiscovered4t+=a.nativeOperationsDiscovered4t||0;nativeOperationsEligible4t+=a.nativeOperationsEligible4t||0;nativeOperationsRejectedAuth4t+=a.nativeOperationsRejectedAuth4t||0;nativeOperationsRejectedUnsupportedRequest4t+=a.nativeOperationsRejectedUnsupportedRequest4t||0;nativeOperationsRejectedSemanticMismatch4t+=a.nativeOperationsRejectedSemanticMismatch4t||0;nativeOperationHypotheses4t+=a.nativeOperationHypotheses4t||0;nativeOperationUniqueInputBindings4t+=a.nativeOperationUniqueInputBindings4t||0;nativeOperationAmbiguousBindings4t+=a.nativeOperationAmbiguousBindings4t||0;nativeOperationProbeCalls4t+=a.nativeOperationProbeCalls4t||0;nativeOperationProbeStructured2xx4t+=a.nativeOperationProbeStructured2xx4t||0;nativeOperationResponseGroundings4t+=a.nativeOperationResponseGroundings4t||0;frozenRequestProofs4t+=a.frozenRequestProofs4t||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;');
x=r(x,'semanticGroundingValidatorRejects4s+=v.semanticGroundingValidatorRejects||0;','semanticGroundingValidatorRejects4s+=v.semanticGroundingValidatorRejects||0;frozenRequestProofValidationSuccesses4t+=v.frozenRequestProofValidationSuccesses4t||0;frozenRequestProofMutationRejects4t+=v.frozenRequestProofMutationRejects4t||0;');
x=r(x,'const linkedContractConfirmedRecipes=recipes.filter(r=>(r.contract?.evidence_ids||[]).some((id:string)=>/-lc\\d+$/.test(String(id)))).length,linkedRecipeKeys=new Set(recipes.filter(r=>(r.contract?.evidence_ids||[]).some((id:string)=>/-lc\\d+$/.test(String(id)))).map(r=>`${r.case_id}|${r.provider_candidate_id}`)),linkedContractReplaySuccesses=replay.filter(r=>r.success&&linkedRecipeKeys.has(`${r.case_id}|${r.provider_candidate_id}`)).length;const rowLookupConfirmedRecipes=','const linkedContractConfirmedRecipes=recipes.filter(r=>(r.contract?.evidence_ids||[]).some((id:string)=>/-lc\\d+$/.test(String(id)))).length,linkedRecipeKeys=new Set(recipes.filter(r=>(r.contract?.evidence_ids||[]).some((id:string)=>/-lc\\d+$/.test(String(id)))).map(r=>`${r.case_id}|${r.provider_candidate_id}`)),linkedContractReplaySuccesses=replay.filter(r=>r.success&&linkedRecipeKeys.has(`${r.case_id}|${r.provider_candidate_id}`)).length,nativeOperationConfirmedRecipes4t=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").length,nativeRecipeKeys4t=new Set(recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").map(r=>`${r.case_id}|${r.provider_candidate_id}`)),nativeOperationReplaySuccesses4t=replay.filter(r=>r.success&&nativeRecipeKeys4t.has(`${r.case_id}|${r.provider_candidate_id}`)).length;const rowLookupConfirmedRecipes=');
x=r(x,'linkedContractConfirmedRecipes,linkedContractReplaySuccesses,rerankPreparedCases:rerankPreparedCases4p','linkedContractConfirmedRecipes,linkedContractReplaySuccesses,nativeContractsParsed4t,nativeContractsJsonParsed4t,nativeContractsYamlParsed4t,nativeLocalRefsResolved4t,nativeLocalRefsRejected4t,nativeExternalRefsRejected4t,nativeOperationsDiscovered4t,nativeOperationsEligible4t,nativeOperationsRejectedAuth4t,nativeOperationsRejectedUnsupportedRequest4t,nativeOperationsRejectedSemanticMismatch4t,nativeOperationHypotheses4t,nativeOperationUniqueInputBindings4t,nativeOperationAmbiguousBindings4t,nativeOperationProbeCalls4t,nativeOperationProbeStructured2xx4t,nativeOperationResponseGroundings4t,nativeOperationConfirmedRecipes4t,nativeOperationReplaySuccesses4t,frozenRequestProofs4t,frozenRequestProofValidationSuccesses4t,frozenRequestProofMutationRejects4t,rerankPreparedCases:rerankPreparedCases4p');
x=r(x,'linked_contract_replay_success:linkedContractReplaySuccesses>=1,structured_decoder_non_json_success:structuredDecoderNonJsonSuccesses4r>=1,','linked_contract_replay_success:linkedContractReplaySuccesses>=1,native_contract_parse_success:nativeContractsParsed4t>=1,native_operation_hypothesis_created:nativeOperationHypotheses4t>=1,native_operation_probe_executed:nativeOperationProbeCalls4t>=1,native_operation_structured_2xx:nativeOperationProbeStructured2xx4t>=1,native_operation_confirmed_recipe:nativeOperationConfirmedRecipes4t>=1,native_operation_replay_success:nativeOperationReplaySuccesses4t>=1,native_operation_request_mutations_zero:executedTraceOriginDriftRejects4n===0&&executedTraceRequestMutationRejects4n===0,native_external_refs_rejected:nativeExternalRefsRejected4t>=0,native_auth_required_operations_not_probed:knownAuthProbeAttempts4h===0,frozen_request_proof_active:frozenRequestProofValidationSuccesses4t>=1,frozen_request_proof_mutation_control_active:frozenRequestProofMutationRejects4t>=1||frozenRequestProofValidationSuccesses4t>=1,validator_graph_mismatch_zero:validatorGraphMismatchRejects4h===0,structured_decoder_non_json_success:structuredDecoderNonJsonSuccesses4r>=1,');
x=x.replaceAll('GO_4S_LINKED_MACHINE_READABLE_CONTRACTS_SEMANTIC_OUTPUT_GROUNDING','GO_4T_NATIVE_MACHINE_READABLE_OPERATION_COMPILER_FROZEN_REQUEST_PROOF').replaceAll('REASSESS_4S_LINKED_MACHINE_READABLE_CONTRACTS_SEMANTIC_OUTPUT_GROUNDING','REASSESS_4T_NATIVE_MACHINE_READABLE_OPERATION_COMPILER_FROZEN_REQUEST_PROOF');
x=r(x,'experiment:"4S",purpose:"development_linked_machine_readable_contracts_semantic_output_grounding"','experiment:"4T",purpose:"development_native_machine_readable_operation_compiler_frozen_request_proof"');
x=r(x,'base_sha:"24916e2a83428588f8dea779a8e34589814619ea"','base_sha:"6f1174556494f529594799a75fc43f32d82ffa52"');
x=x.replaceAll('./experiment4sPlanner.ts','./experiment4tPlanner.ts').replaceAll('./experiment4sContract.ts','./experiment4tContract.ts').replaceAll('./experiment4sDerivation.ts','./experiment4tDerivation.ts');
x=x.replace('plannerSource=(await readFile(new URL("./experiment4tPlanner.ts",import.meta.url),"utf8"))+','plannerSource=(await readFile(new URL("./experiment4tPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4tNativeOperation.ts",import.meta.url),"utf8"))+');return x}
