import {deriveExperiment4wSource} from "./experiment4wDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5bSource(source:string){let x=deriveExperiment4wSource(source);
x=r(x,'import {compile4w as compile4ar,project4w as project4ar,scope4w as scope4ar,validate4w as validate4ar,validateProjected4w as validateProjected4ar} from "./experiment4wContract.js";','import {compile5b as compile4ar,project5b as project4ar,scope5b as scope4ar,validate5b as validate4ar,validateProjected5b as validateProjected4ar} from "./experiment5bContract.js";');
x=r(x,'import {synthesize4w as synthesize4ar} from "./experiment4wPlanner.js";','import {synthesize5b as synthesize4ar} from "./experiment5bPlanner.js";');
x=r(x,'import {verifySchemaRoleWitnessReplayBody4W} from "./experiment4wReplay.js";','import {verifySchemaRoleWitnessReplayBody4W} from "./experiment4wReplay.js";\nimport {verifyEntityCouplingReplay5B,verifyResponseRoleReplay5B} from "./experiment5bResponse.js";');
x=r(x,'const OUT="results/experiment-4w",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'schema_role_witness_4w:a.parsed_json?.schema_role_witness_4w??null};','schema_role_witness_4w:a.parsed_json?.schema_role_witness_4w??null,response_role_witness_5b:a.parsed_json?.response_role_witness_5b??null,entity_coupling_witness_5b:a.parsed_json?.entity_coupling_witness_5b??null,request_first_5b:String(a.parsed_json?.reason||"").startsWith("5B_REQUEST_FIRST_")};');
x=r(x,'schema_role_witness_4w:syn.schema_role_witness_4w??null,contract,contract_fingerprint:sha3yr(contract)','schema_role_witness_4w:syn.schema_role_witness_4w??null,response_role_witness_5b:syn.response_role_witness_5b??null,entity_coupling_witness_5b:syn.entity_coupling_witness_5b??null,request_first_5b:syn.request_first_5b===true,contract,contract_fingerprint:sha3yr(contract)');
x=r(x,'if(recipe.schema_role_witness_4w&&!verifySchemaRoleWitnessReplayBody4W(recipe.schema_role_witness_4w,got.body))throw new Error("4w_replay_schema_witness_path_missing");const out=project4ar(recipe.projection,got.body,c.replay);','if(recipe.schema_role_witness_4w&&!verifySchemaRoleWitnessReplayBody4W(recipe.schema_role_witness_4w,got.body))throw new Error("4w_replay_schema_witness_path_missing");if(recipe.response_role_witness_5b&&!verifyResponseRoleReplay5B(recipe.response_role_witness_5b,got.body))throw new Error("5b_replay_response_role_witness_path_missing");if(!recipe.entity_coupling_witness_5b||!verifyEntityCouplingReplay5B(recipe.entity_coupling_witness_5b,c.input_names,c.replay,got.body))throw new Error("5b_replay_entity_coupling_failed");const out=project4ar(recipe.projection,got.body,c.replay);');
x=x.replaceAll('experiment:"4W"','experiment:"5B-ENGINE"').replaceAll('purpose:"development_feasibility_constrained_binding_distinctive_semantic_gate"','purpose:"development_request_first_response_grounded_entity_coupled_engine"').replaceAll('base_sha:"dc28d53b18740f3ea83585877fb851b4ff6a9c11"','base_sha:"03d0ec9fcf50b3ba72f98b99130c301044383a56"');
x=x.replaceAll('./experiment4wPlanner.ts','./experiment5bPlanner.ts').replaceAll('./experiment4wContract.ts','./experiment5bContract.ts').replaceAll('./experiment4wDerivation.ts','./experiment5bDerivation.ts');
x=x.replace('(await readFile(new URL("./experiment4wNativeOperation.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5bNativeOperation.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5bResponse.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
