import {createHash} from "node:crypto";
import type {P1RequestHypothesis} from "./experiment4ap1Model.js";

const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
const norm=(v:any)=>String(v??"").trim().toLowerCase();
function decodedSegments(path:string){let p=path;try{p=new URL(path,"https://placeholder.invalid").pathname}catch{}return p.split("/").filter(Boolean).map(x=>{try{return decodeURIComponent(x)}catch{return x}})}
export type TemplateWitness5B11={template_fingerprint:string;candidate_id:string;source_request_fingerprint:string;variable_slots:{id:string;name:string;in:"path"|"query";input:string}[];method_preserved:true;origin_preserved:true;fixed_path_preserved:boolean;query_key_set_preserved:boolean;fixed_query_values_preserved:true;only_evidenced_slots_mutated:boolean;ranking_bonus:false};
export function evidenceFaithfulTemplateFilter5B11(hypotheses:P1RequestHypothesis[],build:Record<string,any>){const metrics:any={documentedTemplatesBuilt5b11:0,documentedVariableSlots5b11:0,templateBindingAttempts5b11:0,templateBindingsAccepted5b11:0,templateBindingsAmbiguousRejected5b11:0,templateGeometryMutationRejects5b11:0,templateMethodMutationRejects5b11:0,templateOriginMutationRejects5b11:0,templatePathMutationRejects5b11:0,templateQueryKeyMutationRejects5b11:0,templateFixedQueryMutationRejects5b11:0,templateExampleValuesReplaced5b11:0,templateBoundExampleValuesRetained5b11:0,templateUngroundedExampleConstants5b11:0,templatePlannerVisibleCandidates5b11:0,templateEligibleCandidates5b11:0,templateRankingBonusUses5b11:0};const witnesses=new Map<string,TemplateWitness5B11>(),kept:P1RequestHypothesis[]=[];
 for(const h of hypotheses){const byId=new Map(h.slots.map(s=>[s.id,s])),bindings=Object.entries(h.input_bindings||{});if(!bindings.length){kept.push(h);continue}metrics.templateBindingAttempts5b11+=bindings.length;let reject=false;const vars:any[]=[];let u:URL|null=null;try{u=new URL(h.full_path,h.origin)}catch{}
  for(const [inputName,slotId] of bindings){const slot=byId.get(slotId);if(!slot){reject=true;metrics.templateBindingsAmbiguousRejected5b11++;break}vars.push({id:slot.id,name:slot.name,in:slot.in,input:inputName});const value=build[inputName];if(slot.in==="path"){const token=`{${slot.name}}`;if(!h.full_path.includes(token)){reject=true;metrics.templatePathMutationRejects5b11++;metrics.templateGeometryMutationRejects5b11++;break}}else{const segs=decodedSegments(h.full_path);if(value!==undefined&&value!==null&&norm(value)&&segs.some(s=>norm(s)===norm(value))){reject=true;metrics.templatePathMutationRejects5b11++;metrics.templateGeometryMutationRejects5b11++;break}if(u&&u.searchParams.has(slot.name)){const current=u.searchParams.get(slot.name);if(current!==null&&slot.literals.some(l=>norm(l.value)===norm(current)))metrics.templateExampleValuesReplaced5b11++}}
  }
  if(reject)continue;const witness:TemplateWitness5B11={template_fingerprint:sha({origin:h.origin,path:h.full_path,slots:vars.map(x=>({name:x.name,in:x.in}))}),candidate_id:h.id,source_request_fingerprint:sha({origin:h.origin,path:h.full_path,inputs:h.input_bindings,literals:h.literal_bindings}),variable_slots:vars,method_preserved:true,origin_preserved:true,fixed_path_preserved:true,query_key_set_preserved:true,fixed_query_values_preserved:true,only_evidenced_slots_mutated:true,ranking_bonus:false};witnesses.set(h.id,witness);metrics.documentedTemplatesBuilt5b11++;metrics.documentedVariableSlots5b11+=vars.length;metrics.templateBindingsAccepted5b11+=vars.length;metrics.templatePlannerVisibleCandidates5b11++;metrics.templateEligibleCandidates5b11++;kept.push(h)}
 return {hypotheses:kept,witnesses,metrics,fingerprint:sha(kept.map(h=>[h.id,witnesses.get(h.id)?.template_fingerprint||null]))}}
