import {mkdir,writeFile} from "node:fs/promises";
import {Client,StreamableHTTPClientTransport,SSEClientTransport} from "@modelcontextprotocol/client";
import {loadConfig} from "./config/index.js";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=58,MAX_SOURCE_EXECUTIONS=24,MAX_REAL_JUDGES=20,MAX_DECOY_JUDGES=20,MAX_TARGET_EXECUTIONS=10,MAX_RECIPES=3,TIMEOUT_MS=12000;
const READ=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUT=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
const PLACE=new Set(["unable","unknown","none","null","n/a","na","undefined","error","failed",""]);
const STOP=new Set(["the","a","an","current","target","source","input","output","value","data","result","item","object"]);
const ALIAS:Record<string,string>={id:"identifier",identifier:"identifier",key:"identifier",url:"url",uri:"url",link:"url",href:"url",repo:"repository",repository:"repository",org:"organization",organization:"organization",organisation:"organization",user:"user",username:"user",account:"user",path:"path",route:"path",name:"name",title:"name",lang:"language",language:"language",locale:"language",country:"country",nation:"country",city:"city",town:"city",code:"code",slug:"code"};
let unsafeExecuted=0,credentialsSupplied=0,replayJudgeCalls=0,authErrorSuccess=0;

type Candidate={name:string;namespace:string;url:string;transport:string};
type ToolRef={server:Candidate;tool:any;safe:boolean;reasons:string[]};
type Scalar={path:string;name:string;type:"string"|"number"|"boolean";value:any};
type Pair={source:ToolRef,target:ToolRef,scalar:Scalar,spec:{param:string;type:string;description:string},canonical:string};
type Judge={decision:"COMPATIBLE"|"INCOMPATIBLE";entity_relation:"same_entity"|"derived_entity"|"different_entity"|"unclear";reason:string;confidence:number};
function ns(n:string){return n.includes("/")?n.split("/")[0]:n.includes(":")?n.split(":")[0]:n;}
function timeout<T>(p:Promise<T>){return new Promise<T>((res,rej)=>{const t=setTimeout(()=>rej(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);res(v)},e=>{clearTimeout(t);rej(e)});});}
function rtype(x:any){return String(x?.type??x?.transport??"").toLowerCase();}function rurl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligible(r:any){const t=rtype(r),u=rurl(r);if(!["streamable-http","sse"].includes(t)||typeof u!=="string"||!u.startsWith("https://")||/[{}]/.test(u))return false;const h=r?.headers;return !(h&&((Array.isArray(h)&&h.length)||(!Array.isArray(h)&&Object.keys(h).length)));}
async function registry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3J/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function records(b:any){return Array.isArray(b)?b:Array.isArray(b?.servers)?b.servers:Array.isArray(b?.data)?b.data:Array.isArray(b?.items)?b.items:[];}
function candidates(rs:any[]){const o:Candidate[]=[];for(const raw of rs){const s=raw?.server??raw,n=String(s?.name??raw?.name??"");if(!n)continue;const st=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(st))continue;const r=(s?.remotes??raw?.remotes??[]).find(eligible);if(r)o.push({name:n,namespace:ns(n),url:rurl(r),transport:rtype(r)});}o.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return o.filter(x=>!seen.has(x.name)&&!!seen.add(x.name));}
function has(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
function req(t:any){return Array.isArray(t?.inputSchema?.required)?t.inputSchema.required:[];}
function classify(t:any){const r:string[]=[];if(!t?.inputSchema||typeof t.inputSchema!=="object"||Array.isArray(t.inputSchema))r.push("invalid_schema");if(t?.annotations?.readOnlyHint!==true)r.push("missing_readonly");if(t?.annotations?.destructiveHint===true)r.push("destructive");const text=`${t?.name??""} ${t?.description??""}`;if(!has(text,READ))r.push("no_read_signal");if(has(text,MUT))r.push("mutation_signal");return {safe:r.length===0,reasons:r};}
function transport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function list(c:Candidate){const client=new Client({name:"missing-experiment-3j",version:"0.1.0"});await timeout(client.connect(transport(c)));const x:any=await timeout(client.listTools());return {client,tools:x.tools??[]};}
async function call(client:Client,t:any,args:any){if(!classify(t).safe)unsafeExecuted++;return timeout(client.callTool({name:t.name,arguments:args}));}
function split(s:string){return s.replace(/([a-z0-9])([A-Z])/g,"$1 $2").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);}function canonical(s:string){return [...new Set(split(s).map(x=>ALIAS[x]??x).filter(x=>!STOP.has(x)))].sort().join("+");}
function runtime(v:any):"string"|"number"|"boolean"|null{return typeof v==="string"?"string":typeof v==="number"&&Number.isFinite(v)?"number":typeof v==="boolean"?"boolean":null;}function placeholder(v:any){return typeof v==="string"&&PLACE.has(v.trim().toLowerCase());}
function flatten(v:any,path="",out:Scalar[]=[]){if(out.length>=80)return out;const t=runtime(v);if(t){const name=(path.split(".").pop()??"value").replace(/^\d+$/,"value");if(!(t==="string"&&(v.length>200||placeholder(v))))out.push({path:path||"$",name,type:t,value:v});return out;}if(Array.isArray(v)){for(let i=0;i<Math.min(10,v.length);i++)flatten(v[i],path?`${path}.${i}`:`${i}`,out);}else if(v&&typeof v==="object")for(const k of Object.keys(v).sort().slice(0,40))flatten(v[k],path?`${path}.${k}`:k,out);return out;}
function structured(r:any){if(r?.structuredContent&&typeof r.structuredContent==="object")return r.structuredContent;const texts=(r?.content??[]).filter((x:any)=>x?.type==="text"&&typeof x.text==="string");if(texts.length===1)try{const p=JSON.parse(texts[0].text);if(p&&typeof p==="object")return p;}catch{}return null;}
function spec(t:any){const q=req(t);if(q.length!==1)return null;const p=q[0],s=t.inputSchema?.properties?.[p];if(!s||typeof s!=="object")return null;const type=s.type==="integer"?"number":s.type;if(!["string","number","boolean"].includes(type))return null;return {param:p,type,description:String(s.description??"")};}
function functional(r:any){if(!r||r.isError===true)return false;const body=r.structuredContent; if(body&&typeof body==="object"){if(body.ok===false)return false;if(["error","failed","invalid","unauthorized"].includes(String(body.status??"").toLowerCase()))return false;}const nonempty=(Array.isArray(r.content)&&r.content.length>0)||(body&&typeof body==="object"&&Object.keys(body).length>0);if(!nonempty)return false;const s=JSON.stringify(r);return !/authentication required|unauthorized|forbidden|requires a subscriber|requires an api key|"error"\s*:\s*"[^"\n]+"|\berror:/i.test(s);}
async function source(ref:ToolRef){const {client,tools}=await list(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe||req(t).length!==0){await client.close();throw new Error("source_invalid");}try{const result=await call(client,t,{});if(!functional(result))throw new Error("source_functional_failure");return {result,scalars:flatten(structured(result))};}finally{await client.close();}}
async function target(ref:ToolRef,param:string,value:any){const {client,tools}=await list(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe){await client.close();throw new Error("target_invalid");}try{const result=await call(client,t,{[param]:value});if(!functional(result))throw new Error("target_functional_failure");return {result,args:{[param]:value}};}finally{await client.close();}}
function pathGet(v:any,p:string){return p==="$"?v:p.split(".").reduce((x,k)=>x?.[k],v);}
function redact(v:any){const s=typeof v==="string"?v:JSON.stringify(v);return s.length>160?s.slice(0,157)+"...":s;}
async function judgePair(config:ReturnType<typeof loadConfig>,p:Pair):Promise<Judge>{const payload={source:{server:p.source.server.name,tool:p.source.tool.name,description:p.source.tool.description??"",field:p.scalar.name,path:p.scalar.path,canonical:p.canonical,type:p.scalar.type,example:redact(p.scalar.value)},target:{server:p.target.server.name,tool:p.target.tool.name,description:p.target.tool.description??"",parameter:p.spec.param,parameter_description:p.spec.description,canonical:p.canonical,type:p.spec.type},intent:`Use the exact ${p.canonical} produced by ${p.source.tool.name} as the entity consumed by ${p.target.tool.name} to obtain the target tool's documented result.`};const system="You are a conservative semantic compatibility judge. Decide whether the source value and target parameter refer to the SAME ENTITY in the supplied metadata, not merely the same data type. Reject if the source is a news/article URL while target expects a store/site/business URL, or if identifiers belong to different domains. Do not invent facts. Return JSON only with decision COMPATIBLE or INCOMPATIBLE, entity_relation same_entity|derived_entity|different_entity|unclear, reason, confidence 0..1. If uncertain, reject.";const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`judge_${r.status}:${await r.text()}`);const b:any=await r.json();return JSON.parse(b.choices?.[0]?.message?.content??"{}");}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3J");const reg=await registry(),rs=records(reg),cs=candidates(rs),tools:ToolRef[]=[],discovery:any[]=[];
for(const c of cs.slice(0,MAX_SERVERS)){try{const {client,tools:listTools}=await list(c);for(const t of listTools){const d=classify(t);tools.push({server:c,tool:t,...d});}discovery.push({server:c,tool_count:listTools.length});await client.close();}catch(e){discovery.push({server:c,error:String(e)});}}
const sources=tools.filter(x=>x.safe&&req(x.tool).length===0),targets=tools.filter(x=>x.safe&&spec(x.tool));const pairs:Pair[]=[],sourceEvidence:any[]=[];let sourceExecs=0;
for(const s of sources){if(sourceExecs>=MAX_SOURCE_EXECUTIONS)break;try{const sx=await source(s);sourceExecs++;sourceEvidence.push({server:s.server.name,tool:s.tool.name,scalars:sx.scalars});for(const t of targets){if(s.server.name===t.server.name)continue;const sp=spec(t.tool)!;for(const sc of sx.scalars){const cc=canonical(sc.name);if(cc&&cc===canonical(sp.param)&&sc.type===sp.type&&!placeholder(sc.value)){pairs.push({source:s,target:t,scalar:sc,spec:sp,canonical:cc});break;}}}}catch(e){sourceEvidence.push({server:s.server.name,tool:s.tool.name,error:String(e)});}}
const real=pairs.slice(0,MAX_REAL_JUDGES);const decoys:any[]=[];for(let i=0;i<real.length&&decoys.length<MAX_DECOY_JUDGES;i++){const p=real[i];const alt=real.find((q,j)=>j!==i&&q.canonical===p.canonical&&q.spec.type===p.spec.type&&q.target.server.name!==p.target.server.name&&q.target.server.name!==p.source.server.name);if(alt)decoys.push({...p,target:alt.target,spec:alt.spec});}
const judgeEvidence:any[]=[],approved:any[]=[];let decoyFP=0;
for(const d of decoys){const j=await judgePair(config,d);judgeEvidence.push({kind:"decoy",pair:{source:d.source.tool.name,target:d.target.tool.name,canonical:d.canonical},judge:j});if(j.decision==="COMPATIBLE"&&j.entity_relation==="same_entity"&&Number(j.confidence)>=0.9)decoyFP++;}
for(const p of real){const j=await judgePair(config,p);judgeEvidence.push({kind:"real",pair:{source:p.source.tool.name,target:p.target.tool.name,canonical:p.canonical},judge:j});if(j.decision==="COMPATIBLE"&&j.entity_relation==="same_entity"&&Number(j.confidence)>=0.9)approved.push({pair:p,judge:j});}
const recipes:any[]=[],rejected=judgeEvidence.filter(x=>!(x.judge.decision==="COMPATIBLE"&&x.judge.entity_relation==="same_entity"&&Number(x.judge.confidence)>=0.9));let execs=0;
for(const a of approved){if(execs>=MAX_TARGET_EXECUTIONS||recipes.length>=MAX_RECIPES)break;execs++;try{const tx=await target(a.pair.target,a.pair.spec.param,a.pair.scalar.value);recipes.push({recipe:{canonical_concept:a.pair.canonical,source_server:a.pair.source.server,source_tool:a.pair.source.tool.name,source_path:a.pair.scalar.path,source_leaf:a.pair.scalar.name,target_server:a.pair.target.server,target_tool:a.pair.target.tool.name,target_parameter:a.pair.spec.param,target_type:a.pair.spec.type,judge:a.judge},first_execution:{source_value:a.pair.scalar.value,target_args:tx.args,target_result:tx.result}});}catch(e){rejected.push({kind:"real_execution",reason:String(e)});}}
const replay:any[]=[];for(const e of recipes){const r=e.recipe,before=replayJudgeCalls;try{const sr=tools.find(x=>x.server.name===r.source_server.name&&x.tool.name===r.source_tool)!;const tr=tools.find(x=>x.server.name===r.target_server.name&&x.tool.name===r.target_tool)!;const sx=await source(sr),v=pathGet(structured(sx.result),r.source_path);if(runtime(v)!==r.target_type||placeholder(v)||canonical(r.source_leaf)!==canonical(r.target_parameter))throw new Error("replay_invalid_bridge");const tx=await target(tr,r.target_parameter,v);replay.push({recipe:r,success:true,source_value:v,target_result:tx.result});}catch(e){replay.push({recipe:r,success:false,error:String(e)});}replayJudgeCalls+=before-replayJudgeCalls;}
const replaySuccess=replay.filter(x=>x.success).length,replayRate=recipes.length?replaySuccess/recipes.length:0,decoyRate=decoys.length?decoyFP/decoys.length:0;const successResultsOk=recipes.every(x=>x.first_execution.target_result?.isError!==true&&x.first_execution.target_result?.structuredContent?.ok!==false);
const criteria={one_semantic_functional_composition:recipes.length>=1,one_replay:replaySuccess>=1,replay_success_rate:replayRate===1,zero_decoy_false_positives:decoyRate===0,approved_pairs_high_confidence:recipes.every(x=>x.recipe.judge.confidence>=0.9&&x.recipe.judge.entity_relation==="same_entity"),successful_results_strict:successResultsOk,zero_auth_error_success:authErrorSuccess===0,zero_unsafe:unsafeExecuted===0,zero_credentials:credentialsSupplied===0,zero_replay_judge_calls:replayJudgeCalls===0,twenty_rejections:rejected.length>=20,evidence_persisted:true};const decision=Object.values(criteria).every(Boolean)?"GO_INTENT_CONSTRAINED_SEMANTIC_COMPOSITION":"REASSESS_INTENT_CONSTRAINED_SEMANTIC_COMPOSITION";
const summary={experiment:"MISSING Experiment 3J — Intent-Constrained Semantic Composition",created_at:new Date().toISOString(),metrics:{registry_records:rs.length,eligible_servers:cs.length,servers_inspected:discovery.length,discovered_tools:tools.length,sources:sources.length,targets:targets.length,source_executions:sourceExecs,deterministic_pairs:pairs.length,real_judge_calls:real.length,decoy_judge_calls:decoys.length,decoy_false_positives:decoyFP,decoy_false_positive_rate:decoyRate,approved_pairs:approved.length,target_execution_attempts:execs,successful_recipes:recipes.length,replay_successes:replaySuccess,replay_success_rate:replayRate,unsafe_tools_executed:unsafeExecuted,credentials_supplied:credentialsSupplied,replay_judge_calls:replayJudgeCalls},criteria,decision,recipes,replay};
await mkdir("results/experiment-3j",{recursive:true});await writeFile("results/experiment-3j/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3j/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:reg,discovery,source_evidence:sourceEvidence,judge_evidence:judgeEvidence,rejected,recipes,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
