import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {validate4u,compile4u,project4u,validateProjected4u,scope4u} from "./experiment4uContract.js";
import {verifySchemaRoleWitness4W} from "./experiment4wSchemaWitness.js";

function witnessLedgerProxy4W(ledger:RecoveryLedger,allowed:Set<string>){return {record:(layer:any,kind:string,accepted:boolean,detail?:any)=>{if(kind==="ungrounded_projection_fields"&&accepted===false&&detail&&typeof detail==="object"&&allowed.has(`${String(detail.output||"")}:${String(detail.path||"")}`))return;ledger.record(layer,kind,accepted,detail)}} as RecoveryLedger}
export function validate4w(raw:any,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger,probeProof:P1ProbeProof|null){if(raw?.decision!=="COMPILE"||!probeProof){const checked:any=validate4u(raw,provider,evidence,ledger,probeProof);return {...checked,schemaRoleResolverValidationSuccesses4w:0,schemaRoleResolverWitnessMutationRejects4w:0}}const witness=raw?.schema_role_witness_4w;if(!witness){const checked:any=validate4u(raw,provider,evidence,ledger,probeProof);return {...checked,schemaRoleResolverValidationSuccesses4w:0,schemaRoleResolverWitnessMutationRejects4w:0}}if(!verifySchemaRoleWitness4W(witness,probeProof)){const checked:any=validate4u(raw,provider,evidence,ledger,probeProof);ledger.record("guard","ungrounded_projection_fields",false,{reason:"4w_schema_witness_mutated"});return {...checked,errors:[...(checked.errors||[]),"4w_schema_witness_mutated"],projection:null,probe_proof:null,schemaRoleResolverValidationSuccesses4w:0,schemaRoleResolverWitnessMutationRejects4w:1}}const allowed=new Set<string>((witness.mappings||[]).map((m:any)=>`${m.output_role}:${m.observed_path}`)),proxy=witnessLedgerProxy4W(ledger,allowed),checked:any=validate4u(raw,provider,evidence,proxy,probeProof);let witnessUngrounded=0;const errors=(checked.errors||[]).filter((e:string)=>{const m=/^4u_ungrounded_output:([^:]+):(.+)$/.exec(e),approved=!!(m&&allowed.has(`${m[1]}:${m[2]}`));if(approved)witnessUngrounded++;return !approved});const semanticGroundingValidatorRejects=Math.max(0,Number(checked.semanticGroundingValidatorRejects||0)-witnessUngrounded);return {...checked,errors,projection:errors.length?null:(raw.projection as ProjectionPlan),probe_proof:errors.length?null:probeProof,semanticGroundingValidatorRejects,schemaRoleResolverValidationSuccesses4w:errors.length?0:1,schemaRoleResolverWitnessMutationRejects4w:0}}
export function compile4w(contract:MicroContract,input:Record<string,unknown>){return compile4u(contract,input)}
export function project4w(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return project4u(plan,body,input)}
export function validateProjected4w(caseId:string,input:Record<string,any>,out:Record<string,any>){return validateProjected4u(caseId,input,out)}
export function scope4w(start:string,target:string){return scope4u(start,target)}
