import {deriveExperiment5b5Source} from "./experiment5b5Derivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b6_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b6Source(source:string){let x=deriveExperiment5b5Source(source);
x=r(x,'import {compile5b5 as compile4ar,project5b5 as project4ar,scope5b5 as scope4ar,validate5b5 as validate4ar,validateProjected5b5 as validateProjected4ar} from "./experiment5b5Contract.js";','import {compile5b6 as compile4ar,project5b6 as project4ar,scope5b6 as scope4ar,validate5b6 as validate4ar,validateProjected5b6 as validateProjected4ar} from "./experiment5b6Contract.js";');
x=r(x,'import {synthesize5b5 as synthesize4ar} from "./experiment5b5Planner.js";','import {synthesize5b6 as synthesize4ar} from "./experiment5b6Planner.js";');
x=r(x,'const OUT="results/experiment-5b5-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b6-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'cross_document_alignment_witness_5b5:a.parsed_json?.cross_document_alignment_witness_5b5??null};','cross_document_alignment_witness_5b5:a.parsed_json?.cross_document_alignment_witness_5b5??null,query_operation_witness_5b6:a.parsed_json?.query_operation_witness_5b6??null};');
x=r(x,'cross_document_alignment_witness_5b5:syn.cross_document_alignment_witness_5b5??null,contract,contract_fingerprint:sha3yr(contract)','cross_document_alignment_witness_5b5:syn.cross_document_alignment_witness_5b5??null,query_operation_witness_5b6:syn.query_operation_witness_5b6??null,contract,contract_fingerprint:sha3yr(contract)');
x=x.replaceAll('experiment:"5B5-ENGINE"','experiment:"5B6-ENGINE"').replaceAll('purpose:"development_cross_document_operation_alignment_section_local_evidence_engine"','purpose:"development_query_oriented_parameter_local_compiler_engine"').replaceAll('base_sha:"7e4471b7eea7fdc958c03d6be7b65b9c4c26adfc"','base_sha:"addfcdb0012a800e418ed58f8ea684406a05edfb"');
x=x.replaceAll('./experiment5b5Planner.ts','./experiment5b6Planner.ts').replaceAll('./experiment5b5Contract.ts','./experiment5b6Contract.ts').replaceAll('./experiment5b5Derivation.ts','./experiment5b6Derivation.ts');
x=x.replace('(await readFile(new URL("./experiment5b5Section.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b5Section.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b6Query.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
