export type StructuredFormat4R="json"|"xml"|"csv";
export type DecodeMetrics4R={structuredDecoderJsonSuccesses:number;structuredDecoderXmlSuccesses:number;structuredDecoderCsvSuccesses:number;structuredDecoderFailures:number;structuredDecoderNonJsonSuccesses:number};
export type Decoded4R={format:StructuredFormat4R;body:any;metrics:DecodeMetrics4R};
const MAX_DEPTH=10,MAX_ROWS=500,MAX_FIELDS=128;
function metrics(format:StructuredFormat4R):DecodeMetrics4R{return {structuredDecoderJsonSuccesses:format==="json"?1:0,structuredDecoderXmlSuccesses:format==="xml"?1:0,structuredDecoderCsvSuccesses:format==="csv"?1:0,structuredDecoderFailures:0,structuredDecoderNonJsonSuccesses:format==="json"?0:1}}
function decodeEntities(s:string){return s.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&")}
function add(obj:any,key:string,val:any){if(Object.prototype.hasOwnProperty.call(obj,key)){obj[key]=Array.isArray(obj[key])?[...obj[key],val]:[obj[key],val]}else obj[key]=val}
function xmlDecode(text:string){const src=text.replace(/<\?xml[^>]*\?>/gi,"").replace(/<!--([\s\S]*?)-->/g,"").trim();if(!src.startsWith("<"))throw new Error("4r_xml_missing_root");const root:any={},stack:{name:string;node:any;text:string;depth:number}[]=[];const re=/<([^>]+)>|([^<]+)/g;let m:RegExpExecArray|null,tokens=0;while((m=re.exec(src))){if(++tokens>200000)throw new Error("4r_xml_token_cap");if(m[2]){if(stack.length)stack[stack.length-1].text+=m[2];continue}const tag=(m[1]||"").trim();if(!tag||tag.startsWith("!"))continue;if(tag.startsWith("/")){const name=tag.slice(1).trim().split(/\s+/)[0],cur=stack.pop();if(!cur||cur.name!==name)throw new Error("4r_xml_unbalanced");const txt=decodeEntities(cur.text.trim()),keys=Object.keys(cur.node);const val=keys.length?({...cur.node,...(txt?{_text:txt}:{})}):txt;if(stack.length)add(stack[stack.length-1].node,name,val);else add(root,name,val);continue}const self=tag.endsWith("/"),inner=self?tag.slice(0,-1).trim():tag,name=inner.split(/\s+/)[0];if(!/^[A-Za-z_][\w:.-]*$/.test(name))throw new Error("4r_xml_bad_name");const depth=stack.length+1;if(depth>MAX_DEPTH)throw new Error("4r_xml_depth_cap");const node:any={};const attrs=[...inner.matchAll(/\s+([A-Za-z_][\w:.-]*)\s*=\s*(?:"([^"]*)"|'([^']*)')/g)].slice(0,MAX_FIELDS);for(const a of attrs)node[`@${a[1]}`]=decodeEntities(a[2]??a[3]??"");if(self){if(stack.length)add(stack[stack.length-1].node,name,node);else add(root,name,node)}else stack.push({name,node,text:"",depth})}if(stack.length)throw new Error("4r_xml_unclosed");return root}
function parseCsvLine(line:string){const out:string[]=[],cur:string[]=[];let quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur.push('"');i++}else quoted=!quoted}else if(ch===","&&!quoted){out.push(cur.join(""));cur.length=0}else cur.push(ch)}if(quoted)throw new Error("4r_csv_unclosed_quote");out.push(cur.join(""));return out}
function csvDecode(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim().length);if(lines.length<2)throw new Error("4r_csv_insufficient_rows");const head=parseCsvLine(lines[0]).map(x=>x.trim());if(!head.length||head.length>MAX_FIELDS||new Set(head).size!==head.length||head.some(x=>!x))throw new Error("4r_csv_bad_header");const rows=lines.slice(1,MAX_ROWS+1).map(line=>{const vals=parseCsvLine(line);if(vals.length!==head.length)throw new Error("4r_csv_width_mismatch");return Object.fromEntries(head.map((h,i)=>[h,vals[i]]))});if(!rows.length)throw new Error("4r_csv_no_rows");return {rows}}
export function decodeStructured4R(text:string,contentType:string|null,url:string):Decoded4R{const ct=String(contentType||"").toLowerCase(),trim=text.trim();try{if(/json/.test(ct)||trim.startsWith("{")||trim.startsWith("[")){const body=JSON.parse(text);if(body===null||body===undefined)throw new Error("4r_json_empty");return {format:"json",body,metrics:metrics("json")}}if(/xml/.test(ct)||/\.xml(?:$|[?#])/i.test(url)||trim.startsWith("<")){return {format:"xml",body:xmlDecode(text),metrics:metrics("xml")}}if(/csv/.test(ct)||/[?&]format=csv(?:&|$)/i.test(url)||/\.csv(?:$|[?#])/i.test(url)){return {format:"csv",body:csvDecode(text),metrics:metrics("csv")}}throw new Error("4r_unsupported_structured_format")}catch(e){throw e}}
