import {lexicalTokensP1} from "./experiment4ap1Request.js";
import type {ProjectionExpr} from "./experiment3xCore.js";

export type RelationalRowSet4O={array_path:string;shared_scalar_fields:string[];label_field:string;value_field:string;observed_labels:string[];row_count:number};
export type RelationalSummary4O={row_sets:RelationalRowSet4O[];metrics:Record<string,number>};
const MAX_ARRAYS=32,MAX_ROWS=200,MAX_LABELS=200,MAX_DEPTH=7;
function scalar(v:any){return v===null||["string","number","boolean"].includes(typeof v)}
function pathParts(path:string){return path.split(".").filter(Boolean)}
function getPath(v:any,path:string){return pathParts(path).reduce((x,k)=>x?.[k],v)}
function tokens(v:string){return lexicalTokensP1(v)}
function overlap(a:string,b:string){const x=new Set(tokens(a)),y=new Set(tokens(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function arrays(value:any,prefix="",depth=0,out:{path:string;rows:any[]}[]=[]){if(depth>MAX_DEPTH||out.length>=MAX_ARRAYS)return out;if(Array.isArray(value)){if(prefix)out.push({path:prefix,rows:value.slice(0,MAX_ROWS)});for(const row of value.slice(0,3))if(row&&typeof row==="object"&&!Array.isArray(row))for(const [k,v] of Object.entries(row))arrays(v,prefix?`${prefix}.${k}`:k,depth+1,out);return out}if(value&&typeof value==="object")for(const [k,v] of Object.entries(value)){arrays(v,prefix?`${prefix}.${k}`:k,depth+1,out);if(out.length>=MAX_ARRAYS)break}return out}
function sharedScalarFields(rows:any[]){const objects=rows.filter(r=>r&&typeof r==="object"&&!Array.isArray(r));if(objects.length<2)return [] as string[];const first=Object.keys(objects[0]).filter(k=>scalar(objects[0][k]));return first.filter(k=>objects.slice(1).some(r=>Object.prototype.hasOwnProperty.call(r,k)&&scalar(r[k])))}
function distinctValues(rows:any[],field:string){const vals=rows.filter(r=>r&&typeof r==="object"&&!Array.isArray(r)&&scalar(r[field])&&r[field]!==null).map(r=>String(r[field]).trim()).filter(Boolean);return [...new Set(vals)]}
function fieldRoleScore(field:string,values:string[],kind:"label"|"value"){const f=field.toLowerCase(),uniq=values.length;if(kind==="label")return (/variable|field|label|name|type|key|property|attribute|metric/.test(f)?8:0)+Math.min(6,uniq);return (/value|result|data|content|answer|description/.test(f)?8:0)+Math.min(4,uniq)}
export function summarizeRelational4O(body:any):RelationalSummary4O{const metrics={relationalArrayCandidates:0,relationalRowSetsAccepted:0,relationalRowSetsRejectedInsufficientRows:0,relationalRowSetsRejectedNoSharedSchema:0,relationalLabelFieldCandidates:0,relationalValueFieldCandidates:0,relationalObservedLabels:0,relationalOutputMatches:0},row_sets:RelationalRowSet4O[]=[];for(const candidate of arrays(body)){metrics.relationalArrayCandidates++;const objects=candidate.rows.filter(r=>r&&typeof r==="object"&&!Array.isArray(r));if(objects.length<2){metrics.relationalRowSetsRejectedInsufficientRows++;continue}const shared=sharedScalarFields(objects);if(shared.length<2){metrics.relationalRowSetsRejectedNoSharedSchema++;continue}const fields=shared.map(field=>({field,values:distinctValues(objects,field)})).filter(x=>x.values.length>0);metrics.relationalLabelFieldCandidates+=fields.length;metrics.relationalValueFieldCandidates+=fields.length;const labels=[...fields].sort((a,b)=>fieldRoleScore(b.field,b.values,"label")-fieldRoleScore(a.field,a.values,"label")||b.values.length-a.values.length||a.field.localeCompare(b.field));const values=[...fields].sort((a,b)=>fieldRoleScore(b.field,b.values,"value")-fieldRoleScore(a.field,a.values,"value")||a.field.localeCompare(b.field));const label=labels[0],value=values.find(v=>v.field!==label?.field);if(!label||!value)continue;const observed=label.values.slice(0,MAX_LABELS);row_sets.push({array_path:candidate.path,shared_scalar_fields:shared.sort(),label_field:label.field,value_field:value.field,observed_labels:observed,row_count:objects.length});metrics.relationalRowSetsAccepted++;metrics.relationalObservedLabels+=observed.length}return {row_sets,metrics}}
export function identityCompatible4O(output:string,input:string){const a=tokens(output),b=tokens(input);if(!a.length||!b.length)return false;const generic=new Set(["id","identifier","code","name","value"]),aa=a.filter(x=>!generic.has(x)),bb=b.filter(x=>!generic.has(x));if(aa.length&&bb.length)return aa.some(x=>bb.includes(x));return a.join("_")===b.join("_")}
export function uniqueRowLookup4O(summary:RelationalSummary4O,output:string){const candidates:{expr:ProjectionExpr;score:number;label:string;row_set:RelationalRowSet4O}[]=[];for(const rs of summary.row_sets)for(const label of rs.observed_labels){const score=overlap(output,label);if(score>0)candidates.push({expr:{op:"ROW_LOOKUP",array_path:rs.array_path,label_field:rs.label_field,label_value:label,value_field:rs.value_field},score,label,row_set:rs})}candidates.sort((a,b)=>b.score-a.score||a.label.localeCompare(b.label));if(!candidates.length)return null;if(candidates.length>1&&candidates[0].score===candidates[1].score)return null;return candidates[0]}
export function rowLookupHasNumericIndex4O(e:any){return e?.op==="ROW_LOOKUP"&&[e.array_path,e.label_field,e.value_field].some((p:string)=>/(^|\.)\d+(\.|$)/.test(String(p||"")))}
export function validateRowLookupObserved4O(expr:any,summary:RelationalSummary4O){if(!expr||expr.op!=="ROW_LOOKUP")return false;if(rowLookupHasNumericIndex4O(expr))return false;return summary.row_sets.some(rs=>rs.array_path===expr.array_path&&rs.label_field===expr.label_field&&rs.value_field===expr.value_field&&rs.observed_labels.includes(expr.label_value))}
