import {mkdir,writeFile} from "node:fs/promises";
import {RecoveryLedger,derivedSafetyCounters,sha3yr} from "./experiment3yrCore.js";
import {fetchTextSafeR2,safetyGateFromLedger} from "./experiment3yr2Core.js";
import {validateIntegrationContractR,compileIntegrationRequestR,executeIntegrationProjectionR,validateIntegrationOutputR,classifyFailure,type IntegrationProvider} from "./experiment3yirCore.js";
import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {runNegativeControls as run3vControls} from "./experiment3vControls.js";
import {run3xControls} from "./experiment3xControls.js";

const OUT="results/experiment-3yir",FREEZE_SHA="6b79298feb6288f843e0c11c04cfbe7cd4a1a794",MAX=4*1024*1024;
const burned=[
 {provider:{case_id:"pokemon_metadata",candidate_id:"burned_pokeapi",name:"PokéAPI",start_url:"https://pokeapi.co"},evidence:'GET https://pokeapi.co/api/v2/pokemon/{id_or_name}. Response JSON fields include id and name.',contract:{case_id:"pokemon_metadata",provider_candidate_id:"burned_pokeapi",decision:"COMPILE",method:"GET",base_url:"https://pokeapi.co",path_template:"/api/v2/pokemon/{id_or_name}",path_bindings:{id_or_name:"$input.pokemon_name"},query_bindings:{},output_paths:{id:"id",name:"name"},evidence_ids:["burned_pokeapi-e01"],reason:"burned 3Y provider"}},
 {provider:{case_id:"currency_metadata",candidate_id:"burned_nbp",name:"National Bank of Poland",start_url:"https://api.nbp.pl"},evidence:'GET https://api.nbp.pl/api/exchangerates/rates/{table}/{code}/ . Response JSON fields include currency and code.',contract:{case_id:"currency_metadata",provider_candidate_id:"burned_nbp",decision:"COMPILE",method:"GET",base_url:"https://api.nbp.pl",path_template:"/api/exchangerates/rates/a/{code}/",path_bindings:{code:"$input.currency_id"},query_bindings:{},output_paths:{code:"code",name:"currency"},evidence_ids:["burned_nbp-e01"],reason:"burned 3X provider"}}
] as const;

async function live(url:string,ledger:RecoveryLedger){try{const g=await fetchTextSafeR2(url,url,MAX,ledger),body=JSON.parse(g.text);return {body,requested_at:new Date().toISOString(),body_fingerprint:sha3yr(g.text)};}catch(e:any){throw e;}}
async function main(){await mkdir(OUT,{recursive:true});const ledger=new RecoveryLedger(),controls=[...(await run3vControls()),...run3xControls().controls],results:any[]=[],recipes:any[]=[];for(const b of burned){const p=b.provider as IntegrationProvider,docs:DocEvidence[]=[{evidence_id:`${p.candidate_id}-e01`,provider_candidate_id:p.candidate_id,requested_url:p.start_url,resolved_url:p.start_url,verified_at:new Date().toISOString(),status:200,content_type:"text/plain",body_fingerprint:sha3yr(b.evidence),text:b.evidence,state:"ok"}],v=validateIntegrationContractR(b.contract,p,docs,ledger);if(v.errors.length){results.push({provider:p,success:false,classification:"SYSTEM_FAILURE",stage:"validation",errors:v.errors});continue;}try{const c=b.contract as unknown as MicroContract,build=(p.case_id==="pokemon_metadata"?{pokemon_name:"pikachu"}:{currency_id:"USD"}),replay=(p.case_id==="pokemon_metadata"?{pokemon_name:"bulbasaur"}:{currency_id:"EUR"}),u1=compileIntegrationRequestR(c,build),a=await live(u1,ledger),o1=executeIntegrationProjectionR(c,p.case_id,a.body,build);if(!validateIntegrationOutputR(p.case_id,build,o1))throw new Error("semantic_validation_first_failed");const b2=await live(u1,ledger),o2=executeIntegrationProjectionR(c,p.case_id,b2.body,build);if(!validateIntegrationOutputR(p.case_id,build,o2))throw new Error("semantic_validation_confirmation_failed");const recipe:any={case_id:p.case_id,provider_candidate_id:p.candidate_id,provider_name:p.name,contract:c,projection_kind:"3x_FIELD_program",first_verification:a,confirmation_verification:b2,documentation_fingerprint:sha3yr(docs),contract_fingerprint:sha3yr(c)};recipe.recipe_fingerprint=sha3yr(recipe);const u2=compileIntegrationRequestR(c,replay),r=await live(u2,ledger),ro=executeIntegrationProjectionR(c,p.case_id,r.body,replay);if(!validateIntegrationOutputR(p.case_id,replay,ro))throw new Error("replay_semantic_validation_failed");recipes.push(recipe);results.push({provider:p,success:true,build_output:o2,replay_output:ro});}catch(e:any){results.push({provider:p,success:false,classification:classifyFailure(String(e),e?.status),stage:"live",error:String(e)});}}
 const counters=derivedSafetyCounters(ledger),verified=controls.filter(x=>x.executed&&x.rejected).length,gates={freeze_sha_preserved:FREEZE_SHA==="6b79298feb6288f843e0c11c04cfbe7cd4a1a794",burned_only:true,generic_provider_parameter_mapping:results.some(x=>x.provider?.candidate_id==="burned_pokeapi"&&x.success),failure_classification_available:results.filter(x=>!x.success).every(x=>["SYSTEM_FAILURE","PROVIDER_INELIGIBLE","FIXTURE_STALE","LIVE_PROVIDER_FAILURE"].includes(x.classification)),two_manufactures:recipes.length===2,two_distinct_providers:new Set(recipes.map(x=>x.provider_candidate_id)).size===2,double_live_verify:recipes.every(x=>x.first_verification&&x.confirmation_verification),replay_100_percent:results.filter(x=>x.success).length===2,real_3x_interpreter:recipes.every(x=>x.projection_kind==="3x_FIELD_program"),fingerprints_present:recipes.every(x=>x.documentation_fingerprint&&x.contract_fingerprint&&x.recipe_fingerprint),controls_active:verified===controls.length,event_derived_safety:safetyGateFromLedger(ledger,counters),ledger_non_empty:ledger.events.length>0};const decision=Object.values(gates).every(Boolean)?"GO_3Y_I_R_END_TO_END_INTEGRATION_REPAIR":"REASSESS_3Y_I_R_END_TO_END_INTEGRATION_REPAIR",report={experiment:"3Y-I-R",purpose:"engineering_repair_only_not_confirmatory",freeze_sha:FREEZE_SHA,decision,metrics:{successful_manufactures:recipes.length,controls:controls.length,controls_verified:verified,live_calls:results.length*3},gates,results,recipes,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};await writeFile(`${OUT}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({decision,metrics:report.metrics,gates},null,2));console.log(decision);}
main().catch(e=>{console.error(e);process.exitCode=1;});
