import type {Config} from "./config/index.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import {probeHypothesis4R,probeCacheMetrics4R} from "./experiment4rProbe.js";
import {allowedInputSources4S,deterministicPartialProjection4S,groundingStats4S,materialize4S} from "./experiment4sCore.js";
import {fieldSemanticallyGrounded4S} from "./experiment4sGrounding.js";
import {synthesize4s} from "./experiment4sPlanner.js";
import {buildNativeHypotheses4T,freezeRequestProof4T} from "./experiment4tNativeOperation.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(r=>[r.case_id,r]));
function overlap(a:string,b:string){const x=new Set(lexicalTokensP1(a)),y=new Set(lexicalTokensP1(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function groundedFields(p:P1ProbeProof,output:string){return [...p.record.observed_fields].filter(f=>fieldSemanticallyGrounded4S(output,f)).map(field=>({field,score:overlap(output,field.leaf)*100+field.build_value_relations.length*20-Math.min(30,field.path.split(".").length)})).sort((a,b)=>b.score-a.score||a.field.path.length-b.field.path.length).slice(0,48).map(r=>r.field)}
async function callStructured(config:Config,payload:any,jsonSchema:any){const started=Date.now();const response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:"Resolve ONLY unresolved outputs. Selected fields are semantically grounded. Never invent fields, URLs, credentials, indices, providers, request parameters, or alternate response formats."},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:jsonSchema}})});const latency_ms=Date.now()-started,text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}return {status:response.status,ok:response.ok,latency_ms,usage:body?.usage??null,raw:body?.choices?.[0]?.message?.content??null,refusal:body?.choices?.[0]?.message?.refusal??null}}
function mappingSchema(proof:P1ProbeProof,inputs:readonly string[],unresolved:readonly string[]){const properties:any={};for(const output of unresolved){const sources=[...groundedFields(proof,output).map(f=>f.id),...allowedInputSources4S(output,inputs).map(i=>`TASK_INPUT:${i}`)];properties[output]={type:"object",additionalProperties:false,properties:{source_id:{type:"string",enum:sources.length?sources:["NO_VALID_SOURCE"]}},required:["source_id"]}}return {name:"missing_4t_grounded_mapping",strict:true,schema:{type:"object",additionalProperties:false,properties:{decision:{type:"string",enum:["SELECT","REJECT"]},output_bindings:{type:"object",additionalProperties:false,properties,required:[...unresolved]},reason:{type:"string"}},required:["decision","output_bindings","reason"]}}}
function fallbackProjection(caseId:string,proof:P1ProbeProof,raw:string,unresolved:string[]){const c=BY_ID[caseId],v=JSON.parse(raw),projection:any={};if(v.decision!=="SELECT")return null;for(const output of unresolved){const source=String(v.output_bindings?.[output]?.source_id||"");if(source.startsWith("TASK_INPUT:")){const input=source.slice(11);if(!allowedInputSources4S(output,c.input_names).includes(input))throw new Error("4t_forbidden_input_source");projection[output]={op:"INPUT",name:input};continue}const f=proof.record.observed_fields.find(x=>x.id===source);if(!f||!fieldSemanticallyGrounded4S(output,f))throw new Error(`4t_ungrounded_output:${output}:${f?.path||source}`);projection[output]={op:"FIELD",path:f.path}}return projection}
function metricDefaults(){return {nativeContractsParsed4t:0,nativeContractsJsonParsed4t:0,nativeContractsYamlParsed4t:0,nativeLocalRefsResolved4t:0,nativeLocalRefsRejected4t:0,nativeExternalRefsRejected4t:0,nativeOperationsDiscovered4t:0,nativeOperationsEligible4t:0,nativeOperationsRejectedAuth4t:0,nativeOperationsRejectedUnsupportedRequest4t:0,nativeOperationsRejectedSemanticMismatch4t:0,nativeOperationHypotheses4t:0,nativeOperationUniqueInputBindings4t:0,nativeOperationAmbiguousBindings4t:0,nativeOperationProbeCalls4t:0,nativeOperationProbeStructured2xx4t:0,nativeOperationResponseGroundings4t:0,nativeOperationConfirmedRecipes4t:0,nativeOperationReplaySuccesses4t:0,nativeOperationOriginMutationRejects4t:0,nativeOperationPathMutationRejects4t:0,frozenRequestProofs4t:0,frozenRequestProofValidationSuccesses4t:0,frozenRequestProofMutationRejects4t:0}}
function merged(base:any,metrics:any,extra:any={}){return {...base,...metricDefaults(),...metrics,...extra}}
export async function synthesize4t(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){
  // The entire inherited 4S lane runs first and is returned unchanged when it succeeds.
  const base=await synthesize4s(config,provider,evidence,ledger);if(base?.parsed_json?.decision==="COMPILE")return merged(base,{});
  const c=BY_ID[provider.case_id];if(!c)return merged(base,{});const native=await buildNativeHypotheses4T(evidence,provider,ledger);if(!native.hypotheses.length)return merged(base,native.metrics);
  const cacheBefore=probeCacheMetrics4R(),h=native.hypotheses[0],row:any=await probeHypothesis4R(h,c.build,ledger),cacheAfter=probeCacheMetrics4R();const success=row.proof.record.disposition==="success",ground=success?groundingStats4S(row.proof,c.required):{semanticGroundingCandidates:0,semanticGroundingAccepted:0,semanticGroundingRejected:0};
  const nativeMetrics={...native.metrics,nativeOperationProbeCalls4t:1,nativeOperationProbeStructured2xx4t:success?1:0,nativeOperationResponseGroundings4t:success?ground.semanticGroundingAccepted:0,probeCacheHits:Number((cacheAfter as any).probeCacheHits||0)-Number((cacheBefore as any).probeCacheHits||0),probeNetworkFetches:Number((cacheAfter as any).probeNetworkFetches||0)-Number((cacheBefore as any).probeNetworkFetches||0),duplicateProbeNetworkFetches:Number((cacheAfter as any).duplicateProbeNetworkFetches||0)-Number((cacheBefore as any).duplicateProbeNetworkFetches||0)};if(!success)return merged(base,nativeMetrics,{request_hypotheses:[...(base.request_hypotheses||[]),h]});
  const d=deterministicPartialProjection4S(row.proof,row.relational_summary,c.input_names,c.required);let projection:any=d.projection,usage:any=null,latency_ms=0,planner_skipped=d.unresolved.length===0;
  if(d.unresolved.length){const fields=Object.fromEntries((d.unresolved as string[]).map(o=>[o,groundedFields(row.proof,o).map(f=>({field_id:f.id,path:f.path,leaf:f.leaf,sample_type:f.sample_type}))])),call=await callStructured(config,{case:{case_id:provider.case_id,intent:c.intent,input_names:c.input_names,required_outputs:c.required},locked_projection:d.projection,unresolved_outputs:d.unresolved,grounded_observed_fields:fields,native_operation_proof:native.proofs.find(p=>p.hypothesis_id===h.id)},mappingSchema(row.proof,c.input_names,d.unresolved));usage=call.usage;latency_ms=call.latency_ms;if(typeof call.raw!=="string")return merged(base,nativeMetrics);try{const extra=fallbackProjection(provider.case_id,row.proof,call.raw,d.unresolved);if(!extra)return merged(base,nativeMetrics);projection={...projection,...extra}}catch{return merged(base,nativeMetrics)}}
  const m=materialize4S(provider.case_id,provider.candidate_id,row.proof,projection,row.relational_summary);m.raw.reason=`4T_NATIVE_MACHINE_READABLE_OPERATION:${h.id}`;m.raw.frozen_request_proof=freezeRequestProof4T(h);m.raw.native_operation_proof=native.proofs.find(p=>p.hypothesis_id===h.id)||null;
  return merged(base,nativeMetrics,{http_status:0,http_ok:true,parsed_json:m.raw,parse_error:null,usage,latency_ms,probe_proof:row.proof,operation_proof:m.proof,planner_skipped,deterministic_mapping:planner_skipped,row_lookup_selected:d.rowLookups>0,identity_projection_selected:d.identityInputs>0,selected_from_trace:false,selected_from_documented_role:false,selected_from_linked_contract:true,selected_from_native_contract:true,compositional_locked_bindings:d.locked.length,exact_relational_label_selections:d.exactRelationalLabels,structured_format:row.structured_format,request_hypotheses:[...(base.request_hypotheses||[]),h],probe_records:[...(base.probe_records||[]),row.proof.record],frozenRequestProofs4t:1});
}
