import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {compileFrozenRequest,sha,type Frozen3xCase} from "./experiment3xCore.js";
import type {SafetyEvent} from "./experiment3wCore.js";

function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function publicIp(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
export async function assertPublicExecutionUrl(raw:string,safety:SafetyEvent[]=[]){const u=new URL(raw);if(u.username||u.password){safety.push({kind:"credentials_supplied",accepted:false});throw new Error("execution_credentials_rejected");}if(u.protocol!=="https:"){safety.push({kind:"http_execution",accepted:false});throw new Error("execution_non_https");}if(isIP(u.hostname)){safety.push({kind:"private_ip",accepted:false});throw new Error("execution_ip_literal");}let addrs;try{addrs=await lookup(u.hostname,{all:true,verbatim:true});}catch(e){throw new Error(`dns_unreachable:${u.hostname}:${String(e)}`);}if(!addrs.length||addrs.some(a=>!publicIp(a.address))){safety.push({kind:"private_ip",accepted:false});throw new Error("execution_non_public_dns");}return u;}
export async function executeFrozenGet(c:Frozen3xCase,input:Record<string,unknown>,safety:SafetyEvent[]=[]){const url=compileFrozenRequest(c,input,safety),u=await assertPublicExecutionUrl(url,safety);if(!c.request)throw new Error("missing_frozen_request");if(u.origin!==new URL(c.request.base_url).origin){safety.push({kind:"endpoint_mutation",accepted:false});throw new Error("execution_origin_mutated");}const requested_at=new Date().toISOString(),ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(url,{method:"GET",headers:{accept:"application/json,application/*+json,*/*","user-agent":"MISSING-Experiment-3X/0.1"},redirect:"manual",signal:ctrl.signal});if([301,302,303,307,308].includes(r.status))throw new Error("execution_redirect_rejected");if(!r.ok)throw new Error(`http_${r.status}`);const text=await r.text();if(Buffer.byteLength(text)>4*1024*1024)throw new Error("response_too_large");let body:any;try{body=JSON.parse(text);}catch{throw new Error("non_json");}const body_fingerprint=sha(text);return {requested_at,url,status:r.status,content_type:r.headers.get("content-type")||"",body_fingerprint,trace_fingerprint:sha({requested_at,url,status:r.status,content_type:r.headers.get("content-type")||"",body_fingerprint}),body};}finally{clearTimeout(timer);}}
