import { mkdir, writeFile } from "node:fs/promises";
import { Client, StreamableHTTPClientTransport, SSEClientTransport } from "@modelcontextprotocol/client";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=40,MAX_EXECUTIONS=12,TIMEOUT_MS=12000;
const READ_WORDS=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUTATION_WORDS=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
let unsafeToolsExecuted=0,requiredParamToolsExecuted=0,nonEmptyArgsExecutions=0,credentialsSupplied=0;

type Candidate={name:string;namespace:string;url:string;transport:string};
function namespaceOf(name:string){return name.includes("/")?name.split("/")[0]:name.includes(":")?name.split(":")[0]:name;}
function withTimeout<T>(p:Promise<T>):Promise<T>{return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)});});}
function normalizeRemoteType(x:any){return String(x?.type??x?.transport??"").toLowerCase();}
function remoteUrl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligibleRemote(rem:any){const type=normalizeRemoteType(rem),url=remoteUrl(rem);if(!["streamable-http","sse"].includes(type))return false;if(typeof url!=="string"||!url.startsWith("https://")||/[{}]/.test(url))return false;const h=rem?.headers;if(h&&((Array.isArray(h)&&h.length>0)||(!Array.isArray(h)&&Object.keys(h).length>0)))return false;return true;}
async function fetchRegistry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3F/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function extractRecords(body:any){if(Array.isArray(body))return body;if(Array.isArray(body?.servers))return body.servers;if(Array.isArray(body?.data))return body.data;if(Array.isArray(body?.items))return body.items;return [];}
function buildCandidates(records:any[]){const out:Candidate[]=[];for(const raw of records){const s=raw?.server??raw;const status=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(status))continue;const name=String(s?.name??raw?.name??"");if(!name)continue;const rem=(s?.remotes??raw?.remotes??[]).find(eligibleRemote);if(!rem)continue;out.push({name,namespace:namespaceOf(name),url:remoteUrl(rem),transport:normalizeRemoteType(rem)});}out.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return out.filter(c=>!seen.has(c.name)&&!!seen.add(c.name));}
function textHasWord(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
function requiredCount(tool:any){return Array.isArray(tool?.inputSchema?.required)?tool.inputSchema.required.length:0;}
function classify(tool:any){const reasons:string[]=[];if(!tool?.inputSchema||typeof tool.inputSchema!=="object"||Array.isArray(tool.inputSchema))reasons.push("invalid_input_schema");if(requiredCount(tool)>0)reasons.push("required_parameters_present");if(tool?.annotations?.readOnlyHint!==true)reasons.push("missing_affirmative_readonly_hint");if(tool?.annotations?.destructiveHint===true)reasons.push("destructive_hint_true");const text=`${tool?.name??""} ${tool?.description??""}`;if(!textHasWord(text,READ_WORDS))reasons.push("no_explicit_read_signal");if(textHasWord(text,MUTATION_WORDS))reasons.push("mutation_signal_present");return {safe:reasons.length===0,reasons};}
function makeTransport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
function authError(error:string){return /(auth|unauthorized|forbidden|\b401\b|\b403\b)/i.test(error);}
async function connectAndList(c:Candidate){const client=new Client({name:"missing-experiment-3f",version:"0.1.0"});try{await withTimeout(client.connect(makeTransport(c)));const listed:any=await withTimeout(client.listTools());return {client,tools:listed.tools??[]};}catch(e){try{await client.close();}catch{}throw e;}}
async function executeSafe(client:Client,tool:any){const args={};if(!classify(tool).safe)unsafeToolsExecuted++;if(requiredCount(tool)>0)requiredParamToolsExecuted++;if(Object.keys(args).length)nonEmptyArgsExecutions++;const started=Date.now();try{const result=await withTimeout(client.callTool({name:tool.name,arguments:args}));return {success:true,args,result,latency_ms:Date.now()-started};}catch(e){return {success:false,args,error:String(e),latency_ms:Date.now()-started};}}

const registry=await fetchRegistry();const records=extractRecords(registry);const candidates=buildCandidates(records);const evidence:any[]=[];let executionAttempts=0;const publicNamespaces=new Set<string>();let firstSuccesses=0,confirmedPublic=0,authRequired=0;
for(const c of candidates.slice(0,MAX_SERVERS)){
  let first:any;try{first=await connectAndList(c);}catch(e){evidence.push({...c,state:"unreachable",error:String(e)});continue;}
  const decisions=first.tools.map((tool:any)=>({tool:{name:tool.name,description:tool.description??null,inputSchema:tool.inputSchema,annotations:tool.annotations??null},...classify(tool)}));
  const safe=decisions.find((d:any)=>d.safe)?.tool;
  if(!safe){await first.client.close();evidence.push({...c,state:"no_safe_candidate",decisions});continue;}
  if(executionAttempts>=MAX_EXECUTIONS){await first.client.close();evidence.push({...c,state:"no_safe_candidate",decisions,note:"execution_budget_exhausted"});continue;}
  executionAttempts++;const firstExec=await executeSafe(first.client,safe);await first.client.close();
  if(!firstExec.success){const state=authError(String(firstExec.error))?"auth_required":"execution_error";if(state==="auth_required")authRequired++;evidence.push({...c,state,decisions,first_execution:{tool_name:safe.name,...firstExec}});continue;}
  firstSuccesses++;
  let second:any;try{second=await connectAndList(c);}catch(e){evidence.push({...c,state:"execution_error",decisions,first_execution:{tool_name:safe.name,...firstExec},confirmation_error:String(e)});continue;}
  const same=second.tools.find((t:any)=>t.name===safe.name);if(!same||!classify(same).safe){await second.client.close();evidence.push({...c,state:"execution_error",decisions,first_execution:{tool_name:safe.name,...firstExec},confirmation_error:"tool_missing_or_no_longer_safe"});continue;}
  const secondExec=await executeSafe(second.client,same);await second.client.close();
  if(secondExec.success){confirmedPublic++;publicNamespaces.add(c.namespace);evidence.push({...c,state:"public",decisions,first_execution:{tool_name:safe.name,...firstExec},second_execution:{tool_name:safe.name,...secondExec}});}else{const state=authError(String(secondExec.error))?"auth_required":"execution_error";if(state==="auth_required")authRequired++;evidence.push({...c,state,decisions,first_execution:{tool_name:safe.name,...firstExec},second_execution:{tool_name:safe.name,...secondExec}});}
}
const observedStates=new Set(evidence.map(x=>x.state)).size;const confirmationRate=firstSuccesses?confirmedPublic/firstSuccesses:0;
const criteria={four_public_servers:confirmedPublic>=4,four_distinct_namespaces:publicNamespaces.size>=4,public_confirmation_rate:confirmationRate===1,one_auth_required:authRequired>=1,zero_unsafe_executions:unsafeToolsExecuted===0,zero_required_parameter_executions:requiredParamToolsExecuted===0,zero_nonempty_args:nonEmptyArgsExecutions===0,zero_credentials:credentialsSupplied===0,three_readiness_states:observedStates>=3,evidence_persisted:true};
const decision=Object.values(criteria).every(Boolean)?"GO_MCP_EXECUTION_READINESS":"REASSESS_MCP_EXECUTION_READINESS";
const summary={experiment:"MISSING Experiment 3F — MCP Execution Readiness Discovery",created_at:new Date().toISOString(),metrics:{registry_records:records.length,eligible_servers:candidates.length,servers_inspected:evidence.length,execution_attempts:executionAttempts,first_execution_successes:firstSuccesses,confirmed_public_servers:confirmedPublic,public_namespaces:publicNamespaces.size,auth_required_servers:authRequired,observed_readiness_states:observedStates,public_confirmation_rate:confirmationRate,unsafe_tools_executed:unsafeToolsExecuted,required_param_tools_executed:requiredParamToolsExecuted,nonempty_args_executions:nonEmptyArgsExecutions,credentials_supplied:credentialsSupplied},criteria,decision,states:Object.fromEntries([...new Set(evidence.map(x=>x.state))].map(s=>[s,evidence.filter(x=>x.state===s).length]))};
await mkdir("results/experiment-3f",{recursive:true});await writeFile("results/experiment-3f/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3f/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:registry,candidates,server_evidence:evidence},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
