import type {Config} from "./config/index.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {materializeSelectionP1} from "./experiment4ap1Core.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,type P1ProbeProof,type P1SemanticSelection} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4L} from "./experiment4lRequest.js";
import {probeCacheMetrics4L,probeHypothesis4L} from "./experiment4lProbe.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(r=>[r.case_id,r]));
function overlap(a:string,b:string){const x=new Set(lexicalTokensP1(a)),y=new Set(lexicalTokensP1(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function echoCompatible(o:string,i:string){const out=lexicalTokensP1(o),inp=new Set(lexicalTokensP1(i));return out.length>0&&out.every(t=>inp.has(t))}
function fieldPacket(p:P1ProbeProof,req:readonly string[]){return [...p.record.observed_fields].map(field=>({field,score:Math.max(0,...req.map(o=>overlap(o,field.leaf)))*100+field.build_value_relations.length*20-Math.min(30,field.path.split(".").length)})).sort((a,b)=>b.score-a.score||a.field.path.length-b.field.path.length).slice(0,48).map(r=>r.field)}
function deterministic(proofs:P1ProbeProof[],inputs:readonly string[],required:readonly string[]){for(const proof of proofs){const bindings:{task_output:string;source_id:string}[]=[],used=new Set<string>();let ok=true;for(const output of required){const echoes=inputs.filter(i=>echoCompatible(output,i)).map(i=>`TASK_INPUT:${i}`),positive=proof.record.observed_fields.filter(f=>overlap(output,f.leaf)>0).sort((a,b)=>overlap(output,b.leaf)-overlap(output,a.leaf)||a.path.length-b.path.length);let source:string|null=null;if(echoes.length===1&&positive.length===0)source=echoes[0];else if(echoes.length===0&&positive.length===1)source=positive[0].id;else if(echoes.length===1&&positive.length===1&&positive[0].build_value_relations.some(r=>r.startsWith(echoes[0]+":")))source=positive[0].id;if(!source||(!source.startsWith("TASK_INPUT:")&&used.has(source))){ok=false;break}if(!source.startsWith("TASK_INPUT:"))used.add(source);bindings.push({task_output:output,source_id:source})}if(ok)return {proof,selection:{decision:"SELECT",hypothesis_id:proof.hypothesis.id,output_bindings:bindings,reason:"4L_DETERMINISTIC_OBSERVED_MAPPING"} as P1SemanticSelection}}return null}
async function callStructured(config:Config,payload:any,jsonSchema:any){const started=Date.now(),response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:"Map required outputs only to supplied successful 4L documentation-grounded probe hypotheses and observed field IDs or TASK_INPUT echoes. Executable-operation and route-family proof are immutable. Never invent or mutate URL, host, path, parameters, credentials, fields or indices. Reject if output correspondence is not defensible."},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:jsonSchema}})}),latency_ms=Date.now()-started,text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}return {status:response.status,ok:response.ok,latency_ms,usage:body?.usage??null,raw:body?.choices?.[0]?.message?.content??null,refusal:body?.choices?.[0]?.message?.refusal??null}}
function schema(proofs:P1ProbeProof[],inputs:readonly string[],required:readonly string[]){const hs=proofs.map(p=>p.hypothesis.id),fields=[...new Set(proofs.flatMap(p=>fieldPacket(p,required).map(f=>f.id)))],sources=[...fields,...inputs.map(i=>`TASK_INPUT:${i}`)];return {name:"missing_4l_observed_mapping",strict:true,schema:{type:"object",additionalProperties:false,properties:{decision:{type:"string",enum:["SELECT","REJECT"]},hypothesis_id:{type:"string",enum:hs},output_bindings:{type:"array",minItems:required.length,maxItems:required.length,items:{type:"object",additionalProperties:false,properties:{task_output:{type:"string",enum:required},source_id:{type:"string",enum:sources}},required:["task_output","source_id"]}},reason:{type:"string"}},required:["decision","hypothesis_id","output_bindings","reason"]}}}
function parse(raw:any):P1SemanticSelection{if(typeof raw!=="string")throw new Error("4l_planner_missing_content");const v=JSON.parse(raw);return {decision:v.decision,hypothesis_id:String(v.hypothesis_id),output_bindings:(v.output_bindings||[]).map((r:any)=>({task_output:String(r.task_output),source_id:String(r.source_id)})),reason:String(v.reason||"")}}
function routeFamily(h:any){return String(h?.proof_type||"").startsWith("4l_executable_route_family_")}
function delta(a:Record<string,number>,b:Record<string,number>,k:string){return Number(b[k]||0)-Number(a[k]||0)}
export async function synthesize4l(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){
  const c=BY_ID[provider.case_id];if(!c)throw new Error(`4l_unknown_case:${provider.case_id}`);
  const request=await prepareRequestGraph4L(evidence,provider.case_id,ledger),probeRecords:P1ProbeProof[]=[],cacheBefore=probeCacheMetrics4L();
  for(const h of request.probe_packet.slice(0,FOUR_AP1_MAX_PROBES_PER_PROVIDER)){const got=await probeHypothesis4L(h,c.build,ledger);probeRecords.push(got.proof)}
  const cacheAfter=probeCacheMetrics4L(),cacheMetrics={probeCacheHits:delta(cacheBefore,cacheAfter,"probeCacheHits"),probeNetworkFetches:delta(cacheBefore,cacheAfter,"probeNetworkFetches"),duplicateProbeNetworkFetches:delta(cacheBefore,cacheAfter,"duplicateProbeNetworkFetches")};
  const successful=probeRecords.filter(r=>r.record.disposition==="success"),routeProbes=probeRecords.filter(r=>routeFamily(r.hypothesis)),routeSuccess=routeProbes.filter(r=>r.record.disposition==="success"),probeMetrics={schemaProbeCalls:probeRecords.length,schemaProbe2xxJson:successful.length,schemaProbeRejected:probeRecords.length-successful.length,schemaProbeBytes:successful.reduce((n,r)=>n+r.record.bytes,0),routeFamilyProbeCalls:routeProbes.length,routeFamilyProbe2xxJson:routeSuccess.length,executableGateProbeCalls:routeProbes.length,executableGateProbe2xxJson:routeSuccess.length,...cacheMetrics},noIrOperation=request.metrics.noIrOperation,irOperationUnusable=request.metrics.irOperationUnusable,attribution={request_inventory_count:request.hypotheses.length,alignment_metrics:request.metrics,operation_semantics_fingerprint:request.semantics.fingerprint,request_graph_fingerprint:request.graph_fingerprint,request_hypotheses:request.probe_packet,probe_records:probeRecords.map(r=>r.record),...probeMetrics,noIrOperation,irOperationUnusable};
  if(!successful.length)return {http_status:0,http_ok:true,refusal:null,raw_content:null,parsed_json:{case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:noIrOperation?"4L_NO_OPERATION":irOperationUnusable?"4L_ALIGNMENT_UNUSABLE":"4L_GATED_PROBE_FAILED"},parse_error:null,usage:null,latency_ms:0,probe_proof:null,semantic_selection:null,planner_skipped:true,deterministic_mapping:false,selected_from_route_family:false,...attribution};
  const d=deterministic(successful,c.input_names,c.required);
  if(d){const m=materializeSelectionP1(provider.case_id,provider.candidate_id,d.proof,d.selection);m.raw.reason=`4L_EXECUTABLE_API_OPERATION_FAMILY:${d.proof.hypothesis.id}`;return {http_status:0,http_ok:true,refusal:null,raw_content:null,parsed_json:m.raw,parse_error:null,usage:null,latency_ms:0,probe_proof:d.proof,semantic_selection:d.selection,operation_proof:m.proof,planner_skipped:true,deterministic_mapping:true,selected_from_route_family:routeFamily(d.proof.hypothesis),selected_from_expanded_evidence:d.proof.hypothesis.evidence_ids.some(id=>/^4[e-g]_ref_/.test(id)),...attribution}}
  const call=await callStructured(config,{case:{case_id:provider.case_id,intent:c.intent,input_names:c.input_names,required_outputs:c.required,build_input:c.build,replay_input:c.replay},provider:{candidate_id:provider.candidate_id,name:provider.name},alignment_fingerprint:request.graph_fingerprint,successful_probe_hypotheses:successful.map(p=>({hypothesis_id:p.hypothesis.id,origin:p.hypothesis.origin,full_path:p.hypothesis.full_path,proof_type:p.hypothesis.proof_type,evidence_ids:p.hypothesis.evidence_ids,fields:fieldPacket(p,c.required).map(f=>({field_id:f.id,path:f.path,leaf:f.leaf,sample_type:f.sample_type,sample_value:f.sample_value,build_value_relations:f.build_value_relations}))}))},schema(successful,c.input_names,c.required));
  let selection:P1SemanticSelection|null=null,parsed_json:any=null,probe_proof:P1ProbeProof|null=null,operation_proof:any=null,parse_error:string|null=null;
  try{selection=parse(call.raw);if(selection.decision==="REJECT")parsed_json={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:`4L_SUCCESSFUL_PROBE_MAPPING_REJECT:${selection.reason}`};else{probe_proof=successful.find(r=>r.hypothesis.id===selection!.hypothesis_id)||null;if(!probe_proof)throw new Error("4l_selected_probe_missing");const m=materializeSelectionP1(provider.case_id,provider.candidate_id,probe_proof,selection);m.raw.reason=`4L_EXECUTABLE_API_OPERATION_FAMILY:${probe_proof.hypothesis.id}`;parsed_json=m.raw;operation_proof=m.proof}}catch(e){parse_error=String(e).replace(/^Error:\s*/,"")}
  return {http_status:call.status,http_ok:call.ok,refusal:call.refusal,raw_content:call.raw,parsed_json,parse_error,usage:call.usage,latency_ms:call.latency_ms,probe_proof,semantic_selection:selection,operation_proof,planner_skipped:false,deterministic_mapping:false,selected_from_route_family:probe_proof?routeFamily(probe_proof.hypothesis):false,selected_from_expanded_evidence:probe_proof?.hypothesis.evidence_ids.some(id=>/^4[e-g]_ref_/.test(id))??false,...attribution};
}
