import {deriveExperiment5b14Source} from "./experiment5b14Derivation.js";

function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b16_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
function replaceBetween(s:string,start:string,end:string,replacement:string){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);if(a<0||b<0)throw new Error(`5b16_range_anchor_missing:${start}`);return s.slice(0,a)+replacement+s.slice(b)}

const FROZEN_LOOP=`let authLikeRenderedRequests5b16=0,wrongTaskProbeAttempts5b16=0;
for(const primary of frozen5b16.primaries){
 const c=FOUR_A_CASES.find((x:any)=>x.case_id===primary.case_id);const caseStart=Date.now(),attempts:any[]=[];let success:any=null;
 if(!c){wrongTaskProbeAttempts5b16++;caseEvidence.push({family:primary.family,case_id:primary.case_id,primary_recipe_fingerprint:primary.primary_recipe_fingerprint,selected:[],attempts:[{status:"frozen_case_missing"}],success:null,elapsed_ms:Date.now()-caseStart});continue;}
 const selected=resolveFrozenTail5b16(frozen5b16,catalog,c.case_id);
 for(const s of selected){
  if(s.case_id!==c.case_id||s.primary_recipe_fingerprint!==primary.primary_recipe_fingerprint){wrongTaskProbeAttempts5b16++;attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"frozen_identity_context_mismatch"});continue;}
  if(Number(s.selected_position)>8){attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"position_over_8_violation"});continue;}
  if(s.duplicate_url_identity){attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"duplicate_identity_skipped",url_fingerprint:s.url_fingerprint,identity_resolved:s.identity_resolved});continue;}
  if(!s.identity_resolved||!s.link){attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"identity_unresolved",url_fingerprint:s.url_fingerprint,identity_error:s.identity_error,identity_match_count:s.identity_match_count});continue;}
  const originalStart=String(s.link),upgrade=originalStart.startsWith("http://")?httpsUpgradeCandidate5B9(originalStart):null,effectiveStart=originalStart.startsWith("https://")?originalStart:upgrade?.url??null;
  if(!effectiveStart){attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"provider_ineligible",reason:"non_https_catalog_start_not_upgradeable"});continue;}
  if(!independentProviderDomain5b16(primary.primary_provider_start_url,effectiveStart)){attempts.push({candidate_id:s.candidate_id,name:s.name,selected_position:s.selected_position,status:"independent_domain_reject"});continue;}
  const p:Provider4A={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:effectiveStart},cr=await crawl5b9(p,ledger,originalStart),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence,cr.recovery?.lineages||[]);
  if(!syn.contract||!syn.projection||syn.contract.decision!=="COMPILE"){attempts.push({candidate_id:p.candidate_id,name:p.name,selected_position:s.selected_position,status:"contract_reject",error:syn.error,docs:cr.evidence.length});continue;}
  const contract=syn.contract as MicroContract;let first:any=null,second:any=null,out2:any=null,buildUrl="";
  try{buildUrl=compile4ar(contract,c.build);if(authLikeRenderedUrl5b16(buildUrl)){authLikeRenderedRequests5b16++;throw new Error("auth_like_rendered_build_request");}first=await safeJson(buildUrl,ledger);const out1=project4ar(syn.projection,first.body,c.build);if(!validateProjected4ar(c.case_id,c.build,out1))throw new Error("semantic_validation_first_failed");second=await safeJson(buildUrl,ledger);out2=project4ar(syn.projection,second.body,c.build);if(!validateProjected4ar(c.case_id,c.build,out2))throw new Error("semantic_validation_confirmation_failed");if(!sameRequired(out1,out2,c.required))throw new Error("confirmation_value_mismatch");}catch(e:any){attempts.push({candidate_id:p.candidate_id,name:p.name,selected_position:s.selected_position,status:"build_verify_failed",error:String(e)});continue;}
  const replayBefore={catalog_fetches:catalogFetches,reranker_calls:rerankerCalls,documentation_fetches:docFetches,synthesis_calls:synthesisCalls,recovery_fetches:Number(recoveryMetrics5b9.recoveryFetchAttempts5b9||0)};let replayRecord:any=null;
  try{const replayUrl=compile4ar(contract,c.replay);if(authLikeRenderedUrl5b16(replayUrl)){authLikeRenderedRequests5b16++;throw new Error("auth_like_rendered_replay_request");}const got=await safeJson(replayUrl,ledger),out=project4ar(syn.projection,got.body,c.replay);if(!validateProjected4ar(c.case_id,c.replay,out))throw new Error("alternate_replay_semantic_validation_failed");const replayDeltas={catalog_fetches:catalogFetches-replayBefore.catalog_fetches,reranker_calls:rerankerCalls-replayBefore.reranker_calls,documentation_fetches:docFetches-replayBefore.documentation_fetches,synthesis_calls:synthesisCalls-replayBefore.synthesis_calls,recovery_fetches:Number(recoveryMetrics5b9.recoveryFetchAttempts5b9||0)-replayBefore.recovery_fetches};replayRecord={case_id:c.case_id,provider_candidate_id:p.candidate_id,success:true,output:out,verification:got,replay_deltas:replayDeltas};}catch(e:any){const replayDeltas={catalog_fetches:catalogFetches-replayBefore.catalog_fetches,reranker_calls:rerankerCalls-replayBefore.reranker_calls,documentation_fetches:docFetches-replayBefore.documentation_fetches,synthesis_calls:synthesisCalls-replayBefore.synthesis_calls,recovery_fetches:Number(recoveryMetrics5b9.recoveryFetchAttempts5b9||0)-replayBefore.recovery_fetches};attempts.push({candidate_id:p.candidate_id,name:p.name,selected_position:s.selected_position,status:"replay_failed",error:String(e),replay_deltas:replayDeltas});continue;}
  const po=plannerOutput5b14(synthesisEvidence,p.case_id,p.candidate_id),recipe:any={family:c.family,case_id:c.case_id,primary_recipe_fingerprint:primary.primary_recipe_fingerprint,primary_provider_start_url:primary.primary_provider_start_url,provider_candidate_id:p.candidate_id,provider_name:p.name,provider_start_url:p.start_url,provider_catalog_start_url:originalStart,frozen_selected_position:s.selected_position,frozen_url_fingerprint:s.url_fingerprint,provider_selection_fingerprint:frozen5b16.frozen_tail_fingerprint,documentation_fingerprint:sha3yr(cr.evidence.map((e:any)=>({id:e.evidence_id,url:e.resolved_url,fp:e.body_fingerprint,state:e.state}))),frontier_fingerprint:frontierFingerprint(cr.frontier),recovery_lineage_5b9:cr.recovery?.lineages||[],recovery_surface_witness_5b9:cr.recovery?.summary||null,documentary_witness_5b12:po?.documentary_witness_5b12??null,request_utility_5b14:po?.request_utility_5b14??null,contract,contract_fingerprint:sha3yr(contract),projection_kind:"3x_typed_program",projection:syn.projection,projection_fingerprint:sha3yr(syn.projection),first_verification:first,confirmation_verification:second,changed_input_replay:replayRecord};recipe.recipe_fingerprint=sha3yr({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);success={candidate_id:p.candidate_id,name:p.name,host:hostOf(p.start_url),output:out2,recipe_fingerprint:recipe.recipe_fingerprint,primary_recipe_fingerprint:primary.primary_recipe_fingerprint};attempts.push({candidate_id:p.candidate_id,name:p.name,selected_position:s.selected_position,status:"qualified_alternate",recipe_fingerprint:recipe.recipe_fingerprint,replay_deltas:replayRecord.replay_deltas});break;
 }
 caseEvidence.push({family:c.family,case_id:c.case_id,primary_recipe_fingerprint:primary.primary_recipe_fingerprint,primary_provider_start_url:primary.primary_provider_start_url,unhealthy_after_5b15:primary.unhealthy_after_5b15,selected:selected.map((x:any)=>({candidate_id:x.candidate_id,name:x.name,selected_position:x.selected_position,lexical_rank:x.lexical_rank,url_fingerprint:x.url_fingerprint,duplicate_url_identity:x.duplicate_url_identity,identity_resolved:x.identity_resolved,identity_match_count:x.identity_match_count,identity_error:x.identity_error})),attempts,success,elapsed_ms:Date.now()-caseStart});
}
`;

const FINAL_REPORT=`const replay:any[]=recipes.map((r:any)=>r.changed_input_replay);const successful=caseEvidence.filter((x:any)=>x.success),successFamilies=new Set(successful.map((x:any)=>x.family)),providers=new Set(successful.map((x:any)=>x.success.host)),counters=derivedSafetyCounters(ledger),verifiedControls=controls.filter((x:any)=>x.executed&&x.rejected).length,totalLlmCost=llmUsage.reduce((s:number,x:any)=>s+Number(x.cost_usd||0),0),meanCost=recipes.length?totalLlmCost/recipes.length:null,replayDeltas=caseEvidence.flatMap((x:any)=>x.attempts||[]).map((x:any)=>x.replay_deltas).filter(Boolean).reduce((a:any,d:any)=>({catalog_fetches:a.catalog_fetches+Number(d.catalog_fetches||0),reranker_calls:a.reranker_calls+Number(d.reranker_calls||0),documentation_fetches:a.documentation_fetches+Number(d.documentation_fetches||0),synthesis_calls:a.synthesis_calls+Number(d.synthesis_calls||0),recovery_fetches:a.recovery_fetches+Number(d.recovery_fetches||0)}),{catalog_fetches:0,reranker_calls:0,documentation_fetches:0,synthesis_calls:0,recovery_fetches:0});const report:any={experiment:"5B16-ENGINE",purpose:"development_verified_recipe_redundancy_acquisition_engine",started_at,finished_at:new Date().toISOString(),base_sha:"a6c1f471e2067108fa929cff52d6245051d687e0",model:FOUR_A_MODEL,pricing:FOUR_A_PRICE,metrics:{...recoveryMetrics5b9,frozenPrimaryCount5b16:frozen5b16.primaries.length,rawFrozenTailCount5b16:frozen5b16.raw_tail_count,distinctFrozenTailUrlIdentities5b16:frozen5b16.distinct_tail_url_identity_count,catalogIdentityResolutionFetches5b16:catalogFetches,broadRetrievalCalls5b16:0,newProviderSelectionCalls5b16:0,qualifyingAlternates5b16:recipes.length,capabilitiesWithAlternates5b16:successful.length,familiesWithAlternates5b16:successFamilies.size,distinctAlternateProviders5b16:providers.size,catalogFetches,rerankerCalls,docFetches,specProbeFetches,synthesisCalls,synthesisRepairs,liveCalls,total_llm_cost_usd:totalLlmCost,mean_llm_cost_per_qualifying_alternate_usd:meanCost,authLikeRenderedRequests5b16,wrongTaskProbeAttempts5b16,replay_deltas:replayDeltas,controls:controls.length,controls_verified:verifiedControls},caseEvidence,replay,recipes,llmUsage,rerankEvidence,synthesisEvidence,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()},frozen_workload:{frozen_tail_fingerprint:frozen5b16.frozen_tail_fingerprint,unhealthy_primary_set_fingerprint:frozen5b16.unhealthy_primary_set_fingerprint,primary_set_fingerprint:frozen5b16.primary_set_fingerprint,public_apis_snapshot:frozen5b16.public_apis_snapshot}};report.fingerprint=fourArSha(report);await writeFile(OUT+"/report.json",JSON.stringify(report,null,2));console.log(JSON.stringify({experiment:report.experiment,metrics:report.metrics,fingerprint:report.fingerprint},null,2));}
`;

export function deriveExperiment5b16Source(source:string){let x=deriveExperiment5b14Source(source);
 x='import {authLikeRenderedUrl5b16,independentProviderDomain5b16,loadFiveB16Workload,resolveFrozenTail5b16} from "./experiment5b16Workload.js";\n'+x;
 x=r(x,'const OUT="results/experiment-5b14-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b16-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
 x=r(x,'catalogFetches++;const catalog=(await fetchTextSafeR2(PUBLIC_APIS_URL,PUBLIC_APIS_URL,MAX_BYTES,ledger)).text;','const frozen5b16=loadFiveB16Workload();catalogFetches++;const frozenCatalogUrl=frozen5b16.public_apis_snapshot.raw_url;const catalog=(await fetchTextSafeR2(frozenCatalogUrl,frozenCatalogUrl,MAX_BYTES,ledger)).text;');
 x=replaceBetween(x,'for(const c of FOUR_A_CASES){','const before=',FROZEN_LOOP);
 x=replaceBetween(x,'const before=','main().catch',FINAL_REPORT);
 x=x.replaceAll('experiment:"5B14-ENGINE"','experiment:"5B16-ENGINE"').replaceAll('purpose:"development_symmetric_request_local_operation_compatibility_engine"','purpose:"development_verified_recipe_redundancy_acquisition_engine"');
 return x;
}
