import {mkdir,writeFile} from "node:fs/promises";
import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {createHash} from "node:crypto";
import {loadConfig} from "./config/index.js";

const TIMEOUT_MS=12000,MAX_OPS=12;
const CASES=[
 {case_id:"constrained_capital_coordinates",intent:"Given a country name, return coordinates for that country's capital city, and prove that the geocoded result belongs to the same country.",build:{country:"Costa Rica"},replay:{country:"Japan"}},
 {case_id:"ambiguity_control",intent:"Given a country name, return coordinates for its capital while preserving country identity through the downstream lookup.",build:{country:"Panama"},replay:{country:"Mexico"}}
] as const;
const SOURCES={
 worldbank_countries:{source_id:"worldbank_countries",description:"World Bank country metadata. Response array index 1 contains country records with name and capitalCity.",url_template:"https://api.worldbank.org/v2/country?format=json&per_page=400"},
 openmeteo_geocode:{source_id:"openmeteo_geocode",description:"Open-Meteo geocoder. Query by city and return up to 10 results containing name, latitude, longitude, country and country_code.",url_template:"https://geocoding-api.open-meteo.com/v1/search?name={city}&count=10&language=en&format=json"}
};
const EXISTING_SUPPLY={city_geocode:{capability_id:"city_geocode",description:"Unconstrained city geocoder that selects the first city-name match. Insufficient when country identity must be preserved.",input:{city:"string"}}};
const OPS=new Set(["SOURCE","ARRAY_GET","FILTER_EQ","FIRST","SELECT","PROJECT","TRIM","LOWERCASE","OUTPUT"]);
let plannerCalls=0,repairCalls=0,replayPlannerCalls=0,sourceViolations=0,operationViolations=0,hostViolations=0,redirectsFollowed=0,credentialsSupplied=0,arbitraryCodeExecuted=0,negativeControlAccepted=0;

type Ref = "$input.country"|"$capital";
type Op={op:string,source_id?:string,args?:Record<string,string>,index?:number,path?:string,ref?:Ref,fields?:string[]};
type Plan={case_id:string,decision:"ROUTE"|"COMPOSE"|"MANUFACTURE"|"REJECT",reason?:string,ops?:Op[]};
const sha=(x:any)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
function pathGet(v:any,path:string){return path.split(".").filter(Boolean).reduce((x,k)=>x?.[k],v);}
function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function isPublic(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
async function safeUrl(raw:string){const u=new URL(raw),e:any={url:raw,hostname:u.hostname,resolved:[],allowed:false};if(u.protocol!=="https:"||isIP(u.hostname)){hostViolations++;throw new Error("host_policy_protocol_or_ip_literal");}const addrs=await lookup(u.hostname,{all:true,verbatim:true});e.resolved=addrs;if(!addrs.length||addrs.some(a=>!isPublic(a.address))){hostViolations++;throw new Error("host_policy_non_public_dns");}e.allowed=true;return e;}
async function fetchJson(url:string,evidence:any[]){evidence.push(await safeUrl(url));const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3N/0.1"},redirect:"manual",signal:ctrl.signal});if(r.status>=300&&r.status<400)throw new Error(`redirect_rejected_${r.status}`);if(!r.ok)throw new Error(`http_${r.status}`);if(!(r.headers.get("content-type")??"").toLowerCase().includes("json"))throw new Error("non_json");return await r.json();}finally{clearTimeout(timer);}}
function validatePlan(p:Plan,c:any){const e:string[]=[];if(p.case_id!==c.case_id)e.push("case_id_mismatch");if(p.decision!=="MANUFACTURE")return e;const ops=p.ops??[];if(ops.length<6||ops.length>MAX_OPS)e.push("invalid_op_count");let wb=false,geo=false,countryFilter=false,output=false;for(const [i,o] of ops.entries()){if(!OPS.has(o.op)){operationViolations++;e.push(`unknown_op:${o.op}`);continue;}if(o.op==="SOURCE"){if(o.source_id!=="worldbank_countries"&&o.source_id!=="openmeteo_geocode"){sourceViolations++;e.push("unknown_source");}if(o.source_id==="worldbank_countries")wb=true;if(o.source_id==="openmeteo_geocode"){geo=true;if(o.args?.city!=="$capital")e.push("geocode_city_must_capital");}}
 if(o.op==="FILTER_EQ"){if(o.path==="name"&&o.ref==="$input.country"&&!geo){}else if(o.path==="country"&&o.ref==="$input.country"&&geo)countryFilter=true;else e.push(`invalid_filter:${i}`);}if(o.op==="PROJECT"){const f=new Set(o.fields??[]);if(!["latitude","longitude","country","name"].every(x=>f.has(x)))e.push("project_missing_fields");}if(o.op==="OUTPUT")output=true;}
 if(!wb)e.push("missing_worldbank");if(!geo)e.push("missing_geocoder_adapter");if(!countryFilter)e.push("missing_country_constraint");if(!output)e.push("missing_output");if((p.reason??"").includes("city_geocode(city only)"))negativeControlAccepted++;return e;}
async function execute(p:Plan,input:any,net:any[]){let value:any,capital:string|undefined,geoStarted=false;for(const o of p.ops??[]){switch(o.op){case"SOURCE":if(o.source_id==="worldbank_countries"){value=await fetchJson(SOURCES.worldbank_countries.url_template,net);geoStarted=false;}else{if(!capital)throw new Error("missing_capital");value=await fetchJson(SOURCES.openmeteo_geocode.url_template.replace("{city}",encodeURIComponent(capital)),net);value=value?.results??[];geoStarted=true;}break;case"ARRAY_GET":if(!Array.isArray(value))throw new Error("array_get_non_array");value=value[o.index!];break;case"FILTER_EQ":if(!Array.isArray(value))throw new Error("filter_non_array");{const expected=o.ref==="$input.country"?input.country:capital;value=value.filter((x:any)=>String(pathGet(x,o.path!)).trim()===String(expected).trim());}break;case"FIRST":if(!Array.isArray(value)||!value.length)throw new Error("first_empty");value=value[0];break;case"SELECT":value=pathGet(value,o.path!);break;case"PROJECT":{const q:any={};for(const f of o.fields??[])q[f]=value?.[f];value=q;}break;case"TRIM":if(typeof value!=="string")throw new Error("trim_non_string");value=value.trim();if(!geoStarted)capital=value;break;case"LOWERCASE":if(typeof value!=="string")throw new Error("lower_non_string");value=value.toLowerCase();break;case"OUTPUT":if(!value||typeof value.latitude!=="number"||typeof value.longitude!=="number"||String(value.country).trim()!==String(input.country).trim())throw new Error("semantic_constraint_failure");return {capital,final_output:value};default:throw new Error("unsupported_op");}}
 throw new Error("no_output");}
async function planner(config:any,c:any,failed?:string){plannerCalls++;if(failed)repairCalls++;const system=`You are MISSING Constraint-Preserving Composer. Existing city_geocode(city) is explicitly insufficient because it can return a homonymous city in the wrong country. Choose MANUFACTURE only if the approved sources and DSL can preserve the original country constraint through the chain. Allowed ops: SOURCE, ARRAY_GET, FILTER_EQ, FIRST, SELECT, PROJECT, TRIM, LOWERCASE, OUTPUT. Max ${MAX_OPS}. World Bank must derive the capital from the country. Open-Meteo may then search up to 10 city candidates. The chain must FILTER_EQ candidate.country against $input.country before FIRST and PROJECT latitude, longitude, country, name. Never invent URLs, constants, code, credentials, transforms, or fields. Return JSON only.`;const payload={case:{case_id:c.case_id,intent:c.intent,input_schema:{country:"string"}},existing_supply:EXISTING_SUPPLY,approved_sources:SOURCES,entity_constraint:"Final selected geocoder candidate country must exactly equal $input.country; latitude/longitude must come from that same candidate.",dsl:[...OPS],output_schema:{case_id:c.case_id,decision:"ROUTE|COMPOSE|MANUFACTURE|REJECT",reason:"string",ops:"ordered DSL operations using only approved sources and refs $input.country/$capital"},previous_failure:failed??null};const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`planner_${r.status}:${await r.text()}`);const b:any=await r.json();return JSON.parse(b.choices?.[0]?.message?.content??"{}");}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3N");const results:any[]=[],persisted:any[]=[];
for(const c of CASES){let plan:Plan=await planner(config,c),errors=validatePlan(plan,c),execution:any=null,repaired=false,network:any[]=[];if(plan.decision==="MANUFACTURE"&&!errors.length){try{execution=await execute(plan,c.build,network);}catch(e){plan=await planner(config,c,"Static-valid chain failed live/semantic validation. Repair using same sources, DSL and country-preservation rule.");repaired=true;errors=validatePlan(plan,c);network=[];if(plan.decision==="MANUFACTURE"&&!errors.length)try{execution=await execute(plan,c.build,network);}catch(e2){execution={error:String(e2)};}else execution={error:"repair_invalid"};}}const validated=plan.decision==="MANUFACTURE"&&!errors.length&&execution&&!execution.error;if(validated)persisted.push({case_id:c.case_id,plan,fingerprint:sha(plan),execution});results.push({case_id:c.case_id,plan,static_errors:errors,static_valid:!errors.length,validated,repaired,execution,network_evidence:network});}
const replay:any[]=[];for(const p of persisted){const c=CASES.find(x=>x.case_id===p.case_id)!;const before=plannerCalls,network:any[]=[];try{const output=await execute(p.plan,c.replay,network);replay.push({case_id:p.case_id,success:true,input:c.replay,output,fingerprint:p.fingerprint,network_evidence:network});}catch(e){replay.push({case_id:p.case_id,success:false,input:c.replay,error:String(e),fingerprint:p.fingerprint,network_evidence:network});}replayPlannerCalls+=plannerCalls-before;}
const rs=replay.filter(x=>x.success).length,rr=persisted.length?rs/persisted.length:0,caseA=results.find(x=>x.case_id==="constrained_capital_coordinates");const allSem=persisted.every(x=>String(x.execution?.final_output?.country).trim()===String(CASES.find(c=>c.case_id===x.case_id)!.build.country).trim()&&replay.filter(r=>r.case_id===x.case_id&&r.success).every(r=>String(r.output?.final_output?.country).trim()===String(r.input.country).trim()));
const criteria={one_manufacture:results.some(x=>x.plan.decision==="MANUFACTURE"),one_static_constraint_chain:results.some(x=>x.plan.decision==="MANUFACTURE"&&x.static_valid),one_live_semantic_pass:persisted.length>=1,case_a_country_exact:caseA?.execution?.final_output?.country==="Costa Rica",case_a_not_known_wrong_result:!(caseA?.execution?.final_output?.country==="United States"&&caseA?.execution?.final_output?.name==="San Jose"),one_replay:rs>=1,replay_success_rate:rr===1,all_outputs_preserve_country:allSem,negative_control_accepted_zero:negativeControlAccepted===0,replay_planner_calls_zero:replayPlannerCalls===0,source_operation_policy_zero:sourceViolations===0&&operationViolations===0,host_policy_zero:hostViolations===0,redirects_followed_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,provenance_fingerprints:persisted.every(x=>x.fingerprint?.length===64)};
const decision=Object.values(criteria).every(Boolean)?"GO_CONSTRAINT_PRESERVING_AUTONOMOUS_COMPOSITION":"REASSESS_CONSTRAINT_PRESERVING_AUTONOMOUS_COMPOSITION";const summary={experiment:"MISSING Experiment 3N — Constraint-Preserving Autonomous Composition",created_at:new Date().toISOString(),metrics:{cases:CASES.length,planner_calls:plannerCalls,repair_calls:repairCalls,manufacture_decisions:results.filter(x=>x.plan.decision==="MANUFACTURE").length,static_valid_chains:results.filter(x=>x.plan.decision==="MANUFACTURE"&&x.static_valid).length,validated_chains:persisted.length,replay_successes:rs,replay_success_rate:rr,replay_planner_calls:replayPlannerCalls,negative_control_accepted:negativeControlAccepted,source_policy_violations:sourceViolations,operation_policy_violations:operationViolations,host_policy_violations:hostViolations,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted},criteria,decision,results:results.map(x=>({case_id:x.case_id,plan:x.plan,static_errors:x.static_errors,static_valid:x.static_valid,validated:x.validated,repaired:x.repaired,execution:x.execution})),replay:replay.map(x=>({case_id:x.case_id,success:x.success,input:x.input,output:x.output,error:x.error,fingerprint:x.fingerprint}))};
await mkdir("results/experiment-3n",{recursive:true});await writeFile("results/experiment-3n/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3n/evidence.json",JSON.stringify({sources:SOURCES,existing_supply:EXISTING_SUPPLY,results,persisted,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
