import type {Config} from "./config/index.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {sha4u,resolveLocalRef4U,type RefMetrics4U} from "./experiment4uOpenApi.js";

const CONFIDENCE_THRESHOLD_4W=0.82;
function emptyRefMetrics():RefMetrics4U{return {operationLocalRefsResolved4u:0,operationLocalRefsRejected4u:0,operationExternalRefsRejected4u:0,operationExternalRefFetches4u:0,operationRefCyclesRejected4u:0,unrelatedRefFailuresIsolated4u:0}}
function successfulSchema(root:any,op:any){const entries=Object.entries(op?.responses||{}).filter(([k])=>/^2\d\d$/.test(k)).sort(([a],[b])=>a.localeCompare(b));for(const [,respRaw] of entries){let resp:any=respRaw;try{resp=resolveLocalRef4U(root,resp,emptyRefMetrics())}catch{continue}const content=resp?.content||{};for(const ct of Object.keys(content).sort()){let schema=content[ct]?.schema;if(!schema)continue;try{schema=resolveLocalRef4U(root,schema,emptyRefMetrics())}catch{continue}return {schema,responseDescription:String(resp?.description||""),contentType:ct}}}return null}
function flatten(root:any,node:any,path:string[],enclosing:string,responseDescription:string,out:any[],depth=0){if(depth>8||!node||typeof node!=="object")return;try{node=resolveLocalRef4U(root,node,emptyRefMetrics())}catch{return}if(node.type==="array"&&node.items){flatten(root,node.items,path,enclosing,responseDescription,out,depth+1);return}const props=node.properties&&typeof node.properties==="object"&&!Array.isArray(node.properties)?node.properties:null;if(!props)return;for(const [name,raw] of Object.entries(props)){let p:any=raw;try{p=resolveLocalRef4U(root,p,emptyRefMetrics())}catch{continue}const pth=[...path,name];out.push({schema_path:pth.join("."),property_name:name,property_title:String(p?.title||""),property_description:String(p?.description||""),documented_examples:[p?.example,...(Array.isArray(p?.examples)?p.examples:[])].filter(v=>v!==undefined).slice(0,3).map(String),enclosing_schema_name:String(node?.title||enclosing||""),response_description:responseDescription});if(p?.properties||p?.items)flatten(root,p,pth,String(p?.title||name),responseDescription,out,depth+1)}}
export function schemaFieldCandidates4W(root:any,op:any,proof:P1ProbeProof){const s=successfulSchema(root,op);if(!s)return [];const desc:any[]=[];flatten(root,s.schema,[],String(s.schema?.title||""),s.responseDescription,desc);const out:any[]=[];for(const d of desc){const fields=proof.record.observed_fields.filter(f=>f.leaf===d.property_name||f.path.endsWith(`.${d.property_name}`)||f.path===d.property_name);for(const f of fields.slice(0,4)){const candidate_id=`field_${sha4u({schema:d.schema_path,observed:f.path}).slice(0,14)}`;out.push({candidate_id,schema_path:d.schema_path,observed_path:f.path,property_name:d.property_name,property_title:d.property_title,property_description:d.property_description,documented_examples:d.documented_examples,enclosing_schema_name:d.enclosing_schema_name,response_description:d.response_description,observed_type:f.sample_type})}}const dedup=new Map<string,any>();for(const c of out)if(!dedup.has(c.candidate_id))dedup.set(c.candidate_id,c);return [...dedup.values()].sort((a,b)=>a.candidate_id.localeCompare(b.candidate_id)).slice(0,60)}

export function buildSchemaResolverPayload4W(intent:string,unresolved:readonly string[],candidates:any[]){return {task_intent:intent,required_output_roles:[...unresolved],closed_field_candidates:candidates.map(c=>({candidate_id:c.candidate_id,schema_path:c.schema_path,observed_path:c.observed_path,property_name:c.property_name,property_title:c.property_title,property_description:c.property_description,documented_examples:c.documented_examples,enclosing_schema_name:c.enclosing_schema_name,response_description:c.response_description,observed_type:c.observed_type}))}}

export function validateSchemaResolverOutput4W(raw:any,unresolved:readonly string[],candidates:any[]){const metrics={schemaRoleResolverAccepted4w:0,schemaRoleResolverNoValidSource4w:0,schemaRoleResolverRejectedInventedPath4w:0,schemaRoleResolverRejectedAmbiguous4w:0,schemaRoleResolverValueGenerationRejects4w:0};if(!raw||!Array.isArray(raw.mappings))return {mappings:[],metrics};const byId=new Map(candidates.map(c=>[c.candidate_id,c])),allowedRoles=new Set(unresolved),used=new Set<string>(),mappedRoles=new Set<string>(),mappings:any[]=[];for(const row of raw.mappings){if(!row||typeof row!=="object")continue;if("value" in row||"literal" in row||"output_value" in row){metrics.schemaRoleResolverValueGenerationRejects4w++;continue}const role=String(row.output_role||""),candidateId=String(row.candidate_id||"");if(!allowedRoles.has(role)||mappedRoles.has(role))continue;if(candidateId==="NO_VALID_SOURCE"){metrics.schemaRoleResolverNoValidSource4w++;mappedRoles.add(role);continue}const c=byId.get(candidateId);if(!c){metrics.schemaRoleResolverRejectedInventedPath4w++;continue}const confidence=Number(row.confidence);if(!Number.isFinite(confidence)||confidence<CONFIDENCE_THRESHOLD_4W)continue;if(used.has(candidateId)){metrics.schemaRoleResolverRejectedAmbiguous4w++;continue}used.add(candidateId);mappedRoles.add(role);mappings.push({output_role:role,candidate_id:candidateId,schema_path:c.schema_path,observed_path:c.observed_path,confidence,evidence_fields:[c.property_name,c.property_title,c.property_description,c.enclosing_schema_name,c.response_description].filter(Boolean)})}metrics.schemaRoleResolverAccepted4w=mappings.length;return {mappings,metrics}}

function combineUsage(base:any,extra:any){if(!base&&!extra)return null;const p=(x:any,k:string)=>Number(x?.[k]||0);return {prompt_tokens:p(base,"prompt_tokens")+p(extra,"prompt_tokens"),completion_tokens:p(base,"completion_tokens")+p(extra,"completion_tokens"),total_tokens:p(base,"total_tokens")+p(extra,"total_tokens"),prompt_tokens_details:{cached_tokens:p(base?.prompt_tokens_details,"cached_tokens")+p(extra?.prompt_tokens_details,"cached_tokens")}}}
export async function resolveSchemaRoles4W(config:Config,args:{intent:string;root:any;op:any;proof:P1ProbeProof;unresolved:readonly string[];specFingerprint:string;operationPointer:string}){const candidates=schemaFieldCandidates4W(args.root,args.op,args.proof),baseMetrics={schemaRoleResolverCalls4w:0,schemaRoleResolverClosedFieldCandidates4w:candidates.length,schemaRoleResolverAccepted4w:0,schemaRoleResolverNoValidSource4w:0,schemaRoleResolverRejectedInventedPath4w:0,schemaRoleResolverRejectedAmbiguous4w:0,schemaRoleResolverValueGenerationRejects4w:0};if(!candidates.length||!args.unresolved.length)return {witness:null,metrics:{...baseMetrics,schemaRoleResolverNoValidSource4w:args.unresolved.length},usage:null};const payload=buildSchemaResolverPayload4W(args.intent,args.unresolved,candidates);let body:any=null,parsed:any=null;try{const response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,seed:config.seed,response_format:{type:"json_object"},messages:[{role:"system",content:"You are a closed-world schema-role classifier. Map each requested output role only to one candidate_id from the supplied closed_field_candidates, or NO_VALID_SOURCE. Never output a value, literal, provider, URL, new path, or explanation. Return strict JSON: {\"mappings\":[{\"output_role\":string,\"candidate_id\":string,\"confidence\":number}]}."},{role:"user",content:JSON.stringify(payload)}]})});if(!response.ok)return {witness:null,metrics:{...baseMetrics,schemaRoleResolverCalls4w:1,schemaRoleResolverNoValidSource4w:args.unresolved.length},usage:null};body=await response.json();parsed=JSON.parse(String(body?.choices?.[0]?.message?.content||"{}"))}catch{return {witness:null,metrics:{...baseMetrics,schemaRoleResolverCalls4w:1,schemaRoleResolverNoValidSource4w:args.unresolved.length},usage:body?.usage||null}}const checked=validateSchemaResolverOutput4W(parsed,args.unresolved,candidates),mappings=checked.mappings;if(!mappings.length)return {witness:null,metrics:{...baseMetrics,schemaRoleResolverCalls4w:1,...checked.metrics},usage:body?.usage||null};const witness={spec_fingerprint:args.specFingerprint,operation_pointer:args.operationPointer,response_schema_fingerprint:sha4u(args.op?.responses||{}),mappings,semantic_evidence_fingerprint:sha4u(candidates),resolver_output_fingerprint:sha4u(mappings)};return {witness,metrics:{...baseMetrics,schemaRoleResolverCalls4w:1,...checked.metrics},usage:body?.usage||null}}

export function verifySchemaRoleWitness4W(w:any,proof:P1ProbeProof){if(!w||!Array.isArray(w.mappings)||w.resolver_output_fingerprint!==sha4u(w.mappings))return false;const paths=new Set(proof.record.observed_fields.map(f=>f.path)),used=new Set<string>();for(const m of w.mappings){if(!m||typeof m.output_role!=="string"||typeof m.schema_path!=="string"||typeof m.observed_path!=="string"||typeof m.candidate_id!=="string"||"value" in m||!paths.has(m.observed_path)||used.has(m.candidate_id))return false;used.add(m.candidate_id)}return true}
export function applySchemaRoleWitness4W(projection:any,w:any){const out={...projection};for(const m of w?.mappings||[])if(!out[m.output_role])out[m.output_role]={op:"FIELD",path:m.observed_path};return out}
export const schemaRoleConfidenceThreshold4W=CONFIDENCE_THRESHOLD_4W;
export const combineUsage4W=combineUsage;
