import type {CaseDef} from "./experiment3qCore.js";
import type {ProviderCandidate} from "./experiment3vCore.js";
import {sha3yr} from "./experiment3yrCore.js";

const JSON_SCHEMA:any={name:"missing_5b17_capability_equivalence",strict:true,schema:{type:"object",additionalProperties:false,required:["case_id","selected"],properties:{case_id:{type:"string"},selected:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,required:["candidate_id","reason","input_roles_supported","output_roles_supported"],properties:{candidate_id:{type:"string"},reason:{type:"string"},input_roles_supported:{type:"array",items:{type:"string"}},output_roles_supported:{type:"array",items:{type:"string"}}}}}}}};
export type FiveB17EquivalenceChoice={candidate_id:string;reason:string;input_roles_supported:string[];output_roles_supported:string[]};
export type FiveB17EquivalenceSelection={case_id:string;selected:FiveB17EquivalenceChoice[]};

function sameSet(a:any,b:readonly string[]){if(!Array.isArray(a)||a.some(x=>typeof x!=="string"))return false;const aa=[...new Set(a.map(String))].sort(),bb=[...new Set(b.map(String))].sort();return JSON.stringify(aa)===JSON.stringify(bb)}
export function plannerVisibleCandidates5b17(xs:ProviderCandidate[]){return xs.map((x:any)=>({candidate_id:x.candidate_id,name:x.name,description:x.description,category:x.category,auth:x.auth,https:x.https,cors:x.cors??null}))}
export function validateCapabilityEquivalence5b17(x:any,broad:ProviderCandidate[],c:CaseDef){const issues:string[]=[];if(!x||typeof x!=="object"||Array.isArray(x))return {selection:null,error:"equivalence_not_object"};for(const k of Object.keys(x))if(!["case_id","selected"].includes(k))issues.push(`extra:${k}`);if(x.case_id!==c.case_id)issues.push(`case_id_mismatch:${String(x.case_id)}`);if(!Array.isArray(x.selected))issues.push("selected_type");const allowed=new Set(broad.map(p=>p.candidate_id)),seen=new Set<string>();if(Array.isArray(x.selected)){if(x.selected.length>12)issues.push("too_many_selected");for(let i=0;i<x.selected.length;i++){const row=x.selected[i];if(!row||typeof row!=="object"||Array.isArray(row)){issues.push(`selected_${i}_type`);continue;}for(const k of Object.keys(row))if(!["candidate_id","reason","input_roles_supported","output_roles_supported"].includes(k))issues.push(`selected_${i}_extra:${k}`);if(typeof row.candidate_id!=="string")issues.push(`selected_${i}_candidate_id_type`);else{if(!allowed.has(row.candidate_id))issues.push(`unknown_candidate_id:${row.candidate_id}`);if(seen.has(row.candidate_id))issues.push(`duplicate_candidate_id:${row.candidate_id}`);seen.add(row.candidate_id);}if(typeof row.reason!=="string"||!row.reason.trim())issues.push(`selected_${i}_reason_type`);if(!sameSet(row.input_roles_supported,c.input_names))issues.push(`selected_${i}_input_role_coverage`);if(!sameSet(row.output_roles_supported,c.required_output_leaf_names))issues.push(`selected_${i}_output_role_coverage`);}}
 return issues.length?{selection:null,error:`equivalence_contract_invalid:${issues.join(",")}`}:{selection:{case_id:x.case_id,selected:x.selected} as FiveB17EquivalenceSelection,error:null};}
export function selectionFingerprint5b17(selection:FiveB17EquivalenceSelection){return sha3yr({case_id:selection.case_id,selected:selection.selected.map(x=>({candidate_id:x.candidate_id,input_roles_supported:[...x.input_roles_supported].sort(),output_roles_supported:[...x.output_roles_supported].sort()}))})}
export function resolveSelected5b17(selection:FiveB17EquivalenceSelection,broad:ProviderCandidate[]){const byId=new Map(broad.map(x=>[x.candidate_id,x]));return selection.selected.map((claim,i)=>({candidate:byId.get(claim.candidate_id)!,claim,selected_position:i+1})).filter(x=>!!x.candidate)}

export async function callCapabilityEquivalenceReranker5b17(config:any,c:CaseDef,broad:ProviderCandidate[],phase:"initial"|"repair",previous?:string){
 const system=["You are the MISSING capability-equivalence retriever.","Your job is not to find providers that are merely related by topic; select only candidates that are plausible functional substitutes for the requested capability.","A substitute must plausibly accept every named input role and provide every required output role as part of the same usable operation or service.","Reject adjacent datasets, unrelated APIs in the same category, reverse-direction services, generic search services without the required output contract, and candidates whose catalog description does not justify full functional substitutability.","Use only the supplied catalog metadata. This is retrieval, not proof; downstream live compilation will verify your choices.","You may select only opaque candidate_id values from the supplied list.","For each selected candidate, copy every supplied input role into input_roles_supported and every supplied required output role into output_roles_supported only when the metadata makes full coverage plausible.","Do not emit or infer URLs, hosts, endpoints, operation paths, credentials, provider identities outside the list, build values, replay values, or expected answers.","Return the exact supplied case_id and the strict response object."].join(" ");
 const payload={capability:{case_id:c.case_id,intent:c.intent,input_roles:c.input_names,required_output_roles:c.required_output_leaf_names},candidate_providers:plannerVisibleCandidates5b17(broad),previous_response_contract_failure:previous??null};
 const t0=Date.now(),r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:JSON_SCHEMA}})}),latency_ms=Date.now()-t0,text=await r.text();let body:any=null;try{body=JSON.parse(text)}catch{}const msg=body?.choices?.[0]?.message,raw=msg?.content??null;let parsed:any=null,parse_error:string|null=null;if(typeof raw==="string"){try{parsed=JSON.parse(raw)}catch(e){parse_error=String(e)}}return {phase,expected_case_id:c.case_id,http_status:r.status,http_ok:r.ok,raw_response:text,raw_content:raw,refusal:msg?.refusal??null,parsed_json:parsed,parse_error,usage:body?.usage??null,latency_ms};
}
export function parseCapabilityEquivalenceAttempt5b17(attempt:any,broad:ProviderCandidate[],c:CaseDef){if(!attempt.http_ok)return {selection:null,error:`planner_http_${attempt.http_status}`};if(attempt.refusal)return {selection:null,error:"planner_refusal"};if(!attempt.parsed_json)return {selection:null,error:"planner_json_parse_failure"};return validateCapabilityEquivalence5b17(attempt.parsed_json,broad,c)}
