import {deriveExperiment5b9PlannerSource} from "./experiment5b9PlannerDerivation.js";

function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b10_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}

export function deriveExperiment5b10PlannerSource(source:string){let x=deriveExperiment5b9PlannerSource(source);
 x=r(x,'export async function synthesize5b9(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){','export async function synthesize5b10(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger,_synthesisEvidence5b10:any[]=[],recoveryLineages5b10:any[]=[]){');
 x=r(x,'const c=BY_ID[provider.case_id];if(!c)throw new Error(`5b6_unknown_case:${provider.case_id}`);const metrics:any=defaults(),usageHolder:{usage:any}={usage:null};','const c=BY_ID[provider.case_id];if(!c)throw new Error(`5b10_unknown_case:${provider.case_id}`);const metrics:any=defaults(),usageHolder:{usage:any}={usage:null};metrics.synthesisGraphRefreshes5b10=recoveryLineages5b10.length?1:0;metrics.synthesisGraphRefreshSkippedNoRecovery5b10=recoveryLineages5b10.length?0:1;metrics.plannerVisibleCandidatesBeforeRecovery5b10=0;metrics.plannerVisibleCandidatesAfterRecovery5b10=0;metrics.recoveryDerivedPlannerVisibleCandidates5b10=0;metrics.recoveryDerivedEligibleCandidates5b10=0;metrics.recoveryDerivedBeamEntries5b10=0;metrics.recoveryDerivedBeamPosition1_5b10=0;metrics.recoveryDerivedBeamPosition2_5b10=0;metrics.recoveryRankingBonusUses5b10=0;metrics.globalBeamSizeMax5b10=0;metrics.recoveryExecutedCandidates5b10=0;metrics.recoveryStrictRecipes5b10=0;metrics.recoveryPlannerConsistencyAuditRows5b10=recoveryLineages5b10.length?1:0;metrics.recoveryOperationWithoutPlannerCandidate5b10=0;metrics.recoveryCandidateSemanticRejects5b10=0;metrics.recoveryEligibleRankedOutsideBeam5b10=0;metrics.recoveryBeamNotExecuted5b10=0;metrics.recoveryExecutedNotCompiled5b10=0;metrics.recoveryCompiledStrictRejects5b10=0;metrics.recoveryPlannerConsistencyAuditComplete5b10=recoveryLineages5b10.length?1:0;');
 x=r(x,'const nativeProofById=new Map((native.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),collectionProofById=new Map((collection.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),queryProofById=new Map((query.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),sectionById=new Map(sectioned.sections.map(s=>[s.section_id,s]));','const nativeProofById=new Map((native.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),collectionProofById=new Map((collection.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),queryProofById=new Map((query.proofs||[]).map((p:any)=>[p.hypothesis_id,p])),sectionById=new Map(sectioned.sections.map(s=>[s.section_id,s]));const recoveredEvidenceIds5b10=new Set(recoveryLineages5b10.map((z:any)=>String(z?.resulting_evidence_id||"" )).filter(Boolean)),recoveredBodyFps5b10=new Set(recoveryLineages5b10.map((z:any)=>String(z?.resulting_body_fingerprint||"" )).filter(Boolean));const recoveryDerivedIds5b10=new Set<string>();for(const h of localized.hypotheses){const p:any=nativeProofById.get(h.id)||collectionProofById.get(h.id)||queryProofById.get(h.id);const sid=String(p?.source_evidence_id||p?.evidence_id||""),sfp=String(p?.source_body_fingerprint||p?.body_fingerprint||"");if((sid&&recoveredEvidenceIds5b10.has(sid))||(sfp&&recoveredBodyFps5b10.has(sfp)))recoveryDerivedIds5b10.add(h.id)}metrics.plannerVisibleCandidatesAfterRecovery5b10=localized.hypotheses.length;metrics.recoveryDerivedPlannerVisibleCandidates5b10=recoveryDerivedIds5b10.size;metrics.recoveryDerivedEligibleCandidates5b10=recoveryDerivedIds5b10.size;if(recoveryLineages5b10.length&&recoveryDerivedIds5b10.size===0)metrics.recoveryOperationWithoutPlannerCandidate5b10=1;');
 x=r(x,'const beam=dedup.slice(0,2);for(const h of beam){if(collectionProofById.has(h.id)&&alignment.witnesses.has(h.id))metrics.alignedStructuredCollectionBeamEntries5b5++;if(queryProofById.has(h.id))metrics.queryBeamEntries5b6++}','const beam=dedup.slice(0,2);metrics.globalBeamSizeMax5b10=Math.max(metrics.globalBeamSizeMax5b10,beam.length);for(let bi=0;bi<beam.length;bi++){const h=beam[bi];if(collectionProofById.has(h.id)&&alignment.witnesses.has(h.id))metrics.alignedStructuredCollectionBeamEntries5b5++;if(queryProofById.has(h.id))metrics.queryBeamEntries5b6++;if(recoveryDerivedIds5b10.has(h.id)){metrics.recoveryDerivedBeamEntries5b10++;if(bi===0)metrics.recoveryDerivedBeamPosition1_5b10++;if(bi===1)metrics.recoveryDerivedBeamPosition2_5b10++;}}metrics.recoveryEligibleRankedOutsideBeam5b10=Math.max(0,recoveryDerivedIds5b10.size-metrics.recoveryDerivedBeamEntries5b10);');
 x=r(x,'for(let i=0;i<beam.length;i++){const h=beam[i],isNative=nativeProofById.has(h.id),isCollection=collectionProofById.has(h.id),isQuery=queryProofById.has(h.id),alignmentWitness=alignment.witnesses.get(h.id)||null;','for(let i=0;i<beam.length;i++){const h=beam[i],isNative=nativeProofById.has(h.id),isCollection=collectionProofById.has(h.id),isQuery=queryProofById.has(h.id),alignmentWitness=alignment.witnesses.get(h.id)||null,isRecovery5b10=recoveryDerivedIds5b10.has(h.id);if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;');
 x=r(x,'materialized.raw.query_operation_witness_5b6=isQuery?{...queryProofById.get(h.id),final_request_ordering_fingerprint:finalFingerprint}:null;','materialized.raw.query_operation_witness_5b6=isQuery?{...queryProofById.get(h.id),final_request_ordering_fingerprint:finalFingerprint}:null;materialized.raw.recovery_candidate_witness_5b10=isRecovery5b10?{candidate_id:h.id,request_fingerprint:shape(h),beam_position:i+1,recovery_lineage_fingerprints:recoveryLineages5b10.map((z:any)=>z?.lineage_fingerprint).filter(Boolean),source_evidence_ids:[...recoveredEvidenceIds5b10],ranking_bonus:false}:null;if(isRecovery5b10)metrics.recoveryStrictRecipes5b10++;');
 x=x.replaceAll('5B8_BEAM_EXHAUSTED','5B10_BEAM_EXHAUSTED');
 return x;
}
