import {deriveExperiment4oSource} from "./experiment4oDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4p_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4pSource(source:string){
 let x=deriveExperiment4oSource(source);
 x=r(x,'import {compile4o as compile4ar,project4o as project4ar,scope4o as scope4ar,validate4o as validate4ar,validateProjected4o as validateProjected4ar} from "./experiment4oContract.js";','import {compile4p as compile4ar,project4p as project4ar,scope4p as scope4ar,validate4p as validate4ar,validateProjected4p as validateProjected4ar} from "./experiment4pContract.js";');
 x=r(x,'import {synthesize4o as synthesize4ar} from "./experiment4oPlanner.js";','import {synthesize4p as synthesize4ar} from "./experiment4pPlanner.js";\nimport {boundedOrderedMap4P} from "./experiment4pSchedule.js";');
 x=r(x,'const OUT="results/experiment-4o",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4p",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
 x=r(x,'const llmUsage:any[]=[];','const llmUsage:any[]=[];let rerankPreparedCases4p=0,rerankCompletedCases4p=0,rerankMaxObservedConcurrency4p=0,rerankWallPhaseMs4p=0,rerankAggregateCaseLatencyMs4p=0;const rerankConcurrencyLimit4p=3;');
 const old='let mechanicalFrontier=true;\nfor(const c of FOUR_A_CASES){const caseStart=Date.now(),broad=recoveredBroadRetrieveR2(c as any,catalog);mechanicalFrontier=mechanicalFrontier&&broad.length<=RECOVERY_R2_TOP_K&&broad.every((x:any,i:number)=>x.lexical_rank===i+1);const r=await rerank(config,c,broad,rerankEvidence);';
 const neu='let mechanicalFrontier=true;const rerankPhaseStart4p=Date.now(),preparedReranks4p=await boundedOrderedMap4P(FOUR_A_CASES,rerankConcurrencyLimit4p,async(c)=>{rerankPreparedCases4p++;const t=Date.now(),broad=recoveredBroadRetrieveR2(c as any,catalog);mechanicalFrontier=mechanicalFrontier&&broad.length<=RECOVERY_R2_TOP_K&&broad.every((x:any,i:number)=>x.lexical_rank===i+1);const r=await rerank(config,c,broad,rerankEvidence),rerank_elapsed_ms=Date.now()-t;rerankCompletedCases4p++;rerankAggregateCaseLatencyMs4p+=rerank_elapsed_ms;return {c,broad,r,rerank_elapsed_ms};});rerankWallPhaseMs4p=Date.now()-rerankPhaseStart4p;rerankMaxObservedConcurrency4p=preparedReranks4p.maxObservedConcurrency;\nfor(const prepared of preparedReranks4p.results){const {c,broad,r}=prepared,caseStart=Date.now();';
 x=r(x,old,neu);
 x=x.replaceAll('elapsed_ms:Date.now()-caseStart','elapsed_ms:prepared.rerank_elapsed_ms+(Date.now()-caseStart)');
 x=r(x,'forbidden_input_source_selections_zero:forbiddenInputSourceSelections4o===0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,','forbidden_input_source_selections_zero:forbiddenInputSourceSelections4o===0,rerank_all_cases_prepared:rerankPreparedCases4p===FOUR_A_CASES.length,rerank_all_cases_completed:rerankCompletedCases4p===FOUR_A_CASES.length,rerank_concurrency_bounded:rerankMaxObservedConcurrency4p<=rerankConcurrencyLimit4p&&rerankMaxObservedConcurrency4p>0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,');
 x=r(x,'forbiddenInputSourceSelections:forbiddenInputSourceSelections4o,probeCacheHits:probeCacheHits4l','forbiddenInputSourceSelections:forbiddenInputSourceSelections4o,rerankPreparedCases:rerankPreparedCases4p,rerankCompletedCases:rerankCompletedCases4p,rerankConcurrencyLimit:rerankConcurrencyLimit4p,rerankMaxObservedConcurrency:rerankMaxObservedConcurrency4p,rerankWallPhaseMs:rerankWallPhaseMs4p,rerankAggregateCaseLatencyMs:rerankAggregateCaseLatencyMs4p,rerankOverlapSavingsMs:Math.max(0,rerankAggregateCaseLatencyMs4p-rerankWallPhaseMs4p),probeCacheHits:probeCacheHits4l');
 x=x.replaceAll('4O_RELATIONAL_RESPONSE:','4P_PROJECTION_COMPATIBILITY:').replaceAll('4O_MAPPING_REJECT','4P_MAPPING_REJECT').replaceAll('GO_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION','GO_4P_PROJECTION_COMPATIBILITY_ENVELOPE').replaceAll('REASSESS_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION','REASSESS_4P_PROJECTION_COMPATIBILITY_ENVELOPE');
 x=r(x,'experiment:"4O",purpose:"development_relational_response_ir_keyed_row_projection"','experiment:"4P",purpose:"development_projection_compatibility_envelope"');
 x=r(x,'base_sha:"07997e9e791f159b118349ef55e5a45a1c92fa5e"','base_sha:"3a1fffc82d3854302b34e9bcfc1a4e1f44ac0744"');
 x=x.replaceAll('./experiment4oPlanner.ts','./experiment4pPlanner.ts').replaceAll('./experiment4oContract.ts','./experiment4pContract.ts').replaceAll('./experiment4oDerivation.ts','./experiment4pDerivation.ts');
 x=x.replace('plannerSource=(await readFile(new URL("./experiment4pPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oRelational.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))','plannerSource=(await readFile(new URL("./experiment4pPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4pCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oRelational.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4pSchedule.ts",import.meta.url),"utf8"))');
 return x;
}
