import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {expandReferenceEvidence4E} from "./experiment4eRequest.js";
import {compileDocumentationIr4F,type DocumentationIr,type IrOperation,type IrParameter} from "./experiment4fIr.js";

const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
function toks(v:string){return lexicalTokensP1(v)}
function overlap(a:string,b:string){const x=new Set(toks(a)),y=new Set(toks(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function canon(v:string){return v.replace(/[^a-z0-9]+/gi,"").toLowerCase()}
function norm(v:any){return String(v??"").trim().toLowerCase()}
function byId<T extends {id:string}>(xs:T[]){return new Map(xs.map(x=>[x.id,x]))}
function operationText(ir:DocumentationIr,op:IrOperation){const section=ir.sections.find(s=>s.id===op.section_id);return `${op.title} ${section?.title||""} ${op.context}`}
function explicitAuthRisk(ir:DocumentationIr,op:IrOperation,params:IrParameter[]){if(op.auth_ids.some(id=>{const a=ir.auth.find(x=>x.id===id);return a&&!a.optional}))return true;return params.some(p=>p.auth_like&&(p.example!==null||p.required!==false))}
function taskCorresponds(caseId:string,ir:DocumentationIr,op:IrOperation,params:IrParameter[]){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;const text=operationText(ir,op),bindings:Record<string,string>={},used=new Set<string>();for(const input of c.input_names){const build=String(c.build[input]??"");const scored=params.filter(p=>!p.auth_like&&!used.has(p.id)).map(p=>{const idEq=canon(input)===canon(p.name)?320:0,lex=overlap(input,`${p.name} ${p.description}`)*180,value=p.example!==null&&norm(p.example)===norm(build)?300:0,context=overlap(c.intent||"",text)>0?50:0;return {p,score:idEq+lex+value+context}}).filter(x=>x.score>=180).sort((a,b)=>b.score-a.score);let best=scored[0];if(!best&&build){const segs=op.path.split("/"),hits:number[]=[];for(let i=0;i<segs.length;i++){let v=segs[i];try{v=decodeURIComponent(v)}catch{}if(norm(v)===norm(build))hits.push(i)}if(hits.length===1&&overlap(c.intent||"",text)>0){const p:IrParameter={id:`par4f_${fourAp1Sha({o:op.id,input,concrete:1}).slice(0,16)}`,name:input,in:"path",required:true,auth_like:false,example:build,description:"documented concrete example",section_id:op.section_id,source:op.source};params.push(p);best={p,score:350}}}if(!best)return null;bindings[input]=best.p.id;used.add(best.p.id)}return bindings}
function makeHypothesis(caseId:string,ir:DocumentationIr,op:IrOperation){const base=ir.api_bases.find(b=>b.id===op.api_base_id);if(!base)return {h:null,authReject:false,correspondenceReject:false};const params=op.parameter_ids.map(id=>ir.parameters.find(p=>p.id===id)).filter(Boolean) as IrParameter[];if(explicitAuthRisk(ir,op,params))return {h:null,authReject:true,correspondenceReject:false};const mutable=[...params],bindings=taskCorresponds(caseId,ir,op,mutable);if(!bindings)return {h:null,authReject:false,correspondenceReject:true};let path=op.path;for(const [input,pid] of Object.entries(bindings)){const p=mutable.find(x=>x.id===pid);if(p?.description==="documented concrete example"&&p.example){const encoded=encodeURIComponent(p.example);path=path.replace(p.example,`{${input}}`).replace(encoded,`{${input}}`)}}
const slots:P1RequestSlot[]=mutable.map(p=>({id:p.id,name:p.name,in:p.in==="path"?"path":"query",required:p.required===true,auth_like:p.auth_like||AUTH_NAME.test(p.name),literals:p.example!==null?[{id:`lit4f_${fourAp1Sha({p:p.id,v:p.example}).slice(0,16)}`,value:p.example}]:[]}));const p1Bindings:Record<string,string>={};for(const [input,pid] of Object.entries(bindings))p1Bindings[input]=pid;const literal_bindings:Record<string,string>={};for(const s of slots){if(Object.values(p1Bindings).includes(s.id)||s.auth_like)continue;if(s.literals.length===1&&/json/i.test(s.literals[0].value)&&/(?:format|response|output|type)/i.test(s.name))literal_bindings[s.id]=s.literals[0].id}
const h:P1RequestHypothesis={id:`req4f_${fourAp1Sha({op:op.id,base:base.id,path,bindings:p1Bindings,literal_bindings}).slice(0,16)}`,source_operation_id:op.id,origin:base.origin,full_path:path,proof_type:`4f_documentation_ir_${op.api_base_relation||"absolute"}`,evidence_ids:[op.source.evidence_id,base.source.evidence_id],source_urls:[op.source.source_url,base.source.source_url],slots,input_bindings:p1Bindings,literal_bindings,score:800+(op.source.expanded?20:0),concrete_relation:op.absolute_url===null};return {h,authReject:false,correspondenceReject:false}}
function renderedAuthLike(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return true;let rendered="";try{rendered=compileRequestHypothesisP1(h,c.build)}catch{return true}let u:URL;try{u=new URL(rendered)}catch{return true}for(const [name] of u.searchParams)if(AUTH_NAME.test(name))return true;for(const s of h.slots)if(s.auth_like&&(s.in==="path"||u.searchParams.has(s.name)))return true;return false}

export async function prepareRequestGraph4F(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const expansion=await expandReferenceEvidence4E(evidence,ledger,3),ir=compileDocumentationIr4F(evidence),built=ir.operations.map(op=>makeHypothesis(caseId,ir,op));let authRequiredOperationsRejected=built.filter(x=>x.authReject).length,operationCorrespondenceRejected=built.filter(x=>x.correspondenceReject).length;const hypotheses=built.map(x=>x.h).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of hypotheses){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const ordered=[...dedup.values()].sort((a,b)=>b.score-a.score),packet:P1RequestHypothesis[]=[],rendered=new Set<string>();let duplicateRenderedProbeUrlsRejected=0,authLikeRenderedRequests=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of ordered){if(!c)break;if(renderedAuthLike(h,caseId)){authLikeRenderedRequests++;authRequiredOperationsRejected++;continue}let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(rendered.has(url)){duplicateRenderedProbeUrlsRejected++;continue}rendered.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}
const expandedOps=new Set(ir.operations.filter(o=>o.source.expanded).map(o=>o.id)),expandedHypotheses=ordered.filter(h=>expandedOps.has(h.source_operation_id)).length;const metrics={...ir.metrics,...expansion,authRequiredOperationsRejected,authLikeRenderedRequests,knownAuthProbeAttempts:0,operationCorrespondenceCandidates:ir.operations.length-authRequiredOperationsRejected,operationCorrespondenceAccepted:ordered.length,operationCorrespondenceRejected,wrongTaskProbeAttempts:0,noIrOperation:ir.operations.length===0,irOperationUnusable:ir.operations.length>0&&ordered.length===0,requestHypotheses:ordered.length,expandedEvidenceHypotheses:expandedHypotheses,uniqueRenderedProbeUrls:rendered.size,duplicateRenderedProbeUrlsRejected,documentationOriginFallbacks:0,standaloneUrlPromotions:0};return {ir,hypotheses:ordered,probe_packet:packet,metrics,graph_fingerprint:fourAp1Sha({ir:ir.fingerprint,h:ordered.map(x=>x.id)})}}

export function rebuildRequestGraph4F(evidence:DocEvidence[],caseId:string){const ir=compileDocumentationIr4F(evidence),built=ir.operations.map(op=>makeHypothesis(caseId,ir,op)),ordered=built.map(x=>x.h).filter(Boolean) as P1RequestHypothesis[];const dedup=new Map<string,P1RequestHypothesis>();for(const h of ordered){if(renderedAuthLike(h,caseId))continue;const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score);return {ir,hypotheses,graph_fingerprint:fourAp1Sha({ir:ir.fingerprint,h:hypotheses.map(x=>x.id)})}}
