import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {validate4u,compile4u,project4u,validateProjected4u,scope4u} from "./experiment4uContract.js";
import {verifyEntityCouplingWitness5B,verifyResponseRoleWitness5B} from "./experiment5bResponse.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(c=>[c.case_id,c]));
function witnessLedgerProxy5B(ledger:RecoveryLedger,allowed:Set<string>){return {record:(layer:any,kind:string,accepted:boolean,detail?:any)=>{if(kind==="ungrounded_projection_fields"&&accepted===false&&detail&&typeof detail==="object"&&allowed.has(`${String(detail.output||"")}:${String(detail.path||"")}`))return;ledger.record(layer,kind,accepted,detail)}} as RecoveryLedger}
export function validate5b(raw:any,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger,probeProof:P1ProbeProof|null){const c=BY_ID[provider.case_id],baseMetrics={entityCouplingContractValidationSuccesses5b:0,entityCouplingContractMutationRejects5b:0,responseGroundedWitnessValidationSuccesses5b:0,responseGroundedWitnessMutationRejects5b:0};if(raw?.decision!=="COMPILE")return {...validate4u(raw,provider,evidence,ledger,probeProof),...baseMetrics};if(!c||!probeProof)return {...validate4u(raw,provider,evidence,ledger,probeProof),...baseMetrics,errors:["5b_missing_case_or_probe"]};const entity=raw?.entity_coupling_witness_5b;if(!entity||!verifyEntityCouplingWitness5B(entity,{inputNames:c.input_names,input:c.build,projection:raw.projection,proof:probeProof})){ledger.record("guard","ungrounded_projection_fields",false,{reason:"5b_entity_coupling_witness_invalid"});return {errors:["5b_entity_coupling_witness_invalid"],contract:null as any,projection:null as any,probe_proof:null,...baseMetrics,entityCouplingContractMutationRejects5b:1}}const responseWitness=raw?.response_role_witness_5b,allowed=new Set<string>();if(responseWitness){if(!verifyResponseRoleWitness5B(responseWitness,probeProof)){ledger.record("guard","ungrounded_projection_fields",false,{reason:"5b_response_role_witness_invalid"});return {errors:["5b_response_role_witness_invalid"],contract:null as any,projection:null as any,probe_proof:null,...baseMetrics,responseGroundedWitnessMutationRejects5b:1}}for(const m of responseWitness.mappings||[])allowed.add(`${m.output_role}:${m.observed_path}`)}const checked:any=validate4u(raw,provider,evidence,allowed.size?witnessLedgerProxy5B(ledger,allowed):ledger,probeProof);let bypassed=0;const errors=(checked.errors||[]).filter((e:string)=>{const m=/^4u_ungrounded_output:([^:]+):(.+)$/.exec(e),ok=!!(m&&allowed.has(`${m[1]}:${m[2]}`));if(ok)bypassed++;return !ok});return {...checked,errors,projection:errors.length?null:(raw.projection as ProjectionPlan),probe_proof:errors.length?null:probeProof,semanticGroundingValidatorRejects:Math.max(0,Number(checked.semanticGroundingValidatorRejects||0)-bypassed),...baseMetrics,entityCouplingContractValidationSuccesses5b:errors.length?0:1,responseGroundedWitnessValidationSuccesses5b:responseWitness&&!errors.length?1:0}}
export function compile5b(contract:MicroContract,input:Record<string,unknown>){return compile4u(contract,input)}
export function project5b(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return project4u(plan,body,input)}
export function validateProjected5b(caseId:string,input:Record<string,any>,out:Record<string,any>){return validateProjected4u(caseId,input,out)}
export function scope5b(start:string,target:string){return scope4u(start,target)}
