import {mkdir,writeFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {CASES,candidateSummary,casesContainNoMappings,parseContractDocument,type CaseDef,type LiveContract,type RegistryRecord} from "./experiment3qCore.js";
import {fetchTextBounded} from "./experiment3qNetwork.js";
import {EXEC_CASES,compileRequest,executionReadiness,induceProjection,makeRecipe,project,semanticValidate,validateBindingProgram} from "./experiment3rCore.js";
import {callProcurementPlanner,parseProcurementPlan} from "./experiment3rPlanner.js";
import {buildSupplierCandidates,verificationTraceFingerprint} from "./experiment3sCore.js";
import {verifyJsonRequest} from "./experiment3sNetwork.js";
import {MAX_BYTES,MAX_CONTRACT_CANDIDATES,MAX_DEPTH,MAX_HTML_PAGES,PUBLIC_APIS_URL,acquiredEvidence,extractLinks,isValidContract,operationCount,sha as sha3u,standardCandidates,type AcquiredContract,type CrawlLink} from "./experiment3uCore.js";
import {budgetAllows} from "./experiment3uNetwork.js";
import {BROAD_TOP_K,RERANK_TOP_K,broadRetrieve,providerSelectionFingerprint,relevantOperation,resolveSelected,sha,type ProviderCandidate} from "./experiment3vCore.js";
import {callProviderReranker,parseRerankAttempt} from "./experiment3vPlanner.js";
import {runNegativeControls} from "./experiment3vControls.js";

const OUTDIR="results/experiment-3v";
let catalogFetches=0,rerankerCalls=0,rerankerRepairs=0,htmlFetches=0,contractFetches=0,procurementPlannerCalls=0,procurementRepairs=0,projectionInductions=0;
const credentialsSupplied=0,crossDomainAccepted=0,privateIpAccepted=0,httpDowngradeAccepted=0,arbitraryCodeExecuted=0,unknownIdsAccepted=0,duplicateIdsAccepted=0,outOfSetIdsAccepted=0;

async function fetchCatalog(){catalogFetches++;const {text}=await fetchTextBounded(PUBLIC_APIS_URL,16*1024*1024,"text/markdown,text/plain");return text;}
function parseJsonContract(text:string){try{const spec=JSON.parse(text);return isValidContract(spec)?spec:null;}catch{return null;}}

async function crawlProvider(p:ProviderCandidate){const acquired:AcquiredContract[]=[],trace:any[]=[],start=p.link;if(!/^yes$/i.test(p.https)||!start.startsWith("https://"))return {provider:p,acquired,trace:[{state:"ineligible_https"}]};const pages:CrawlLink[]=[{url:start,kind:"page",mechanism:"catalog_start",depth:0,evidence:"catalog"}],contracts:CrawlLink[]=[...standardCandidates(start)],seenPages=new Set<string>(),seenContracts=new Set<string>();let pageUsed=0,contractUsed=0;while(pages.length||contracts.length){while(contracts.length&&budgetAllows("contract",contractUsed)){const c=contracts.shift()!;if(seenContracts.has(c.url))continue;seenContracts.add(c.url);contractUsed++;contractFetches++;try{const {text,content_type}=await fetchTextBounded(c.url,MAX_BYTES,"application/json, text/plain, */*");const spec=parseJsonContract(text);if(!spec){trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"not_openapi",content_type});continue;}const contract_fingerprint=sha3u(text),operation_count=operationCount(spec),item:AcquiredContract={catalog_name:p.name,start_url:start,contract_url:c.url,mechanism:c.mechanism,depth:c.depth,contract_fingerprint,operation_count,acquisition_trace_fingerprint:sha3u({start,url:c.url,mechanism:c.mechanism,depth:c.depth,contract_fingerprint}),spec};if(acquiredEvidence(item))acquired.push(item);trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"acquired",operation_count});}catch(e){trace.push({kind:"contract",url:c.url,mechanism:c.mechanism,state:"fetch_error",error:String(e)});}}if(!pages.length||!budgetAllows("html",pageUsed))break;const page=pages.shift()!;if(page.depth>MAX_DEPTH||seenPages.has(page.url))continue;seenPages.add(page.url);pageUsed++;htmlFetches++;try{const {text}=await fetchTextBounded(page.url,MAX_BYTES,"text/html, text/plain, */*");for(const l of extractLinks(start,page.url,text,page.depth+1)){if(l.kind==="contract"){if(!seenContracts.has(l.url)&&contracts.length+contractUsed<MAX_CONTRACT_CANDIDATES*2)contracts.push(l);}else if(l.depth<=MAX_DEPTH&&!seenPages.has(l.url)&&pages.length+pageUsed<MAX_HTML_PAGES*2)pages.push(l);}}catch(e){trace.push({kind:"page",url:page.url,state:"fetch_error",error:String(e)});}if(!budgetAllows("html",pageUsed)&&!budgetAllows("contract",contractUsed))break;}return {provider:p,acquired,trace};}
async function crawlSelected(xs:ProviderCandidate[]){const out:any[]=new Array(xs.length);let next=0;const workers=Array.from({length:4},async()=>{while(true){const i=next++;if(i>=xs.length)return;out[i]=await crawlProvider(xs[i]);}});await Promise.all(workers);return out;}
function toLiveContract(p:ProviderCandidate,a:AcquiredContract):LiveContract{const record:RegistryRecord={api_key:`public_apis::${p.name}@${new URL(p.link).hostname}`,version:"live",spec_url:a.contract_url,title:p.name,description:p.description,categories:[p.category],registry_score:p.score,registry_rank:p.lexical_rank};return parseContractDocument(record,JSON.stringify(a.spec));}

async function rerank(config:any,c:CaseDef,broad:ProviderCandidate[],evidence:any[]){rerankerCalls++;let a=await callProviderReranker(config,c,broad,"initial"),parsed=parseRerankAttempt(a,broad);evidence.push({case_id:c.case_id,...a,error:parsed.error});if(parsed.error){rerankerCalls++;rerankerRepairs++;const repair=await callProviderReranker(config,c,broad,"repair",parsed.error);parsed=parseRerankAttempt(repair,broad);evidence.push({case_id:c.case_id,...repair,error:parsed.error});}return parsed;}
async function procure(config:any,c:CaseDef,execCase:any,supplier:any,evidence:any[]):Promise<any>{const readiness=executionReadiness(supplier.contract,supplier.candidate);if(!readiness.ready)return {ok:false,status:"not_publicly_executable",readiness};procurementPlannerCalls++;let a=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"initial"),parsed=parseProcurementPlan(a),plan=parsed.plan,stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,...a,static_errors:stat.errors});if(parsed.error||stat.errors.length){procurementPlannerCalls++;procurementRepairs++;const repair=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"repair",(parsed.error?[parsed.error]:stat.errors).join(","));parsed=parseProcurementPlan(repair);plan=parsed.plan;stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};evidence.push({case_id:c.case_id,api_key:supplier.candidate.api_key,...repair,static_errors:stat.errors});}if(!plan||plan.decision!=="COMPILE"||stat.errors.length)return {ok:false,status:"binding_reject",readiness,plan};return {ok:true,readiness,bindings:stat.bindings,plan};}

async function main(){await mkdir(OUTDIR,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");const started_at=new Date().toISOString(),controls=await runNegativeControls(),catalog=await fetchCatalog(),rerankEvidence:any[]=[],procurementEvidence:any[]=[],caseEvidence:any[]=[],recipes:any[]=[];
  for(const c of CASES){const broad=broadRetrieve(c,catalog),baseline20=broad.slice(0,20),r=await rerank(config,c,broad,rerankEvidence);if(!r.selection){caseEvidence.push({case_id:c.case_id,broad_count:broad.length,baseline20:baseline20.map(x=>({candidate_id:x.candidate_id,name:x.name,rank:x.lexical_rank})),rerank_error:r.error,selected:[],acquired_contracts:[],relevant_candidates:[],attempts:[],selected_live:null});continue;}const selectedProviders=resolveSelected(r.selection,broad),selectionFp=providerSelectionFingerprint(c,r.selection),crawled=await crawlSelected(selectedProviders),contracts:LiveContract[]=[],meta=new Map<string,any>();for(const row of crawled)for(const a of row.acquired){const lc=toLiveContract(row.provider,a);contracts.push(lc);meta.set(`${lc.api_key}|${lc.spec_url}`,{provider:row.provider,acquired:a});}const candidates=candidateSummary(c,contracts),relevant=candidates.filter(relevantOperation),suppliers=buildSupplierCandidates(relevant,contracts),execCase=EXEC_CASES[c.case_id],attempts:any[]=[];let selectedLive:any=null;for(const supplier of suppliers){const proc=await procure(config,c,execCase,supplier,procurementEvidence);if(!proc.ok){attempts.push({api_key:supplier.candidate.api_key,status:proc.status});continue;}try{const rr=proc.readiness,bindings=proc.bindings??[];if(!rr.server_base||!rr.allowed_host)throw new Error("missing_execution_base");const url=compileRequest(rr.server_base,rr.allowed_host,supplier.candidate.path,rr.params,bindings,execCase.build),verified=await verifyJsonRequest(url,MAX_BYTES);projectionInductions++;const projection=induceProjection(verified.body,execCase,execCase.build),out=project(verified.body,projection);if(!semanticValidate(execCase,execCase.build,out))throw new Error("semantic_mismatch");const m=meta.get(`${supplier.contract.api_key}|${supplier.contract.spec_url}`),descriptor={case_id:c.case_id,api_key:supplier.contract.api_key,title:supplier.contract.title,spec_url:supplier.contract.spec_url,spec_fingerprint:supplier.contract.spec_fingerprint,operation_path:supplier.candidate.path,descriptor_fingerprint:sha({case_id:c.case_id,api_key:supplier.contract.api_key,spec:supplier.contract.spec_fingerprint,path:supplier.candidate.path})};let recipe:any=makeRecipe(execCase,descriptor,rr,bindings,projection);recipe={...recipe,provider_selection_fingerprint:selectionFp,acquisition_trace_fingerprint:m?.acquired?.acquisition_trace_fingerprint,verification_trace_fingerprint:verificationTraceFingerprint({url,out})};recipe.recipe_fingerprint=sha({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);selectedLive={api_key:supplier.candidate.api_key,provider:m?.provider,output:out,recipe};attempts.push({api_key:supplier.candidate.api_key,status:"verified_live"});break;}catch(e){attempts.push({api_key:supplier.candidate.api_key,status:"live_failed",error:String(e)});}}
    caseEvidence.push({case_id:c.case_id,broad_count:broad.length,baseline20:baseline20.map(x=>({candidate_id:x.candidate_id,name:x.name,rank:x.lexical_rank})),reranked:selectedProviders.map(x=>({candidate_id:x.candidate_id,name:x.name,lexical_rank:x.lexical_rank,from_beyond_20:x.lexical_rank>20})),provider_selection_fingerprint:selectionFp,acquired_contracts:contracts.map(x=>({api_key:x.api_key,spec_url:x.spec_url,operation_count:x.operations.length,...meta.get(`${x.api_key}|${x.spec_url}`)?.acquired,provider_lexical_rank:meta.get(`${x.api_key}|${x.spec_url}`)?.provider?.lexical_rank})),relevant_candidates:relevant,attempts,selected_live:selectedLive});}
  const before={catalogFetches,rerankerCalls,htmlFetches,contractFetches,procurementPlannerCalls,projectionInductions},replay:any[]=[];for(const recipe of recipes){const execCase=EXEC_CASES[recipe.case_id];try{const url=compileRequest(recipe.server_base,recipe.allowed_host,recipe.operation_path,recipe.params,recipe.bindings,execCase.replay),verified=await verifyJsonRequest(url,MAX_BYTES),out=project(verified.body,recipe.projection);if(!semanticValidate(execCase,execCase.replay,out))throw new Error("semantic_mismatch");replay.push({case_id:recipe.case_id,success:true,output:out});}catch(e){replay.push({case_id:recipe.case_id,success:false,error:String(e)});}}
  const parsedEntries=catalog.split(/\r?\n/).filter(x=>x.startsWith("| [")).length,replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,reranker_calls:rerankerCalls-before.rerankerCalls,html_fetches:htmlFetches-before.htmlFetches,contract_fetches:contractFetches-before.contractFetches,procurement_planner_calls:procurementPlannerCalls-before.procurementPlannerCalls,supplier_selection_calls:0,projection_inductions:projectionInductions-before.projectionInductions},validRerankCases=caseEvidence.filter(x=>!x.rerank_error),acquiredCases=caseEvidence.filter(x=>x.acquired_contracts.length>0),providers=new Set(acquiredCases.flatMap(x=>x.acquired_contracts.map((y:any)=>y.api_key))).size,relevantCases=caseEvidence.filter(x=>x.relevant_candidates.length>0),beyond20Relevant=caseEvidence.some(x=>x.relevant_candidates.some((rc:any)=>{const m=x.acquired_contracts.find((a:any)=>a.api_key===rc.api_key&&a.spec_url===rc.spec_url);return m?.provider_lexical_rank>20;})),liveCases=caseEvidence.filter(x=>x.selected_live),liveProviders=new Set(liveCases.map(x=>x.selected_live.api_key)).size,replaySuccess=replay.filter(x=>x.success),controlsExecuted=controls.filter(x=>x.executed).length,controlsVerified=controls.filter(x=>x.executed&&x.rejected).length,allRecipeFingerprints=recipes.length>=2&&recipes.every(r=>r.spec_fingerprint&&r.acquisition_trace_fingerprint&&r.provider_selection_fingerprint&&r.verification_trace_fingerprint&&r.recipe_fingerprint);
  const metrics={catalog_entries:parsedEntries,valid_rerank_cases:validRerankCases.length,reranker_calls:rerankerCalls,reranker_repairs:rerankerRepairs,cases_with_acquired_contract:acquiredCases.length,distinct_acquired_providers:providers,relevantly_acquired_cases:relevantCases.length,beyond20_relevant_recovery:beyond20Relevant,live_semantic_cases:liveCases.length,distinct_live_providers:liveProviders,persisted_recipes:recipes.length,replay_successes:replaySuccess.length,replay_rate:recipes.length?replaySuccess.length/recipes.length:0,controls_executed:controlsExecuted,controls_verified:controlsVerified,replay_deltas:replayDeltas,credentials_supplied:credentialsSupplied,cross_domain_accepted:crossDomainAccepted,private_ip_accepted:privateIpAccepted,http_downgrade_accepted:httpDowngradeAccepted,arbitrary_code_executed:arbitraryCodeExecuted,unknown_ids_accepted:unknownIdsAccepted,duplicate_ids_accepted:duplicateIdsAccepted,out_of_set_ids_accepted:outOfSetIdsAccepted};
  const gates={catalog_live_and_200:parsedEntries>=200,zero_case_mappings:casesContainNoMappings(),broad_retrieval_bounded:caseEvidence.every(x=>x.broad_count<=BROAD_TOP_K),valid_rerank_all_3:validRerankCases.length===3&&rerankerRepairs<=3,at_least_2_cases_acquire:acquiredCases.length>=2,at_least_2_acquired_providers:providers>=2,at_least_2_relevant_cases:relevantCases.length>=2,beyond20_relevant_recovery:beyond20Relevant,at_least_2_live_recipes:liveCases.length>=2&&recipes.length>=2,at_least_2_live_providers:liveProviders>=2,replay_100_percent:recipes.length>=2&&replaySuccess.length===recipes.length,replay_control_calls_zero:Object.values(replayDeltas).every(v=>v===0),all_recipe_fingerprints_nonempty:allRecipeFingerprints,all_18_controls_verified:controlsExecuted===18&&controlsVerified===18,invalid_provider_ids_zero:unknownIdsAccepted===0&&duplicateIdsAccepted===0&&outOfSetIdsAccepted===0,credentials_zero:credentialsSupplied===0,network_boundary_zero:crossDomainAccepted===0&&privateIpAccepted===0&&httpDowngradeAccepted===0,arbitrary_code_zero:arbitraryCodeExecuted===0};const formal_decision=Object.values(gates).every(Boolean)?"GO_SEMANTIC_PROVIDER_RETRIEVAL":"REASSESS_SEMANTIC_PROVIDER_RETRIEVAL";const report={experiment:"3V",title:"Semantic Provider Retrieval",started_at,finished_at:new Date().toISOString(),formal_decision,limits:{broad_top_k:BROAD_TOP_K,rerank_top_k:RERANK_TOP_K,max_depth:MAX_DEPTH,max_html_pages:MAX_HTML_PAGES,max_contract_candidates:MAX_CONTRACT_CANDIDATES},metrics,gates,cases:caseEvidence,replay,negative_controls:controls};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUTDIR}/reranker-evidence.json`,JSON.stringify(rerankEvidence,null,2));await writeFile(`${OUTDIR}/procurement-evidence.json`,JSON.stringify(procurementEvidence,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));}
main().catch(async e=>{await mkdir(OUTDIR,{recursive:true});await writeFile(`${OUTDIR}/report.json`,JSON.stringify({experiment:"3V",formal_decision:"REASSESS_SEMANTIC_PROVIDER_RETRIEVAL",fatal_error:String(e)},null,2));console.error(e);process.exitCode=1;});
