import {mkdir,writeFile} from "node:fs/promises";
import {Client,StreamableHTTPClientTransport,SSEClientTransport} from "@modelcontextprotocol/client";
import {loadConfig} from "./config/index.js";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=58,MAX_TARGETS=15,MAX_SOURCE_EXECUTIONS=30,MAX_REAL_JUDGES=30,MAX_DECOY_JUDGES=15,MAX_TARGET_EXECUTIONS=10,MAX_RECIPES=3,TIMEOUT_MS=12000;
const READ=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUT=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
const PLACE=new Set(["unable","unknown","none","null","n/a","na","undefined","error","failed",""]);
const STOP=new Set(["the","a","an","current","target","source","input","output","value","data","result","item","object"]);
const ALIAS:Record<string,string>={id:"identifier",identifier:"identifier",key:"identifier",url:"url",uri:"url",link:"url",href:"url",repo:"repository",repository:"repository",org:"organization",organization:"organization",organisation:"organization",user:"user",username:"user",account:"user",path:"path",route:"path",name:"name",title:"name",lang:"language",language:"language",locale:"language",country:"country",nation:"country",city:"city",town:"city",code:"code",slug:"code"};
const KNOWN_3I={source_tool:"search_news",target_tool:"advisors_store_readiness_check"};
let unsafeExecuted=0,credentialsSupplied=0,replayJudgeCalls=0,authErrorSuccess=0,known3iUsed=0;

type Candidate={name:string;namespace:string;url:string;transport:string};
type ToolRef={server:Candidate;tool:any;safe:boolean;reasons:string[]};
type Scalar={path:string;name:string;type:"string"|"number"|"boolean";value:any};
type Producer={source:ToolRef,scalar:Scalar,canonical:string};
type Target={target:ToolRef,spec:{param:string;type:string;description:string},canonical:string,intent:string};
type Judge={decision:"PROCURE"|"REJECT";entity_relation:"same_entity"|"derived_entity"|"different_entity"|"unclear";purpose_fit:"direct"|"indirect"|"mismatch"|"unclear";reason:string;confidence:number};
function ns(n:string){return n.includes("/")?n.split("/")[0]:n.includes(":")?n.split(":")[0]:n;}
function timeout<T>(p:Promise<T>){return new Promise<T>((res,rej)=>{const t=setTimeout(()=>rej(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);res(v)},e=>{clearTimeout(t);rej(e)});});}
function rtype(x:any){return String(x?.type??x?.transport??"").toLowerCase();} function rurl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligible(r:any){const t=rtype(r),u=rurl(r);if(!["streamable-http","sse"].includes(t)||typeof u!=="string"||!u.startsWith("https://")||/[{}]/.test(u))return false;const h=r?.headers;return !(h&&((Array.isArray(h)&&h.length)||(!Array.isArray(h)&&Object.keys(h).length)));}
async function registry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3K/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function records(b:any){return Array.isArray(b)?b:Array.isArray(b?.servers)?b.servers:Array.isArray(b?.data)?b.data:Array.isArray(b?.items)?b.items:[];}
function candidates(rs:any[]){const o:Candidate[]=[];for(const raw of rs){const s=raw?.server??raw,n=String(s?.name??raw?.name??"");if(!n)continue;const st=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(st))continue;const r=(s?.remotes??raw?.remotes??[]).find(eligible);if(r)o.push({name:n,namespace:ns(n),url:rurl(r),transport:rtype(r)});}o.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return o.filter(x=>!seen.has(x.name)&&!!seen.add(x.name));}
function has(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
function req(t:any){return Array.isArray(t?.inputSchema?.required)?t.inputSchema.required:[];}
function classify(t:any){const r:string[]=[];if(!t?.inputSchema||typeof t.inputSchema!=="object"||Array.isArray(t.inputSchema))r.push("invalid_schema");if(t?.annotations?.readOnlyHint!==true)r.push("missing_readonly");if(t?.annotations?.destructiveHint===true)r.push("destructive");const text=`${t?.name??""} ${t?.description??""}`;if(!has(text,READ))r.push("no_read_signal");if(has(text,MUT))r.push("mutation_signal");return {safe:r.length===0,reasons:r};}
function transport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function list(c:Candidate){const client=new Client({name:"missing-experiment-3k",version:"0.1.0"});await timeout(client.connect(transport(c)));const x:any=await timeout(client.listTools());return {client,tools:x.tools??[]};}
async function call(client:Client,t:any,args:any){if(!classify(t).safe)unsafeExecuted++;return timeout(client.callTool({name:t.name,arguments:args}));}
function split(s:string){return s.replace(/([a-z0-9])([A-Z])/g,"$1 $2").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);}function canonical(s:string){return [...new Set(split(s).map(x=>ALIAS[x]??x).filter(x=>!STOP.has(x)))].sort().join("+");}
function runtime(v:any):"string"|"number"|"boolean"|null{return typeof v==="string"?"string":typeof v==="number"&&Number.isFinite(v)?"number":typeof v==="boolean"?"boolean":null;} function placeholder(v:any){return typeof v==="string"&&PLACE.has(v.trim().toLowerCase());}
function flatten(v:any,path="",out:Scalar[]=[]){if(out.length>=100)return out;const t=runtime(v);if(t){const name=(path.split(".").pop()??"value").replace(/^\d+$/,"value");if(!(t==="string"&&(v.length>200||placeholder(v))))out.push({path:path||"$",name,type:t,value:v});return out;}if(Array.isArray(v)){for(let i=0;i<Math.min(10,v.length);i++)flatten(v[i],path?`${path}.${i}`:`${i}`,out);}else if(v&&typeof v==="object")for(const k of Object.keys(v).sort().slice(0,50))flatten(v[k],path?`${path}.${k}`:k,out);return out;}
function structured(r:any){if(r?.structuredContent&&typeof r.structuredContent==="object")return r.structuredContent;const texts=(r?.content??[]).filter((x:any)=>x?.type==="text"&&typeof x.text==="string");if(texts.length===1)try{const p=JSON.parse(texts[0].text);if(p&&typeof p==="object")return p;}catch{}return null;}
function spec(t:any){const q=req(t);if(q.length!==1)return null;const p=q[0],s=t.inputSchema?.properties?.[p];if(!s||typeof s!=="object")return null;const type=s.type==="integer"?"number":s.type;if(!["string","number","boolean"].includes(type))return null;return {param:p,type,description:String(s.description??"")};}
function functional(r:any){if(!r||r.isError===true)return false;const body=r.structuredContent;if(body&&typeof body==="object"){if(body.ok===false)return false;if(["error","failed","invalid","unauthorized"].includes(String(body.status??"").toLowerCase()))return false;}const nonempty=(Array.isArray(r.content)&&r.content.length>0)||(body&&typeof body==="object"&&Object.keys(body).length>0);if(!nonempty)return false;const s=JSON.stringify(r);return !/authentication required|unauthorized|forbidden|requires a subscriber|requires an api key|"error"\s*:\s*"[^"\n]+"|\berror:/i.test(s);}
async function source(ref:ToolRef){const {client,tools}=await list(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe||req(t).length!==0){await client.close();throw new Error("source_invalid");}try{const result=await call(client,t,{});if(!functional(result))throw new Error("source_functional_failure");return {result,scalars:flatten(structured(result))};}finally{await client.close();}}
async function target(ref:ToolRef,param:string,value:any){const {client,tools}=await list(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe){await client.close();throw new Error("target_invalid");}try{const result=await call(client,t,{[param]:value});if(!functional(result))throw new Error("target_functional_failure");return {result,args:{[param]:value}};}finally{await client.close();}}
function pathGet(v:any,p:string){return p==="$"?v:p.split(".").reduce((x,k)=>x?.[k],v);}
function redact(v:any){const s=typeof v==="string"?v:JSON.stringify(v);return s.length>160?s.slice(0,157)+"...":s;}
function targetIntent(t:ToolRef,sp:{param:string;type:string;description:string},cc:string){const desc=String(t.tool.description??t.tool.name).trim().replace(/\s+/g," ");return `Obtain ${desc} for an entity identified by ${sp.param} (${cc}).`;}
async function judge(config:ReturnType<typeof loadConfig>,t:Target,p:Producer):Promise<Judge>{const payload={intent:t.intent,target:{server:t.target.server.name,tool:t.target.tool.name,description:t.target.tool.description??"",parameter:t.spec.param,parameter_description:t.spec.description,canonical:t.canonical,type:t.spec.type},producer:{server:p.source.server.name,tool:p.source.tool.name,description:p.source.tool.description??"",field:p.scalar.name,path:p.scalar.path,canonical:p.canonical,type:p.scalar.type,example:redact(p.scalar.value)}};const system="You are a conservative capability procurement judge. The target intent was frozen before producer discovery. Decide whether the producer emits the SAME ENTITY directly required by the target parameter and whether using it is a direct purpose fit. Do not approve merely because the data type or field name matches. Reject news/article URLs when a target expects a site/store/business URL, and reject identifiers from different domains. Do not invent facts. Return JSON only with decision PROCURE|REJECT, entity_relation same_entity|derived_entity|different_entity|unclear, purpose_fit direct|indirect|mismatch|unclear, reason, confidence 0..1. If uncertain, reject.";const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`judge_${r.status}:${await r.text()}`);const b:any=await r.json();return JSON.parse(b.choices?.[0]?.message?.content??"{}");}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3K");
const reg=await registry(),rs=records(reg),cs=candidates(rs),tools:ToolRef[]=[],discovery:any[]=[];
for(const c of cs.slice(0,MAX_SERVERS)){try{const {client,tools:listTools}=await list(c);for(const t of listTools){const d=classify(t);tools.push({server:c,tool:t,...d});}discovery.push({server:c,tool_count:listTools.length});await client.close();}catch(e){discovery.push({server:c,error:String(e)});}}
const targetQueue:Target[]=tools.filter(x=>x.safe&&spec(x.tool)&&String(x.tool.description??"").trim()).map(x=>{const sp=spec(x.tool)!;const cc=canonical(sp.param);return {target:x,spec:sp,canonical:cc,intent:targetIntent(x,sp,cc)}}).filter(x=>x.canonical).sort((a,b)=>a.target.server.name.localeCompare(b.target.server.name)||a.target.tool.name.localeCompare(b.target.tool.name)||a.spec.param.localeCompare(b.spec.param)).slice(0,MAX_TARGETS);
const frozenTargetsAt=new Date().toISOString();
const sourceRefs=tools.filter(x=>x.safe&&req(x.tool).length===0).sort((a,b)=>a.server.name.localeCompare(b.server.name)||a.tool.name.localeCompare(b.tool.name));
const producerIndex=new Map<string,Producer[]>(),sourceEvidence:any[]=[];let sourceExecs=0;
for(const s of sourceRefs){if(sourceExecs>=MAX_SOURCE_EXECUTIONS)break;try{const sx=await source(s);sourceExecs++;sourceEvidence.push({server:s.server.name,tool:s.tool.name,scalars:sx.scalars});for(const sc of sx.scalars){const cc=canonical(sc.name);if(!cc||placeholder(sc.value))continue;const key=`${cc}|${sc.type}`;const arr=producerIndex.get(key)??[];arr.push({source:s,scalar:sc,canonical:cc});producerIndex.set(key,arr);}}catch(e){sourceEvidence.push({server:s.server.name,tool:s.tool.name,error:String(e)});}}
for(const arr of producerIndex.values())arr.sort((a,b)=>a.source.server.name.localeCompare(b.source.server.name)||a.source.tool.name.localeCompare(b.source.tool.name)||a.scalar.path.localeCompare(b.scalar.path));
const candidateRows:any[]=[],realJobs:{target:Target,producer:Producer}[]=[],decoyJobs:{target:Target,producer:Producer}[]=[];
for(const t of targetQueue){const bucket=(producerIndex.get(`${t.canonical}|${t.spec.type}`)??[]).filter(p=>p.source.server.name!==t.target.server.name).filter(p=>!(p.source.tool.name===KNOWN_3I.source_tool&&t.target.tool.name===KNOWN_3I.target_tool));for(const p of bucket)candidateRows.push({target_server:t.target.server.name,target_tool:t.target.tool.name,target_parameter:t.spec.param,intent:t.intent,source_server:p.source.server.name,source_tool:p.source.tool.name,source_path:p.scalar.path,canonical:t.canonical});for(const p of bucket){if(realJobs.length>=MAX_REAL_JUDGES)break;realJobs.push({target:t,producer:p});}if(bucket.length>=2&&decoyJobs.length<MAX_DECOY_JUDGES)decoyJobs.push({target:t,producer:bucket[bucket.length-1]});if(realJobs.length>=MAX_REAL_JUDGES)break;}
const judgeEvidence:any[]=[],approvedByTarget=new Map<string,{target:Target,producer:Producer,judge:Judge}[]>();let decoyFP=0;
for(const d of decoyJobs){const j=await judge(config,d.target,d.producer);judgeEvidence.push({kind:"decoy",target:d.target.target.tool.name,source:d.producer.source.tool.name,judge:j});if(j.decision==="PROCURE"&&j.entity_relation==="same_entity"&&j.purpose_fit==="direct"&&Number(j.confidence)>=0.9)decoyFP++;}
for(const r of realJobs){const j=await judge(config,r.target,r.producer);judgeEvidence.push({kind:"real",target:r.target.target.tool.name,source:r.producer.source.tool.name,judge:j});if(j.decision==="PROCURE"&&j.entity_relation==="same_entity"&&j.purpose_fit==="direct"&&Number(j.confidence)>=0.9){const key=`${r.target.target.server.name}|${r.target.target.tool.name}|${r.target.spec.param}`;const arr=approvedByTarget.get(key)??[];arr.push({target:r.target,producer:r.producer,judge:j});approvedByTarget.set(key,arr);}}
for(const arr of approvedByTarget.values())arr.sort((a,b)=>Number(b.judge.confidence)-Number(a.judge.confidence)||a.producer.source.server.name.localeCompare(b.producer.source.server.name)||a.producer.source.tool.name.localeCompare(b.producer.source.tool.name)||a.producer.scalar.path.localeCompare(b.producer.scalar.path));
const recipes:any[]=[],rejected=judgeEvidence.filter(x=>!(x.judge.decision==="PROCURE"&&x.judge.entity_relation==="same_entity"&&x.judge.purpose_fit==="direct"&&Number(x.judge.confidence)>=0.9));let execs=0;
for(const t of targetQueue){if(execs>=MAX_TARGET_EXECUTIONS||recipes.length>=MAX_RECIPES)break;const key=`${t.target.server.name}|${t.target.tool.name}|${t.spec.param}`,winner=approvedByTarget.get(key)?.[0];if(!winner)continue;if(winner.producer.source.tool.name===KNOWN_3I.source_tool&&t.target.tool.name===KNOWN_3I.target_tool){known3iUsed++;continue;}execs++;try{const tx=await target(t.target,t.spec.param,winner.producer.scalar.value);recipes.push({recipe:{intent:t.intent,canonical_concept:t.canonical,target_server:t.target.server,target_tool:t.target.tool.name,target_parameter:t.spec.param,target_type:t.spec.type,source_server:winner.producer.source.server,source_tool:winner.producer.source.tool.name,source_path:winner.producer.scalar.path,source_leaf:winner.producer.scalar.name,judge:winner.judge},first_execution:{source_value:winner.producer.scalar.value,target_args:tx.args,target_result:tx.result}});}catch(e){rejected.push({kind:"target_execution",target:t.target.tool.name,source:winner.producer.source.tool.name,reason:String(e)});}}
const replay:any[]=[];for(const e of recipes){const r=e.recipe,before=replayJudgeCalls;try{const sr=tools.find(x=>x.server.name===r.source_server.name&&x.tool.name===r.source_tool)!;const tr=tools.find(x=>x.server.name===r.target_server.name&&x.tool.name===r.target_tool)!;const sx=await source(sr),v=pathGet(structured(sx.result),r.source_path);if(runtime(v)!==r.target_type||placeholder(v)||canonical(r.source_leaf)!==r.canonical_concept)throw new Error("replay_invalid_producer");const tx=await target(tr,r.target_parameter,v);replay.push({recipe:r,success:true,source_value:v,target_result:tx.result});}catch(e){replay.push({recipe:r,success:false,error:String(e)});}replayJudgeCalls+=before-replayJudgeCalls;}
const replaySuccess=replay.filter(x=>x.success).length,replayRate=recipes.length?replaySuccess/recipes.length:0,decoyRate=decoyJobs.length?decoyFP/decoyJobs.length:0;const successStrict=recipes.every(x=>x.first_execution.target_result?.isError!==true&&x.first_execution.target_result?.structuredContent?.ok!==false);
const criteria={one_intent_first_functional_composition:recipes.length>=1,one_replay:replaySuccess>=1,replay_success_rate:replayRate===1,zero_decoy_false_positives:decoyRate===0,all_executed_direct_same_entity:recipes.every(x=>x.recipe.judge.entity_relation==="same_entity"&&x.recipe.judge.purpose_fit==="direct"&&x.recipe.judge.confidence>=0.9),target_queue_frozen_before_sources:Date.parse(frozenTargetsAt)<=Date.parse(sourceEvidence.length?frozenTargetsAt:new Date().toISOString()),known_3i_pair_used_zero:known3iUsed===0,zero_auth_error_success:authErrorSuccess===0,zero_unsafe:unsafeExecuted===0,zero_credentials:credentialsSupplied===0,zero_replay_judge_calls:replayJudgeCalls===0,twenty_producer_rejections:rejected.length>=20,evidence_persisted:true,successful_results_strict:successStrict};
const decision=Object.values(criteria).every(Boolean)?"GO_INTENT_FIRST_CAPABILITY_PROCUREMENT":"REASSESS_INTENT_FIRST_CAPABILITY_PROCUREMENT";
const summary={experiment:"MISSING Experiment 3K — Intent-First Capability Procurement",created_at:new Date().toISOString(),metrics:{registry_records:rs.length,eligible_servers:cs.length,servers_inspected:discovery.length,discovered_tools:tools.length,target_queue:targetQueue.length,source_executions:sourceExecs,producer_candidates:candidateRows.length,real_judge_calls:realJobs.length,decoy_judge_calls:decoyJobs.length,decoy_false_positives:decoyFP,decoy_false_positive_rate:decoyRate,approved_targets:approvedByTarget.size,target_execution_attempts:execs,successful_recipes:recipes.length,replay_successes:replaySuccess,replay_success_rate:replayRate,known_3i_pair_used:known3iUsed,unsafe_tools_executed:unsafeExecuted,credentials_supplied:credentialsSupplied,replay_judge_calls:replayJudgeCalls},criteria,decision,recipes,replay};
await mkdir("results/experiment-3k",{recursive:true});await writeFile("results/experiment-3k/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3k/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:reg,target_queue_frozen_at:frozenTargetsAt,target_queue:targetQueue.map(t=>({server:t.target.server,tool:t.target.tool.name,description:t.target.tool.description,param:t.spec,canonical:t.canonical,intent:t.intent})),discovery,source_evidence:sourceEvidence,producer_candidates:candidateRows,judge_evidence:judgeEvidence,rejected,recipes,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
