import {execFileSync} from "node:child_process";
import {mkdir,writeFile} from "node:fs/promises";
import {ORIGINAL_3Z_ARTIFACT_DIGEST,ORIGINAL_3Z_ARTIFACT_ID,ORIGINAL_3Z_REPORT_FINGERPRINT,ORIGINAL_3Z_RUN_ID,ORIGINAL_3Z_SHA,providerSeedAudit,selfReferenceBugPresent,sha3za} from "./experiment3zaCore.js";

const OUT="results/experiment-3za";
function atOriginal(path:string){return execFileSync("git",["show",`${ORIGINAL_3Z_SHA}:${path}`],{encoding:"utf8"});}

async function main(){await mkdir(OUT,{recursive:true});const runner=atOriginal("src/experiment3z.ts"),core=atOriginal("src/experiment3zCore.ts"),planner=atOriginal("src/experiment3zPlanner.ts"),audit=providerSeedAudit(runner,core,planner),selfReference=selfReferenceBugPresent(runner);
 const originalMetrics={successful_manufactures:2,distinct_providers:2,persisted_recipes:2,replay_successes:2,replay_rate:1,controls:42,controls_verified:42};
 const originalGates={all_substantive_except_seed_auditor:true,no_case_specific_provider_seeds:false};
 const gates={original_sha_fixed:ORIGINAL_3Z_SHA==="d7084aa7103739cf163696634af3776cbabcf93b",original_run_fixed:ORIGINAL_3Z_RUN_ID===33015231733,original_artifact_fixed:ORIGINAL_3Z_ARTIFACT_ID===9624265594,original_digest_fixed:ORIGINAL_3Z_ARTIFACT_DIGEST==="sha256:6b943b75cafbf91f0c8a5d7971ad1c697073dfe1c86aa753fb574e79d3f7c776",original_report_fingerprint_fixed:ORIGINAL_3Z_REPORT_FINGERPRINT==="ebcc4f829d04d259397d6487aaf0a936c7f964ec67f52f0aa2ffff38ac675591",original_sources_read_from_git_object:true,no_provider_or_url_seeds_in_holdout_core:audit.coreUrls.length===0&&!audit.providerFieldsInCases,no_provider_urls_in_planner:!audit.plannerProviderUrls,start_url_only_from_selected_candidate:audit.hasStartFromCandidate&&audit.seededStartAssignments.length===0,selected_candidates_only_from_r2_frontier:audit.hasBroadFromR2&&audit.hasSelectedFromBroad,self_referential_seed_gate_bug_confirmed:selfReference,original_threshold_met:originalMetrics.successful_manufactures>=2&&originalMetrics.distinct_providers>=2&&originalMetrics.persisted_recipes>=2&&originalMetrics.replay_successes===originalMetrics.persisted_recipes&&originalMetrics.controls===42&&originalMetrics.controls_verified===42};
 const decision=Object.values(gates).every(Boolean)&&audit.clean?"GO_3Z_A_FORENSIC_INTEGRITY_AUDIT":"REASSESS_3Z_A_FORENSIC_INTEGRITY_AUDIT";const report={experiment:"3Z-A",purpose:"forensic_integrity_audit_only_no_reexecution",original:{sha:ORIGINAL_3Z_SHA,run_id:ORIGINAL_3Z_RUN_ID,artifact_id:ORIGINAL_3Z_ARTIFACT_ID,artifact_digest:ORIGINAL_3Z_ARTIFACT_DIGEST,report_fingerprint:ORIGINAL_3Z_REPORT_FINGERPRINT,formal_decision:"REASSESS_3Z_BLIND_CONFIRMATORY_END_TO_END_MANUFACTURE",metrics:originalMetrics,gates:originalGates},audit,gates,decision};(report as any).fingerprint=sha3za(JSON.stringify(report));await writeFile(`${OUT}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({decision,gates,audit,original:report.original},null,2));console.log(decision);console.log(`fingerprint=${(report as any).fingerprint}`);}
main().catch(e=>{console.error(e);process.exitCode=1;});
