import {deriveExperiment4hSource} from "./experiment4hDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4i_anchor_missing:${a.slice(0,120)}`);return s.replace(a,b)}
export function deriveExperiment4iSource(source:string){let x=deriveExperiment4hSource(source);
x=r(x,'import {compile4h as compile4ar,project4h as project4ar,scope4h as scope4ar,validate4h as validate4ar,validateProjected4h as validateProjected4ar} from "./experiment4hContract.js";','import {compile4i as compile4ar,project4i as project4ar,scope4i as scope4ar,validate4i as validate4ar,validateProjected4i as validateProjected4ar} from "./experiment4iContract.js";');
x=r(x,'import {synthesize4h as synthesize4ar} from "./experiment4hPlanner.js";','import {synthesize4i as synthesize4ar} from "./experiment4iPlanner.js";');
x=r(x,'const OUT="results/experiment-4h",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4i",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'documentationOriginFallbacks4h=0;','documentationOriginFallbacks4h=0,placeholderBearingOperations4i=0,placeholderPreservationChecks4i=0,placeholderPreservationFailures4i=0,authPairsPrunedSurgically4i=0,nonAuthRequestTextMutations4i=0,identifierRoleCandidates4i=0,identifierRoleAcceptedNamedParameter4i=0,identifierRoleAcceptedPlaceholder4i=0,identifierRoleAcceptedUniqueBuildValue4i=0,identifierRoleRejectedAmbiguousOccurrence4i=0,identifierRoleRejectedNoSemanticSupport4i=0,identifierRoleRejectedAuthLike4i=0;');
x=r(x,'documentationOriginFallbacks4h+=sm.documentationOriginFallbacks||0;','documentationOriginFallbacks4h+=sm.documentationOriginFallbacks||0;placeholderBearingOperations4i+=sm.placeholderBearingOperations||0;placeholderPreservationChecks4i+=sm.placeholderPreservationChecks||0;placeholderPreservationFailures4i+=sm.placeholderPreservationFailures||0;authPairsPrunedSurgically4i+=sm.authPairsPrunedSurgically||0;nonAuthRequestTextMutations4i+=sm.nonAuthRequestTextMutations||0;identifierRoleCandidates4i+=sm.identifierRoleCandidates||0;identifierRoleAcceptedNamedParameter4i+=sm.identifierRoleAcceptedNamedParameter||0;identifierRoleAcceptedPlaceholder4i+=sm.identifierRoleAcceptedPlaceholder||0;identifierRoleAcceptedUniqueBuildValue4i+=sm.identifierRoleAcceptedUniqueBuildValue||0;identifierRoleRejectedAmbiguousOccurrence4i+=sm.identifierRoleRejectedAmbiguousOccurrence||0;identifierRoleRejectedNoSemanticSupport4i+=sm.identifierRoleRejectedNoSemanticSupport||0;identifierRoleRejectedAuthLike4i+=sm.identifierRoleRejectedAuthLike||0;');
x=r(x,'documentationOriginFallbacks:documentationOriginFallbacks4h,schemaProbeCalls','documentationOriginFallbacks:documentationOriginFallbacks4h,placeholderBearingOperations:placeholderBearingOperations4i,placeholderPreservationChecks:placeholderPreservationChecks4i,placeholderPreservationFailures:placeholderPreservationFailures4i,authPairsPrunedSurgically:authPairsPrunedSurgically4i,nonAuthRequestTextMutations:nonAuthRequestTextMutations4i,identifierRoleCandidates:identifierRoleCandidates4i,identifierRoleAcceptedNamedParameter:identifierRoleAcceptedNamedParameter4i,identifierRoleAcceptedPlaceholder:identifierRoleAcceptedPlaceholder4i,identifierRoleAcceptedUniqueBuildValue:identifierRoleAcceptedUniqueBuildValue4i,identifierRoleRejectedAmbiguousOccurrence:identifierRoleRejectedAmbiguousOccurrence4i,identifierRoleRejectedNoSemanticSupport:identifierRoleRejectedNoSemanticSupport4i,identifierRoleRejectedAuthLike:identifierRoleRejectedAuthLike4i,schemaProbeCalls');
x=x.replaceAll('4H_TASK_OPERATION_ALIGNMENT:','4I_STRUCTURAL_IDENTIFIER_ROLE:').replaceAll('GO_4H_TASK_OPERATION_SEMANTIC_ALIGNMENT','GO_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE').replaceAll('REASSESS_4H_TASK_OPERATION_SEMANTIC_ALIGNMENT','REASSESS_4I_STRUCTURAL_IDENTIFIER_ROLE_INFERENCE');
x=r(x,'experiment:"4H",purpose:"development_task_operation_semantic_alignment"','experiment:"4I",purpose:"development_structural_identifier_role_inference"');
x=r(x,'base_sha:"547e72a94345b978cc64fdb18c3330736742a927"','base_sha:"28c83671b4aa38bd87bf6ddefd540e1b5d6035c1"');
x=r(x,'wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,','wrong_task_probe_attempts_zero:wrongTaskProbeAttempts4h===0,placeholder_preservation_failures_zero:placeholderPreservationFailures4i===0,non_auth_request_text_mutations_zero:nonAuthRequestTextMutations4i===0,');
return x}
