import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {MAX_BYTES,TIMEOUT_MS,docScopeAllowed,sha,type DocEvidence,type FrozenProvider,type SafetyEvent} from "./experiment3wCore.js";

function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function publicIp(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
export async function assertPublicHost(raw:string,httpsOnly:boolean,safety:SafetyEvent[]){const u=new URL(raw);if(httpsOnly&&u.protocol!=="https:"){safety.push({kind:"http_execution",accepted:false,detail:raw});throw new Error("host_policy_non_https");}if(!["http:","https:"].includes(u.protocol))throw new Error("host_policy_scheme");if(isIP(u.hostname)){safety.push({kind:"private_ip",accepted:false,detail:u.hostname});throw new Error("host_policy_ip_literal");}let addrs;try{addrs=await lookup(u.hostname,{all:true,verbatim:true});}catch(e){throw new Error(`dns_unreachable:${u.hostname}:${String(e)}`);}if(!addrs.length||addrs.some(a=>!publicIp(a.address))){safety.push({kind:"private_ip",accepted:false,detail:u.hostname});throw new Error("host_policy_non_public_dns");}return u;}
async function rawGet(url:string,accept:string,httpsOnly:boolean,safety:SafetyEvent[]){await assertPublicHost(url,httpsOnly,safety);const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{method:"GET",headers:{accept,"user-agent":"MISSING-Experiment-3W/0.1"},redirect:"manual",signal:ctrl.signal});const declared=Number(r.headers.get("content-length")||0);if(declared>MAX_BYTES)throw new Error("response_too_large_declared");const text=await r.text();if(Buffer.byteLength(text)>MAX_BYTES)throw new Error("response_too_large");return {status:r.status,ok:r.ok,location:r.headers.get("location"),content_type:r.headers.get("content-type")||"",text};}finally{clearTimeout(timer);}}
export async function fetchDocumentation(provider:FrozenProvider,url:string,evidenceId:string,safety:SafetyEvent[]):Promise<DocEvidence>{const at=new Date().toISOString();try{if(!docScopeAllowed(provider.start_url,url)){safety.push({kind:"cross_domain_docs",accepted:false,detail:url});throw new Error("cross_domain_docs_rejected");}let current=url,first=await rawGet(current,"text/html,text/plain,application/json,*/*",false,safety);if([301,302,307,308].includes(first.status)){if(!first.location)throw new Error("redirect_missing_location");const target=new URL(first.location,current).toString();const a=new URL(current),b=new URL(target);const canonical=b.protocol==="https:"&&a.hostname===b.hostname&&a.pathname===b.pathname&&a.search===b.search;if(!canonical)throw new Error("redirect_not_canonical_https");current=target;first=await rawGet(current,"text/html,text/plain,application/json,*/*",true,safety);if([301,302,307,308].includes(first.status))throw new Error("redirect_chain_rejected");}if(!first.ok)throw new Error(`http_${first.status}`);return {evidence_id:evidenceId,provider_candidate_id:provider.candidate_id,requested_url:url,resolved_url:current,verified_at:at,status:first.status,content_type:first.content_type,body_fingerprint:sha(first.text),text:first.text,state:"ok"};}catch(e){return {evidence_id:evidenceId,provider_candidate_id:provider.candidate_id,requested_url:url,resolved_url:url,verified_at:at,status:0,content_type:"",body_fingerprint:"",text:"",state:"error",error:String(e)};}}
export async function verifiedJsonGet(url:string,safety:SafetyEvent[]){const requested_at=new Date().toISOString();const r=await rawGet(url,"application/json,application/vnd.api+json,*/*",true,safety);if([301,302,307,308].includes(r.status))throw new Error("execution_redirect_rejected");if(!r.ok)throw new Error(`http_${r.status}`);let body:any;try{body=JSON.parse(r.text);}catch{throw new Error("non_json");}return {requested_at,url,status:r.status,content_type:r.content_type,body_fingerprint:sha(r.text),body,trace_fingerprint:sha({requested_at,url,status:r.status,content_type:r.content_type,body_fingerprint:sha(r.text)})};}
