import {deriveExperiment5b3Source} from "./experiment5b3Derivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b4_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment5b4Source(source:string){let x=deriveExperiment5b3Source(source);
x=r(x,'import {compile5b3 as compile4ar,project5b3 as project4ar,scope5b3 as scope4ar,validate5b3 as validate4ar,validateProjected5b3 as validateProjected4ar} from "./experiment5b3Contract.js";','import {compile5b4 as compile4ar,project5b4 as project4ar,scope5b4 as scope4ar,validate5b4 as validate4ar,validateProjected5b4 as validateProjected4ar} from "./experiment5b4Contract.js";');
x=r(x,'import {synthesize5b3 as synthesize4ar} from "./experiment5b3Planner.js";','import {synthesize5b4 as synthesize4ar} from "./experiment5b4Planner.js";');
x=r(x,'const OUT="results/experiment-5b3-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b4-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'request_utility_recovered_5b3:a.parsed_json?.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:a.parsed_json?.request_ordering_fingerprint_5b3??null};','request_utility_recovered_5b3:a.parsed_json?.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:a.parsed_json?.request_ordering_fingerprint_5b3??null,structured_collection_witness_5b4:a.parsed_json?.structured_collection_witness_5b4??null};');
x=r(x,'request_utility_recovered_5b3:syn.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:syn.request_ordering_fingerprint_5b3??null,contract,contract_fingerprint:sha3yr(contract)','request_utility_recovered_5b3:syn.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:syn.request_ordering_fingerprint_5b3??null,structured_collection_witness_5b4:syn.structured_collection_witness_5b4??null,contract,contract_fingerprint:sha3yr(contract)');
x=x.replaceAll('experiment:"5B3-ENGINE"','experiment:"5B4-ENGINE"').replaceAll('purpose:"development_deterministic_provider_output_aware_beam_engine"','purpose:"development_structured_collection_operation_local_utility_engine"').replaceAll('base_sha:"cd85224d9e21ba3e0ddf5de02e371872a2931c37"','base_sha:"fc88d67b47edca26c4cc9bdcc0e500370857338d"');
x=x.replaceAll('./experiment5b3Planner.ts','./experiment5b4Planner.ts').replaceAll('./experiment5b3Contract.ts','./experiment5b4Contract.ts').replaceAll('./experiment5b3Derivation.ts','./experiment5b4Derivation.ts');
x=x.replace('(await readFile(new URL("./experiment5b3RequestUtility.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b3RequestUtility.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b4Collection.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
