import {createHash} from "node:crypto";
import {docScopeAllowed,type DocEvidence} from "./experiment3wCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {P1RequestHypothesis,P1RequestSlot} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";

const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
const AUTH=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|app[_-]?id|appid|client[_-]?id|client[_-]?secret)$/i;
const GENERIC=/^(?:id|name|q|s|query|search|term|value|input|title)$/i;
const PLACEHOLDER=/^(?::([A-Za-z][\w-]*)|\{\{?([A-Za-z][\w-]*)\}?\}|<([A-Za-z][\w-]*)>|\$\{?([A-Za-z][\w-]*)\}?)$/;
const uniq=<T>(xs:T[])=>[...new Set(xs)];
function overlap(a:string,b:string){const l=new Set(lexicalTokensP1(a)),r=new Set(lexicalTokensP1(b));let n=0;for(const t of l)if(r.has(t))n++;return n}
function clean(raw:string){return raw.replace(/&amp;/gi,"&").replace(/[),.;'"`<>]+$/g,"")}
function requestLiterals(text:string){const rows:{raw:string;offset:number}[]=[];const seen=new Set<string>();const abs=/https?:\/\/[^\s"'`<>]+/gi;let m:RegExpExecArray|null;while((m=abs.exec(text))){const raw=clean(m[0]);if(!seen.has(`${m.index}:${raw}`)){seen.add(`${m.index}:${raw}`);rows.push({raw,offset:m.index})}}const rel=/(?:^|[\s"'`>])(\/[A-Za-z0-9._~!$&'()*+,;=:@%{}<>:-]+(?:\/[A-Za-z0-9._~!$&'()*+,;=:@%{}<>:-]*)*(?:\?[^\s"'`<>]+)?)/gm;while((m=rel.exec(text))){const raw=clean(m[1]);if(!raw.includes("?")&&!/[{:<]/.test(raw))continue;const off=m.index+(m[0].length-m[1].length);if(!seen.has(`${off}:${raw}`)){seen.add(`${off}:${raw}`);rows.push({raw,offset:off})}}return rows.sort((a,b)=>a.offset-b.offset||a.raw.localeCompare(b.raw))}
function ctx(text:string,offset:number){return text.slice(Math.max(0,offset-500),Math.min(text.length,offset+1000))}
function placeholderName(value:string){const m=value.trim().match(PLACEHOLDER);return m?m.slice(1).find(Boolean)||null:null}
function urlFrom(raw:string,e:DocEvidence){try{return new URL(raw,e.resolved_url||e.requested_url)}catch{return null}}
function pathPlaceholders(pathname:string){const out:{name:string;token:string}[]=[];for(const seg of pathname.split("/")){const n=placeholderName(seg);if(n)out.push({name:n,token:seg})}return out}
function inputCandidates(c:any,name:string,key:string,context:string){return (c.input_names||[]).map((input:string)=>{const a=overlap(input,name)*160,b=overlap(input,key)*120,d=overlap(`${input} ${c.intent||""}`,context)*8;let score=a+b+d;if(!score&&(c.input_names||[]).length===1&&GENERIC.test(key))score=25;return {input,score}}).filter((x:any)=>x.score>0).sort((a:any,b:any)=>b.score-a.score||a.input.localeCompare(b.input))}
function uniqueInput(c:any,name:string,key:string,context:string){const rows=inputCandidates(c,name,key,context);if(!rows.length)return null;if(rows.length>1&&rows[0].score===rows[1].score)return null;return rows[0].input as string}
function exampleVariableInput(c:any,key:string,context:string,paramCount:number){if((c.input_names||[]).length!==1)return null;const input=String(c.input_names[0]);const semantic=overlap(`${input} ${c.intent||""}`,`${key} ${context}`)>0;if(!semantic&&!GENERIC.test(key))return null;if(paramCount>1&&!GENERIC.test(key)&&overlap(input,key)===0)return null;return input}

export type DocumentaryWitness5B12={template_fingerprint:string;source_evidence_id:string;source_body_fingerprint:string;source_request_fingerprint:string;source_span_fingerprint:string;candidate_id:string;method:"GET";origin:string;fixed_path_fingerprint:string;query_key_set_fingerprint:string;fixed_query_fingerprint:string;variable_slots:{id:string;name:string;in:"path"|"query";input:string;documented_token:string;example_value:string|null}[];ranking_bonus:false};

export function buildDocumentaryRequestHypotheses5B12(evidence:DocEvidence[],provider:Provider4A,c:any){const metrics:any={documentaryRequestsObserved5b12:0,documentaryTemplatesAccepted5b12:0,documentaryTemplatesRejectedScope5b12:0,documentaryTemplatesRejectedAmbiguous5b12:0,documentaryVariableSlots5b12:0,documentaryBindingsAttempted5b12:0,documentaryBindingsAccepted5b12:0,documentaryExampleValueBindings5b12:0,documentaryPlannerVisibleCandidates5b12:0,documentaryEligibleCandidates5b12:0,documentaryBeamEntries5b12:0,documentaryExecutedCandidates5b12:0,documentaryTransport2xx5b12:0,documentaryStructured2xx5b12:0,documentaryStrictRecipes5b12:0,documentaryChangedInputReplaySuccesses5b12:0,documentaryNewFamilyRecipes5b12:0,documentaryLineageComplete5b12:0,documentaryGeometryViolationsAccepted5b12:0,documentaryBoundExampleValuesRetained5b12:0,documentaryUngroundedRuntimeConstants5b12:0,documentaryRankingBonusUses5b12:0};const hypotheses:P1RequestHypothesis[]=[];const witnesses=new Map<string,DocumentaryWitness5B12>();
 for(const e of evidence){if(e.state!=="ok"||e.provider_candidate_id!==provider.candidate_id)continue;for(const lit of requestLiterals(e.text||"")){metrics.documentaryRequestsObserved5b12++;const u=urlFrom(lit.raw,e);if(!u||u.protocol!=="https:"||!docScopeAllowed(provider.start_url,u.toString())){metrics.documentaryTemplatesRejectedScope5b12++;continue}const context=ctx(e.text||"",lit.offset),slots:P1RequestSlot[]=[],input_bindings:Record<string,string>={},literal_bindings:Record<string,string>={},variables:any[]=[];let pathname=u.pathname,ambiguous=false;for(const p of pathPlaceholders(pathname)){metrics.documentaryBindingsAttempted5b12++;const input=uniqueInput(c,p.name,p.name,context);if(!input){ambiguous=true;break}const id=`d12_${sha({e:e.evidence_id,off:lit.offset,in:"path",name:p.name}).slice(0,14)}`;slots.push({id,name:p.name,in:"path",required:true,auth_like:AUTH.test(p.name),literals:[]});if(AUTH.test(p.name)){ambiguous=true;break}input_bindings[input]=id;variables.push({id,name:p.name,in:"path",input,documented_token:p.token,example_value:null});pathname=pathname.replace(p.token,`{${p.name}}`);metrics.documentaryBindingsAccepted5b12++}
  if(ambiguous){metrics.documentaryTemplatesRejectedAmbiguous5b12++;continue}const params=[...u.searchParams.entries()];for(const [key,value] of params){if(AUTH.test(key)){ambiguous=true;break}const ph=placeholderName(value);let input:string|null=null,example:string|null=null;if(ph){metrics.documentaryBindingsAttempted5b12++;input=uniqueInput(c,ph,key,context)}else{input=exampleVariableInput(c,key,context,params.length);if(input){metrics.documentaryBindingsAttempted5b12++;example=value}}if(input){if(Object.prototype.hasOwnProperty.call(input_bindings,input)){ambiguous=true;break}const id=`d12_${sha({e:e.evidence_id,off:lit.offset,in:"query",key}).slice(0,14)}`,literalId=`dl12_${sha({id,value}).slice(0,14)}`;slots.push({id,name:key,in:"query",required:true,auth_like:false,literals:value?[{id:literalId,value}]:[]});input_bindings[input]=id;variables.push({id,name:key,in:"query",input,documented_token:value,example_value:example});metrics.documentaryBindingsAccepted5b12++;if(example!==null)metrics.documentaryExampleValueBindings5b12++}else{const id=`d12_${sha({e:e.evidence_id,off:lit.offset,in:"query-fixed",key,value}).slice(0,14)}`,literalId=`dl12_${sha({id,value}).slice(0,14)}`;slots.push({id,name:key,in:"query",required:true,auth_like:false,literals:[{id:literalId,value}]});literal_bindings[id]=literalId}}
  if(ambiguous||Object.keys(input_bindings).length!==(c.input_names||[]).length){metrics.documentaryTemplatesRejectedAmbiguous5b12++;continue}const fullPath=pathname+u.search,identity={e:e.evidence_id,off:lit.offset,origin:u.origin,path:fullPath,inputs:input_bindings,literals:literal_bindings},id=`doc12_${sha(identity).slice(0,16)}`;const h:P1RequestHypothesis={id,source_operation_id:`documentary_${sha({e:e.evidence_id,off:lit.offset}).slice(0,14)}`,origin:u.origin,full_path:fullPath,proof_type:"5b12_documentary_request_template",evidence_ids:[e.evidence_id],source_urls:[u.toString()],slots,input_bindings,literal_bindings,score:90,concrete_relation:false};const fixedQuery=params.filter(([k])=>!variables.some(v=>v.in==="query"&&v.name===k));const witness:DocumentaryWitness5B12={template_fingerprint:sha({origin:u.origin,pathname,query_keys:params.map(([k])=>k).sort(),fixed:fixedQuery,variables:variables.map(v=>({name:v.name,in:v.in,input:v.input}))}),source_evidence_id:e.evidence_id,source_body_fingerprint:e.body_fingerprint,source_request_fingerprint:sha(lit.raw),source_span_fingerprint:sha(context),candidate_id:id,method:"GET",origin:u.origin,fixed_path_fingerprint:sha(pathname.replace(/\{[^}]+\}/g,"{}")),query_key_set_fingerprint:sha(params.map(([k])=>k).sort()),fixed_query_fingerprint:sha(fixedQuery),variable_slots:variables,ranking_bonus:false};hypotheses.push(h);witnesses.set(id,witness);metrics.documentaryTemplatesAccepted5b12++;metrics.documentaryVariableSlots5b12+=variables.length}
 }
 const dedup=new Map<string,P1RequestHypothesis>();for(const h of hypotheses){const k=sha({origin:h.origin,path:h.full_path,inputs:h.input_bindings,literals:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const ordered=[...dedup.values()].sort((a,b)=>a.id.localeCompare(b.id));metrics.documentaryPlannerVisibleCandidates5b12=ordered.length;metrics.documentaryEligibleCandidates5b12=ordered.length;return {hypotheses:ordered,witnesses,metrics,fingerprint:sha(ordered.map(h=>[h.id,witnesses.get(h.id)?.template_fingerprint]))}}
