import {deriveExperiment5b14PlannerSource} from "./experiment5b14PlannerDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b20_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}

export function deriveExperiment5b20PlannerSource(source:string){let x=deriveExperiment5b14PlannerSource(source);
 x='import {qualifyRequestHypotheses5B20,qualificationDeterminism5B20} from "./experiment5b20Qualification.js";\n'+x;
 x=r(x,'const historicalPrimary=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,det=requestOrderingDeterminism5B14(c,plannerHypotheses5b11,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B14(c,plannerHypotheses5b11,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);',
 'const qualificationArgs5b20={hypotheses:plannerHypotheses5b11,evidence:localized.evidence,intent:c.intent,inputNames:c.input_names,nativeProofById,collectionProofById,queryProofById,documentaryWitnessById},qualification5b20=qualifyRequestHypotheses5B20(qualificationArgs5b20),qualificationDet5b20=qualificationDeterminism5B20(qualificationArgs5b20);add(metrics,qualification5b20.metrics);if(!qualificationDet5b20.ok)metrics.qualificationNondeterminismViolations5b20=(metrics.qualificationNondeterminismViolations5b20||0)+1;const qualifiedPlannerHypotheses5b20=qualification5b20.hypotheses,qualificationWitnessById5b20=qualification5b20.witnesses,historicalPrimary0=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,historicalPrimary=historicalPrimary0&&qualificationWitnessById5b20.has(historicalPrimary0.id)?historicalPrimary0:undefined,det=requestOrderingDeterminism5B14(c,qualifiedPlannerHypotheses5b20,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B14(c,qualifiedPlannerHypotheses5b20,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);');
 x=r(x,'metrics.documentaryBeamPosition2_5b13=beam[1]&&documentaryWitnessById.has(beam[1].id)?1:0;',
 'metrics.documentaryBeamPosition2_5b13=beam[1]&&documentaryWitnessById.has(beam[1].id)?1:0;metrics.qualificationBeamEntries5b20=beam.filter((h:any)=>qualificationWitnessById5b20.has(h.id)).length;metrics.beamEntriesWithoutQualificationWitness5b20=beam.length-metrics.qualificationBeamEntries5b20;');
 x=r(x,'templateWitness5b11=template5b11.witnesses.get(h.id)||null,documentaryWitness5b12=documentaryWitnessById.get(h.id)||null;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;',
 'templateWitness5b11=template5b11.witnesses.get(h.id)||null,documentaryWitness5b12=documentaryWitnessById.get(h.id)||null,qualificationWitness5b20=qualificationWitnessById5b20.get(h.id)||null;if(qualificationWitness5b20)metrics.probedRequestsWithQualificationWitness5b20=(metrics.probedRequestsWithQualificationWitness5b20||0)+1;else metrics.probedRequestsWithoutQualificationWitness5b20=(metrics.probedRequestsWithoutQualificationWitness5b20||0)+1;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;');
 x=r(x,'materialized.raw.request_utility_rank_5b3=i+1;materialized.raw.request_utility_5b13=byId.get(h.id)||null;',
 'materialized.raw.request_utility_rank_5b3=i+1;materialized.raw.request_utility_5b13=byId.get(h.id)||null;materialized.raw.evidence_qualification_witness_5b20=qualificationWitness5b20?{...qualificationWitness5b20,beam_position:i+1,request_fingerprint:shape(h)}:null;');
 x=r(x,'request_hypotheses:beam,probe_records:',
 'request_hypotheses:beam,request_qualification_fingerprint_5b20:qualification5b20.fingerprint,request_qualification_witnesses_5b20:beam.map((h:any)=>qualificationWitnessById5b20.get(h.id)||null),request_qualification_rejections_5b20:qualification5b20.rejections,probe_records:');
 x=x.replaceAll('export async function synthesize5b14','export async function synthesize5b20').replaceAll('5b14_unknown_case','5b20_unknown_case').replaceAll('5B14_BEAM_EXHAUSTED','5B20_BEAM_EXHAUSTED');
 return x}
