import type {Config} from "./config/index.js";
import type {P1ProbeProof,P1ObservedField} from "./experiment4ap1Model.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import {resolveLocalRef4U,sha4u,type RefMetrics4U} from "./experiment4uOpenApi.js";
import {combineUsage4W} from "./experiment4wSchemaWitness.js";

const GENERIC_OUTPUT=new Set(["id","identifier","code","name","value","data","result","response","item","items","object","string","number","text"]);
const STOP=new Set(["the","a","an","of","for","to","and","or","in","on","by","with","from","same","human","readable","public","machine","operation","returns","return","given"]);
const CONFIDENCE=0.80;
const tokenize=(v:any)=>String(v||"").toLowerCase().match(/[a-z0-9]+/g)||[];
const distinctive=(v:any)=>[...new Set(tokenize(v).filter(t=>t.length>1&&!GENERIC_OUTPUT.has(t)&&!STOP.has(t)))];
const normalizeRole=(v:any)=>tokenize(v).join("_");
function refMetrics():RefMetrics4U{return {operationLocalRefsResolved4u:0,operationLocalRefsRejected4u:0,operationExternalRefsRejected4u:0,operationExternalRefFetches4u:0,operationRefCyclesRejected4u:0,unrelatedRefFailuresIsolated4u:0}}

export type OutputCoverage5B={supported_roles:string[];unsupported_roles:string[];strong_matches:number;exact_matches:number;weak_exact_matches:number;score:number};
function responseText(op:any){const out:string[]=[];const visit=(node:any,depth=0)=>{if(depth>8||node==null)return;if(Array.isArray(node)){for(const x of node.slice(0,80))visit(x,depth+1);return}if(typeof node!=="object")return;for(const [k,v] of Object.entries(node)){if(["description","title","summary"].includes(k)&&typeof v==="string")out.push(v);if(k==="properties"&&v&&typeof v==="object"&&!Array.isArray(v)){for(const [name,p] of Object.entries(v)){out.push(name);visit(p,depth+1)}}else if(["schema","content","items","responses","allOf","oneOf","anyOf"].includes(k))visit(v,depth+1)}};visit(op?.responses||{});return out.join(" ")}
export function outputCoverage5B(op:any,required:readonly string[]):OutputCoverage5B{const text=responseText(op),tokens=new Set(tokenize(text)),normText=normalizeRole(text),supported:string[]=[],unsupported:string[]=[];let strongMatches=0,exactMatches=0,weakExactMatches=0;for(const role of required){const roleNorm=normalizeRole(role),strong=distinctive(role),exact=!!roleNorm&&normText.includes(roleNorm),overlap=strong.filter(t=>tokens.has(t)).length;const weakOnly=strong.length===0&&tokenize(role).some(t=>GENERIC_OUTPUT.has(t))&&tokenize(role).some(t=>tokens.has(t));if(exact){exactMatches++;supported.push(role)}else if(overlap>0){strongMatches+=overlap;supported.push(role)}else if(weakOnly){weakExactMatches++;supported.push(role)}else unsupported.push(role)}return {supported_roles:supported,unsupported_roles:unsupported,strong_matches:strongMatches,exact_matches:exactMatches,weak_exact_matches:weakExactMatches,score:supported.length*240+strongMatches*160+exactMatches*120+weakExactMatches*20}}

function schemaMetadata(root:any,op:any){const byLeaf=new Map<string,any[]>();const seen=new Set<any>();const add=(name:string,node:any,enclosing:string,responseDescription:string)=>{const row={property_name:name,property_title:String(node?.title||""),property_description:String(node?.description||""),enclosing_schema_name:enclosing,response_description:responseDescription};const k=name.toLowerCase();if(!byLeaf.has(k))byLeaf.set(k,[]);byLeaf.get(k)!.push(row)};const walk=(node:any,enclosing:string,responseDescription:string,depth=0)=>{if(depth>8||!node||typeof node!=="object"||seen.has(node))return;seen.add(node);let x=node;try{x=resolveLocalRef4U(root,node,refMetrics())}catch{}if(x?.type==="array"&&x.items){walk(x.items,String(x?.title||enclosing),responseDescription,depth+1);return}if(x?.properties&&typeof x.properties==="object"&&!Array.isArray(x.properties)){for(const [name,raw] of Object.entries(x.properties)){let p:any=raw;try{p=resolveLocalRef4U(root,raw,refMetrics())}catch{}add(name,p,String(x?.title||enclosing),responseDescription);walk(p,String(p?.title||name),responseDescription,depth+1)}}for(const key of ["allOf","oneOf","anyOf"])if(Array.isArray(x?.[key]))for(const child of x[key])walk(child,enclosing,responseDescription,depth+1)};for(const [status,rawResp] of Object.entries(op?.responses||{})){if(!/^2\d\d$/.test(status)&&status!=="default")continue;let resp:any=rawResp;try{resp=resolveLocalRef4U(root,rawResp,refMetrics())}catch{}const desc=String(resp?.description||"");for(const entry of Object.values(resp?.content||{}) as any[]){if(entry?.schema)walk(entry.schema,"",desc)}}return byLeaf}

export function responseGroundedCandidates5B(root:any,op:any,proof:P1ProbeProof){const meta=schemaMetadata(root,op),out:any[]=[];for(const f of proof.record.observed_fields.slice(0,80)){const rows=meta.get(String(f.leaf||"").toLowerCase())||[{}];const m=rows[0]||{};out.push({candidate_id:`obs_${sha4u({path:f.path,type:f.sample_type}).slice(0,14)}`,observed_path:f.path,leaf:f.leaf,observed_type:f.sample_type,property_name:m.property_name||f.leaf,property_title:m.property_title||"",property_description:m.property_description||"",enclosing_schema_name:m.enclosing_schema_name||"",response_description:m.response_description||""})}const dedup=new Map<string,any>();for(const c of out)if(!dedup.has(c.observed_path))dedup.set(c.observed_path,c);return [...dedup.values()].sort((a,b)=>a.observed_path.localeCompare(b.observed_path))}
export function buildResponseResolverPayload5B(intent:string,unresolved:readonly string[],candidates:any[]){return {task_intent:intent,required_output_roles:[...unresolved],closed_observed_field_candidates:candidates.map(c=>({observed_path:c.observed_path,leaf:c.leaf,observed_type:c.observed_type,property_name:c.property_name,property_title:c.property_title,property_description:c.property_description,enclosing_schema_name:c.enclosing_schema_name,response_description:c.response_description}))}}
export function validateResponseResolverOutput5B(raw:any,unresolved:readonly string[],candidates:any[]){const metrics={responseGroundedMappingsAccepted5b:0,responseGroundedNoValidSource5b:0,responseGroundedInventedPathRejects5b:0,responseGroundedAmbiguousRejects5b:0,responseGroundedValueGenerationRejects5b:0};if(!raw||!Array.isArray(raw.mappings))return {mappings:[],metrics};const byPath=new Map(candidates.map(c=>[String(c.observed_path),c])),allowed=new Set(unresolved),used=new Set<string>(),mapped=new Set<string>(),mappings:any[]=[];for(const row of raw.mappings){if(!row||typeof row!=="object")continue;if("value" in row||"literal" in row||"output_value" in row||"code" in row||"transform" in row){metrics.responseGroundedValueGenerationRejects5b++;continue}const role=String(row.output_role||""),path=String(row.observed_path||"");if(!allowed.has(role)||mapped.has(role))continue;if(path==="NO_VALID_SOURCE"){metrics.responseGroundedNoValidSource5b++;mapped.add(role);continue}const candidate=byPath.get(path);if(!candidate){metrics.responseGroundedInventedPathRejects5b++;continue}if(used.has(path)){metrics.responseGroundedAmbiguousRejects5b++;continue}const confidence=Number(row.confidence);if(!Number.isFinite(confidence)||confidence<CONFIDENCE)continue;used.add(path);mapped.add(role);mappings.push({output_role:role,candidate_id:candidate.candidate_id,observed_path:path,confidence,evidence_fields:[candidate.leaf,candidate.property_title,candidate.property_description,candidate.enclosing_schema_name,candidate.response_description].filter(Boolean)})}metrics.responseGroundedMappingsAccepted5b=mappings.length;return {mappings,metrics}}

export async function resolveResponseRoles5B(config:Config,args:{intent:string;root:any;op:any;proof:P1ProbeProof;unresolved:readonly string[]}){const candidates=responseGroundedCandidates5B(args.root,args.op,args.proof),base={responseGroundedResolverCalls5b:0,responseGroundedCandidateFields5b:candidates.length,responseGroundedMappingsAccepted5b:0,responseGroundedNoValidSource5b:0,responseGroundedInventedPathRejects5b:0,responseGroundedAmbiguousRejects5b:0,responseGroundedValueGenerationRejects5b:0};if(!args.unresolved.length||!candidates.length)return {witness:null,metrics:{...base,responseGroundedNoValidSource5b:args.unresolved.length},usage:null};const payload=buildResponseResolverPayload5B(args.intent,args.unresolved,candidates);let body:any=null,parsed:any=null;try{const response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,seed:config.seed,response_format:{type:"json_object"},messages:[{role:"system",content:"You are a closed-world response-role classifier. For each requested output role, select only an observed_path appearing verbatim in closed_observed_field_candidates, or NO_VALID_SOURCE. Never generate a value, provider, URL, new path, code, transformation, or explanation. Return strict JSON: {\"mappings\":[{\"output_role\":string,\"observed_path\":string,\"confidence\":number}]}."},{role:"user",content:JSON.stringify(payload)}]})});if(!response.ok)return {witness:null,metrics:{...base,responseGroundedResolverCalls5b:1,responseGroundedNoValidSource5b:args.unresolved.length},usage:null};body=await response.json();parsed=JSON.parse(String(body?.choices?.[0]?.message?.content||"{}"))}catch{return {witness:null,metrics:{...base,responseGroundedResolverCalls5b:1,responseGroundedNoValidSource5b:args.unresolved.length},usage:body?.usage||null}}const checked=validateResponseResolverOutput5B(parsed,args.unresolved,candidates);if(!checked.mappings.length)return {witness:null,metrics:{...base,responseGroundedResolverCalls5b:1,...checked.metrics},usage:body?.usage||null};const witness={mappings:checked.mappings,candidate_set_fingerprint:sha4u(candidates),resolver_output_fingerprint:sha4u(checked.mappings)};return {witness,metrics:{...base,responseGroundedResolverCalls5b:1,...checked.metrics},usage:body?.usage||null}}
export function verifyResponseRoleWitness5B(w:any,proof:P1ProbeProof){if(!w||!Array.isArray(w.mappings)||w.resolver_output_fingerprint!==sha4u(w.mappings))return false;const paths=new Set(proof.record.observed_fields.map(f=>f.path)),used=new Set<string>();for(const m of w.mappings){if(!m||typeof m.output_role!=="string"||typeof m.observed_path!=="string"||"value" in m||!paths.has(m.observed_path)||used.has(m.observed_path))return false;used.add(m.observed_path)}return w.mappings.length>0}
export function applyResponseRoleWitness5B(projection:any,w:any){const out={...projection};for(const m of w?.mappings||[])if(!out[m.output_role])out[m.output_role]={op:"FIELD",path:m.observed_path};return out}

function entityScope(path:string){const parts=String(path||"").split(".").filter(Boolean);const i=parts.findIndex(p=>/^\d+$/.test(p));return i>=0?parts.slice(0,i+1).join("."):""}
function normalize(v:any){if(v===null||v===undefined)return "";return String(v).trim().toLowerCase().replace(/\.$/,"")}
function numeric(v:any){const s=String(v??"").trim();if(!/^[+-]?(?:\d+\.?\d*|\.\d+)$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?n:null}
function boundedContains(hay:any,needle:any){const h=normalize(hay),n=normalize(needle);if(n.length<4||!h)return false;const escaped=n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(?:^|[^a-z0-9])${escaped}(?:$|[^a-z0-9])`,`i`).test(h)}
function relation(sample:any,input:any,allInputs:any[]){const a=normalize(sample),b=normalize(input);if(a&&b&&a===b)return "normalized_equal";const an=numeric(sample),bn=numeric(input);if(an!==null&&bn!==null&&an===bn)return "numeric_equal";if(boundedContains(sample,input))return "complete_identifier_contains";if(allInputs.length>1&&allInputs.every(v=>boundedContains(sample,v)||normalize(sample)===normalize(v)))return "composite_contains_all";return null}
function exprPath(e:any){if(!e||typeof e!=="object")return null;if(e.op==="FIELD"&&typeof e.path==="string")return e.path;if(e.op==="ROW_LOOKUP"&&typeof e.array_path==="string")return `${e.array_path}.0`;return null}
export type EntityCouplingResult5B={ok:boolean;witness:any|null;metrics:{entityCouplingCandidates5b:number;entityCouplingWitnesses5b:number;entityCouplingValidationSuccesses5b:number;entityCouplingRejects5b:number;inputDerivedOutputCouplingRejects5b:number;crossEntityProjectionRejects5b:number};reason:string|null};
export function deriveEntityCouplingWitness5B(args:{inputNames:readonly string[];input:Record<string,any>;projection:ProjectionPlan|any;proof:P1ProbeProof}) : EntityCouplingResult5B {const metrics={entityCouplingCandidates5b:0,entityCouplingWitnesses5b:0,entityCouplingValidationSuccesses5b:0,entityCouplingRejects5b:0,inputDerivedOutputCouplingRejects5b:0,crossEntityProjectionRejects5b:0},nonInput=Object.values(args.projection||{}).map(exprPath).filter(Boolean) as string[];if(!nonInput.length){metrics.entityCouplingRejects5b++;return {ok:false,witness:null,metrics,reason:"no_response_projected_fields"}}const scopes=new Set(nonInput.map(entityScope));if(scopes.size!==1){metrics.crossEntityProjectionRejects5b++;metrics.entityCouplingRejects5b++;return {ok:false,witness:null,metrics,reason:"cross_entity_projection"}}const scope=[...scopes][0],fields=args.proof.record.observed_fields.filter(f=>entityScope(f.path)===scope),allInputs=args.inputNames.map(n=>args.input[n]),inputWitnesses:any[]=[];for(const name of args.inputNames){const value=args.input[name],matches:any[]=[];for(const f of fields){metrics.entityCouplingCandidates5b++;const rel=relation(f.sample_value,value,allInputs);if(rel)matches.push({input_name:name,observed_path:f.path,relation:rel,entity_scope:scope})}matches.sort((a,b)=>a.observed_path.localeCompare(b.observed_path));if(!matches.length){metrics.entityCouplingRejects5b++;if(Object.values(args.projection||{}).some((e:any)=>e?.op==="INPUT"&&e?.name===name))metrics.inputDerivedOutputCouplingRejects5b++;return {ok:false,witness:null,metrics,reason:`input_not_coupled:${name}`}}inputWitnesses.push(matches[0])}metrics.entityCouplingWitnesses5b=inputWitnesses.length;metrics.entityCouplingValidationSuccesses5b=1;const witness={entity_scope:scope,input_witnesses:inputWitnesses,projected_response_paths:[...nonInput].sort(),projection_fingerprint:sha4u(args.projection),witness_fingerprint:sha4u({scope,inputWitnesses,paths:[...nonInput].sort(),projection:sha4u(args.projection)})};return {ok:true,witness,metrics,reason:null}}
export function verifyEntityCouplingWitness5B(w:any,args:{inputNames:readonly string[];input:Record<string,any>;projection:any;proof:P1ProbeProof}){if(!w||!Array.isArray(w.input_witnesses)||w.projection_fingerprint!==sha4u(args.projection))return false;const expected=sha4u({scope:w.entity_scope,inputWitnesses:w.input_witnesses,paths:[...(w.projected_response_paths||[])].sort(),projection:w.projection_fingerprint});if(w.witness_fingerprint!==expected)return false;const fields=new Map(args.proof.record.observed_fields.map(f=>[f.path,f]));const allInputs=args.inputNames.map(n=>args.input[n]);for(const name of args.inputNames){const row=w.input_witnesses.find((x:any)=>x.input_name===name),field=row?fields.get(row.observed_path):null;if(!row||!field||entityScope(row.observed_path)!==w.entity_scope||relation((field as P1ObservedField).sample_value,args.input[name],allInputs)!==row.relation)return false}return true}
function getPath(body:any,path:string){let cur=body;for(const part of String(path||"").split(".").filter(Boolean)){if(cur===null||cur===undefined)return {ok:false,value:undefined};if(Array.isArray(cur)){if(!/^\d+$/.test(part))return {ok:false,value:undefined};cur=cur[Number(part)]}else if(typeof cur==="object"&&Object.prototype.hasOwnProperty.call(cur,part))cur=cur[part];else return {ok:false,value:undefined}}return {ok:true,value:cur}}
export function verifyEntityCouplingReplay5B(w:any,inputNames:readonly string[],input:Record<string,any>,body:any){if(!w||!Array.isArray(w.input_witnesses))return false;const allInputs=inputNames.map(n=>input[n]);for(const name of inputNames){const row=w.input_witnesses.find((x:any)=>x.input_name===name);if(!row)return false;const got=getPath(body,row.observed_path);if(!got.ok||relation(got.value,input[name],allInputs)!==row.relation)return false}for(const path of w.projected_response_paths||[])if(!getPath(body,path).ok)return false;return true}
export function verifyResponseRoleReplay5B(w:any,body:any){if(!w)return true;if(!Array.isArray(w.mappings)||w.resolver_output_fingerprint!==sha4u(w.mappings))return false;return w.mappings.every((m:any)=>typeof m.observed_path==="string"&&getPath(body,m.observed_path).ok)}
export const combineUsage5B=combineUsage4W;
