import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";

const AUTH_LIKE=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|app[_-]?id|appid|client[_-]?id|client[_-]?secret)$/i;
const AUTH_TEXT=/(?:authorization\s*:|bearer\s+[a-z0-9._-]+|basic\s+auth|curl\s+-u\b|oauth|access[_ -]?token|api[_ -]?key|authentication\s+required|requires?\s+authentication|securitySchemes?)/i;
const MUTATING=/\b(?:POST|PUT|PATCH|DELETE)\b/i;
const REF_TEXT=/(?:API\s*Reference|REST\s*API|Endpoints?|OpenAPI|Swagger|Developer\s*API|API\s*Docs?)/i;
const NAV_PATH=/(?:^|\/)(?:privacy|terms|legal|license|contact|about|login|signin|signup|register|account|blog|news|careers?|press|status)(?:\/|$)/i;
const ASSET=/\.(?:png|jpe?g|gif|svg|css|m?js|woff2?|pdf|zip|tar|gz)(?:$|\?)/i;

export type ProofKind4E="openapi_operation"|"http_request"|"curl_request"|"fetch_request"|"axios_request"|"endpoint_labeled"|"base_relative_operation"|"dom_code_request";
export type Operation4E={id:string;proof_kind:ProofKind4E;evidence_id:string;source_url:string;raw:string;method:"GET";api_base:string|null;operation_path:string|null;absolute_url:string|null;auth_required:boolean;correspondence_text:string;};
export type ReferenceExpansionMetrics={referenceLinksDiscovered:number;referenceExpansionFetches:number;referenceExpansionSuccesses:number;referenceExpansionEvidenceAdded:number;};

function decodeHtml(s:string){return s.replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#x2F;/gi,"/").replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function normalizeTemplate(raw:string){return raw.replace(/\{\{([A-Za-z_][\w.-]*)\}\}/g,"{$1}").replace(/:([A-Za-z_][\w.-]*)/g,"{$1}").replace(/\[([A-Za-z_][\w.-]*)\]/g,"{$1}").replace(/<([A-Za-z_][\w.-]*)>/g,"{$1}").replace(/%7B/gi,"{").replace(/%7D/gi,"}")}
function safeAbs(raw:string){try{const u=new URL(normalizeTemplate(decodeHtml(raw).replace(/[),;]+$/g,"")));if(u.protocol!=="https:"||u.username||u.password||ASSET.test(u.pathname)||NAV_PATH.test(u.pathname))return null;return u}catch{return null}}
function toks(v:string){return lexicalTokensP1(v)}
function overlap(a:string,b:string){const aa=new Set(toks(a)),bb=new Set(toks(b));let n=0;for(const t of aa)if(bb.has(t))n++;return n}
function norm(v:any){return String(v??"").trim().toLowerCase()}
function sameReg(a:string,b:string){const x=a.toLowerCase().split(".").filter(Boolean),y=b.toLowerCase().split(".").filter(Boolean);if(x.length<2||y.length<2)return a===b;return x.slice(-2).join(".")===y.slice(-2).join(".")}

function structuralScopes(text:string){const out:{raw:string;kind:"dom"|"fence"|"line";start:number}[]=[];for(const m of text.matchAll(/<(?:pre|code)\b[^>]*>[\s\S]{0,5000}?<\/(?:pre|code)>/gi))out.push({raw:decodeHtml(m[0]),kind:"dom",start:m.index??0});for(const m of text.matchAll(/```[\s\S]{0,5000}?```/g))out.push({raw:decodeHtml(m[0]),kind:"fence",start:m.index??0});const plain=decodeHtml(text);for(const m of plain.matchAll(/(?:GET\s+[^\s]+|curl\s+[^\n;]+|fetch\s*\([^\n;]+|axios\.get\s*\([^\n;]+|(?:Base\s+URL|API\s+Base|Endpoint|Request\s+URL|API\s+URL)\s*:\s*[^\s]+)/gi))out.push({raw:m[0],kind:"line",start:m.index??0});return [...new Map(out.map(x=>[`${x.kind}:${x.start}:${x.raw}`,x])).values()]}

function requestAtoms(raw:string){const out:{kind:ProofKind4E;value:string;relative:boolean}[]=[];for(const m of raw.matchAll(/\bGET\s+(https:\/\/[^\s"'`\\]+|\/[^\s"'`\\]+)/gi))out.push({kind:"http_request",value:m[1],relative:m[1].startsWith("/")});for(const m of raw.matchAll(/\bcurl\b[^\n;]*?(https:\/\/[^\s"'`\\]+)/gi))out.push({kind:"curl_request",value:m[1],relative:false});for(const m of raw.matchAll(/\bfetch\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/gi))out.push({kind:"fetch_request",value:m[1],relative:false});for(const m of raw.matchAll(/\baxios\.get\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/gi))out.push({kind:"axios_request",value:m[1],relative:false});for(const m of raw.matchAll(/\b(?:Endpoint|Request\s+URL|API\s+URL)\s*:\s*(https:\/\/[^\s"'`\\]+)/gi))out.push({kind:"endpoint_labeled",value:m[1],relative:false});return out}

export function extractOperations4E(evidence:DocEvidence[]){const operations:Operation4E[]=[];let domScopesParsed=0,requestExamplesExtracted=0,crossRegionJoinRejects=0;for(const ev of evidence){if(ev.state!=="ok")continue;for(const s of structuralScopes(ev.text)){if(s.kind!=="line")domScopesParsed++;const baseMatch=s.raw.match(/\b(?:Base\s+URL|API\s+Base)\s*:\s*(https:\/\/[^\s"'`\\]+)/i);const base=baseMatch?safeAbs(baseMatch[1])?.origin??null:null;const atoms=requestAtoms(s.raw);requestExamplesExtracted+=atoms.length;for(const a of atoms){if(MUTATING.test(s.raw)&&!/\bGET\b/i.test(s.raw))continue;let api_base:string|null=null,operation_path:string|null=null,absolute_url:string|null=null,kind=a.kind;if(a.relative){operation_path=normalizeTemplate(a.value);if(base){api_base=base;kind="base_relative_operation"}else{crossRegionJoinRejects++;continue}}else{const u=safeAbs(a.value);if(!u)continue;api_base=u.origin;operation_path=normalizeTemplate(`${u.pathname}${u.search}`);absolute_url=u.toString();if(s.kind==="dom")kind="dom_code_request"}const auth_required=AUTH_TEXT.test(s.raw);operations.push({id:`op4e_${fourAp1Sha({e:ev.evidence_id,s:s.start,k:kind,v:a.value}).slice(0,16)}`,proof_kind:kind,evidence_id:ev.evidence_id,source_url:ev.resolved_url||ev.requested_url,raw:s.raw,method:"GET",api_base,operation_path,absolute_url,auth_required,correspondence_text:s.raw});}}}return {operations:[...new Map(operations.map(o=>[o.id,o])).values()],metrics:{domScopesParsed,requestExamplesExtracted,crossRegionJoinRejects}}}

export function discoverReferenceLinks4E(evidence:DocEvidence[]){const out:{sourceEvidenceId:string;sourceUrl:string;target:string}[]=[];for(const ev of evidence){if(ev.state!=="ok")continue;const text=ev.text;for(const m of text.matchAll(/<a\b[^>]*href=["'](https:\/\/[^"']+)["'][^>]*>([\s\S]{0,300}?)<\/a>/gi)){const label=decodeHtml(m[2]);if(!REF_TEXT.test(label)&&!REF_TEXT.test(m[0]))continue;const u=safeAbs(m[1]);if(!u)continue;try{const src=new URL(ev.resolved_url||ev.requested_url);if(!sameReg(src.hostname,u.hostname))continue}catch{continue}out.push({sourceEvidenceId:ev.evidence_id,sourceUrl:ev.resolved_url||ev.requested_url,target:u.toString()})}for(const m of text.matchAll(/(?:API\s*Reference|REST\s*API|OpenAPI|Swagger|Developer\s*API|API\s*Docs?)[^\n]{0,240}?(https:\/\/[^\s"'<>]+)/gi)){const u=safeAbs(m[1]);if(!u)continue;try{const src=new URL(ev.resolved_url||ev.requested_url);if(!sameReg(src.hostname,u.hostname))continue}catch{continue}out.push({sourceEvidenceId:ev.evidence_id,sourceUrl:ev.resolved_url||ev.requested_url,target:u.toString()})}}return [...new Map(out.map(x=>[x.target,x])).values()]}

export async function expandReferenceEvidence4E(evidence:DocEvidence[],ledger:RecoveryLedger,maxFetches=3):Promise<ReferenceExpansionMetrics>{const links=discoverReferenceLinks4E(evidence),seen=new Set(evidence.map(e=>e.resolved_url||e.requested_url));let fetches=0,successes=0,added=0;for(const link of links.slice(0,maxFetches)){if(seen.has(link.target))continue;fetches++;let status=0,bytes=0,text="",final=link.target;try{const r=await fetch(link.target,{method:"GET",headers:{accept:"text/html,application/json,text/plain;q=0.8"},redirect:"follow"});status=r.status;final=r.url||link.target;text=(await r.text()).slice(0,200000);bytes=Buffer.byteLength(text);if(r.ok&&text){successes++;const ev:any={evidence_id:`4e_ref_${fourAp1Sha({source:link.sourceEvidenceId,target:final,text:text.slice(0,256)}).slice(0,16)}`,requested_url:link.target,resolved_url:final,state:"ok",status_code:status,text,bytes,source_kind:"4e_reference_expansion"};evidence.push(ev as DocEvidence);seen.add(final);added++;ledger.record("documentation","4e_reference_expansion",true,{source_evidence_id:link.sourceEvidenceId,source_url:link.sourceUrl,target_url:link.target,resolved_url:final,status,bytes,evidence_id:ev.evidence_id})}else ledger.record("documentation","4e_reference_expansion",false,{source_evidence_id:link.sourceEvidenceId,target_url:link.target,status,bytes})}catch(err){ledger.record("documentation","4e_reference_expansion",false,{source_evidence_id:link.sourceEvidenceId,target_url:link.target,error:String(err).slice(0,200)})}}return {referenceLinksDiscovered:links.length,referenceExpansionFetches:fetches,referenceExpansionSuccesses:successes,referenceExpansionEvidenceAdded:added}}

function buildHypothesis(op:Operation4E,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c||!op.api_base||!op.operation_path||op.auth_required)return {hypothesis:null,correspondenceCandidate:false,correspondenceAccepted:false,authRejected:!!op.auth_required};let path=normalizeTemplate(op.operation_path),u=new URL(path,op.api_base),slots:P1RequestSlot[]=[];for(const m of path.matchAll(/\{([A-Za-z_][\w.-]*)\}/g))slots.push({id:`par_${fourAp1Sha({o:op.id,n:m[1],p:1}).slice(0,14)}`,name:m[1],in:"path",required:true,auth_like:AUTH_LIKE.test(m[1]),literals:[]});for(const [name,value] of u.searchParams)slots.push({id:`par_${fourAp1Sha({o:op.id,n:name,q:1}).slice(0,14)}`,name,in:"query",required:false,auth_like:AUTH_LIKE.test(name),literals:value?[{id:`lit_${fourAp1Sha({o:op.id,name,value}).slice(0,14)}`,value}]:[]});if(slots.some(s=>s.required&&s.auth_like))return {hypothesis:null,correspondenceCandidate:true,correspondenceAccepted:false,authRejected:true};const bindings:Record<string,string>={},used=new Set<string>();let correspondenceAccepted=true;for(const input of c.input_names){const build=String(c.build[input]??"");let best=slots.filter(s=>!s.auth_like&&!used.has(s.id)).map(s=>({s,score:overlap(input,s.name)*160+(s.literals.some(l=>norm(l.value)===norm(build))?260:0)+(overlap(c.intent||"",op.correspondence_text)>0?40:0)})).filter(x=>x.score>=160).sort((a,b)=>b.score-a.score)[0];if(!best){const seg=path.split("/"),hits:number[]=[];for(let i=0;i<seg.length;i++){let d=seg[i];try{d=decodeURIComponent(d)}catch{}if(norm(d)===norm(build))hits.push(i)}if(hits.length===1&&overlap(c.intent||"",op.correspondence_text)>0){seg[hits[0]]=`{${input}}`;path=seg.join("/");const s={id:`par_${fourAp1Sha({o:op.id,input,concrete:1}).slice(0,14)}`,name:input,in:"path" as const,required:true,auth_like:false,literals:[]};slots.push(s);best={s,score:300}}}if(!best){correspondenceAccepted=false;break}bindings[input]=best.s.id;used.add(best.s.id)}if(!correspondenceAccepted)return {hypothesis:null,correspondenceCandidate:true,correspondenceAccepted:false,authRejected:false};const literals:Record<string,string>={};for(const s of slots)if(!used.has(s.id)&&s.literals.length===1&&/json/i.test(s.literals[0].value)&&/(?:format|response|output|type)/i.test(s.name))literals[s.id]=s.literals[0].id;const h:P1RequestHypothesis={id:`req4e_${fourAp1Sha({o:op.id,path,bindings,literals}).slice(0,16)}`,source_operation_id:op.id,origin:op.api_base,full_path:path,proof_type:`4e_${op.proof_kind}`,evidence_ids:[op.evidence_id],source_urls:[op.source_url],slots,input_bindings:bindings,literal_bindings:literals,score:700,concrete_relation:!op.absolute_url};return {hypothesis:h,correspondenceCandidate:true,correspondenceAccepted:true,authRejected:false}}

export function buildRequestGraph4E(evidence:DocEvidence[],caseId:string){const extracted=extractOperations4E(evidence),built=extracted.operations.map(o=>buildHypothesis(o,caseId)),hypotheses=built.map(x=>x.hypothesis).filter(Boolean) as P1RequestHypothesis[],dedup=new Map<string,P1RequestHypothesis>();for(const h of hypotheses){const k=fourAp1Sha({o:h.origin,p:h.full_path,i:h.input_bindings,l:h.literal_bindings});if(!dedup.has(k))dedup.set(k,h)}const hs=[...dedup.values()].sort((a,b)=>b.score-a.score),packet:P1RequestHypothesis[]=[],rendered=new Set<string>();let dup=0;const c=FOUR_A_CASES.find(x=>x.case_id===caseId);for(const h of hs){if(!c)break;let url:string;try{url=compileRequestHypothesisP1(h,c.build)}catch{continue}if(rendered.has(url)){dup++;continue}rendered.add(url);packet.push(h);if(packet.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}const kinds:Record<string,number>={};for(const o of extracted.operations)kinds[o.proof_kind]=(kinds[o.proof_kind]||0)+1;const placeholderSyntaxCounts={brace:extracted.operations.reduce((n,o)=>n+(o.raw.match(/\{[A-Za-z_][\w.-]*\}/g)?.length||0),0),colon:extracted.operations.reduce((n,o)=>n+(o.raw.match(/:[A-Za-z_][\w.-]*/g)?.length||0),0),bracket:extracted.operations.reduce((n,o)=>n+(o.raw.match(/\[[A-Za-z_][\w.-]*\]/g)?.length||0),0),angle:extracted.operations.reduce((n,o)=>n+(o.raw.match(/<[A-Za-z_][\w.-]*>/g)?.length||0),0),double_brace:extracted.operations.reduce((n,o)=>n+(o.raw.match(/\{\{[A-Za-z_][\w.-]*\}\}/g)?.length||0),0)};return {operations:extracted.operations,hypotheses:hs,probe_packet:packet,metrics:{...extracted.metrics,operationsExtracted:extracted.operations.length,operationsByProofKind:kinds,placeholderSyntaxCounts,authRequiredOperationsRejected:built.filter(x=>x.authRejected).length,knownAuthProbeAttempts:0,operationCorrespondenceCandidates:built.filter(x=>x.correspondenceCandidate).length,operationCorrespondenceAccepted:built.filter(x=>x.correspondenceAccepted).length,operationCorrespondenceRejected:built.filter(x=>x.correspondenceCandidate&&!x.correspondenceAccepted&&!x.authRejected).length,wrongTaskProbeAttempts:0,baseRelativeLinksFormed:extracted.operations.filter(o=>o.proof_kind==="base_relative_operation").length,noOperationEvidence:extracted.operations.length===0,operationEvidenceUnusable:extracted.operations.length>0&&hs.length===0,requestHypotheses:hs.length,uniqueRenderedProbeUrls:rendered.size,duplicateRenderedProbeUrlsRejected:dup,standaloneUrlPromotions:0,documentationOriginFallbacks:0},graph_fingerprint:fourAp1Sha({ops:extracted.operations.map(o=>o.id),hs:hs.map(h=>h.id)})}}
