import {readFile,writeFile} from "node:fs/promises";
import {deriveExperiment5b13Source} from "./experiment5b13Derivation.js";
import {deriveExperiment5b13PlannerSource} from "./experiment5b13PlannerDerivation.js";
const planner=await readFile(new URL("./experiment5b6Planner.ts",import.meta.url),"utf8");
await writeFile(new URL("./.generated-experiment5b13Planner.ts",import.meta.url),deriveExperiment5b13PlannerSource(planner));
const source=await readFile(new URL("./experiment4ar.ts",import.meta.url),"utf8");
const generated=deriveExperiment5b13Source(source).replace("async function rerank(async function rerank(","async function rerank(");
await writeFile(new URL("./.generated-experiment5b13.ts",import.meta.url),generated);
const generatedImport="./.generated-experiment5b13.js";
await import(generatedImport);
