import {createHash} from "node:crypto";
import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import type {ProjectionExpr} from "./experiment3xCore.js";

export const FOUR_AR_BASE_SHA="9038f5591be396a44f1971520288ddec64098141";
export const STANDARD_SPEC_PATHS=["/openapi.json","/swagger.json","/api/openapi.json","/v3/api-docs","/.well-known/openapi.json","/openapi.yaml","/openapi.yml","/swagger.yaml","/swagger.yml"] as const;
export const fourArSha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");

export function normalizeOutputPath(raw:string){let s=String(raw||"").trim();s=s.replace(/^\$\.?/,"");s=s.replace(/\[(\d+)\]/g,".$1");s=s.replace(/^\.+|\.+$/g,"").replace(/\.{2,}/g,".");if(s.includes("*"))throw new Error("wildcard_projection_forbidden");return s;}

export function normalizeRequestContract(raw:any,inputNames:string[]){if(!raw||typeof raw!=="object"||Array.isArray(raw))return raw;const c:any=structuredClone(raw);if(c.decision!=="COMPILE")return c;c.path_bindings={...(c.path_bindings||{})};let path=String(c.path_template||"");for(const name of inputNames){const literal=`$input.${name}`;if(path.includes(literal)){path=path.replaceAll(literal,`{${name}}`);c.path_bindings[name]=literal;}const colon=new RegExp(`:${name}(?=/|$)`,`g`);if(colon.test(path)){path=path.replace(colon,`{${name}}`);c.path_bindings[name]=literal;}}
c.path_template=path;if(c.output_paths&&typeof c.output_paths==="object")for(const [k,v] of Object.entries(c.output_paths))if(typeof v==="string")c.output_paths[k]=normalizeOutputPath(v);return c;}

export function evidenceScore(text:string,required:string[]){const t=text.toLowerCase();let s=0;const scheme="h"+"ttps:"+"//";if(/\bget\b/.test(t)||t.includes(scheme))s+=3;if(/openapi|swagger|api-docs|schema/.test(t))s+=5;if(/response|returns?|example|sample|json/.test(t))s+=3;if(/parameter|query|path|endpoint/.test(t))s+=3;for(const r of required)if(t.includes(r.toLowerCase()))s+=2;return s;}

export function selectEvidenceWindows(evidence:DocEvidence[],required:string[],maxChars=52000){const ranked=evidence.filter(e=>e.state==="ok").map(e=>({...e,_score:evidenceScore(e.text,required)})).sort((a,b)=>b._score-a._score||a.evidence_id.localeCompare(b.evidence_id));const out:any[]=[];let used=0;const scheme="h"+"ttps:"+"//";for(const e of ranked){if(used>=maxChars)break;const needles=[scheme," GET ","get ","response","example","schema",...required];const lower=e.text.toLowerCase();const centers:number[]=[];for(const n of needles){const i=lower.indexOf(n.toLowerCase());if(i>=0)centers.push(i);}let text=e.text;if(centers.length){const chunks=centers.slice(0,8).map(i=>e.text.slice(Math.max(0,i-1400),Math.min(e.text.length,i+3600)));text=[...new Set(chunks)].join("\n---\n");}text=text.slice(0,Math.max(0,maxChars-used));used+=text.length;out.push({evidence_id:e.evidence_id,url:e.resolved_url,content_type:e.content_type,text,score:e._score});}return out;}

export type ProjectionPlan=Record<string,ProjectionExpr>;
export function validateProjectionPlan(plan:any,required:readonly string[],inputs:string[]){if(!plan||typeof plan!=="object"||Array.isArray(plan))throw new Error("projection_plan_invalid");const keys=Object.keys(plan).sort(),req=[...required].sort();if(keys.length!==req.length||keys.some((k,i)=>k!==req[i]))throw new Error("projection_keys_mismatch");for(const k of required){const e=plan[k];if(!e||typeof e!=="object")throw new Error(`projection_invalid:${k}`);if(!["FIELD","INPUT","LOOKUP","FIND"].includes(e.op))throw new Error(`projection_op_invalid:${k}`);if(e.op==="FIELD"){e.path=normalizeOutputPath(e.path);if(!e.path)throw new Error(`projection_path_empty:${k}`);}if(e.op==="INPUT"&&!inputs.includes(e.name))throw new Error(`projection_input_invalid:${k}`);if(e.op==="LOOKUP"){e.map_path=normalizeOutputPath(e.map_path);e.value_path=normalizeOutputPath(e.value_path||"");if(e.key?.op==="INPUT"&&!inputs.includes(e.key.name))throw new Error(`projection_lookup_input_invalid:${k}`);}if(e.op==="FIND"){e.array_path=normalizeOutputPath(e.array_path);e.where_path=normalizeOutputPath(e.where_path);e.value_path=normalizeOutputPath(e.value_path||"");if(e.equals?.op==="INPUT"&&!inputs.includes(e.equals.name))throw new Error(`projection_find_input_invalid:${k}`);}}
return plan as ProjectionPlan;}

export function contractFromPlan(base:MicroContract,projection:ProjectionPlan){return {...base,projection};}
