import {mkdir,readFile,writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {FIVE_B15_MAX_ATTEMPTS,FIVE_B15_RETRY_DELAY_MS,fiveB15Sha,retryAllowedFiveB15} from "./experiment5b15Policy.js";
import {inspectFiveB15Integrity} from "./experiment5b15Harness.js";
import {buildFiveB15Report} from "./experiment5b15Decision.js";
import {createFiveB15RunState,executeFiveB15Attempt,lineageFingerprintFiveB15,type FiveB15Attempt} from "./experiment5b15Replay.js";

const outDir=fileURLToPath(new URL("../results/experiment-5b15/",import.meta.url));
const workloadPath=fileURLToPath(new URL("../experiments/5b15/frozen-5b14-replay-workload.json",import.meta.url));
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));

await mkdir(outDir,{recursive:true});const started_at=new Date().toISOString(),integrity=inspectFiveB15Integrity();
if(!integrity.ok){const failure={experiment:"5B15",decision:"REASSESS_5B15_DETERMINISTIC_REPLAY_RESILIENCE",integrity,started_at,finished_at:new Date().toISOString()};await writeFile(`${outDir}/report.json`,JSON.stringify(failure,null,2));throw new Error(`5b15_integrity_failed:${integrity.errors.join("|")}`)}
const workload=JSON.parse(await readFile(workloadPath,"utf8")),recipes:any[]=clone(workload.recipes),state=createFiveB15RunState(),lineageBaseline=new Map<string,string>();
for(const recipe of recipes){const key=String(recipe.recipe_fingerprint);state.recipeBaseline.set(key,fiveB15Sha(recipe));state.inputBaseline.set(key,fiveB15Sha(recipe.changed_input));if(recipe.documentary_witness_5b12)lineageBaseline.set(key,lineageFingerprintFiveB15(recipe))}
const byRecipe=new Map<string,FiveB15Attempt[]>();
for(const recipe of recipes){const row=await executeFiveB15Attempt(recipe,1,state);byRecipe.set(String(recipe.recipe_fingerprint),[row])}
const attempt1AllRecordedBeforeRetry=byRecipe.size===recipes.length&&[...byRecipe.values()].every(rows=>rows.length===1),retried=new Set<string>();let retryDelaysApplied=0;
for(const recipe of recipes){const key=String(recipe.recipe_fingerprint),rows=byRecipe.get(key)!;while(!rows.at(-1)!.success&&retryAllowedFiveB15(rows.length,{outcome_class:rows.at(-1)!.outcome_class,retryable:rows.at(-1)!.retryable,http_status:rows.at(-1)!.http_status})){retried.add(key);await sleep(FIVE_B15_RETRY_DELAY_MS);retryDelaysApplied++;rows.push(await executeFiveB15Attempt(recipe,rows.length+1,state))}}
const attempts=[...byRecipe.values()].flat();let nonRetryableRetriedViolations=0,retryBudgetViolations=0;
for(const rows of byRecipe.values()){if(rows.length>FIVE_B15_MAX_ATTEMPTS)retryBudgetViolations++;for(let i=1;i<rows.length;i++)if(!rows[i-1].retryable)nonRetryableRetriedViolations++}
for(const recipe of recipes){const key=String(recipe.recipe_fingerprint);if(fiveB15Sha(recipe)!==state.recipeBaseline.get(key))state.recipeMutationViolations++;if(fiveB15Sha(recipe.changed_input)!==state.inputBaseline.get(key))state.changedInputMutationViolations++}
const attempt1=attempts.filter(a=>a.attempt===1),finalRows=recipes.map(r=>byRecipe.get(String(r.recipe_fingerprint))!.at(-1)!),finalSuccesses=finalRows.filter(a=>a.success),retryRecoveries=recipes.filter(r=>{const rows=byRecipe.get(String(r.recipe_fingerprint))!;return rows.length>1&&!rows[0].success&&rows.at(-1)!.success}).length,documentaryRecipes=recipes.filter(r=>!!r.documentary_witness_5b12),documentarySuccesses=documentaryRecipes.filter(r=>byRecipe.get(String(r.recipe_fingerprint))!.at(-1)!.success),documentaryLineagePreserved=documentaryRecipes.length>0&&documentaryRecipes.every(r=>lineageFingerprintFiveB15(r)===lineageBaseline.get(String(r.recipe_fingerprint)));
const metrics:any={frozen_recipe_count:recipes.length,recipe_fingerprint_set_fingerprint:workload.recipe_fingerprint_set_fingerprint,changed_input_workload_fingerprint:workload.changed_input_workload_fingerprint,attempt1_records:attempt1.length,attempt1_all_recorded_before_retry:attempt1AllRecordedBeforeRetry,attempt1_replay_successes:attempt1.filter(a=>a.success).length,attempt1_replay_failures:attempt1.filter(a=>!a.success).length,retry_eligible_failures:attempts.filter(a=>!a.success&&a.retryable).length,non_retryable_failures:attempts.filter(a=>!a.success&&!a.retryable).length,recipes_retried:retried.size,retry_attempts_beyond_attempt1:attempts.filter(a=>a.attempt>1).length,retry_delays_applied:retryDelaysApplied,retry_delay_ms:FIVE_B15_RETRY_DELAY_MS,retry_recoveries:retryRecoveries,final_replay_successes:finalSuccesses.length,final_replay_rate:recipes.length?finalSuccesses.length/recipes.length:0,maximum_attempts_used:Math.max(0,...[...byRecipe.values()].map(rows=>rows.length)),logical_execution_attempts:state.logicalAttempts,total_http_attempts:state.ledger.count("fetch"),request_fingerprint_comparisons:state.requestComparisons,request_fingerprint_mismatch_violations:state.requestMismatchViolations,changed_input_mutation_violations:state.changedInputMutationViolations,non_retryable_retried_violations:nonRetryableRetriedViolations,retry_budget_violations:retryBudgetViolations,recipe_mutation_violations:state.recipeMutationViolations,semantic_verifier_source_fingerprint:integrity.semantic_verifier_source_fingerprint,replay_catalog_fetches:0,replay_reranker_calls:0,replay_documentation_fetches:0,replay_synthesis_calls:0,replay_recovery_fetches:0,recipe_generation_calls:0,auth_like_rendered_requests:state.authLikeRenderedRequests,wrong_task_probe_attempts:state.wrongTaskProbeAttempts,stochastic_decisions:0,holdout_accesses:0,documentary_recipe_count:documentaryRecipes.length,documentary_recipe_final_replay_successes:documentarySuccesses.length,documentary_lineage_preserved:documentaryLineagePreserved,ledger_fingerprint:state.ledger.fingerprint()};
const report=buildFiveB15Report(metrics,integrity,attempts,started_at,new Date().toISOString());await writeFile(`${outDir}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({experiment:"5B15",decision:report.decision,fingerprint:report.fingerprint,metrics:report.metrics,gates:report.gates},null,2));
