import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {compileMicroRequest} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES,semanticValidate4a} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import type {ProjectionPlan} from "./experiment4arCore.js";
import {scope4ar4} from "./experiment4ar4Contract.js";
import {executeProgram} from "./experiment3xCore.js";
import {contractFromP1Raw} from "./experiment4ap1Core.js";
import type {P1ProbeProof} from "./experiment4ap1Model.js";
import {buildTypedRequestGraph4C} from "./experiment4cRequest.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(row=>[row.case_id,row]));
const same=(a:any,b:any)=>JSON.stringify(a)===JSON.stringify(b);

export function validate4c(raw:any,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger,probeProof:P1ProbeProof|null){const c=BY_ID[provider.case_id],errors:string[]=[];if(!c)return {errors:["4c_unknown_case"],contract:null as any,projection:null as any,probe_proof:null};if(!raw||typeof raw!=="object"||Array.isArray(raw))return {errors:["4c_contract_not_object"],contract:null as any,projection:null as any,probe_proof:null};if(raw.case_id!==provider.case_id)errors.push("4c_case_id_mismatch");if(raw.provider_candidate_id!==provider.candidate_id)errors.push("4c_provider_id_mismatch");if(raw.decision==="REJECT")return {errors,contract:contractFromP1Raw(raw),projection:null,probe_proof:null};if(raw.decision!=="COMPILE")return {errors:[...errors,"4c_decision_invalid"],contract:null,projection:null,probe_proof:null};if(!probeProof||probeProof.record.disposition!=="success")return {errors:[...errors,"4c_missing_successful_probe_proof"],contract:null,projection:null,probe_proof:null};
 const graph=buildTypedRequestGraph4C(evidence,provider.case_id),prefix="4C_TYPED_REQUEST:",reason=String(raw.reason||""),hypothesisId=reason.startsWith(prefix)?reason.slice(prefix.length):"",hypothesis=graph.hypotheses.find(h=>h.id===hypothesisId);if(!hypothesis){errors.push("4c_request_hypothesis_not_in_typed_graph");ledger.record("guard","endpoint_mutations",false,hypothesisId);return {errors,contract:null,projection:null,probe_proof:null};}if(probeProof.hypothesis.id!==hypothesis.id)errors.push("4c_probe_hypothesis_mismatch");if(raw.method!=="GET"){errors.push("4c_method_not_get");ledger.record("guard","non_get",false,raw.method);}if(raw.base_url!==hypothesis.origin){errors.push("4c_origin_mutated");ledger.record("guard","endpoint_mutations",false,{got:raw.base_url,expected:hypothesis.origin});}if(raw.path_template!==hypothesis.full_path){errors.push("4c_path_mutated");ledger.record("guard","endpoint_mutations",false,{got:raw.path_template,expected:hypothesis.full_path});}if(raw.probe_schema_fingerprint!==probeProof.record.schema_fingerprint||raw.probe_body_fingerprint!==probeProof.record.response_body_fingerprint)errors.push("4c_probe_fingerprint_mismatch");
 const bySlot=new Map(hypothesis.slots.map(s=>[s.id,s])),expectedPath:Record<string,string>={},expectedQuery:Record<string,string>={};for(const [input,slotId] of Object.entries(hypothesis.input_bindings)){const slot=bySlot.get(slotId);if(!slot){errors.push(`4c_missing_slot:${slotId}`);continue;}(slot.in==="path"?expectedPath:expectedQuery)[slot.name]=`$input.${input}`;}for(const [slotId,literalId] of Object.entries(hypothesis.literal_bindings)){const slot=bySlot.get(slotId),literal=slot?.literals.find(l=>l.id===literalId);if(!slot||!literal){errors.push(`4c_literal_proof_missing:${slotId}`);continue;}expectedQuery[slot.name]=literal.value;}if(!same(raw.path_bindings||{},expectedPath)){errors.push("4c_path_bindings_mutated");ledger.record("guard","invented_parameters",false,{got:raw.path_bindings,expected:expectedPath});}if(!same(raw.query_bindings||{},expectedQuery)){errors.push("4c_query_bindings_mutated");ledger.record("guard","invented_parameters",false,{got:raw.query_bindings,expected:expectedQuery});}for(const input of c.input_names)if(!Object.keys(hypothesis.input_bindings).includes(input)){errors.push(`4c_missing_input_influence:${input}`);ledger.record("guard","invented_parameters",false,input);}if(hypothesis.slots.some(s=>s.required&&s.auth_like)){errors.push("4c_required_auth_parameter");ledger.record("guard","credentials",false,hypothesis.id);}
 const plan=raw.projection as ProjectionPlan;if(!plan||typeof plan!=="object"||Array.isArray(plan))errors.push("4c_projection_invalid");else{const keys=Object.keys(plan).sort(),required=[...c.required].sort();if(keys.length!==required.length||keys.some((k,i)=>k!==required[i]))errors.push("4c_projection_keys_mismatch");const observed=new Set(probeProof.record.observed_fields.map(f=>f.path)),used=new Set<string>();for(const output of c.required){const value:any=(plan as any)[output];if(!value){errors.push(`4c_projection_missing:${output}`);continue;}if(value.op==="INPUT"){if(!c.input_names.includes(value.name)){errors.push(`4c_projection_input_invalid:${output}`);ledger.record("guard","ungrounded_projection_fields",false,value.name);}}else if(value.op==="FIELD"){if(!observed.has(value.path)){errors.push(`4c_field_not_observed:${value.path}`);ledger.record("guard","ungrounded_projection_fields",false,value.path);}else if(used.has(value.path))errors.push(`4c_field_reused:${value.path}`);else used.add(value.path);}else{errors.push(`4c_projection_op_forbidden:${output}`);ledger.record("guard","ungrounded_projection_fields",false,value.op);}}}
 const contract:MicroContract=contractFromP1Raw(raw);return {errors,contract,projection:errors.length?null:plan,probe_proof:errors.length?null:probeProof,typed_graph_fingerprint:graph.graph_fingerprint};}

export function compile4c(contract:MicroContract,input:Record<string,unknown>){return compileMicroRequest(contract,input);}
export function project4c(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return executeProgram(plan,body,input) as Record<string,any>;}
export function validateProjected4c(caseId:string,input:Record<string,any>,out:Record<string,any>){return semanticValidate4a(caseId,input,out);}
export function scope4c(start:string,target:string){return scope4ar4(start,target);}
