import { mkdir, writeFile } from "node:fs/promises";
import { Client, StreamableHTTPClientTransport, SSEClientTransport } from "@modelcontextprotocol/client";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=40,MAX_SOURCE_EXECUTIONS=12,MAX_COMPOSITION_ATTEMPTS=20,MAX_RECIPES=3,TIMEOUT_MS=12000;
const READ_WORDS=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUTATION_WORDS=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
let unsafeToolsExecuted=0,credentialsSupplied=0,plannerCalls=0;

type Candidate={name:string;namespace:string;url:string;transport:string};
type ToolRef={server:Candidate;tool:any;safe:boolean;reasons:string[]};
type Scalar={path:string;name:string;type:"string"|"number"|"boolean";value:any};
type Recipe={source_server:Candidate;source_tool:string;source_path:string;target_server:Candidate;target_tool:string;target_parameter:string;target_type:string};
function namespaceOf(name:string){return name.includes("/")?name.split("/")[0]:name.includes(":")?name.split(":")[0]:name;}
function withTimeout<T>(p:Promise<T>):Promise<T>{return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)});});}
function normalizeRemoteType(x:any){return String(x?.type??x?.transport??"").toLowerCase();}
function remoteUrl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligibleRemote(rem:any){const type=normalizeRemoteType(rem),url=remoteUrl(rem);if(!["streamable-http","sse"].includes(type))return false;if(typeof url!=="string"||!url.startsWith("https://")||/[{}]/.test(url))return false;const h=rem?.headers;if(h&&((Array.isArray(h)&&h.length>0)||(!Array.isArray(h)&&Object.keys(h).length>0)))return false;return true;}
async function fetchRegistry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3G/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function extractRecords(body:any){if(Array.isArray(body))return body;if(Array.isArray(body?.servers))return body.servers;if(Array.isArray(body?.data))return body.data;if(Array.isArray(body?.items))return body.items;return [];}
function buildCandidates(records:any[]){const out:Candidate[]=[];for(const raw of records){const s=raw?.server??raw;const status=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(status))continue;const name=String(s?.name??raw?.name??"");if(!name)continue;const rem=(s?.remotes??raw?.remotes??[]).find(eligibleRemote);if(!rem)continue;out.push({name,namespace:namespaceOf(name),url:remoteUrl(rem),transport:normalizeRemoteType(rem)});}out.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return out.filter(c=>!seen.has(c.name)&&!!seen.add(c.name));}
function textHasWord(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
function required(tool:any){return Array.isArray(tool?.inputSchema?.required)?tool.inputSchema.required:[];}
function classify(tool:any){const reasons:string[]=[];if(!tool?.inputSchema||typeof tool.inputSchema!=="object"||Array.isArray(tool.inputSchema))reasons.push("invalid_input_schema");if(tool?.annotations?.readOnlyHint!==true)reasons.push("missing_affirmative_readonly_hint");if(tool?.annotations?.destructiveHint===true)reasons.push("destructive_hint_true");const text=`${tool?.name??""} ${tool?.description??""}`;if(!textHasWord(text,READ_WORDS))reasons.push("no_explicit_read_signal");if(textHasWord(text,MUTATION_WORDS))reasons.push("mutation_signal_present");return {safe:reasons.length===0,reasons};}
function makeTransport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function connectAndList(c:Candidate){const client=new Client({name:"missing-experiment-3g",version:"0.1.0"});await withTimeout(client.connect(makeTransport(c)));const listed:any=await withTimeout(client.listTools());return {client,tools:listed.tools??[]};}
async function call(client:Client,tool:any,args:any){if(!classify(tool).safe)unsafeToolsExecuted++;return withTimeout(client.callTool({name:tool.name,arguments:args}));}
function normalizeName(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,"");}
function compatibleName(a:string,b:string){const x=normalizeName(a),y=normalizeName(b);return x===y||((x.length>=3&&y.includes(x))||(y.length>=3&&x.includes(y)));}
function runtimeType(v:any):"string"|"number"|"boolean"|null{if(typeof v==="string")return "string";if(typeof v==="number"&&Number.isFinite(v))return "number";if(typeof v==="boolean")return "boolean";return null;}
function flatten(v:any,path="",out:Scalar[]=[]){if(out.length>=50)return out;const t=runtimeType(v);if(t){const name=(path.split(".").pop()??"value").replace(/^\d+$/,"value");if(!(t==="string"&&v.length>200))out.push({path:path||"$",name,type:t,value:v});return out;}if(Array.isArray(v)){for(let i=0;i<Math.min(v.length,10);i++)flatten(v[i],path?`${path}.${i}`:`${i}`,out);return out;}if(v&&typeof v==="object"){for(const k of Object.keys(v).sort().slice(0,30))flatten(v[k],path?`${path}.${k}`:k,out);}return out;}
function structured(result:any){if(result?.structuredContent&&typeof result.structuredContent==="object")return result.structuredContent;const texts=(result?.content??[]).filter((x:any)=>x?.type==="text"&&typeof x.text==="string");if(texts.length===1){try{const p=JSON.parse(texts[0].text);if(p&&typeof p==="object")return p;}catch{}}return null;}
function targetSpec(tool:any){const req=required(tool);if(req.length!==1)return null;const p=req[0],schema=tool.inputSchema?.properties?.[p];if(!schema||typeof schema!=="object")return null;const type=schema.type==="integer"?"number":schema.type;if(!["string","number","boolean"].includes(type))return null;return {param:p,type};}
async function executeSource(ref:ToolRef){const {client,tools}=await connectAndList(ref.server);const tool=tools.find((t:any)=>t.name===ref.tool.name);if(!tool||!classify(tool).safe||required(tool).length!==0){await client.close();throw new Error("source_not_available_or_safe");}const started=Date.now();try{const result=await call(client,tool,{});return {result,latency_ms:Date.now()-started,scalars:flatten(structured(result))};}finally{await client.close();}}
async function executeTarget(ref:ToolRef,param:string,value:any){const {client,tools}=await connectAndList(ref.server);const tool=tools.find((t:any)=>t.name===ref.tool.name);if(!tool||!classify(tool).safe){await client.close();throw new Error("target_not_available_or_safe");}const spec=targetSpec(tool);if(!spec||spec.param!==param){await client.close();throw new Error("target_schema_changed");}const args={[param]:value};const started=Date.now();try{return {result:await call(client,tool,args),latency_ms:Date.now()-started,args};}finally{await client.close();}}

const registry=await fetchRegistry();const records=extractRecords(registry);const candidates=buildCandidates(records);const tools:ToolRef[]=[];const discovery:any[]=[];
for(const c of candidates.slice(0,MAX_SERVERS)){try{const {client,tools:list}=await connectAndList(c);for(const tool of list){const d=classify(tool);tools.push({server:c,tool,safe:d.safe,reasons:d.reasons});}discovery.push({server:c,tool_count:list.length});await client.close();}catch(e){discovery.push({server:c,error:String(e)});}}
const sourceRefs=tools.filter(r=>r.safe&&required(r.tool).length===0);const targetRefs=tools.filter(r=>r.safe&&targetSpec(r.tool)!==null);const sourceEvidence:any[]=[];const rejectedPairs:any[]=[];const recipes:any[]=[];let sourceExecs=0,compositionAttempts=0;
for(const src of sourceRefs){if(sourceExecs>=MAX_SOURCE_EXECUTIONS||recipes.length>=MAX_RECIPES)break;let sx:any;try{sx=await executeSource(src);sourceExecs++;sourceEvidence.push({server:src.server.name,tool:src.tool.name,scalars:sx.scalars,latency_ms:sx.latency_ms});}catch(e){sourceEvidence.push({server:src.server.name,tool:src.tool.name,error:String(e)});continue;}if(!sx.scalars.length)continue;
  for(const tgt of targetRefs){if(compositionAttempts>=MAX_COMPOSITION_ATTEMPTS||recipes.length>=MAX_RECIPES)break;if(tgt.server.name===src.server.name){rejectedPairs.push({source:src.tool.name,target:tgt.tool.name,reason:"same_server"});continue;}const spec=targetSpec(tgt.tool)!;let match:Scalar|undefined;for(const scalar of sx.scalars){if(scalar.type===spec.type&&compatibleName(scalar.name,spec.param)){match=scalar;break;}}
    if(!match){rejectedPairs.push({source_server:src.server.name,source_tool:src.tool.name,target_server:tgt.server.name,target_tool:tgt.tool.name,reason:"no_compatible_scalar"});continue;}
    compositionAttempts++;try{const tx=await executeTarget(tgt,spec.param,match.value);const recipe:Recipe={source_server:src.server,source_tool:src.tool.name,source_path:match.path,target_server:tgt.server,target_tool:tgt.tool.name,target_parameter:spec.param,target_type:spec.type};recipes.push({recipe,first_execution:{source_value:match.value,target_args:tx.args,target_result:tx.result,target_latency_ms:tx.latency_ms}});}catch(e){rejectedPairs.push({source_server:src.server.name,source_tool:src.tool.name,target_server:tgt.server.name,target_tool:tgt.tool.name,reason:`execution_failed:${String(e)}`});}}
}
function getPath(v:any,path:string){if(path==="$"||!path)return v;return path.split(".").reduce((x,k)=>x?.[k],v);}
const replay:any[]=[];
for(const entry of recipes){const r:Recipe=entry.recipe;try{const sourceRef=tools.find(x=>x.server.name===r.source_server.name&&x.tool.name===r.source_tool)!;const targetRef=tools.find(x=>x.server.name===r.target_server.name&&x.tool.name===r.target_tool)!;const sx=await executeSource(sourceRef);const body=structured(sx.result);const value=getPath(body,r.source_path);if(runtimeType(value)!==r.target_type)throw new Error("replay_source_type_changed");const tx=await executeTarget(targetRef,r.target_parameter,value);replay.push({recipe:r,success:true,source_value:value,target_args:tx.args,target_result:tx.result});}catch(e){replay.push({recipe:r,success:false,error:String(e)});}}
const successful=recipes.length;const replaySuccess=replay.filter(x=>x.success).length;const replayRate=recipes.length?replaySuccess/recipes.length:0;const allDistinct=recipes.every(x=>x.recipe.source_server.name!==x.recipe.target_server.name);const oneArg=recipes.every(x=>Object.keys(x.first_execution.target_args??{}).length===1);const criteria={one_cross_server_composition:successful>=1,one_replay_success:replaySuccess>=1,replay_success_rate:replayRate===1,two_distinct_servers:allDistinct,one_derived_argument:oneArg,zero_unsafe_executions:unsafeToolsExecuted===0,zero_credentials:credentialsSupplied===0,zero_planner_llm_calls:plannerCalls===0,ten_incompatible_pairs_rejected:rejectedPairs.length>=10,evidence_persisted:true};const decision=Object.values(criteria).every(Boolean)?"GO_LIVE_MCP_CAPABILITY_COMPOSITION":"REASSESS_LIVE_MCP_CAPABILITY_COMPOSITION";
const summary={experiment:"MISSING Experiment 3G — Live MCP Capability Composition",created_at:new Date().toISOString(),metrics:{registry_records:records.length,eligible_servers:candidates.length,servers_inspected:discovery.length,discovered_tools:tools.length,safe_zero_arg_sources:sourceRefs.length,safe_single_required_targets:targetRefs.length,source_executions:sourceExecs,composition_attempts:compositionAttempts,successful_recipes:successful,replay_successes:replaySuccess,replay_success_rate:replayRate,rejected_pairs:rejectedPairs.length,unsafe_tools_executed:unsafeToolsExecuted,credentials_supplied:credentialsSupplied,planner_llm_calls:plannerCalls},criteria,decision,recipes,replay};
await mkdir("results/experiment-3g",{recursive:true});await writeFile("results/experiment-3g/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3g/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:registry,discovery,source_evidence:sourceEvidence,rejected_pairs:rejectedPairs,recipes,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
