import {createHash} from "node:crypto";
import type {DocEvidence} from "./experiment3wCore.js";
import {semanticTokens} from "./experiment3yr2Core.js";
import type {P1RequestHypothesis} from "./experiment4ap1Model.js";

const GENERIC_OUTPUT=new Set(["id","identifier","code","name","value","data","result","response","item","items","object","metadata"]);
const STRUCTURED=new Set(["json","openapi","swagger","schema","response","application","xml","yaml"]);
const uniq=(xs:string[])=>[...new Set(xs)];
const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
function pathText(raw:string){try{const u=new URL(raw);return `${u.pathname} ${Array.from(u.searchParams.keys()).join(" ")}`;}catch{return raw}}
function localSemanticText(h:P1RequestHypothesis,evidence:DocEvidence[]){const ids=new Set(h.evidence_ids||[]),rows=evidence.filter(e=>ids.has(e.evidence_id)&&e.state==="ok"),needles=uniq([...(h.source_urls||[]),String(h.full_path||"")].filter(Boolean));for(const row of rows){const body=String(row.text||"");let at=-1,needle="";for(const n of needles){const i=body.indexOf(n);if(i>=0&&(at<0||i<at)){at=i;needle=n}}if(at<0){for(const n of needles){try{const u=new URL(n);const p=`${u.pathname}${u.search}`;const i=body.indexOf(p);if(i>=0&&(at<0||i<at)){at=i;needle=p}}catch{}}}if(at>=0){const start=Math.max(0,at-700),end=Math.min(body.length,at+needle.length+1400),span=body.slice(start,end);return {text:`${h.source_operation_id} ${h.full_path} ${h.proof_type} ${(h.source_urls||[]).map(pathText).join(" ")} ${span}`,bytes:Buffer.byteLength(span),found:true}}}
 return {text:`${h.source_operation_id} ${h.full_path} ${h.proof_type} ${(h.source_urls||[]).map(pathText).join(" ")}`,bytes:0,found:false}}
function roleCoverage(required:readonly string[],text:string){const doc=new Set(semanticTokens(text));let roles=0,strong=0,weak=0;for(const role of required){const ts=uniq(semanticTokens(role)),distinct=ts.filter(t=>!GENERIC_OUTPUT.has(t));if(distinct.length){const hit=distinct.filter(t=>doc.has(t)).length;if(hit){roles++;strong+=hit}}else if(ts.some(t=>doc.has(t))){roles++;weak++}}return {roles,score:roles*100+strong*25+weak*5}}
export function provenanceNeutralBindingScore5B14(c:any,h:P1RequestHypothesis){const slotIds=new Set((h.slots||[]).map(s=>s.id)),boundSlotIds=new Set(Object.values(h.input_bindings||{})),inputs=(c.input_names||[]) as string[];let invalidRefs=0;for(const [input,slotId] of Object.entries(h.input_bindings||{})){if(!inputs.includes(input)||!slotIds.has(String(slotId)))invalidRefs++}const covered=inputs.filter(input=>{const slotId=h.input_bindings?.[input];return !!slotId&&slotIds.has(slotId)}).length;const unresolved=(h.slots||[]).filter(s=>s.required&&!boundSlotIds.has(s.id)&&!h.literal_bindings?.[s.id]).length;return {score:covered*100-unresolved*300-invalidRefs*500,covered,unresolved,invalidRefs,provenanceBonusUses:0}}
function taskScore(c:any,text:string){const q=uniq(semanticTokens(String(c.intent||""))).filter(t=>!GENERIC_OUTPUT.has(t)),doc=new Set(semanticTokens(text));return q.filter(t=>doc.has(t)).length*20}
function structuredEvidence(text:string){const d=new Set(semanticTokens(text));return [...STRUCTURED].filter(t=>d.has(t)).length}
function complexity(h:P1RequestHypothesis){const pathSegments=String(h.full_path||"").split("/").filter(Boolean).length;return (h.slots||[]).length*10+Object.keys(h.literal_bindings||{}).length*5+pathSegments}
export type RequestUtility5B14={hypothesis_id:string;request_fingerprint:string;output_coverage:number;output_roles_supported:number;binding_score:number;task_score:number;structured_evidence:number;complexity:number;base_score:number;documentary:boolean;request_local_span_found:boolean;request_local_span_bytes:number;binding_unresolved:number;binding_invalid_refs:number;binding_provenance_bonus_uses:number;candidate_class:string};
function candidateClass(h:P1RequestHypothesis){const p=String(h.proof_type||"");if(p==="5b12_documentary_request_template")return "documentary";if(/native/i.test(p))return "native";if(/collection/i.test(p))return "collection";if(/query/i.test(p))return "query";if(/template/i.test(p))return "template";if(/recovery/i.test(p))return "recovery";return "other"}
export function requestUtility5B14(c:any,h:P1RequestHypothesis,evidence:DocEvidence[],nativeProof:any){const local=localSemanticText(h,evidence),nativeCoverage=nativeProof?.output_coverage_5b||null,coverage=nativeCoverage?{roles:Number(nativeCoverage.supported_roles?.length||0),score:Number(nativeCoverage.score||0)}:roleCoverage(c.required||c.required_output_leaf_names||[],local.text),binding=provenanceNeutralBindingScore5B14(c,h),requestFingerprint=sha({origin:h.origin,path:h.full_path,input_bindings:h.input_bindings,literal_bindings:h.literal_bindings});return {hypothesis_id:h.id,request_fingerprint:requestFingerprint,output_coverage:Number(coverage.score||0),output_roles_supported:Number(coverage.roles||0),binding_score:binding.score,task_score:taskScore(c,local.text),structured_evidence:structuredEvidence(local.text),complexity:complexity(h),base_score:Number(h.score||0),documentary:String(h.proof_type||"")==="5b12_documentary_request_template",request_local_span_found:local.found,request_local_span_bytes:local.bytes,binding_unresolved:binding.unresolved,binding_invalid_refs:binding.invalidRefs,binding_provenance_bonus_uses:0,candidate_class:candidateClass(h)}}
export function rankRequestBeam5B14(c:any,hypotheses:P1RequestHypothesis[],evidence:DocEvidence[],nativeProofById:Map<string,any>,documentaryWitnessById:Map<string,any>,historicalPrimary?:P1RequestHypothesis){const rows=hypotheses.map(h=>({h,u:requestUtility5B14(c,h,evidence,nativeProofById.get(h.id))}));rows.sort((a,b)=>b.u.output_coverage-a.u.output_coverage||b.u.binding_score-a.u.binding_score||b.u.task_score-a.u.task_score||b.u.structured_evidence-a.u.structured_evidence||a.u.complexity-b.u.complexity||b.u.base_score-a.u.base_score||a.u.request_fingerprint.localeCompare(b.u.request_fingerprint));const ordering=rows.map((r,i)=>({rank:i+1,...r.u})),fingerprint=sha(ordering),primaryFp=historicalPrimary?requestUtility5B14(c,historicalPrimary,evidence,nativeProofById.get(historicalPrimary.id)).request_fingerprint:null,displaced=!!(primaryFp&&ordering.length&&ordering[0].request_fingerprint!==primaryFp),docs=ordering.filter((o:any)=>o.documentary),classCounts:any={};for(const o of ordering)classCounts[`requestLocalEvaluationsClass_${o.candidate_class}_5b14`]=(classCounts[`requestLocalEvaluationsClass_${o.candidate_class}_5b14`]||0)+1;return {hypotheses:rows.map(r=>r.h),ordering,fingerprint,primary_displaced:displaced,metrics:{requestLocalSemanticEvaluations5b14:rows.length,requestLocalSpanFound5b14:ordering.filter((o:any)=>o.request_local_span_found).length,requestLocalSpanMissing5b14:ordering.filter((o:any)=>!o.request_local_span_found).length,broadDocumentSemanticFallbackUses5b14:0,provenanceNeutralBindingEvaluations5b14:rows.length,bindingProvenanceBonusUses5b14:0,invalidInputSlotReferences5b14:rows.reduce((n,r)=>n+r.u.binding_invalid_refs,0),unresolvedRequiredSlotEvaluations5b14:rows.reduce((n,r)=>n+r.u.binding_unresolved,0),documentaryRank1Candidates5b14:docs.filter((o:any)=>o.rank===1).length,documentaryRank2Candidates5b14:docs.filter((o:any)=>o.rank===2).length,requestOrderingFingerprintCount5b14:1,requestOrderingNondeterminismRejects5b14:0,...classCounts}}}
export function requestOrderingDeterminism5B14(c:any,hypotheses:P1RequestHypothesis[],evidence:DocEvidence[],nativeProofById:Map<string,any>,documentaryWitnessById:Map<string,any>,historicalPrimary?:P1RequestHypothesis){const a=rankRequestBeam5B14(c,hypotheses,evidence,nativeProofById,documentaryWitnessById,historicalPrimary),b=rankRequestBeam5B14(c,hypotheses,evidence,nativeProofById,documentaryWitnessById,historicalPrimary);return {ok:a.fingerprint===b.fingerprint&&JSON.stringify(a.ordering)===JSON.stringify(b.ordering),fingerprint:a.fingerprint}}
