import {mkdir,writeFile} from "node:fs/promises";
import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {createHash} from "node:crypto";
import {z} from "zod";
import {loadConfig} from "./config/index.js";

const TIMEOUT_MS=12000;
const CASES=[
 {case_id:"scholarly_doi_metadata",family:"scholarly",required_source:"crossref_work",build:{doi:"10.1038/nphys1170"},replay:{doi:"10.1126/science.169.3946.635"},required:["doi","title","publisher"]},
 {case_id:"current_weather_coordinates",family:"weather",required_source:"openmeteo_current",build:{latitude:40.7128,longitude:-74.0060},replay:{latitude:35.6762,longitude:139.6503},required:["temperature","weather_code","time"]},
 {case_id:"earthquake_latest_feed",family:"earthquake",required_source:"usgs_feed",build:{window:"all_day"},replay:{window:"all_week"},required:["id","magnitude","place","time"]}
] as const;
const SOURCES={
 crossref_work:{family:"scholarly",url:"https://api.crossref.org/works/{doi}",allowed_paths:["message.DOI","message.title.0","message.publisher"]},
 openmeteo_current:{family:"weather",url:"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,weather_code&timezone=UTC",allowed_paths:["current.temperature_2m","current.weather_code","current.time"]},
 usgs_feed:{family:"earthquake",url:"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/{window}.geojson",allowed_paths:["features.0.id","features.0.properties.mag","features.0.properties.place","features.0.properties.time"]}
} as const;

const sourceSchema=z.union([
 z.object({op:z.literal("SOURCE"),source_id:z.literal("crossref_work"),args:z.object({doi:z.literal("$input.doi")}).strict()}).strict(),
 z.object({op:z.literal("SOURCE"),source_id:z.literal("openmeteo_current"),args:z.object({latitude:z.literal("$input.latitude"),longitude:z.literal("$input.longitude")}).strict()}).strict(),
 z.object({op:z.literal("SOURCE"),source_id:z.literal("usgs_feed"),args:z.object({window:z.literal("$input.window")}).strict()}).strict()
]);
const projectSchema=z.object({op:z.literal("PROJECT_PATHS"),fields:z.record(z.string(),z.string())}).strict();
const outputSchema=z.object({op:z.literal("OUTPUT")}).strict();
const opSchema=z.union([sourceSchema,projectSchema,outputSchema]);
const planSchema=z.object({case_id:z.string(),decision:z.enum(["MANUFACTURE","REJECT"]),reason:z.string(),ops:z.array(opSchema).max(3)}).strict();
type Plan=z.infer<typeof planSchema>;

const JSON_SCHEMA={name:"missing_3o2_plan",strict:true,schema:{type:"object",additionalProperties:false,required:["case_id","decision","reason","ops"],properties:{case_id:{type:"string"},decision:{type:"string",enum:["MANUFACTURE","REJECT"]},reason:{type:"string"},ops:{type:"array",maxItems:3,items:{oneOf:[
 {type:"object",additionalProperties:false,required:["op","source_id","args"],properties:{op:{const:"SOURCE"},source_id:{const:"crossref_work"},args:{type:"object",additionalProperties:false,required:["doi"],properties:{doi:{const:"$input.doi"}}}}},
 {type:"object",additionalProperties:false,required:["op","source_id","args"],properties:{op:{const:"SOURCE"},source_id:{const:"openmeteo_current"},args:{type:"object",additionalProperties:false,required:["latitude","longitude"],properties:{latitude:{const:"$input.latitude"},longitude:{const:"$input.longitude"}}}}},
 {type:"object",additionalProperties:false,required:["op","source_id","args"],properties:{op:{const:"SOURCE"},source_id:{const:"usgs_feed"},args:{type:"object",additionalProperties:false,required:["window"],properties:{window:{const:"$input.window"}}}}},
 {type:"object",additionalProperties:false,required:["op","fields"],properties:{op:{const:"PROJECT_PATHS"},fields:{type:"object",additionalProperties:{type:"string"}}}},
 {type:"object",additionalProperties:false,required:["op"],properties:{op:{const:"OUTPUT"}}}
]}}}}};

let plannerCalls=0,repairCalls=0,replayPlannerCalls=0,wrongSourceDetected=0,wrongSourceAccepted=0,aliasAccepted=0,sourceViolations=0,operationViolations=0,hostViolations=0,redirectsFollowed=0,credentialsSupplied=0,arbitraryCodeExecuted=0;
const sha=(v:any)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
function getPath(v:any,path:string){return path.split(".").reduce((x,k)=>Array.isArray(x)&&/^\d+$/.test(k)?x[Number(k)]:x?.[k],v);}
function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function isPublic(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
async function safeUrl(raw:string){const u=new URL(raw),ev:any={url:raw,hostname:u.hostname,resolved:[],allowed:false};if(u.protocol!=="https:"||isIP(u.hostname)){hostViolations++;throw new Error("host_policy_protocol_or_ip_literal");}const addrs=await lookup(u.hostname,{all:true,verbatim:true});ev.resolved=addrs;if(!addrs.length||addrs.some(a=>!isPublic(a.address))){hostViolations++;throw new Error("host_policy_non_public_dns");}ev.allowed=true;return ev;}
async function fetchJson(url:string,network:any[]){network.push(await safeUrl(url));const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3O2/0.1"},redirect:"manual",signal:ctrl.signal});if(r.status>=300&&r.status<400)throw new Error(`redirect_rejected_${r.status}`);if(!r.ok)throw new Error(`http_${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
function staticValidate(plan:Plan,c:any,count=true){const e:string[]=[];if(plan.case_id!==c.case_id)e.push("case_id_mismatch");if(plan.decision!=="MANUFACTURE")return e;if(plan.ops.length!==3||plan.ops[0].op!=="SOURCE"||plan.ops[1].op!=="PROJECT_PATHS"||plan.ops[2].op!=="OUTPUT")e.push("wrong_sequence");const s:any=plan.ops[0];if(s?.op==="SOURCE"&&s.source_id!==c.required_source){e.push("wrong_source");if(count)wrongSourceDetected++;}const p:any=plan.ops[1];if(p?.op==="PROJECT_PATHS"){const allowed=new Set((SOURCES as any)[c.required_source].allowed_paths);for(const k of c.required){const path=p.fields?.[k];if(!path||!allowed.has(path))e.push(`bad_field:${k}`);}for(const [k,path] of Object.entries(p.fields??{}))if(!c.required.includes(k)||!allowed.has(String(path)))e.push(`unexpected_projection:${k}`);}return e;}
function buildUrl(sourceId:string,input:any){if(sourceId==="crossref_work")return SOURCES.crossref_work.url.replace("{doi}",encodeURIComponent(input.doi));if(sourceId==="openmeteo_current")return SOURCES.openmeteo_current.url.replace("{latitude}",String(input.latitude)).replace("{longitude}",String(input.longitude));if(sourceId==="usgs_feed"){if(!["all_day","all_week"].includes(input.window))throw new Error("invalid_window");return SOURCES.usgs_feed.url.replace("{window}",input.window);}sourceViolations++;throw new Error("unknown_source");}
function semanticValidate(c:any,input:any,out:any){if(c.family==="scholarly")return typeof out.doi==="string"&&out.doi.toLowerCase()===input.doi.toLowerCase()&&typeof out.title==="string"&&out.title.trim()&&typeof out.publisher==="string"&&out.publisher.trim();if(c.family==="weather")return Number.isFinite(out.temperature)&&Number.isFinite(out.weather_code)&&typeof out.time==="string"&&out.time.length>0;if(c.family==="earthquake")return typeof out.id==="string"&&out.id.length>0&&Number.isFinite(out.magnitude)&&typeof out.place==="string"&&out.place.length>0&&Number.isFinite(out.time);return false;}
async function execute(plan:Plan,c:any,input:any,network:any[]){const s:any=plan.ops[0],p:any=plan.ops[1];const body=await fetchJson(buildUrl(s.source_id,input),network);const out:any={};for(const [k,path] of Object.entries(p.fields))out[k]=getPath(body,String(path));if(!semanticValidate(c,input,out))throw new Error("semantic_validation_failed");return {final_output:out,trace_fingerprint:sha(out)};}

async function callPlanner(config:any,c:any,phase:"initial"|"repair",previous?:string){plannerCalls++;if(phase==="repair")repairCalls++;const system="You are MISSING Multi-Family Capability Forge. Choose the correct approved source for the intent and produce exactly SOURCE, PROJECT_PATHS, OUTPUT for MANUFACTURE. Use only allowed paths from the supplied source catalog. Do not invent transforms, URLs, code, aliases, or extra properties.";const payload={case:c,sources:SOURCES,previous_failure:previous??null};const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:JSON_SCHEMA}})});const text=await r.text();let body:any=null;try{body=JSON.parse(text);}catch{}const message=body?.choices?.[0]?.message;const rawContent=message?.content??null;let parsedJson:any=null,parseError:null|string=null;if(typeof rawContent==="string"){try{parsedJson=JSON.parse(rawContent);}catch(e){parseError=String(e);}}return {phase,http_status:r.status,http_ok:r.ok,raw_response:text,raw_content:rawContent,refusal:message?.refusal??null,parsed_json:parsedJson,parse_error:parseError};}
function parsePlanner(a:any){if(!a.http_ok)return {plan:null,error:`planner_http_${a.http_status}`,issues:[]};if(a.refusal)return {plan:null,error:"planner_refusal",issues:[]};if(!a.parsed_json)return {plan:null,error:"planner_json_parse_failure",issues:[]};const p=planSchema.safeParse(a.parsed_json);if(!p.success)return {plan:null,error:"planner_contract_invalid",issues:p.error.issues};return {plan:p.data,error:null,issues:[]};}

const negativeControls=CASES.map((c,i)=>({case_id:c.case_id,decision:"MANUFACTURE",reason:"wrong source control",ops:[{op:"SOURCE",source_id:CASES[(i+1)%CASES.length].required_source,args:CASES[(i+1)%CASES.length].required_source==="crossref_work"?{doi:"$input.doi"}:CASES[(i+1)%CASES.length].required_source==="openmeteo_current"?{latitude:"$input.latitude",longitude:"$input.longitude"}:{window:"$input.window"}},{op:"PROJECT_PATHS",fields:{}},{op:"OUTPUT"}]}));
let negativeRejected=0;for(let i=0;i<negativeControls.length;i++){const p=planSchema.safeParse(negativeControls[i]);if(!p.success||staticValidate(p.data,CASES[i]).length)negativeRejected++;}

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3O2");const results:any[]=[],persisted:any[]=[];
for(const c of CASES){const attempts:any[]=[];let a=await callPlanner(config,c,"initial"),parsed=parsePlanner(a),plan=parsed.plan as Plan|null,errors=parsed.error?[parsed.error]:plan?staticValidate(plan,c):["no_plan"],repaired=false,execution:any=null,network:any[]=[];attempts.push({...a,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:errors});if((parsed.error||errors.length)){a=await callPlanner(config,c,"repair","Previous output failed strict planner/static validation. Return only the schema-constrained valid plan using the correct source and allowed paths.");repaired=true;parsed=parsePlanner(a);plan=parsed.plan as Plan|null;errors=parsed.error?[parsed.error]:plan?staticValidate(plan,c):["no_plan"];attempts.push({...a,validation_error:parsed.error,validation_issues:parsed.issues,static_errors:errors});}if(plan?.decision==="MANUFACTURE"&&!errors.length){try{execution=await execute(plan,c,c.build,network);}catch(e){execution={error:String(e)};}}const validated=Boolean(plan?.decision==="MANUFACTURE"&&!errors.length&&execution&&!execution.error);if(validated){if((plan!.ops[0] as any).source_id!==c.required_source)wrongSourceAccepted++;persisted.push({case_id:c.case_id,family:c.family,plan,fingerprint:sha(plan),execution,network_evidence:network});}results.push({case_id:c.case_id,family:c.family,plan,static_errors:errors,strict_typed:Boolean(plan&&!parsed.error),validated,repaired,execution,attempts,network_evidence:network});}
const replay:any[]=[];for(const p of persisted){const c=CASES.find(x=>x.case_id===p.case_id)!;const before=plannerCalls,network:any[]=[];try{const output=await execute(p.plan,c,c.replay,network);replay.push({case_id:p.case_id,family:p.family,success:true,input:c.replay,output,fingerprint:p.fingerprint,network_evidence:network});}catch(e){replay.push({case_id:p.case_id,family:p.family,success:false,error:String(e),fingerprint:p.fingerprint});}replayPlannerCalls+=plannerCalls-before;}
const famMan=new Set(results.filter(x=>x.plan?.decision==="MANUFACTURE").map(x=>x.family));const famStatic=new Set(results.filter(x=>x.plan?.decision==="MANUFACTURE"&&x.strict_typed&&!x.static_errors.length).map(x=>x.family));const famLive=new Set(results.filter(x=>x.validated).map(x=>x.family));const famReplay=new Set(replay.filter(x=>x.success).map(x=>x.family));const rr=persisted.length?replay.filter(x=>x.success).length/persisted.length:0;const fingerprintsEvidence=persisted.length>0&&persisted.every(x=>x.fingerprint?.length===64&&Array.isArray(x.network_evidence));const criteria={two_manufacture_families:famMan.size>=2,two_static_families:famStatic.size>=2,two_live_families:famLive.size>=2,two_replay_families:famReplay.size>=2,replay_success_rate:persisted.length>0&&rr===1,wrong_source_accepted_zero:wrongSourceAccepted===0,negative_controls_rejected:negativeRejected===negativeControls.length,unknown_alias_accepted_zero:aliasAccepted===0,replay_planner_repair_zero:replayPlannerCalls===0,source_operation_host_zero:sourceViolations===0&&operationViolations===0&&hostViolations===0,redirects_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,fingerprints_evidence:fingerprintsEvidence};const decision=Object.values(criteria).every(Boolean)?"GO_MULTI_FAMILY_AUTONOMOUS_GAP_FILL":"REASSESS_MULTI_FAMILY_AUTONOMOUS_GAP_FILL";const summary={experiment:"MISSING Experiment 3O2 — Schema-Constrained Multi-Family Forge",created_at:new Date().toISOString(),metrics:{cases:CASES.length,planner_calls:plannerCalls,repair_calls:repairCalls,manufacture_families:famMan.size,static_families:famStatic.size,live_families:famLive.size,replay_families:famReplay.size,persisted_recipes:persisted.length,replay_success_rate:rr,negative_controls:negativeControls.length,negative_controls_rejected:negativeRejected,wrong_source_detected:wrongSourceDetected,wrong_source_accepted:wrongSourceAccepted,alias_fields_accepted:aliasAccepted,source_policy_violations:sourceViolations,operation_policy_violations:operationViolations,host_policy_violations:hostViolations,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted},criteria,decision,results:results.map(x=>({case_id:x.case_id,family:x.family,plan:x.plan,static_errors:x.static_errors,strict_typed:x.strict_typed,validated:x.validated,repaired:x.repaired,execution:x.execution,attempts:x.attempts})),replay:replay.map(x=>({case_id:x.case_id,family:x.family,success:x.success,input:x.input,output:x.output,error:x.error,fingerprint:x.fingerprint}))};await mkdir("results/experiment-3o2",{recursive:true});await writeFile("results/experiment-3o2/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3o2/evidence.json",JSON.stringify({sources:SOURCES,negativeControls,results,persisted,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
