import {docScopeAllowed,type DocEvidence,type FrozenProvider,type SafetyEvent,validateMicroContract} from "./experiment3wCore.js";
import {decideFrontier,enforceCrawlDepth,enforcePageBudget,enforceReplayBudget} from "./experiment3wrCore.js";
import {assertPublicHost3wr,validateDocumentationRedirect} from "./experiment3wrNetwork.js";

const provider:FrozenProvider={case_id:"currency_metadata",candidate_id:"p019_x",name:"X",start_url:"https://docs.example.com"};
const evidence:DocEvidence[]=[{evidence_id:"e1",provider_candidate_id:provider.candidate_id,requested_url:provider.start_url,resolved_url:provider.start_url,verified_at:new Date(0).toISOString(),status:200,content_type:"text/html",body_fingerprint:"abc",state:"ok",text:"GET https://api.example.com/currencies/{code} code name JSON response example code name"}];
const good:any={case_id:"currency_metadata",provider_candidate_id:provider.candidate_id,decision:"COMPILE",method:"GET",base_url:"https://api.example.com",path_template:"/currencies/{code}",path_bindings:{code:"$input.currency_id"},query_bindings:{},output_paths:{code:"code",name:"name"},evidence_ids:["e1"],reason:"x"};
function validator(c:any,ev=evidence){const safety:SafetyEvent[]=[];const r=validateMicroContract(c,provider,ev,safety);if(!r.errors.length)throw new Error("control_not_rejected");return r.errors;}
async function rejectedBy(name:string,guard:string,fn:()=>any|Promise<any>){try{await fn();return {control:name,executed:true,rejected:false,guard,evidence:"no_rejection"};}catch(e){return {control:name,executed:true,rejected:true,guard,evidence:String(e)};}}
export async function run3wrControls(){const c:any[]=[];const v=(name:string,obj:any,ev=evidence)=>{const errors=validator(obj,ev);c.push({control:name,executed:true,rejected:true,guard:"validateMicroContract",evidence:errors});};v("wrong_case_id",{...good,case_id:"wrong"});v("wrong_provider_id",{...good,provider_candidate_id:"wrong"});v("post_method",{...good,method:"POST"});v("undocumented_base_url",{...good,base_url:"https://evil.example.net"});v("undocumented_path",{...good,path_template:"/secret/{code}"});v("invented_path_parameter",{...good,path_template:"/currencies/{invented}",path_bindings:{invented:"$input.currency_id"}});v("invented_query_parameter",{...good,query_bindings:{invented:"$input.currency_id"}});v("invented_output_field",{...good,output_paths:{code:"madeup",name:"name"}});v("empty_evidence",{...good,evidence_ids:[]});v("unknown_evidence",{...good,evidence_ids:["missing"]});v("cross_provider_evidence",good,[{...evidence[0],provider_candidate_id:"other"}]);v("credential_bearing_url",{...good,base_url:"https://user:pass@api.example.com"});v("authorization_header_field",{...good,headers:{Authorization:"Bearer x"}});v("http_execution_url",{...good,base_url:"http://api.example.com"});v("ip_literal_host",{...good,base_url:"https://127.0.0.1"});c.push(await rejectedBy("private_dns","assertPublicHost3wr",()=>assertPublicHost3wr("https://localhost",true,[])));c.push(await rejectedBy("cross_domain_docs","validateDocumentationRedirect",()=>validateDocumentationRedirect(provider,provider.start_url,"https://evil.example.net/docs",[])));c.push(await rejectedBy("crawl_depth","enforceCrawlDepth",()=>enforceCrawlDepth(3)));c.push(await rejectedBy("html_budget","enforcePageBudget",()=>enforcePageBudget(8)));const js=decideFrontier("e1","https://docs.example.com/app.js","API docs");if(js.accepted)throw new Error("js_control_not_rejected");c.push({control:"javascript_execution",executed:true,rejected:true,guard:"decideFrontier",evidence:js});const bin=decideFrontier("e1","https://docs.example.com/tool.sh","shell");if(bin.accepted)throw new Error("shell_control_not_rejected");c.push({control:"arbitrary_code",executed:true,rejected:true,guard:"decideFrontier",evidence:bin});c.push(await rejectedBy("replay_external_calls","enforceReplayBudget",()=>enforceReplayBudget({documentation_fetches:1,synthesis_calls:0,provider_selection_calls:0,projection_inductions:0})));if(c.length!==22)throw new Error(`control_count:${c.length}`);return c;}
