import {createHash} from "node:crypto";
import type {ProviderCandidate,RerankSelection} from "./experiment3vCore.js";
import {RERANK_TOP_K} from "./experiment3vCore.js";
import {semanticTokens} from "./experiment3yr2Core.js";

const GENERIC_OUTPUT=new Set(["id","identifier","code","name","value","data","result","response","item","object","metadata"]);
const API_TOKENS=new Set(["api","rest","restful","openapi","swagger","json","documentation","docs","endpoint","developer"]);
const NOISE_TOKENS=new Set(["social","marketing","advertising","ads","hosting","search","random","joke","meme","image","photo"]);
export const PROVIDER_WEIGHTS_5B3={task_overlap:140,output_support:180,input_support:90,api_evidence:30,public_noauth:20,noise_penalty:60} as const;
const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
const uniq=(xs:string[])=>[...new Set(xs)];
function urlPathText(raw:string){try{const u=new URL(raw);return `${u.pathname} ${u.searchParams.keys?Array.from(u.searchParams.keys()).join(" "):""}`;}catch{return ""}}
function metadataText(c:ProviderCandidate){return `${c.name} ${c.description} ${c.category} ${urlPathText(c.link)}`;}
function overlap(q:string[],d:Set<string>){return q.filter(x=>d.has(x)).length;}
function outputTokens(c:any){return uniq(semanticTokens((c.required_output_leaf_names||c.required||[]).join(" ")).filter(t=>!GENERIC_OUTPUT.has(t)));}
function inputTokens(c:any){return uniq(semanticTokens((c.input_names||[]).join(" ")));}
function taskTokens(c:any){return uniq(semanticTokens(String(c.intent||"")));}
function explicitNoAuth(c:ProviderCandidate){const a=String(c.auth||"").trim().toLowerCase();return !a||["no","none","false","n/a","null"].includes(a);}
export type ProviderScore5B3={candidate_id:string;total:number;task_overlap:number;output_support:number;input_support:number;api_evidence:number;public_noauth:number;noise_penalty:number;distinctive_task_anchors:number;normalized_url:string};
export function scoreProvider5B3(c:any,p:ProviderCandidate):ProviderScore5B3{const doc=new Set(semanticTokens(metadataText(p))),task=taskTokens(c),outputs=outputTokens(c),inputs=inputTokens(c),taskOverlap=overlap(task,doc),outputSupport=overlap(outputs,doc),inputSupport=overlap(inputs,doc),apiEvidence=[...API_TOKENS].filter(t=>doc.has(t)).length,publicNoauth=explicitNoAuth(p)&&String(p.https||"").toLowerCase()!=="false"?1:0,noiseHits=[...NOISE_TOKENS].filter(t=>doc.has(t)).length,noisePenalty=(taskOverlap===0&&outputSupport===0&&inputSupport===0?1:0)+(noiseHits>0&&taskOverlap===0?1:0),total=taskOverlap*PROVIDER_WEIGHTS_5B3.task_overlap+outputSupport*PROVIDER_WEIGHTS_5B3.output_support+inputSupport*PROVIDER_WEIGHTS_5B3.input_support+apiEvidence*PROVIDER_WEIGHTS_5B3.api_evidence+publicNoauth*PROVIDER_WEIGHTS_5B3.public_noauth-noisePenalty*PROVIDER_WEIGHTS_5B3.noise_penalty;return {candidate_id:p.candidate_id,total,task_overlap:taskOverlap,output_support:outputSupport,input_support:inputSupport,api_evidence:apiEvidence,public_noauth:publicNoauth,noise_penalty:noisePenalty,distinctive_task_anchors:taskOverlap,normalized_url:String(p.link||"").trim().toLowerCase()}}
export function deterministicProviderSelection5B3(c:any,broad:ProviderCandidate[]){const scored=broad.map(p=>({p,s:scoreProvider5B3(c,p)}));scored.sort((a,b)=>b.s.total-a.s.total||b.s.distinctive_task_anchors-a.s.distinctive_task_anchors||b.s.output_support-a.s.output_support||a.s.normalized_url.length-b.s.normalized_url.length||a.s.normalized_url.localeCompare(b.s.normalized_url)||a.p.candidate_id.localeCompare(b.p.candidate_id));let tieBreaks=0;for(let i=1;i<scored.length;i++)if(scored[i-1].s.total===scored[i].s.total)tieBreaks++;const selected=scored.slice(0,RERANK_TOP_K),selection:RerankSelection={case_id:c.case_id,selected:selected.map(({p,s})=>({candidate_id:p.candidate_id,reason:`deterministic_5b3:score=${s.total};task=${s.task_overlap};outputs=${s.output_support};inputs=${s.input_support};api=${s.api_evidence};public=${s.public_noauth};noise=${s.noise_penalty}`}))},ordering=scored.map(({p,s},i)=>({rank:i+1,candidate_id:p.candidate_id,total:s.total,task_overlap:s.task_overlap,output_support:s.output_support,input_support:s.input_support,api_evidence:s.api_evidence,public_noauth:s.public_noauth,noise_penalty:s.noise_penalty,url_fingerprint:sha(s.normalized_url)})),fingerprint=sha(ordering);return {selection,ordering,fingerprint,metrics:{deterministicProviderCandidates5b3:broad.length,deterministicProviderSelected5b3:selected.length,deterministicProviderTaskOverlap5b3:scored.reduce((n,x)=>n+x.s.task_overlap,0),deterministicProviderOutputSupport5b3:scored.reduce((n,x)=>n+x.s.output_support,0),deterministicProviderApiEvidence5b3:scored.reduce((n,x)=>n+x.s.api_evidence,0),deterministicProviderNoisePenalties5b3:scored.reduce((n,x)=>n+x.s.noise_penalty,0),deterministicProviderTieBreaks5b3:tieBreaks,stochasticProviderRerankerCalls5b3:0,providerOrderingFingerprintCount5b3:1,providerOrderingNondeterminismRejects5b3:0}}}
export function providerOrderingDeterminism5B3(c:any,broad:ProviderCandidate[]){const a=deterministicProviderSelection5B3(c,broad),b=deterministicProviderSelection5B3(c,broad);return {ok:a.fingerprint===b.fingerprint&&JSON.stringify(a.ordering)===JSON.stringify(b.ordering),fingerprint:a.fingerprint}}
