import type {RecoveryLedger} from "./experiment3yrCore.js";
import {fetchTextSafeR2} from "./experiment3yr2Core.js";
import {FOUR_A_BUDGET} from "./experiment4aCore.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {FOUR_AP1_MAX_OBSERVED_FIELDS,fourAp1Sha,type P1ObservedField,type P1ProbeProof,type P1ProbeRecord,type P1RequestHypothesis} from "./experiment4ap1Model.js";

type CachedNetwork={ok:true;final_url:string;content_type:string;text:string}|{ok:false;error:string};
const CACHE=new Map<string,CachedNetwork>();
let cacheHits=0,networkFetches=0,duplicateNetworkFetches=0;
export function resetProbeCache4L(){CACHE.clear();cacheHits=0;networkFetches=0;duplicateNetworkFetches=0}
export function probeCacheMetrics4L(){return {probeCacheHits:cacheHits,probeNetworkFetches:networkFetches,duplicateProbeNetworkFetches:duplicateNetworkFetches}}
function scalar(value:any){return value===null||["string","number","boolean"].includes(typeof value)}
function sample(value:any){if(value===null)return "null";const text=String(value);return text.length<=120?text:`${text.slice(0,117)}...`}
function norm(value:any){return String(value??"").trim().toLowerCase()}
function collect(value:any,prefix="",depth=0,out:{path:string;value:any}[]=[]){if(depth>7||out.length>=FOUR_AP1_MAX_OBSERVED_FIELDS*3)return out;if(scalar(value)){if(prefix)out.push({path:prefix,value});return out}if(Array.isArray(value)){if(value.length)collect(value[0],prefix?`${prefix}.0`:"0",depth+1,out);return out}if(value&&typeof value==="object")for(const [key,child] of Object.entries(value)){collect(child,prefix?`${prefix}.${key}`:key,depth+1,out);if(out.length>=FOUR_AP1_MAX_OBSERVED_FIELDS*3)break}return out}
function errorEnvelope(body:any){if(!body||typeof body!=="object"||Array.isArray(body))return false;if(body.success===false)return true;if(typeof body.status==="number"&&body.status>=400)return true;if(typeof body.statusCode==="number"&&body.statusCode>=400)return true;const keys=Object.keys(body).map(x=>x.toLowerCase()),has=keys.includes("error")||keys.includes("errors")||keys.includes("err"),sub=keys.some(k=>!["error","errors","err","message","status","statuscode","code","success"].includes(k));return has&&!sub}
function fields(h:P1RequestHypothesis,body:any,build:Record<string,any>,bodyFingerprint:string){return collect(body).slice(0,FOUR_AP1_MAX_OBSERVED_FIELDS).map(({path,value}):P1ObservedField=>{const relations:string[]=[];for(const [name,inputValue] of Object.entries(build)){if(scalar(inputValue)&&norm(value)===norm(inputValue))relations.push(`TASK_INPUT:${name}:normalized_equal`);if(typeof value==="number"&&typeof inputValue==="number"&&value===inputValue)relations.push(`TASK_INPUT:${name}:numeric_equal`)}const leaf=path.split(".").filter(Boolean).at(-1)||path;return {id:`fld_${fourAp1Sha({hypothesis:h.id,path,bodyFingerprint}).slice(0,16)}`,path,leaf,tokens:lexicalTokensP1(leaf),sample_type:value===null?"null":typeof value,sample_value:sample(value),build_value_relations:[...new Set(relations)]}})}
async function network(url:string,ledger:RecoveryLedger){const prior=CACHE.get(url);if(prior){cacheHits++;return {entry:prior,cache_hit:true}}networkFetches++;let entry:CachedNetwork;try{const got=await fetchTextSafeR2(url,url,FOUR_A_BUDGET.max_bytes,ledger);entry={ok:true,final_url:got.final_url,content_type:got.content_type,text:got.text}}catch(e){entry={ok:false,error:String(e).replace(/^Error:\s*/,"")}}if(CACHE.has(url))duplicateNetworkFetches++;CACHE.set(url,entry);return {entry,cache_hit:false}}
export async function probeHypothesis4L(hypothesis:P1RequestHypothesis,build:Record<string,any>,ledger:RecoveryLedger):Promise<{proof:P1ProbeProof;cache_hit:boolean;network_fetch:boolean}>{
  const requested_at=new Date().toISOString();let requested_url="";
  try{requested_url=compileRequestHypothesisP1(hypothesis,build);const got=await network(requested_url,ledger);if(!got.entry.ok)throw new Error(got.entry.error);const bytes=Buffer.byteLength(got.entry.text);let body:any;try{body=JSON.parse(got.entry.text)}catch{throw new Error("probe_response_not_json")}if(body===null||body===undefined)throw new Error("probe_response_empty");if(errorEnvelope(body))throw new Error("probe_error_envelope");const bodyFingerprint=fourAp1Sha(got.entry.text),observed=fields(hypothesis,body,build,bodyFingerprint);if(!observed.length)throw new Error("probe_no_scalar_fields");const schemaFingerprint=fourAp1Sha(observed.map(f=>({path:f.path,type:f.sample_type}))),record:P1ProbeRecord={hypothesis_id:hypothesis.id,disposition:"success",requested_url,requested_at,final_url:got.entry.final_url,content_type:got.entry.content_type,response_body_fingerprint:bodyFingerprint,schema_fingerprint:schemaFingerprint,observed_fields:observed,observed_path_count:observed.length,bytes,error:null};return {proof:{hypothesis,record},cache_hit:got.cache_hit,network_fetch:!got.cache_hit}}
  catch(error){const record:P1ProbeRecord={hypothesis_id:hypothesis.id,disposition:"rejected",requested_url,requested_at,final_url:null,content_type:null,response_body_fingerprint:null,schema_fingerprint:null,observed_fields:[],observed_path_count:0,bytes:0,error:String(error).replace(/^Error:\s*/,"")};return {proof:{hypothesis,record},cache_hit:CACHE.has(requested_url),network_fetch:requested_url?false:false}}
}
