import type {Config} from "./config/index.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,type P1ProbeProof} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4Q} from "./experiment4qRequest.js";
import type {RelationalSummary4O} from "./experiment4oRelational.js";
import {probeHypothesis4R,probeCacheMetrics4R} from "./experiment4rProbe.js";
import {allowedInputSources4R,deterministicPartialProjection4R,materialize4R} from "./experiment4rCore.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(r=>[r.case_id,r]));
function overlap(a:string,b:string){const x=new Set(lexicalTokensP1(a)),y=new Set(lexicalTokensP1(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function fieldPacket(p:P1ProbeProof,req:readonly string[]){return [...p.record.observed_fields].map(field=>({field,score:Math.max(0,...req.map(o=>overlap(o,field.leaf)))*100+field.build_value_relations.length*20-Math.min(30,field.path.split(".").length)})).sort((a,b)=>b.score-a.score||a.field.path.length-b.field.path.length).slice(0,48).map(r=>r.field)}
async function callStructured(config:Config,payload:any,jsonSchema:any){const started=Date.now();const response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:"Resolve ONLY the unresolved outputs. Locked deterministic bindings are immutable and are not choices. Map each unresolved output only to supplied observed field IDs or explicitly permitted task inputs. Never invent fields, URLs, indices, credentials, labels, or alternate response formats."},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:jsonSchema}})});const latency_ms=Date.now()-started,text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}return {status:response.status,ok:response.ok,latency_ms,usage:body?.usage??null,raw:body?.choices?.[0]?.message?.content??null,refusal:body?.choices?.[0]?.message?.refusal??null}}
function schema(proof:P1ProbeProof,inputs:readonly string[],unresolved:readonly string[]){const fields=fieldPacket(proof,unresolved),properties:any={};for(const output of unresolved){const sources=[...fields.map(f=>f.id),...allowedInputSources4R(output,inputs).map(i=>`TASK_INPUT:${i}`)];properties[output]={type:"object",additionalProperties:false,properties:{source_id:{type:"string",enum:sources.length?sources:["NO_VALID_SOURCE"]}},required:["source_id"]}}return {name:"missing_4r_unresolved_mapping",strict:true,schema:{type:"object",additionalProperties:false,properties:{decision:{type:"string",enum:["SELECT","REJECT"]},output_bindings:{type:"object",additionalProperties:false,properties,required:[...unresolved]},reason:{type:"string"}},required:["decision","output_bindings","reason"]}}}
function fallbackProjection(caseId:string,proof:P1ProbeProof,raw:string,unresolved:string[]){const c=BY_ID[caseId],v=JSON.parse(raw),projection:any={};if(v.decision!=="SELECT")return null;for(const output of unresolved){const source=String(v.output_bindings?.[output]?.source_id||"");if(source.startsWith("TASK_INPUT:")){const input=source.slice(11);if(!allowedInputSources4R(output,c.input_names).includes(input))throw new Error("4r_forbidden_input_source");projection[output]={op:"INPUT",name:input};continue}const f=proof.record.observed_fields.find(x=>x.id===source);if(!f)throw new Error("4r_field_invalid");projection[output]={op:"FIELD",path:f.path}}return projection}
function trace(h:any){return String(h?.proof_type||"").startsWith("4n_executed_trace_")}
function documentedRole(h:any){return String(h?.proof_type||"").startsWith("4n_executed_trace_documented_role_")}
function delta(a:Record<string,number>,b:Record<string,number>,k:string){return Number(b[k]||0)-Number(a[k]||0)}
export async function synthesize4r(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){const c=BY_ID[provider.case_id];if(!c)throw new Error(`4r_unknown_case:${provider.case_id}`);const request=await prepareRequestGraph4Q(evidence,provider.case_id,provider.candidate_id,ledger),rows:any[]=[],cacheBefore=probeCacheMetrics4R();for(const h of request.probe_packet.slice(0,FOUR_AP1_MAX_PROBES_PER_PROVIDER)){const got=await probeHypothesis4R(h,c.build,ledger);rows.push(got)}const cacheAfter=probeCacheMetrics4R(),successful=rows.filter(r=>r.proof.record.disposition==="success"),decodeMetrics=rows.reduce((a,r)=>{for(const [k,v] of Object.entries(r.decode_metrics||{}))a[k]=(a[k]||0)+Number(v||0);return a},{} as Record<string,number>),relMetrics=successful.reduce((a,r)=>{for(const [k,v] of Object.entries(r.relational_summary?.metrics||{}))a[k]=(a[k]||0)+Number(v||0);return a},{} as Record<string,number>),probeMetrics={schemaProbeCalls:rows.length,schemaProbe2xxJson:successful.filter(r=>r.structured_format==="json").length,schemaProbe2xxStructured:successful.length,schemaProbeRejected:rows.length-successful.length,schemaProbeBytes:successful.reduce((n,r)=>n+r.proof.record.bytes,0),executedTraceProbeCalls:rows.filter(r=>trace(r.proof.hypothesis)).length,executedTraceProbe2xxJson:successful.filter(r=>trace(r.proof.hypothesis)&&r.structured_format==="json").length,executedTraceProbe2xxStructured:successful.filter(r=>trace(r.proof.hypothesis)).length,executedTraceDocumentedRoleProbeCalls:rows.filter(r=>documentedRole(r.proof.hypothesis)).length,executedTraceDocumentedRoleProbe2xxJson:successful.filter(r=>documentedRole(r.proof.hypothesis)&&r.structured_format==="json").length,executedTraceDocumentedRoleProbe2xxStructured:successful.filter(r=>documentedRole(r.proof.hypothesis)).length,...decodeMetrics,...relMetrics,probeCacheHits:delta(cacheBefore,cacheAfter,"probeCacheHits"),probeNetworkFetches:delta(cacheBefore,cacheAfter,"probeNetworkFetches"),duplicateProbeNetworkFetches:delta(cacheBefore,cacheAfter,"duplicateProbeNetworkFetches")},attribution={request_inventory_count:request.hypotheses.length,alignment_metrics:request.metrics,operation_semantics_fingerprint:request.semantics.fingerprint,request_graph_fingerprint:request.graph_fingerprint,request_hypotheses:request.probe_packet,probe_records:successful.map(r=>r.proof.record),...probeMetrics,noIrOperation:request.metrics.noIrOperation,irOperationUnusable:request.metrics.irOperationUnusable};if(!successful.length)return {http_status:0,http_ok:true,parsed_json:{case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:"4R_PROBE_FAILED"},parse_error:null,usage:null,latency_ms:0,probe_proof:null,planner_skipped:true,deterministic_mapping:false,row_lookup_selected:false,compositional_locked_bindings:0,exact_relational_label_selections:0,structured_format:null,...attribution};
let best:any=null;for(const row of successful){const d=deterministicPartialProjection4R(row.proof,row.relational_summary,c.input_names,c.required);if(!best||d.locked.length>best.d.locked.length||d.locked.length===best.d.locked.length&&row.structured_format==="json"&&best.row.structured_format!=="json")best={row,d};if(!d.unresolved.length){const m=materialize4R(provider.case_id,provider.candidate_id,row.proof,d.projection,row.relational_summary);return {http_status:0,http_ok:true,parsed_json:m.raw,parse_error:null,usage:null,latency_ms:0,probe_proof:row.proof,operation_proof:m.proof,planner_skipped:true,deterministic_mapping:true,row_lookup_selected:d.rowLookups>0,identity_projection_selected:d.identityInputs>0,selected_from_trace:trace(row.proof.hypothesis),selected_from_documented_role:documentedRole(row.proof.hypothesis),compositional_locked_bindings:d.locked.length,exact_relational_label_selections:d.exactRelationalLabels,structured_format:row.structured_format,...attribution}}}
const {row,d}=best,call=await callStructured(config,{case:{case_id:provider.case_id,intent:c.intent,input_names:c.input_names,required_outputs:c.required},locked_projection:d.projection,unresolved_outputs:d.unresolved,observed_fields:fieldPacket(row.proof,d.unresolved).map(f=>({field_id:f.id,path:f.path,leaf:f.leaf,sample_type:f.sample_type}))},schema(row.proof,c.input_names,d.unresolved));let parsed_json:any=null,parse_error:string|null=null;try{if(typeof call.raw!=="string")throw new Error("4r_planner_missing_content");const extra=fallbackProjection(provider.case_id,row.proof,call.raw,d.unresolved);if(!extra)parsed_json={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:"4R_MAPPING_REJECT"};else{const projection={...d.projection,...extra},m=materialize4R(provider.case_id,provider.candidate_id,row.proof,projection,row.relational_summary);parsed_json=m.raw}}catch(e){parse_error=String(e).replace(/^Error:\s*/,"")}return {http_status:call.status,http_ok:call.ok,raw_content:call.raw,refusal:call.refusal,parsed_json,parse_error,usage:call.usage,latency_ms:call.latency_ms,probe_proof:row.proof,operation_proof:null,planner_skipped:false,deterministic_mapping:false,row_lookup_selected:d.rowLookups>0,identity_projection_selected:d.identityInputs>0,selected_from_trace:trace(row.proof.hypothesis),selected_from_documented_role:documentedRole(row.proof.hypothesis),compositional_locked_bindings:d.locked.length,exact_relational_label_selections:d.exactRelationalLabels,locked_binding_mutations:0,structured_format:row.structured_format,...attribution}}
