import {mkdir,writeFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {CASES,MAX_REGISTRY_BYTES,MAX_SPEC_BYTES,PLANNER_CANDIDATE_LIMIT,REGISTRY_TOP_K,REGISTRY_URL,SPEC_FETCH_LIMIT,candidateSummary,casesContainNoMappings,flattenRegistry,parseContractDocument,rankRegistryRecords,sha,validateSpecUrlSyntax,type CaseDef,type LiveContract,type RegistryRecord} from "./experiment3qCore.js";
import {fetchTextBounded} from "./experiment3qNetwork.js";
import {EXEC_CASES,compileRequest,executionReadiness,induceProjection,makeRecipe,project,semanticValidate,validateBindingProgram,type Recipe} from "./experiment3rCore.js";
import {callProcurementPlanner,parseProcurementPlan} from "./experiment3rPlanner.js";
import {MAX_SUPPLIERS_PER_CASE,buildSupplierCandidates,canonicalBaseFromRedirect,recipeHas3SFingerprintEvidence,runNegativeControls,verificationTraceFingerprint} from "./experiment3sCore.js";
import {verifyJsonRequest} from "./experiment3sNetwork.js";

const OUTDIR="results/experiment-3s",MAX_EXEC_BYTES=4*1024*1024;
let registryFetchCalls=0,specFetchCalls=0,procurementPlannerCalls=0,procurementRepairCalls=0,projectionInductionCalls=0;
const discoveryPlannerCalls=0,supplierSelectionCalls=0,credentialsSupplied=0,arbitraryCodeExecuted=0,nonGetSuppliersExecuted=0,authRequiredSuppliersExecuted=0,unsafeRedirectsFollowed=0;

async function fetchRegistry(){registryFetchCalls++;const {text,content_type}=await fetchTextBounded(REGISTRY_URL,MAX_REGISTRY_BYTES,"application/json");const raw=JSON.parse(text);return {records:flattenRegistry(raw),content_type,registry_fingerprint:sha(text),raw_entry_count:Object.keys(raw).length};}
async function fetchCaseContracts(c:CaseDef,ranked:RegistryRecord[],cache:Map<string,{contract:LiveContract|null;evidence:any}>){const contracts:LiveContract[]=[],evidence:any[]=[];const unique=ranked.filter((r,i,a)=>a.findIndex(x=>x.spec_url===r.spec_url)===i).slice(0,SPEC_FETCH_LIMIT);for(const record of unique){let cached=cache.get(record.spec_url);if(!cached){specFetchCalls++;try{const syntax=validateSpecUrlSyntax(record.spec_url);if(!syntax.ok)throw new Error(`spec_url_${syntax.reason}`);const {text,content_type}=await fetchTextBounded(record.spec_url,MAX_SPEC_BYTES,"application/vnd.oai.openapi+json, application/json");const contract=parseContractDocument(record,text);cached={contract,evidence:{api_key:record.api_key,spec_url:record.spec_url,status:"ok",content_type,operations:contract.operations.length,spec_fingerprint:contract.spec_fingerprint}};}catch(e){cached={contract:null,evidence:{api_key:record.api_key,spec_url:record.spec_url,status:"error",error:String(e)}};}cache.set(record.spec_url,cached);}evidence.push({...cached.evidence,case_id:c.case_id});if(cached.contract)contracts.push({...cached.contract,registry_rank:record.registry_rank,registry_score:record.registry_score});}return {contracts,evidence};}
function classifyFailure(error:string){const s=error.toLowerCase();if(s.includes("dns_unreachable")||s.includes("enotfound"))return "dns_unreachable";if(s.includes("redirect"))return "redirect_rejected";if(s.includes("non_json"))return "non_json";if(s.includes("semantic"))return "semantic_mismatch";if(s.includes("http_error")||s.includes("http_"))return "http_error";return "http_error";}

async function procure(config:any,c:CaseDef,execCase:any,supplier:any,evidence:any[]){const readiness=executionReadiness(supplier.contract,supplier.candidate);if(!readiness.ready)return {status:"not_publicly_executable",readiness,plan:null,bindings:[],static_errors:readiness.errors};procurementPlannerCalls++;let attempt=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"initial");let parsed=parseProcurementPlan(attempt),plan=parsed.plan,stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};if(plan&&plan.candidate_id!==supplier.candidate.candidate_id)stat.errors.push("candidate_id_mismatch");evidence.push({case_id:c.case_id,supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,...attempt,validation_error:parsed.error,static_errors:stat.errors});if(parsed.error||stat.errors.length){procurementPlannerCalls++;procurementRepairCalls++;const previous=(parsed.error?[parsed.error]:stat.errors).join(",");const repair=await callProcurementPlanner(config,c,execCase,supplier.candidate,readiness,"repair",previous);parsed=parseProcurementPlan(repair);plan=parsed.plan;stat=plan?validateBindingProgram(plan,execCase,readiness):{errors:[parsed.error||"no_plan"],bindings:[]};if(plan&&plan.candidate_id!==supplier.candidate.candidate_id)stat.errors.push("candidate_id_mismatch");evidence.push({case_id:c.case_id,supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,...repair,validation_error:parsed.error,static_errors:stat.errors});}
  if(!plan||plan.decision!=="COMPILE"||stat.errors.length)return {status:"binding_reject",readiness,plan,bindings:stat.bindings,static_errors:stat.errors};return {status:"compiled",readiness,plan,bindings:stat.bindings,static_errors:[]};}

async function main(){await mkdir(OUTDIR,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");const started_at=new Date().toISOString(),controls=runNegativeControls(),controlMap=Object.fromEntries(controls.map(c=>[c.control,c])),specEvidence:any[]=[],plannerEvidence:any[]=[],caseEvidence:any[]=[],recipes:any[]=[];let registry:any={records:[],raw_entry_count:0},registryError:string|null=null;try{registry=await fetchRegistry();}catch(e){registryError=String(e);}const cache=new Map<string,{contract:LiveContract|null;evidence:any}>();
  if(!registryError)for(const c of CASES){const execCase=EXEC_CASES[c.case_id],ranked=rankRegistryRecords(c,registry.records),fetched=await fetchCaseContracts(c,ranked,cache);specEvidence.push(...fetched.evidence);const candidates=candidateSummary(c,fetched.contracts),suppliers=buildSupplierCandidates(candidates,fetched.contracts),attempts:any[]=[];let selected:any=null;
    for(const supplier of suppliers){const proc=await procure(config,c,execCase,supplier,plannerEvidence);if(proc.status!=="compiled"){attempts.push({supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,status:proc.status,readiness:proc.readiness,static_errors:proc.static_errors});continue;}try{const r=proc.readiness;if(!r.server_base||!r.allowed_host)throw new Error("missing_ready_base");const requestUrl=compileRequest(r.server_base,r.allowed_host,supplier.candidate.path,r.params,proc.bindings,execCase.build);const verified=await verifyJsonRequest(requestUrl,MAX_EXEC_BYTES);projectionInductionCalls++;const projection=induceProjection(verified.body,execCase,execCase.build),out=project(verified.body,projection);if(!semanticValidate(execCase,execCase.build,out))throw new Error("semantic_mismatch");let canonicalBase=r.server_base,canonicalHost=r.allowed_host;if(verified.trace.redirect_used){canonicalBase=canonicalBaseFromRedirect(verified.final_url,supplier.candidate.path);canonicalHost=new URL(verified.final_url).hostname;}const descriptor={case_id:c.case_id,api_key:supplier.contract.api_key,title:supplier.contract.title,spec_url:supplier.contract.spec_url,spec_fingerprint:supplier.contract.spec_fingerprint,operation_path:supplier.candidate.path,descriptor_fingerprint:sha({case_id:c.case_id,api_key:supplier.contract.api_key,spec_fingerprint:supplier.contract.spec_fingerprint,path:supplier.candidate.path})};let recipe:any=makeRecipe(execCase,descriptor,{...r,server_base:canonicalBase,allowed_host:canonicalHost},proc.bindings,projection);const trace={supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,documented_base:r.server_base,canonical_base:canonicalBase,redirect_used:verified.trace.redirect_used,status:"verified_live",output_fingerprint:sha(out)};recipe={...recipe,supplier_rank:supplier.supplier_rank,verification_status:"verified_live",documented_execution_base:r.server_base,canonical_execution_base:canonicalBase,safe_redirect_used:verified.trace.redirect_used,verification_trace_fingerprint:verificationTraceFingerprint(trace)};recipe.recipe_fingerprint=sha({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);selected={supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,status:"verified_live",candidate:supplier.candidate,procurement_plan:proc.plan,output:out,projection,trace,recipe};attempts.push(selected);break;}catch(e){attempts.push({supplier_rank:supplier.supplier_rank,api_key:supplier.candidate.api_key,status:classifyFailure(String(e)),error:String(e),candidate:supplier.candidate,procurement_plan:proc.plan});}}
    caseEvidence.push({case_id:c.case_id,compatible_supplier_count:suppliers.length,suppliers:suppliers.map(s=>({rank:s.supplier_rank,api_key:s.candidate.api_key,path:s.candidate.path,score:s.candidate.score})),attempts,selected});}
  const before={registryFetchCalls,specFetchCalls,discoveryPlannerCalls,supplierSelectionCalls,procurementPlannerCalls,projectionInductionCalls},replay:any[]=[];for(const recipe of recipes){const execCase=EXEC_CASES[recipe.case_id];try{const url=compileRequest(recipe.canonical_execution_base,recipe.allowed_host,recipe.operation_path,recipe.params,recipe.bindings,execCase.replay);const verified=await verifyJsonRequest(url,MAX_EXEC_BYTES);if(verified.trace.redirect_used)throw new Error("replay_unexpected_redirect");const out=project(verified.body,recipe.projection);if(!semanticValidate(execCase,execCase.replay,out))throw new Error("semantic_mismatch");replay.push({case_id:recipe.case_id,api_key:recipe.api_key,success:true,output:out,recipe_fingerprint:recipe.recipe_fingerprint});}catch(e){replay.push({case_id:recipe.case_id,api_key:recipe.api_key,success:false,error:String(e),recipe_fingerprint:recipe.recipe_fingerprint});}}
  const replayDeltas={registry_fetch_calls:registryFetchCalls-before.registryFetchCalls,spec_fetch_calls:specFetchCalls-before.specFetchCalls,discovery_planner_calls:discoveryPlannerCalls-before.discoveryPlannerCalls,supplier_selection_calls:supplierSelectionCalls-before.supplierSelectionCalls,procurement_planner_calls:procurementPlannerCalls-before.procurementPlannerCalls,projection_induction_calls:projectionInductionCalls-before.projectionInductionCalls};const successful=caseEvidence.filter(x=>x.selected),fallbackCases=successful.filter(x=>x.selected.supplier_rank>1),multiCompatible=caseEvidence.filter(x=>x.compatible_supplier_count>=2),distinctProviders=new Set(successful.map(x=>x.selected.api_key)).size,replaySuccess=replay.filter(x=>x.success),replayRate=recipes.length?replaySuccess.length/recipes.length:0,controlsExecuted=controls.filter(c=>c.executed).length,controlsVerified=controls.filter(c=>c.executed&&c.rejected).length,fingerprintEvidence=recipeHas3SFingerprintEvidence(recipes);
  const unknownOperationsAccepted=controlMap.operation_absent_from_contract?.rejected?0:1,undeclaredParamsAccepted=controlMap.undeclared_bound_parameter?.rejected?0:1,invalidBindingsAccepted=(controlMap.missing_required_parameter?.rejected&&controlMap.direct_missing_input?.rejected&&controlMap.split_out_of_range?.rejected)?0:1,unsupportedTransformsAccepted=controlMap.unsupported_transform?.rejected?0:1,hostPolicyViolationsAccepted=(controlMap.non_https_execution_base?.rejected&&controlMap.ip_literal_execution_host?.rejected)?0:1;
  const supplierBreadthGate=multiCompatible.length>=2||(multiCompatible.length>=1&&fallbackCases.length>=1&&successful.length>=2);const metrics={cases:CASES.length,registry_entry_count:registry.raw_entry_count,registry_fetch_calls:registryFetchCalls,spec_fetch_calls:specFetchCalls,procurement_planner_calls:procurementPlannerCalls,procurement_repair_calls:procurementRepairCalls,projection_induction_calls:projectionInductionCalls,successful_cases:successful.length,distinct_selected_providers:distinctProviders,multi_compatible_cases:multiCompatible.length,fallback_cases:fallbackCases.length,persisted_recipes:recipes.length,replay_successes:replaySuccess.length,replay_success_rate:replayRate,replay_deltas:replayDeltas,negative_controls_executed:controlsExecuted,negative_controls_verified:controlsVerified,unknown_operations_accepted:unknownOperationsAccepted,undeclared_params_accepted:undeclaredParamsAccepted,invalid_typed_bindings_accepted:invalidBindingsAccepted,unsupported_transforms_accepted:unsupportedTransformsAccepted,auth_required_suppliers_executed:authRequiredSuppliersExecuted,non_get_suppliers_executed:nonGetSuppliersExecuted,unsafe_redirects_followed:unsafeRedirectsFollowed,host_policy_violations_accepted:hostPolicyViolationsAccepted,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted,fingerprint_evidence:fingerprintEvidence};
  const gates={live_registry_fetched:!registryError&&registry.raw_entry_count>=1,registry_at_least_1000_entries:registry.raw_entry_count>=1000,zero_case_source_mappings:casesContainNoMappings(),supplier_breadth_or_fallback:supplierBreadthGate,at_least_2_verified_live_cases:successful.length>=2,at_least_2_distinct_selected_providers:distinctProviders>=2,actual_fallback_demonstrated:fallbackCases.length>=1,at_least_2_static_compiled_selected:successful.length>=2,at_least_2_live_semantic_successes:successful.length>=2,at_least_2_distinct_provider_recipes:recipes.length>=2&&new Set(recipes.map(r=>r.api_key)).size>=2,replay_100_percent:recipes.length>=2&&replayRate===1,replay_all_control_calls_zero:Object.values(replayDeltas).every(v=>v===0),all_15_negative_controls_verified:controlsExecuted===15&&controlsVerified===15,unknown_operations_zero:unknownOperationsAccepted===0,undeclared_params_zero:undeclaredParamsAccepted===0,invalid_typed_bindings_zero:invalidBindingsAccepted===0,unsupported_transforms_zero:unsupportedTransformsAccepted===0,auth_required_executed_zero:authRequiredSuppliersExecuted===0,non_get_executed_zero:nonGetSuppliersExecuted===0,unsafe_redirects_zero:unsafeRedirectsFollowed===0,host_policy_zero:hostPolicyViolationsAccepted===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,fingerprint_evidence_non_vacuous:fingerprintEvidence};const formal_decision=Object.values(gates).every(Boolean)?"GO_EXECUTION_VERIFIED_CAPABILITY_PROCUREMENT":"REASSESS_EXECUTION_VERIFIED_CAPABILITY_PROCUREMENT";const report={experiment:"3S",title:"Execution-Verified Capability Procurement",started_at,finished_at:new Date().toISOString(),formal_decision,registry:{url:REGISTRY_URL,error:registryError,entry_count:registry.raw_entry_count},limits:{registry_top_k:REGISTRY_TOP_K,spec_fetch_limit_per_case:SPEC_FETCH_LIMIT,planner_candidate_limit:PLANNER_CANDIDATE_LIMIT,max_suppliers_per_case:MAX_SUPPLIERS_PER_CASE},metrics,gates,cases:caseEvidence,replay,negative_controls:controls};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUTDIR}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUTDIR}/procurement-planner-evidence.json`,JSON.stringify(plannerEvidence,null,2));await writeFile(`${OUTDIR}/spec-evidence.json`,JSON.stringify(specEvidence,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));}
main().catch(async e=>{await mkdir(OUTDIR,{recursive:true});await writeFile(`${OUTDIR}/report.json`,JSON.stringify({experiment:"3S",formal_decision:"REASSESS_EXECUTION_VERIFIED_CAPABILITY_PROCUREMENT",fatal_error:String(e)},null,2));console.error(e);process.exitCode=1;});
