import type {DocEvidence} from "./experiment3wCore.js";
import {fourAp1Sha} from "./experiment4ap1Model.js";
import {compileDocumentationIr4F,type DocumentationIr,type IrOperation,type IrParameter,type IrSource} from "./experiment4fIr.js";

export type AuthClass="REQUIRED"|"OPTIONAL"|"RATE_LIMIT_UPGRADE"|"UNRELATED"|"UNKNOWN";
export type OperationForm="explicit_http"|"code_url"|"endpoint_label"|"table_or_link"|"openapi"|"relative"|"4f";
export type Operation4G=IrOperation&{form:OperationForm;auth_class:AuthClass};
export type SemanticIr4G={ir:DocumentationIr;operations:Operation4G[];parameters:IrParameter[];metrics:Record<string,number>;fingerprint:string};
const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const NAV=/(?:privacy|terms|legal|contact|about|login|signin|signup|register|account|blog|news|careers?|press|status|github\.com|twitter\.com|facebook\.com|linkedin\.com)/i;
const API_CONTEXT=/(?:api|endpoint|request|response|lookup|search|query|reference|developer|example|resource|object|product|vehicle|metadata|decode|estimate|retrieve|fetch)/i;
const REQUIRED_AUTH=/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth).{0,80}(?:required|must|need|mandatory)|(?:required|must|need|mandatory).{0,80}(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i;
const OPTIONAL_AUTH=/(?:anonymous|without authentication|no authentication|authentication is optional|api key is optional|optional api key|unauthenticated)/i;
const UPGRADE_AUTH=/(?:higher|increase|increased|more|premium).{0,50}(?:rate|limit|quota)|(?:rate|limit|quota).{0,50}(?:key|token|premium)/i;
function decode(s:string){return s.replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'")}
function strip(s:string){return decode(s.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function source(ev:DocEvidence,start:number,end:number):IrSource{return {evidence_id:ev.evidence_id,source_url:ev.resolved_url||ev.requested_url,start,end,expanded:(ev as any).source_kind==="4e_reference_expansion"||(ev as any).source_kind==="4f_reference_expansion"||(ev as any).source_kind==="4g_reference_expansion"}}
function safeAbs(raw:string){try{const u=new URL(decode(raw).replace(/[),;.'"]+$/g,""));if(u.protocol!=="https:"||u.username||u.password||NAV.test(`${u.hostname}${u.pathname}`))return null;return u}catch{return null}}
function normPath(s:string){return decode(s).replace(/\{\{([A-Za-z_][\w.-]*)\}\}/g,"{$1}").replace(/:([A-Za-z_][\w.-]*)/g,"{$1}").replace(/\[([A-Za-z_][\w.-]*)\]/g,"{$1}").replace(/<([A-Za-z_][\w.-]*)>/g,"{$1}")}
function params(target:string,sectionId:string,src:IrSource){const out:IrParameter[]=[];for(const m of normPath(target).matchAll(/\{([A-Za-z_][\w.-]*)\}/g)){const name=m[1];out.push({id:`par4g_${fourAp1Sha({e:src.evidence_id,s:src.start,n:name,p:1}).slice(0,16)}`,name,in:"path",required:true,auth_like:AUTH_NAME.test(name),example:null,description:"",section_id:sectionId,source:src})}let u:URL|null=null;try{u=new URL(normPath(target),"https://placeholder.invalid")}catch{}if(u)for(const [name,value] of u.searchParams)out.push({id:`par4g_${fourAp1Sha({e:src.evidence_id,s:src.start,n:name,q:1,v:value}).slice(0,16)}`,name,in:"query",required:null,auth_like:AUTH_NAME.test(name),example:value||null,description:"",section_id:sectionId,source:src});return out}
function authClass(context:string){if(REQUIRED_AUTH.test(context))return "REQUIRED" as const;if(OPTIONAL_AUTH.test(context))return "OPTIONAL" as const;if(UPGRADE_AUTH.test(context))return "RATE_LIMIT_UPGRADE" as const;if(/(?:api[_ -]?key|token|authorization|bearer|oauth|basic auth)/i.test(context))return "UNKNOWN" as const;return "UNRELATED" as const}
function localSection(ir:DocumentationIr,evId:string,pos:number){return ir.sections.filter(s=>s.source.evidence_id===evId&&s.start<=pos&&pos<s.end).sort((a,b)=>b.level-a.level||b.start-a.start)[0]||ir.sections.find(s=>s.source.evidence_id===evId)!}
function addOperation(out:Operation4G[],allParams:IrParameter[],ir:DocumentationIr,ev:DocEvidence,target:string,start:number,end:number,form:OperationForm,context:string){const abs=safeAbs(target),sec=localSection(ir,ev.evidence_id,start);if(!sec)return false;if(!abs&&!target.startsWith("/"))return false;if(!API_CONTEXT.test(`${sec.title} ${context}`)&&form!=="explicit_http"&&form!=="openapi")return false;const src=source(ev,start,end),path=abs?normPath(`${abs.pathname}${abs.search}`):normPath(target),ps=params(abs?abs.toString():target,sec.id,src);allParams.push(...ps);let baseId:string|null=null,rel:IrOperation["api_base_relation"]=null;if(abs){let b=ir.api_bases.find(x=>x.origin===abs.origin&&x.source.evidence_id===ev.evidence_id);if(!b){b={id:`base4g_${fourAp1Sha({e:ev.evidence_id,o:abs.origin}).slice(0,16)}`,origin:abs.origin,section_id:sec.id,source:src};ir.api_bases.push(b)}baseId=b.id;rel="same_section"}else{const chainIds=new Set<string>();let cur:any=sec;while(cur){chainIds.add(cur.id);cur=cur.parent_id?ir.sections.find(x=>x.id===cur.parent_id):null}const bs=ir.api_bases.filter(b=>b.source.evidence_id===ev.evidence_id&&chainIds.has(b.section_id));if(bs.length===1){baseId=bs[0].id;rel=bs[0].section_id===sec.id?"same_section":"ancestor_section"}}
const ac=authClass(`${sec.title} ${context}`),op:Operation4G={id:`op4g_${fourAp1Sha({e:ev.evidence_id,s:start,t:target,f:form}).slice(0,16)}`,method:"GET",raw_target:target,absolute_url:abs?.toString()??null,path,section_id:sec.id,title:sec.title,context:context.slice(0,2400),parameter_ids:ps.map(p=>p.id),auth_ids:[],api_base_id:baseId,api_base_relation:rel,source:src,form,auth_class:ac};out.push(op);return true}
export function compileEvidenceNativeSemantics4G(evidence:DocEvidence[]):SemanticIr4G{const ir=compileDocumentationIr4F(evidence),operations:Operation4G[]=ir.operations.map(o=>({...o,form:"4f",auth_class:authClass(`${o.title} ${o.context}`)})),allParams=[...ir.parameters];const seen=new Set(operations.map(o=>`${o.source.evidence_id}|${o.path}|${o.section_id}`));const metrics:any={operationFormsExplicitHttp:0,operationFormsCodeUrl:0,operationFormsEndpointLabel:0,operationFormsTableOrLink:0,operationFormsOpenApi:0,operationFormsRelative:0,operationsRejectedAsNavigation:0};for(const ev of evidence){if(ev.state!=="ok")continue;const raw=String(ev.text||"");const forms:{re:RegExp;form:OperationForm;idx:number}[]=[{re:/\bGET\s+(https:\/\/[^\s"'<>`]+|\/[^\s"'<>`]+)/gi,form:"explicit_http",idx:1},{re:/(?:Endpoint|Request\s+URL|API\s+URL|Example\s+Request)\s*[:=-]\s*(https:\/\/[^\s"'<>`]+|\/[^\s"'<>`]+)/gi,form:"endpoint_label",idx:1},{re:/<(?:code|pre)[^>]*>[\s\S]{0,500}?(https:\/\/[^\s"'<>`]+)[\s\S]{0,500}?<\/(?:code|pre)>/gi,form:"code_url",idx:1},{re:/<(?:td|th|a)\b[^>]*(?:href=["'](https:\/\/[^"']+)["'][^>]*)?>([\s\S]{0,800}?)<\/(?:td|th|a)>/gi,form:"table_or_link",idx:1},{re:/\b(https:\/\/[^\s"'<>`]+)/gi,form:"table_or_link",idx:1},{re:/\b(\/[A-Za-z0-9_{}\[\].:-]+(?:\/[A-Za-z0-9_{}\[\].:-]+)+(?:\?[^\s"'<>`]*)?)/gi,form:"relative",idx:1}];for(const f of forms)for(const m of raw.matchAll(f.re)){let target=m[f.idx]||"";if(f.form==="table_or_link"&&!target){const txt=strip(m[2]||"");const mm=txt.match(/https:\/\/\S+/);target=mm?.[0]||""}if(!target)continue;const pos=m.index??0,ctx=strip(raw.slice(Math.max(0,pos-500),Math.min(raw.length,pos+m[0].length+500)));if(safeAbs(target)===null&&target.startsWith("https://")){metrics.operationsRejectedAsNavigation++;continue}const before=operations.length;if(addOperation(operations,allParams,ir,ev,target,pos,pos+m[0].length,f.form,ctx)){const op=operations.at(-1)!;const key=`${op.source.evidence_id}|${op.path}|${op.section_id}`;if(seen.has(key))operations.pop();else{seen.add(key);if(f.form==="explicit_http")metrics.operationFormsExplicitHttp++;else if(f.form==="code_url")metrics.operationFormsCodeUrl++;else if(f.form==="endpoint_label")metrics.operationFormsEndpointLabel++;else if(f.form==="table_or_link")metrics.operationFormsTableOrLink++;else if(f.form==="openapi")metrics.operationFormsOpenApi++;else if(f.form==="relative")metrics.operationFormsRelative++}}else if(before===operations.length&&NAV.test(target))metrics.operationsRejectedAsNavigation++}}
metrics.authClassRequired=operations.filter(o=>o.auth_class==="REQUIRED").length;metrics.authClassOptional=operations.filter(o=>o.auth_class==="OPTIONAL").length;metrics.authClassRateLimitUpgrade=operations.filter(o=>o.auth_class==="RATE_LIMIT_UPGRADE").length;metrics.authClassUnrelated=operations.filter(o=>o.auth_class==="UNRELATED").length;metrics.authClassUnknown=operations.filter(o=>o.auth_class==="UNKNOWN").length;metrics.operationsFromExpandedEvidence=operations.filter(o=>o.source.expanded).length;metrics.operationApiBaseLinks=operations.filter(o=>!!o.api_base_id).length;metrics.relativeOperationsUnlinked=operations.filter(o=>o.path.startsWith("/")&&!o.api_base_id).length;return {ir,operations,parameters:allParams,metrics,fingerprint:fourAp1Sha({ir:ir.fingerprint,ops:operations.map(o=>[o.id,o.path,o.form,o.auth_class,o.api_base_id]),params:allParams.map(p=>[p.id,p.name,p.in,p.example])})}}
