import {createHash} from "node:crypto";
import type {DocEvidence} from "./experiment3wCore.js";
import {semanticTokens} from "./experiment3yr2Core.js";
import type {P1RequestHypothesis} from "./experiment4ap1Model.js";
import {outputCoverage5B} from "./experiment5bResponse.js";

const GENERIC_OUTPUT=new Set(["id","identifier","code","name","value","data","result","response","item","items","object","metadata"]);
const STRUCTURED=new Set(["json","openapi","swagger","schema","response","application","xml","yaml"]);
const uniq=(xs:string[])=>[...new Set(xs)];
const sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");
function pathText(raw:string){try{const u=new URL(raw);return `${u.pathname} ${Array.from(u.searchParams.keys()).join(" ")}`;}catch{return raw}}
function evidenceText(h:P1RequestHypothesis,evidence:DocEvidence[]){const ids=new Set(h.evidence_ids||[]),rows=evidence.filter(e=>ids.has(e.evidence_id));return `${h.source_operation_id} ${h.full_path} ${h.proof_type} ${(h.source_urls||[]).map(pathText).join(" ")} ${rows.map(r=>`${r.requested_url?pathText(r.requested_url):""} ${r.resolved_url?pathText(r.resolved_url):""} ${String(r.text||"").slice(0,12000)}`).join(" ")}`;}
function roleCoverage(required:readonly string[],text:string){const doc=new Set(semanticTokens(text));let roles=0,strong=0,weak=0;for(const role of required){const ts=uniq(semanticTokens(role)),distinct=ts.filter(t=>!GENERIC_OUTPUT.has(t));if(distinct.length){const hit=distinct.filter(t=>doc.has(t)).length;if(hit){roles++;strong+=hit}}else if(ts.some(t=>doc.has(t))){roles++;weak++}}return {roles,strong,weak,score:roles*100+strong*25+weak*5}}
function bindingScore(c:any,h:P1RequestHypothesis){const mapped=new Set(Object.values(h.input_bindings||{})),inputs=(c.input_names||[]) as string[],covered=inputs.filter((n:string)=>mapped.has(n)).length,unresolved=(h.slots||[]).filter(s=>s.required&&!h.input_bindings?.[s.id]&&!h.literal_bindings?.[s.id]).length;return covered*100-unresolved*300+(h.concrete_relation?20:0)}
function taskScore(c:any,text:string){const q=uniq(semanticTokens(String(c.intent||""))).filter(t=>!GENERIC_OUTPUT.has(t)),doc=new Set(semanticTokens(text));return q.filter(t=>doc.has(t)).length*20}
function structuredEvidence(text:string){const d=new Set(semanticTokens(text));return [...STRUCTURED].filter(t=>d.has(t)).length}
function complexity(h:P1RequestHypothesis){const pathSegments=String(h.full_path||"").split("/").filter(Boolean).length;return (h.slots||[]).length*10+Object.keys(h.literal_bindings||{}).length*5+pathSegments}
export type RequestUtility5B3={hypothesis_id:string;request_fingerprint:string;output_coverage:number;output_roles_supported:number;binding_score:number;task_score:number;structured_evidence:number;complexity:number;base_score:number;native:boolean};
export function requestUtility5B3(c:any,h:P1RequestHypothesis,evidence:DocEvidence[],nativeProof?:any):RequestUtility5B3{const text=evidenceText(h,evidence),nativeCoverage=nativeProof?.output_coverage_5b||null,coverage=nativeCoverage?{roles:Number(nativeCoverage.supported_roles?.length||0),score:Number(nativeCoverage.score||0)}:roleCoverage(c.required||c.required_output_leaf_names||[],text),requestFingerprint=sha({origin:h.origin,path:h.full_path,input_bindings:h.input_bindings,literal_bindings:h.literal_bindings});return {hypothesis_id:h.id,request_fingerprint:requestFingerprint,output_coverage:Number(coverage.score||0),output_roles_supported:Number(coverage.roles||0),binding_score:bindingScore(c,h),task_score:taskScore(c,text),structured_evidence:structuredEvidence(text),complexity:complexity(h),base_score:Number(h.score||0),native:!!nativeProof}}
export function rankRequestBeam5B3(c:any,hypotheses:P1RequestHypothesis[],evidence:DocEvidence[],nativeProofById:Map<string,any>,historicalPrimary?:P1RequestHypothesis){const rows=hypotheses.map(h=>({h,u:requestUtility5B3(c,h,evidence,nativeProofById.get(h.id))}));rows.sort((a,b)=>b.u.output_coverage-a.u.output_coverage||b.u.binding_score-a.u.binding_score||b.u.task_score-a.u.task_score||b.u.structured_evidence-a.u.structured_evidence||a.u.complexity-b.u.complexity||b.u.base_score-a.u.base_score||a.u.request_fingerprint.localeCompare(b.u.request_fingerprint));const ordering=rows.map((r,i)=>({rank:i+1,...r.u})),fingerprint=sha(ordering),primaryFp=historicalPrimary?requestUtility5B3(c,historicalPrimary,evidence,nativeProofById.get(historicalPrimary.id)).request_fingerprint:null,displaced=!!(primaryFp&&ordering.length&&ordering[0].request_fingerprint!==primaryFp);return {hypotheses:rows.map(r=>r.h),ordering,fingerprint,primary_displaced:displaced,metrics:{requestUtilityCandidates5b3:rows.length,requestUtilityOutputCoverage5b3:rows.reduce((n,r)=>n+r.u.output_coverage,0),requestUtilityBindingScore5b3:rows.reduce((n,r)=>n+r.u.binding_score,0),requestUtilityTaskScore5b3:rows.reduce((n,r)=>n+r.u.task_score,0),requestUtilityStructuredEvidence5b3:rows.reduce((n,r)=>n+r.u.structured_evidence,0),requestUtilityPrimaryDisplaced5b3:displaced?1:0,requestOrderingFingerprintCount5b3:1,requestOrderingNondeterminismRejects5b3:0}}}
export function requestOrderingDeterminism5B3(c:any,hypotheses:P1RequestHypothesis[],evidence:DocEvidence[],nativeProofById:Map<string,any>,historicalPrimary?:P1RequestHypothesis){const a=rankRequestBeam5B3(c,hypotheses,evidence,nativeProofById,historicalPrimary),b=rankRequestBeam5B3(c,hypotheses,evidence,nativeProofById,historicalPrimary);return {ok:a.fingerprint===b.fingerprint&&JSON.stringify(a.ordering)===JSON.stringify(b.ordering),fingerprint:a.fingerprint}}
