import {deriveExperiment4nSource} from "./experiment4nDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4o_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4oSource(source:string){
 let x=deriveExperiment4nSource(source);
 x=r(x,'import {compile4n as compile4ar,project4n as project4ar,scope4n as scope4ar,validate4n as validate4ar,validateProjected4n as validateProjected4ar} from "./experiment4nContract.js";','import {compile4o as compile4ar,project4o as project4ar,scope4o as scope4ar,validate4o as validate4ar,validateProjected4o as validateProjected4ar} from "./experiment4oContract.js";');
 x=r(x,'import {synthesize4n as synthesize4ar} from "./experiment4nPlanner.js";','import {synthesize4o as synthesize4ar} from "./experiment4oPlanner.js";');
 x=r(x,'const OUT="results/experiment-4n",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4o",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
 x=r(x,'documentationRouteProbeAttempts4n=0;',`documentationRouteProbeAttempts4n=0,relationalArrayCandidates4o=0,relationalRowSetsAccepted4o=0,relationalRowSetsRejectedInsufficientRows4o=0,relationalRowSetsRejectedNoSharedSchema4o=0,relationalLabelFieldCandidates4o=0,relationalValueFieldCandidates4o=0,relationalObservedLabels4o=0,relationalOutputMatches4o=0,rowLookupPlannerSelections4o=0,rowLookupValidatorRejects4o=0,forbiddenInputSourceCandidates4o=0,forbiddenInputSourceSelections4o=0;`);
 x=r(x,'executedTraceDocumentedRoleProbeCalls4n+=a.executedTraceDocumentedRoleProbeCalls||0;executedTraceDocumentedRoleProbe2xxJson4n+=a.executedTraceDocumentedRoleProbe2xxJson||0;',`executedTraceDocumentedRoleProbeCalls4n+=a.executedTraceDocumentedRoleProbeCalls||0;executedTraceDocumentedRoleProbe2xxJson4n+=a.executedTraceDocumentedRoleProbe2xxJson||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;relationalRowSetsAccepted4o+=a.relationalRowSetsAccepted||0;relationalRowSetsRejectedInsufficientRows4o+=a.relationalRowSetsRejectedInsufficientRows||0;relationalRowSetsRejectedNoSharedSchema4o+=a.relationalRowSetsRejectedNoSharedSchema||0;relationalLabelFieldCandidates4o+=a.relationalLabelFieldCandidates||0;relationalValueFieldCandidates4o+=a.relationalValueFieldCandidates||0;relationalObservedLabels4o+=a.relationalObservedLabels||0;forbiddenInputSourceCandidates4o+=a.forbidden_input_source_candidates||0;if(a.row_lookup_selected)rowLookupPlannerSelections4o++;`);
 x=r(x,'if(v.errors?.includes?.("4n_request_hypothesis_not_in_trace_graph"))validatorGraphMismatchRejects4h++;if(v.errors?.includes?.("4n_trace_origin_drift"))executedTraceOriginDriftRejects4n++;if(v.errors?.includes?.("4n_trace_request_mutation"))executedTraceRequestMutationRejects4n++;',`if(v.errors?.includes?.("4o_request_hypothesis_not_in_trace_graph"))validatorGraphMismatchRejects4h++;if(v.errors?.includes?.("4o_trace_origin_drift"))executedTraceOriginDriftRejects4n++;if(v.errors?.includes?.("4o_trace_request_mutation"))executedTraceRequestMutationRejects4n++;if(v.errors?.some?.((e:any)=>String(e).startsWith("4o_row_lookup_not_observed")||String(e).includes("numeric_index_row_lookup")))rowLookupValidatorRejects4o++;if(v.errors?.some?.((e:any)=>String(e).startsWith("4o_forbidden_input_source")))forbiddenInputSourceSelections4o++;`);
 x=r(x,'executedTraceDocumentedRoleConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_documented_role_")).length;',`executedTraceDocumentedRoleConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_documented_role_")).length,rowLookupConfirmedRecipes=recipes.filter(r=>Object.values(r.projection||{}).some((e:any)=>e?.op==="ROW_LOOKUP")).length,numericIndexedRowLookupRecipes=recipes.filter(r=>Object.values(r.projection||{}).some((e:any)=>e?.op==="ROW_LOOKUP"&&[e.array_path,e.label_field,e.value_field].some((p:string)=>/(^|\\.)\\d+(\\.|$)/.test(String(p||""))))).length;`);
 x=r(x,'executedTraceRequestMutationRejects:executedTraceRequestMutationRejects4n,documentationRouteProbeAttempts:documentationRouteProbeAttempts4n,probeCacheHits:probeCacheHits4l',`executedTraceRequestMutationRejects:executedTraceRequestMutationRejects4n,documentationRouteProbeAttempts:documentationRouteProbeAttempts4n,relationalArrayCandidates:relationalArrayCandidates4o,relationalRowSetsAccepted:relationalRowSetsAccepted4o,relationalRowSetsRejectedInsufficientRows:relationalRowSetsRejectedInsufficientRows4o,relationalRowSetsRejectedNoSharedSchema:relationalRowSetsRejectedNoSharedSchema4o,relationalLabelFieldCandidates:relationalLabelFieldCandidates4o,relationalValueFieldCandidates:relationalValueFieldCandidates4o,relationalObservedLabels:relationalObservedLabels4o,relationalOutputMatches:relationalOutputMatches4o,rowLookupPlannerSelections:rowLookupPlannerSelections4o,rowLookupValidatorRejects:rowLookupValidatorRejects4o,rowLookupConfirmedRecipes,numericIndexedRowLookupRecipes,forbiddenInputSourceCandidates:forbiddenInputSourceCandidates4o,forbiddenInputSourceSelections:forbiddenInputSourceSelections4o,probeCacheHits:probeCacheHits4l`);
 x=r(x,'executed_trace_documented_role_confirmed_recipe:executedTraceDocumentedRoleConfirmedRecipes>=1,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,',`executed_trace_documented_role_confirmed_recipe:executedTraceDocumentedRoleConfirmedRecipes>=1,row_lookup_confirmed_recipe:rowLookupConfirmedRecipes>=1,numeric_index_row_lookup_recipes_zero:numericIndexedRowLookupRecipes===0,forbidden_input_source_selections_zero:forbiddenInputSourceSelections4o===0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,`);
 x=x.replaceAll('4N_FIRST_CLASS_EXECUTED_TRACE:','4O_RELATIONAL_RESPONSE:').replaceAll('4N_SUCCESSFUL_PROBE_MAPPING_REJECT','4O_MAPPING_REJECT').replaceAll('GO_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH','GO_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION').replaceAll('REASSESS_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH','REASSESS_4O_RELATIONAL_RESPONSE_IR_KEYED_ROW_PROJECTION');
 x=r(x,'experiment:"4N",purpose:"development_first_class_executed_request_evidence_graph"','experiment:"4O",purpose:"development_relational_response_ir_keyed_row_projection"');
 x=r(x,'base_sha:"9d30929caec004ef4c5fc2bbf2afa4eafeb4ff26"','base_sha:"07997e9e791f159b118349ef55e5a45a1c92fa5e"');
 x=x.replaceAll('./experiment4nPlanner.ts','./experiment4oPlanner.ts').replaceAll('./experiment4nContract.ts','./experiment4oContract.ts').replaceAll('./experiment4nDerivation.ts','./experiment4oDerivation.ts');
 x=x.replace('plannerSource=(await readFile(new URL("./experiment4oPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nReference.ts",import.meta.url),"utf8"))','plannerSource=(await readFile(new URL("./experiment4oPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4oRelational.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))');
 return x;
}
