export const RECOVERY_GLOBALS_5B9='const recoveryMetrics5b9:any={selectedProviderAcquisitionStarved5b9:0,selectedProviderRecoveryActivated5b9:0,selectedProviderRecoverySkippedBudgetExhausted5b9:0,selectedProviderRecoverySkippedExecutableSurfacePresent5b9:0,httpsUpgradeCandidates5b9:0,httpsUpgradeFetches5b9:0,httpsUpgradeAccepted5b9:0,httpsUpgradeRejectedScope5b9:0,httpsUpgradeRecoveredOperations5b9:0,recoveryLinkCandidates5b9:0,recoveryLinkAccepted5b9:0,recoveryLinkRejectedScope5b9:0,recoveryLinkRejectedNoise5b9:0,recoveryLinkAlreadyFetched5b9:0,recoveryLinkOrderingFingerprintCount5b9:0,recoveryLinkOrderingNondeterminismRejects5b9:0,recoveryFetchAttempts5b9:0,recoveryFetchSuccesses5b9:0,recoveryFetchFailures5b9:0,recoveryStoppedOnExecutableSurface5b9:0,recoveryStoppedOnBudget5b9:0,recoveryExecutableOperationsAdded5b9:0,recoveryRequestHypothesesAdded5b9:0,recoveryDerivedHypothesesEnteredBeam5b9:0,maxDocumentationFetchesPerProvider5b9:0,maxRecoveryPlusOrdinaryDepth5b9:0};\nconst recoveryLineage5b9:any[]=[],providerFetchAudit5b9:any[]=[];\nfunction addRecoveryMetrics5b9(src:any){for(const [k,v] of Object.entries(src||{}))if(typeof v==="number")recoveryMetrics5b9[k]=(recoveryMetrics5b9[k]||0)+v;}';

export const RECOVERY_CRAWL_5B9=`async function crawl5b9(provider:Provider4A,ledger:RecoveryLedger,originalStart:string){
 const evidence:DocEvidence[]=[],frontier:any[]=[],queue:any[]=[{url:provider.start_url,depth:0,parent_evidence_ids:[] as string[]}],seen=new Set<string>(),depthByEvidence=new Map<string,number>(),lineages:any[]=[];
 let seq=0,fetchCount=0,recoveryFetchCount=0,recoveryActivated=false,becameExecutable=false;
 const maxPages=FOUR_A_BUDGET.max_doc_pages_per_provider,initialUpgrade=String(originalStart).startsWith("http://")?httpsUpgradeCandidate5B9(originalStart):null;
 if(String(originalStart).startsWith("http://")){recoveryMetrics5b9.httpsUpgradeCandidates5b9++;recoveryMetrics5b9.selectedProviderAcquisitionStarved5b9++;if(initialUpgrade){recoveryActivated=true;recoveryMetrics5b9.selectedProviderRecoveryActivated5b9++;}else recoveryMetrics5b9.httpsUpgradeRejectedScope5b9++;}
 const pushEvidence=(requested_url:string,resolved_url:string,content_type:string,text:string,state:"ok"|"error",depth:number,error?:string)=>{const evidence_id=provider.candidate_id+"-e"+String(++seq).padStart(2,"0");evidence.push({evidence_id,provider_candidate_id:provider.candidate_id,requested_url,resolved_url,verified_at:new Date().toISOString(),status:state==="ok"?200:0,content_type,body_fingerprint:state==="ok"?sha3yr(text):"",text,state,error});depthByEvidence.set(evidence_id,depth);return evidence_id;};
 const persistLineage=(reason:"https_upgrade"|"explicit_same_provider_link",candidate:any,item:any,fetchStatus:number,contentType:string,resultingEvidenceId:string,resultingBodyFingerprint:string,before:any,after:any,finalUrl:string)=>{const base:any={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,source_evidence_ids:candidate?[candidate.source_evidence_id]:[],source_body_fingerprints:candidate?[candidate.source_body_fingerprint]:[],candidate_url_fingerprint:candidate?.target_url_fingerprint??sha3yr(item.url),normalized_origin_fingerprint:sha3yr((()=>{try{return new URL(finalUrl||provider.start_url).origin.toLowerCase()}catch{return provider.start_url}})()),recovery_reason:reason,anchor_context_fingerprint:candidate?.anchor_context_fingerprint??null,recovery_utility_tuple:candidate?[candidate.score,candidate.reasons]:[0,["scheme_only_https_upgrade"]],recovery_ordering_fingerprint:candidate?.ordering_fingerprint??initialUpgrade?.fingerprint??"",fetch_status:fetchStatus,fetch_content_type:contentType,resulting_evidence_id:resultingEvidenceId,resulting_body_fingerprint:resultingBodyFingerprint,operation_inventory_before:before.get_operations,operation_inventory_after:after.get_operations,request_hypotheses_before:before.executable_hypotheses,request_hypotheses_after:after.executable_hypotheses,budget_slot_index:fetchCount};const row={...base,lineage_fingerprint:recoveryLineageFingerprint5B9(base)};lineages.push(row);recoveryLineage5b9.push(row);};
 const fetchOne=async(item:any,reason:null|"https_upgrade"|"explicit_same_provider_link",candidate:any=null)=>{if(fetchCount>=maxPages)return null;const before=recoverySurface5B9(evidence,provider);seen.add(item.url);fetchCount++;docFetches++;recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9=Math.max(recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9,Number(item.depth||0));if(reason){recoveryFetchCount++;recoveryMetrics5b9.recoveryFetchAttempts5b9++;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeFetches5b9++;}
  const traceStage=reason==="explicit_same_provider_link"?"REFERENCE_EXPANSION":"CRAWL",parentIds=reason==="explicit_same_provider_link"&&candidate?[candidate.source_evidence_id]:(item.parent_evidence_ids||[]);
  try{const got=await fetchDocTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:traceStage,parent_evidence_ids:parentIds},provider.start_url,item.url,MAX_BYTES,ledger),id=pushEvidence(item.url,got.final_url,got.content_type,got.text,"ok",item.depth);if(reason){recoveryMetrics5b9.recoveryFetchSuccesses5b9++;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeAccepted5b9++;const after=recoverySurface5B9(evidence,provider),opDelta=Math.max(0,after.get_operations-before.get_operations),hypDelta=Math.max(0,after.executable_hypotheses-before.executable_hypotheses);recoveryMetrics5b9.recoveryExecutableOperationsAdded5b9+=opDelta;recoveryMetrics5b9.recoveryRequestHypothesesAdded5b9+=hypDelta;if(reason==="https_upgrade")recoveryMetrics5b9.httpsUpgradeRecoveredOperations5b9+=opDelta;if(!before.executable_hypotheses&&after.executable_hypotheses){becameExecutable=true;recoveryMetrics5b9.recoveryStoppedOnExecutableSurface5b9++;}persistLineage(reason,candidate,item,200,got.content_type,id,sha3yr(got.text),before,after,got.final_url);}return {got,id};}
  catch(e){const id=pushEvidence(item.url,item.url,"","","error",item.depth,String(e));if(reason){recoveryMetrics5b9.recoveryFetchFailures5b9++;persistLineage(reason,candidate,item,0,"",id,"",before,before,item.url);}return null;}
 };
 while(queue.length&&fetchCount<maxPages){const item=queue.shift()!;if(item.depth>FOUR_A_BUDGET.max_doc_depth||seen.has(item.url))continue;const first=fetchCount===0&&!!initialUpgrade&&item.url===provider.start_url,result=await fetchOne(item,first?"https_upgrade":null);if(result&&/text\\/html/i.test(result.got.content_type)){const links=extractFrontierLinks(result.got.final_url,provider.start_url,result.got.text,result.id,scope4ar);frontier.push(...links);for(const link of links.filter((z:any)=>z.accepted).slice(0,16))if(item.depth+1<=FOUR_A_BUDGET.max_doc_depth&&!seen.has(link.target_url))queue.push({url:link.target_url,depth:item.depth+1,parent_evidence_ids:[result.id]});}}
 let origin:string|null=null;try{origin=new URL(provider.start_url).origin}catch{}
 if(origin){for(const path of STANDARD_SPEC_PATHS){if(fetchCount>=maxPages)break;const url=new URL(path,origin).toString();if(seen.has(url))continue;seen.add(url);fetchCount++;specProbeFetches++;docFetches++;recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9=Math.max(recoveryMetrics5b9.maxRecoveryPlusOrdinaryDepth5b9,1);try{const got=await fetchSpecTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"STANDARD_SPEC",parent_evidence_ids:[]},provider.start_url,url,MAX_BYTES,ledger),spec=parseOpenApiText(got.text);if(spec)pushEvidence(url,got.final_url,got.content_type,"Verified API specification at "+got.final_url+"\\n"+specSummary(spec,provider.case_id,got.final_url),"ok",1);else pushEvidence(url,got.final_url,got.content_type,"","error",1,"not_machine_readable_spec");}catch(e){pushEvidence(url,url,"","","error",1,String(e));}}}
 let surface=recoverySurface5B9(evidence,provider);
 if(!surface.executable_hypotheses&&!recoveryActivated){recoveryMetrics5b9.selectedProviderAcquisitionStarved5b9++;if(fetchCount<maxPages){recoveryActivated=true;recoveryMetrics5b9.selectedProviderRecoveryActivated5b9++;}else recoveryMetrics5b9.selectedProviderRecoverySkippedBudgetExhausted5b9++;}else if(surface.executable_hypotheses&&!recoveryActivated)recoveryMetrics5b9.selectedProviderRecoverySkippedExecutableSurfacePresent5b9++;
 while(recoveryActivated&&!surface.executable_hypotheses&&fetchCount<maxPages){const det=recoveryLinkOrderingDeterminism5B9(evidence,provider,seen,depthByEvidence);recoveryMetrics5b9.recoveryLinkOrderingFingerprintCount5b9++;if(!det.ok){recoveryMetrics5b9.recoveryLinkOrderingNondeterminismRejects5b9++;break}const built=buildRecoveryLinkQueue5B9(evidence,provider,seen,depthByEvidence);addRecoveryMetrics5b9({...built.metrics,recoveryLinkOrderingFingerprintCount5b9:0,recoveryLinkOrderingNondeterminismRejects5b9:0});const candidate=built.queue.find((z:any)=>z.depth<=FOUR_A_BUDGET.max_doc_depth);if(!candidate)break;await fetchOne({url:candidate.target_url,depth:candidate.depth,parent_evidence_ids:[candidate.source_evidence_id]},"explicit_same_provider_link",candidate);surface=recoverySurface5B9(evidence,provider);if(surface.executable_hypotheses)break;}
 if(recoveryActivated&&!surface.executable_hypotheses&&fetchCount>=maxPages)recoveryMetrics5b9.recoveryStoppedOnBudget5b9++;
 recoveryMetrics5b9.maxDocumentationFetchesPerProvider5b9=Math.max(recoveryMetrics5b9.maxDocumentationFetchesPerProvider5b9,fetchCount);providerFetchAudit5b9.push({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,ordinary_plus_recovery_fetches:fetchCount,recovery_fetches:recoveryFetchCount,max_depth:Math.max(0,...depthByEvidence.values()),recovery_activated:recoveryActivated,executable_surface:surface,lineage_fingerprints:lineages.map(x=>x.lineage_fingerprint)});
 return {evidence,frontier,recovery:{activated:recoveryActivated,became_executable:becameExecutable,lineages,summary:{fetches:fetchCount,recovery_fetches:recoveryFetchCount,surface}}};
}
`;
