import {mkdir,writeFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {PUBLIC_APIS_URL} from "./experiment3uCore.js";
import {resolveSelected,providerSelectionFingerprint} from "./experiment3vCore.js";
import {callProviderReranker,parseRerankAttempt} from "./experiment3vPlanner.js";
import {runNegativeControls as run3vControls} from "./experiment3vControls.js";
import {run3xControls} from "./experiment3xControls.js";
import {BLIND_CASES,BLIND_EXEC_CASES,sha3y} from "./experiment3yCore.js";
import {RecoveryLedger,derivedSafetyCounters,sha3yr} from "./experiment3yrCore.js";
import {fetchTextSafeR2,recoveredBroadRetrieveR2,safetyGateFromLedger} from "./experiment3yr2Core.js";
import {extractFrontierLinks,frontierFingerprint} from "./experiment3wrCore.js";
import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {compileIntegrationRequest,executeIntegrationProjection,integrationScopeAllowed,type IntegrationProvider,validateIntegrationContract,validateIntegrationOutput} from "./experiment3yiCore.js";
import {synthesizeIntegrationContract} from "./experiment3yiPlanner.js";

const OUT="results/experiment-3yi",FREEZE_SHA="6b79298feb6288f843e0c11c04cfbe7cd4a1a794",MAX_DOC_PAGES=8,MAX_DEPTH=2,MAX_BYTES=4*1024*1024;
let catalogFetches=0,rerankerCalls=0,docFetches=0,synthesisCalls=0,synthesisRepairs=0,liveCalls=0;

async function safeJson(url:string,ledger:RecoveryLedger){liveCalls++;const got=await fetchTextSafeR2(url,url,MAX_BYTES,ledger);let body:any;try{body=JSON.parse(got.text);}catch{throw new Error("response_not_json");}return {body,requested_at:new Date().toISOString(),body_fingerprint:sha3yr(got.text),final_url:got.final_url};}
async function crawl(provider:IntegrationProvider,ledger:RecoveryLedger){const evidence:DocEvidence[]=[],frontier:any[]=[],queue=[{url:provider.start_url,depth:0}],seen=new Set<string>();let seq=0;while(queue.length&&evidence.filter(e=>e.state==="ok").length<MAX_DOC_PAGES){const item=queue.shift()!;if(item.depth>MAX_DEPTH||seen.has(item.url))continue;seen.add(item.url);docFetches++;const evidence_id=`${provider.candidate_id}-e${String(++seq).padStart(2,"0")}`,at=new Date().toISOString();try{const got=await fetchTextSafeR2(provider.start_url,item.url,MAX_BYTES,ledger);const ev:DocEvidence={evidence_id,provider_candidate_id:provider.candidate_id,requested_url:item.url,resolved_url:got.final_url,verified_at:at,status:200,content_type:got.content_type,body_fingerprint:sha3yr(got.text),text:got.text,state:"ok"};evidence.push(ev);if(/text\/html/i.test(got.content_type)){const links=extractFrontierLinks(got.final_url,provider.start_url,got.text,evidence_id,integrationScopeAllowed);frontier.push(...links);for(const l of links.filter(x=>x.accepted).slice(0,12))if(item.depth+1<=MAX_DEPTH&&!seen.has(l.target_url))queue.push({url:l.target_url,depth:item.depth+1});}}catch(e){evidence.push({evidence_id,provider_candidate_id:provider.candidate_id,requested_url:item.url,resolved_url:item.url,verified_at:at,status:0,content_type:"",body_fingerprint:"",text:"",state:"error",error:String(e)});}}
 return {evidence,frontier};}
async function rerank(config:any,c:any,broad:any[],evidence:any[]){rerankerCalls++;let a=await callProviderReranker(config,c,broad,"initial"),parsed=parseRerankAttempt(a,broad,c.case_id);evidence.push({case_id:c.case_id,...a,error:parsed.error});if(parsed.error){rerankerCalls++;const b=await callProviderReranker(config,c,broad,"repair",parsed.error);parsed=parseRerankAttempt(b,broad,c.case_id);evidence.push({case_id:c.case_id,...b,error:parsed.error});}return parsed;}
async function synthesize(config:any,p:IntegrationProvider,docs:DocEvidence[],ledger:RecoveryLedger,evidence:any[]){synthesisCalls++;let a=await synthesizeIntegrationContract(config,p,docs,"initial"),v=a.parsed_json?validateIntegrationContract(a.parsed_json,p,docs,ledger):{errors:[a.parse_error||`planner_http_${a.http_status}`]};evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...a,static_errors:v.errors});if(a.parsed_json?.decision==="REJECT"&&!v.errors.length)return {contract:a.parsed_json,error:null};if(v.errors.length){synthesisCalls++;synthesisRepairs++;const b=await synthesizeIntegrationContract(config,p,docs,"repair",v.errors.join(","));v=b.parsed_json?validateIntegrationContract(b.parsed_json,p,docs,ledger):{errors:[b.parse_error||`planner_http_${b.http_status}`]};evidence.push({case_id:p.case_id,provider_candidate_id:p.candidate_id,...b,static_errors:v.errors});return {contract:v.errors.length?null:b.parsed_json,error:v.errors.join(",")||null};}return {contract:a.parsed_json,error:null};}
function sameRequired(a:any,b:any,required:readonly string[]){return required.every(k=>JSON.stringify(a[k])===JSON.stringify(b[k]));}

async function main(){await mkdir(OUT,{recursive:true});const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");const started_at=new Date().toISOString(),ledger=new RecoveryLedger(),rerankEvidence:any[]=[],synthesisEvidence:any[]=[],caseEvidence:any[]=[],recipes:any[]=[];catalogFetches++;const catalog=(await fetchTextSafeR2(PUBLIC_APIS_URL,PUBLIC_APIS_URL,MAX_BYTES,ledger)).text;const controls=[...(await run3vControls()).map(x=>({...x,source:"3v"})),...run3xControls().controls.map(x=>({...x,source:"3x"}))];
 for(const c of BLIND_CASES){const broad=recoveredBroadRetrieveR2(c as any,catalog),r=await rerank(config,c,broad,rerankEvidence);if(!r.selection){caseEvidence.push({case_id:c.case_id,status:"rerank_reject",error:r.error});continue;}const selected=resolveSelected(r.selection,broad as any),selectionFp=providerSelectionFingerprint(c as any,r.selection);let success:any=null;const attempts:any[]=[];for(const s of selected){if(!String(s.link).startsWith("https://")){attempts.push({candidate_id:s.candidate_id,name:s.name,status:"non_https_catalog_start"});continue;}const p:IntegrationProvider={case_id:c.case_id,candidate_id:s.candidate_id,name:s.name,start_url:s.link};const cr=await crawl(p,ledger),syn=await synthesize(config,p,cr.evidence,ledger,synthesisEvidence);if(!syn.contract||syn.contract.decision!=="COMPILE"){attempts.push({candidate_id:p.candidate_id,name:p.name,status:"contract_reject",error:syn.error,docs:cr.evidence.length});continue;}try{const ec=BLIND_EXEC_CASES[c.case_id],contract=syn.contract as MicroContract,url=compileIntegrationRequest(contract,ec.build),first=await safeJson(url,ledger),out1=executeIntegrationProjection(contract,c.case_id,first.body,ec.build);if(!validateIntegrationOutput(c.case_id,ec.build,out1))throw new Error("semantic_validation_first_failed");const second=await safeJson(url,ledger),out2=executeIntegrationProjection(contract,c.case_id,second.body,ec.build);if(!validateIntegrationOutput(c.case_id,ec.build,out2))throw new Error("semantic_validation_confirmation_failed");if(!sameRequired(out1,out2,ec.required))throw new Error("confirmation_value_mismatch");const recipe:any={case_id:c.case_id,provider_candidate_id:p.candidate_id,provider_name:p.name,provider_selection_fingerprint:selectionFp,documentation_fingerprint:sha3yr(cr.evidence.map(e=>({id:e.evidence_id,url:e.resolved_url,fp:e.body_fingerprint,state:e.state}))),frontier_fingerprint:frontierFingerprint(cr.frontier),contract,contract_fingerprint:sha3yr(contract),projection_kind:"3x_FIELD_program",first_verification:first,confirmation_verification:second};recipe.recipe_fingerprint=sha3yr({...recipe,recipe_fingerprint:undefined});recipes.push(recipe);success={candidate_id:p.candidate_id,name:p.name,output:out2,docs:cr.evidence.length,recipe_fingerprint:recipe.recipe_fingerprint};attempts.push({candidate_id:p.candidate_id,name:p.name,status:"verified_live"});break;}catch(e){attempts.push({candidate_id:p.candidate_id,name:p.name,status:"live_failed",error:String(e)});}}
 caseEvidence.push({case_id:c.case_id,selection_fingerprint:selectionFp,selected:selected.map(x=>({candidate_id:x.candidate_id,name:x.name,rank:x.lexical_rank})),attempts,success});}
 const before={catalogFetches,rerankerCalls,docFetches,synthesisCalls},replay:any[]=[];for(const recipe of recipes){const ec=BLIND_EXEC_CASES[recipe.case_id];try{const url=compileIntegrationRequest(recipe.contract,ec.replay),got=await safeJson(url,ledger),out=executeIntegrationProjection(recipe.contract,recipe.case_id,got.body,ec.replay);if(!validateIntegrationOutput(recipe.case_id,ec.replay,out))throw new Error("replay_semantic_validation_failed");replay.push({case_id:recipe.case_id,provider_candidate_id:recipe.provider_candidate_id,success:true,output:out,verification:got});}catch(e){replay.push({case_id:recipe.case_id,provider_candidate_id:recipe.provider_candidate_id,success:false,error:String(e)});}}
 const replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,reranker_calls:rerankerCalls-before.rerankerCalls,documentation_fetches:docFetches-before.docFetches,synthesis_calls:synthesisCalls-before.synthesisCalls},successful=caseEvidence.filter(x=>x.success),providers=new Set(successful.map(x=>x.success.candidate_id)),replaySuccess=replay.filter(x=>x.success),counters=derivedSafetyCounters(ledger),verifiedControls=controls.filter(x=>x.executed&&x.rejected).length;const gates={freeze_sha_declared:FREEZE_SHA==="6b79298feb6288f843e0c11c04cfbe7cd4a1a794",three_known_3y_cases:BLIND_CASES.length===3,mechanical_r2_frontier:true,at_least_2_manufactures:successful.length>=2,at_least_2_distinct_providers:providers.size>=2,double_live_verify_all:recipes.length>=2&&recipes.length===successful.length,recipes_persisted:recipes.length>=2,replay_100_percent:recipes.length>=2&&replaySuccess.length===recipes.length,replay_cognitive_deltas_zero:Object.values(replayDeltas).every(v=>v===0),real_3x_interpreter_projection:recipes.length>=2&&recipes.every(r=>r.projection_kind==="3x_FIELD_program"),fingerprints_present:recipes.length>=2&&recipes.every(r=>r.provider_selection_fingerprint&&r.documentation_fingerprint&&r.frontier_fingerprint&&r.contract_fingerprint&&r.recipe_fingerprint),controls_active:controls.length>=24&&verifiedControls===controls.length,event_derived_safety:safetyGateFromLedger(ledger,counters),ledger_non_empty:ledger.events.length>0};const decision=Object.values(gates).every(Boolean)?"GO_3Y_I_END_TO_END_INTEGRATION_RECOVERY":"REASSESS_3Y_I_END_TO_END_INTEGRATION_RECOVERY";const report={experiment:"3Y-I",purpose:"engineering_integration_only_not_confirmatory_evidence",freeze_sha:FREEZE_SHA,started_at,finished_at:new Date().toISOString(),decision,metrics:{successful_manufactures:successful.length,distinct_providers:providers.size,persisted_recipes:recipes.length,replay_successes:replaySuccess.length,replay_deltas:replayDeltas,controls:controls.length,controls_verified:verifiedControls,catalogFetches,rerankerCalls,docFetches,synthesisCalls,synthesisRepairs,liveCalls},gates,caseEvidence,replay,recipes,rerankEvidence,synthesisEvidence,safety_counters:counters,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()}};await writeFile(`${OUT}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({decision,metrics:report.metrics,gates},null,2));console.log(decision);console.log(`fingerprint=${sha3y(report)}`);}
main().catch(e=>{console.error(e);process.exitCode=1;});
