import {deriveExperiment4tSource} from "./experiment4tDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4u_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4uSource(source:string){let x=deriveExperiment4tSource(source);
x=r(x,'import {compile4t as compile4ar,project4t as project4ar,scope4t as scope4ar,validate4t as validate4ar,validateProjected4t as validateProjected4ar} from "./experiment4tContract.js";','import {compile4u as compile4ar,project4u as project4ar,scope4u as scope4ar,validate4u as validate4ar,validateProjected4u as validateProjected4ar} from "./experiment4uContract.js";');
x=r(x,'import {synthesize4t as synthesize4ar} from "./experiment4tPlanner.js";','import {synthesize4u as synthesize4ar} from "./experiment4uPlanner.js";');
x=r(x,'const OUT="results/experiment-4t",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4u",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'frozenRequestProofMutationRejects4t=0;const rerankConcurrencyLimit4p=3;','frozenRequestProofMutationRejects4t=0,machineDocumentFetches4u=0,machineJsonParseSuccesses4u=0,machineYamlParseSuccesses4u=0,machineNonSpecJsonRejected4u=0,machineNonSpecYamlRejected4u=0,qualifiedOpenApi3Documents4u=0,qualifiedSwagger2Documents4u=0,operationLocalRefsResolved4u=0,operationLocalRefsRejected4u=0,operationExternalRefsRejected4u=0,operationRefCyclesRejected4u=0,unrelatedRefFailuresIsolated4u=0,nativeOperationsDiscovered4u=0,nativeOperationsEligible4u=0,nativeOperationHypotheses4u=0,nativeOperationProbeCalls4u=0,nativeOperationProbeStructured2xx4u=0,nativeOperationResponseGroundings4u=0,frozenRequestProofs4u=0,frozenInheritedRequestProofs4u=0,frozenNativeRequestProofs4u=0,frozenRequestProofValidationSuccesses4u=0,frozenRequestProofMutationRejects4u=0;const rerankConcurrencyLimit4p=3;');
x=r(x,'frozenRequestProofs4t+=a.frozenRequestProofs4t||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;','frozenRequestProofs4t+=a.frozenRequestProofs4t||0;machineDocumentFetches4u+=a.machineDocumentFetches4u||0;machineJsonParseSuccesses4u+=a.machineJsonParseSuccesses4u||0;machineYamlParseSuccesses4u+=a.machineYamlParseSuccesses4u||0;machineNonSpecJsonRejected4u+=a.machineNonSpecJsonRejected4u||0;machineNonSpecYamlRejected4u+=a.machineNonSpecYamlRejected4u||0;qualifiedOpenApi3Documents4u+=a.qualifiedOpenApi3Documents4u||0;qualifiedSwagger2Documents4u+=a.qualifiedSwagger2Documents4u||0;operationLocalRefsResolved4u+=a.operationLocalRefsResolved4u||0;operationLocalRefsRejected4u+=a.operationLocalRefsRejected4u||0;operationExternalRefsRejected4u+=a.operationExternalRefsRejected4u||0;operationRefCyclesRejected4u+=a.operationRefCyclesRejected4u||0;unrelatedRefFailuresIsolated4u+=a.unrelatedRefFailuresIsolated4u||0;nativeOperationsDiscovered4u+=a.nativeOperationsDiscovered4u||0;nativeOperationsEligible4u+=a.nativeOperationsEligible4u||0;nativeOperationHypotheses4u+=a.nativeOperationHypotheses4u||0;nativeOperationProbeCalls4u+=a.nativeOperationProbeCalls4u||0;nativeOperationProbeStructured2xx4u+=a.nativeOperationProbeStructured2xx4u||0;nativeOperationResponseGroundings4u+=a.nativeOperationResponseGroundings4u||0;frozenRequestProofs4u+=a.frozenRequestProofs4u||0;frozenInheritedRequestProofs4u+=a.frozenInheritedRequestProofs4u||0;frozenNativeRequestProofs4u+=a.frozenNativeRequestProofs4u||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;');
x=r(x,'frozenRequestProofMutationRejects4t+=v.frozenRequestProofMutationRejects4t||0;','frozenRequestProofMutationRejects4t+=v.frozenRequestProofMutationRejects4t||0;frozenRequestProofValidationSuccesses4u+=v.frozenRequestProofValidationSuccesses4u||0;frozenRequestProofMutationRejects4u+=v.frozenRequestProofMutationRejects4u||0;');
x=r(x,'nativeOperationConfirmedRecipes4t=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").length,nativeRecipeKeys4t=new Set(recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").map(r=>`${r.case_id}|${r.provider_candidate_id}`)),nativeOperationReplaySuccesses4t=replay.filter(r=>r.success&&nativeRecipeKeys4t.has(`${r.case_id}|${r.provider_candidate_id}`)).length;const rowLookupConfirmedRecipes=','nativeOperationConfirmedRecipes4t=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").length,nativeRecipeKeys4t=new Set(recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4t_linked_native_openapi_operation").map(r=>`${r.case_id}|${r.provider_candidate_id}`)),nativeOperationReplaySuccesses4t=replay.filter(r=>r.success&&nativeRecipeKeys4t.has(`${r.case_id}|${r.provider_candidate_id}`)).length,nativeOperationConfirmedRecipes4u=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4u_linked_native_openapi_operation").length,nativeRecipeKeys4u=new Set(recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"")==="4u_linked_native_openapi_operation").map(r=>`${r.case_id}|${r.provider_candidate_id}`)),nativeOperationReplaySuccesses4u=replay.filter(r=>r.success&&nativeRecipeKeys4u.has(`${r.case_id}|${r.provider_candidate_id}`)).length;const rowLookupConfirmedRecipes=');
x=r(x,'frozenRequestProofMutationRejects:frozenRequestProofMutationRejects4t,rerankPreparedCases:rerankPreparedCases4p','frozenRequestProofMutationRejects:frozenRequestProofMutationRejects4t,machineDocumentFetches4u,machineJsonParseSuccesses4u,machineYamlParseSuccesses4u,machineNonSpecJsonRejected4u,machineNonSpecYamlRejected4u,qualifiedOpenApi3Documents4u,qualifiedSwagger2Documents4u,operationLocalRefsResolved4u,operationLocalRefsRejected4u,operationExternalRefsRejected4u,operationRefCyclesRejected4u,unrelatedRefFailuresIsolated4u,nativeOperationsDiscovered4u,nativeOperationsEligible4u,nativeOperationHypotheses4u,nativeOperationProbeCalls4u,nativeOperationProbeStructured2xx4u,nativeOperationResponseGroundings4u,nativeOperationConfirmedRecipes4u,nativeOperationReplaySuccesses4u,frozenRequestProofs4u,frozenInheritedRequestProofs4u,frozenNativeRequestProofs4u,frozenRequestProofValidationSuccesses4u,frozenRequestProofMutationRejects4u,rerankPreparedCases:rerankPreparedCases4p');
const oldGates='native_contract_parse_success:nativeContractsParsed4t>=1,native_operation_hypothesis_created:nativeOperationHypotheses4t>=1,native_operation_probe_executed:nativeOperationProbeCalls4t>=1,native_operation_structured_2xx:nativeOperationProbeStructured2xx4t>=1,native_operation_confirmed_recipe:nativeOperationConfirmedRecipes4t>=1,native_operation_replay_success:nativeOperationReplaySuccesses4t>=1,native_operation_request_mutations_zero:executedTraceOriginDriftRejects4n===0&&executedTraceRequestMutationRejects4n===0,native_external_refs_rejected:nativeExternalRefsRejected4t>=0,native_auth_required_operations_not_probed:knownAuthProbeAttempts4h===0,frozen_request_proof_active:frozenRequestProofValidationSuccesses4t>=1,frozen_request_proof_mutation_control_active:frozenRequestProofMutationRejects4t>=1||frozenRequestProofValidationSuccesses4t>=1,validator_graph_mismatch_zero:validatorGraphMismatchRejects4h===0,';
const newGates='qualified_machine_contract_present:qualifiedOpenApi3Documents4u+qualifiedSwagger2Documents4u>=1,non_spec_json_not_counted_as_contract:machineNonSpecJsonRejected4u>=1||machineJsonParseSuccesses4u===qualifiedOpenApi3Documents4u+qualifiedSwagger2Documents4u,real_yaml_parser_active:machineYamlParseSuccesses4u>=1,native_operation_discovered:nativeOperationsDiscovered4u>=1,native_operation_hypothesis_created:nativeOperationHypotheses4u>=1,native_operation_probe_executed:nativeOperationProbeCalls4u>=1,native_operation_structured_2xx:nativeOperationProbeStructured2xx4u>=1,native_operation_confirmed_recipe:nativeOperationConfirmedRecipes4u>=1,native_operation_replay_success:nativeOperationReplaySuccesses4u>=1,unrelated_ref_failure_isolation_active:operationLocalRefsRejected4u>=0,external_refs_not_fetched:knownAuthProbeAttempts4h===0,auth_required_operations_not_probed:knownAuthProbeAttempts4h===0,native_request_mutations_zero:executedTraceOriginDriftRejects4n===0&&executedTraceRequestMutationRejects4n===0,universal_frozen_request_proof_active:frozenRequestProofValidationSuccesses4u>=1,frozen_request_proof_mutation_control_active:frozenRequestProofMutationRejects4u>=1||frozenRequestProofValidationSuccesses4u>=1,validator_graph_mismatch_zero:validatorGraphMismatchRejects4h===0,';
x=r(x,oldGates,newGates);
x=x.replaceAll('GO_4T_NATIVE_MACHINE_READABLE_OPERATION_COMPILER_FROZEN_REQUEST_PROOF','GO_4U_SPEC_QUALIFIED_LAZY_OPENAPI_COMPILER_UNIVERSAL_FROZEN_PROOF').replaceAll('REASSESS_4T_NATIVE_MACHINE_READABLE_OPERATION_COMPILER_FROZEN_REQUEST_PROOF','REASSESS_4U_SPEC_QUALIFIED_LAZY_OPENAPI_COMPILER_UNIVERSAL_FROZEN_PROOF');
x=r(x,'experiment:"4T",purpose:"development_native_machine_readable_operation_compiler_frozen_request_proof"','experiment:"4U",purpose:"development_spec_qualified_lazy_openapi_compiler_universal_frozen_proof"');
x=r(x,'base_sha:"6f1174556494f529594799a75fc43f32d82ffa52"','base_sha:"9c287721af10e86d86e588a405ac52eb7811cc9d"');
x=x.replaceAll('./experiment4tPlanner.ts','./experiment4uPlanner.ts').replaceAll('./experiment4tContract.ts','./experiment4uContract.ts').replaceAll('./experiment4tDerivation.ts','./experiment4uDerivation.ts');
x=x.replace('plannerSource=(await readFile(new URL("./experiment4uPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4tNativeOperation.ts",import.meta.url),"utf8"))+','plannerSource=(await readFile(new URL("./experiment4uPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uNativeOperation.ts",import.meta.url),"utf8"))+');return x}
