import type {Config} from "./config/index.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {makeBoundarySchema,canonicalizeBoundary3} from "./experiment4ar3Core.js";
import type {DocEvidence} from "./experiment3wCore.js";
import {packEvidenceR5,fourAr5Sha} from "./experiment4ar5Core.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(x=>[x.case_id,x]));
export async function synthesize4ar5(config:Config,p:Provider4A,evidence:DocEvidence[],phase:"initial"|"repair",previousError?:string){
 const ec=BY_ID[p.case_id],inputNames=Object.keys(ec.build),packet=packEvidenceR5(evidence,p.case_id);
 const system=["You are MISSING's deterministic evidence-grounded typed API compiler.","Use ONLY supplied evidence_packet items.","Evidence items are already deterministically ranked; prefer verified_spec and explicit response schema/example evidence over generic prose.","If evidence cannot support an anonymous HTTPS GET satisfying every required output, return REJECT.","Never invent provider, host, path, parameter, field, credential, header, transformation, endpoint, input, or literal.","Path bindings are typed rows. source_kind must be INPUT and input_name must be one of the case input names; literal_value must be null.","Query bindings are typed rows. For source_kind INPUT, input_name must be one of the case input names and literal_value must be null. For source_kind LITERAL, input_name must be null and literal_value must be literally documented in cited evidence.","For COMPILE, projection rows must use only FIELD, INPUT, LOOKUP, or FIND.","FIELD uses path; INPUT uses name; LOOKUP uses map_path plus key_op/key_name or key_value plus value_path; FIND uses array_path, where_path, equals_op/equals_name or equals_value plus value_path.","Paths use dotted notation with numeric indices. No JSONPath, brackets, or wildcard.","method must be GET and base_url must be an HTTPS origin literally present in cited evidence.","Cite only evidence_id values actually supplied in the evidence packet."].join(" ");
 const payload={case:{case_id:p.case_id,input_names:inputNames,required_outputs:ec.required,build_input:ec.build,replay_input:ec.replay},provider:{candidate_id:p.candidate_id,name:p.name},phase,previous_validation_error:previousError??null,evidence_packet:packet.items};
 const t0=Date.now();const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:makeBoundarySchema(inputNames)}})});const latency_ms=Date.now()-t0,text=await r.text();let body:any=null;try{body=JSON.parse(text);}catch{}const msg=body?.choices?.[0]?.message,raw=msg?.content??null;let parsed:any=null,parse_error:string|null=null;if(typeof raw==="string"){try{parsed=canonicalizeBoundary3(JSON.parse(raw),ec.required,inputNames);}catch(e){parse_error=String(e);}}
 return {phase,http_status:r.status,http_ok:r.ok,refusal:msg?.refusal??null,raw_content:raw,parsed_json:parsed,parse_error,usage:body?.usage??null,latency_ms,evidence_packet_fingerprint:packet.fingerprint,evidence_packet:packet.items.map(({text,...meta}:any)=>({...meta,text_fingerprint:fourAr5Sha(text)})),evidence_packet_total_chars:packet.total_chars};
}
