import type {Config} from "./config/index.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import type {DocEvidence} from "./experiment3wCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {Provider4A} from "./experiment4aContract.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,type P1ProbeProof,type P1SemanticSelection} from "./experiment4ap1Model.js";
import {lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4N} from "./experiment4nRequest.js";
import {probeCacheMetrics4L,probeHypothesis4L} from "./experiment4lProbe.js";
import {allowedInputSources4O,deterministicProjection4O,materialize4O} from "./experiment4oCore.js";
import type {RelationalSummary4O} from "./experiment4oRelational.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(r=>[r.case_id,r]));
function overlap(a:string,b:string){const x=new Set(lexicalTokensP1(a)),y=new Set(lexicalTokensP1(b));let n=0;for(const t of x)if(y.has(t))n++;return n}
function fieldPacket(p:P1ProbeProof,req:readonly string[]){return [...p.record.observed_fields].filter(f=>!/(^|\.)\d+(\.|$)/.test(f.path)).map(field=>({field,score:Math.max(0,...req.map(o=>overlap(o,field.leaf)))*100+field.build_value_relations.length*20-Math.min(30,field.path.split(".").length)})).sort((a,b)=>b.score-a.score||a.field.path.length-b.field.path.length).slice(0,48).map(r=>r.field)}
async function callStructured(config:Config,payload:any,jsonSchema:any){const started=Date.now();const response=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,temperature:0,messages:[{role:"system",content:"Map outputs only to supplied observed field IDs or output-compatible TASK_INPUT sources. Never infer one task role from an incompatible input role. Never invent URLs, fields, indices, credentials, or labels. ROW_LOOKUP is compiled deterministically outside this call."},{role:"user",content:JSON.stringify(payload)}],response_format:{type:"json_schema",json_schema:jsonSchema}})});const latency_ms=Date.now()-started,text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}return {status:response.status,ok:response.ok,latency_ms,usage:body?.usage??null,raw:body?.choices?.[0]?.message?.content??null,refusal:body?.choices?.[0]?.message?.refusal??null}}
function schema(proofs:P1ProbeProof[],inputs:readonly string[],required:readonly string[]){const hs=proofs.map(p=>p.hypothesis.id),fields=[...new Set(proofs.flatMap(p=>fieldPacket(p,required).map(f=>f.id)))],variants=required.map(output=>{const sources=[...fields,...allowedInputSources4O(output,inputs).map(i=>`TASK_INPUT:${i}`)];return {type:"object",additionalProperties:false,properties:{task_output:{const:output},source_id:{type:"string",enum:sources.length?sources:["NO_VALID_SOURCE"]}},required:["task_output","source_id"]}});return {name:"missing_4o_observed_mapping",strict:true,schema:{type:"object",additionalProperties:false,properties:{decision:{type:"string",enum:["SELECT","REJECT"]},hypothesis_id:{type:"string",enum:hs},output_bindings:{type:"array",minItems:required.length,maxItems:required.length,items:{oneOf:variants}},reason:{type:"string"}},required:["decision","hypothesis_id","output_bindings","reason"]}}}
function parse(raw:any):P1SemanticSelection{if(typeof raw!=="string")throw new Error("4o_planner_missing_content");const v=JSON.parse(raw);return {decision:v.decision,hypothesis_id:String(v.hypothesis_id),output_bindings:(v.output_bindings||[]).map((r:any)=>({task_output:String(r.task_output),source_id:String(r.source_id)})),reason:String(v.reason||"")}}
function legacyProjection(caseId:string,proof:P1ProbeProof,selection:P1SemanticSelection){const c=BY_ID[caseId],projection:any={},used=new Set<string>();for(const b of selection.output_bindings){if(!c.required.includes(b.task_output))throw new Error("4o_unknown_output");if(b.source_id.startsWith("TASK_INPUT:")){const input=b.source_id.slice(11);if(!allowedInputSources4O(b.task_output,c.input_names).includes(input))throw new Error("4o_forbidden_input_source");projection[b.task_output]={op:"INPUT",name:input};continue}const f=proof.record.observed_fields.find(x=>x.id===b.source_id);if(!f||/(^|\.)\d+(\.|$)/.test(f.path)||used.has(f.id))throw new Error("4o_field_invalid");used.add(f.id);projection[b.task_output]={op:"FIELD",path:f.path}}return projection}
function trace(h:any){return String(h?.proof_type||"").startsWith("4n_executed_trace_")}
function documentedRole(h:any){return String(h?.proof_type||"").startsWith("4n_executed_trace_documented_role_")}
function delta(a:Record<string,number>,b:Record<string,number>,k:string){return Number(b[k]||0)-Number(a[k]||0)}
export async function synthesize4o(config:Config,provider:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){
 const c=BY_ID[provider.case_id];if(!c)throw new Error(`4o_unknown_case:${provider.case_id}`);
 const request=await prepareRequestGraph4N(evidence,provider.case_id,provider.candidate_id,ledger),rows:{proof:P1ProbeProof;summary:RelationalSummary4O|null}[]=[],cacheBefore=probeCacheMetrics4L();
 for(const h of request.probe_packet.slice(0,FOUR_AP1_MAX_PROBES_PER_PROVIDER)){const got=await probeHypothesis4L(h,c.build,ledger);rows.push({proof:got.proof,summary:got.relational_summary})}
 const cacheAfter=probeCacheMetrics4L(),cacheMetrics={probeCacheHits:delta(cacheBefore,cacheAfter,"probeCacheHits"),probeNetworkFetches:delta(cacheBefore,cacheAfter,"probeNetworkFetches"),duplicateProbeNetworkFetches:delta(cacheBefore,cacheAfter,"duplicateProbeNetworkFetches")},successful=rows.filter(r=>r.proof.record.disposition==="success"),proofs=successful.map(r=>r.proof),relMetrics=successful.reduce((a,r)=>{for(const [k,v] of Object.entries(r.summary?.metrics||{}))a[k]=(a[k]||0)+Number(v||0);return a},{} as Record<string,number>),probeMetrics={schemaProbeCalls:rows.length,schemaProbe2xxJson:successful.length,schemaProbeRejected:rows.length-successful.length,schemaProbeBytes:successful.reduce((n,r)=>n+r.proof.record.bytes,0),executedTraceProbeCalls:rows.filter(r=>trace(r.proof.hypothesis)).length,executedTraceProbe2xxJson:successful.filter(r=>trace(r.proof.hypothesis)).length,executedTraceDocumentedRoleProbeCalls:rows.filter(r=>documentedRole(r.proof.hypothesis)).length,executedTraceDocumentedRoleProbe2xxJson:successful.filter(r=>documentedRole(r.proof.hypothesis)).length,...relMetrics,...cacheMetrics},attribution={request_inventory_count:request.hypotheses.length,alignment_metrics:request.metrics,operation_semantics_fingerprint:request.semantics.fingerprint,request_graph_fingerprint:request.graph_fingerprint,request_hypotheses:request.probe_packet,probe_records:proofs.map(r=>r.record),...probeMetrics,noIrOperation:request.metrics.noIrOperation,irOperationUnusable:request.metrics.irOperationUnusable},forbidden=c.required.reduce((n,o)=>n+c.input_names.filter(i=>!allowedInputSources4O(o,c.input_names).includes(i)).length,0);
 if(!successful.length)return {http_status:0,http_ok:true,refusal:null,raw_content:null,parsed_json:{case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:"4O_PROBE_FAILED"},parse_error:null,usage:null,latency_ms:0,probe_proof:null,planner_skipped:true,deterministic_mapping:false,row_lookup_selected:false,forbidden_input_source_candidates:forbidden,...attribution};
 for(const row of successful){const d=deterministicProjection4O(row.proof,row.summary,c.input_names,c.required);if(!d)continue;const m=materialize4O(provider.case_id,provider.candidate_id,row.proof,d.projection,row.summary);return {http_status:0,http_ok:true,refusal:null,raw_content:null,parsed_json:m.raw,parse_error:null,usage:null,latency_ms:0,probe_proof:row.proof,operation_proof:m.proof,planner_skipped:true,deterministic_mapping:true,row_lookup_selected:d.rowLookups>0,selected_from_trace:trace(row.proof.hypothesis),selected_from_documented_role:documentedRole(row.proof.hypothesis),forbidden_input_source_candidates:forbidden,...attribution}}
 const call=await callStructured(config,{case:{case_id:provider.case_id,intent:c.intent,input_names:c.input_names,required_outputs:c.required},provider:{candidate_id:provider.candidate_id,name:provider.name},successful_probe_hypotheses:proofs.map(p=>({hypothesis_id:p.hypothesis.id,fields:fieldPacket(p,c.required).map(f=>({field_id:f.id,path:f.path,leaf:f.leaf,sample_type:f.sample_type,build_value_relations:f.build_value_relations}))}))},schema(proofs,c.input_names,c.required));
 let selection:P1SemanticSelection|null=null,parsed_json:any=null,probe_proof:P1ProbeProof|null=null,operation_proof:any=null,parse_error:string|null=null;
 try{selection=parse(call.raw);if(selection.decision==="REJECT")parsed_json={case_id:provider.case_id,provider_candidate_id:provider.candidate_id,decision:"REJECT",reason:`4O_MAPPING_REJECT:${selection.reason}`};else{probe_proof=proofs.find(p=>p.hypothesis.id===selection!.hypothesis_id)||null;if(!probe_proof)throw new Error("4o_selected_probe_missing");const projection=legacyProjection(provider.case_id,probe_proof,selection),m=materialize4O(provider.case_id,provider.candidate_id,probe_proof,projection,null);parsed_json=m.raw;operation_proof=m.proof}}catch(e){parse_error=String(e).replace(/^Error:\s*/,"")}
 return {http_status:call.status,http_ok:call.ok,refusal:call.refusal,raw_content:call.raw,parsed_json,parse_error,usage:call.usage,latency_ms:call.latency_ms,probe_proof,operation_proof,planner_skipped:false,deterministic_mapping:false,row_lookup_selected:false,selected_from_trace:probe_proof?trace(probe_proof.hypothesis):false,selected_from_documented_role:probe_proof?documentedRole(probe_proof.hypothesis):false,forbidden_input_source_candidates:forbidden,...attribution};
}
