import {deriveExperiment5b14PlannerSource} from "./experiment5b14PlannerDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b19_planner_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}

export function deriveExperiment5b19PlannerSource(source:string){let x=deriveExperiment5b14PlannerSource(source);
 x='import {qualifyRequestHypotheses5B19,qualificationDeterminism5B19} from "./experiment5b19Qualification.js";\n'+x;
 x=r(x,'const historicalPrimary=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,det=requestOrderingDeterminism5B14(c,plannerHypotheses5b11,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B14(c,plannerHypotheses5b11,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);',
 'const qualificationArgs5b19={hypotheses:plannerHypotheses5b11,evidence:localized.evidence,intent:c.intent,inputNames:c.input_names,nativeProofById,collectionProofById,queryProofById,documentaryWitnessById},qualification5b19=qualifyRequestHypotheses5B19(qualificationArgs5b19),qualificationDet5b19=qualificationDeterminism5B19(qualificationArgs5b19);add(metrics,qualification5b19.metrics);if(!qualificationDet5b19.ok)metrics.qualificationNondeterminismViolations5b19=(metrics.qualificationNondeterminismViolations5b19||0)+1;const qualifiedPlannerHypotheses5b19=qualification5b19.hypotheses,qualificationWitnessById5b19=qualification5b19.witnesses,historicalPrimary0=(request.probe_packet||[])[0] as P1RequestHypothesis|undefined,historicalPrimary=historicalPrimary0&&qualificationWitnessById5b19.has(historicalPrimary0.id)?historicalPrimary0:undefined,det=requestOrderingDeterminism5B14(c,qualifiedPlannerHypotheses5b19,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);if(!det.ok)metrics.requestOrderingNondeterminismRejects5b3++;const ranked=rankRequestBeam5B14(c,qualifiedPlannerHypotheses5b19,localized.evidence,utilityProofById,documentaryWitnessById,historicalPrimary);');
 x=r(x,'metrics.documentaryBeamPosition2_5b13=beam[1]&&documentaryWitnessById.has(beam[1].id)?1:0;',
 'metrics.documentaryBeamPosition2_5b13=beam[1]&&documentaryWitnessById.has(beam[1].id)?1:0;metrics.qualificationBeamEntries5b19=beam.filter((h:any)=>qualificationWitnessById5b19.has(h.id)).length;metrics.beamEntriesWithoutQualificationWitness5b19=beam.length-metrics.qualificationBeamEntries5b19;');
 x=r(x,'templateWitness5b11=template5b11.witnesses.get(h.id)||null,documentaryWitness5b12=documentaryWitnessById.get(h.id)||null;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;',
 'templateWitness5b11=template5b11.witnesses.get(h.id)||null,documentaryWitness5b12=documentaryWitnessById.get(h.id)||null,qualificationWitness5b19=qualificationWitnessById5b19.get(h.id)||null;if(qualificationWitness5b19)metrics.probedRequestsWithQualificationWitness5b19=(metrics.probedRequestsWithQualificationWitness5b19||0)+1;else metrics.probedRequestsWithoutQualificationWitness5b19=(metrics.probedRequestsWithoutQualificationWitness5b19||0)+1;if(isRecovery5b10)metrics.recoveryExecutedCandidates5b10++;');
 x=r(x,'materialized.raw.request_utility_rank_5b3=i+1;materialized.raw.request_utility_5b13=byId.get(h.id)||null;',
 'materialized.raw.request_utility_rank_5b3=i+1;materialized.raw.request_utility_5b13=byId.get(h.id)||null;materialized.raw.evidence_qualification_witness_5b19=qualificationWitness5b19?{...qualificationWitness5b19,beam_position:i+1,request_fingerprint:shape(h)}:null;');
 x=r(x,'request_hypotheses:beam,probe_records:',
 'request_hypotheses:beam,request_qualification_fingerprint_5b19:qualification5b19.fingerprint,request_qualification_witnesses_5b19:beam.map((h:any)=>qualificationWitnessById5b19.get(h.id)||null),request_qualification_rejections_5b19:qualification5b19.rejections,probe_records:');
 x=x.replaceAll('export async function synthesize5b14','export async function synthesize5b19').replaceAll('5b14_unknown_case','5b19_unknown_case').replaceAll('5B14_BEAM_EXHAUSTED','5B19_BEAM_EXHAUSTED');
 return x}
