import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {compileMicroRequest,docScopeAllowed} from "./experiment3wCore.js";
import {executeProgram,type ProjectionExpr} from "./experiment3xCore.js";
import {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES,semanticValidate4a} from "./experiment4aCore.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(x=>[x.case_id,x]));
export type Provider4A={case_id:string,candidate_id:string,name:string,start_url:string};
function evidenceText(ids:string[],all:DocEvidence[],providerId:string){const by=new Map(all.map(e=>[e.evidence_id,e]));const out:DocEvidence[]=[];for(const id of ids){const e=by.get(id);if(!e)throw new Error(`unknown_evidence_id:${id}`);if(e.provider_candidate_id!==providerId)throw new Error(`cross_provider_evidence:${id}`);if(e.state!=="ok")throw new Error(`non_ok_evidence:${id}`);out.push(e);}return out.map(x=>x.text).join("\n");}
function sourceKey(v:string){return v.startsWith("$input.")?v.slice(7):null;}
function pathGrounded(path:string,text:string){if(text.includes(path))return true;const n=path.replace(/\{[^}]+\}/g,"{}");return [...text.matchAll(/\/[^\s"'<>`]*/g)].map(m=>m[0].replace(/\{[^}]+\}/g,"{}")).some(x=>x===n||x.endsWith(n));}
function fieldGrounded(leaf:string,text:string){const t=text.toLowerCase(),n=leaf.toLowerCase();let i=t.indexOf(n);while(i>=0){const ctx=t.slice(Math.max(0,i-650),Math.min(t.length,i+n.length+650));if(/response|return|json|schema|example|sample|output|property|field/.test(ctx))return true;i=t.indexOf(n,i+n.length);}return false;}
export function validate4aContract(c:any,p:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){const errors:string[]=[],ec=BY_ID[p.case_id];if(!ec)return {errors:["unknown_case"]};if(!c||typeof c!=="object"||Array.isArray(c))return {errors:["contract_not_object"]};if(c.case_id!==p.case_id)errors.push("case_id_mismatch");if(c.provider_candidate_id!==p.candidate_id)errors.push("provider_id_mismatch");if(!["COMPILE","REJECT"].includes(c.decision))errors.push("decision_invalid");if(c.decision!=="COMPILE")return {errors,contract:c as MicroContract};if(c.method!=="GET"){errors.push("method_not_get");ledger.record("guard","non_get",false,c.method);}const ids=Array.isArray(c.evidence_ids)?c.evidence_ids:[];if(!ids.length)errors.push("empty_evidence_ids");let text="";try{text=evidenceText(ids,evidence,p.candidate_id);}catch(e){errors.push(String(e).replace(/^Error:\s*/,""));}
 try{const base=new URL(String(c.base_url||""));if(base.protocol!=="https:"){errors.push("base_non_https");ledger.record("guard","non_https",false,base.toString());}if(base.username||base.password){errors.push("credential_bearing_base");ledger.record("guard","credentials",false);}if(text&&!text.includes(base.origin)){errors.push("undocumented_base_url");ledger.record("guard","endpoint_mutations",false,base.origin);}}catch{errors.push("invalid_base_url");}
 const path=String(c.path_template||"");if(!path.startsWith("/"))errors.push("path_not_absolute");if(text&&!pathGrounded(path,text)){errors.push("undocumented_path");ledger.record("guard","endpoint_mutations",false,path);}const pb=c.path_bindings&&typeof c.path_bindings==="object"&&!Array.isArray(c.path_bindings)?c.path_bindings:{},qb=c.query_bindings&&typeof c.query_bindings==="object"&&!Array.isArray(c.query_bindings)?c.query_bindings:{},op=c.output_paths&&typeof c.output_paths==="object"&&!Array.isArray(c.output_paths)?c.output_paths:{};
 for(const [providerParam,src] of Object.entries(pb)){if(!path.includes(`{${providerParam}}`))errors.push(`path_placeholder_missing:${providerParam}`);const k=sourceKey(String(src));if(!k||!(k in ec.build)){errors.push(`invalid_input_source:${providerParam}`);ledger.record("guard","invented_parameters",false,providerParam);}}
 for(const [providerParam,src] of Object.entries(qb)){const k=sourceKey(String(src));if(String(src).startsWith("$input.")&&(!k||!(k in ec.build))){errors.push(`invalid_input_source:${providerParam}`);ledger.record("guard","invented_parameters",false,providerParam);}if(text&&!text.toLowerCase().includes(providerParam.toLowerCase())){errors.push(`invented_query_parameter:${providerParam}`);ledger.record("guard","invented_parameters",false,providerParam);}}
 for(const req of ec.required){const pth=op[req];if(typeof pth!=="string"||!pth)errors.push(`missing_output_path:${req}`);else{const leaf=pth.split(".").filter(Boolean).pop()||pth;if(text&&!fieldGrounded(leaf,text)){errors.push(`invented_output_field:${req}:${leaf}`);ledger.record("guard","invented_output_fields",false,leaf);}}}for(const ph of path.match(/\{([^}]+)\}/g)||[]){const n=ph.slice(1,-1);if(!(n in pb))errors.push(`unbound_path_placeholder:${n}`);}return {errors,contract:c as MicroContract};}
export function compile4a(c:MicroContract,input:Record<string,unknown>){return compileMicroRequest(c,input);}
export function project4a(c:MicroContract,caseId:string,body:any,input:Record<string,unknown>){const ec=BY_ID[caseId];if(!ec)throw new Error("unknown_case");const program:Record<string,ProjectionExpr>={};for(const k of ec.required){const path=String(c.output_paths?.[k]||"");if(!path)throw new Error(`missing_projection_path:${k}`);program[k]={op:"FIELD",path};}return executeProgram(program,body,input);}
export function validateProjected4a(caseId:string,input:Record<string,any>,out:Record<string,any>){return semanticValidate4a(caseId,input,out);}
export function scope4a(start:string,target:string){return docScopeAllowed(start,target);}
