import {createHash} from "node:crypto";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import type {DocEvidence} from "./experiment3wCore.js";

export const FOUR_AR5_BASE_SHA="43b72b332fd0a1e7a18aac6454ff69d30122886d";
export const FOUR_AR5_FROZEN_RUN=33027569131;
export const FOUR_AR5_FROZEN_ARTIFACT=9629192653;
export const FOUR_AR5_FROZEN_DIGEST="sha256:9f9d107f7bdf29c793e104f906c8ff2b4237eb111d8f6d5338363d30f54cf368";
export const FOUR_AR5_FROZEN_REPORT_FP="15054f0b84a3589f5a08bddfa048a9d20bb66dbf932643806ce0731e0923c978";
export const FOUR_AR5_FROZEN_LEDGER_FP="940fb33e79e5b979ca40eab4d1c179d96e6c2e2f3386782d02b6ce41ccde2aaf";
export const FOUR_AR5_RERANK_COUNT=120;
export const FOUR_AR5_EVIDENCE_MAX_CHARS=52000;
export const fourAr5Sha=(v:any)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v)).digest("hex");

const STOP=new Set(["a","an","the","and","or","of","to","for","from","in","on","by","with","that","this","is","are","be","given","identify","public","machine","readable","api","operation","returns","return","canonical","human","metadata"]);
export function r5Tokens(raw:string){return [...new Set((String(raw).toLowerCase().match(/[a-z0-9_]+/g)||[]).filter(x=>x.length>=2&&!STOP.has(x)))];}
export function caseTokensR5(caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return [];return r5Tokens(`${c.intent} ${c.input_names.join(" ")} ${c.required_output_leaf_names.join(" ")}`);}

export type R5ScoreRow={candidate_id:string;functional_fit:number;evidence_likelihood:number;anonymous_get_likelihood:number};
export function deterministicRerankR5(rows:R5ScoreRow[],broad:any[]){const by=new Map(broad.map(x=>[x.candidate_id,x]));return rows.map(r=>{const c=by.get(r.candidate_id);if(!c)throw new Error(`r5_unknown_candidate:${r.candidate_id}`);const total=5*r.functional_fit+3*r.evidence_likelihood+2*r.anonymous_get_likelihood;return {...c,r5_functional_fit:r.functional_fit,r5_evidence_likelihood:r.evidence_likelihood,r5_anonymous_get_likelihood:r.anonymous_get_likelihood,r5_score:total};}).sort((a,b)=>b.r5_score-a.r5_score||a.lexical_rank-b.lexical_rank||a.candidate_id.localeCompare(b.candidate_id));}

const SPEC_HINT=/(openapi|swagger|api-docs|redoc|schema\.(?:json|ya?ml)|openapi\.(?:json|ya?ml)|swagger\.(?:json|ya?ml))/i;
const DOC_HINT=/(api|docs?|documentation|developer|reference|endpoint|response|example|schema)/i;
export type R5FrontierDecision={source_evidence_id:string;target_url:string;anchor_text:string;score:number;reasons:string[];accepted:boolean;kind:"spec"|"docs";rejection_reason?:string};
function frontierScoreR5(url:string,anchor:string,tokens:string[]){const u=new URL(url),hay=`${u.pathname} ${u.search} ${anchor}`.toLowerCase();let score=0;const reasons:string[]=[];const spec=SPEC_HINT.test(hay);if(spec){score+=40;reasons.push("spec_reference");}if(DOC_HINT.test(hay)){score+=12;reasons.push("documentation_reference");}for(const t of tokens)if(hay.includes(t)){score+=3;reasons.push(`case_token:${t}`);}if(/\.(json|ya?ml)$/i.test(u.pathname)){score+=8;reasons.push("structured_suffix");}return {score,reasons,kind:spec?"spec" as const:"docs" as const};}
export function extractEvidenceFrontierR5(base:string,start:string,text:string,sourceEvidenceId:string,scopeAllowed:(a:string,b:string)=>boolean,caseId:string){
 const tokens=caseTokensR5(caseId),seen=new Set<string>(),out:R5FrontierDecision[]=[];
 const push=(raw:string,anchor:string)=>{try{const target=new URL(raw,base).toString();if(seen.has(target))return;seen.add(target);if(!scopeAllowed(start,target)){out.push({source_evidence_id:sourceEvidenceId,target_url:target,anchor_text:anchor,score:-100,reasons:[],accepted:false,kind:"docs",rejection_reason:"out_of_scope"});return;}const s=frontierScoreR5(target,anchor,tokens);const accepted=s.score>=12;out.push({source_evidence_id:sourceEvidenceId,target_url:target,anchor_text:anchor,score:s.score,reasons:s.reasons,accepted,kind:s.kind,rejection_reason:accepted?undefined:"not_evidence_relevant"});}catch{}};
 let m:RegExpExecArray|null;const attrs=/\b(?:href|src|data-url|data-spec-url|data-swagger-url)\s*=\s*["']([^"'#]+)["']/gi;while((m=attrs.exec(text)))push(m[1],text.slice(Math.max(0,m.index-100),Math.min(text.length,m.index+220)).replace(/<[^>]+>/g," ").replace(/\s+/g," "));
 const cfg=/(?:spec-url|specUrl|swaggerUrl|openapi|api-docs|\burl)\s*[:=]\s*["']([^"']+)["']/gi;while((m=cfg.exec(text)))if(SPEC_HINT.test(m[0])||SPEC_HINT.test(m[1]))push(m[1],m[0]);
 return out.sort((a,b)=>b.score-a.score||a.kind.localeCompare(b.kind)||a.target_url.localeCompare(b.target_url));
}

function refResolve(spec:any,node:any){if(node&&typeof node==="object"&&typeof node.$ref==="string"&&node.$ref.startsWith("#/")){let cur=spec;for(const p of node.$ref.slice(2).split("/")){cur=cur?.[p.replace(/~1/g,"/").replace(/~0/g,"~")];}return cur??node;}return node;}
function schemaPaths(spec:any,schema:any,prefix="",depth=0,seen=new Set<any>()):string[]{schema=refResolve(spec,schema);if(!schema||typeof schema!=="object"||depth>5||seen.has(schema))return [];seen.add(schema);const out:string[]=[];if(schema.properties&&typeof schema.properties==="object")for(const [k,v] of Object.entries(schema.properties)){const p=prefix?`${prefix}.${k}`:k;out.push(p);out.push(...schemaPaths(spec,v,p,depth+1,new Set(seen)));}if(schema.items)out.push(...schemaPaths(spec,schema.items,prefix?`${prefix}.0`:"0",depth+1,new Set(seen)));for(const key of ["allOf","oneOf","anyOf"])if(Array.isArray(schema[key]))for(const child of schema[key])out.push(...schemaPaths(spec,child,prefix,depth+1,new Set(seen)));return [...new Set(out)].slice(0,160);}
function responseSchemas(spec:any,responses:any){const props:string[]=[];for(const [code,r0] of Object.entries(responses||{})){if(!/^2\d\d$/.test(code)&&code!=="default")continue;const r=refResolve(spec,r0);const content=r?.content&&typeof r.content==="object"?Object.values(r.content):[];for(const media of content as any[])props.push(...schemaPaths(spec,media?.schema));if(r?.schema)props.push(...schemaPaths(spec,r.schema));}return [...new Set(props)].slice(0,160);}
export function specSummaryR5(spec:any,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId),tokens=caseTokensR5(caseId),ops:any[]=[];for(const [path,item] of Object.entries(spec?.paths||{}) as any[]){const op=item?.get;if(!op)continue;const parameters=[...(item?.parameters||[]),...(op?.parameters||[])].map((p:any)=>refResolve(spec,p)).map((p:any)=>({name:p?.name,in:p?.in,required:Boolean(p?.required)}));const response_properties=responseSchemas(spec,op.responses||{});const hay=`${path} ${op.operationId||""} ${op.summary||""} ${op.description||""} ${parameters.map((p:any)=>p.name).join(" ")} ${response_properties.join(" ")}`.toLowerCase();let relevance=0;for(const t of tokens)if(hay.includes(t))relevance+=3;for(const r of c?.required||[])if(hay.includes(String(r).toLowerCase()))relevance+=5;for(const i of c?.input_names||[])if(hay.includes(String(i).toLowerCase()))relevance+=4;ops.push({method:"GET",path,operation_id:op.operationId||null,summary:op.summary||null,parameters,response_properties,relevance});}ops.sort((a,b)=>b.relevance-a.relevance||a.path.localeCompare(b.path));const selected=ops.slice(0,40);return `R5_VERIFIED_API_SPEC\n${JSON.stringify({openapi:spec.openapi,swagger:spec.swagger,servers:spec.servers,host:spec.host,basePath:spec.basePath,schemes:spec.schemes,operation_count:ops.length,response_property_count:[...new Set(ops.flatMap(x=>x.response_properties))].length,operations:selected},null,2)}`;}

function evidenceClass(text:string,contentType:string){if(text.startsWith("R5_VERIFIED_API_SPEC"))return "verified_spec";const t=text.toLowerCase();if(/openapi|swagger|api-docs/.test(t))return "spec_like";if(/\b(get|endpoint|response|example|schema|parameter)\b/.test(t))return "api_docs";if(contentType.includes("json")||contentType.includes("yaml"))return "structured_doc";return "prose";}
function focusedText(text:string,needles:string[],budget=12000){const lower=text.toLowerCase(),hits:number[]=[];for(const n of needles){let from=0,i=-1;while((i=lower.indexOf(n.toLowerCase(),from))>=0&&hits.length<32){hits.push(i);from=i+n.length;}}if(!hits.length)return text.slice(0,budget);hits.sort((a,b)=>a-b);const chunks:string[]=[];for(const i of hits){const chunk=text.slice(Math.max(0,i-900),Math.min(text.length,i+2700));if(!chunks.includes(chunk))chunks.push(chunk);if(chunks.join("\n---\n").length>=budget)break;}return chunks.join("\n---\n").slice(0,budget);}
export function packEvidenceR5(evidence:DocEvidence[],caseId:string,maxChars=FOUR_AR5_EVIDENCE_MAX_CHARS){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {items:[],fingerprint:fourAr5Sha([]),total_chars:0};const needles=["https://"," GET ","endpoint","response","example","schema","parameter",...c.input_names,...c.required];const rows=evidence.filter(e=>e.state==="ok").map(e=>{const cls=evidenceClass(e.text,e.content_type||""),focused=focusedText(e.text,needles),lower=focused.toLowerCase();let score=cls==="verified_spec"?100:cls==="spec_like"?70:cls==="api_docs"?45:cls==="structured_doc"?30:10;for(const r of c.required)if(lower.includes(String(r).toLowerCase()))score+=8;for(const i of c.input_names)if(lower.includes(String(i).toLowerCase()))score+=5;const opm=focused.match(/"operation_count"\s*:\s*(\d+)/),rpm=focused.match(/"response_property_count"\s*:\s*(\d+)/);return {evidence_id:e.evidence_id,url:e.resolved_url,content_type:e.content_type,evidence_class:cls,score,spec_operation_count:Number(opm?.[1]||0),response_property_count:Number(rpm?.[1]||0),text:focused};}).sort((a,b)=>b.score-a.score||a.evidence_class.localeCompare(b.evidence_class)||a.evidence_id.localeCompare(b.evidence_id)||a.url.localeCompare(b.url));const items:any[]=[];let used=0;for(const r of rows){if(used>=maxChars)break;const room=maxChars-used,text=r.text.slice(0,room);if(!text)break;items.push({...r,text});used+=text.length;}const fingerprint=fourAr5Sha(items.map(x=>({evidence_id:x.evidence_id,url:x.url,evidence_class:x.evidence_class,score:x.score,spec_operation_count:x.spec_operation_count,response_property_count:x.response_property_count,text_fingerprint:fourAr5Sha(x.text)})));return {items,fingerprint,total_chars:used};}
