import {deriveExperiment5b2Source} from "./experiment5b2Derivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`5b3_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
function replaceBetween(s:string,start:string,end:string,replacement:string){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);if(a<0||b<0)throw new Error(`5b3_range_anchor_missing:${start}`);return s.slice(0,a)+replacement+s.slice(b)}
export function deriveExperiment5b3Source(source:string){let x=deriveExperiment5b2Source(source);
x=r(x,'import {callProviderReranker,parseRerankAttempt} from "./experiment3vPlanner.js";','import {deterministicProviderSelection5B3,providerOrderingDeterminism5B3} from "./experiment5b3Provider.js";');
x=r(x,'import {compile5b2 as compile4ar,project5b2 as project4ar,scope5b2 as scope4ar,validate5b2 as validate4ar,validateProjected5b2 as validateProjected4ar} from "./experiment5b2Contract.js";','import {compile5b3 as compile4ar,project5b3 as project4ar,scope5b3 as scope4ar,validate5b3 as validate4ar,validateProjected5b3 as validateProjected4ar} from "./experiment5b3Contract.js";');
x=r(x,'import {synthesize5b2 as synthesize4ar} from "./experiment5b2Planner.js";','import {synthesize5b3 as synthesize4ar} from "./experiment5b3Planner.js";');
x=r(x,'const OUT="results/experiment-5b2-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-5b3-engine",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
const deterministicRerank='async function rerank(config:any,c:any,broad:any[],evidence:any[]){const d=deterministicProviderSelection5B3(c,broad),check=providerOrderingDeterminism5B3(c,broad),error=check.ok?null:"5b3_provider_ordering_nondeterministic";evidence.push({case_id:c.case_id,phase:"deterministic_5b3",ordering_fingerprint:d.fingerprint,ordering:d.ordering,metrics:{...d.metrics,providerOrderingNondeterminismRejects5b3:check.ok?0:1},error});return {selection:error?null:d.selection,error};}\n';
x=replaceBetween(x,'async function rerank(config:any,c:any,broad:any[],evidence:any[]){','async function synthesize(',deterministicRerank);
x=r(x,'semantic_identity_witness_5b2:a.parsed_json?.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:a.parsed_json?.input_output_compatibility_fingerprint_5b2??null,cross_graph_rank_5b2:a.parsed_json?.cross_graph_rank_5b2??null,cross_graph_recovered_5b2:a.parsed_json?.cross_graph_recovered_5b2===true};','semantic_identity_witness_5b2:a.parsed_json?.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:a.parsed_json?.input_output_compatibility_fingerprint_5b2??null,request_utility_rank_5b3:a.parsed_json?.request_utility_rank_5b3??null,request_utility_primary_displaced_5b3:a.parsed_json?.request_utility_primary_displaced_5b3===true,request_utility_recovered_5b3:a.parsed_json?.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:a.parsed_json?.request_ordering_fingerprint_5b3??null};');
x=r(x,'semantic_identity_witness_5b2:syn.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:syn.input_output_compatibility_fingerprint_5b2??null,cross_graph_rank_5b2:syn.cross_graph_rank_5b2??null,cross_graph_recovered_5b2:syn.cross_graph_recovered_5b2===true,contract,contract_fingerprint:sha3yr(contract)','semantic_identity_witness_5b2:syn.semantic_identity_witness_5b2??null,input_output_compatibility_fingerprint_5b2:syn.input_output_compatibility_fingerprint_5b2??null,request_utility_rank_5b3:syn.request_utility_rank_5b3??null,request_utility_primary_displaced_5b3:syn.request_utility_primary_displaced_5b3===true,request_utility_recovered_5b3:syn.request_utility_recovered_5b3===true,request_ordering_fingerprint_5b3:syn.request_ordering_fingerprint_5b3??null,contract,contract_fingerprint:sha3yr(contract)');
x=x.replaceAll('experiment:"5B2-ENGINE"','experiment:"5B3-ENGINE"').replaceAll('purpose:"development_semantic_identity_witness_cross_graph_beam_engine"','purpose:"development_deterministic_provider_output_aware_beam_engine"').replaceAll('base_sha:"8648ab3a97b98aaa61ec4feec7752f01423b36c4"','base_sha:"cd85224d9e21ba3e0ddf5de02e371872a2931c37"');
x=x.replaceAll('./experiment5b2Planner.ts','./experiment5b3Planner.ts').replaceAll('./experiment5b2Contract.ts','./experiment5b3Contract.ts').replaceAll('./experiment5b2Derivation.ts','./experiment5b3Derivation.ts');
x=x.replace('(await readFile(new URL("./experiment5b2Semantics.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+','(await readFile(new URL("./experiment5b2Semantics.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b3Provider.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment5b3RequestUtility.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4uOpenApi.ts",import.meta.url),"utf8"))+');
return x}
