import {deriveExperiment4qSource} from "./experiment4qDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4r_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4rSource(source:string){let x=deriveExperiment4qSource(source);
x=r(x,'import {compile4q as compile4ar,project4q as project4ar,scope4q as scope4ar,validate4q as validate4ar,validateProjected4q as validateProjected4ar} from "./experiment4qContract.js";','import {compile4r as compile4ar,project4r as project4ar,scope4r as scope4ar,validate4r as validate4ar,validateProjected4r as validateProjected4ar} from "./experiment4rContract.js";\nimport {decodeStructured4R} from "./experiment4rDecode.js";');
x=r(x,'import {synthesize4q as synthesize4ar} from "./experiment4qPlanner.js";','import {synthesize4r as synthesize4ar} from "./experiment4rPlanner.js";');
x=r(x,'const OUT="results/experiment-4q",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4r",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
x=r(x,'async function safeJson(url:string,ledger:RecoveryLedger){liveCalls++;const t0=Date.now(),got=await fetchTextSafeR2(url,url,MAX_BYTES,ledger);let body:any;try{body=JSON.parse(got.text);}catch{throw new Error("response_not_json");}return {body,latency_ms:Date.now()-t0,requested_at:new Date().toISOString(),body_fingerprint:sha3yr(got.text),final_url:got.final_url};}','async function safeJson(url:string,ledger:RecoveryLedger){liveCalls++;const t0=Date.now(),got=await fetchTextSafeR2(url,url,MAX_BYTES,ledger),decoded=decodeStructured4R(got.text,got.content_type,url);return {body:decoded.body,structured_format:decoded.format,latency_ms:Date.now()-t0,requested_at:new Date().toISOString(),body_fingerprint:sha3yr(got.text),final_url:got.final_url};}');
x=r(x,'identityProjectionSelections4q=0;const rerankConcurrencyLimit4p=3;','identityProjectionSelections4q=0,structuredDecoderNonJsonSuccesses4r=0,structuredDecoderXmlSuccesses4r=0,structuredDecoderCsvSuccesses4r=0,compositionalLockedBindings4r=0,exactRelationalLabelSelections4r=0,lockedBindingMutations4r=0,nonJsonConfirmedRecipes4r=0;const rerankConcurrencyLimit4p=3;');
x=r(x,'if(a.identity_projection_selected)identityProjectionSelections4q++;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;','if(a.identity_projection_selected)identityProjectionSelections4q++;structuredDecoderNonJsonSuccesses4r+=a.structuredDecoderNonJsonSuccesses||0;structuredDecoderXmlSuccesses4r+=a.structuredDecoderXmlSuccesses||0;structuredDecoderCsvSuccesses4r+=a.structuredDecoderCsvSuccesses||0;compositionalLockedBindings4r+=a.compositional_locked_bindings||0;exactRelationalLabelSelections4r+=a.exact_relational_label_selections||0;lockedBindingMutations4r+=a.locked_binding_mutations||0;relationalArrayCandidates4o+=a.relationalArrayCandidates||0;');
x=x.replaceAll('4q_request_hypothesis_not_in_trace_graph','4r_request_hypothesis_not_in_trace_graph').replaceAll('4q_trace_origin_drift','4r_trace_origin_drift').replaceAll('4q_trace_request_mutation','4r_trace_request_mutation').replaceAll('4q_row_lookup_not_observed','4r_row_lookup_not_observed').replaceAll('4q_forbidden_input_source','4r_forbidden_input_source');
x=r(x,'executedTraceDocumentedRoleConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_documented_role_")).length,rowLookupConfirmedRecipes=', 'executedTraceDocumentedRoleConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_documented_role_")).length;nonJsonConfirmedRecipes4r=recipes.filter(r=>r.first_verification?.structured_format&&r.first_verification.structured_format!=="json").length;const rowLookupConfirmedRecipes=');
x=r(x,'identityProjectionSelections:identityProjectionSelections4q,rerankPreparedCases:rerankPreparedCases4p','identityProjectionSelections:identityProjectionSelections4q,structuredDecoderNonJsonSuccesses:structuredDecoderNonJsonSuccesses4r,structuredDecoderXmlSuccesses:structuredDecoderXmlSuccesses4r,structuredDecoderCsvSuccesses:structuredDecoderCsvSuccesses4r,compositionalLockedBindings:compositionalLockedBindings4r,exactRelationalLabelSelections:exactRelationalLabelSelections4r,lockedBindingMutations:lockedBindingMutations4r,nonJsonConfirmedRecipes:nonJsonConfirmedRecipes4r,rerankPreparedCases:rerankPreparedCases4p');
x=r(x,'identity_projection_integrity:forbiddenInputSourceSelections4o===0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,','identity_projection_integrity:forbiddenInputSourceSelections4o===0,structured_decoder_non_json_success:structuredDecoderNonJsonSuccesses4r>=1,non_json_confirmed_recipe:nonJsonConfirmedRecipes4r>=1,compositional_locked_bindings_active:compositionalLockedBindings4r>=2,exact_relational_label_selection_active:exactRelationalLabelSelections4r>=1,locked_binding_mutations_zero:lockedBindingMutations4r===0,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,');
x=x.replaceAll('4Q_EVIDENCE_PREFERENCE_IDENTITY:','4R_STRUCTURED_IR_COMPOSITIONAL:').replaceAll('4Q_MAPPING_REJECT','4R_MAPPING_REJECT').replaceAll('GO_4Q_EVIDENCE_PREFERENCE_IDENTITY_PRESERVING_PROJECTION','GO_4R_REPRESENTATION_AGNOSTIC_RESPONSE_IR_COMPOSITIONAL_PROJECTION').replaceAll('REASSESS_4Q_EVIDENCE_PREFERENCE_IDENTITY_PRESERVING_PROJECTION','REASSESS_4R_REPRESENTATION_AGNOSTIC_RESPONSE_IR_COMPOSITIONAL_PROJECTION');
x=r(x,'experiment:"4Q",purpose:"development_evidence_preference_identity_preserving_projection"','experiment:"4R",purpose:"development_representation_agnostic_response_ir_compositional_projection"');
x=r(x,'base_sha:"89360e887796f967d987d9c08a4841d457cb66c1"','base_sha:"fd5a32ace7cfbf6b11e86040da892b1d0a1238b1"');
x=x.replaceAll('./experiment4qPlanner.ts','./experiment4rPlanner.ts').replaceAll('./experiment4qContract.ts','./experiment4rContract.ts').replaceAll('./experiment4qDerivation.ts','./experiment4rDerivation.ts');
x=x.replace('plannerSource=(await readFile(new URL("./experiment4rPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qPreference.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qRequest.ts",import.meta.url),"utf8"))+','plannerSource=(await readFile(new URL("./experiment4rPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4rCore.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4rProbe.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4rDecode.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qPreference.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4qRequest.ts",import.meta.url),"utf8"))+');return x}
