import type {DocEvidence} from "./experiment3wCore.js";
import type {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES} from "./experiment4aCore.js";
import {FOUR_AP1_MAX_PROBES_PER_PROVIDER,fourAp1Sha,type P1RequestHypothesis,type P1RequestSlot} from "./experiment4ap1Model.js";
import {compileRequestHypothesisP1,lexicalTokensP1} from "./experiment4ap1Request.js";
import {prepareRequestGraph4L,rebuildRequestGraph4L} from "./experiment4lRequest.js";

const AUTH=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const ASSET_EXT=/\.(?:js|mjs|css|map|png|jpe?g|gif|svg|webp|ico|bmp|avif|woff2?|ttf|otf|eot|mp4|webm|mp3|wav|pdf)(?:$|[?#])/i;
const ASSET_SEG=/(?:^|\/)(?:static|assets?|images?|img|icons?|logos?|fonts?|styles?|scripts?|css|js|media|thumbnails?|avatars?)(?:\/|$)/i;
const NAV_SEG=/(?:^|\/)(?:docs?|documentation|help|support|blog|about|contact|login|signin|signup|register|pricing|careers?|press|terms|privacy|downloads?)(?:\/|$)/i;
const ACTION=new Set(["get","lookup","search","find","retrieve","fetch","decode","estimate","resolve","convert","list","identify"]);
const NOISE=new Set(["given","public","machine","readable","api","operation","return","returns","canonical","current","human","identify","identifier","identification","metadata","string","numeric","number","matching","queried","query","estimated","information","data","value","values","result","results","using","use","provide","provides"]);

type Pos={kind:"path";index:number}|{kind:"query";key:string};
type ParsedTrace={evidence:DocEvidence;origin:string;path:string;segments:string[];query:{key:string;rawKey:string;value:string}[]};
type TraceMember={trace:ParsedTrace;value:string};
type TraceFamily={signature:string;position:Pos;members:Map<string,TraceMember>};
type Metrics=Record<string,number|boolean>;

function norm(v:any){let s=String(v??"");try{s=decodeURIComponent(s.replace(/\+/g," "))}catch{}return s.trim().toLowerCase()}
function tokens(v:string){return lexicalTokensP1(v)}
function splitPath(path:string){const q=path.indexOf("?");return {head:q<0?path:path.slice(0,q),query:q<0?"":path.slice(q+1)}}
function parseQuery(raw:string){if(!raw)return [] as ParsedTrace["query"];return raw.split("&").filter(Boolean).map(part=>{const i=part.indexOf("="),rawKey=i<0?part:part.slice(0,i),value=i<0?"":part.slice(i+1);return {key:norm(rawKey.replace(/^amp;/i,"")),rawKey,value:norm(value)}})}
function hardReason(url:URL){if(ASSET_EXT.test(url.pathname)||ASSET_SEG.test(url.pathname))return "asset";if(NAV_SEG.test(url.pathname)&&!/(?:^|\/)api(?:\/|$)/i.test(url.pathname))return "navigation";return null}
function parsedTrace(e:DocEvidence){if(e.state!=="ok"||!e.requested_url?.startsWith("https://"))return null;let u:URL;try{u=new URL(e.requested_url)}catch{return null}const r=hardReason(u);if(r)return {reject:r as "asset"|"navigation",trace:null};const query=parseQuery(u.search.slice(1));if(query.some(q=>AUTH.test(q.key)))return {reject:"auth" as const,trace:null};return {reject:null,trace:{evidence:e,origin:u.origin,path:u.pathname+u.search,segments:u.pathname.split("/").map(norm),query} satisfies ParsedTrace}}
function scalarEcho(text:string,value:string){const n=norm(value);if(n.length<3)return false;try{const body=JSON.parse(text),stack=[body];while(stack.length){const x=stack.pop();if(x===null||x===undefined)continue;if(typeof x==="string"||typeof x==="number"||typeof x==="boolean"){if(norm(x)===n)return true;continue}if(Array.isArray(x)){for(const y of x)stack.push(y);continue}if(typeof x==="object")for(const y of Object.values(x))stack.push(y)}}catch{}const escaped=n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`,`i`).test(norm(text))}
function semanticSupport(caseId:string,traces:ParsedTrace[]){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return {entity:false,secondary:false};const sample=traces.map(t=>`${t.path} ${t.evidence.text.slice(0,12000)}`).join(" "),op=new Set(tokens(sample)),intent=new Set(tokens(c.intent||"")),outputs=new Set(c.required.flatMap(x=>tokens(x))),inputs=new Set(c.input_names.flatMap(x=>tokens(x))),entity=[...intent].filter(x=>!ACTION.has(x)&&!outputs.has(x)&&!inputs.has(x)&&!NOISE.has(x)&&x.length>2),actions=[...intent].filter(x=>ACTION.has(x));return {entity:entity.some(x=>op.has(x)),secondary:[...outputs].some(x=>op.has(x))||(actions.length>0&&actions.some(x=>op.has(x)))}}
function shape(v:string){const s=norm(v);if(/^\d+$/.test(s))return "numeric";if(/^[a-z]+$/i.test(s))return "alpha";if(/^[a-z0-9]+$/i.test(s))return "alnum";if(/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(s))return "uuid";return "other"}
function valueAt(t:ParsedTrace,p:Pos){if(p.kind==="path")return t.segments[p.index]||"";return t.query.find(q=>q.key===p.key)?.value||""}
function sig(t:ParsedTrace,p:Pos){const seg=[...t.segments];if(p.kind==="path")seg[p.index]="*";const q=t.query.map(x=>[x.key,p.kind==="query"&&x.key===p.key?"*":x.value] as const).sort((a,b)=>a[0].localeCompare(b[0]));return fourAp1Sha({o:t.origin,s:seg,q,p})}
function replacePos(t:ParsedTrace,p:Pos,input:string){if(p.kind==="query")return t.path;const {head,query}=splitPath(t.path),segments=head.split("/");segments[p.index]=`{${input}}`;return segments.join("/")+(query?`?${query}`:"")}
function buildHyp(trace:ParsedTrace,pos:Pos,input:string,proof:string,score:number,supportIds:string[]){const slotName=pos.kind==="path"?input:pos.key,slot:P1RequestSlot={id:`4m_slot_${fourAp1Sha({url:trace.evidence.requested_url,pos,input}).slice(0,14)}`,name:slotName,in:pos.kind,required:true,auth_like:false,literals:[]};return {id:`req4m_${fourAp1Sha({url:trace.evidence.requested_url,pos,input,proof}).slice(0,16)}`,source_operation_id:`trace_${fourAp1Sha(trace.evidence.requested_url).slice(0,14)}`,origin:trace.origin,full_path:replacePos(trace,pos,input),proof_type:proof,evidence_ids:[...new Set([trace.evidence.evidence_id,...supportIds])],source_urls:[trace.evidence.requested_url],slots:[slot],input_bindings:{[input]:slot.id},literal_bindings:{},score,concrete_relation:true} satisfies P1RequestHypothesis}
function metrics0():Metrics{return {acquisitionTraceEvents:0,acquisitionTraceDistinctUrls:0,acquisitionTraceEligible:0,acquisitionTraceRejectedAsset:0,acquisitionTraceRejectedNavigation:0,acquisitionTraceRejectedDocumentation:0,acquisitionTraceRejectedLineage:0,acquisitionTraceRejectedAuthLike:0,acquisitionTraceExactBuildValueSlots:0,acquisitionTraceFamilySlots:0,acquisitionTraceEchoSupportedSlots:0,acquisitionTraceHypotheses:0}}

export function buildAcquisitionTraceHypotheses4M(evidence:DocEvidence[],caseId:string){
  const metrics=metrics0(),c=FOUR_A_CASES.find(x=>x.case_id===caseId),hypotheses:P1RequestHypothesis[]=[];if(!c||c.input_names.length!==1)return {hypotheses,metrics};const input=c.input_names[0],build=norm(c.build[input]),provider=evidence.find(e=>e.provider_candidate_id)?.provider_candidate_id,traces:ParsedTrace[]=[];
  metrics.acquisitionTraceEvents=evidence.filter(e=>e.state==="ok").length;metrics.acquisitionTraceDistinctUrls=new Set(evidence.filter(e=>e.state==="ok").map(e=>e.requested_url)).size;
  for(const e of evidence){if(provider&&e.provider_candidate_id!==provider){metrics.acquisitionTraceRejectedLineage=Number(metrics.acquisitionTraceRejectedLineage)+1;continue}const p=parsedTrace(e);if(!p)continue;if(p.reject){if(p.reject==="asset")metrics.acquisitionTraceRejectedAsset=Number(metrics.acquisitionTraceRejectedAsset)+1;else if(p.reject==="navigation")metrics.acquisitionTraceRejectedNavigation=Number(metrics.acquisitionTraceRejectedNavigation)+1;else metrics.acquisitionTraceRejectedAuthLike=Number(metrics.acquisitionTraceRejectedAuthLike)+1;continue}traces.push(p.trace!)}
  metrics.acquisitionTraceEligible=traces.length;const semantic=semanticSupport(caseId,traces);
  if(semantic.entity&&semantic.secondary&&build.length>=3){for(const t of traces){const matches:Pos[]=[];for(let i=0;i<t.segments.length;i++)if(t.segments[i]===build)matches.push({kind:"path",index:i});for(const q of t.query)if(q.value===build)matches.push({kind:"query",key:q.key});if(matches.length===1){const echo=scalarEcho(t.evidence.text,build);if(echo)metrics.acquisitionTraceEchoSupportedSlots=Number(metrics.acquisitionTraceEchoSupportedSlots)+1;hypotheses.push(buildHyp(t,matches[0],input,`4m_executed_trace_exact_${matches[0].kind}`,1180+(echo?30:0),[]));metrics.acquisitionTraceExactBuildValueSlots=Number(metrics.acquisitionTraceExactBuildValueSlots)+1}}}
  const families=new Map<string,TraceFamily>();for(const t of traces){for(let i=0;i<t.segments.length;i++){if(!t.segments[i])continue;const p:Pos={kind:"path",index:i},k=sig(t,p),f=families.get(k)||{signature:k,position:p,members:new Map()};f.members.set(t.evidence.evidence_id,{trace:t,value:valueAt(t,p)});families.set(k,f)}for(const q of t.query){const p:Pos={kind:"query",key:q.key},k=sig(t,p),f=families.get(k)||{signature:k,position:p,members:new Map()};f.members.set(t.evidence.evidence_id,{trace:t,value:valueAt(t,p)});families.set(k,f)}}
  for(const f of families.values()){const members=[...f.members.values()],values=[...new Set(members.map(m=>m.value).filter(Boolean))];if(members.length<2||values.length<2||!semantic.entity||!semantic.secondary)continue;if(!values.every(v=>shape(v)===shape(build)))continue;const rep=[...members].sort((a,b)=>a.trace.evidence.evidence_id.localeCompare(b.trace.evidence.evidence_id))[0],echo=members.some(m=>scalarEcho(m.trace.evidence.text,m.value));if(echo)metrics.acquisitionTraceEchoSupportedSlots=Number(metrics.acquisitionTraceEchoSupportedSlots)+1;hypotheses.push(buildHyp(rep.trace,f.position,input,`4m_executed_trace_family_${f.position.kind}`,1110+(echo?20:0),members.map(m=>m.trace.evidence.evidence_id)));metrics.acquisitionTraceFamilySlots=Number(metrics.acquisitionTraceFamilySlots)+1}
  const dedup=new Map<string,P1RequestHypothesis>();for(const h of hypotheses){const key=fourAp1Sha({o:h.origin,p:h.full_path,b:h.input_bindings});const prior=dedup.get(key);if(!prior||h.score>prior.score)dedup.set(key,h)}const rows=[...dedup.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));metrics.acquisitionTraceHypotheses=rows.length;return {hypotheses:rows,metrics};
}
function render(h:P1RequestHypothesis,caseId:string){const c=FOUR_A_CASES.find(x=>x.case_id===caseId);if(!c)return null;try{return compileRequestHypothesisP1(h,c.build)}catch{return null}}
function augment(base:any,evidence:DocEvidence[],caseId:string){const trace=buildAcquisitionTraceHypotheses4M(evidence,caseId),dedup=new Map<string,P1RequestHypothesis>();for(const h of [...(base.hypotheses as P1RequestHypothesis[]),...trace.hypotheses]){const key=fourAp1Sha({o:h.origin,p:h.full_path,b:h.input_bindings,l:h.literal_bindings}),prior=dedup.get(key);if(!prior||h.score>prior.score)dedup.set(key,h)}const hypotheses=[...dedup.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));return {...base,hypotheses,metrics:{...base.metrics,...trace.metrics},graph_fingerprint:fourAp1Sha({base:base.graph_fingerprint,h:hypotheses.map(h=>h.id),trace:trace.metrics})}}
function packet(hypotheses:P1RequestHypothesis[],caseId:string){const trace=hypotheses.filter(h=>h.proof_type.startsWith("4m_executed_trace_")),legacy=hypotheses.filter(h=>!h.proof_type.startsWith("4m_executed_trace_")),ordered=trace.length?[...legacy.slice(0,2),trace[0],...legacy.slice(2),...trace.slice(1)]:legacy,seen=new Set<string>(),out:P1RequestHypothesis[]=[];let duplicate=0;for(const h of ordered){const u=render(h,caseId);if(!u)continue;if(seen.has(u)){duplicate++;continue}seen.add(u);out.push(h);if(out.length>=FOUR_AP1_MAX_PROBES_PER_PROVIDER)break}return {out,seen,duplicate}}
export async function prepareRequestGraph4M(evidence:DocEvidence[],caseId:string,ledger:RecoveryLedger){const base=await prepareRequestGraph4L(evidence,caseId,ledger),g=augment(base,evidence,caseId),p=packet(g.hypotheses as P1RequestHypothesis[],caseId);return {...g,probe_packet:p.out,metrics:{...g.metrics,requestHypotheses:g.hypotheses.length,uniqueRenderedProbeUrls:p.seen.size,duplicateRenderedProbeUrlsRejected4m:p.duplicate,acquisitionTracePacketHypotheses:p.out.filter(h=>h.proof_type.startsWith("4m_executed_trace_")).length,noIrOperation:g.semantics.operations.length===0,irOperationUnusable:g.semantics.operations.length>0&&g.hypotheses.length===0}}}
export function rebuildRequestGraph4M(evidence:DocEvidence[],caseId:string){return augment(rebuildRequestGraph4L(evidence,caseId),evidence,caseId)}
