import { mkdir, writeFile } from "node:fs/promises";
import { Client, StreamableHTTPClientTransport, SSEClientTransport } from "@modelcontextprotocol/client";

const REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
const MAX_SERVERS=58,MAX_SOURCE_EXECUTIONS=24,MAX_COMPOSITION_ATTEMPTS=35,MAX_RECIPES=3,TIMEOUT_MS=12000;
const READ_WORDS=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUTATION_WORDS=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","unsubscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
const PLACEHOLDERS=new Set(["unable","unknown","none","null","n/a","na","undefined","error","failed",""]);
const STOP=new Set(["the","a","an","current","target","source","input","output","value","data","result","item","object"]);
const ALIAS:Record<string,string>={id:"identifier",identifier:"identifier",key:"identifier",url:"url",uri:"url",link:"url",href:"url",repo:"repository",repository:"repository",org:"organization",organization:"organization",organisation:"organization",user:"user",username:"user",account:"user",path:"path",route:"path",name:"name",title:"name",lang:"language",language:"language",locale:"language",country:"country",nation:"country",city:"city",town:"city",code:"code",slug:"code"};
let unsafeToolsExecuted=0,credentialsSupplied=0,plannerCalls=0,embeddingCalls=0,authErrorResultsCountedAsSuccess=0;

type Candidate={name:string;namespace:string;url:string;transport:string};
type ToolRef={server:Candidate;tool:any;safe:boolean;reasons:string[]};
type Scalar={path:string;name:string;type:"string"|"number"|"boolean";value:any};
function namespaceOf(name:string){return name.includes("/")?name.split("/")[0]:name.includes(":")?name.split(":")[0]:name;}
function timeout<T>(p:Promise<T>):Promise<T>{return new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error(`timeout_${TIMEOUT_MS}`)),TIMEOUT_MS);p.then(v=>{clearTimeout(t);res(v)},e=>{clearTimeout(t);rej(e)});});}
function remoteType(x:any){return String(x?.type??x?.transport??"").toLowerCase();} function remoteUrl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
function eligibleRemote(r:any){const t=remoteType(r),u=remoteUrl(r);if(!["streamable-http","sse"].includes(t)||typeof u!=="string"||!u.startsWith("https://")||/[{}]/.test(u))return false;const h=r?.headers;return !(h&&((Array.isArray(h)&&h.length)||(!Array.isArray(h)&&Object.keys(h).length)));}
async function fetchRegistry(){const r=await fetch(REGISTRY_URL,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3I/0.1"}});if(!r.ok)throw new Error(`registry_${r.status}`);return r.json() as Promise<any>;}
function recordsOf(b:any){return Array.isArray(b)?b:Array.isArray(b?.servers)?b.servers:Array.isArray(b?.data)?b.data:Array.isArray(b?.items)?b.items:[];}
function candidatesOf(records:any[]){const out:Candidate[]=[];for(const raw of records){const s=raw?.server??raw;const status=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(status))continue;const name=String(s?.name??raw?.name??"");if(!name)continue;const r=(s?.remotes??raw?.remotes??[]).find(eligibleRemote);if(r)out.push({name,namespace:namespaceOf(name),url:remoteUrl(r),transport:remoteType(r)});}out.sort((a,b)=>a.name.localeCompare(b.name)||a.url.localeCompare(b.url));const seen=new Set<string>();return out.filter(x=>!seen.has(x.name)&&!!seen.add(x.name));}
function hasWord(text:string,words:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return words.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
function required(t:any){return Array.isArray(t?.inputSchema?.required)?t.inputSchema.required:[];}
function classify(t:any){const r:string[]=[];if(!t?.inputSchema||typeof t.inputSchema!=="object"||Array.isArray(t.inputSchema))r.push("invalid_input_schema");if(t?.annotations?.readOnlyHint!==true)r.push("missing_readonly_hint");if(t?.annotations?.destructiveHint===true)r.push("destructive_hint_true");const text=`${t?.name??""} ${t?.description??""}`;if(!hasWord(text,READ_WORDS))r.push("no_read_signal");if(hasWord(text,MUTATION_WORDS))r.push("mutation_signal");return {safe:r.length===0,reasons:r};}
function transport(c:Candidate){return c.transport==="sse"?new SSEClientTransport(new URL(c.url)):new StreamableHTTPClientTransport(new URL(c.url));}
async function connectAndList(c:Candidate){const client=new Client({name:"missing-experiment-3i",version:"0.1.0"});await timeout(client.connect(transport(c)));const listed:any=await timeout(client.listTools());return {client,tools:listed.tools??[]};}
async function call(client:Client,t:any,args:any){if(!classify(t).safe)unsafeToolsExecuted++;return timeout(client.callTool({name:t.name,arguments:args}));}
function splitTokens(s:string){return s.replace(/([a-z0-9])([A-Z])/g,"$1 $2").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);}
function canonicalTokens(s:string){return [...new Set(splitTokens(s).map(x=>ALIAS[x]??x).filter(x=>!STOP.has(x)))].sort();}
function canonical(s:string){return canonicalTokens(s).join("+");}
function norm(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,"");}
function runtimeType(v:any):"string"|"number"|"boolean"|null{return typeof v==="string"?"string":typeof v==="number"&&Number.isFinite(v)?"number":typeof v==="boolean"?"boolean":null;}
function placeholder(v:any){return typeof v==="string"&&PLACEHOLDERS.has(v.trim().toLowerCase());}
function flatten(v:any,path="",out:Scalar[]=[]){if(out.length>=80)return out;const t=runtimeType(v);if(t){const name=(path.split(".").pop()??"value").replace(/^\d+$/,"value");if(!(t==="string"&&(v.length>200||placeholder(v))))out.push({path:path||"$",name,type:t,value:v});return out;}if(Array.isArray(v)){for(let i=0;i<Math.min(v.length,10);i++)flatten(v[i],path?`${path}.${i}`:`${i}`,out);}else if(v&&typeof v==="object")for(const k of Object.keys(v).sort().slice(0,40))flatten(v[k],path?`${path}.${k}`:k,out);return out;}
function structured(r:any){if(r?.structuredContent&&typeof r.structuredContent==="object")return r.structuredContent;const texts=(r?.content??[]).filter((x:any)=>x?.type==="text"&&typeof x.text==="string");if(texts.length===1)try{const p=JSON.parse(texts[0].text);if(p&&typeof p==="object")return p;}catch{}return null;}
function targetSpec(t:any){const req=required(t);if(req.length!==1)return null;const p=req[0],s=t.inputSchema?.properties?.[p];if(!s||typeof s!=="object")return null;const type=s.type==="integer"?"number":s.type;if(!["string","number","boolean"].includes(type))return null;return {param:p,type,description:String(s.description??"")};}
function functional(r:any){if(!r||r.isError===true)return false;const content=(Array.isArray(r.content)&&r.content.length>0)||(r.structuredContent&&typeof r.structuredContent==="object"&&Object.keys(r.structuredContent).length>0);if(!content)return false;const s=JSON.stringify(r);return !/authentication required|unauthorized|forbidden|requires a subscriber|requires an api key|"error"\s*:\s*"[^"\n]+"|\berror:/i.test(s);}
function contextEvidence(tokens:string[],src:any,tgt:any,spec:any){const text=`${src.tool.description??""} ${tgt.tool.description??""} ${spec.description??""}`.toLowerCase();return tokens.filter(x=>new RegExp(`\\b${x}\\b`,`i`).test(text));}
async function executeSource(ref:ToolRef){const {client,tools}=await connectAndList(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe||required(t).length!==0){await client.close();throw new Error("source_invalid");}try{const result=await call(client,t,{});if(!functional(result))throw new Error("source_functional_failure");return {result,scalars:flatten(structured(result))};}finally{await client.close();}}
async function executeTarget(ref:ToolRef,param:string,value:any){const {client,tools}=await connectAndList(ref.server);const t=tools.find((x:any)=>x.name===ref.tool.name);if(!t||!classify(t).safe){await client.close();throw new Error("target_invalid");}try{const result=await call(client,t,{[param]:value});if(!functional(result))throw new Error("target_functional_failure");return {result,args:{[param]:value}};}finally{await client.close();}}
function getPath(v:any,path:string){return path==="$"?v:path.split(".").reduce((x,k)=>x?.[k],v);}

const registry=await fetchRegistry(),records=recordsOf(registry),candidates=candidatesOf(records),tools:ToolRef[]=[],discovery:any[]=[];
for(const c of candidates.slice(0,MAX_SERVERS)){try{const {client,tools:list}=await connectAndList(c);for(const t of list){const d=classify(t);tools.push({server:c,tool:t,...d});}discovery.push({server:c,tool_count:list.length});await client.close();}catch(e){discovery.push({server:c,error:String(e)});}}
const sources=tools.filter(x=>x.safe&&required(x.tool).length===0),targets=tools.filter(x=>x.safe&&targetSpec(x.tool));const sourceEvidence:any[]=[],rejected:any[]=[],recipes:any[]=[];let sourceExecs=0,attempts=0;
for(const src of sources){if(sourceExecs>=MAX_SOURCE_EXECUTIONS||recipes.length>=MAX_RECIPES)break;let sx:any;try{sx=await executeSource(src);sourceExecs++;sourceEvidence.push({server:src.server.name,tool:src.tool.name,scalars:sx.scalars});}catch(e){continue;}for(const tgt of targets){if(attempts>=MAX_COMPOSITION_ATTEMPTS||recipes.length>=MAX_RECIPES)break;if(src.server.name===tgt.server.name){rejected.push({reason:"same_server"});continue;}const spec=targetSpec(tgt.tool)!;let match:any=null,evidence:string[]=[];for(const s of sx.scalars){const ct=canonicalTokens(s.name),cc=ct.join("+");if(s.type===spec.type&&cc&&cc===canonical(spec.param)&&norm(s.name)!==norm(spec.param)&&!placeholder(s.value)){const ev=contextEvidence(ct,src,tgt,spec);if(ev.length){match=s;evidence=ev;break;}}}if(!match){rejected.push({source:src.tool.name,target:tgt.tool.name,reason:"canonical_type_context_mismatch"});continue;}attempts++;try{const tx=await executeTarget(tgt,spec.param,match.value);recipes.push({recipe:{canonical_concept:canonical(match.name),evidence_tokens:evidence,source_server:src.server,source_tool:src.tool.name,source_path:match.path,source_leaf:match.name,target_server:tgt.server,target_tool:tgt.tool.name,target_parameter:spec.param,target_type:spec.type},first_execution:{source_value:match.value,target_args:tx.args,target_result:tx.result}});}catch(e){rejected.push({source:src.tool.name,target:tgt.tool.name,reason:`outcome_failed:${String(e)}`});}}
}
const replay:any[]=[];for(const e of recipes){const r=e.recipe;try{const sref=tools.find(x=>x.server.name===r.source_server.name&&x.tool.name===r.source_tool)!;const tref=tools.find(x=>x.server.name===r.target_server.name&&x.tool.name===r.target_tool)!;const sx=await executeSource(sref),value=getPath(structured(sx.result),r.source_path);if(runtimeType(value)!==r.target_type||placeholder(value)||canonical(r.source_leaf)!==canonical(r.target_parameter))throw new Error("replay_bridge_invalid");const tx=await executeTarget(tref,r.target_parameter,value);replay.push({recipe:r,success:true,source_value:value,target_result:tx.result});}catch(e){replay.push({recipe:r,success:false,error:String(e)});}}
const rs=replay.filter(x=>x.success).length,rate=recipes.length?rs/recipes.length:0;const criteria={one_different_surface_bridge:recipes.length>=1,one_replay:rs>=1,replay_success_rate:rate===1,canonical_and_context:recipes.every(x=>x.recipe.canonical_concept&&x.recipe.evidence_tokens.length>0),zero_direct_exact_names:recipes.every(x=>norm(x.recipe.source_leaf)!==norm(x.recipe.target_parameter)),zero_placeholders:recipes.every(x=>!placeholder(x.first_execution.source_value)),zero_auth_error_success:authErrorResultsCountedAsSuccess===0,zero_unsafe:unsafeToolsExecuted===0,zero_credentials:credentialsSupplied===0,zero_planner_llm_embeddings:plannerCalls===0&&embeddingCalls===0,thirty_rejections:rejected.length>=30,evidence_persisted:true};const decision=Object.values(criteria).every(Boolean)?"GO_CANONICAL_SEMANTIC_BRIDGE":"REASSESS_CANONICAL_SEMANTIC_BRIDGE";
const summary={experiment:"MISSING Experiment 3I — Canonical Semantic Bridge",created_at:new Date().toISOString(),metrics:{registry_records:records.length,eligible_servers:candidates.length,servers_inspected:discovery.length,discovered_tools:tools.length,sources:sources.length,targets:targets.length,source_executions:sourceExecs,composition_attempts:attempts,successful_recipes:recipes.length,replay_successes:rs,replay_success_rate:rate,rejected_pairs:rejected.length,unsafe_tools_executed:unsafeToolsExecuted,credentials_supplied:credentialsSupplied,planner_llm_embedding_calls:plannerCalls+embeddingCalls},criteria,decision,recipes,replay};
await mkdir("results/experiment-3i",{recursive:true});await writeFile("results/experiment-3i/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3i/evidence.json",JSON.stringify({registry_url:REGISTRY_URL,raw_registry:registry,discovery,source_evidence:sourceEvidence,rejected_pairs:rejected,recipes,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));