import type {DocEvidence} from "./experiment3wCore.js";
import {fourAp1Sha} from "./experiment4ap1Model.js";

const AUTH_NAME=/^(?:api[_-]?key|apikey|key|token|access[_-]?token|secret|authorization|auth|client[_-]?id|client[_-]?secret)$/i;
const AUTH_TEXT=/(?:authorization\s*:|bearer\s+[^\s]+|basic\s+auth|curl\s+-u\b|oauth|access[_ -]?token|api[_ -]?key|authentication\s+required|requires?\s+authentication|securitySchemes?)/gi;
const HEADING=/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi;
const BLOCK=/<(?:pre|code)\b[^>]*>[\s\S]*?<\/(?:pre|code)>/gi;
const TAG=/<[^>]+>/g;
const NAV_PATH=/(?:^|\/)(?:privacy|terms|legal|license|contact|about|login|signin|signup|register|account|blog|news|careers?|press|status)(?:\/|$)/i;
const ASSET=/\.(?:png|jpe?g|gif|svg|css|m?js|woff2?|pdf|zip|tar|gz)(?:$|\?)/i;

export type IrSource={evidence_id:string;source_url:string;start:number;end:number;expanded:boolean};
export type IrSection={id:string,parent_id:string|null,level:number,title:string,start:number;end:number;source:IrSource};
export type IrApiBase={id:string,origin:string,section_id:string;source:IrSource};
export type IrAuth={id:string,kind:string,optional:boolean,section_id:string;source:IrSource};
export type IrParameter={id:string,name:string,in:"path"|"query"|"header"|"cookie";required:boolean|null;auth_like:boolean;example:string|null;description:string;section_id:string;source:IrSource};
export type IrOperation={id:string,method:"GET";raw_target:string;absolute_url:string|null;path:string;section_id:string;title:string;context:string;parameter_ids:string[];auth_ids:string[];api_base_id:string|null;api_base_relation:"same_section"|"ancestor_section"|"source_local_namespace"|null;source:IrSource};
export type DocumentationIr={documents:number;sections:IrSection[];api_bases:IrApiBase[];auth:IrAuth[];parameters:IrParameter[];operations:IrOperation[];fingerprint:string;metrics:{irDocuments:number;irSections:number;irOperations:number;irParameters:number;irApiBases:number;irAuthRequirements:number;irReferenceDocuments:number;irOperationsFromReferenceExpansion:number;operationApiBaseLinks:number;ancestorApiBaseLinks:number;sourceLocalNamespaceLinks:number;relativeOperationsUnlinked:number;}};

function decodeEntities(s:string){return s.replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#x2f;/gi,"/").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function textOnly(s:string){return decodeEntities(s.replace(/<br\s*\/?\s*>/gi,"\n").replace(TAG," ")).replace(/[ \t]+/g," ").replace(/\n\s+/g,"\n").trim()}
function normTemplate(s:string){return s.replace(/\{\{([A-Za-z_][\w.-]*)\}\}/g,"{$1}").replace(/:([A-Za-z_][\w.-]*)/g,"{$1}").replace(/\[([A-Za-z_][\w.-]*)\]/g,"{$1}").replace(/<([A-Za-z_][\w.-]*)>/g,"{$1}").replace(/%7B/gi,"{").replace(/%7D/gi,"}")}
function safeUrl(raw:string){try{const u=new URL(normTemplate(decodeEntities(raw).replace(/[),;]+$/g,"")));if(u.protocol!=="https:"||u.username||u.password||ASSET.test(u.pathname)||NAV_PATH.test(u.pathname))return null;return u}catch{return null}}
function source(ev:DocEvidence,start:number,end:number):IrSource{return {evidence_id:ev.evidence_id,source_url:ev.resolved_url||ev.requested_url,start,end,expanded:(ev as any).source_kind==="4e_reference_expansion"||(ev as any).source_kind==="4f_reference_expansion"}}
function sectionAt(sections:IrSection[],pos:number){return [...sections].filter(s=>s.start<=pos&&pos<s.end).sort((a,b)=>b.level-a.level||b.start-a.start)[0]||sections[0]}
function ancestors(sections:IrSection[],id:string){const by=new Map(sections.map(s=>[s.id,s]));const out:IrSection[]=[];let cur=by.get(id)||null;while(cur){out.push(cur);cur=cur.parent_id?by.get(cur.parent_id)||null:null}return out}
function requestAtoms(raw:string){const out:{target:string;start:number;end:number}[]=[];const patterns=[/\bGET\s+(https:\/\/[^\s"'`\\]+|\/[^\s"'`\\]+)/gi,/\bcurl\b[^\n;]*?(https:\/\/[^\s"'`\\]+)/gi,/\bfetch\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/gi,/\baxios\.get\s*\(\s*["'`](https:\/\/[^"'`]+)["'`]/gi,/\b(?:Endpoint|Request\s+URL|API\s+URL)\s*:\s*(https:\/\/[^\s"'`\\]+)/gi];for(const re of patterns)for(const m of raw.matchAll(re))out.push({target:m[1],start:m.index??0,end:(m.index??0)+m[0].length});return out}
function paramsFromTarget(target:string,section:IrSection,src:IrSource){const path=normTemplate(target),params:IrParameter[]=[];for(const m of path.matchAll(/\{([A-Za-z_][\w.-]*)\}/g)){const name=m[1];params.push({id:`par4f_${fourAp1Sha({e:src.evidence_id,s:src.start,n:name,p:1}).slice(0,16)}`,name,in:"path",required:true,auth_like:AUTH_NAME.test(name),example:null,description:"",section_id:section.id,source:src})}let u:URL|null=null;try{u=new URL(path,"https://placeholder.invalid")}catch{}if(u)for(const [name,value] of u.searchParams)params.push({id:`par4f_${fourAp1Sha({e:src.evidence_id,s:src.start,n:name,q:1,v:value}).slice(0,16)}`,name,in:"query",required:null,auth_like:AUTH_NAME.test(name),example:value||null,description:"",section_id:section.id,source:src});return params}
function sectionize(ev:DocEvidence){const raw=String(ev.text||""),heads=[...raw.matchAll(HEADING)].map(m=>({level:Number(m[1]),title:textOnly(m[2]),start:m.index??0}));if(!heads.length)return [{id:`sec4f_${fourAp1Sha({e:ev.evidence_id,r:0}).slice(0,16)}`,parent_id:null,level:0,title:"document",start:0,end:raw.length,source:source(ev,0,raw.length)}] as IrSection[];const sections:IrSection[]=[{id:`sec4f_${fourAp1Sha({e:ev.evidence_id,r:"root"}).slice(0,16)}`,parent_id:null,level:0,title:"document",start:0,end:raw.length,source:source(ev,0,raw.length)}],stack:IrSection[]=[sections[0]];for(let i=0;i<heads.length;i++){const h=heads[i];while(stack.length>1&&stack.at(-1)!.level>=h.level)stack.pop();const parent=stack.at(-1)!;let end=raw.length;for(let j=i+1;j<heads.length;j++)if(heads[j].level<=h.level){end=heads[j].start;break}const s:IrSection={id:`sec4f_${fourAp1Sha({e:ev.evidence_id,s:h.start,t:h.title}).slice(0,16)}`,parent_id:parent.id,level:h.level,title:h.title,start:h.start,end,source:source(ev,h.start,end)};sections.push(s);stack.push(s)}return sections}

export function compileDocumentationIr4F(evidence:DocEvidence[]):DocumentationIr{const sections:IrSection[]=[],api_bases:IrApiBase[]=[],auth:IrAuth[]=[],parameters:IrParameter[]=[],operations:IrOperation[]=[];for(const ev of evidence){if(ev.state!=="ok")continue;const raw=String(ev.text||""),secs=sectionize(ev);sections.push(...secs);for(const m of raw.matchAll(/\b(?:Base\s+URL|API\s+Base|Base\s+URI|Server\s+URL)\s*[:=]\s*(https:\/\/[^\s"'<>]+)/gi)){const u=safeUrl(m[1]);if(!u)continue;const sec=sectionAt(secs,m.index??0),src=source(ev,m.index??0,(m.index??0)+m[0].length);api_bases.push({id:`base4f_${fourAp1Sha({e:ev.evidence_id,s:src.start,o:u.origin}).slice(0,16)}`,origin:u.origin,section_id:sec.id,source:src})}for(const m of raw.matchAll(AUTH_TEXT)){const sec=sectionAt(secs,m.index??0),src=source(ev,m.index??0,(m.index??0)+m[0].length);auth.push({id:`auth4f_${fourAp1Sha({e:ev.evidence_id,s:src.start,r:m[0]}).slice(0,16)}`,kind:textOnly(m[0]).slice(0,120),optional:/optional|not required|without authentication/i.test(raw.slice(Math.max(0,src.start-120),src.end+120)),section_id:sec.id,source:src})}
const scopes:{text:string;start:number;end:number;section:IrSection}[]=[];for(const m of raw.matchAll(BLOCK)){const sec=sectionAt(secs,m.index??0);scopes.push({text:textOnly(m[0]),start:m.index??0,end:(m.index??0)+m[0].length,section:sec})}for(const sec of secs.filter(s=>s.level>0)){const slice=raw.slice(sec.start,sec.end);scopes.push({text:textOnly(slice),start:sec.start,end:sec.end,section:sec})}if(secs.length===1)scopes.push({text:textOnly(raw),start:0,end:raw.length,section:secs[0]});const seen=new Set<string>();for(const scope of scopes){for(const atom of requestAtoms(scope.text)){const key=`${scope.section.id}|${atom.target}`;if(seen.has(key))continue;seen.add(key);const sec=scope.section,src=source(ev,scope.start,scope.end),abs=safeUrl(atom.target),path=abs?normTemplate(`${abs.pathname}${abs.search}`):normTemplate(atom.target),opParams=paramsFromTarget(abs?abs.toString():atom.target,sec,src);parameters.push(...opParams);const op:IrOperation={id:`op4f_${fourAp1Sha({e:ev.evidence_id,s:src.start,t:atom.target,sec:sec.id}).slice(0,16)}`,method:"GET",raw_target:atom.target,absolute_url:abs?.toString()??null,path,section_id:sec.id,title:sec.title,context:scope.text.slice(0,2400),parameter_ids:opParams.map(p=>p.id),auth_ids:[],api_base_id:null,api_base_relation:null,source:src};if(abs){let b=api_bases.find(x=>x.origin===abs.origin&&x.source.evidence_id===ev.evidence_id);if(!b){b={id:`base4f_${fourAp1Sha({e:ev.evidence_id,o:abs.origin,derived:1}).slice(0,16)}`,origin:abs.origin,section_id:sec.id,source:src};api_bases.push(b)}op.api_base_id=b.id;op.api_base_relation="same_section"}operations.push(op)}}}
const bySec=new Map(sections.map(s=>[s.id,s]));for(const op of operations){const chain=ancestors(sections,op.section_id),chainIds=new Set(chain.map(s=>s.id));op.auth_ids=auth.filter(a=>a.source.evidence_id===op.source.evidence_id&&chainIds.has(a.section_id)).map(a=>a.id);if(op.api_base_id||!op.path.startsWith("/"))continue;let chosen:IrApiBase|null=null,relation:IrOperation["api_base_relation"]=null;for(const s of chain){const candidates=api_bases.filter(b=>b.section_id===s.id&&b.source.evidence_id===op.source.evidence_id);if(candidates.length===1){chosen=candidates[0];relation=s.id===op.section_id?"same_section":"ancestor_section";break}}if(!chosen){const parent=bySec.get(op.section_id)?.parent_id;const cousins=parent?api_bases.filter(b=>bySec.get(b.section_id)?.parent_id===parent&&b.source.evidence_id===op.source.evidence_id):[];if(cousins.length===1){chosen=cousins[0];relation="source_local_namespace"}}if(chosen){op.api_base_id=chosen.id;op.api_base_relation=relation}}
const metrics={irDocuments:evidence.filter(e=>e.state==="ok").length,irSections:sections.length,irOperations:operations.length,irParameters:parameters.length,irApiBases:api_bases.length,irAuthRequirements:auth.length,irReferenceDocuments:evidence.filter(e=>(e as any).source_kind==="4e_reference_expansion"||(e as any).source_kind==="4f_reference_expansion").length,irOperationsFromReferenceExpansion:operations.filter(o=>o.source.expanded).length,operationApiBaseLinks:operations.filter(o=>!!o.api_base_id).length,ancestorApiBaseLinks:operations.filter(o=>o.api_base_relation==="ancestor_section").length,sourceLocalNamespaceLinks:operations.filter(o=>o.api_base_relation==="source_local_namespace").length,relativeOperationsUnlinked:operations.filter(o=>o.path.startsWith("/")&&!o.api_base_id).length};return {documents:metrics.irDocuments,sections,api_bases,auth,parameters,operations,fingerprint:fourAp1Sha({sections:sections.map(x=>[x.id,x.parent_id,x.title]),bases:api_bases.map(x=>[x.id,x.origin,x.section_id]),auth:auth.map(x=>[x.id,x.kind,x.optional,x.section_id]),params:parameters.map(x=>[x.id,x.name,x.in,x.required,x.auth_like,x.example]),ops:operations.map(x=>[x.id,x.path,x.section_id,x.api_base_id,x.api_base_relation,x.parameter_ids,x.auth_ids])}),metrics}}
