import type {DocEvidence,MicroContract} from "./experiment3wCore.js";
import {compileMicroRequest,docScopeAllowed} from "./experiment3wCore.js";
import {executeProgram} from "./experiment3xCore.js";
import {RecoveryLedger} from "./experiment3yrCore.js";
import {FOUR_A_CASES,semanticValidate4a} from "./experiment4aCore.js";
import {normalizeRequestContract,validateProjectionPlan,type ProjectionPlan} from "./experiment4arCore.js";
import type {Provider4A} from "./experiment4aContract.js";

const BY_ID=Object.fromEntries(FOUR_A_CASES.map(x=>[x.case_id,x]));
function evidenceText(ids:string[],all:DocEvidence[],providerId:string){const by=new Map(all.map(e=>[e.evidence_id,e]));const out:DocEvidence[]=[];for(const id of ids){const e=by.get(id);if(!e)throw new Error(`unknown_evidence_id:${id}`);if(e.provider_candidate_id!==providerId)throw new Error(`cross_provider_evidence:${id}`);if(e.state!=="ok")throw new Error(`non_ok_evidence:${id}`);out.push(e);}return out.map(x=>x.text).join("\n");}
function sourceKey(v:string){return v.startsWith("$input.")?v.slice(7):null;}
function tokenGrounded(path:string,text:string){const t=text.toLowerCase();for(const p of String(path||"").split(".").filter(Boolean)){if(/^\d+$/.test(p))continue;if(!t.includes(p.toLowerCase()))return false;}return true;}
function pathGrounded(path:string,text:string){if(text.includes(path))return true;const n=path.replace(/\{[^}]+\}/g,"{}");const candidates=[...text.matchAll(/\/[^\s"'<>`]*/g)].map(m=>m[0].replace(/\{[^}]+\}/g,"{}"));return candidates.some(x=>x===n||x.includes(n)||n.includes(x));}
export function validate4ar(raw:any,p:Provider4A,evidence:DocEvidence[],ledger:RecoveryLedger){const ec=BY_ID[p.case_id],errors:string[]=[];if(!ec)return {errors:["unknown_case"],contract:null as any,projection:null as any};const c=normalizeRequestContract(raw,Object.keys(ec.build));if(!c||typeof c!=="object"||Array.isArray(c))return {errors:["contract_not_object"],contract:null as any,projection:null as any};const caseMatches=c.case_id===p.case_id;if(!caseMatches)errors.push("case_id_mismatch");if(c.provider_candidate_id!==p.candidate_id)errors.push("provider_id_mismatch");if(!["COMPILE","REJECT"].includes(c.decision))errors.push("decision_invalid");if(c.decision!=="COMPILE")return {errors,contract:c,projection:null};if(c.method!=="GET"){errors.push("method_not_get");ledger.record("guard","non_get",false,c.method);}const ids=Array.isArray(c.evidence_ids)?c.evidence_ids:[];if(!ids.length)errors.push("empty_evidence_ids");let text="";try{text=evidenceText(ids,evidence,p.candidate_id);}catch(e){errors.push(String(e).replace(/^Error:\s*/,""));}
try{const u=new URL(String(c.base_url||""));if(u.protocol!=="https:"){errors.push("base_non_https");ledger.record("guard","non_https",false,u.toString());}if(u.username||u.password){errors.push("credential_bearing_base");ledger.record("guard","credentials",false);}if(text&&!text.includes(u.origin)){errors.push("undocumented_base_url");ledger.record("guard","endpoint_mutations",false,u.origin);}}catch{errors.push("invalid_base_url");}
const path=String(c.path_template||"");if(!path.startsWith("/"))errors.push("path_not_absolute");if(path.includes("$input.")||/:[A-Za-z_][A-Za-z0-9_]*/.test(path))errors.push("noncanonical_path_syntax");if(text&&!pathGrounded(path,text)){errors.push("undocumented_path");ledger.record("guard","endpoint_mutations",false,path);}const pb=c.path_bindings&&typeof c.path_bindings==="object"&&!Array.isArray(c.path_bindings)?c.path_bindings:{},qb=c.query_bindings&&typeof c.query_bindings==="object"&&!Array.isArray(c.query_bindings)?c.query_bindings:{};
for(const [n,src] of Object.entries(pb)){if(!path.includes(`{${n}}`))errors.push(`path_placeholder_missing:${n}`);const k=sourceKey(String(src));if(!k||!(k in ec.build)){errors.push(`invalid_input_source:${n}`);ledger.record("guard","invented_parameters",false,n);}}
for(const [n,src] of Object.entries(qb)){const s=String(src);if(s.startsWith("$input.")){const k=sourceKey(s);if(!k||!(k in ec.build)){errors.push(`invalid_input_source:${n}`);ledger.record("guard","invented_parameters",false,n);}}if(text&&!text.toLowerCase().includes(n.toLowerCase())){errors.push(`invented_query_parameter:${n}`);ledger.record("guard","invented_parameters",false,n);}}
for(const ph of path.match(/\{([^}]+)\}/g)||[]){const n=ph.slice(1,-1);if(!(n in pb))errors.push(`unbound_path_placeholder:${n}`);}let projection:ProjectionPlan|null=null;try{projection=validateProjectionPlan(c.projection,ec.required,Object.keys(ec.build));if(text)for(const e of Object.values(projection) as any[]){for(const key of ["path","map_path","array_path","where_path","value_path"]){const v=e?.[key];if(v&&!tokenGrounded(String(v),text)){errors.push(`ungrounded_projection:${key}:${v}`);ledger.record("guard","ungrounded_projection_fields",false,v);}}}}catch(e){errors.push(String(e).replace(/^Error:\s*/,""));}
const contract:MicroContract={case_id:c.case_id,provider_candidate_id:c.provider_candidate_id,decision:c.decision,method:c.method,base_url:c.base_url,path_template:c.path_template,path_bindings:pb,query_bindings:qb,evidence_ids:ids,reason:c.reason};return {errors,contract,projection};}
export function compile4ar(c:MicroContract,input:Record<string,unknown>){return compileMicroRequest(c,input);}
export function project4ar(plan:ProjectionPlan,body:any,input:Record<string,unknown>){return executeProgram(plan,body,input) as Record<string,any>;}
export function validateProjected4ar(caseId:string,input:Record<string,any>,out:Record<string,any>){return semanticValidate4a(caseId,input,out);}
export function scope4ar(start:string,target:string){return docScopeAllowed(start,target);}
