import type {ProjectionExpr} from "./experiment3xCore.js";
export {auditProviderBlindSource} from "./experiment4ar2Core.js";

export const FOUR_AR3_BASE_SHA="2b6718b8625eb257291bcb6df9d2a586f5126346";
export const FOUR_AR3_FROZEN_RUN=33021647548;
export const FOUR_AR3_FROZEN_ARTIFACT=9627153170;
export const FOUR_AR3_FROZEN_DIGEST="sha256:5cfe8066c58707b2f8d27dfc83bf7f80c2f94b9b612739a18c99f5b7c2ee18d2";
export const FOUR_AR3_FROZEN_REPORT_FP="5ac172e89b66eeadedbaa121af7398a5fc16a95ee2905db8b816ee94d241f3b9";

const projectionItem={type:"object",additionalProperties:false,required:["output","op","path","name","map_path","key_op","key_name","key_value","value_path","array_path","where_path","equals_op","equals_name","equals_value"],properties:{output:{type:"string"},op:{type:"string",enum:["FIELD","INPUT","LOOKUP","FIND"]},path:{type:["string","null"]},name:{type:["string","null"]},map_path:{type:["string","null"]},key_op:{type:["string","null"],enum:["INPUT","LITERAL",null]},key_name:{type:["string","null"]},key_value:{type:["string","null"]},value_path:{type:["string","null"]},array_path:{type:["string","null"]},where_path:{type:["string","null"]},equals_op:{type:["string","null"],enum:["INPUT","LITERAL",null]},equals_name:{type:["string","null"]},equals_value:{type:["string","null"]}}} as const;

export function makeBoundarySchema(inputNames:readonly string[]){
 const inputEnum=[...inputNames,null];
 const pathBinding={type:"object",additionalProperties:false,required:["name","source_kind","input_name","literal_value"],properties:{name:{type:"string"},source_kind:{type:"string",enum:["INPUT"]},input_name:{type:["string","null"],enum:inputEnum},literal_value:{type:["string","null"],enum:[null]}}};
 const queryBinding={type:"object",additionalProperties:false,required:["name","source_kind","input_name","literal_value"],properties:{name:{type:"string"},source_kind:{type:"string",enum:["INPUT","LITERAL"]},input_name:{type:["string","null"],enum:inputEnum},literal_value:{type:["string","null"]}}};
 return {name:"missing_4ar3_typed_binding_ir",strict:true,schema:{type:"object",additionalProperties:false,required:["case_id","provider_candidate_id","decision","method","base_url","path_template","path_bindings","query_bindings","projection","evidence_ids","reason"],properties:{case_id:{type:"string"},provider_candidate_id:{type:"string"},decision:{type:"string",enum:["COMPILE","REJECT"]},method:{type:["string","null"],enum:["GET",null]},base_url:{type:["string","null"]},path_template:{type:["string","null"]},path_bindings:{type:"array",items:pathBinding},query_bindings:{type:"array",items:queryBinding},projection:{type:"array",items:projectionItem},evidence_ids:{type:"array",items:{type:"string"}},reason:{type:"string"}}}} as const;
}

function typedBindings(rows:any,inputNames:readonly string[],allowLiteral:boolean){const out:Record<string,string>={};for(const r of Array.isArray(rows)?rows:[]){if(!r||typeof r.name!=="string"||!r.name)throw new Error("binding_name_invalid");if(r.name in out)throw new Error(`duplicate_binding:${r.name}`);if(r.source_kind==="INPUT"){if(typeof r.input_name!=="string"||!inputNames.includes(r.input_name))throw new Error(`binding_input_invalid:${r.name}`);if(r.literal_value!==null)throw new Error(`binding_input_literal_must_be_null:${r.name}`);out[r.name]=`$input.${r.input_name}`;}else if(r.source_kind==="LITERAL"&&allowLiteral){if(r.input_name!==null)throw new Error(`binding_literal_input_must_be_null:${r.name}`);if(typeof r.literal_value!=="string")throw new Error(`binding_literal_invalid:${r.name}`);out[r.name]=r.literal_value;}else throw new Error(`binding_source_kind_invalid:${r.name}`);}return out;}
function key(op:any,name:any,value:any,inputNames:readonly string[]){if(op==="INPUT"){if(typeof name!=="string"||!inputNames.includes(name))throw new Error("projection_input_key_invalid");return {op:"INPUT",name};}if(op==="LITERAL"){if(typeof value!=="string")throw new Error("projection_literal_key_invalid");return {op:"LITERAL",value};}throw new Error("invalid_key");}
export function canonicalizeBoundary3(raw:any,required:readonly string[],inputNames:readonly string[]){if(!raw||typeof raw!=="object")throw new Error("boundary_not_object");if(raw.decision==="REJECT")return {case_id:raw.case_id,provider_candidate_id:raw.provider_candidate_id,decision:"REJECT",reason:String(raw.reason||"")};if(raw.decision!=="COMPILE")throw new Error("boundary_decision_invalid");const projection:Record<string,ProjectionExpr>={};for(const row of raw.projection||[]){if(!required.includes(row.output))throw new Error(`unexpected_output:${row.output}`);if(row.output in projection)throw new Error(`duplicate_output:${row.output}`);if(row.op==="FIELD")projection[row.output]={op:"FIELD",path:String(row.path||"")};else if(row.op==="INPUT"){if(typeof row.name!=="string"||!inputNames.includes(row.name))throw new Error(`projection_input_invalid:${row.output}`);projection[row.output]={op:"INPUT",name:row.name};}else if(row.op==="LOOKUP")projection[row.output]={op:"LOOKUP",map_path:String(row.map_path||""),key:key(row.key_op,row.key_name,row.key_value,inputNames) as any,value_path:String(row.value_path||"")};else if(row.op==="FIND")projection[row.output]={op:"FIND",array_path:String(row.array_path||""),where_path:String(row.where_path||""),equals:key(row.equals_op,row.equals_name,row.equals_value,inputNames) as any,value_path:String(row.value_path||"")};else throw new Error(`invalid_op:${row.op}`);}for(const r of required)if(!projection[r])throw new Error(`missing_output:${r}`);return {case_id:raw.case_id,provider_candidate_id:raw.provider_candidate_id,decision:"COMPILE",method:raw.method,base_url:raw.base_url,path_template:raw.path_template,path_bindings:typedBindings(raw.path_bindings,inputNames,false),query_bindings:typedBindings(raw.query_bindings,inputNames,true),projection,evidence_ids:raw.evidence_ids,reason:String(raw.reason||"")};}
