import {mkdir,writeFile} from "node:fs/promises";
import {loadConfig} from "./config/index.js";
import {fetchTextBounded} from "./experiment3qNetwork.js";
import {PUBLIC_APIS_URL,parsePublicApis} from "./experiment3tCore.js";
import {BROAD_TOP_K,RERANK_TOP_K,providerSelectionFingerprint,resolveSelected,type ProviderCandidate} from "./experiment3vCore.js";
import {MAX_DEPTH,MAX_BYTES,extractDocLinks,type DocEvidence,type FrozenProvider,type SafetyEvent} from "./experiment3wCore.js";
import {fetchDocumentation,verifiedJsonGet} from "./experiment3wNetwork.js";
import {CASES,assertBlindCases,compileRequest,enforceReplayDeltas,executeProgram,sameRequired,semanticValidate,sha,validateDecision,type CompileDecision,type HoldoutCase,type ProviderRef} from "./experiment3yCore.js";
import {broadRetrieve3y} from "./experiment3yDiscovery.js";
import {compileCapability} from "./experiment3yPlanner.js";
import {call3yProviderReranker,parse3yRerankAttempt} from "./experiment3yProviderPlanner.js";
import {run3yControls} from "./experiment3yControls.js";

const OUT="results/experiment-3y";
const BASE_SHA="a19b930691f7127b2dd15b93dc88fd130c1054dd";
const DOC_PAGES=6;
let catalogFetches=0,rerankerCalls=0,rerankerRepairs=0,documentationFetches=0,compilerCalls=0,compilerRepairs=0,liveVerificationCalls=0;

async function fetchCatalog(){catalogFetches++;const {text}=await fetchTextBounded(PUBLIC_APIS_URL,16*1024*1024,"text/markdown,text/plain");return text;}
async function rerank(config:any,c:HoldoutCase,broad:ProviderCandidate[],evidence:any[]){rerankerCalls++;let a=await call3yProviderReranker(config,c,broad,"initial"),parsed=parse3yRerankAttempt(a,broad,c.case_id);evidence.push({case_id:c.case_id,...a,error:parsed.error});if(parsed.error){rerankerCalls++;rerankerRepairs++;const b=await call3yProviderReranker(config,c,broad,"repair",parsed.error);parsed=parse3yRerankAttempt(b,broad,c.case_id);evidence.push({case_id:c.case_id,...b,error:parsed.error});}return parsed;}
function anonymousHttps(p:ProviderCandidate){return /^no$/i.test(String(p.auth).trim())&&/^yes$/i.test(String(p.https).trim())&&p.link.startsWith("https://");}
async function crawl(c:HoldoutCase,p:ProviderCandidate,safety:SafetyEvent[]){const provider:FrozenProvider={case_id:c.case_id,candidate_id:p.candidate_id,name:p.name,start_url:p.link},evidence:DocEvidence[]=[],queue=[{url:p.link,depth:0}],seen=new Set<string>();while(queue.length&&evidence.length<DOC_PAGES){const item=queue.shift()!;if(item.depth>MAX_DEPTH||seen.has(item.url))continue;seen.add(item.url);documentationFetches++;const ev=await fetchDocumentation(provider,item.url,`${p.candidate_id}-e${String(evidence.length+1).padStart(2,"0")}`,safety);evidence.push(ev);if(ev.state!=="ok")continue;for(const link of extractDocLinks(ev.resolved_url,p.link,ev.text,item.depth+1)){if(link.depth<=MAX_DEPTH&&!seen.has(link.url)&&queue.length+evidence.length<DOC_PAGES*3)queue.push(link);}}return evidence;}
async function compile(config:any,c:HoldoutCase,p:ProviderCandidate,evidence:DocEvidence[],safety:SafetyEvent[],planner:any[]){const pref:ProviderRef={candidate_id:p.candidate_id,name:p.name,link:p.link};if(!evidence.some(e=>e.state==="ok"))return {decision:null as CompileDecision|null,error:"no_documentation_evidence"};compilerCalls++;let first=await compileCapability(config,c,pref,evidence,"initial"),decision=first.parsed_json,error:string|null=null;try{if(!decision)throw new Error(first.parse_error||`compiler_http_${first.http_status}`);validateDecision(decision,c,pref,evidence,safety);}catch(e){error=String(e).replace(/^Error:\s*/,"");}planner.push({case_id:c.case_id,provider_candidate_id:p.candidate_id,...first,static_error:error});if(error){compilerCalls++;compilerRepairs++;const second=await compileCapability(config,c,pref,evidence,"repair",error);decision=second.parsed_json;error=null;try{if(!decision)throw new Error(second.parse_error||`compiler_http_${second.http_status}`);validateDecision(decision,c,pref,evidence,safety);}catch(e){error=String(e).replace(/^Error:\s*/,"");}planner.push({case_id:c.case_id,provider_candidate_id:p.candidate_id,...second,static_error:error});}return {decision:error?null:decision,error};}
function evidenceFingerprint(evidence:DocEvidence[]){return sha(evidence.map(e=>({id:e.evidence_id,provider:e.provider_candidate_id,url:e.resolved_url,at:e.verified_at,status:e.status,body:e.body_fingerprint,state:e.state,error:e.error??null})));}

async function main(){
 await mkdir(OUT,{recursive:true});assertBlindCases();const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required");
 const started_at=new Date().toISOString(),safety:SafetyEvent[]=[],controlRun=run3yControls(),catalog=await fetchCatalog(),rerankEvidence:any[]=[],compilerEvidence:any[]=[],documentationEvidence:any[]=[],caseResults:any[]=[],recipes:any[]=[],usableDocs=new Set<string>();
 for(const c of CASES){
  const broad=broadRetrieve3y(c,catalog),r=await rerank(config,c,broad,rerankEvidence);if(!r.selection){caseResults.push({case_id:c.case_id,broad_count:broad.length,rerank_error:r.error,selected:[],attempts:[],recipe:null});continue;}
  const selectionFp=providerSelectionFingerprint(c as any,r.selection),selected=resolveSelected(r.selection,broad),attempts:any[]=[];let recipe:any=null;
  for(const p of selected){
   if(!anonymousHttps(p)){attempts.push({provider_candidate_id:p.candidate_id,provider_name:p.name,status:"ineligible_anonymous_https",auth:p.auth,https:p.https});continue;}
   const docs=await crawl(c,p,safety);documentationEvidence.push({case_id:c.case_id,provider_candidate_id:p.candidate_id,provider_name:p.name,start_url:p.link,evidence:docs});if(docs.some(e=>e.state==="ok"))usableDocs.add(`${c.case_id}|${p.candidate_id}`);
   const compiled=await compile(config,c,p,docs,safety,compilerEvidence),decision=compiled.decision;if(!decision||decision.decision!=="COMPILE"||!decision.outputs){attempts.push({provider_candidate_id:p.candidate_id,provider_name:p.name,status:decision?.decision==="REJECT"?"compiler_reject":"compiler_invalid",error:compiled.error??null});continue;}
   const attempted_at=new Date().toISOString();try{
    const url=compileRequest(decision,c.build);liveVerificationCalls++;const first=await verifiedJsonGet(url,safety),out1=executeProgram(decision.outputs,first.body,c.build);if(!semanticValidate(c,c.build,out1))throw new Error("semantic_validation_first_failed");
    liveVerificationCalls++;const second=await verifiedJsonGet(url,safety),out2=executeProgram(decision.outputs,second.body,c.build);if(!semanticValidate(c,c.build,out2))throw new Error("semantic_validation_confirmation_failed");if(!sameRequired(out1,out2,c.required_output_leaf_names))throw new Error("fresh_confirmation_value_mismatch");
    const base={case_id:c.case_id,provider_candidate_id:p.candidate_id,provider_name:p.name,provider_domain:new URL(String(decision.base_url)).hostname,method:"GET",base_url:decision.base_url,path_template:decision.path_template,path_bindings:decision.path_bindings??{},query_bindings:decision.query_bindings??{},outputs:decision.outputs,evidence_ids:decision.evidence_ids??[],provider_selection_fingerprint:selectionFp,evidence_fingerprint:evidenceFingerprint(docs),program_fingerprint:sha(decision.outputs),provenance_fingerprint:sha({case:c,provider_candidate_id:p.candidate_id,provider_selection_fingerprint:selectionFp,evidence_ids:decision.evidence_ids}),first_verification:{requested_at:first.requested_at,url:first.url,status:first.status,content_type:first.content_type,body_fingerprint:first.body_fingerprint,trace_fingerprint:first.trace_fingerprint},confirmation_verification:{requested_at:second.requested_at,url:second.url,status:second.status,content_type:second.content_type,body_fingerprint:second.body_fingerprint,trace_fingerprint:second.trace_fingerprint}};recipe={...base,recipe_fingerprint:sha(base)};recipes.push(recipe);attempts.push({provider_candidate_id:p.candidate_id,provider_name:p.name,status:"verified_live",attempted_at,output:out2});break;
   }catch(e){attempts.push({provider_candidate_id:p.candidate_id,provider_name:p.name,status:"live_failed",attempted_at,error:String(e)});}
  }
  caseResults.push({case_id:c.case_id,broad_count:broad.length,rerank_error:null,selected:selected.map(x=>({candidate_id:x.candidate_id,name:x.name,lexical_rank:x.lexical_rank,auth:x.auth,https:x.https})),provider_selection_fingerprint:selectionFp,attempts,recipe:recipe??recipes.find(x=>x.case_id===c.case_id)??null});
 }
 const before={catalogFetches,rerankerCalls,rerankerRepairs,documentationFetches,compilerCalls,compilerRepairs},replay:any[]=[];
 for(const r of recipes){const c=CASES.find(x=>x.case_id===r.case_id)!;const decision:CompileDecision={case_id:r.case_id,provider_candidate_id:r.provider_candidate_id,decision:"COMPILE",method:"GET",base_url:r.base_url,path_template:r.path_template,path_bindings:r.path_bindings,query_bindings:r.query_bindings,outputs:r.outputs,evidence_ids:r.evidence_ids,reason:"persisted_recipe"};try{const url=compileRequest(decision,c.replay);liveVerificationCalls++;const got=await verifiedJsonGet(url,safety),out=executeProgram(r.outputs,got.body,c.replay);if(!semanticValidate(c,c.replay,out))throw new Error("replay_semantic_validation_failed");replay.push({case_id:c.case_id,provider_candidate_id:r.provider_candidate_id,success:true,input:c.replay,output:out,verification:{requested_at:got.requested_at,url:got.url,status:got.status,content_type:got.content_type,body_fingerprint:got.body_fingerprint,trace_fingerprint:got.trace_fingerprint}});}catch(e){replay.push({case_id:c.case_id,provider_candidate_id:r.provider_candidate_id,success:false,error:String(e)});}}
 const replayDeltas={catalog_fetches:catalogFetches-before.catalogFetches,provider_reranker_calls:rerankerCalls-before.rerankerCalls,provider_reranker_repairs:rerankerRepairs-before.rerankerRepairs,documentation_fetches:documentationFetches-before.documentationFetches,compiler_calls:compilerCalls-before.compilerCalls,compiler_repairs:compilerRepairs-before.compilerRepairs,projection_inductions:0};let replayZero=true;try{enforceReplayDeltas(replayDeltas,safety);}catch{replayZero=false;}
 const entries=parsePublicApis(catalog).length,validReranks=caseResults.filter(x=>!x.rerank_error).length,manufactured=caseResults.filter(x=>x.recipe).length,replaySuccess=replay.filter(x=>x.success).length,domains=new Set(recipes.map(r=>r.provider_domain)).size,controls=controlRun.controls,verifiedControls=controls.filter(x=>x.executed&&x.rejected).length;const accepted=(kind:string)=>safety.filter(x=>x.kind===kind&&x.accepted).length;const metrics={holdout_cases:CASES.length,catalog_entries:entries,catalog_fetches:catalogFetches,reranker_calls:rerankerCalls,reranker_repairs:rerankerRepairs,documentation_fetches:documentationFetches,compiler_calls:compilerCalls,compiler_repairs:compilerRepairs,live_verification_calls:liveVerificationCalls,usable_documentation_candidates:usableDocs.size,manufactured_capabilities:manufactured,persisted_recipes:recipes.length,distinct_provider_domains:domains,replay_successes:replaySuccess,replay_rate:recipes.length?replaySuccess/recipes.length:0,replay_deltas:replayDeltas,controls_executed:controls.length,controls_verified:verifiedControls,credentials_supplied:accepted("credentials_supplied"),authorization_headers_sent:accepted("authorization_header"),non_get_requests_sent:accepted("non_get"),non_https_execution_accepted:accepted("http_execution"),private_ip_accepted:accepted("private_ip"),undocumented_hosts_accepted:accepted("undocumented_host"),undocumented_paths_accepted:accepted("undocumented_path"),arbitrary_code_executed:accepted("arbitrary_code"),replay_external_calls_accepted:accepted("replay_external_calls")};
 const fingerprints=recipes.length===3&&recipes.every(r=>r.provider_selection_fingerprint&&r.evidence_fingerprint&&r.program_fingerprint&&r.provenance_fingerprint&&r.recipe_fingerprint&&r.first_verification?.body_fingerprint&&r.first_verification?.trace_fingerprint&&r.confirmation_verification?.body_fingerprint&&r.confirmation_verification?.trace_fingerprint),timestamps=recipes.length===3&&recipes.every(r=>r.first_verification?.requested_at&&r.confirmation_verification?.requested_at)&&replay.every(x=>!x.success||x.verification?.requested_at);
 const gates={exact_base_sha_matches:BASE_SHA==="a19b930691f7127b2dd15b93dc88fd130c1054dd",source_level_blindness:assertBlindCases()===true,exactly_3_holdout_families:CASES.length===3,live_catalog_at_least_200:entries>=200,valid_bounded_rerank_all_3:validReranks===3&&caseResults.every(x=>x.broad_count<=BROAD_TOP_K)&&RERANK_TOP_K===12,at_least_3_usable_documentation_candidates:usableDocs.size>=3,all_3_grounded_compile:manufactured===3,all_3_first_live_semantic:recipes.length===3&&recipes.every(r=>r.first_verification?.status>=200&&r.first_verification?.status<300),all_3_fresh_second_live_semantic:recipes.length===3&&recipes.every(r=>r.confirmation_verification?.status>=200&&r.confirmation_verification?.status<300),exactly_3_recipes:recipes.length===3,at_least_2_distinct_provider_domains:domains>=2,all_3_changed_input_replays:recipes.length===3&&replaySuccess===3,replay_100_percent:recipes.length===3&&replaySuccess===recipes.length,replay_discovery_documentation_llm_deltas_zero:replayZero,all_fingerprints_nonempty:fingerprints,all_live_observations_timestamped:timestamps,at_least_26_controls_verified:controls.length>=26&&verifiedControls===controls.length,all_safety_counters_zero:[metrics.credentials_supplied,metrics.authorization_headers_sent,metrics.non_get_requests_sent,metrics.non_https_execution_accepted,metrics.private_ip_accepted,metrics.undocumented_hosts_accepted,metrics.undocumented_paths_accepted,metrics.arbitrary_code_executed,metrics.replay_external_calls_accepted].every(x=>x===0)};
 const formal_decision=Object.values(gates).every(Boolean)?"GO_BLIND_END_TO_END_CAPABILITY_MANUFACTURE":"REASSESS_BLIND_END_TO_END_CAPABILITY_MANUFACTURE";const report={experiment:"3Y",title:"Blind End-to-End Capability Manufacture",started_at,finished_at:new Date().toISOString(),base_sha:BASE_SHA,formal_decision,limits:{broad_top_k:BROAD_TOP_K,rerank_top_k:RERANK_TOP_K,max_doc_depth:MAX_DEPTH,max_doc_pages:DOC_PAGES,max_doc_bytes:MAX_BYTES},metrics,gates,cases:caseResults,replay,negative_controls:controls,safety_events:[...controlRun.safety,...safety]};
 await writeFile(`${OUT}/report.json`,JSON.stringify(report,null,2));await writeFile(`${OUT}/recipes.json`,JSON.stringify(recipes,null,2));await writeFile(`${OUT}/discovery-evidence.json`,JSON.stringify(rerankEvidence,null,2));await writeFile(`${OUT}/compiler-evidence.json`,JSON.stringify(compilerEvidence,null,2));await writeFile(`${OUT}/documentation-evidence.json`,JSON.stringify(documentationEvidence,null,2));console.log(JSON.stringify({formal_decision,metrics,gates},null,2));
}
main().catch(e=>{console.error(e);process.exit(1);});
