import {deriveExperiment4jSource} from "./experiment4jDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4k_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4kSource(source:string){
  let x=deriveExperiment4jSource(source);
  x=r(x,'import {compile4j as compile4ar,project4j as project4ar,scope4j as scope4ar,validate4j as validate4ar,validateProjected4j as validateProjected4ar} from "./experiment4jContract.js";','import {compile4k as compile4ar,project4k as project4ar,scope4k as scope4ar,validate4k as validate4ar,validateProjected4k as validateProjected4ar} from "./experiment4kContract.js";');
  x=r(x,'import {synthesize4j as synthesize4ar} from "./experiment4jPlanner.js";','import {synthesize4k as synthesize4ar} from "./experiment4kPlanner.js";');
  x=r(x,'const OUT="results/experiment-4j",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4k",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');

  x=r(x,'renderCompileRejected4j=0,renderUrlParseRejected4j=0,entityIncompatibleStructuralProbeAttempts4j=0;',`renderCompileRejected4j=0,renderUrlParseRejected4j=0,entityIncompatibleStructuralProbeAttempts4j=0,
routeFamilyCandidates4k=0,routeFamiliesAccepted4k=0,routeFamiliesRejectedInsufficientMembers4k=0,routeFamiliesRejectedMultipleVariablePositions4k=0,routeFamiliesRejectedOriginMismatch4k=0,routeFamiliesRejectedQueryShapeMismatch4k=0,routeFamiliesRejectedAuthLike4k=0,routeFamilyMembers4k=0,routeFamilyInducedPathSlots4k=0,routeFamilyInducedQuerySlots4k=0,routeFamilyDistinctObservedValues4k=0,routeFamilyShapeSupportedBindings4k=0,routeFamilyEntityRejectedBindings4k=0,routeFamilySecondarySupportRejectedBindings4k=0,routeFamilyHypotheses4k=0,routeFamilyProbeCalls4k=0,routeFamilyProbe2xxJson4k=0;`);
  x=r(x,'schemaProbeCalls+=a.schemaProbeCalls||0;schemaProbe2xxJson+=a.schemaProbe2xxJson||0;',`schemaProbeCalls+=a.schemaProbeCalls||0;schemaProbe2xxJson+=a.schemaProbe2xxJson||0;routeFamilyProbeCalls4k+=a.routeFamilyProbeCalls||0;routeFamilyProbe2xxJson4k+=a.routeFamilyProbe2xxJson||0;`);
  x=r(x,'renderCompileRejected4j+=sm.renderCompileRejected||0;renderUrlParseRejected4j+=sm.renderUrlParseRejected||0;entityIncompatibleStructuralProbeAttempts4j+=sm.entityIncompatibleStructuralProbeAttempts||0;',`renderCompileRejected4j+=sm.renderCompileRejected||0;renderUrlParseRejected4j+=sm.renderUrlParseRejected||0;entityIncompatibleStructuralProbeAttempts4j+=sm.entityIncompatibleStructuralProbeAttempts||0;
routeFamilyCandidates4k+=sm.routeFamilyCandidates||0;routeFamiliesAccepted4k+=sm.routeFamiliesAccepted||0;routeFamiliesRejectedInsufficientMembers4k+=sm.routeFamiliesRejectedInsufficientMembers||0;routeFamiliesRejectedMultipleVariablePositions4k+=sm.routeFamiliesRejectedMultipleVariablePositions||0;routeFamiliesRejectedOriginMismatch4k+=sm.routeFamiliesRejectedOriginMismatch||0;routeFamiliesRejectedQueryShapeMismatch4k+=sm.routeFamiliesRejectedQueryShapeMismatch||0;routeFamiliesRejectedAuthLike4k+=sm.routeFamiliesRejectedAuthLike||0;routeFamilyMembers4k+=sm.routeFamilyMembers||0;routeFamilyInducedPathSlots4k+=sm.routeFamilyInducedPathSlots||0;routeFamilyInducedQuerySlots4k+=sm.routeFamilyInducedQuerySlots||0;routeFamilyDistinctObservedValues4k+=sm.routeFamilyDistinctObservedValues||0;routeFamilyShapeSupportedBindings4k+=sm.routeFamilyShapeSupportedBindings||0;routeFamilyEntityRejectedBindings4k+=sm.routeFamilyEntityRejectedBindings||0;routeFamilySecondarySupportRejectedBindings4k+=sm.routeFamilySecondarySupportRejectedBindings||0;routeFamilyHypotheses4k+=sm.routeFamilyHypotheses||0;`);
  x=r(x,'renderCompileRejected:renderCompileRejected4j,renderUrlParseRejected:renderUrlParseRejected4j,entityIncompatibleStructuralProbeAttempts:entityIncompatibleStructuralProbeAttempts4j,schemaProbeCalls',`renderCompileRejected:renderCompileRejected4j,renderUrlParseRejected:renderUrlParseRejected4j,entityIncompatibleStructuralProbeAttempts:entityIncompatibleStructuralProbeAttempts4j,
routeFamilyCandidates:routeFamilyCandidates4k,routeFamiliesAccepted:routeFamiliesAccepted4k,routeFamiliesRejectedInsufficientMembers:routeFamiliesRejectedInsufficientMembers4k,routeFamiliesRejectedMultipleVariablePositions:routeFamiliesRejectedMultipleVariablePositions4k,routeFamiliesRejectedOriginMismatch:routeFamiliesRejectedOriginMismatch4k,routeFamiliesRejectedQueryShapeMismatch:routeFamiliesRejectedQueryShapeMismatch4k,routeFamiliesRejectedAuthLike:routeFamiliesRejectedAuthLike4k,routeFamilyMembers:routeFamilyMembers4k,routeFamilyInducedPathSlots:routeFamilyInducedPathSlots4k,routeFamilyInducedQuerySlots:routeFamilyInducedQuerySlots4k,routeFamilyDistinctObservedValues:routeFamilyDistinctObservedValues4k,routeFamilyShapeSupportedBindings:routeFamilyShapeSupportedBindings4k,routeFamilyEntityRejectedBindings:routeFamilyEntityRejectedBindings4k,routeFamilySecondarySupportRejectedBindings:routeFamilySecondarySupportRejectedBindings4k,routeFamilyHypotheses:routeFamilyHypotheses4k,routeFamilyProbeCalls:routeFamilyProbeCalls4k,routeFamilyProbe2xxJson:routeFamilyProbe2xxJson4k,routeFamilyConfirmedRecipes:routeFamilyConfirmedRecipes,routeFamilyExpandedEvidenceRecipes:routeFamilyExpandedEvidenceRecipes,schemaProbeCalls`);

  x=x.replaceAll('4J_ENTITY_GATED_IDENTIFIER_ROLE:','4K_ROUTE_FAMILY_VARIABLE_SLOT:')
    .replaceAll('4J_SUCCESSFUL_PROBE_MAPPING_REJECT','4K_SUCCESSFUL_PROBE_MAPPING_REJECT')
    .replaceAll('4j_request_hypothesis_not_in_alignment_graph','4k_request_hypothesis_not_in_route_family_graph')
    .replaceAll('GO_4J_ENTITY_GATED_DOCUMENTED_IDENTIFIER_ROLES','GO_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION')
    .replaceAll('REASSESS_4J_ENTITY_GATED_DOCUMENTED_IDENTIFIER_ROLES','REASSESS_4K_ROUTE_FAMILY_VARIABLE_SLOT_INDUCTION');
  x=r(x,'experiment:"4J",purpose:"development_entity_gated_documented_identifier_roles"','experiment:"4K",purpose:"development_route_family_variable_slot_induction"');
  x=r(x,'base_sha:"008af94c9f6fb6e8f63b8c40616ede0bbcbc3988"','base_sha:"93b3aef43f0c35657bc222629ce85fb9d22fad95"');
  x=r(x,'falseCharacterBooksRecipe=recipes.some(r=>r.case_id==="fictional_character_metadata"&&/(?:^|\\/)api\\/books(?:\\/|$)/i.test(String(r.contract?.path_template||"")));',`falseCharacterBooksRecipe=recipes.some(r=>r.case_id==="fictional_character_metadata"&&/(?:^|\\/)api\\/books(?:\\/|$)/i.test(String(r.contract?.path_template||""))),routeFamilyConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4k_route_family_")).length,routeFamilyExpandedEvidenceRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4k_route_family_")&&r.expanded_evidence_request).length;`);
  x=r(x,'false_character_books_recipe_absent:!falseCharacterBooksRecipe,',`false_character_books_recipe_absent:!falseCharacterBooksRecipe,
route_family_confirmed_recipe:routeFamilyConfirmedRecipes>=1,`);
  x=x.replaceAll('./experiment4jPlanner.ts','./experiment4kPlanner.ts').replaceAll('./experiment4jRequest.ts','./experiment4kRequest.ts').replaceAll('./experiment4jContract.ts','./experiment4kContract.ts').replaceAll('./experiment4jDerivation.ts','./experiment4kDerivation.ts');
  return x;
}
