import {mkdir,writeFile} from "node:fs/promises";
import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {createHash} from "node:crypto";
import {z} from "zod";
import {loadConfig} from "./config/index.js";

const TIMEOUT_MS=12000;
const CASES=[
 {case_id:"scholarly_doi_metadata",family:"scholarly",required_source:"crossref_work",build:{doi:"10.1038/nphys1170"},replay:{doi:"10.1126/science.169.3946.635"},required:["doi","title","publisher"]},
 {case_id:"current_weather_coordinates",family:"weather",required_source:"openmeteo_current",build:{latitude:40.7128,longitude:-74.0060},replay:{latitude:35.6762,longitude:139.6503},required:["temperature","weather_code","time"]},
 {case_id:"earthquake_latest_feed",family:"earthquake",required_source:"usgs_feed",build:{window:"all_day"},replay:{window:"all_week"},required:["id","magnitude","place","time"]}
] as const;
const SOURCES={
 crossref_work:{family:"scholarly",url:"https://api.crossref.org/works/{doi}",args:["doi"],allowed_paths:["message.DOI","message.title.0","message.publisher"]},
 openmeteo_current:{family:"weather",url:"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,weather_code&timezone=UTC",args:["latitude","longitude"],allowed_paths:["current.temperature_2m","current.weather_code","current.time"]},
 usgs_feed:{family:"earthquake",url:"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/{window}.geojson",args:["window"],allowed_paths:["features.0.id","features.0.properties.mag","features.0.properties.place","features.0.properties.time"]}
} as const;

const sourceSchema=z.union([
 z.object({op:z.literal("SOURCE"),source_id:z.literal("crossref_work"),args:z.object({doi:z.literal("$input.doi")}).strict()}).strict(),
 z.object({op:z.literal("SOURCE"),source_id:z.literal("openmeteo_current"),args:z.object({latitude:z.literal("$input.latitude"),longitude:z.literal("$input.longitude")}).strict()}).strict(),
 z.object({op:z.literal("SOURCE"),source_id:z.literal("usgs_feed"),args:z.object({window:z.literal("$input.window")}).strict()}).strict()
]);
const projectSchema=z.object({op:z.literal("PROJECT_PATHS"),fields:z.record(z.string(),z.string())}).strict();
const outputSchema=z.object({op:z.literal("OUTPUT")}).strict();
const opSchema=z.union([sourceSchema,projectSchema,outputSchema]);
const planSchema=z.object({case_id:z.string(),decision:z.enum(["MANUFACTURE","REJECT"]),reason:z.string(),ops:z.array(opSchema).max(3)}).strict();
type Plan=z.infer<typeof planSchema>;

let plannerCalls=0,repairCalls=0,replayPlannerCalls=0,wrongSourceAccepted=0,aliasAccepted=0,sourceViolations=0,operationViolations=0,hostViolations=0,redirectsFollowed=0,credentialsSupplied=0,arbitraryCodeExecuted=0;
const sha=(v:any)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
function getPath(v:any,path:string){return path.split(".").reduce((x,k)=>Array.isArray(x)&&/^\d+$/.test(k)?x[Number(k)]:x?.[k],v);}
function publicIPv4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b,c]=p;if(a===0||a===10||a===127||a>=224)return false;if(a===100&&b>=64&&b<=127)return false;if(a===169&&b===254)return false;if(a===172&&b>=16&&b<=31)return false;if(a===192&&b===168)return false;if(a===192&&b===0&&(c===0||c===2))return false;if(a===198&&(b===18||b===19))return false;if(a===198&&b===51&&c===100)return false;if(a===203&&b===0&&c===113)return false;return true;}
function publicIPv6(ip:string){const s=ip.toLowerCase();if(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||/^fe[89ab]/.test(s)||s.startsWith("ff")||s.startsWith("2001:db8:"))return false;if(s.startsWith("::ffff:")){const t=s.slice(7);return isIP(t)===4&&publicIPv4(t);}return true;}
function isPublic(ip:string){return isIP(ip)===4?publicIPv4(ip):isIP(ip)===6?publicIPv6(ip):false;}
async function safeUrl(raw:string){const u=new URL(raw),ev:any={url:raw,hostname:u.hostname,resolved:[],allowed:false};if(u.protocol!=="https:"||isIP(u.hostname)){hostViolations++;throw new Error("host_policy_protocol_or_ip_literal");}const addrs=await lookup(u.hostname,{all:true,verbatim:true});ev.resolved=addrs;if(!addrs.length||addrs.some(a=>!isPublic(a.address))){hostViolations++;throw new Error("host_policy_non_public_dns");}ev.allowed=true;return ev;}
async function fetchJson(url:string,network:any[]){network.push(await safeUrl(url));const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"MISSING-Experiment-3O/0.1"},redirect:"manual",signal:ctrl.signal});if(r.status>=300&&r.status<400)throw new Error(`redirect_rejected_${r.status}`);if(!r.ok)throw new Error(`http_${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
function aliases(raw:any){const bad=new Set(["field","value","path_map","url","method"]);return Boolean(raw&&typeof raw==="object"&&Array.isArray(raw.ops)&&raw.ops.some((o:any)=>o&&typeof o==="object"&&Object.keys(o).some(k=>bad.has(k))));}
function staticValidate(plan:Plan,c:any){const e:string[]=[];if(plan.case_id!==c.case_id)e.push("case_id_mismatch");if(plan.decision!=="MANUFACTURE")return e;if(plan.ops.length!==3||plan.ops[0].op!=="SOURCE"||plan.ops[1].op!=="PROJECT_PATHS"||plan.ops[2].op!=="OUTPUT")e.push("wrong_sequence");const s:any=plan.ops[0];if(s?.op==="SOURCE"&&s.source_id!==c.required_source){e.push("wrong_source");wrongSourceAccepted++;}const p:any=plan.ops[1];if(p?.op==="PROJECT_PATHS"){const allowed=new Set((SOURCES as any)[c.required_source].allowed_paths);for(const k of c.required){const path=p.fields?.[k];if(!path||!allowed.has(path))e.push(`bad_field:${k}`);}for(const [k,path] of Object.entries(p.fields??{}))if(!c.required.includes(k)||!allowed.has(String(path)))e.push(`unexpected_projection:${k}`);}return e;}
function buildUrl(sourceId:string,args:any,input:any){if(sourceId==="crossref_work")return SOURCES.crossref_work.url.replace("{doi}",encodeURIComponent(input.doi));if(sourceId==="openmeteo_current")return SOURCES.openmeteo_current.url.replace("{latitude}",String(input.latitude)).replace("{longitude}",String(input.longitude));if(sourceId==="usgs_feed"){if(!["all_day","all_week"].includes(input.window))throw new Error("invalid_window");return SOURCES.usgs_feed.url.replace("{window}",input.window);}sourceViolations++;throw new Error("unknown_source");}
function semanticValidate(c:any,input:any,out:any){if(c.family==="scholarly")return typeof out.doi==="string"&&out.doi.toLowerCase()===input.doi.toLowerCase()&&typeof out.title==="string"&&out.title.trim()&&typeof out.publisher==="string"&&out.publisher.trim();if(c.family==="weather")return Number.isFinite(out.temperature)&&Number.isFinite(out.weather_code)&&typeof out.time==="string"&&out.time.length>0;if(c.family==="earthquake")return typeof out.id==="string"&&out.id.length>0&&Number.isFinite(out.magnitude)&&typeof out.place==="string"&&out.place.length>0&&Number.isFinite(out.time);return false;}
async function execute(plan:Plan,c:any,input:any,network:any[]){const s:any=plan.ops[0],p:any=plan.ops[1];const body=await fetchJson(buildUrl(s.source_id,s.args,input),network);const out:any={};for(const [k,path] of Object.entries(p.fields))out[k]=getPath(body,String(path));if(!semanticValidate(c,input,out))throw new Error("semantic_validation_failed");return {final_output:out,trace_fingerprint:sha(out)};}
async function planner(config:any,c:any,previous?:string){plannerCalls++;if(previous)repairCalls++;const sys=`You are MISSING Multi-Family Capability Forge. Choose MANUFACTURE or REJECT. You always see three approved sources. Select the source matching the intent. Return JSON only. Strict plan: case_id, decision, reason, ops. Exactly 3 ops for MANUFACTURE: SOURCE, PROJECT_PATHS, OUTPUT. Source schemas: crossref_work args {doi:'$input.doi'}; openmeteo_current args {latitude:'$input.latitude',longitude:'$input.longitude'}; usgs_feed args {window:'$input.window'}. PROJECT_PATHS fields map output names to allowed JSON paths. No extra properties, aliases, transforms, URLs or code.`;const body={case:c,sources:SOURCES,previous_failure:previous??null};const r=await fetch(`${config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",messages:[{role:"system",content:sys},{role:"user",content:JSON.stringify(body)}],response_format:{type:"json_object"}})});if(!r.ok)throw new Error(`planner_${r.status}`);const b:any=await r.json();return JSON.parse(b.choices?.[0]?.message?.content??"{}");}
function parse(raw:any){if(aliases(raw))aliasAccepted++;const p=planSchema.safeParse(raw);return p.success?{plan:p.data,error:null}:{plan:null,error:"planner_contract_invalid"};}

const negativeControls=CASES.map((c,i)=>({case_id:c.case_id,decision:"MANUFACTURE",reason:"wrong source control",ops:[{op:"SOURCE",source_id:CASES[(i+1)%CASES.length].required_source,args:CASES[(i+1)%CASES.length].required_source==="crossref_work"?{doi:"$input.doi"}:CASES[(i+1)%CASES.length].required_source==="openmeteo_current"?{latitude:"$input.latitude",longitude:"$input.longitude"}:{window:"$input.window"}},{op:"PROJECT_PATHS",fields:{}},{op:"OUTPUT"}]}));
let negativeRejected=0;for(let i=0;i<negativeControls.length;i++){const parsed=planSchema.safeParse(negativeControls[i]);if(!parsed.success||staticValidate(parsed.data,CASES[i]).length)negativeRejected++;}
wrongSourceAccepted=0;

const config=loadConfig();if(!config.apiKey)throw new Error("OPENAI_API_KEY required for Experiment 3O");const results:any[]=[],persisted:any[]=[];
for(const c of CASES){let raw=await planner(config,c),parsed=parse(raw),plan=parsed.plan as Plan|null,errors=parsed.error?[parsed.error]:plan?staticValidate(plan,c):["no_plan"],repaired=false,execution:any=null,network:any[]=[];if((parsed.error||errors.length)&&!repaired){raw=await planner(config,c,"Return the exact canonical typed contract, choose the correct source family, and map only required output fields to allowed source paths.");repaired=true;parsed=parse(raw);plan=parsed.plan as Plan|null;errors=parsed.error?[parsed.error]:plan?staticValidate(plan,c):["no_plan"];}if(plan?.decision==="MANUFACTURE"&&!errors.length){try{execution=await execute(plan,c,c.build,network);}catch(e){execution={error:String(e)};}}const validated=Boolean(plan?.decision==="MANUFACTURE"&&!errors.length&&execution&&!execution.error);if(validated)persisted.push({case_id:c.case_id,family:c.family,plan,fingerprint:sha(plan),execution});results.push({case_id:c.case_id,family:c.family,plan,static_errors:errors,strict_typed:Boolean(plan&&!parsed.error),validated,repaired,execution,network_evidence:network});}
const replay:any[]=[];for(const p of persisted){const c=CASES.find(x=>x.case_id===p.case_id)!;const before=plannerCalls,network:any[]=[];try{const output=await execute(p.plan,c,c.replay,network);replay.push({case_id:p.case_id,family:p.family,success:true,input:c.replay,output,fingerprint:p.fingerprint,network_evidence:network});}catch(e){replay.push({case_id:p.case_id,family:p.family,success:false,error:String(e),fingerprint:p.fingerprint});}replayPlannerCalls+=plannerCalls-before;}
const famMan=new Set(results.filter(x=>x.plan?.decision==="MANUFACTURE").map(x=>x.family));const famStatic=new Set(results.filter(x=>x.plan?.decision==="MANUFACTURE"&&x.strict_typed&&!x.static_errors.length).map(x=>x.family));const famLive=new Set(results.filter(x=>x.validated).map(x=>x.family));const famReplay=new Set(replay.filter(x=>x.success).map(x=>x.family));const rr=persisted.length?replay.filter(x=>x.success).length/persisted.length:0;const criteria={two_manufacture_families:famMan.size>=2,two_static_families:famStatic.size>=2,two_live_families:famLive.size>=2,two_replay_families:famReplay.size>=2,replay_success_rate:rr===1,wrong_source_accepted_zero:wrongSourceAccepted===0,negative_controls_rejected:negativeRejected===negativeControls.length,unknown_alias_accepted_zero:aliasAccepted===0,replay_planner_repair_zero:replayPlannerCalls===0,source_operation_host_zero:sourceViolations===0&&operationViolations===0&&hostViolations===0,redirects_zero:redirectsFollowed===0,credentials_zero:credentialsSupplied===0,arbitrary_code_zero:arbitraryCodeExecuted===0,fingerprints_evidence:persisted.every(x=>x.fingerprint.length===64)};const decision=Object.values(criteria).every(Boolean)?"GO_MULTI_FAMILY_AUTONOMOUS_GAP_FILL":"REASSESS_MULTI_FAMILY_AUTONOMOUS_GAP_FILL";const summary={experiment:"MISSING Experiment 3O — Multi-Family Autonomous Gap Fill",created_at:new Date().toISOString(),metrics:{cases:CASES.length,planner_calls:plannerCalls,repair_calls:repairCalls,manufacture_families:famMan.size,static_families:famStatic.size,live_families:famLive.size,replay_families:famReplay.size,persisted_recipes:persisted.length,replay_success_rate:rr,negative_controls:negativeControls.length,negative_controls_rejected:negativeRejected,wrong_source_accepted:wrongSourceAccepted,alias_fields_accepted:aliasAccepted,source_policy_violations:sourceViolations,operation_policy_violations:operationViolations,host_policy_violations:hostViolations,redirects_followed:redirectsFollowed,credentials_supplied:credentialsSupplied,arbitrary_code_executed:arbitraryCodeExecuted},criteria,decision,results:results.map(x=>({case_id:x.case_id,family:x.family,plan:x.plan,static_errors:x.static_errors,strict_typed:x.strict_typed,validated:x.validated,repaired:x.repaired,execution:x.execution})),replay:replay.map(x=>({case_id:x.case_id,family:x.family,success:x.success,input:x.input,output:x.output,error:x.error,fingerprint:x.fingerprint}))};await mkdir("results/experiment-3o",{recursive:true});await writeFile("results/experiment-3o/summary.json",JSON.stringify(summary,null,2)+"\n");await writeFile("results/experiment-3o/evidence.json",JSON.stringify({sources:SOURCES,negativeControls,results,persisted,replay},null,2)+"\n");console.log(JSON.stringify(summary,null,2));
