import {createHash} from "node:crypto";
import {isIP} from "node:net";
import {runNegativeControls as run3sControls,type SupplierCandidate} from "./experiment3sCore.js";
import type {CaseDef} from "./experiment3qCore.js";

export const PUBLIC_APIS_URL="https://raw.githubusercontent.com/public-apis/public-apis/master/README.md";
export const MCP_REGISTRY_URL="https://registry.modelcontextprotocol.io/v0.1/servers?version=latest&limit=100";
export const STANDARD_SPEC_PATHS=["/openapi.json","/swagger.json","/api/openapi.json","/v3/api-docs","/.well-known/openapi.json"] as const;
export const PUBLIC_APIS_TOP_K=12,MCP_MAX_SERVERS=30,MCP_MAX_EXECUTIONS=8;
export type PublicApiEntry={name:string;description:string;auth:string;https:string;cors:string;link:string;category:string;score:number};
export type McpCandidate={name:string;namespace:string;url:string;transport:"streamable-http"|"sse"};

export const sha=(x:any)=>createHash("sha256").update(typeof x==="string"?x:JSON.stringify(x)).digest("hex");
function words(s:string){return (String(s).toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>=2);}
function affinity(a:string,b:string){const q=words(a),d=new Set(words(b));let n=0;for(const w of q)if(d.has(w))n+=2;else if([...d].some(x=>w.length>=4&&x.length>=4&&(w.includes(x)||x.includes(w))))n+=1;return n;}

export function parsePublicApis(md:string):PublicApiEntry[]{
  const out:PublicApiEntry[]=[],lines=md.split(/\r?\n/);let category="";
  for(const line of lines){const h=line.match(/^###\s+(.+?)\s*$/);if(h){category=h[1].trim();continue;}if(!line.startsWith("| ["))continue;const cells=line.split("|").slice(1,-1).map(x=>x.trim());if(cells.length<5)continue;const m=cells[0].match(/^\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/);if(!m)continue;out.push({name:m[1],link:m[2],description:cells[1]||"",auth:(cells[2]||"").replace(/`/g,""),https:cells[3]||"",cors:cells[4]||"",category,score:0});}
  return out;
}
export function rankPublicApis(c:CaseDef,entries:PublicApiEntry[]){const query=`${c.intent} ${c.input_names.join(" ")} ${c.required_output_leaf_names.join(" ")}`;return entries.map(e=>({...e,score:affinity(query,`${e.name} ${e.description} ${e.category}`)})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,PUBLIC_APIS_TOP_K);}
export function publicApiEligible(e:PublicApiEntry){return /^yes$/i.test(e.https)&&e.link.startsWith("https://");}
export function standardProbeUrl(link:string,path:string){if(!STANDARD_SPEC_PATHS.includes(path as any))throw new Error("probe_path_not_allowed");const u=new URL(link);if(u.protocol!=="https:"||isIP(u.hostname))throw new Error("catalog_origin_not_public_https");return `${u.protocol}//${u.host}${path}`;}
export function isOpenApiLike(x:any){return Boolean(x&&typeof x==="object"&&!Array.isArray(x)&&(typeof x.openapi==="string"||typeof x.swagger==="string")&&x.paths&&typeof x.paths==="object");}

function namespaceOf(name:string){return name.includes("/")?name.split("/")[0]:name.includes(":")?name.split(":")[0]:name;}
function normalizeRemoteType(x:any){return String(x?.type??x?.transport??"").toLowerCase();}
function remoteUrl(x:any){return x?.url??x?.uri??x?.endpoint??null;}
export function literalHeadersOnly(x:any){const h=x?.headers;if(!h)return true;if(Array.isArray(h))return h.length===0||h.every(v=>typeof v?.value==="string"&&!/[${}{]|env:|secret|token/i.test(v.value));if(typeof h==="object")return Object.values(h).every((v:any)=>typeof (typeof v==="string"?v:v?.value)==="string"&&!/[${}{]|env:|secret|token/i.test(typeof v==="string"?v:v?.value));return false;}
export function extractMcpCandidates(body:any):McpCandidate[]{const records=Array.isArray(body)?body:Array.isArray(body?.servers)?body.servers:Array.isArray(body?.data)?body.data:Array.isArray(body?.items)?body.items:[],out:McpCandidate[]=[];for(const raw of records){const s=raw?.server??raw,status=String(raw?.status??s?.status??"active").toLowerCase();if(["deleted","deprecated","inactive"].includes(status))continue;const name=String(s?.name??raw?.name??"");if(!name)continue;for(const rem of s?.remotes??raw?.remotes??[]){const t=normalizeRemoteType(rem),url=remoteUrl(rem);if(!["streamable-http","sse"].includes(t)||typeof url!=="string"||!url.startsWith("https://")||/[{}]/.test(url)||!literalHeadersOnly(rem))continue;out.push({name,namespace:namespaceOf(name),url,transport:t as any});break;}}out.sort((a,b)=>a.name.localeCompare(b.name));const seen=new Set<string>();return out.filter(x=>!seen.has(x.name)&&!!seen.add(x.name));}
const READ=["get","list","read","search","find","lookup","fetch","inspect","describe","status","health","info","view","show","discover","ping"];
const MUTATE=["create","update","delete","remove","send","publish","post","put","patch","upload","write","insert","checkout","purchase","buy","order","pay","transfer","submit","commit","merge","close","cancel","invite","message","email","reply","vote","like","follow","subscribe","deploy","restart","stop","start","set","change","edit","add","execute","run","save","generate","trigger","login","logout","authorize","authenticate","mint"];
function hasWord(text:string,arr:string[]){const n=text.toLowerCase().replace(/[_\-./:]+/g," ");return arr.some(w=>new RegExp(`\\b${w}\\b`,`i`).test(n));}
export function classifyMcpTool(t:any){const reasons:string[]=[];if(!t?.inputSchema||typeof t.inputSchema!=="object"||Array.isArray(t.inputSchema))reasons.push("invalid_input_schema");if(Array.isArray(t?.inputSchema?.required)&&t.inputSchema.required.length>0)reasons.push("required_parameters_present");if(t?.annotations?.readOnlyHint!==true)reasons.push("missing_affirmative_readonly_hint");if(t?.annotations?.destructiveHint===true)reasons.push("destructive_hint_true");const text=`${t?.name??""} ${t?.description??""}`;if(!hasWord(text,READ))reasons.push("no_explicit_read_signal");if(hasWord(text,MUTATE))reasons.push("mutation_signal_present");return {safe:reasons.length===0,reasons};}

export function runNegativeControls(){const controls=[...run3sControls()];const nonHttps:PublicApiEntry={name:"x",description:"",auth:"No",https:"No",cors:"",link:"http://example.com",category:"",score:0};controls.push({control:"public_apis_non_https",executed:true,rejected:!publicApiEligible(nonHttps),evidence:{eligible:publicApiEligible(nonHttps)}});let pathRejected=false;try{standardProbeUrl("https://example.com/docs","/custom-spec.json");}catch{pathRejected=true;}controls.push({control:"public_apis_probe_outside_standard_set",executed:true,rejected:pathRejected,evidence:{path:"/custom-spec.json"}});controls.push({control:"non_openapi_probe_response",executed:true,rejected:!isOpenApiLike({hello:"world"}),evidence:{predicate:false}});const headerRecord={headers:{Authorization:{value:"${TOKEN}"}}};controls.push({control:"mcp_required_headers",executed:true,rejected:!literalHeadersOnly(headerRecord),evidence:{literal_headers_only:literalHeadersOnly(headerRecord)}});let t:any={name:"read",description:"read info",inputSchema:{type:"object",required:["id"]},annotations:{readOnlyHint:true}};controls.push({control:"mcp_required_input",executed:true,rejected:!classifyMcpTool(t).safe,evidence:classifyMcpTool(t)});t={name:"read",description:"read info",inputSchema:{type:"object"},annotations:{}};controls.push({control:"mcp_missing_readonly",executed:true,rejected:!classifyMcpTool(t).safe,evidence:classifyMcpTool(t)});t={name:"delete_status",description:"delete status",inputSchema:{type:"object"},annotations:{readOnlyHint:true}};controls.push({control:"mcp_mutation_signal",executed:true,rejected:!classifyMcpTool(t).safe,evidence:classifyMcpTool(t)});return controls;}
