import {deriveExperiment4mSource} from "./experiment4mDerivation.js";
function r(s:string,a:string,b:string){if(!s.includes(a))throw new Error(`4n_anchor_missing:${a.slice(0,180)}`);return s.replace(a,b)}
export function deriveExperiment4nSource(source:string){
  let x=deriveExperiment4mSource(source);
  x=r(x,'import {compile4m as compile4ar,project4m as project4ar,scope4m as scope4ar,validate4m as validate4ar,validateProjected4m as validateProjected4ar} from "./experiment4mContract.js";','import {compile4n as compile4ar,project4n as project4ar,scope4n as scope4ar,validate4n as validate4ar,validateProjected4n as validateProjected4ar} from "./experiment4nContract.js";');
  x=r(x,'import {synthesize4m as synthesize4ar} from "./experiment4mPlanner.js";','import {synthesize4n as synthesize4ar} from "./experiment4nPlanner.js";');
  x=r(x,'import {fetchDocTextSafe4M,fetchSpecTextSafe4M,resetAcquisitionCache4M,acquisitionCacheMetrics4M} from "./experiment4mFetch.js";',`import {fetchDocTextSafe4M,fetchSpecTextSafe4M,resetAcquisitionCache4M,acquisitionCacheMetrics4M} from "./experiment4mFetch.js";
import {fetchDocTextSafe4N,fetchSpecTextSafe4N,resetExecutedTraceGraph4N,executedTraceRegistryMetrics4N} from "./experiment4nTrace.js";`);
  x=r(x,'const OUT="results/experiment-4m",MAX_BYTES=FOUR_A_BUDGET.max_bytes;','const OUT="results/experiment-4n",MAX_BYTES=FOUR_A_BUDGET.max_bytes;');
  x=r(x,'queue=[{url:provider.start_url,depth:0}],seen=new Set<string>()','queue=[{url:provider.start_url,depth:0,parent_evidence_ids:[] as string[]}],seen=new Set<string>()');
  x=r(x,'const got=await fetchDocTextSafe4M(provider.start_url,item.url,MAX_BYTES,ledger)','const got=await fetchDocTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"CRAWL",parent_evidence_ids:item.parent_evidence_ids||[]},provider.start_url,item.url,MAX_BYTES,ledger)');
  x=r(x,'queue.push({url:l.target_url,depth:item.depth+1})','queue.push({url:l.target_url,depth:item.depth+1,parent_evidence_ids:[id]})');
  x=r(x,'const got=await fetchSpecTextSafe4M(provider.start_url,url,MAX_BYTES,ledger)','const got=await fetchSpecTextSafe4N({case_id:provider.case_id,provider_candidate_id:provider.candidate_id,stage:"STANDARD_SPEC",parent_evidence_ids:[]},provider.start_url,url,MAX_BYTES,ledger)');
  x=r(x,'async function main(){resetAcquisitionCache4M();await mkdir(OUT,{recursive:true});','async function main(){resetAcquisitionCache4M();resetExecutedTraceGraph4N();await mkdir(OUT,{recursive:true});');

  x=r(x,'acquisitionTraceRequestMutationRejects4m=0;',`acquisitionTraceRequestMutationRejects4m=0,
executedTraceEligible4n=0,executedTraceRejectedAsset4n=0,executedTraceRejectedNavigation4n=0,executedTraceRejectedDocumentation4n=0,executedTraceRejectedAuthLike4n=0,executedTraceRejectedLineage4n=0,executedTraceExactBuildSlots4n=0,executedTraceFamilySlots4n=0,executedTraceDocumentedRoleJoins4n=0,executedTraceDocumentedRoleJoinRejects4n=0,executedTraceEchoSupportedSlots4n=0,executedTraceHypotheses4n=0,executedTraceProbeCalls4n=0,executedTraceProbe2xxJson4n=0,executedTraceDocumentedRoleProbeCalls4n=0,executedTraceDocumentedRoleProbe2xxJson4n=0,executedTraceOriginDriftRejects4n=0,executedTraceRequestMutationRejects4n=0,documentationRouteProbeAttempts4n=0;`);
  x=r(x,'acquisitionTraceProbeCalls4m+=a.acquisitionTraceProbeCalls||0;acquisitionTraceProbe2xxJson4m+=a.acquisitionTraceProbe2xxJson||0;',`acquisitionTraceProbeCalls4m+=a.acquisitionTraceProbeCalls||0;acquisitionTraceProbe2xxJson4m+=a.acquisitionTraceProbe2xxJson||0;executedTraceProbeCalls4n+=a.executedTraceProbeCalls||0;executedTraceProbe2xxJson4n+=a.executedTraceProbe2xxJson||0;executedTraceDocumentedRoleProbeCalls4n+=a.executedTraceDocumentedRoleProbeCalls||0;executedTraceDocumentedRoleProbe2xxJson4n+=a.executedTraceDocumentedRoleProbe2xxJson||0;`);
  x=r(x,'acquisitionTraceHypotheses4m+=sm.acquisitionTraceHypotheses||0;',`acquisitionTraceHypotheses4m+=sm.acquisitionTraceHypotheses||0;executedTraceEligible4n+=sm.executedTraceEligible||0;executedTraceRejectedAsset4n+=sm.executedTraceRejectedAsset||0;executedTraceRejectedNavigation4n+=sm.executedTraceRejectedNavigation||0;executedTraceRejectedDocumentation4n+=sm.executedTraceRejectedDocumentation||0;executedTraceRejectedAuthLike4n+=sm.executedTraceRejectedAuthLike||0;executedTraceRejectedLineage4n+=sm.executedTraceRejectedLineage||0;executedTraceExactBuildSlots4n+=sm.executedTraceExactBuildSlots||0;executedTraceFamilySlots4n+=sm.executedTraceFamilySlots||0;executedTraceDocumentedRoleJoins4n+=sm.executedTraceDocumentedRoleJoins||0;executedTraceDocumentedRoleJoinRejects4n+=sm.executedTraceDocumentedRoleJoinRejects||0;executedTraceEchoSupportedSlots4n+=sm.executedTraceEchoSupportedSlots||0;executedTraceHypotheses4n+=sm.executedTraceHypotheses||0;documentationRouteProbeAttempts4n+=sm.documentationRouteProbeAttempts||0;`);
  x=r(x,'if(v.errors?.includes?.("4m_request_hypothesis_not_in_trace_graph"))validatorGraphMismatchRejects4h++;if(v.errors?.includes?.("4m_trace_origin_drift"))acquisitionTraceOriginDriftRejects4m++;if(v.errors?.includes?.("4m_trace_request_mutation"))acquisitionTraceRequestMutationRejects4m++;',`if(v.errors?.includes?.("4n_request_hypothesis_not_in_trace_graph"))validatorGraphMismatchRejects4h++;if(v.errors?.includes?.("4n_trace_origin_drift"))executedTraceOriginDriftRejects4n++;if(v.errors?.includes?.("4n_trace_request_mutation"))executedTraceRequestMutationRejects4n++;`);
  x=r(x,'if(a.parsed_json?.reason?.startsWith?.("4M_SUCCESSFUL_PROBE_MAPPING_REJECT"))successfulProbeMappingRejects4h++;','if(a.parsed_json?.reason?.startsWith?.("4N_SUCCESSFUL_PROBE_MAPPING_REJECT"))successfulProbeMappingRejects4h++;');

  x=r(x,'controls:controls.length,controls_verified:verifiedControls,benchmark_duration_ms:Date.now()-Date.parse(started_at),...acquisitionCacheMetrics4M()',`controls:controls.length,controls_verified:verifiedControls,benchmark_duration_ms:Date.now()-Date.parse(started_at),...acquisitionCacheMetrics4M(),...executedTraceRegistryMetrics4N()`);
  x=r(x,'acquisitionTraceRequestMutationRejects:acquisitionTraceRequestMutationRejects4m,probeCacheHits:probeCacheHits4l',`acquisitionTraceRequestMutationRejects:acquisitionTraceRequestMutationRejects4m,executedTraceEligible:executedTraceEligible4n,executedTraceRejectedAsset:executedTraceRejectedAsset4n,executedTraceRejectedNavigation:executedTraceRejectedNavigation4n,executedTraceRejectedDocumentation:executedTraceRejectedDocumentation4n,executedTraceRejectedAuthLike:executedTraceRejectedAuthLike4n,executedTraceRejectedLineage:executedTraceRejectedLineage4n,executedTraceExactBuildSlots:executedTraceExactBuildSlots4n,executedTraceFamilySlots:executedTraceFamilySlots4n,executedTraceDocumentedRoleJoins:executedTraceDocumentedRoleJoins4n,executedTraceDocumentedRoleJoinRejects:executedTraceDocumentedRoleJoinRejects4n,executedTraceEchoSupportedSlots:executedTraceEchoSupportedSlots4n,executedTraceHypotheses:executedTraceHypotheses4n,executedTraceProbeCalls:executedTraceProbeCalls4n,executedTraceProbe2xxJson:executedTraceProbe2xxJson4n,executedTraceDocumentedRoleProbeCalls:executedTraceDocumentedRoleProbeCalls4n,executedTraceDocumentedRoleProbe2xxJson:executedTraceDocumentedRoleProbe2xxJson4n,executedTraceConfirmedRecipes,executedTraceDocumentedRoleConfirmedRecipes,executedTraceOriginDriftRejects:executedTraceOriginDriftRejects4n,executedTraceRequestMutationRejects:executedTraceRequestMutationRejects4n,documentationRouteProbeAttempts:documentationRouteProbeAttempts4n,probeCacheHits:probeCacheHits4l`);
  x=r(x,'acquisitionTraceConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4m_executed_trace_")).length;',`acquisitionTraceConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4m_executed_trace_")).length,executedTraceConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_")).length,executedTraceDocumentedRoleConfirmedRecipes=recipes.filter(r=>String(r.active_schema_proof?.request_proof_type||"").startsWith("4n_executed_trace_documented_role_")).length;`);
  x=r(x,'acquisition_trace_confirmed_recipe:acquisitionTraceConfirmedRecipes>=1,duplicate_probe_network_fetches_zero:duplicateProbeNetworkFetches4l===0,',`executed_trace_confirmed_recipe:executedTraceConfirmedRecipes>=1,executed_trace_documented_role_confirmed_recipe:executedTraceDocumentedRoleConfirmedRecipes>=1,documentation_route_probe_attempts_zero:documentationRouteProbeAttempts4n===0,confirmed_trace_origin_drift_zero:executedTraceOriginDriftRejects4n===0,confirmed_trace_request_mutation_zero:executedTraceRequestMutationRejects4n===0,duplicate_probe_network_fetches_zero:duplicateProbeNetworkFetches4l===0,`);

  x=x.replaceAll('4M_EXECUTED_ACQUISITION_TRACE:','4N_FIRST_CLASS_EXECUTED_TRACE:')
    .replaceAll('4M_SUCCESSFUL_PROBE_MAPPING_REJECT','4N_SUCCESSFUL_PROBE_MAPPING_REJECT')
    .replaceAll('GO_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF','GO_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH')
    .replaceAll('REASSESS_4M_EXECUTED_ACQUISITION_TRACE_OPERATION_PROOF','REASSESS_4N_FIRST_CLASS_EXECUTED_REQUEST_EVIDENCE_GRAPH');
  x=r(x,'experiment:"4M",purpose:"development_executed_acquisition_trace_operation_proof"','experiment:"4N",purpose:"development_first_class_executed_request_evidence_graph"');
  x=r(x,'base_sha:"a936218a82f8c38156dbef516c1271159b1b18c4"','base_sha:"9d30929caec004ef4c5fc2bbf2afa4eafeb4ff26"');
  x=x.replaceAll('./experiment4mPlanner.ts','./experiment4nPlanner.ts').replaceAll('./experiment4mRequest.ts','./experiment4nRequest.ts').replaceAll('./experiment4mContract.ts','./experiment4nContract.ts').replaceAll('./experiment4mDerivation.ts','./experiment4nDerivation.ts');
  x=x.replace('plannerSource=(await readFile(new URL("./experiment4nPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))', 'plannerSource=(await readFile(new URL("./experiment4nPlanner.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nRequest.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nTrace.ts",import.meta.url),"utf8"))+"\\n"+(await readFile(new URL("./experiment4nReference.ts",import.meta.url),"utf8"))');
  return x;
}
