import {mkdir,writeFile} from "node:fs/promises";
import {PUBLIC_APIS_URL} from "./experiment3uCore.js";
import {BLIND_CASES} from "./experiment3yCore.js";
import {RecoveryLedger,derivedSafetyCounters,normalizeTokenText,sha3yr} from "./experiment3yrCore.js";
import {parseRepresentativeYaml,recoveredBroadRetrieveR2,safetyGateFromLedger,singularizeToken,uniqueSemanticTokens,validatePublicHostname} from "./experiment3yr2Core.js";

const OUTDIR="results/experiment-3yr2";
async function main(){await mkdir(OUTDIR,{recursive:true});const started_at=new Date().toISOString(),ledger=new RecoveryLedger();const r=await fetch(PUBLIC_APIS_URL,{headers:{accept:"text/markdown,text/plain"}});if(!r.ok)throw new Error(`catalog_http_${r.status}`);const catalog=await r.text();
 const retrieval=BLIND_CASES.map(c=>{const ranked=recoveredBroadRetrieveR2(c as any,catalog);return {case_id:c.case_id,query_tokens:uniqueSemanticTokens(`${c.intent} ${c.input_names.join(" ")} ${c.required_output_leaf_names.join(" ")}`),top:ranked.slice(0,20).map(x=>({rank:x.lexical_rank,name:x.name,score:x.score,link:x.link})),known_target_ranks:{rest_countries:ranked.find(x=>/rest countries/i.test(x.name))?.lexical_rank??null,pokeapi:ranked.find(x=>/pok[eé]api/i.test(x.name))?.lexical_rank??null,open_brewery:ranked.find(x=>/open brewery/i.test(x.name))?.lexical_rank??null}};});
 const targetRanks={country:retrieval.find(x=>x.case_id==="country_metadata")?.known_target_ranks.rest_countries??null,pokemon:retrieval.find(x=>x.case_id==="pokemon_metadata")?.known_target_ranks.pokeapi??null,brewery:retrieval.find(x=>x.case_id==="brewery_metadata")?.known_target_ranks.open_brewery??null};
 const yaml=parseRepresentativeYaml();const dnsControls:any[]=[];for(const [name,address] of [["loopback","127.0.0.1"],["rfc1918","10.1.2.3"]] as const){const l=new RecoveryLedger(),resolver=async()=>[{address,family:4}] as any;try{await validatePublicHostname("docs.example.com",l,resolver as any);dnsControls.push({name,rejected:false,events:l.events});}catch(e){dnsControls.push({name,rejected:true,error:String(e),events:l.events});}}
 const counters=derivedSafetyCounters(ledger);const gates={unicode_normalization:normalizeTokenText("PokéAPI")==="pokeapi",generic_morphology:singularizeToken("countries")==="country"&&singularizeToken("breweries")==="brewery"&&singularizeToken("abilities")==="ability",query_deduplication:JSON.stringify(uniqueSemanticTokens("country countries country"))===JSON.stringify(["country"]),semantic_retrieval_targets_in_frontier:Object.values(targetRanks).every(x=>typeof x==="number"&&x<=120),representative_yaml_openapi:Boolean(yaml?.paths?.["/resource/{id}"]?.get),private_dns_controls:dnsControls.every(x=>x.rejected),event_derived_safety_gate:safetyGateFromLedger(ledger,counters)};
 const decision=Object.values(gates).every(Boolean)?"GO_3Y_R2_ENGINEERING_RECOVERY":"REASSESS_3Y_R2_ENGINEERING_RECOVERY";const report={experiment:"3Y-R2",purpose:"engineering_recovery_only_not_confirmatory_evidence",started_at,finished_at:new Date().toISOString(),retrieval,targetRanks,yaml:{parsed:Boolean(yaml),operation:Boolean(yaml?.paths?.["/resource/{id}"]?.get)},dnsControls,ledger:{events:ledger.events,fingerprint:ledger.fingerprint()},safety_counters:counters,gates,decision};await writeFile(`${OUTDIR}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));console.log(decision);console.log(`fingerprint=${sha3yr(report)}`);}
main().catch(e=>{console.error(e);process.exitCode=1;});
